(() => {
 'use strict';
 const app=window.CanvasApp,core=window.AudioCore,$=s=>document.querySelector(s);
 let resourceDisplay;
 const resourceDisplayReady=window.CanvasResourceDisplayReady||import('./src/features/local-resource-migration/display-media.mjs');
 const pendingOriginalAudio=node=>!!node?.audio&&(resourceDisplay?resourceDisplay.isOriginalMediaRef(node.audio):/^\s*(?:https?:|[\/\\]{2})/i.test(node.audio));
 async function repairAudio(nodeId){
  const node=app.getState().nodes.find(item=>item.id===nodeId),projectId=app.projectIdentity().id;
  const isCurrent=()=>app.projectIdentity().id===projectId&&app.getState().nodes.includes(node);
  try{const {openNodeAudioRepair}=await import('./src/features/local-resource-migration/node-audio-repair-ui.mjs');if(isCurrent())openNodeAudioRepair({app,nodeId,isCurrent});}
  catch(error){if(isCurrent())app.notify(error.message);}
 }
 const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const icon=name=>window.UI_ICONS[name]||window.UI_ICONS.music;
 const button=(label,name,fn)=>{const b=el('button');b.type='button';b.title=label;b.setAttribute('aria-label',label);if(name)b.innerHTML=icon(name);else b.textContent=label;b.onclick=fn;return b;};
 const panel=el('section','audio-editor');panel.hidden=true;panel.setAttribute('aria-label','音频生成参数');document.body.append(panel);
 let voiceUI=null,voiceChoiceControl=null;const externalVoiceMenus=new Set();
 const voiceUIReady=import('./src/features/audio-voices/menu.mjs').then(module=>voiceUI=module);
 const localVoiceReady=import('./src/features/audio-voices/client.mjs').then(module=>module.createVoiceProvider());
 const defaultVoiceProvider={listVoices:options=>localVoiceReady.then(provider=>provider.listVoices(options)),previewVoice:(voice,options)=>localVoiceReady.then(provider=>provider.previewVoice(voice,options))};
 const players=new Map(),analysis=new Map();let current=null,config=null,pop=null,expanded=false,advanced=false,playing=null,voices=[],voiceProvider=defaultVoiceProvider;
 const preparing=new Set();let generationAction=null,lastGenerationBusy=null;
 import('./src/features/generation-results/action-button.mjs').then(module=>{generationAction=module;updateGenerateState();}).catch(error=>console.error('Audio generation action:',error));
 const generationBusy=id=>preparing.has(id)||!!app.getState().nodes.find(node=>node.id===id)?.pendingOperation||window.GenerationAPI.getJobs().some(job=>job.request.nodeId===id&&(['queued','running'].includes(job.status)||job.applying));
 let decodeContext,popAnchor=null,lastStored=null,popSession=0,popFocusTimer=null,voiceRevision=0;const saveTimers=new Map(),drafts=new Map();
 function writeConfig(id,snapshot){const node=app.getState().nodes.find(n=>n.id===id);if(!node)return;const serialized=JSON.stringify(snapshot);if(current?.id===id)lastStored=serialized;if(JSON.stringify(node.audioConfig||{})!==serialized)app.updateNode(id,{audioConfig:snapshot});}
 function scheduleSave(){const id=current.id,snapshot=structuredClone(config);drafts.set(id,snapshot);clearTimeout(saveTimers.get(id));saveTimers.set(id,setTimeout(()=>{saveTimers.delete(id);drafts.delete(id);writeConfig(id,snapshot);},200));}
 const decode=async src=>{if(!analysis.has(src)){const pending=(async()=>{const url=await window.LocalAssets.url(src),response=await fetch(url);if(!response.ok)throw Error('音频加载失败');decodeContext??=new AudioContext();const buffer=await decodeContext.decodeAudioData(await response.arrayBuffer());return {duration:buffer.duration,peaks:core.peaks(Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),600),sampleRate:buffer.sampleRate};})();analysis.set(src,pending);pending.catch(()=>analysis.delete(src));}return analysis.get(src);};
 const time=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
 function makePlayer(src,nodeId,options={}){
  const wrap=el('div','audio-player'),waveWrap=el('div','audio-wave-wrap'),wave=el('canvas','audio-wave'),controls=el('div','audio-play-controls'),audio=el('audio'),error=el('div','audio-error');error.hidden=true;
  wave.tabIndex=options.seekable===false?-1:0;wave.setAttribute('role',options.seekable===false?'img':'slider');wave.setAttribute('aria-label',options.seekable===false?'音频波形':'音频播放位置');wave.setAttribute('aria-valuemin','0');
  audio.preload='metadata';let data=[],duration=0,dragging=false,resume=false,frame=0,disposed=false;
  function draw(){if(disposed)return;const width=Math.max(1,wave.clientWidth),height=Math.max(1,wave.clientHeight),dpr=devicePixelRatio||1;wave.width=width*dpr;wave.height=height*dpr;const ctx=wave.getContext('2d');ctx.scale(dpr,dpr);const count=Math.max(1,Math.floor(width/13)),progress=duration?audio.currentTime/duration:0;
   for(let i=0;i<count;i++){const from=Math.floor(i*data.length/count),to=Math.max(from+1,Math.floor((i+1)*data.length/count)),peak=data.length?Math.max(...data.slice(from,to)):.05,h=Math.max(6,peak*(height-8)),x=i*13+(width-count*13)/2;ctx.globalAlpha=i/count<=progress?1:.25;const gradient=ctx.createLinearGradient(0,i%2?height:0,0,i%2?0:height);gradient.addColorStop(0,'rgba(153,153,153,.6)');gradient.addColorStop(1,'#fff');ctx.fillStyle=gradient;ctx.beginPath();ctx.roundRect(x,(height-h)/2,8,h,4);ctx.fill();}
   ctx.globalAlpha=1;ctx.fillStyle='#ddd';ctx.fillRect(progress*width,4,1,height-8);wave.setAttribute('aria-valuemax',String(duration));wave.setAttribute('aria-valuenow',audio.currentTime.toFixed(2));wave.setAttribute('aria-valuetext',time(audio.currentTime)+' / '+time(duration));
  }
  const play=button('播放音频','play',async()=>{if(options.interactive===false)return;if(!audio.paused){audio.pause();return;}try{if(playing&&playing!==audio)playing.pause();await audio.play();playing=audio;}catch(e){error.textContent='播放失败：'+e.message;error.hidden=false;}});play.className='audio-play';
  const seek=value=>{if(!duration)return;audio.currentTime=Math.max(0,Math.min(duration,value));draw();};
  controls.append(button('后退 10 秒','rewind10',()=>seek(audio.currentTime-10)),play,button('前进 10 秒','forward10',()=>seek(audio.currentTime+10)));waveWrap.append(wave);wrap.append(waveWrap,controls,audio,error);
  function animate(){draw();if(!audio.paused)frame=requestAnimationFrame(animate);}
  audio.onplay=()=>{play.innerHTML=icon('pause');play.setAttribute('aria-label','暂停音频');cancelAnimationFrame(frame);animate();};audio.onpause=audio.onended=()=>{play.innerHTML=icon('play');play.setAttribute('aria-label','播放音频');cancelAnimationFrame(frame);draw();};audio.onloadedmetadata=()=>{duration=audio.duration;draw();};audio.ontimeupdate=draw;audio.onerror=()=>{error.textContent='音频无法播放，请检查文件格式或重新上传';error.hidden=false;};
  const point=e=>{const r=wave.getBoundingClientRect();return (e.clientX-r.left)/r.width*duration;};
  wave.onpointerdown=e=>{if(options.seekable===false)return;e.preventDefault();dragging=true;resume=!audio.paused;audio.pause();wave.setPointerCapture(e.pointerId);seek(point(e));};wave.onpointermove=e=>{if(dragging)seek(point(e));};wave.onpointerup=wave.onpointercancel=()=>{dragging=false;if(resume)audio.play().catch(()=>{});};wave.onkeydown=e=>{if(options.seekable===false)return;if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();seek(e.key==='Home'?0:e.key==='End'?duration:audio.currentTime+(e.key==='ArrowLeft'?-1:1));}else if(e.code==='Space'){e.preventDefault();play.click();}};
  wrap.onpointerdown=e=>{if(options.dragSurface&&!e.target.closest('button'))return;e.stopPropagation();if(nodeId&&!app.getState().selected.includes(nodeId))app.select(nodeId);};wrap.onkeydown=e=>e.stopPropagation();wrap.ondblclick=e=>e.stopPropagation();
  if(options.interactive===false)controls.querySelectorAll('button').forEach(b=>b.disabled=true);if(options.pauseOnLeave)wrap.onpointerleave=()=>audio.pause();
  const observer=new ResizeObserver(draw);observer.observe(wave);
  window.LocalAssets.url(src).then(url=>{if(!disposed)audio.src=url;}).catch(e=>{error.textContent=e.message;error.hidden=false;});
  decode(src).then(value=>{if(disposed)return;data=value.peaks;duration=value.duration;wrap.dataset.waveform='decoded';draw();}).catch(e=>{error.textContent='波形解析失败：'+e.message;error.hidden=false;});
  return {wrap,audio,dispose(){disposed=true;audio.pause();audio.removeAttribute('src');audio.load();observer.disconnect();cancelAnimationFrame(frame);}};
 }
 async function localize(src){if(src.startsWith('asset:'))return src;const response=await fetch(src);if(!response.ok)throw Error('生成音频下载失败');const blob=await response.blob();if(!blob.size||blob.size>50*1024*1024)throw Error('生成音频为空或超过50MB');const url=URL.createObjectURL(blob);try{await decode(url);}finally{URL.revokeObjectURL(url);analysis.delete(url);}return window.LocalAssets.put(blob);}
 async function upload(node){const input=el('input');input.type='file';input.accept='.mp3,.wav,.ogg,.m4a,.aac,.flac,.webm,audio/*';input.onchange=async()=>{const file=input.files[0];if(!file)return;try{core.validateFile(file);const url=URL.createObjectURL(file);let meta;try{meta=await decode(url);}finally{URL.revokeObjectURL(url);analysis.delete(url);}const asset=await window.LocalAssets.put(file);app.updateNode(node.id,{audio:asset,audioMode:'upload',title:file.name,audioDuration:meta.duration,width:300,height:300});}catch(e){window.NodeActions.notify(e.message);}};input.click();}
 function preview(node){const d=el('dialog','audio-preview'),header=el('header'),player=makePlayer(node.audio);header.append(el('strong','',node.title),button('关闭音频预览','close',()=>d.close()));d.append(header,player.wrap);document.body.append(d);d.onclose=()=>{player.dispose();d.remove();};d.showModal();}
 async function download(node){try{const url=await window.LocalAssets.url(node.audio),blob=await(await fetch(url)).blob(),ext=blob.type.includes('wav')?'wav':blob.type.includes('ogg')?'ogg':blob.type.includes('webm')?'webm':'mp3';window.LocalMedia.download(blob,/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(node.title)?node.title:node.title+'.'+ext);}catch(e){window.NodeActions.notify(e.message);}}
 function persist(){if(!current)return;const id=current.id;clearTimeout(saveTimers.get(id));saveTimers.delete(id);drafts.delete(id);writeConfig(id,structuredClone(config));}
 function liveAnchor(anchor){if(anchor?.isConnected)return anchor;const label=anchor?.getAttribute('aria-label');return label?Array.from(panel.querySelectorAll('button')).find(b=>b.getAttribute('aria-label')===label):null;}
 function closePop(restoreFocus=false){voiceChoiceControl?.dispose();voiceChoiceControl=null;clearTimeout(popFocusTimer);popFocusTimer=null;const anchor=liveAnchor(popAnchor);popSession++;pop?.remove();pop=null;popAnchor=null;anchor?.setAttribute('aria-expanded','false');anchor?.removeAttribute('aria-controls');if(restoreFocus&&!panel.hidden&&anchor?.isConnected&&!anchor.disabled)anchor.focus({preventScroll:true});}
 function ownsPop(p){return pop===p&&p.isConnected&&!panel.hidden&&current?.id===p.dataset.nodeId;}
 function focusPop(p,key){if(!ownsPop(p))return;const controls=Array.from(p.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)'));const target=controls.find(b=>key&&b.dataset.focusKey===key)||controls.find(b=>b.getAttribute('aria-checked')==='true')||controls[0]||p;target.focus({preventScroll:true});}
 function popKey(event){if(!pop||event.defaultPrevented||event.isComposing||event.keyCode===229||!pop.contains(event.target)&&!popAnchor?.contains(event.target))return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closePop(true);return;}if(pop.getAttribute('role')!=='menu'||!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;const items=Array.from(pop.querySelectorAll('[role="menuitemradio"]:not(:disabled)'));if(!items.length)return;event.preventDefault();event.stopPropagation();let i=items.indexOf(document.activeElement);i=event.key==='Home'?0:event.key==='End'?items.length-1:(i+(event.key==='ArrowUp'?-1:1)+items.length)%items.length;for(const b of items)b.tabIndex=b===items[i]?0:-1;items[i].focus({preventScroll:true});}
 function popup(anchor,width=313,refresh=false,role='dialog'){if(pop&&popAnchor===anchor&&!refresh){closePop(true);return null;}closePop();popAnchor=anchor;pop=el('div','audio-popover');pop.id='audio-popover-'+popSession;pop.dataset.nodeId=current.id;pop.tabIndex=-1;pop.setAttribute('role',role);pop.setAttribute('aria-label',anchor.getAttribute('aria-label')||'音频选项');anchor.setAttribute('aria-haspopup',role);anchor.setAttribute('aria-expanded','true');anchor.setAttribute('aria-controls',pop.id);pop.style.width=width+'px';document.body.append(pop);const r=anchor.getBoundingClientRect();pop.style.left=Math.max(8,Math.min(innerWidth-width-8,r.left))+'px';pop.dataset.anchorTop=r.top;pop.onpointerdown=e=>e.stopPropagation();pop.onkeydown=e=>{popKey(e);if(e.key!=='Escape')e.stopPropagation();};pop.addEventListener('focusout',()=>{const session=popSession,p=pop;clearTimeout(popFocusTimer);popFocusTimer=setTimeout(()=>{popFocusTimer=null;if(session===popSession&&ownsPop(p)&&!p.contains(document.activeElement)&&!popAnchor?.contains(document.activeElement))closePop();},0);});return pop;}
 function placePop(){if(!pop)return;const anchor=liveAnchor(popAnchor);if(anchor&&anchor!==popAnchor){popAnchor=anchor;anchor.setAttribute('aria-haspopup',pop.getAttribute('role'));anchor.setAttribute('aria-expanded','true');anchor.setAttribute('aria-controls',pop.id);}if(anchor)pop.dataset.anchorTop=anchor.getBoundingClientRect().top;pop.style.top=Math.max(8,Number(pop.dataset.anchorTop)-pop.offsetHeight-8)+'px';}
 function options(container,label,values,value,change){const section=el('div','audio-section'),group=el('div','audio-options');group.setAttribute('role','group');group.setAttribute('aria-label',label);section.append(el('span','',label),group);values.forEach(([v,name])=>{const b=button(name,null,()=>{if(ownsPop(container))change(v);});b.dataset.focusKey=label+':'+String(v);b.classList.toggle('chosen',v===value);b.setAttribute('aria-pressed',String(v===value));group.append(b);});container.append(section);}
 function number(container,label,key,min,max,step=1,slider=false,rate=false){
  const row=el('div','audio-number'),input=el('input'),value=rate?1+(config.params[key]||0)/100:config.params[key]??min;
  input.type=slider?'range':'number';input.min=min;input.max=max;input.step=step;input.value=value;input.setAttribute('aria-label',label);row.append(el('span','',label),input);
  const numeric=slider?el('input'):input;if(slider){numeric.type='number';numeric.min=min;numeric.max=max;numeric.step=step;numeric.value=value;numeric.setAttribute('aria-label',label+'数值');row.append(numeric);}
  const sync=(source,save)=>{const parsed=Number(source.value);if(!source.value||!Number.isFinite(parsed)){if(save){input.value=numeric.value=rate?1+(config.params[key]||0)/100:config.params[key]??min;}return;}const next=Math.max(min,Math.min(max,parsed));input.value=numeric.value=next;if(save){config.params[key]=rate?Math.round((next-1)*100):next;persist();}};
  input.oninput=()=>{if(slider)numeric.value=input.value;};input.onchange=()=>sync(input,true);if(slider)numeric.onchange=()=>sync(numeric,true);container.append(row);
 }
 function sampling(container){const values=[8000,16000,24000,32000,44100,48000],row=el('div','audio-number'),slider=el('input'),select=el('select');slider.type='range';slider.min=0;slider.max=values.length-1;slider.step=1;slider.value=Math.max(0,values.indexOf(config.params.sample_rate));slider.setAttribute('aria-label','采样率');select.setAttribute('aria-label','采样率数值');for(const value of values){const option=el('option','',value+' Hz');option.value=value;select.append(option);}select.value=config.params.sample_rate;slider.oninput=()=>{select.value=values[+slider.value];};slider.onchange=()=>{config.params.sample_rate=values[+slider.value];persist();};select.onchange=()=>{config.params.sample_rate=+select.value;slider.value=values.indexOf(+select.value);persist();};row.append(el('span','','采样率'),slider,select);container.append(row);}
 function changeModel(virtual,scene){const anchor=popAnchor;closePop();advanced=false;const old=config.references.length;config=core.transition(config,virtual,scene);for(const n of referenceNodes())if(!core.compatible(config.model,n.type))app.disconnect(n.id,current.id);persist();draw();liveAnchor(anchor)?.focus({preventScroll:true});if(config.references.length<old)window.NodeActions.notify('已断开当前模型不支持的参考素材');}
 function modelMenu(anchor){const p=popup(anchor,300,false,'menu');if(!p)return;for(const m of core.models){const b=button(m.name,'music',()=>{if(ownsPop(p))changeModel(m.id);});b.append(el('span','',m.name));b.classList.toggle('chosen',m.id===config.virtualModel);b.setAttribute('role','menuitemradio');b.setAttribute('aria-checked',String(m.id===config.virtualModel));b.tabIndex=m.id===config.virtualModel?0:-1;p.append(b);}placePop();focusPop(p);}
 function sceneMenu(anchor){const p=popup(anchor,220,false,'menu');if(!p)return;const entry=core.models.find(m=>m.id===config.virtualModel);for(const scene of Object.keys(entry.scenes)){const b=button(core.scenes[scene],'music',()=>{if(ownsPop(p))changeModel(config.virtualModel,scene);});b.append(el('span','',core.scenes[scene]));b.setAttribute('role','menuitemradio');b.setAttribute('aria-checked',String(scene===config.scene));b.tabIndex=scene===config.scene?0:-1;p.append(b);}placePop();focusPop(p);}
 function parameters(anchor,refresh=false){const focusKey=refresh&&pop?.contains(document.activeElement)?document.activeElement.dataset.focusKey:null;const p=popup(anchor,config.model==='music_v1'?340:313,refresh);if(!p)return;const spec=core.specs[config.model];
  const redraw=()=>{persist();draw();parameters(anchor.isConnected?anchor:panel.querySelector('[aria-label="音频参数"]'),true);};
  if(spec.lyrics){options(p,'歌词',[['auto','自动'],['custom','自定义'],...(spec.instrumental?[['instrumental','纯音乐']]:[])],config.params.force_instrumental?'instrumental':config.params.lyric_mode?'custom':'auto',v=>{config.params.lyric_mode=v==='custom';config.params.force_instrumental=v==='instrumental';redraw();});}
  if(spec.video&&referenceNodes().some(n=>n.type==='video')){p.append(el('p','audio-status','时长自动匹配参考视频'));}else if(spec.duration){const d=spec.duration,scale=d.scale||1;options(p,'时长',d.presets.map(v=>[v,v===null?'自动':v+'s']),config.params[d.key]==null?null:config.params[d.key]/scale,v=>{if(v===null)delete config.params[d.key];else config.params[d.key]=v*scale;redraw();});const label=el('label','audio-number'),input=el('input');input.type='number';input.min=d.min;input.max=d.max;input.step=.1;input.value=config.params[d.key]==null?'':config.params[d.key]/scale;input.setAttribute('aria-label','自定义音频时长');input.dataset.focusKey='duration:custom';input.onchange=()=>{if(!ownsPop(p))return;config.params[d.key]=Math.max(d.min,Math.min(d.max,+input.value))*scale;persist();draw();};label.append(el('span','','自定义（秒）'),input);p.append(label);}
  if(config.scene==='Sound'&&config.model==='eleven_sound_effect')options(p,'循环',[[true,'开启'],[false,'关闭']],config.params.loop,v=>{config.params.loop=v;redraw();});
  if(config.model==='doubao-seed-audio-1-0'){options(p,'字幕',[[true,'开启'],[false,'关闭']],config.params.enable_subtitle,v=>{config.params.enable_subtitle=v;redraw();});options(p,'输出格式',[['wav','WAV'],['mp3','MP3'],['ogg_opus','OGG OPUS']],config.params.format,v=>{config.params.format=v;redraw();});}
  placePop();focusPop(p,focusKey);
 }
 function mountVoiceChoices(p,options){
  let child=null,disposed=false;const pending=el('p','audio-status','加载音色…');p.append(pending);
  const mount=module=>{if(disposed||!p.isConnected||!options.isCurrent())return;pending.remove();child=module.createVoiceChoices(p,options);};
  if(voiceUI)mount(voiceUI);else voiceUIReady.then(mount).catch(error=>{if(!disposed&&p.isConnected)pending.textContent='音色菜单加载失败：'+error.message;});
  return {dispose(){disposed=true;child?.dispose();}};
 }
 async function listVoices(options={}){
  const provider=voiceProvider,revision=voiceRevision;
  if(provider){const value=await provider.listVoices(options);if(options.signal?.aborted)throw options.signal.reason||new DOMException('已取消','AbortError');if(provider===voiceProvider&&revision===voiceRevision){const state=Array.isArray(value)?{voices:value,configured:true}:value;if(!Array.isArray(state?.voices))throw Error('音色目录格式无效');voices=state.voices;return {...state,voices:structuredClone(voices)};}}
  return {voices:structuredClone(voices),configured:!!voiceProvider||voices.length>0};
 }
 function previewVoice(voice,options){if(!voiceProvider?.previewVoice)throw Error('当前音色服务未提供真实试听');return voiceProvider.previewVoice(voice,options);}
 function voiceMenu(anchor){
  const p=popup(anchor,300);if(!p)return;const provider=voiceProvider,revision=voiceRevision,nodeId=current.id,session=popSession;
  const active=()=>ownsPop(p)&&current?.id===nodeId&&voiceProvider===provider&&voiceRevision===revision&&popSession===session;
  voiceChoiceControl=mountVoiceChoices(p,{listVoices,previewVoice,model:config.model,value:config.params.voice_id,initialVoices:voices,isCurrent:active,onLayout:placePop,onSelect:id=>{if(!active())return;config.params.voice_id=id;persist();draw();closePop(true);}});placePop();
 }
 function openVoiceMenu(trigger,options={}){
  const p=el('div','agent-generation-menu is-voice audio-popover');p.setAttribute('role','dialog');p.setAttribute('aria-label','音色');p.tabIndex=-1;document.body.append(p);let closed=false,choices=null;const control={close};externalVoiceMenus.add(control);
  const active=()=>!closed&&trigger.isConnected&&(options.isCurrent?.()??true),position=()=>{if(!active())return close();const r=trigger.getBoundingClientRect();p.style.width='300px';p.style.left=Math.max(8,Math.min(innerWidth-308,r.left))+'px';p.style.top=Math.max(8,Math.min(innerHeight-p.offsetHeight-8,r.bottom+8))+'px';};
  function close(focus=false){if(closed)return;closed=true;choices?.dispose();p.remove();trigger.setAttribute('aria-expanded','false');document.removeEventListener('pointerdown',outside,true);document.removeEventListener('scroll',position,true);window.removeEventListener('resize',position);window.removeEventListener('blur',close);window.removeEventListener('pagehide',close);document.removeEventListener('focusin',outside,true);externalVoiceMenus.delete(control);options.onClose?.();if(focus===true&&trigger.isConnected)trigger.focus({preventScroll:true});}
  function outside(event){if(!p.contains(event.target)&&!trigger.contains(event.target))close();}
  p.onkeydown=event=>{event.stopPropagation();if(event.key==='Escape'&&!event.isComposing){event.preventDefault();close(true);}};
  choices=mountVoiceChoices(p,{...options,listVoices:options.listVoices||listVoices,previewVoice:options.previewVoice||previewVoice,isCurrent:active,onLayout:position,onSelect:id=>{if(!active())return;close(true);options.onSelect?.(id);}});trigger.setAttribute('aria-expanded','true');position();if(!p.querySelector('input'))p.focus({preventScroll:true});
  document.addEventListener('pointerdown',outside,true);document.addEventListener('scroll',position,true);window.addEventListener('resize',position);window.addEventListener('blur',close);window.addEventListener('pagehide',close);document.addEventListener('focusin',outside,true);return control;
 }

 function referenceNodes(){const state=app.getState(),refs=config.references.map(r=>state.nodes.find(n=>n.id===r.id)).filter(Boolean);for(const e of state.edges.filter(e=>e.target===current.id)){const n=state.nodes.find(n=>n.id===e.source);if(n&&!refs.some(r=>r.id===n.id))refs.push(n);}return refs;}
 function refsForRequest(){return referenceNodes().map(n=>({id:n.id,type:n.type,url:n.type==='audio'?n.audio:n.type==='video'?n.video:n.fullImage||n.image,text:n.content,title:n.title}));}
 function picker(anchor){const p=popup(anchor,320);if(!p)return;const search=el('input'),list=el('div','audio-reference-picker');search.type='search';search.placeholder='搜索画布素材';search.setAttribute('aria-label','搜索画布参考素材');p.append(search,list);function show(){if(!ownsPop(p))return;list.replaceChildren();for(const n of app.getState().nodes.filter(n=>n.id!==current.id&&core.compatible(config.model,n.type)&&n.title.toLowerCase().includes(search.value.toLowerCase()))){const b=button(n.title,null,()=>{if(!ownsPop(p))return;if(!config.references.some(r=>r.id===n.id))config.references.push({id:n.id,type:n.type});persist();draw();closePop(true);});if(n.image){const i=el('img');i.src=n.image;b.prepend(i);}b.append(el('small','',n.type));list.append(b);}}search.oninput=show;show();placePop();focusPop(p);}
 async function buildRequest(nodeId,overrides={}){
  const state=app.getState(),node=state.nodes.find(n=>n.id===nodeId);if(!node)throw Error('来源节点不存在');let target=core.transition(node.audioConfig||{});
  const agentAudio=overrides.kind==='audio.generate'?await import('./src/features/agent-generation/audio.mjs'):null;
  if(agentAudio)target=agentAudio.audioRequestConfig(core,node.audioConfig||{},overrides);
  if(!agentAudio&&overrides.model){const entry=core.models.find(m=>m.id===overrides.model||Object.values(m.scenes).includes(overrides.model));if(!entry)throw Error('请选择音频目录中的模型，由接口适配器映射到供应商模型');const scene=Object.entries(entry.scenes).find(([,wire])=>wire===overrides.model)?.[0]||target.scene;target=core.transition(target,entry.id,scene);}
  if(overrides.prompt!==undefined)target.prompt=overrides.prompt;const spec=core.specs[target.model];if(!agentAudio&&overrides.duration!==undefined){if(!spec.duration)throw Error('当前音频模型不支持指定时长');target.params[spec.duration.key]=overrides.duration*(spec.duration.scale||1);}
  const ids=overrides.referenceIds||[...target.references.map(r=>r.id),...state.edges.filter(e=>e.target===nodeId).map(e=>e.source)];
  const refs=[...new Set(ids)].map(id=>{const n=state.nodes.find(n=>n.id===id);if(!n)throw Error('参考素材已不存在');return {id:n.id,type:n.type,url:n.type==='audio'?n.audio:n.type==='video'?n.video:n.fullImage||n.image,text:n.content,title:n.title};});
  for(const ref of refs){if(!ref.url&&!ref.text)throw Error('参考素材尚未上传内容');if(ref.type==='video'&&spec.video){const video=document.createElement('video');video.preload='metadata';try{ref.duration=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('参考视频时长读取超时')),10000);video.onloadedmetadata=()=>{clearTimeout(timeout);resolve(video.duration);};video.onerror=()=>{clearTimeout(timeout);reject(Error('参考视频无法读取'));};window.LocalAssets.url(ref.url).then(url=>{video.src=url;}).catch(error=>{clearTimeout(timeout);reject(error);});});}finally{video.removeAttribute('src');video.load();}target.params.duration=ref.duration;}
   if(ref.url?.startsWith('asset:')){const url=await window.LocalAssets.url(ref.url),blob=await(await fetch(url)).blob();ref.url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}}
  if(agentAudio)agentAudio.validateAudioDraft(agentAudio.createAudioDraft(overrides,[node]),refs.map(ref=>({...ref,content:ref.text})));
  const prompt=core.validate(target,refs);return {kind:'audio.generate',label:core.scenes[target.scene]+'生成',nodeId,prompt,inputs:refs,parameters:{...target.params,model:target.model,scene:target.scene,virtualModel:target.virtualModel}};
 }
 async function generate(){const id=current?.id;if(!id||generationBusy(id))return;preparing.add(id);updateGenerateState();try{persist();return await window.GenerationAPI.submit(await buildRequest(id));}catch(e){if(current?.id===id){const status=panel.querySelector('.audio-status');if(status)status.textContent=e.message;}}finally{preparing.delete(id);updateGenerateState();}}

 function draw(){panel.replaceChildren();panel.classList.toggle('expanded',expanded);const refs=el('div','audio-references');refs.append(button('选择参考素材','cursor',e=>picker(e.currentTarget)));for(const n of referenceNodes()){const b=button('移除参考 '+n.title,null,()=>{config.references=config.references.filter(r=>r.id!==n.id);const edges=app.getState().edges.filter(e=>e.source===n.id&&e.target===current.id);if(edges.length)app.disconnect(n.id,current.id);persist();draw();});b.textContent=n.title;refs.append(b);}refs.append(button('添加参考素材','plus',e=>picker(e.currentTarget)));panel.append(refs);
  const prompt=el('textarea','audio-prompt');prompt.setAttribute('aria-label','音频生成提示词');prompt.placeholder=config.scene==='Music'?'描述您想要的音乐':config.scene==='Sound'?'描述你想要生成的音效':'输入想要转换为语音的文本';prompt.value=config.prompt;prompt.oninput=()=>{config.prompt=prompt.value;scheduleSave();updateGenerateState();};prompt.onchange=persist;const expand=button(expanded?'缩小提示词':'放大提示词',expanded?'collapse':'expand',()=>{expanded=!expanded;draw();position();});expand.className='audio-expand';panel.append(prompt,expand);
  const spec=core.specs[config.model];if(spec.lyrics&&config.params.lyric_mode&&!config.params.force_instrumental){const area=el('div','audio-lyrics'),text=el('textarea');text.placeholder='在此输入或粘贴歌词...';text.setAttribute('aria-label','歌词');text.value=config.params.lyrics||'';text.oninput=()=>{config.params.lyrics=text.value;scheduleSave();updateGenerateState();};text.onchange=persist;area.append(text);panel.append(area);}
  const status=el('p','audio-status'),footer=el('div','audio-footer');panel.append(status,footer);const trigger=(label,ico,fn,display)=>{const b=button(label,ico,e=>fn(e.currentTarget));if(display)b.append(el('span','',display));footer.append(b);};trigger('选择音频模型','music',modelMenu,core.models.find(m=>m.id===config.virtualModel).name);if(Object.keys(core.models.find(m=>m.id===config.virtualModel).scenes).length>1){footer.append(el('span','audio-separator'));trigger('选择音频场景','speaker',sceneMenu,core.scenes[config.scene]);}
  if(spec.voice)trigger('选择音色','user',voiceMenu,voices.find(v=>v.id===config.params.voice_id)?.name||'音色');
  if(spec.lyrics||spec.duration||config.model==='doubao-seed-audio-1-0'){const duration=spec.duration,key=duration?.key,label=spec.video&&referenceNodes().some(n=>n.type==='video')?'跟随视频':config.model==='doubao-seed-audio-1-0'?config.params.format.toUpperCase():duration&&config.params[key]!=null?config.params[key]/(duration.scale||1)+'s':config.params.force_instrumental?'纯音乐':config.params.lyric_mode?'自定义':'自动';trigger('音频参数','settings',parameters,label);}
  if(['doubao-seed-audio-1-0','eleven_v3','eleven_sound_effect'].includes(config.model))trigger('音频高级设置','gear',()=>{closePop();advanced=!advanced;draw();});const mic=button('语音输入','mic');footer.append(mic);const voiceNodeId=current.id;window.VoiceInput.bind(mic,{target:prompt,getValue:()=>prompt.value,setValue:value=>{prompt.value=value;config.prompt=value;persist();updateGenerateState();},isCurrent:()=>current?.id===voiceNodeId,mount:footer});const send=button('生成音频','arrow',generate);send.className='audio-generate generate-trigger';footer.append(send);
  if(advanced){const box=el('div','audio-advanced');if(config.model==='doubao-seed-audio-1-0'){sampling(box);number(box,'语速','speech_rate',.5,2,.01,true,true);number(box,'声调','pitch_rate',-12,12,1,true);number(box,'音量','loudness_rate',.5,2,.01,true,true);}else if(config.model==='eleven_v3')number(box,'稳定性','stability',0,1,.5,true);else if(config.model==='eleven_sound_effect')number(box,'提示词影响度','prompt_influence',0,1,.01,true);panel.append(box);}for(const b of panel.querySelectorAll('button')){const label=b.getAttribute('aria-label');if(['选择音频模型','选择音频场景','选择音色','音频参数','选择参考素材','添加参考素材'].includes(label)){b.setAttribute('aria-haspopup',['选择音频模型','选择音频场景'].includes(label)?'menu':'dialog');b.setAttribute('aria-expanded','false');}}updateGenerateState();position();
 }
 function updateGenerateState(){const send=panel.querySelector('.audio-generate');if(!send||!current)return;const busy=generationBusy(current.id);lastGenerationBusy=busy;let reason='';try{core.validate(config,refsForRequest());}catch(e){reason=e.message;}send.disabled=busy||!!reason;send.title=reason||(busy?'音频生成中，请等待当前任务完成或取消':'生成音频');panel.setAttribute('aria-busy',String(busy));generationAction?.updateGenerationAction(send,{busy,disabled:send.disabled,label:'生成音频'});}
 function position(){if(panel.hidden||!current)return;const view=app.getState().view,r=$('#canvas').getBoundingClientRect(),width=Math.min(650,r.width-24);panel.style.width=width+'px';panel.style.left=Math.max(r.left+12,Math.min(r.right-width-12,r.left+view.x+(current.x+current.width/2)*view.scale-width/2))+'px';const bottom=r.top+view.y+(current.y+current.height)*view.scale;panel.style.top=Math.max(72,Math.min(innerHeight-panel.offsetHeight-12,bottom+12))+'px';placePop();}
 function positionToolbar(state){if(!current)return;const bar=$('#node-toolbar'),rect=$('#canvas').getBoundingClientRect(),center=rect.left+state.view.x+(current.x+current.width/2)*state.view.scale;bar.style.left=Math.max(rect.left+10,Math.min(rect.right-bar.offsetWidth-10,center-bar.offsetWidth/2))+'px';}
 const audioBodies=new WeakMap();let audioToolbar=null;
 function syncToolbar(n){
  const bar=$('#node-toolbar'),hasAudio=!!n.audio;
  if(audioToolbar?.bar===bar&&audioToolbar.id===n.id&&audioToolbar.hasAudio===hasAudio&&bar.children.length===audioToolbar.buttons.length&&audioToolbar.buttons.every((button,index)=>bar.children[index]===button))return;
  const record={bar,id:n.id,hasAudio,buttons:[]};audioToolbar=record;
  const actions=[['Pin','tag',(node,b)=>window.NodeActions.colors(node,b)],...(hasAudio?[['下载音频','download',node=>download(node)],['保存到素材库','folder',()=>app.saveSelection()],['预览音频','expand',node=>preview(node)]]:[])];
  for(const [label,ico,action]of actions){const b=button(label,ico,()=>{
   // The toolbar survives movement and node replacement; resolve the live node
   // on activation instead of retaining a stale media source in its closure.
   if(audioToolbar!==record||b.parentNode!==bar||!bar.isConnected)return;
   const state=app.getState();if(state.selected.length!==1||state.selected[0]!==record.id)return;
   const node=state.nodes.find(item=>item.id===record.id);if(!node||node.type!=='audio'||label!=='Pin'&&!node.audio)return;
   action(node,b);
  });b.className='icon-btn';record.buttons.push(b);}
  bar.replaceChildren(...record.buttons);
 }

 function reconcilePlayers(state){
  const byId=players.size?new Map():null,audioNodes=[],bodies=new Map();
  for(const node of state.nodes){if(byId){const id=node.id;if(!byId.has(id))byId.set(id,node);}if(node.type==='audio')audioNodes.push(node);}
  function bodyFor(id){
   if(bodies.has(id))return bodies.get(id);
   let body;
   if(app.getNodeElement){
    const shell=app.getNodeElement(id);
    if(shell){body=audioBodies.get(shell);if(!body||body.parentNode!==shell){body=shell.querySelector('.node-body');if(body)audioBodies.set(shell,body);}}
   }else body=$(`.node[data-id="${id}"] .node-body`);
   bodies.set(id,body);return body;
  }
  // Reconcile each existing player once; dragging another node must not search
  // the full graph and the document separately for every audio instance.
  for(const [id,p]of players){const node=byId.get(id),body=bodyFor(id);if(!node||node.audio!==p.src||pendingOriginalAudio(node)||!p.wrap.isConnected||!body?.contains(p.wrap)){p.dispose();players.delete(id);}}
  for(const n of audioNodes){const body=bodyFor(n.id);if(!body)continue;
   if(pendingOriginalAudio(n)){
    if(!body.querySelector('.audio-source-repair')){const empty=el('div','audio-empty audio-source-repair');empty.append(el('p','','原站音频待导入本地'));const repair=button('导入本地音频',null,()=>repairAudio(n.id));repair.className='audio-upload';repair.onpointerdown=e=>e.stopPropagation();repair.ondblclick=e=>e.stopPropagation();empty.append(repair);body.replaceChildren(empty);}continue;
   }
   if(n.audio){if(!players.has(n.id)){body.replaceChildren();const p=makePlayer(n.audio,n.id);p.src=n.audio;players.set(n.id,p);body.append(p.wrap);const replace=button('替换音频','import',()=>upload(n));replace.className='audio-upload audio-replace';replace.onpointerdown=e=>e.stopPropagation();replace.ondblclick=e=>e.stopPropagation();body.append(replace);}}else if(!body.querySelector('.audio-empty')){const empty=el('div','audio-empty');empty.innerHTML=icon('music');const uploadButton=button('上传本地音频',null,()=>upload(n));uploadButton.className='audio-upload';uploadButton.onpointerdown=e=>e.stopPropagation();empty.append(uploadButton);body.replaceChildren(empty);}}
 }
 function render(event){if(event?.detail?.viewportOnly){position();if(current)positionToolbar(app.getState());return;}const state=app.getState();reconcilePlayers(state);
  const n=state.selected.length===1?state.nodes.find(n=>n.id===state.selected[0]&&n.type==='audio'):null;
  if(!n){current=null;panel.hidden=true;closePop();return;}const changed=current?.id!==n.id,stored=JSON.stringify(n.audioConfig||{}),externalChange=!changed&&stored!==lastStored;current=n;if(changed||externalChange){if(externalChange){clearTimeout(saveTimers.get(n.id));saveTimers.delete(n.id);drafts.delete(n.id);}config=core.transition(drafts.get(n.id)||n.audioConfig||{});lastStored=stored;if(changed)advanced=false;closePop();}
  panel.hidden=n.audioMode==='upload';if(panel.hidden)closePop();if(!panel.hidden){if(changed||externalChange)draw();else{if(generationBusy(n.id)!==lastGenerationBusy)updateGenerateState();position();}}
  syncToolbar(n);positionToolbar(state);
 }
 window.GenerationAPI.subscribe(updateGenerateState);
 resourceDisplayReady.then(policy=>{resourceDisplay=policy;render();}).catch(error=>console.error('Audio media policy:',error));
 panel.onpointerdown=e=>{if(pop&&!pop.contains(e.target)&&!popAnchor?.contains(e.target))closePop();e.stopPropagation();};panel.onkeydown=e=>{popKey(e);if(e.key!=='Escape')e.stopPropagation();};const dismissOutside=e=>{if(pop&&!pop.contains(e.target)&&!popAnchor?.contains(e.target))closePop();};document.addEventListener('pointerdown',dismissOutside);document.addEventListener('focusin',dismissOutside);window.addEventListener('blur',()=>closePop());window.addEventListener('pagehide',()=>closePop());document.addEventListener('canvas:render',render);window.addEventListener('resize',position);new ResizeObserver(position).observe(panel);
 window.AudioAPI={createPlayer:makePlayer,upload,preview,download,buildRequest,localize,setVoiceProvider(provider){for(const menu of externalVoiceMenus)menu.close();voiceRevision++;voiceProvider=provider;voices=[];if(pop?.getAttribute('aria-label')==='选择音色')closePop();},setVoices(value){for(const menu of externalVoiceMenus)menu.close();voiceRevision++;voices=value;if(pop?.getAttribute('aria-label')==='选择音色')closePop();},listVoices,previewVoice,openVoiceMenu,getConfig(id){return core.transition(app.getState().nodes.find(n=>n.id===id)?.audioConfig||{});}};render();document.dispatchEvent(new Event('audio:ready'));
})();
