import {Outpaint} from './image-outpaint-ui.mjs';
import * as core from './image-crop-core.mjs';
import {nodeSize} from './image-resize-core.mjs';
import icons from './image-crop-icons.mjs';
const app=window.CanvasApp,el=(tag,cls='',text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const stylesheet=el('link');stylesheet.rel='stylesheet';stylesheet.href='image-crop.css';document.head.append(stylesheet);let current;
class Crop extends Outpaint {
 constructor(node){super(node);this.root.classList.add('image-crop');this.root.setAttribute('aria-label','图片裁剪');this.cancel.setAttribute('aria-label','取消裁剪');this.frame.setAttribute('aria-label','裁剪选区');for(const h of this.frame.querySelectorAll('[data-direction]'))h.setAttribute('aria-label',h.getAttribute('aria-label').replace('扩图','裁剪'));this.frame.querySelector('.outpaint-frame-backdrop').remove();this.dim=el('img','crop-native-dim');this.dim.draggable=false;this.dim.alt='裁剪来源图片';this.stage.prepend(this.dim);this.clip=el('div','crop-native-clip');this.preview.alt='裁剪选区图片';this.clip.append(this.preview);this.frame.prepend(this.clip);
  this.confirm=el('button','crop-native-confirm');this.confirm.type='button';this.confirm.setAttribute('aria-label','确认裁剪');this.confirm.innerHTML=icons.confirm;this.confirm.append(document.createTextNode('确认裁剪'));this.confirm.onclick=()=>this.submit();this.bar.className='crop-native-toolbar';this.bar.replaceChildren(this.cancel,el('i','outpaint-divider'),this.ratioButton,el('i','outpaint-divider'),this.confirm);this.paint();
 }
 async load(){try{const url=await LocalAssets.url(this.src),image=new Image();if(/^https?:/.test(url))image.crossOrigin='anonymous';image.src=url;await image.decode();if(!this.alive)return;this.image=image;this.original={width:image.naturalWidth,height:image.naturalHeight};this.preview.src=url;this.dim.src=url;this.place();this.paint();}catch(error){if(this.alive){app.notify('图片加载失败');this.close();}}}
 fit(){if(!this.alive)return;const c=document.querySelector('#canvas'),before=app.getState().view,next=core.openingView(this.node,c.clientWidth,c.clientHeight),distance=Math.hypot(next.x-before.x,next.y-before.y);app.transitionView(next,Math.min(1500,Math.max(200,200+distance*.5+Math.abs(next.scale-before.scale)*600+200/Math.max(before.scale,.2))));this.place();}
 place(){if(!this.alive)return;this.selection||={x:.1,y:.1,width:.8,height:.8};const n=this.node,v=app.getState().view,w=n.width*v.scale,h=n.height*v.scale,x=n.x*v.scale+v.x,y=n.y*v.scale+v.y;this.area={width:w,height:h};this.imageRect={x:0,y:0,width:w,height:h};const s=this.selection,r=this.rect={x:s.x*w,y:s.y*h,width:s.width*w,height:s.height*h};Object.assign(this.stage.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});Object.assign(this.frame.style,{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'});Object.assign(this.preview.style,{left:-r.x+'px',top:-r.y+'px',width:w+'px',height:h+'px'});this.frame.hidden=!this.image;this.bar.style.left=(x+w/2-this.bar.offsetWidth/2)+'px';this.bar.style.top=(y+h+64-this.bar.offsetHeight)+'px';this.bar.style.bottom='auto';this.placeMenu();this.placeTip();}
 paint(){super.paint();if(this.confirm){this.confirm.disabled=this.busy||!this.image;this.ratioButton.disabled=this.busy;this.place();}}
 applyRect(rect){this.selection=core.normalized(rect,this.imageRect.width,this.imageRect.height);this.place();}
 setRatio(value){if(!this.original)return;const ratio=value==='original'?this.original.width/this.original.height:value;this.applyRect(core.ratioRect(this.imageRect.width,this.imageRect.height,ratio));}
 async exportPixels(crop){if(crop.width*crop.height>128*1024*1024)throw Error('裁剪尺寸超过本地画布限制');const canvas=el('canvas');canvas.width=crop.width;canvas.height=crop.height;try{const ctx=canvas.getContext('2d');ctx.drawImage(this.image,crop.x,crop.y,crop.width,crop.height,0,0,crop.width,crop.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('裁剪图片导出失败')),'image/png'));return await LocalMedia.asDataUrl(blob);}finally{canvas.width=canvas.height=0;}}
 async submit(){if(this.busy||!this.image)return;this.busy=true;this.paint();try{this.guard();const crop=core.pixels(this.selection,this.original),png=await this.exportPixels(crop);if(!this.alive)return;this.guard();const result=app.createConnected(this.id,[{type:'image',title:'Cropped Image',image:png,fullImage:png,pixelWidth:crop.width,pixelHeight:crop.height}],{gap:100,nodeSize:nodeSize(crop.width,crop.height)})[0];this.close();return result;}catch(error){if(this.alive)app.notify(error.message.replace('扩图','裁剪'));}finally{this.busy=false;if(this.alive)this.paint();}}
 close(){super.close();if(current===this)current=null;}
}
export function open(node){const n=app.getState().nodes.find(n=>n.id===(typeof node==='string'?node:node.id));if(!n||!(n.fullImage||n.image))return;if(current){current.requestClose();return current;}window.NodeActions.close();window.NodeActions.closePop();window.AdvancedTools.close();window.NodeEditor.closePopover();app.select(n.id);current=new Crop(n);return current;}
window.ImageCrop={open,close:()=>current?.close(),get active(){return current;}};document.addEventListener('canvas:render',()=>{if(!current)return;const s=app.getState();if(!s.nodes.includes(current.node)||(current.node.fullImage||current.node.image)!==current.src||s.selected.length!==1||s.selected[0]!==current.id){current.close();return;}current.place();});
