(() => {
  'use strict';
  const app=window.CanvasApp,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  const btn=(text,fn,cls='')=>{const b=el('button',cls,text);b.type='button';b.onclick=fn;window.applyButtonIcon?.(b,text);return b;};
  const iconButton=(label,name,fn,cls='',text=label)=>{const b=btn('',fn,cls),symbol=el('span','resource-icon-button');b.setAttribute('aria-label',label);b.classList.add('resource-icon-button');symbol.setAttribute('aria-hidden','true');symbol.innerHTML=window.UI_ICONS[name]||'';b.append(symbol);if(text)b.append(el('span','',text));return b;};
  const img=(src,alt='')=>{const i=el('img');i.src=src;i.alt=alt;return i;};
  const folders=['角色','场景','道具','风格','音效','Others'];
  let library=[],extraFolders=[];try{library=JSON.parse(localStorage.getItem('tapnow-library')||'[]');extraFolders=JSON.parse(localStorage.getItem('tapnow-folders')||'[]');}catch{}
  const persistLibrary=()=>{try{localStorage.setItem('tapnow-library',JSON.stringify(library));localStorage.setItem('tapnow-folders',JSON.stringify(extraFolders));}catch{}};
  const favoriteMedia=n=>n?.type==='video'?(n.video||window.EDITOR_DATA?.nodes[n.id]?.video):n?.type==='image'?(n.fullImage||n.image):null;
  const favoriteKey=n=>['video','image'].includes(n?.type)?n.type+':'+(n.currentSourceFileId||n.sourceFileId||favoriteMedia(n)):null;
  const favoriteMatches=(asset,n)=>asset.folder==='收藏'&&(['video','image'].includes(n?.type)?(asset.mediaKey?asset.mediaKey===favoriteKey(n):(n.type==='video'?asset.video:asset.fullImage||asset.image)===favoriteMedia(n)):asset.nodeId===n?.id);
  window.CanvasLibrary={get items(){return library;},get folders(){return [...folders,...extraFolders];},isFavorite(value){const n=typeof value==='string'?app.getState().nodes.find(n=>n.id===value)||{id:value}:value;return library.some(a=>favoriteMatches(a,n));},toggleFavorite(n){const existing=library.findIndex(a=>favoriteMatches(a,n));if(existing>=0)library.splice(existing,1);else library.push({id:crypto.randomUUID(),name:n.title,image:n.image,type:n.type,folder:'收藏',nodeId:n.id,mediaKey:favoriteKey(n),audio:n.audio,video:n.type==='video'?favoriteMedia(n):null,fullImage:n.type==='image'?favoriteMedia(n):null});persistLibrary();return existing<0;}};
  let left=null,intro=null,activePanel=null,subjectManager=null,leftTrigger=null,contextMenu=null,shareMenu=null,contextFocusCheck=0;
  const surfaceMotions=new Map(),surfaceDisposers=new Map();
  function enterSurface(element,kind){
    const create=window.ReplicaUI?.createPresenceMotion;if(!create)return;
    const ease='cubic-bezier(.16,1,.3,1)',leave='cubic-bezier(.7,0,.84,0)';
    const options=kind==='library'?{hidden:{opacity:0,transform:'translateX(-20px)'},enter:{duration:200,easing:ease,opacity:{duration:100,delay:60,easing:ease}},exit:{duration:160,easing:leave,opacity:{duration:60,easing:leave}}}:
      kind==='history'?{hidden:{opacity:0,transform:'translateX(-24px)'},enter:{duration:200,easing:ease}}:
      {hidden:{opacity:0,transform:'scale(.95)'},enter:{duration:150,easing:'cubic-bezier(.4,0,.2,1)'}};
    const motion=create(element,{...options,onHidden:()=>{motion.destroy();surfaceMotions.delete(element);element.remove();}});
    surfaceMotions.set(element,motion);motion.enter();
  }
  function retireSurface(element){
    if(!element)return;
    surfaceDisposers.get(element)?.();surfaceDisposers.delete(element);
    const motion=surfaceMotions.get(element);
    // An exiting drawer must not share its live ID with the replacement drawer.
    element.removeAttribute('id');if(motion)motion.exit();else element.remove();
  }
  window.addEventListener('pagehide',event=>{if(event.persisted)return;closeContext();for(const dispose of surfaceDisposers.values())dispose();surfaceDisposers.clear();for(const [element,motion]of surfaceMotions){motion.destroy();element.remove();}surfaceMotions.clear();});
  const focusBack=trigger=>{if(trigger?.isConnected&&!trigger.closest('[hidden]'))trigger.focus({preventScroll:true});};
  function closeContext(restoreFocus=false){window.clearTimeout?.(contextFocusCheck);contextFocusCheck=0;if(!contextMenu)return;const {element,trigger}=contextMenu;contextMenu=null;retireSurface(element);trigger?.setAttribute('aria-expanded','false');if(restoreFocus)focusBack(trigger);}
  function closeShare(restoreFocus=false){if(!shareMenu)return;const trigger=shareMenu.trigger;shareMenu.element.remove();shareMenu=null;trigger.setAttribute('aria-expanded','false');if(restoreFocus)focusBack(trigger);}
  function closeLeft({restoreFocus=true,onDiscard}={}){const managed=subjectManager?.element;if(subjectManager?.destroy({onDiscard:()=>{closeLeft({restoreFocus});onDiscard?.();}})===false)return false;subjectManager=null;closeContext();if(left!==managed)retireSurface(left);intro?.remove();left=null;intro=null;activePanel=null;$('.side-tools').hidden=false;const trigger=leftTrigger;leftTrigger=null;trigger?.setAttribute('aria-expanded','false');if(restoreFocus)focusBack(trigger);return true;}
  function panel(title,kind){if(!closeLeft({restoreFocus:false,onDiscard:()=>({library:showLibrary,history:showHistory})[kind]?.()}))return {};activePanel=kind;leftTrigger=$(`.side-tools button[aria-label="${title}"]`);left=el('aside','floating-panel left-panel');left.setAttribute('aria-label',title);left.id='left-panel-'+kind;leftTrigger?.setAttribute('aria-expanded','true');const h=el('div','panel-heading');const back=iconButton('关闭'+title,'arrowLeft',()=>closeLeft(),'back-panel',false);back.setAttribute('aria-label','关闭'+title);h.append(back,el('h2','',title));left.append(h);$('.side-tools').hidden=true;document.body.append(left);enterSurface(left,kind);back.focus({preventScroll:true});return {panel:left,head:h};}
  function showDialog(dialog){const trigger=document.activeElement;dialog.addEventListener('keydown',event=>event.stopPropagation());dialog.addEventListener('close',()=>{dialog.remove();focusBack(trigger);});document.body.append(dialog);dialog.showModal();}
  function segments(labels,callback){const s=el('div','segmented');labels.forEach((name,index)=>{const b=btn(name,()=>{s.querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b));callback(name);});if(!index)b.className='chosen';s.append(b);});return s;}
  function searchBox(placeholder,callback){const input=el('input','panel-search');input.type='search';input.placeholder=placeholder;input.setAttribute('aria-label',placeholder);input.oninput=()=>callback(input.value);return input;}
  function folderButton(name,fn){const b=btn('',fn,'folder-row');const chevron=el('span','folder-chevron');chevron.innerHTML=window.UI_ICONS.arrowRight;const folder=el('span','folder-resource-icon');folder.innerHTML=window.UI_ICONS.folder;b.append(chevron,folder,el('span','',name));return b;}
  function assetPreview(item){const n={id:item.id,title:item.name,image:item.image,fullImage:item.fullImage,type:item.type||'image',content:item.content,color:item.color,audio:item.audio,video:item.video||window.EDITOR_DATA?.nodes[item.nodeId]?.video};app.preview(n);}
  function saveAsset(nodes){const assets=nodes.filter(n=>n.image||n.audio||n.video||window.EDITOR_DATA?.nodes[n.id]?.video||n.type==='text'&&n.content?.trim());if(!assets.length)return;const d=el('dialog','save-library-dialog');d.append(el('h2','','保存到素材库'));const name=el('input');name.value=assets.length===1?assets[0].title:`${assets.length} 个素材`;name.setAttribute('aria-label','素材名称');const select=el('select');select.setAttribute('aria-label','素材文件夹');[...folders,...extraFolders,'收藏'].forEach(n=>select.append(el('option','',n)));const save=btn('保存',()=>{assets.forEach((n,i)=>library.push({id:crypto.randomUUID(),name:assets.length===1?name.value:n.title,image:n.image,folder:select.value,type:n.type,nodeId:n.id,content:n.content,color:n.color,audio:n.audio,video:n.video||window.EDITOR_DATA?.nodes[n.id]?.video}));persistLibrary();d.close();showLibrary();},'solid-button');d.append(name,select,save);showDialog(d);}
  document.addEventListener('canvas:save-assets',e=>saveAsset(e.detail));
  function subjectShortcut(){const b=btn('主体库',showSubjectLibrary,'library-shortcut');b.setAttribute('aria-label','主体库');return b;}
  function showLibrary(){
    const {panel:p,head}=panel('素材库','library');if(!p)return;let scope='个人',folder=null,q='';const ai=iconButton('AI 角色','user',()=>showSubjectLibrary());ai.title='AI 角色';const add=iconButton('添加素材','plus',()=>libraryAddMenu(),'panel-plus',false);add.setAttribute('aria-label','添加素材');add.setAttribute('aria-haspopup','menu');add.setAttribute('aria-expanded','false');head.append(ai,add);
    p.append(segments(['个人','团队'],v=>{scope=v;folder=null;render();}),searchBox('搜索',v=>{q=v;render();}));const content=el('div','panel-scroll');p.append(content);
    function render(){const focused=document.activeElement?.closest?.('.asset-tile')?.dataset.assetId;content.replaceChildren();if(scope==='团队'){content.append(el('p','panel-empty','暂无团队素材'));return;}
      if(folder!==null||q){const back=()=>{folder=null;q='';p.querySelector('input').value='';render();},path=folder?iconButton(folder,'arrowLeft',back,'library-shortcut'):btn('搜索结果',back,'library-shortcut');content.append(path);const grid=el('div','library-grid');const items=library.filter(i=>(!folder||i.folder===folder)&&i.name.toLowerCase().includes(q.toLowerCase()));items.forEach(item=>{const b=btn('',()=>assetPreview(item),'asset-tile');b.dataset.assetId=item.id;if(item.image)b.append(img(item.image,item.name));else{const glyph=el('div','asset-audio-placeholder');glyph.innerHTML=window.UI_ICONS[item.type==='text'?'text':'music'];b.append(glyph);}b.append(el('span','',item.name));b.ondblclick=()=>app.insertAsset(item);b.oncontextmenu=e=>{e.preventDefault();simplePopup(e.clientX,e.clientY,[['添加到画布',()=>app.insertAsset(item)],['移到收藏',()=>{item.folder='收藏';persistLibrary();render();}],['重命名',()=>{const name=prompt('素材名称',item.name);if(name?.trim()){item.name=name.trim();persistLibrary();render();}}]],b);};grid.append(b);});content.append(grid);if(!items.length)content.append(el('p','panel-empty','暂无素材'));if(focused)Array.from(content.querySelectorAll('.asset-tile')).find(b=>b.dataset.assetId===focused)?.focus({preventScroll:true});return;}
      content.append(iconButton('收藏','star',()=>{folder='收藏';render();},'library-shortcut'),subjectShortcut(),el('div','library-divider'),el('div','library-caption','文件夹'));
      [...folders,...extraFolders].forEach(name=>{const b=folderButton(name,()=>{folder=name;render();});const dots=el('span','folder-more resource-icon-button');dots.setAttribute('aria-hidden','true');dots.innerHTML=window.UI_ICONS.more||'';b.append(dots);content.append(b);});
    }
    function libraryAddMenu(){const r=add.getBoundingClientRect();simplePopup(r.right,r.bottom+8,[['上传图片',()=>uploadLibrary(folder||'Others',()=>{if(left===p&&p.isConnected&&activePanel==='library')render();})],['保存选中节点',()=>saveAsset(app.getState().nodes.filter(n=>app.getState().selected.includes(n.id)))],['新建文件夹',()=>{const name=prompt('文件夹名称');if(name?.trim()&&![...folders,...extraFolders].includes(name.trim())){extraFolders.push(name.trim());persistLibrary();render();}}]],add);}
    render();
  }
  function uploadLibrary(folder,onSaved){const input=el('input');input.type='file';input.accept='image/*';input.multiple=true;input.onchange=()=>{[...input.files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{library.push({id:crypto.randomUUID(),name:file.name,image:reader.result,folder,type:'image'});persistLibrary();onSaved?.();};reader.readAsDataURL(file);});};input.click();}
  async function showSubjectLibrary(){
    const previous=left;
    const {openSubjectManager}=await import('./src/features/subject-library/manager.mjs');
    if(left!==previous)return;
    const trigger=leftTrigger||$('.side-tools button[aria-label="素材库"]');if(!closeLeft({restoreFocus:false,onDiscard:showSubjectLibrary}))return;leftTrigger=trigger;activePanel='library';$('.side-tools').hidden=true;
    subjectManager=openSubjectManager({onBack:showLibrary,onApply:async (subject,options)=>{const {applySubject}=await import('./src/features/subject-library/apply.mjs');await applySubject(subject,app,options);}});left=subjectManager.element;left.id='left-panel-library';leftTrigger?.setAttribute('aria-expanded','true');
  }
  async function showHistory(){
    const {panel:p,head}=panel('历史','history');if(!p)return;
    try{const {mountHistory}=await import('./src/features/generation-history/ui.mjs');if(left!==p)return;surfaceDisposers.set(p,mountHistory({panel:p,head,app}));}
    catch(error){if(left===p){p.append(el('p','panel-empty','历史面板读取失败：'+error.message));app.notify(error.message);}}
  }
  function showTemplates(){
    if(!closeLeft({restoreFocus:false,onDiscard:showTemplates}))return;activePanel='templates';leftTrigger=$('.side-tools button[aria-label="模板"]');left=el('aside','floating-panel templates-panel');left.setAttribute('aria-label','模板');left.id='left-panel-templates';leftTrigger?.setAttribute('aria-expanded','true');let tab='公共模板',q='';const tabs=el('div','template-tabs');const publicBtn=btn('公共模板',()=>{tab='公共模板';publicBtn.classList.add('chosen');mineBtn.classList.remove('chosen');render();},'chosen'),mineBtn=btn('我的模板',()=>{tab='我的模板';mineBtn.classList.add('chosen');publicBtn.classList.remove('chosen');render();}),expand=iconButton('浏览全部模板','expand',()=>{left.style.top=left.style.top?'':'64px';intro?.remove();},'',false);expand.setAttribute('aria-label','浏览全部模板');tabs.append(publicBtn,mineBtn,expand);left.append(tabs,searchBox('搜索资产包...',v=>{q=v;render();}));const content=el('div','panel-scroll');left.append(content);document.body.append(left);const owner=left;publicBtn.focus({preventScroll:true});
    if(localStorage.getItem('tapnow-template-intro')!=='dismissed'){intro=el('div','template-intro');intro.append(img(window.SIDEBAR_DATA.template[0].image));const text=el('div');text.append(el('h3','','使用模板加速创作'),el('p','','一键使用专业模版，快速构建你的专属场景。'));intro.append(text,btn('知道了',()=>{localStorage.setItem('tapnow-template-intro','dismissed');intro.remove();intro=null;}));document.body.append(intro);}
    const active=()=>left===owner&&owner.isConnected;window.TemplateAPI?.ready.then(()=>{if(active())render();}).catch(error=>{if(active())content.replaceChildren(el('p','panel-empty','模板读取失败：'+error.message));});const refresh=()=>{if(active())render();};document.addEventListener('templates:changed',refresh);surfaceDisposers.set(owner,()=>document.removeEventListener('templates:changed',refresh));
    function render(){const focused=document.activeElement?.closest?.('.template-card')?.dataset.templateId;content.replaceChildren();const grid=el('div','template-grid');const items=tab==='公共模板'?window.SIDEBAR_DATA.template.filter(i=>i.name.toLowerCase().includes(q.toLowerCase())):(window.TemplateAPI?.list()||[]).filter(i=>i.name.toLowerCase().includes(q.toLowerCase()));items.forEach(item=>{const b=btn('',()=>templateDetail(item),'template-card');b.dataset.templateId=item.id||item.name;if(item.image)b.append(img(item.image,item.name));else{const glyph=el('div','asset-audio-placeholder');glyph.innerHTML=window.UI_ICONS[item.type==='text'?'text':'music'];b.append(glyph);}b.append(el('span','',item.name));grid.append(b);});content.append(grid);if(!items.length)content.append(el('p','panel-empty',q?'没有匹配的模板':'暂无模板'));if(focused)Array.from(content.querySelectorAll('.template-card')).find(b=>b.dataset.templateId===focused)?.focus({preventScroll:true});}render();
  }
  function templateDetail(item){const owner=left,trigger=document.activeElement;let using=false;const d=el('dialog','template-preview');d.setAttribute('aria-label',item.name);d.addEventListener('close',()=>{if(left===owner&&!trigger?.isConnected)(Array.from(owner.querySelectorAll('.template-card')).find(b=>b.dataset.templateId===(item.id||item.name))||owner.querySelector('.template-tabs .chosen'))?.focus({preventScroll:true});});const head=el('div','dialog-heading');head.append(el('h2','',item.name),iconButton('关闭模板预览','close',()=>d.close(),'close',false));d.append(head);if(item.video){const video=el('video');video.src=item.video;video.controls=true;d.append(video);}else if(item.image)d.append(img(item.image,item.name));if(item.description)d.append(el('p','template-description',item.description));if(item.tags)d.append(el('p','template-tags',item.tags.join(' · ')));const actions=el('div','template-actions');const use=btn('使用模板',async()=>{if(using)return;using=true;use.disabled=true;use.setAttribute('aria-busy','true');try{await window.TemplateAPI.use(item.id);if(d.isConnected&&d.open){d.close();if(left===owner)closeLeft();}}catch(e){app.notify(e.message);}finally{using=false;if(d.isConnected){use.disabled=!item.graph;use.setAttribute('aria-busy','false');}}},'solid-button');use.disabled=!item.graph;if(!item.graph)use.title='尚未导入此模板的完整节点数据';actions.append(btn('关闭',()=>d.close()),use);d.append(actions);showDialog(d);}
  function simplePopup(x,y,items,trigger=document.activeElement){
    if(contextMenu?.trigger===trigger){closeContext(true);return null;}closeContext();closeShare();
    const p=el('div','menu context-popup');p.setAttribute('role','menu');p.setAttribute('aria-label','素材操作');
    items.forEach(([text,fn])=>{const b=btn(text,()=>{closeContext(true);fn();});b.setAttribute('role','menuitem');p.append(b);});
    p.style.left=Math.max(8,Math.min(innerWidth-230,x))+'px';p.style.top=Math.max(8,Math.min(innerHeight-items.length*38-20,y))+'px';document.body.append(p);enterSurface(p,'menu');contextMenu={element:p,trigger};trigger?.setAttribute('aria-expanded','true');
    p.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeContext(true);return;}if(e.key==='Tab'){if(contextMenu?.element===p)contextMenu.tabLeaving=true;return;}if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();e.stopPropagation();const rows=[...p.querySelectorAll('button')],i=rows.indexOf(document.activeElement);rows[e.key==='Home'?0:e.key==='End'?rows.length-1:(i+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length]?.focus();};
    p.querySelector('button')?.focus({preventScroll:true});return p;
  }
  function showShare(){if(shareMenu){closeShare(true);return;}closeContext();const p=el('section','share-menu');p.setAttribute('aria-label','分享画布');p.setAttribute('role','dialog');p.tabIndex=-1;for(const [title,action,desc]of[['在 TapTV 上发布','发布','在 TapTV 上发布你的作品，让更多创作者看到。'],['通过链接分享','分享','任何拥有此链接的人都可以查看并克隆你的画布。'],['移动到团队项目','移动','将此项目转移到团队进行协作。']]){const s=el('div','share-section'),h=el('div');const b=btn(action,null);b.disabled=true;b.title='本地预览尚未连接协作服务';h.append(el('span','',title),b);s.append(h,el('p','',desc));p.append(s);}document.body.append(p);shareMenu={element:p,trigger:shareButton};shareButton.setAttribute('aria-expanded','true');p.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeShare(true);}else if(e.key==='Tab')closeShare();};p.focus({preventScroll:true});}
  const actions={素材库:['library',showLibrary],模板:['templates',showTemplates],历史:['history',showHistory]};Object.entries(actions).forEach(([name,[kind,fn]])=>{const b=$(`.side-tools button[aria-label^="${name}"]`);b.classList.remove('deferred');b.setAttribute('aria-label',name);b.dataset.tip=name;b.setAttribute('aria-controls','left-panel-'+kind);b.setAttribute('aria-expanded','false');b.onclick=()=>activePanel===kind?closeLeft():fn();});
  const agentButton=$('.agent');agentButton.classList.remove('deferred');agentButton.setAttribute('aria-label','AI 助手');agentButton.dataset.tip='AI 助手';agentButton.onclick=()=>window.AgentUI.toggle();
  const avatar=$('.avatar');
  import('./src/features/generation-results/entry.mjs').then(({install})=>{install(avatar);avatar.classList.remove('deferred');avatar.dataset.tip='个人账号';}).catch(error=>app.notify('画布设置加载失败：'+error.message));
  const shareButton=$('.share');shareButton.classList.remove('deferred');shareButton.setAttribute('aria-label','分享画布');shareButton.dataset.tip='分享';shareButton.onclick=showShare;
  document.addEventListener('canvas:render',()=>{
    const save=$('#node-toolbar button[aria-label="复制节点"]');if(save){save.setAttribute('aria-label','保存到素材库');save.title='保存到素材库';save.onclick=()=>app.saveSelection();}
  });
  document.addEventListener('pointerdown',e=>{if(contextMenu)contextMenu.tabLeaving=false;if(contextMenu&&!contextMenu.element.contains(e.target)&&!contextMenu.trigger?.contains(e.target))closeContext();if(shareMenu&&!shareMenu.element.contains(e.target)&&!shareMenu.trigger.contains(e.target))closeShare();});
  document.addEventListener('focusin',e=>{if(contextMenu&&!contextMenu.element.contains(e.target)&&(!contextMenu.trigger?.contains(e.target)||contextMenu.tabLeaving))closeContext();else if(contextMenu)contextMenu.tabLeaving=false;});
  document.addEventListener('focusout',e=>{
    if(!contextMenu?.element.contains(e.target))return;
    window.clearTimeout?.(contextFocusCheck);const pending=contextMenu;
    contextFocusCheck=window.setTimeout(()=>{if(contextMenu!==pending)return;contextFocusCheck=0;if(document.hasFocus?.()===false||!pending.element.contains(document.activeElement))closeContext();},0);
  });
  window.addEventListener('blur',()=>closeContext());
  // A later listener may remove its popup before this fallback runs. Remember
  // the upper layer at dispatch start so the same Escape cannot close the drawer.
  const upperEscapes=new WeakSet();
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const layers=$$('dialog[open],[role="menu"],[role="dialog"],.subject-editor-v2');if(layers.some(node=>!node.hidden&&!node.closest('[hidden],[inert],[aria-hidden="true"]')&&node!==contextMenu?.element&&node!==shareMenu?.element))upperEscapes.add(e);},{capture:true});
  document.addEventListener('keydown',e=>{if(e.key!=='Escape'||e.defaultPrevented||e.isComposing||upperEscapes.has(e)||document.querySelector('dialog[open]')||document.body.matches('.studio-active,.media-editing,.text-viewer-active,.pile-gallery-active,.video-masking,.video-reshoot-active,.video-creation-active,.video-trimming,.action-editing'))return;if(contextMenu){e.preventDefault();e.stopImmediatePropagation();closeContext(true);return;}if(shareMenu){e.preventDefault();e.stopImmediatePropagation();closeShare(true);return;}if(left){e.preventDefault();e.stopImmediatePropagation();closeLeft();}});

})();
