(() => {
 'use strict';
 const app=window.CanvasApp,el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;},button=(text,fn)=>{const b=el('button','',text);b.type='button';b.onclick=fn;return b;};
 let cache=[],popup=null,pendingOpen=null,templateWrites=Promise.resolve(),migrationPending=null,migrationReport=null,templatePending=0;
 const officialMedia=value=>{try{const host=new URL(value,window.location?.href||'http://localhost/').hostname.toLowerCase().replace(/\.$/,'');return ['tapnow.media','tapnow.ai','tapnow.art','tapnow.top','tapnow.zone','tapnow.plus','tapnow.tv','tamaredge.top','conversation-service-131786869360.asia-northeast1.run.app'].some(domain=>host===domain||host.endsWith('.'+domain));}catch{return false;}};
 function mediaSource(element,value){if(!value)return;if(officialMedia(value)){element.title='此媒体需迁移或重新导入本地素材';return;}if(value.startsWith('asset:')){const pending=window.LocalAssets?.url?.(value);if(!pending){element.title='本地素材存储尚未就绪';return;}pending.then(url=>{if(!officialMedia(url))element.src=url;}).catch(error=>{element.title=error.message;});}else element.src=value;}
 function assertGraphReadable(value,resourceList=false){if(!value||typeof value!=='object')return;for(const [key,item]of Object.entries(value)){if(['content','prompt','description','provenance','mediaKey'].includes(key))continue;if(typeof item==='string'&&(resourceList||['image','fullImage','video','audio','poster','thumbnail','src','sourceUrl','modelUrl','url','asset','base'].includes(key))&&officialMedia(item))throw Error('模板有旧媒体尚未迁移，请先迁移或重新导入本地素材');if(item&&typeof item==='object')assertGraphReadable(item,['refs','references','inputs','versions','options','spzUrls'].includes(key));}}
 const changed=()=>document.dispatchEvent(new CustomEvent('templates:changed'));
 let recentRows=[];
 const recentStore=import('./src/features/workflow-templates/recent.mjs').then(({createRecentTemplateStore})=>createRecentTemplateStore({indexedDB,databaseName:(window.TEMPLATE_DB_NAME||'tapnow-local-templates')+':recent',onChanged:rows=>{recentRows=rows;changed();}}));
 const recentReady=recentStore.then(async store=>{await store.ready;recentRows=store.list();});recentReady.catch(()=>{});
 async function recordRecent(id,kind){const store=await recentStore;await store.record(id,kind);}
 async function rememberPersonal(id){try{await recordRecent(id,'personal');}catch(error){app.notify('模板已应用，但最近使用记录未保存：'+error.message);}}
 const sorted=value=>JSON.stringify([...value].sort((a,b)=>String(a.id).localeCompare(String(b.id))));
 const conflict=()=>Object.assign(Error('另一窗口已更新模板，当前修改尚未保存，请保留此页面重试'),{name:'TemplateConflictError'});
 function queueWrite(operation){templatePending++;const pending=templateWrites.catch(()=>{}).then(operation);templateWrites=pending;pending.catch(()=>{}).finally(()=>templatePending--);return pending;}
 const discardUi=import('./src/shared/draft-dismissal.mjs');
 window.CanvasProjects?.registerNavigationGuard(()=>migrationPending||templatePending||popup?.isBusy?.()?'模板正在保存或迁移，请完成后再切换项目':popup?.isDirty?.()?'模板有未保存的修改，请先保存或取消编辑，再切换项目':null);
 const dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(window.TEMPLATE_DB_NAME||'tapnow-local-templates',1);request.onupgradeneeded=()=>request.result.createObjectStore('templates',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
 async function transaction(mode,fn){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('templates',mode),request=fn(tx.objectStore('templates'));tx.oncomplete=()=>resolve(request?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('模板保存已中断'));});}
 const ready=transaction('readonly',s=>s.getAll()).then(items=>{cache=items.sort((a,b)=>b.updatedAt-a.updatedAt);return cache;});ready.catch(()=>app.notify('模板读取失败，请检查本地存储'));
 async function migrateResources(options={}){
  if(migrationPending)return migrationPending;
  const report=value=>{migrationReport=value;changed();return value;};
  migrationPending=(async()=>{
   await ready;await templateWrites.catch(()=>{});if(popup?.isBusy?.()||popup?.isDirty?.())return report({status:'local_edits',persisted:false});
   const [{migrateTemplateSnapshot},{loadResourceIndex}]=await Promise.all([import('./src/features/local-resource-migration/snapshot.mjs'),import('./src/features/local-resource-migration/canvas-load.mjs')]);
   const indexState=options.indexState||(options.index?{state:'ready',index:options.index}:await loadResourceIndex());if(indexState.state!=='ready')return report({status:indexState.state,persisted:false});
   const baseline=sorted(cache),result=await (options.migrate||migrateTemplateSnapshot)(cache,{index:indexState.index,...(options.hashSource?{hashSource:options.hashSource}:{})});
   const outcome={status:result.unresolved.length?'pending_import':'ready',persisted:false,summary:result.summary,diagnostics:result.unresolved.map(({path,code})=>({path,code}))};
   await queueWrite(async()=>{
    if(sorted(cache)!==baseline||popup?.isBusy?.()||popup?.isDirty?.()){outcome.status='local_edits';return;}
    const db=await dbPromise;await new Promise((resolve,reject)=>{
     const tx=db.transaction('templates','readwrite'),store=tx.objectStore('templates'),request=store.getAll();let cancelled=false;
     request.onsuccess=()=>{if(sorted(request.result)!==baseline||sorted(cache)!==baseline){cancelled=true;outcome.status='local_edits';tx.abort();return;}if(result.changes.length)for(const item of result.snapshot)store.put(item);};request.onerror=()=>reject(request.error);
     tx.oncomplete=()=>{if(result.changes.length){cache=result.snapshot;outcome.persisted=true;}resolve();};tx.onerror=()=>reject(tx.error);tx.onabort=()=>cancelled?resolve():reject(tx.error||Error('模板迁移保存中断'));
    });
   });return report(outcome);
  })().catch(error=>{report({status:error.name==='TemplateConflictError'?'local_edits':'migration_failed',persisted:false});throw error;}).finally(()=>{migrationPending=null;});return migrationPending;
 }
 async function save(groupId,metadata,id){await ready;const name=metadata.name?.trim();if(!name||[...name].length>10)throw Error('名称需为 1–10 个字符');const tags=[...new Set((metadata.tags||[]).map(t=>t.trim()).filter(Boolean))];if(tags.length>5||tags.some(t=>[...t].length>15))throw Error('最多 5 个标签，每个不超过 15 个字符');const state=app.getState();const graph=window.TemplatesCore.capture(state.nodes,state.edges,groupId,n=>window.WorkflowAPI.executable(n)&&['image','video','text'].includes(n.type)?window.NodeEditor.getConfig(n):undefined);for(const n of graph.nodes){n.video=n.video||window.EDITOR_DATA?.nodes[n.id]?.video;}
  const previous=id?cache.find(t=>t.id===id):null;if(id&&!previous)throw Error('历史模板已不存在');const cover=graph.nodes.find(n=>n.video)||graph.nodes.find(n=>n.image);const item={id:id||crypto.randomUUID(),name,tags,description:metadata.description||'',image:metadata.cover||cover?.image||'',video:metadata.cover?'':cover?.video||'',graph,createdAt:previous?.createdAt||Date.now(),updatedAt:Date.now()};await queueWrite(async()=>{const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction('templates','readwrite'),store=tx.objectStore('templates'),request=store.get(item.id);let failure=null;request.onsuccess=()=>{if(JSON.stringify(request.result)!==JSON.stringify(previous||undefined)){failure=conflict();tx.abort();return;}store.put(item);};request.onerror=()=>reject(request.error);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(failure||tx.error||Error('模板保存已中断'));});cache=[item,...cache.filter(t=>t.id!==item.id)];changed();});return item;
 }
 async function use(id,{canApply=()=>true}={}){const projectId=window.CanvasProjects?.id?.();await ready;if(!canApply()||projectId!==window.CanvasProjects?.id?.())throw Error('模板应用已取消：画布或来源已切换');const item=cache.find(t=>t.id===id);if(!item)throw Error('模板已不存在');assertGraphReadable(item.graph);const state=app.getState(),r=document.querySelector('#canvas').getBoundingClientRect();let point={x:(r.width/2-state.view.x)/state.view.scale,y:(r.height/2-state.view.y)/state.view.scale};const intersects=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;let attempts=0;while(state.nodes.some(n=>intersects({...point,width:item.graph.width,height:item.graph.height},n))&&attempts++<state.nodes.length+1)point.x=Math.max(...state.nodes.filter(n=>intersects({...point,width:item.graph.width,height:item.graph.height},n)).map(n=>n.x+n.width))+160;const graph=window.TemplatesCore.instantiate(item,point);app.insertGraph(graph);app.focusNode(graph.group.id);return graph.group;}
 function close({saved=false,restoreFocus=true,onDiscard}={}){pendingOpen=null;if(!popup)return true;const current=popup;if(!saved&&current.canClose?.()===false){if(!current.isBusy())current.requestDiscard(()=>{if(popup!==current)return;close({saved:true,restoreFocus});onDiscard?.();});return false;}const anchor=popup.returnFocus;popup.cancelDiscard?.();popup.remove();popup=null;if(restoreFocus&&anchor?.isConnected)anchor.focus({preventScroll:true});return true;}
 async function open(groupId,anchor){
  if(pendingOpen&&pendingOpen.anchor===anchor){pendingOpen=null;return;}const request={anchor,projectId:window.CanvasProjects?.id?.()};pendingOpen=request;
  try{await ready;if(pendingOpen!==request)return;if(anchor&&!anchor.isConnected||request.projectId!==window.CanvasProjects?.id?.()){pendingOpen=null;return;}window.TemplatesCore.capture(app.getState().nodes,app.getState().edges,groupId);pendingOpen=null;}catch(e){if(pendingOpen===request){pendingOpen=null;app.notify(e.message);}return;}if(popup&&anchor&&popup.returnFocus===anchor){close();return;}if(!close({restoreFocus:false,onDiscard:()=>open(groupId,anchor)}))return;
  const p=popup=el('section','template-create');p.setAttribute('role','dialog');p.setAttribute('aria-label','创建模板');const tabs=el('div','template-create-tabs'),body=el('div'),footer=el('footer'),error=el('p','template-error');let mode='create',selected='',tags=[],cover='';
  const name=el('input'),description=el('textarea');name.placeholder='输入名称（最多10个字符）';name.value='模板';name.setAttribute('aria-label','模板名称');description.placeholder='请输入描述信息';description.value='请介绍您的模板，比如使用场景、操作步骤以及独特价值';description.setAttribute('aria-label','备注');
  const snapshot=()=>JSON.stringify([name.value,description.value,tags,cover]),initial=snapshot();let baseline=initial,saving=false;
  let discardConfirmation=null,loadingDiscard=false;
  p.returnFocus=anchor||document.activeElement;p.isBusy=()=>saving;p.isDirty=()=>snapshot()!==baseline||!!p.querySelector('input[aria-label="新标签"]')?.value.trim();p.canClose=()=>{if(saving){error.textContent='正在保存模板，请完成后再关闭';return false;}return !p.isDirty();};
  p.cancelDiscard=()=>{discardConfirmation?.cancel();discardConfirmation=null;};
  p.requestDiscard=onDiscard=>{if(discardConfirmation||loadingDiscard)return;loadingDiscard=true;discardUi.then(({confirmDiscard})=>{loadingDiscard=false;if(popup!==p)return;discardConfirmation=confirmDiscard({owner:p,title:'放弃模板修改？',message:'模板有未保存的修改。继续编辑可保留当前内容。',onCancel:()=>{discardConfirmation=null;},onDiscard:()=>{discardConfirmation=null;onDiscard();}});}).catch(e=>{loadingDiscard=false;error.textContent='确认窗口加载失败：'+e.message;});};
  const tagsBox=el('div','template-tag-list'),count=el('span','','0/5'),upload=el('input');upload.type='file';upload.accept='image/*';upload.hidden=true;upload.onchange=()=>{const file=upload.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>10*1024*1024){error.textContent='请选择 10MB 以内的图片';return;}const reader=new FileReader();reader.onload=()=>{if(popup!==p)return;cover=reader.result;drawPreview();};reader.readAsDataURL(file);};
  const preview=button('',()=>upload.click());preview.className='template-cover';preview.setAttribute('aria-label','上传模板封面');function drawPreview(){preview.replaceChildren();const nodes=app.getState().nodes.filter(n=>n.parentId===groupId),n=nodes.find(n=>n.video)||nodes.find(n=>n.image);if(cover||n?.image){const image=el('img');mediaSource(image,cover||n.image);preview.append(image);}else if(n?.video){const video=el('video');mediaSource(video,n.video);video.autoplay=true;video.muted=true;video.loop=true;preview.append(video);}else preview.textContent='上传封面';if(window.TEMPLATE_CAPTURE_ICONS?.upload){const overlay=el('span','template-cover-upload');overlay.innerHTML=window.TEMPLATE_CAPTURE_ICONS.upload;preview.append(overlay);}}
  function drawTags(){tagsBox.replaceChildren();count.textContent=tags.length+'/5';for(const tag of tags)tagsBox.append(button(tag+' ×',()=>{tags=tags.filter(t=>t!==tag);drawTags();}));if(tags.length<5)tagsBox.append(button('+ 标签',()=>{const input=el('input');input.placeholder='输入标签，按回车添加';input.setAttribute('aria-label','新标签');input.maxLength=15;let done=false;const commit=()=>{if(done)return;done=true;const v=input.value.trim();if(v&&!tags.includes(v))tags.push(v);drawTags();};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commit();}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();done=true;drawTags();tagsBox.querySelector('button')?.focus({preventScroll:true});}};input.onblur=commit;tagsBox.append(input);input.focus();}));}
  const create=button('创建新模板',()=>{mode='create';draw();}),update=button('更新历史模板',()=>{mode='update';draw();});tabs.append(create,update);
  function field(label,control){const wrap=el('label','template-field');wrap.append(el('span','',label),control);return wrap;}
  function draw(){create.classList.toggle('chosen',mode==='create');update.classList.toggle('chosen',mode==='update');body.replaceChildren();if(mode==='update'){const select=el('select');select.setAttribute('aria-label','选择历史模板');select.append(new Option('请选择历史模板',''));for(const t of cache)select.append(new Option(t.name,t.id));select.value=selected;select.onchange=()=>{const next=select.value;const apply=()=>{selected=next;select.value=next;const t=cache.find(t=>t.id===selected);if(t){name.value=t.name;description.value=t.description;tags=[...t.tags];cover=t.video?'':t.image;drawTags();drawPreview();baseline=snapshot();}};if(!p.canClose()){select.value=selected;if(!saving)p.requestDiscard(apply);return;}apply();};body.append(select);if(!cache.length)body.append(el('p','panel-empty','暂无历史模板'));}
   const row=el('div','template-create-row'),fields=el('div','template-fields'),tagLabel=el('div','template-tag-label','标签');tagLabel.append(count);fields.append(field('名称',name),tagLabel,tagsBox,field('备注',description));row.append(preview,fields);body.append(row);drawTags();drawPreview();}
  const confirm=button('确认',async()=>{if(saving)return;saving=true;p.inert=true;confirm.disabled=true;try{if(mode==='update'&&!selected)throw Error('请选择历史模板');await save(groupId,{name:name.value,description:description.value,tags,cover},mode==='update'?selected:undefined);if(popup===p)close({saved:true});app.notify(mode==='update'?'模板已更新':'模板已创建');}catch(e){error.textContent=e.message;}finally{saving=false;p.inert=false;confirm.disabled=false;}});confirm.className='solid-button';if(window.TEMPLATE_CAPTURE_ICONS?.check)confirm.insertAdjacentHTML('afterbegin',window.TEMPLATE_CAPTURE_ICONS.check);footer.append(error,button('取消',()=>close()),confirm);p.append(tabs,body,upload,footer);draw();document.body.append(p);const r=anchor?.getBoundingClientRect()||{left:innerWidth/2-250,bottom:150};p.style.left=Math.max(8,Math.min(innerWidth-p.offsetWidth-8,r.left+p.offsetWidth/2-250))+'px';p.style.top=Math.max(8,Math.min(innerHeight-p.offsetHeight-8,r.bottom+8))+'px';name.focus({preventScroll:true});
 }
 document.addEventListener('pointerdown',e=>{if(pendingOpen&&!pendingOpen.anchor?.contains(e.target))pendingOpen=null;if(popup&&!document.querySelector('dialog[open]')&&!popup.contains(e.target)&&!popup.returnFocus?.contains(e.target))close({restoreFocus:false});});document.addEventListener('focusin',e=>{if(pendingOpen&&!pendingOpen.anchor?.contains(e.target))pendingOpen=null;});window.addEventListener('blur',()=>{pendingOpen=null;});window.addEventListener('pagehide',()=>{pendingOpen=null;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.defaultPrevented&&!e.isComposing&&e.keyCode!==229&&pendingOpen&&pendingOpen.anchor?.contains(e.target)){pendingOpen=null;e.preventDefault();e.stopImmediatePropagation();return;}if(popup&&e.key==='Escape'&&!e.isComposing&&(!e.target.closest('[role="menu"],[role="dialog"]')||popup.contains(e.target))&&!document.querySelector('dialog[open]')&&!e.target.closest('input[aria-label="新标签"]')){e.preventDefault();e.stopImmediatePropagation();close();}},{capture:true});
 const useAndRemember=async (id,options)=>{const group=await use(id,options);await rememberPersonal(id);return group;};
 window.TemplateAPI={ready,recentReady,list:()=>structuredClone(cache),listRecent:()=>structuredClone(recentRows),recordRecent,save,use:useAndRemember,open,close,migrateResources,migrationStatus:()=>migrationReport&&structuredClone(migrationReport)};
})();
