(() => {
 'use strict';
 const app=window.CanvasApp,el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;},button=(text,fn)=>{const b=el('button','',text);b.type='button';b.onclick=fn;return b;};
 let cache=[],popup=null,pendingOpen=null;
 const discardUi=import('./src/shared/draft-dismissal.mjs');
 window.CanvasProjects?.registerNavigationGuard(()=>popup?.isBusy?.()?'模板正在保存，请完成后再切换项目':popup?.isDirty?.()?'模板有未保存的修改，请先保存或取消编辑，再切换项目':null);
 const dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(window.TEMPLATE_DB_NAME||'tapnow-local-templates',1);request.onupgradeneeded=()=>request.result.createObjectStore('templates',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
 async function transaction(mode,fn){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('templates',mode),request=fn(tx.objectStore('templates'));tx.oncomplete=()=>resolve(request?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('模板保存已中断'));});}
 const ready=transaction('readonly',s=>s.getAll()).then(items=>{cache=items.sort((a,b)=>b.updatedAt-a.updatedAt);return cache;});ready.catch(()=>app.notify('模板读取失败，请检查本地存储'));
 async function save(groupId,metadata,id){await ready;const name=metadata.name?.trim();if(!name||[...name].length>10)throw Error('名称需为 1–10 个字符');const tags=[...new Set((metadata.tags||[]).map(t=>t.trim()).filter(Boolean))];if(tags.length>5||tags.some(t=>[...t].length>15))throw Error('最多 5 个标签，每个不超过 15 个字符');const state=app.getState();const graph=window.TemplatesCore.capture(state.nodes,state.edges,groupId,n=>window.WorkflowAPI.executable(n)&&['image','video','text'].includes(n.type)?window.NodeEditor.getConfig(n):undefined);for(const n of graph.nodes){n.video=n.video||window.EDITOR_DATA?.nodes[n.id]?.video;}
  const previous=id?cache.find(t=>t.id===id):null;if(id&&!previous)throw Error('历史模板已不存在');const cover=graph.nodes.find(n=>n.video)||graph.nodes.find(n=>n.image);const item={id:id||crypto.randomUUID(),name,tags,description:metadata.description||'',image:metadata.cover||cover?.image||'',video:metadata.cover?'':cover?.video||'',graph,createdAt:previous?.createdAt||Date.now(),updatedAt:Date.now()};await transaction('readwrite',s=>s.put(item));cache=[item,...cache.filter(t=>t.id!==item.id)];document.dispatchEvent(new CustomEvent('templates:changed'));return item;
 }
 async function use(id){await ready;const item=cache.find(t=>t.id===id);if(!item)throw Error('模板已不存在');const state=app.getState(),r=document.querySelector('#canvas').getBoundingClientRect();let point={x:(r.width/2-state.view.x)/state.view.scale,y:(r.height/2-state.view.y)/state.view.scale};const intersects=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;let attempts=0;while(state.nodes.some(n=>intersects({...point,width:item.graph.width,height:item.graph.height},n))&&attempts++<state.nodes.length+1)point.x=Math.max(...state.nodes.filter(n=>intersects({...point,width:item.graph.width,height:item.graph.height},n)).map(n=>n.x+n.width))+160;const graph=window.TemplatesCore.instantiate(item,point);app.insertGraph(graph);app.focusNode(graph.group.id);return graph.group;}
 function close({saved=false,restoreFocus=true,onDiscard}={}){pendingOpen=null;if(!popup)return true;const current=popup;if(!saved&&current.canClose?.()===false){if(!current.isBusy())current.requestDiscard(()=>{if(popup!==current)return;close({saved:true,restoreFocus});onDiscard?.();});return false;}const anchor=popup.returnFocus;popup.cancelDiscard?.();popup.remove();popup=null;if(restoreFocus&&anchor?.isConnected)anchor.focus({preventScroll:true});return true;}
 async function open(groupId,anchor){
  if(pendingOpen&&pendingOpen.anchor===anchor){pendingOpen=null;return;}const request={anchor,projectId:window.CanvasProjects?.id?.()};pendingOpen=request;
  try{await ready;if(pendingOpen!==request)return;if(anchor&&!anchor.isConnected||request.projectId!==window.CanvasProjects?.id?.()){pendingOpen=null;return;}window.TemplatesCore.capture(app.getState().nodes,app.getState().edges,groupId);pendingOpen=null;}catch(e){if(pendingOpen===request){pendingOpen=null;app.notify(e.message);}return;}if(popup&&anchor&&popup.returnFocus===anchor){close();return;}if(!close({restoreFocus:false,onDiscard:()=>open(groupId,anchor)}))return;
  const p=popup=el('section','template-create');p.setAttribute('role','dialog');p.setAttribute('aria-label','创建模板');const tabs=el('div','template-create-tabs'),body=el('div'),footer=el('footer'),error=el('p','template-error');let mode='create',selected='',tags=[],cover='';
  const name=el('input'),description=el('textarea');name.placeholder='输入名称（最多10个字符）';name.value='模板';name.setAttribute('aria-label','模板名称');description.placeholder='请输入描述信息';description.value='请介绍您的模板，比如使用场景、操作步骤以及独特价值';description.setAttribute('aria-label','备注');
  const snapshot=()=>JSON.stringify([name.value,description.value,tags,cover]),initial=snapshot();let baseline=initial,saving=false;
  let discardConfirmation=null,loadingDiscard=false;
  p.returnFocus=anchor||document.activeElement;p.isBusy=()=>saving;p.isDirty=()=>snapshot()!==baseline||!!p.querySelector('input[aria-label="新标签"]')?.value.trim();p.canClose=()=>{if(saving){error.textContent='正在保存模板，请完成后再关闭';return false;}return !p.isDirty();};
  p.cancelDiscard=()=>{discardConfirmation?.cancel();discardConfirmation=null;};
  p.requestDiscard=onDiscard=>{if(discardConfirmation||loadingDiscard)return;loadingDiscard=true;discardUi.then(({confirmDiscard})=>{loadingDiscard=false;if(popup!==p)return;discardConfirmation=confirmDiscard({owner:p,title:'放弃模板修改？',message:'模板有未保存的修改。继续编辑可保留当前内容。',onCancel:()=>{discardConfirmation=null;},onDiscard:()=>{discardConfirmation=null;onDiscard();}});}).catch(e=>{loadingDiscard=false;error.textContent='确认窗口加载失败：'+e.message;});};
  const tagsBox=el('div','template-tag-list'),count=el('span','','0/5'),upload=el('input');upload.type='file';upload.accept='image/*';upload.hidden=true;upload.onchange=()=>{const file=upload.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>10*1024*1024){error.textContent='请选择 10MB 以内的图片';return;}const reader=new FileReader();reader.onload=()=>{if(popup!==p)return;cover=reader.result;drawPreview();};reader.readAsDataURL(file);};
  const preview=button('',()=>upload.click());preview.className='template-cover';preview.setAttribute('aria-label','上传模板封面');function drawPreview(){preview.replaceChildren();const nodes=app.getState().nodes.filter(n=>n.parentId===groupId),n=nodes.find(n=>n.video)||nodes.find(n=>n.image);if(cover||n?.image){const image=el('img');image.src=cover||n.image;preview.append(image);}else if(n?.video){const video=el('video');video.src=n.video;video.autoplay=true;video.muted=true;video.loop=true;preview.append(video);}else preview.textContent='上传封面';if(window.TEMPLATE_CAPTURE_ICONS?.upload){const overlay=el('span','template-cover-upload');overlay.innerHTML=window.TEMPLATE_CAPTURE_ICONS.upload;preview.append(overlay);}}
  function drawTags(){tagsBox.replaceChildren();count.textContent=tags.length+'/5';for(const tag of tags)tagsBox.append(button(tag+' ×',()=>{tags=tags.filter(t=>t!==tag);drawTags();}));if(tags.length<5)tagsBox.append(button('+ 标签',()=>{const input=el('input');input.placeholder='输入标签，按回车添加';input.setAttribute('aria-label','新标签');input.maxLength=15;let done=false;const commit=()=>{if(done)return;done=true;const v=input.value.trim();if(v&&!tags.includes(v))tags.push(v);drawTags();};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commit();}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();done=true;drawTags();tagsBox.querySelector('button')?.focus({preventScroll:true});}};input.onblur=commit;tagsBox.append(input);input.focus();}));}
  const create=button('创建新模板',()=>{mode='create';draw();}),update=button('更新历史模板',()=>{mode='update';draw();});tabs.append(create,update);
  function field(label,control){const wrap=el('label','template-field');wrap.append(el('span','',label),control);return wrap;}
  function draw(){create.classList.toggle('chosen',mode==='create');update.classList.toggle('chosen',mode==='update');body.replaceChildren();if(mode==='update'){const select=el('select');select.setAttribute('aria-label','选择历史模板');select.append(new Option('请选择历史模板',''));for(const t of cache)select.append(new Option(t.name,t.id));select.value=selected;select.onchange=()=>{const next=select.value;const apply=()=>{selected=next;select.value=next;const t=cache.find(t=>t.id===selected);if(t){name.value=t.name;description.value=t.description;tags=[...t.tags];cover=t.video?'':t.image;drawTags();drawPreview();baseline=snapshot();}};if(!p.canClose()){select.value=selected;if(!saving)p.requestDiscard(apply);return;}apply();};body.append(select);if(!cache.length)body.append(el('p','panel-empty','暂无历史模板'));}
   const row=el('div','template-create-row'),fields=el('div','template-fields'),tagLabel=el('div','template-tag-label','标签');tagLabel.append(count);fields.append(field('名称',name),tagLabel,tagsBox,field('备注',description));row.append(preview,fields);body.append(row);drawTags();drawPreview();}
  const confirm=button('确认',async()=>{if(saving)return;saving=true;p.inert=true;confirm.disabled=true;try{if(mode==='update'&&!selected)throw Error('请选择历史模板');await save(groupId,{name:name.value,description:description.value,tags,cover},mode==='update'?selected:undefined);if(popup===p)close({saved:true});app.notify(mode==='update'?'模板已更新':'模板已创建');}catch(e){error.textContent=e.message;}finally{saving=false;p.inert=false;confirm.disabled=false;}});confirm.className='solid-button';if(window.TEMPLATE_CAPTURE_ICONS?.check)confirm.insertAdjacentHTML('afterbegin',window.TEMPLATE_CAPTURE_ICONS.check);footer.append(error,button('取消',()=>close()),confirm);p.append(tabs,body,upload,footer);draw();document.body.append(p);const r=anchor?.getBoundingClientRect()||{left:innerWidth/2-250,bottom:150};p.style.left=Math.max(8,Math.min(innerWidth-p.offsetWidth-8,r.left+p.offsetWidth/2-250))+'px';p.style.top=Math.max(8,Math.min(innerHeight-p.offsetHeight-8,r.bottom+8))+'px';name.focus({preventScroll:true});
 }
 document.addEventListener('pointerdown',e=>{if(pendingOpen&&!pendingOpen.anchor?.contains(e.target))pendingOpen=null;if(popup&&!document.querySelector('dialog[open]')&&!popup.contains(e.target)&&!popup.returnFocus?.contains(e.target))close({restoreFocus:false});});document.addEventListener('focusin',e=>{if(pendingOpen&&!pendingOpen.anchor?.contains(e.target))pendingOpen=null;});window.addEventListener('blur',()=>{pendingOpen=null;});window.addEventListener('pagehide',()=>{pendingOpen=null;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!e.defaultPrevented&&!e.isComposing&&e.keyCode!==229&&pendingOpen&&pendingOpen.anchor?.contains(e.target)){pendingOpen=null;e.preventDefault();e.stopImmediatePropagation();return;}if(popup&&e.key==='Escape'&&!e.isComposing&&(!e.target.closest('[role="menu"],[role="dialog"]')||popup.contains(e.target))&&!document.querySelector('dialog[open]')&&!e.target.closest('input[aria-label="新标签"]')){e.preventDefault();e.stopImmediatePropagation();close();}},{capture:true});
 window.TemplateAPI={ready,list:()=>structuredClone(cache),save,use,open,close};
})();
