(() => {
 'use strict';
 const relayout=()=>document.dispatchEvent(new Event('voice:layout'));
 const core=window.VoiceCore,el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
 const button=(label,icon,action)=>{const b=el('button');b.type='button';b.setAttribute('aria-label',label);b.title=label;b.innerHTML=window.UI_ICONS[icon]||'';b.onclick=action;return b;};
 let provider=core.httpProvider(),active=null;const recoveryRows=new Map();
 function dismissRecovery(row){if(!row)return;row.querySelector('audio')?.pause();recoveryRows.get(row)?.();recoveryRows.delete(row);row.remove();relayout();}
 new MutationObserver(()=>{for(const row of recoveryRows.keys())if(!row.isConnected)dismissRecovery(row);}).observe(document.body,{childList:true,subtree:true});
 function selection(target,value){if(typeof target.selectionStart==='number')return {start:target.selectionStart,end:target.selectionEnd};const s=getSelection();if(s.rangeCount&&target.contains(s.anchorNode)&&target.contains(s.focusNode)){const r=s.getRangeAt(0),before=r.cloneRange();before.selectNodeContents(target);before.setEnd(r.startContainer,r.startOffset);const start=before.toString().length;return {start,end:start+r.toString().length,range:r.cloneRange(),startNode:r.startContainer,endNode:r.endContainer};}return {start:value.length,end:value.length};}
 function bind(trigger,{target,getValue,setValue,isCurrent=()=>true,mount=trigger.parentElement,capture,transcriptionProvider,captureSelection,commitTranscript}={}){
  trigger.dataset.voiceTrigger='true';trigger.title='语音输入';trigger.setAttribute('aria-label','语音输入');trigger.disabled=false;
  trigger.onclick=async()=>{
   active?.cancel();dismissRecovery(mount.querySelector('.voice-recovery'));const initialValue=getValue(),snapshot=captureSelection?captureSelection():{initialValue,...selection(target,initialValue)};
   const bar=el('div','voice-control'),finish=button('完成语音输入','check',finishRecording),wave=el('canvas','voice-wave'),status=el('span','voice-status','正在准备麦克风...'),cancel=button('取消语音输入','close',()=>session.cancel());
   bar.setAttribute('aria-label','语音输入控制');bar.setAttribute('role','group');status.setAttribute('aria-live','polite');finish.append(wave,status);bar.append(finish,cancel);trigger.before(bar);trigger.hidden=true;relayout();
   let recording=null,frame=0,closed=false,processing=false,sample=null,previewUrl=null;const abort=new AbortController();
   const session={cancel(){if(closed)return;closed=true;abort.abort();recording?.cancel();cleanup();}};active=session;
   const observer=new MutationObserver(()=>{if(!target.isConnected||!isCurrent()||target.closest('[hidden]'))session.cancel();});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});
   function cleanup(){cancelAnimationFrame(frame);observer.disconnect();bar.remove();trigger.hidden=false;if(previewUrl)URL.revokeObjectURL(previewUrl);if(active===session)active=null;relayout();}
   function update(state){finish.disabled=state!=='recording';bar.dataset.state=state;wave.hidden=state!=='recording';status.hidden=state==='recording';status.textContent=state==='preparing'?'正在准备麦克风...':state==='processing'?'润色中...':'完成';}
   function draw(){if(closed||recording?.state!=='recording')return;const width=Math.max(60,wave.clientWidth),height=24,dpr=devicePixelRatio||1;wave.width=width*dpr;wave.height=height*dpr;const ctx=wave.getContext('2d');ctx.scale(dpr,dpr);const data=new Uint8Array(recording.analyser?.frequencyBinCount||128);recording.analyser?.getByteTimeDomainData(data);ctx.fillStyle='#d4d4d4';for(let x=0;x<width;x+=4){const index=Math.floor(x/width*data.length),h=recording.analyser?Math.max(2,Math.min(height,Math.abs(data[index]-128)/128*height*4)):2;ctx.fillRect(x,(height-h)/2,2,h);}frame=requestAnimationFrame(draw);}
   function recover(error){if(closed)return;closed=true;cleanup();const row=el('div','voice-recovery'),message=el('span','',error.name==='NotAllowedError'?'麦克风权限已关闭，请在系统或浏览器设置中开启。':error.name==='NotFoundError'?'未找到可用的麦克风，请检查设备后重试。':error.message);row.setAttribute('role','status');row.append(message);if(sample){const retry=button('重试语音转写','refresh',()=>{dismissRecovery(row);if(!target.isConnected||!isCurrent())return;closed=false;trigger.before(bar);trigger.hidden=true;relayout();active=session;observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});void processSample();});row.append(retry);const listen=button('试听录音','play',()=>{let audio=row.querySelector('audio');if(!audio){audio=el('audio');audio.controls=true;previewUrl=URL.createObjectURL(sample.blob);audio.src=previewUrl;row.append(audio);}audio.play().catch(()=>{});});row.append(listen);}row.append(button('关闭语音提示','close',()=>{dismissRecovery(row);}));recoveryRows.set(row,()=>{if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}});mount.append(row);relayout();}
   async function processSample(){if(closed||processing)return;processing=true;update('processing');try{const text=await core.transcribe(transcriptionProvider||provider,sample.blob,{signal:abort.signal});if(closed)return;const result=commitTranscript?{committed:target.isConnected&&isCurrent()&&commitTranscript(snapshot,text)}:core.insertText(snapshot,getValue(),text);closed=true;cleanup();if(target.isConnected&&isCurrent()&&result.committed&&(!snapshot.range||target.contains(snapshot.startNode)&&target.contains(snapshot.endNode))){if(commitTranscript){}else if(snapshot.range){const textNode=document.createTextNode(text);snapshot.range.deleteContents();snapshot.range.insertNode(textNode);setValue(target.innerText);}else setValue(result.value);if(typeof target.setSelectionRange==='function'){target.focus();target.setSelectionRange(result.caret,result.caret);}}else{const row=el('div','voice-recovery');row.setAttribute('role','status');row.append(el('span','','语音文字无法自动插入：'+text),button('复制识别文字','copy',()=>navigator.clipboard.writeText(text)),button('关闭语音提示','close',()=>row.remove()));(mount.isConnected?mount:document.body).append(row);relayout();}}catch(e){if(e.name!=='AbortError')recover(e);}finally{processing=false;}}
   async function finishRecording(){if(closed||recording?.state!=='recording')return;update('processing');try{sample=await recording.stop();cancelAnimationFrame(frame);await processSample();}catch(e){if(e.name!=='AbortError')recover(e);}}
   update('preparing');recording=new core.Recorder({...capture,onState:state=>{if(state==='recording')update(state);},onError:recover});try{if(await recording.start())draw();}catch(e){recover(e);}
  };
 }
 window.VoiceInput={bind,setProvider(next){if(typeof next?.transcribe!=='function')throw Error('语音提供方必须实现transcribe');provider=next;},cancel(){active?.cancel();}};
 window.addEventListener('pagehide',()=>active?.cancel());
})();
