'use strict';
// Public HEAD clone + this feature only; fresh browser profile and no provider credentials.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn,spawnSync}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/laplace/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const repo=path.resolve(__dirname,'../../../..'),directory=fs.mkdtempSync(path.join(os.tmpdir(),'canvas-history-expansion-')),port=Number(process.env.HISTORY_QA_PORT||4298),base=`http://127.0.0.1:${port}`;
const output=path.join(repo,'docs/screenshots/history-expansion-20261005');fs.mkdirSync(output,{recursive:true});
const svg=(width,height,color)=>'data:image/svg+xml;base64,'+Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="${color}"/><text x="10" y="35" fill="white" font-size="20">History QA</text></svg>`).toString('base64');
const portrait=svg(180,320,'#6b5740'),square=svg(200,200,'#3d7344'),wide=svg(1600,900,'#964243');
const fixture={referenceWidth:889,referenceHeight:1011,nodes:[{id:'source',type:'image',title:'分批历史',x:54015.125,y:-4155.375,width:444,height:250,image:wide,fullImage:wide,pixelWidth:1600,pixelHeight:900,generation:{prompt:'当前草稿',model:'next',count:4},imageHistory:[{id:'batch-1',prompt:'第一批',parameters:{model:'historical-1',count:2},options:[{id:'portrait',image:portrait,sourceFileId:'p'},{id:'square',image:square,width:200,height:200}]},{id:'batch-2',prompt:'第二批',parameters:{model:'historical-2',count:1},options:[{id:'wide',image:wide,width:1600,height:900}]}]}],edges:[]};
async function archive(){await new Promise((resolve,reject)=>{const git=spawn('git',['archive','HEAD'],{cwd:repo}),tar=spawn('tar',['-x','-C',directory]);git.stdout.pipe(tar.stdin);git.on('error',reject);tar.on('error',reject);tar.on('exit',code=>code?reject(Error('archive failed')):resolve());});
 for(const file of ['canvas-menus.js','src/features/node-history-expansion/model.mjs','src/features/node-history-expansion/runtime.mjs']){fs.mkdirSync(path.dirname(path.join(directory,file)),{recursive:true});fs.copyFileSync(path.join(repo,file),path.join(directory,file));}
 for(const file of ['canvas-data.js','editor-data.js','sidebar-data.js','versions-data.js'])fs.copyFileSync(path.join(directory,'defaults',file),path.join(directory,file));
 fs.writeFileSync(path.join(directory,'canvas-data.js'),'window.CANVAS_DATA='+JSON.stringify(fixture)+';');
 fs.symlinkSync(path.join(repo,'node_modules'),path.join(directory,'node_modules'),'dir');
}
async function main(){
 await archive();let serverOutput='';const server=spawn(process.execPath,['server/server.cjs'],{cwd:directory,env:{PATH:process.env.PATH,PORT:String(port)},stdio:['ignore','pipe','pipe']});server.stdout.on('data',data=>serverOutput+=data);server.stderr.on('data',data=>serverOutput+=data);
 let browser;const report={directory,port,baseCommit:spawnSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).stdout.trim(),checks:{},consoleErrors:[],externalRequests:[],serverOutput:''};
 try{
  for(let i=0;i<80;i++){try{if((await fetch(base+'/api/agent/config')).ok)break;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
  assert.equal((await (await fetch(base+'/api/agent/config')).json()).configured,false);
  assert.equal((await fetch(base+'/reference/context-menu-source.txt')).status,403);
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
  page.on('pageerror',error=>report.consoleErrors.push(error.message));page.on('request',request=>{if(/^https?:/.test(request.url())&&!request.url().startsWith(base))report.externalRequests.push(request.url());});
  await page.goto(base);await page.waitForFunction(()=>window.CanvasMenus&&window.ImageHistory&&window.CanvasApp?.projectSnapshot().nodes.length===1);
  await page.evaluate(()=>{window.CanvasApp.select('source');window.CanvasApp.fitNode('source',{duration:0});});
  const before=await page.evaluate(()=>({graph:JSON.stringify({nodes:CanvasApp.getState().nodes,edges:CanvasApp.getState().edges}),source:JSON.stringify(CanvasApp.getState().nodes[0]),history:CanvasApp.projectSnapshot().history.length}));
  await page.locator('.node[data-id="source"] .node-body').click({button:'right'});await page.getByRole('menuitem',{name:'应用所有历史',exact:true}).click();
  await page.waitForFunction(()=>CanvasApp.getState().nodes.length===5);await page.waitForTimeout(1000);await page.evaluate(()=>CanvasStore.flush());
  const expanded=await page.evaluate(()=>{const s=CanvasApp.getState(),g=s.nodes.find(n=>n.type==='group'),children=s.nodes.filter(n=>n.parentId===g.id),r=CanvasApp.getNodeElement(g.id).getBoundingClientRect();return {source:JSON.stringify(s.nodes.find(n=>n.id==='source')),group:g,children,history:CanvasApp.projectSnapshot().history.length,view:s.view,rect:{x:r.x,y:r.y,width:r.width,height:r.height},dom:children.map(n=>({id:n.id,left:parseFloat(CanvasApp.getNodeElement(n.id).style.left),top:parseFloat(CanvasApp.getNodeElement(n.id).style.top)}))};});
  assert.equal(expanded.source,before.source);assert.equal(expanded.history,before.history+1);const [a,b,c]=expanded.children;assert.equal(a.y,b.y);assert.equal(c.y,a.y+Math.max(a.height,b.height)+72);assert.equal(c.x,a.x);assert.equal(a.generation.prompt,'第一批');assert.equal(c.generation.prompt,'第二批');assert.equal(a.generation.count,2);assert.equal(c.generation.count,1);const cssError=Math.max(...expanded.dom.flatMap(n=>{const child=expanded.children.find(c=>c.id===n.id);return [Math.abs(child.x-n.left),Math.abs(child.y-n.top)];}));assert.ok(cssError<=.051);assert.ok(expanded.rect.x>0&&expanded.rect.y>0&&expanded.rect.x+expanded.rect.width<1440&&expanded.rect.y+expanded.rect.height<1000);
  report.checks.batches={rowCount:2,resultCount:3,sourceUnchanged:true,undoSteps:1,graphCoordinatesExact:true,cssSerializationMaxError:cssError,fitVisible:true,decodedPortrait:{width:a.pixelWidth,height:a.pixelHeight}};assert.equal(a.pixelWidth,180);assert.equal(a.pixelHeight,320);
  await page.screenshot({path:path.join(output,'image-batch-rows.png')});
  await page.evaluate(()=>CanvasApp.undo());assert.equal(await page.evaluate(()=>JSON.stringify({nodes:CanvasApp.getState().nodes,edges:CanvasApp.getState().edges})),before.graph);report.checks.undoExact=true;
  await page.evaluate(()=>CanvasApp.undo(true));await page.evaluate(()=>CanvasStore.flush());const saved=await page.evaluate(()=>JSON.stringify({nodes:CanvasApp.getState().nodes,edges:CanvasApp.getState().edges}));await page.reload();await page.waitForFunction(()=>CanvasApp?.getState().nodes.length===5);assert.equal(await page.evaluate(()=>JSON.stringify({nodes:CanvasApp.getState().nodes,edges:CanvasApp.getState().edges})),saved);report.checks.reloadExact=true;
  await page.evaluate(()=>{CanvasApp.undo();CanvasApp.updateNode('source',{imageHistory:[{id:'single',prompt:'唯一结果',options:[{id:'only',image:CanvasApp.getState().nodes[0].image,width:1600,height:900}]}]});CanvasApp.select('source');CanvasApp.fitNode('source',{duration:0});});
  await page.locator('.node[data-id="source"] .node-body').click({button:'right'});await page.getByRole('menuitem',{name:'应用所有历史',exact:true}).click();await page.waitForFunction(()=>CanvasApp.getState().nodes.length===3);report.checks.singleRealResult=true;
  await page.waitForTimeout(1000);await page.screenshot({path:path.join(output,'single-result.png')});
  await page.evaluate(()=>{CanvasApp.undo();CanvasApp.updateNode('source',{type:'video',title:'分批视频',video:'/src/features/video-history/qa/landscape.mp4',image:'/src/features/video-history/qa/landscape.png',fullImage:null,imageHistory:[],videoHistory:[{id:'v1',prompt:'视频一',options:[{id:'landscape',video:'/src/features/video-history/qa/landscape.mp4',poster:'/src/features/video-history/qa/landscape.png',width:1920,height:1080,duration:1}]},{id:'v2',prompt:'视频二',options:[{id:'portrait',video:'/src/features/video-history/qa/portrait.mp4',poster:'/src/features/video-history/qa/portrait.png',width:1080,height:1920,duration:1}]}]});CanvasApp.select('source');CanvasApp.fitNode('source',{duration:0});});
  await page.locator('.node[data-id="source"] .node-body').click({button:'right'});await page.getByRole('menuitem',{name:'应用所有历史',exact:true}).click();await page.waitForFunction(()=>CanvasApp.getState().nodes.length===4);await page.waitForTimeout(1000);const videos=await page.evaluate(()=>CanvasApp.getState().nodes.filter(n=>n.parentId));assert.equal(videos.length,2);assert.equal(videos[1].y,videos[0].y+videos[0].height+72);assert.equal(videos[0].videoMetadata.width,1920);assert.equal(videos[1].videoMetadata.width,1080);report.checks.videoBatches=true;await page.screenshot({path:path.join(output,'video-batch-rows.png')});
  assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.externalRequests,[]);report.checks.noExternalRequests=true;report.checks.providerUnconfigured=true;
 }finally{report.serverOutput=serverOutput;fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));await browser?.close();if(server.exitCode===null){server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}}
 console.log(JSON.stringify(report,null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});
