const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),http=require('node:http');
const helper=import('../src/features/agent-apps/layer-composer.mjs'),runtimeModule=import('../src/features/agent-apps/layer-composer-runtime.mjs');
const source=fs.readFileSync(require.resolve('../src/features/agent-apps/resources/apps/layer-composer@v1.067126cf.html'),'utf8');
function official(){const c={};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('const mc=2'),source.indexOf(',Ai=['))+';globalThis.api={prepare:m$,state:Ns,valid:Bn,args:g$,locales:sf};',c);return c.api;}
const plain=v=>JSON.parse(JSON.stringify(v));
function crc(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let i=0;i<8;i++)n=n>>>1^(n&1?0xedb88320:0);}return(n^0xffffffff)>>>0;}
function chunk(type,bytes){const out=Buffer.alloc(bytes.length+12);out.writeUInt32BE(bytes.length);out.write(type,4);bytes.copy(out,8);out.writeUInt32BE(crc(out.subarray(4,-4)),out.length-4);return out;}
function png(tint=100,width=64,height=64){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const pixels=Buffer.alloc(height*(1+4*width));for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=y*(1+4*width)+1+x*4;pixels[i]=tint;pixels[i+1]=90;pixels[i+2]=80;pixels[i+3]=255;}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
const uri=b=>'data:image/png;base64,'+b.toString('base64');
const raw=()=>({resource_uri:'ui://tapnow/layer-composer@v1',data:{version:1,locale:'zh-CN',title:'真实图层',canvas:{width:64,height:64,background:'transparent'},layers:['a','b'].map((id,i)=>({id,node_ref:'node/'+id,name:id,center_x:32+i,width:64,height:64,center_y:32,rotation_deg:0,opacity:1,visible:true}))}});
async function fixture({mediaRef,getOrigin,initialFetch}={}){const m=await helper,{createLayerComposerRuntime}=await runtimeModule;let current=true,project='project',added=0,saves=0,conversationSaves=0,renders=0,failStore=false,failConversation=false,onStore=null,onRender=null,fetchHook=initialFetch||null,onPersist=null;
 const assets=new Map([['asset:a',new Blob([png(80)],{type:'image/png'})],['asset:b',new Blob([png(140)],{type:'image/png'})]]),graph={nodes:['a','b'].map(id=>({id,type:'image',image:id==='a'&&mediaRef?mediaRef:'asset:'+id,fullImage:id==='a'&&mediaRef?mediaRef:'asset:'+id,x:0,y:0,width:64,height:64})),edges:[]};
 const runtime=createLayerComposerRuntime({app:{getState:()=>graph,createConnected:(source,patches)=>patches.map(p=>{const node={...p,id:'out-'+(++added)};graph.nodes.push(node);graph.edges.push({id:'edge-'+added,source,target:node.id});return node;})},localAssets:{url:async id=>{const blob=assets.get(id);if(!blob)throw Error('asset absent');return uri(Buffer.from(await blob.arrayBuffer()));},put:async blob=>{const id='asset:out-'+assets.size;assets.set(id,blob);return id;}},store:{save:async()=>{saves++;await onStore?.();return !failStore;},flush:async()=>{}},getProjectId:()=>project,...getOrigin?{getOrigin}:{},persistConversation:async()=>{conversationSaves++;await onPersist?.();return !failConversation;},fetchImpl:(...args)=>fetchHook?fetchHook(...args):fetch(...args),renderPreview:async blob=>{const bytes=Buffer.from(await blob.arrayBuffer());return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),preview:{data_uri:'data:image/webp;base64,UklGRg==',width:64,height:64}};},renderImage:async(sources,{canvas,layers,signal})=>{renders++;await onRender?.({sources,canvas,layers,signal});assert.equal(sources.length,2);return {blob:new Blob([png(200,canvas.width,canvas.height)],{type:'image/png'}),width:canvas.width,height:canvas.height};}});
 const args=await runtime.prepareAppArgs(raw()),result=runtime.bindPreparedResult({response:m.prepareLayerComposer(args.data)},args),trace={id:'trace',result,appState:m.initialLayerComposerState(result.response)},chat={id:'chat'},context=runtime.capture(result.response,{trace,chat,isCurrent:()=>current}),options={callId:'layer-call-1',userAction:true,isCurrent:()=>current,sourceContext:context};
 return {m,runtime,trace,chat,context,graph,assets,options,set current(v){current=v;},set project(v){project=v;},set failStore(v){failStore=v;},set failConversation(v){failConversation=v;},set onStore(v){onStore=v;},set onRender(v){onRender=v;},set fetchHook(v){fetchHook=v;},set onPersist(v){onPersist=v;},get counts(){return {added,saves,conversationSaves,renders};},async apply(extra={}){return runtime.apply(m.layerComposerApplyArguments(trace.result.response,trace.appState),trace,chat,{...options,...extra});}};
}
test('schema/initial state/geometry/apply and five exact localized messages match official HTML',async()=>{const f=await fixture(),o=official(),data=f.trace.result.response;assert.deepEqual(data,plain(o.prepare(data)));assert.deepEqual(f.trace.appState,plain(o.state(data)));for(const rotation of [-180,-90,-15,0,15,90,180]){const state=structuredClone(f.trace.appState);state.edits.b.rotation_deg=rotation;state.edits.b.opacity=.31;state.layer_order.reverse();assert.equal(o.valid(state,data),true);assert.deepEqual(f.m.layerComposerApplyArguments(data,state),plain(o.args(data,state)));}const r=await f.apply();for(const locale of Object.keys(o.locales)){assert.equal(f.m.layerComposerAppliedContext(r,locale),o.locales[locale].appliedContext(2,64,64,r.node_id));assert.equal((await f.m.resolveLayerComposerReply(o.locales[locale].skipMessage,data)).kind,'skipped');}await assert.rejects(f.m.resolveLayerComposerReply('generate a poster',data));});
test('official limits reject invalid aspect ratio, invisibility, huge rotated bounds and duplicate layers',async()=>{const f=await fixture(),data=f.trace.result.response;for(const change of [s=>s.edits.b.height=30,s=>{s.edits.a.visible=false;s.edits.b.visible=false;},s=>s.canvas.width=63,s=>s.edits.b.rotation_deg=181,s=>s.layer_order=['a','a'],s=>s.edits.b.opacity=2,s=>s.edits.b.center_x=193,s=>s.edits.b.width=257]){const state=structuredClone(f.trace.appState);change(state);assert.throws(()=>f.m.validateLayerComposerState(state,data));}assert.throws(()=>f.m.prepareLayerComposer({...data,layers:[data.layers[0],data.layers[0]]}));assert.throws(()=>f.m.prepareLayerComposer({...data,layers:[{...data.layers[0],preview:{...data.layers[0].preview,data_uri:'https://tapnow.ai/fake'}},data.layers[1]]}));});
test('Agent cannot inject preview, dimensions/hash, remote node media or unbound runtime result',async()=>{const f=await fixture();for(const field of ['preview','source_width','source_sha256']){const args=raw();args.data.layers[0][field]='fake';await assert.rejects(f.runtime.prepareAppArgs(args),/宿主生成/);}f.graph.nodes[0].fullImage='https://tapnow.ai/source.png';await assert.rejects(f.runtime.prepareAppArgs(raw()),/本地/);assert.throws(()=>f.runtime.bindPreparedResult({response:f.trace.result.response},raw()),/绑定/);});
test('full real local source blobs saved as one PNG/node with both source hashes and persistent receipt',async()=>{const f=await fixture(),before=structuredClone(f.graph.nodes),r=await f.apply();assert.equal(r.node_id,'out-1');assert.equal(r.layers.length,2);assert.deepEqual(f.graph.nodes.slice(0,2),before);assert.equal(f.graph.nodes[2].fullImage,f.graph.nodes[2].image);assert.match(r.output_sha256,/^[a-f0-9]{64}$/);assert.equal(r.width,64);assert.deepEqual(await f.context.validateReceiptCurrent(r),r);assert.deepEqual(f.trace.layerComposerReceipt,r);assert.equal(f.trace.layerComposerReceipts.length,1);assert.equal(f.counts.added,1);assert.equal(f.counts.saves,1);assert.equal(f.counts.conversationSaves,1);await f.runtime.setModelContext({content:[{type:'text',text:f.m.layerComposerAppliedContext(r,'zh-CN')}]},f.trace,f.chat,f.options);assert.equal(f.trace.layerComposerContext.node_id,r.node_id);});
test('callId/equivalent composition retries and in-flight calls dedupe; callId cannot change saved scene',async()=>{const f=await fixture();let release;const gate=new Promise(r=>release=r);f.onStore=()=>gate;const a=f.apply(),b=f.apply();await new Promise(r=>setTimeout(r,10));release();const [first,second]=await Promise.all([a,b]);assert.equal(first.node_id,second.node_id);const third=await f.apply({callId:'layer-call-2'});assert.equal(third.node_id,first.node_id);assert.equal(f.counts.renders,1);f.trace.appState.edits.b.center_x=37;await assert.rejects(f.apply(),/callId/);});
test('Apply requires exact saved canvas/order/edits and user action; no implicit generation',async()=>{const f=await fixture();await assert.rejects(f.apply({userAction:false}),/用户操作/);const args=f.m.layerComposerApplyArguments(f.trace.result.response,f.trace.appState);args.layers[0].opacity=.4;await assert.rejects(f.runtime.apply(args,f.trace,f.chat,f.options),/已保存/);assert.equal(f.counts.added,0);});
test('all source hashes revalidated including invisible layer and same-asset content replacement',async()=>{const f=await fixture();f.trace.appState.edits.b.visible=false;f.assets.set('asset:b',new Blob([png(141)],{type:'image/png'}));await assert.rejects(f.apply(),/真实字节/);await assert.rejects(f.context.validateSourcesCurrent(),/真实字节/);await assert.rejects(f.context.reply('先不做多图层合成，继续刚才的事。'),/真实字节/);assert.equal(f.counts.added,0);});
test('source bytes changed during render prevent output node insertion',async()=>{const f=await fixture();f.onRender=()=>f.assets.set('asset:a',new Blob([png(81)],{type:'image/png'}));await assert.rejects(f.apply(),/真实字节/);assert.equal(f.counts.added,0);});
test('project switch, in-place response tampering, source deletion and changed draft reject',async()=>{for(const mutation of [f=>f.project='other',f=>f.trace.result.response.layers[0].preview.data_uri+='AA',f=>f.graph.nodes.shift()]){const f=await fixture();mutation(f);await assert.rejects(f.apply());assert.equal(f.counts.added,0);}const f=await fixture();f.onRender=()=>f.trace.appState.edits.b.opacity=.5;await assert.rejects(f.apply(),/保存状态/);assert.equal(f.counts.added,0);});
test('canvas save failure leaves one visible result and retry persists same node',async()=>{const f=await fixture();f.failStore=true;await assert.rejects(f.apply(),/画布保存失败/);assert.equal(f.counts.added,1);assert.equal(f.trace.layerComposerReceipt,undefined);f.failStore=false;const r=await f.apply();assert.equal(r.node_id,'out-1');assert.equal(f.counts.added,1);});
test('conversation failure rolls back receipt/ledger, reports compensation failure, retry reuses node',async()=>{const f=await fixture();f.failConversation=true;await assert.rejects(f.apply(),/补偿保存失败/);assert.equal(f.trace.layerComposerReceipt,undefined);assert.equal(f.trace.layerComposerReceipts,undefined);assert.equal(f.counts.added,1);f.failConversation=false;await f.apply();assert.equal(f.counts.added,1);});
test('deleted or undone committed output cannot recreate even after capture reload',async()=>{const f=await fixture(),r=await f.apply();f.graph.nodes=f.graph.nodes.filter(n=>n.id!==r.node_id);f.graph.edges=[];await assert.rejects(f.apply(),/撤销|删除|失效|变化/);f.context.dispose();const c=f.runtime.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true});await assert.rejects(f.apply({sourceContext:c,callId:'layer-reloaded-call'}),/不能.*重建/);assert.equal(f.counts.added,1);});
test('stored output byte change or node media mutation during save never reports success',async()=>{for(const modify of [f=>{const id=f.graph.nodes[2].fullImage;f.assets.set(id,new Blob([png(201)],{type:'image/png'}));},f=>f.graph.nodes[2].image='asset:a',f=>f.graph.nodes.splice(2,1)]){const f=await fixture();f.onStore=()=>modify(f);await assert.rejects(f.apply());assert.equal(f.trace.layerComposerReceipt,undefined);}});
test('dispose stops stalled fetch stream and late renderer output; rejects remote resolution',async()=>{const f=await fixture();let cancelled=false;f.fetchHook=async()=>({ok:true,headers:new Headers({'content-type':'image/png'}),body:new ReadableStream({pull(){return new Promise(()=>{});},cancel(){cancelled=true;}})});const p=f.apply();await new Promise(r=>setTimeout(r,5));f.context.dispose();await assert.rejects(p,/关闭/);await new Promise(r=>setTimeout(r,5));assert.equal(cancelled,true);assert.equal(f.counts.added,0);const g=await fixture();let release;g.onRender=()=>new Promise(r=>release=r);const work=g.apply();while(!release)await new Promise(r=>setTimeout(r,1));g.context.dispose();release();await assert.rejects(work,/关闭/);assert.equal(g.counts.added,0);});
test('declared and streamed byte excess cancel underlying reader',async()=>{for(const declared of [true,false]){const f=await fixture();let cancelled=false;f.fetchHook=async()=>({ok:true,headers:new Headers({'content-type':'image/png',...(declared?{'content-length':String(f.m.layerComposerLimits.sourceBytes+1)}:{})}),body:new ReadableStream({pull(c){c.enqueue(new Uint8Array(f.m.layerComposerLimits.sourceBytes+1));},cancel(){cancelled=true;}})});await assert.rejects(f.apply(),/超限/);assert.equal(cancelled,true);assert.equal(f.counts.added,0);}});
test('equivalent call joining conversation commit persists its own callId across reload',async()=>{const f=await fixture();let release;const gate=new Promise(r=>release=r);f.onPersist=async()=>{if(f.counts.conversationSaves===1)await gate;};const first=f.apply();while(f.counts.conversationSaves<1)await new Promise(r=>setTimeout(r,1));const second=f.apply({callId:'layer-late-alias'});release();const [a,b]=await Promise.all([first,second]);assert.equal(a.node_id,b.node_id);assert.ok(f.trace.layerComposerReceipts.some(r=>r.callId==='layer-late-alias'));assert.equal(f.counts.added,1);f.context.dispose();const c=f.runtime.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true});f.trace.appState.edits.b.opacity=.5;await assert.rejects(f.apply({sourceContext:c,callId:'layer-late-alias'}),/callId/);});
test('exact same-origin immutable generation ref reads real HTTP PNG and composes; redirects cannot escape',async()=>{const ref='/api/generation/media/01234567-89ab-4cde-8012-3456789abcde';let redirect=false,hits=0;const server=http.createServer((req,res)=>{hits++;assert.equal(req.url,ref);if(redirect){res.writeHead(302,{location:'https://tapnow.ai/image.png'});res.end();return;}const body=png(88);res.writeHead(200,{'content-type':'image/png','content-length':body.length});res.end(body);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;try{const f=await fixture({mediaRef:ref,getOrigin:()=>origin,initialFetch:(url,options)=>{if(url.startsWith(origin)){assert.equal(options.redirect,'error');assert.equal(options.mode,'same-origin');assert.equal(options.credentials,'same-origin');}return fetch(url,options);}});assert.ok(hits);const r=await f.apply();assert.equal(r.layers[0].node_ref,'node/a');assert.equal(f.graph.nodes[0].fullImage,ref);assert.equal(f.counts.added,1);await f.context.validateReceiptCurrent(r);redirect=true;await assert.rejects(f.context.validateSourcesCurrent());assert.equal(f.counts.added,1);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('generation source rejects arbitrary relative/absolute refs and changed response peer before reading',async()=>{const f=await fixture();for(const media of ['/some.png','/api/generation/media/not-a-uuid','/api/generation/media/01234567-89ab-4cde-8012-3456789abcde?token=secret','//evil.example/api/generation/media/01234567-89ab-4cde-8012-3456789abcde','https://tapnow.ai/image.png','http://localhost:4173/api/generation/media/01234567-89ab-4cde-8012-3456789abcde']){f.graph.nodes[0].fullImage=media;await assert.rejects(f.runtime.prepareAppArgs(raw()),/本地/);}let cancelled=false;const wrongResponse=new Response(png(88),{headers:{'content-type':'image/png'}});Object.defineProperty(wrongResponse,'url',{value:'https://evil.example/image.png'});Object.defineProperty(wrongResponse,'body',{value:new ReadableStream({cancel(){cancelled=true;}})});await assert.rejects(fixture({mediaRef:'/api/generation/media/01234567-89ab-4cde-8012-3456789abcde',getOrigin:()=> 'http://localhost:4173',initialFetch:async()=>wrongResponse}),/peer|重定向/);assert.equal(cancelled,true);});
