'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),{once}=require('node:events');
const {TaskService,httpProvider}=require('../generation-api.js'),{parse,definitions}=require('../agent-tools.js');
const root=path.resolve(__dirname,'..'),client=fs.readFileSync(path.join(root,'agent-client.js'),'utf8'),ui=fs.readFileSync(path.join(root,'generation-ui.js'),'utf8');
const input={kind:'image.skin',nodeId:'source',prompt:'',skin:{mode:'heavy'}},bytes=fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')),result=fs.readFileSync(path.join(root,'qa/agent-image-processing-result.png'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function configuration(){const {skinGatewayCapabilities}=require('../server/generation-skin-profile.cjs');return {configured:true,protocol:'skin-tasks-v1',capabilities:{kinds:['image.skin'],models:{'image.skin':{kind:'image.skin'}},skin:skinGatewayCapabilities()}};}
async function fixture(t,options={}){
 const {captureAgentSkinApproval}=await import('../src/features/agent-generation/skin.mjs'),{prepareWorkflowInputs}=await import('../src/features/agent-workflows/media-transport.mjs'),{createApplicationRunner}=await import('../src/features/generation-results/application.mjs'),jobs=await import('../src/features/agent-generation/jobs.mjs');
 const config=await configuration(),source={id:'source',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},target={id:'target',type:'image',tool:'enhance',image:'asset:old',params:{activeTab:'upscale',mode:'detailed'}},state={nodes:[source,...(options.existing?[target]:[])],edges:options.existing?[{source:'source',target:'target'}]:[]};let project='p',metadata=config,saveFails=false,saves=0,created=0,trace,persisted;const posts=[],reads=[],records=new Map(),inPlace=new Map();
 const server=http.createServer(async(req,res)=>{
  if(req.url==='/result.png'){res.writeHead(200,{'content-type':'image/png'});res.end(result);return;}
  if(req.method==='GET'){const value=structuredClone(records.get(decodeURIComponent(req.url.split('/').at(-1))));options.recoveryMutation?.(value.request);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value));return;}
  let body='';for await(const chunk of req)body+=chunk;assert(persisted?.submittedTaskId,'durable Agent receipt must precede HTTP');const request=JSON.parse(body);posts.push(request);const value={id:persisted.submittedTaskId,request,status:'succeeded',outputs:[{type:'image',url:base+'/result.png',width:512,height:320}]};records.set(value.id,value);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(options.unknown?{id:value.id,status:'unknown',request}:value));
 });server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;t.after(()=>{server.closeAllConnections();server.close();});
 const full=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));t.after(()=>URL.revokeObjectURL(full));
 const localAssets={url:async key=>{assert(persisted?.submittedTaskId,'durable receipt must precede media');reads.push(key);if(options.mediaGate)await options.mediaGate.promise;assert.equal(key,'asset:full');return full;}};
 const app={getState:()=>state,projectIdentity:()=>({id:project}),createConnected:(id,outputs)=>outputs.map(output=>{created++;const node={...output,id:'result-'+created};state.nodes.push(node);state.edges.push({source:id,target:node.id});return node;}),updateNode:(id,patch)=>Object.assign(state.nodes.find(node=>node.id===id),patch),saveProject:async()=>{saves++;if(options.saveGate)await options.saveGate.promise;if(saveFails)throw Error('disk full');}};
 const service=new TaskService({prepareInputs:async(request,context)=>{context.validateSources();request.inputs[0].url=await localAssets.url(request.inputs[0].url);context.validateSources();return prepareWorkflowInputs(request,{...context,serialize:async blob=>'data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64')});}});service.setProvider(httpProvider({baseUrl:base+'/tasks',recoverable:true}));
 const host={app,service,inPlace,submitJob:(request,settings)=>service.submit(request,options.historyFailure?{...settings,beforeDispatchReady:async()=>{throw Error('history failed');}}:settings),DOMException};vm.runInNewContext(ui.slice(ui.indexOf('  function runInPlace('),ui.indexOf('  function recoverInPlace(')),host);
 const start=ui.indexOf('      if(target?.verifyRequest){'),end=ui.indexOf('      if(!stored.resultIds&&resultWorkflow',start),context={app,inPlace,window:{},audioGuard:()=>{},recordSubtitleMedia:()=>{},validateJobMedia:async output=>assert.deepEqual(Buffer.from(await fetch(output.url).then(r=>r.arrayBuffer())),result),resultProvenance:()=>({provenance:{provider:'isolated-skin-gateway',model:'three-mode-contract',prompt:''}})};
 vm.runInNewContext('async function apply(job){const stored=job,target=inPlace.get(job.id);'+ui.slice(start,end)+'}',context);
 const runner=createApplicationRunner({getJob:id=>service.jobs.get(id),apply:context.apply,changed:job=>{if(trace)jobs.attachGenerationJob(trace,job);if(!job.applying){const target=inPlace.get(job.id);job.applicationError?target?.reject(Error(job.applicationError)):target?.resolve(job);}}});service.subscribe(job=>{if(job.status==='succeeded')void runner.run(job.id);else if(['failed','cancelled','configuration_required'].includes(job.status))inPlace.get(job.id)?.reject(Error(job.error||job.status));});
 const api={runInPlace:host.runInPlace,cancel:id=>service.cancel(id),availability:async()=>{if(options.availabilityGate)await options.availabilityGate.promise;return {configured:true};},configuration:async()=>metadata,configurationSnapshot:()=>metadata};
 const fragment=client.slice(client.indexOf("  case 'generation_submit':{"),client.indexOf('   if(a.draftSourceId)',client.indexOf("  case 'generation_submit':{"))).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')'),dispatch={app,window:{GenerationAPI:api},modules:name=>import(path.join(root,name))};vm.runInNewContext('async function dispatch(a,signal,onDepthSubmitted,approvedSkinConfiguration,skinApprovalGuard){switch("generation_submit"){'+fragment+'}default:throw Error("unhandled");}}',dispatch);
 const {executeTracedCall,needsToolConfirmation}=await import('../src/features/agent-execution/trace.mjs');
 async function execute(args=options.existing?{...input,targetNodeId:target.id}:input,{mode='ask',confirm=async()=>true,signal}={}){
  const parsed=parse('generation_submit',structuredClone(args)),call={name:'generation_submit',callId:'skin-call',args:parsed.args},approvalGuard=captureAgentSkinApproval(parsed.args,{app,signal}),approvedConfiguration=JSON.stringify(metadata??null);
  const start=client.indexOf('       const onDepthSubmitted=async job=>'),end=client.indexOf('\n       return execute(',start),ack={d:{messages:[]},call,generationJobs:jobs,save:()=>{if(options.receiptFailure)return false;persisted=structuredClone(trace);return true;},flushConversation:async()=>{if(options.receiptGate)await options.receiptGate.promise;if(options.flushFailure)throw Error('receipt flush failed');},executionRenderer:{updateTrace:()=>{}}};vm.runInNewContext(client.slice(start,end)+'\nthis.acknowledge=onDepthSubmitted;',ack);
  return executeTracedCall(call,{signal,confirm:needsToolConfirmation(parsed.definition,mode)?confirm:null,changed:value=>{trace=value;ack.d.messages=[value];},execute:(_name,args)=>dispatch.dispatch(args,signal,ack.acknowledge,approvedConfiguration,approvalGuard)});
 }
 async function settled(){for(let i=0;i<600;i++){const job=[...service.jobs.values()][0];if(job&&(['failed','cancelled'].includes(job.status)||job.status==='succeeded'&&!job.applying&&job.applicationStatus))return job;await tick();}throw Error('skin task did not settle');}
 return {execute,settled,app,api,source,target,state,posts,reads,service,runner,config,get saves(){return saves;},get persisted(){return persisted;},setProject:value=>project=value,setConfiguration:value=>metadata=value,setSaveFailure:value=>saveFails=value};
}
test('skin schema has explicit three modes, source and optional distinct target; rejects freeform processing',async()=>{
 const {agentSkinParameters}=await import('../src/features/agent-generation/skin.mjs');assert.deepEqual(definitions.find(d=>d.name==='generation_submit').parameters.properties.skin.properties.mode.enum,['detailed','standard','heavy']);
 for(const mode of ['detailed','standard','heavy'])assert.deepEqual(agentSkinParameters(parse('generation_submit',{...input,skin:{mode}}).args.skin),{mode});
 for(const patch of [{skin:undefined},{skin:{}},{skin:{mode:'unknown'}},{skin:{mode:'heavy',strength:1}},{targetNodeId:'source'},{prompt:'relight'},{model:'gpt-image'},{quality:'high'},{count:2},{referenceIds:[]},{referenceIds:['other']},{relight:{}},{rotate_right_left:10}])assert.throws(()=>parse('generation_submit',{...input,...patch}));
 assert.throws(()=>parse('generation_submit',{kind:'image.generate',nodeId:'source',prompt:'',skin:{mode:'standard'}}));assert.throws(()=>parse('generation_submit',{kind:'image.generate',nodeId:'source',prompt:'',targetNodeId:'target'}));
});
test('approval reads no media; durable receipt precedes exact full-source POST and new enhance target version/save',async t=>{
 const gate=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>gate.promise});await tick();assert.equal(f.service.jobs.size,0);assert.deepEqual(f.reads,[]);assert.equal(f.state.nodes.length,1);gate.resolve(true);
 const receipt=await pending,job=await f.settled();assert.equal(receipt.result.taskId,f.persisted.submittedTaskId);assert.equal(job.applied,true,job.applicationError);assert.equal(f.posts.length,1);assert.deepEqual(f.posts[0].parameters,{mode:'heavy'});assert.equal(f.posts[0].prompt,'');assert.equal(f.posts[0].inputs[0].role,'source_image');assert.deepEqual(Buffer.from(f.posts[0].inputs[0].url.split(',')[1],'base64'),bytes);assert.deepEqual(f.reads,['asset:full']);assert.equal(f.source.fullImage,'asset:full');const target=f.state.nodes[1];assert.equal(target.tool,'enhance');assert.equal(target.params.activeTab,'realistic-portrait');assert.equal(target.params.mode,'heavy');assert.equal(target.versions.length,1);assert.deepEqual(target.versions[0].parameters,{mode:'heavy'});assert.deepEqual(Array.from(job.resultIds),[target.id]);assert.equal(f.saves,1);
});
test('existing enhance target keeps identity and previous version, save retry reuses same task/target/version',async t=>{
 for(const existing of [false,true]){const f=await fixture(t,{existing});f.setSaveFailure(true);await f.execute(undefined,{mode:'auto'});const job=await f.settled();assert.equal(job.applied,false);assert.match(job.applicationError,/disk full/);const target=f.state.nodes[1],id=target.id,versions=structuredClone(target.versions);if(existing){assert.equal(target,f.target);assert.equal(target.versions.length,2);assert.equal(target.versions[1].fullImage,'asset:old');}f.setSaveFailure(false);f.setConfiguration(null);await f.runner.run(job.id);assert.equal(job.applied,true,job.applicationError);assert.equal(f.state.nodes.length,2);assert.equal(target.id,id);assert.deepEqual(target.versions,versions);assert.equal(f.posts.length,1);assert.equal(f.saves,2);}
});
test('actual task-tray GET recovery rejects changed final mode/source bytes before creating or updating enhance results',async t=>{
 for(const mutate of [request=>request.parameters.mode='standard',request=>request.sourceNodeId='other-source',request=>request.inputs[0].url='data:image/png;base64,'+result.toString('base64')]){
  const f=await fixture(t,{unknown:true,recoveryMutation:mutate}),receipt=await f.execute(input,{mode:'auto'});let original;
  for(let i=0;i<100;i++){original=f.service.jobs.get(receipt.result.taskId);if(original.status==='unknown')break;await tick();}assert.equal(original.status,'unknown');assert.equal(f.posts.length,1);assert.equal(f.state.nodes.length,1);
  await f.service.recover(original.id);const recovered=await f.settled();assert.equal(recovered.id,original.id);assert.equal(recovered.status,'succeeded');assert.equal(recovered.applied,false);assert.match(recovered.applicationError,/原皮肤增强任务请求、模式或来源已变化/);assert.equal(f.state.nodes.length,1);assert.equal(f.saves,0);assert.equal(f.posts.length,1);
 }
});
test('denial, missing/undeclared service, failed durable receipt/history and cancelled receipt never read media or POST',async t=>{
 const denied=await fixture(t);await denied.execute(input,{confirm:()=>false});assert.equal(denied.service.jobs.size,0);
 for(const scenario of ['null','generic','receiptFailure','flushFailure','historyFailure']){const f=await fixture(t,{[scenario]:true});if(scenario==='null')f.setConfiguration(null);else if(scenario==='generic')f.setConfiguration({protocol:'tasks-v1',configured:true});const receipt=await f.execute(input,{mode:'auto'});if(f.service.jobs.size)await f.settled();else assert.equal(receipt.result.status,'configuration_required');assert.deepEqual(f.reads,[]);assert.equal(f.posts.length,0);assert.equal(f.state.nodes.length,1);}
 const gate=deferred(),f=await fixture(t,{receiptGate:gate}),controller=new AbortController(),pending=f.execute(input,{mode:'auto',signal:controller.signal});await tick();controller.abort();await assert.rejects(pending,{name:'AbortError'});gate.resolve();await tick();assert.deepEqual(f.reads,[]);assert.equal(f.posts.length,0);
});
test('approval and async preparation guard source/project/target/edge/arguments/configuration',async t=>{
 for(const scenario of ['source','same-id','crop','project','target','edge','arguments']){const f=await fixture(t,{existing:true}),gate=deferred(),pending=f.execute(undefined,{confirm:()=>gate.promise});await tick();if(scenario==='source')f.source.fullImage='asset:changed';else if(scenario==='same-id')f.state.nodes[0]={...f.source};else if(scenario==='crop')f.source.crop={};else if(scenario==='project')f.setProject('other');else if(scenario==='target')f.target.params.mode='standard';else if(scenario==='edge')f.state.edges[0]={...f.state.edges[0]};gate.resolve(scenario==='arguments'?{allowed:true,args:{...input,targetNodeId:'target',skin:{mode:'standard'}}}:true);const receipt=await pending;assert(receipt.result.error,scenario);assert.equal(f.service.jobs.size,0);assert.deepEqual(f.reads,[]);assert.equal(f.posts.length,0);}
 for(const phase of ['availabilityGate','mediaGate']){const gate=deferred(),f=await fixture(t,{[phase]:gate}),pending=f.execute(input,{mode:'auto'});await tick();f.setConfiguration({...f.config,revision:2});gate.resolve();const receipt=await pending;if(f.service.jobs.size){const job=await f.settled();assert.match(job.error,/供应商配置已变化/);}else assert.match(receipt.result.error,/供应商配置已变化/);assert.equal(f.posts.length,0);}
});
test('new-target approval revalidates every crop/selection field after approval and rejects late output without media/POST/nodes',async t=>{
 const fields=['crop','imageCrop','clip','trim','selection','imageSelection','region','sourceBox','imageRegion','selectedRegion','mask','projection'];
 for(const field of fields){
  const gate=deferred(),f=await fixture(t,{availabilityGate:gate}),pending=f.execute(input,{mode:'auto'});await tick();f.source[field]={changed:true};gate.resolve();const receipt=await pending;assert.match(receipt.result.error,/完整图片/,field);assert.equal(f.service.jobs.size,0,field);assert.deepEqual(f.reads,[],field);assert.equal(f.posts.length,0,field);assert.equal(f.state.nodes.length,1,field);
 }
 const {captureAgentSkinApproval,submitAgentSkin}=await import('../src/features/agent-generation/skin.mjs'),metadata=await configuration();
 for(const field of fields){
  const source={id:'source',type:'image',image:'asset:thumb',fullImage:'asset:full'},state={nodes:[source],edges:[]},gate=deferred();let completion,creates=0,saves=0;
  const app={getState:()=>state,projectIdentity:()=>({id:'p'}),updateNode:()=>assert.fail('late scoped result must not update'),createConnected:()=>{creates++;assert.fail('late scoped result must not create');},saveProject:async()=>{saves++;}},api={availability:async()=>({configured:true}),configuration:async()=>metadata,configurationSnapshot:()=>metadata,cancel:()=>{},runInPlace:(request,target,hooks)=>{
   const job={id:'original-late-task',status:'queued',request:structuredClone(request)};
   completion=(async()=>{await hooks.onSubmitted(job);job.request.inputs[0].url='data:image/png;base64,'+bytes.toString('base64');await hooks.onPrepared(job);await gate.promise;return target.apply({type:'image',url:'asset:late-output'});})();completion.catch(()=>{});return completion;
  }};
  // The fake service drives the actual Agent apply callback only; it performs
  // no media transport or provider POST and cannot generate substitute pixels.
  const receipt=await submitAgentSkin(structuredClone(input),{app,api,onSubmitted:async()=>{},approvedConfiguration:JSON.stringify(metadata),approvalGuard:captureAgentSkinApproval(input,{app})});assert.equal(receipt.taskId,'original-late-task');source[field]={changed:true};gate.resolve();await assert.rejects(completion,/完整图片/,field);assert.equal(creates,0);assert.equal(saves,0);assert.equal(state.nodes.length,1);
 }
});
test('skin presentation discloses actual profile, source, mode and new/existing enhance-version intent',async()=>{
 const {toolPresentation,skinDisclosure}=await import('../src/features/agent-execution/presentation.mjs');
 for(const targetNodeId of [undefined,'target']){const view=toolPresentation({name:'generation_submit',args:{...input,...(targetNodeId?{targetNodeId}:{})},status:'pending',skinDisclosure:skinDisclosure(await configuration())});assert.match(view.label,/皮肤增强/);assert.match(view.detail,/heavy（重度增强）/);assert.match(view.detail,/完整来源 source/);assert.match(view.detail,targetNodeId?/既有增强节点 target/:/新建连接的增强节点/);assert.match(view.detail,/新版本/);assert.match(view.detail,/Enhancor/);assert(!view.detail.includes('打光'));}
});

async function actualApprovalFixture({initial=null,refreshGate,configurationGate}={}){
 const native=await configuration();let current=initial==='missing'?{...native,configured:false,missing:['GENERATION_API_KEY']}:initial,reads=0,project='p';
 const routing=await import('../src/features/node-composer/provider-configuration.mjs'),localProvider={},service={provider:localProvider,jobs:new Map()},configContext={AbortSignal,structuredClone,serverConfigured:false,serverConfigurationSnapshot:null,serverConfigurationRevision:0,localProvider,service,providerConfigurationReady:Promise.resolve(routing),taskNativeConfigurations:new Map(),taskConfigurationIds:new Map(),fetch:async()=>{reads++;if(reads>1&&refreshGate)await refreshGate.promise;return Response.json(current);}};
 const configStart=ui.indexOf('  function refreshServerConfiguration('),configEnd=ui.indexOf('  function submitJob(',configStart);vm.runInNewContext(ui.slice(configStart,configEnd)+'\nthis.api={availability,configuration,configurationSnapshot};',configContext);await configContext.api.configuration();current=native;
 const controller=new AbortController(),source={id:'source',type:'image',image:'asset:thumb',fullImage:'asset:full'},target={id:'target',type:'image',tool:'enhance',params:{mode:'detailed'},image:'asset:old'},state={nodes:[source,target],edges:[{source:source.id,target:target.id}]},app={getState:()=>state,projectIdentity:()=>({id:project})},run={},d={activeRun:null};d.activeRun=run;let active=d;
 const api={...configContext.api,configuration:async()=>{const value=await configContext.api.configuration();if(configurationGate)await configurationGate.promise;return value;},runInPlace:()=>assert.fail('approval must not create tasks')},context={app,call:{name:'generation_submit',args:{...structuredClone(input),targetNodeId:target.id}},runController:controller,d,run,draft:()=>active,window:{GenerationAPI:api,LocalAssets:{url:()=>assert.fail('approval must not read media')}},DOMException,modules:name=>import(path.join(root,name))};
 const start=client.indexOf("     if(call.name==='generation_submit'&&call.args.kind==='image.skin'){"),end=client.indexOf('     const executionOptions=',start),fragment=client.slice(start,end).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');vm.runInNewContext('async function prepare(){let skinNotice,skinConfiguration,skinApprovalGuard;'+fragment+'return {skinNotice,skinConfiguration,skinApprovalGuard};}',context);
 return {prepare:context.prepare,source,target,state,controller,call:context.call,native,service,get reads(){return reads;},setProject:value=>project=value,switchChat:()=>active={},switchRun:()=>d.activeRun={}};
}
test('actual skin approval refreshes stale null/missing cache before actual profile disclosure',async()=>{
 for(const initial of [null,'missing']){const f=await actualApprovalFixture({initial}),approved=await f.prepare();assert.deepEqual(JSON.parse(approved.skinConfiguration),f.native);assert.equal(f.reads,2);assert.match(approved.skinNotice,/独立皮肤|自建网关/);assert.equal(f.service.jobs.size,0);}
});
test('actual skin approval guards both configuration awaits with source, target, edge, args, project, chat, run and cancellation',async()=>{
 for(const phase of ['refreshGate','configurationGate'])for(const mutation of ['source','same-id','target','edge','args','project','chat','run','cancel']){const gate=deferred(),f=await actualApprovalFixture({[phase]:gate}),pending=f.prepare();await tick();if(mutation==='source')f.source.fullImage='asset:other';else if(mutation==='same-id')f.state.nodes[0]={...f.source};else if(mutation==='target')f.target.params.mode='standard';else if(mutation==='edge')f.state.edges[0]={...f.state.edges[0]};else if(mutation==='args')f.call.args.skin.mode='detailed';else if(mutation==='project')f.setProject('other');else if(mutation==='chat')f.switchChat();else if(mutation==='run')f.switchRun();else f.controller.abort();gate.resolve();await assert.rejects(pending);assert.equal(f.service.jobs.size,0);}
 const f=await actualApprovalFixture();f.switchChat();await assert.rejects(f.prepare(),{name:'AbortError'});assert.equal(f.reads,1);
});
test('isolated UI skin Agent fixture fixes only model reply and checks durable original receipt before forwarding POST',async()=>{
 const script=fs.readFileSync(path.join(root,'src/features/agent-generation/qa/skin-agent-fixture.js'),'utf8'),forwarded=[];let recordedId='task-a';
 const context={URL,Headers,Response,structuredClone,crypto:globalThis.crypto,document:{baseURI:'http://localhost:49799/'},location:{href:'http://localhost:49799/',origin:'http://localhost:49799'},AgentTools:{parse},SkinFixture:{ready:true},CanvasProjects:{id:()=> 'qa-project'},CanvasStore:{readRecord:async key=>{assert.equal(key,'agent-conversations:qa-project');return {chats:[{messages:[{name:'generation_submit',args:{kind:'image.skin'},submittedTaskId:recordedId}]}]};}},fetch:async(url,options)=>{forwarded.push({url,options});return Response.json({status:'succeeded',outputs:[]});}};context.window=context;vm.runInNewContext(script,context);
 const binding={projectId:'qa-project',chatId:'chat'};context.SkinAgentFixture.setMode('standard');context.SkinAgentFixture.useTarget('existing');
 const turn=await context.fetch('/api/agent/turn',{method:'POST',body:JSON.stringify({binding})}).then(r=>r.json());assert.deepEqual(turn.calls[0].args,{kind:'image.skin',nodeId:'skin-source',prompt:'',skin:{mode:'standard'},targetNodeId:'existing'});assert.equal(forwarded.length,0);
 const options={method:'POST',headers:{'Idempotency-Key':'task-a'},body:'{}'};await context.fetch('/api/generation/tasks',options);assert.equal(forwarded.length,1);assert.equal(context.SkinAgentFixture.generationReceipts[0].acknowledged,true);recordedId='another';await assert.rejects(context.fetch('/api/generation/tasks',options),/持久对话缺少/);assert.equal(forwarded.length,1);
 await assert.rejects(context.fetch('/api/agent/continue',{method:'POST',body:JSON.stringify({sessionId:turn.sessionId,binding:{...binding,chatId:'other'}})}),/绑定已变化/);assert.throws(()=>context.SkinAgentFixture.setMode('relight'));
});
