'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),fixture=fs.readFileSync(path.join(root,'qa/agent-video-mask-fixture.js'),'utf8');
function boot({throwingStorage=false,throwingFetch=false,throwingDB=false,replace=false}={}){
 const calls=[],storageCalls=[],dbCalls=[],search='?session=video-mask-repro'+(replace?'&kind=replace':'');
 const context={URL,URLSearchParams,Response,Headers,Map,DataView,Uint8Array,TextDecoder,Event,atob,crypto:globalThis.crypto,document:{baseURI:'http://localhost:4173/'},location:{href:'http://localhost:4173/qa/agent-video-mask-app.html'+search,origin:'http://localhost:4173',search},dispatchEvent:()=>{}};
 Object.defineProperty(context,'localStorage',{configurable:true,get:()=>{storageCalls.push('get');if(throwingStorage)throw new DOMException('storage denied','SecurityError');return {getItem:()=>storageCalls.push('read'),setItem:()=>{storageCalls.push('write');throw new DOMException('origin full','QuotaExceededError');}};}});
 Object.defineProperty(context,'fetch',{configurable:true,get:()=>{if(throwingFetch)throw Error('fetch getter failed');return async(...args)=>{calls.push(args);return Response.json({native:true});};}});
 Object.defineProperty(context,'indexedDB',{configurable:true,get:()=>{if(throwingDB)throw Error('DB getter failed');return {open:(...args)=>{dbCalls.push(args);return {};},deleteDatabase:()=>assert.fail('must never delete origin DB')};}});
 context.window=context;vm.runInNewContext(fixture,context);return {context,calls,storageCalls,dbCalls};
}
test('video fixture never accesses origin preferences and bootstrap errors fail closed',async()=>{
 for(const throwingStorage of [false,true]){const f=boot({throwingStorage});assert.deepEqual(f.storageCalls,[]);assert.equal(f.context.AgentVideoMaskFixture.state.preferences,'page-memory');await assert.rejects(f.context.fetch('/api/real-provider'),/未声明/);await assert.rejects(f.context.fetch('https://example.org/api'),/外部/);assert.equal(f.calls.length,0);}
 const failed=boot({throwingFetch:true});assert.match(failed.context.AgentVideoMaskFixture.state.bootstrapError,/素材读取/);await assert.rejects(failed.context.fetch('/api/agent/turn'),/未初始化/);assert.equal(failed.calls.length,0);
 const missing=boot({throwingDB:true});assert.throws(()=>missing.context.indexedDB.open(missing.context.CANVAS_DB_NAME),/真实数据库/);
 const f=boot();assert.throws(()=>f.context.indexedDB.open('tapnow-canvas-replica'),/真实数据库/);assert.throws(()=>f.context.indexedDB.deleteDatabase('tapnow-canvas-replica'),/删除/);f.context.indexedDB.open(f.context.CANVAS_DB_NAME,1);assert.equal(f.dbCalls.length,1);
});
test('video fixture CSP precedes scripts, excludes real API connections, and catalog respects base URI',async()=>{
 const html=fs.readFileSync(path.join(root,'qa/agent-video-mask-app.html'),'utf8'),meta=html.indexOf('http-equiv="Content-Security-Policy"');assert(meta>0&&meta<html.indexOf('<script'));
 const policy=html.match(/http-equiv="Content-Security-Policy" content="([^"]+)"/)[1],connect=policy.split(';').find(item=>item.trim().startsWith('connect-src'));assert(!connect.includes("'self'")&&!connect.includes('/api'));assert(connect.includes('http://localhost:*/qa/'));assert(connect.includes('/runtime-reference/skills-catalog.json'));
 const f=boot();await f.context.fetch('runtime-reference/skills-catalog.json');assert.equal(f.calls[0][0],'http://localhost:4173/runtime-reference/skills-catalog.json');await assert.rejects(f.context.fetch('/runtime-reference/skills-catalog.json',{method:'POST'}),/未声明/);await assert.rejects(f.context.fetch('/runtime-reference/other.json'),/未声明/);assert.equal(f.calls.length,1);
});
test('fixture refresh restores original task with GET and synthetic migration map, without private file reads',async()=>{
 const f=boot(),saved={tasks:[['original-task',{id:'original-task',status:'succeeded'}]],posts:[{id:'original-task',acknowledged:true}]};f.context.CanvasStore={readRecord:async key=>{assert.equal(key,'agent-qa-video-mask-fixture-tasks');return saved;}};
 assert.equal(f.context.AgentVideoMaskFixture.state.taskRecords,'loading');await f.context.AgentVideoMaskFixture.restoreTasks();assert.equal(f.context.AgentVideoMaskFixture.state.taskRecords,'ready');assert.equal(f.context.AgentVideoMaskFixture.state.posts[0].id,'original-task');
 assert.equal((await f.context.fetch('/api/generation/tasks/original-task').then(r=>r.json())).id,'original-task');const {loadResourceIndex}=await import('../src/features/local-resource-migration/canvas-load.mjs'),result=await loadResourceIndex({fetchIndex:f.context.fetch});assert.equal(result.state,'ready');assert.equal(Object.keys(result.index.entries).length,0);assert.equal(f.calls.length,0);
 await assert.rejects(f.context.fetch('/assets/local-resource-index.json',{method:'POST'}),/未声明/);await assert.rejects(f.context.fetch('/assets/private-map.json'),/未声明/);
});
test('actual Agent transport consumes explicit fixed video calls without native model requests',async()=>{
 const {requestAgent}=await import('../src/features/agent-stream/transport.mjs');for(const replace of [false,true]){const f=boot({replace}),binding={projectId:'mask-project',chatId:'fixture-chat'},first=await requestAgent('turn',{binding,message:'编辑视频蒙层'},{fetchImpl:f.context.fetch});assert.equal(first.calls[0].args.kind,replace?'video.replace':'video.erase');assert.equal(first.calls[0].args.prompt,'');assert.deepEqual(first.calls[0].args.referenceIds,replace?['video-mask-reference']:undefined);
 const last=await requestAgent('continue',{binding,sessionId:first.sessionId,results:[]},{fetchImpl:f.context.fetch});assert.equal(last.done,true);assert.equal(f.calls.length,0);assert.equal(f.context.AgentVideoMaskFixture.state.errors.length,0);}
});
test('production mask media preparation reaches fixture only after saved task ID, with full timeline and actual full PNG',async()=>{
 const f=boot({replace:true}),records=new Map();f.context.CanvasStore={readRecord:async key=>records.get(key),writeRecord:async(key,value)=>records.set(key,value)};const config=await f.context.fetch('/api/generation/config').then(r=>r.json());
 const video=fs.readFileSync(path.join(root,'qa/trim-scenes.mp4')),png=fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')),mask={encoding:'rle-zero-based-row-major',width:320,height:180,fps:30,frames:Array.from({length:240},(_,i)=>`${(20+Math.floor(i/10))*320+40} 20`)};
 const {editRequest}=await import('../src/features/video-mask/core.mjs'),{prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs');
 const request=await prepareMaskedVideoMedia(editRequest({id:'video-mask-source',clip:{start:1,end:5}},'replace','data:video/mp4;base64,'+video.toString('base64'),mask,{nodeId:'video-mask-reference',url:'data:image/png;base64,'+png.toString('base64')}),{nativeConfiguration:config,baseUrl:f.context.location.href,resolveMedia:async node=>({url:node[node.type],width:node.type==='video'?320:512,height:node.type==='video'?180:320,...(node.type==='video'?{duration:8}:{})}),normalizeReference:async input=>input});
 const options={method:'POST',headers:{'Idempotency-Key':'qa-mask-task'},body:JSON.stringify(request)};await assert.rejects(f.context.fetch('/api/generation/tasks',options),/持久回执/);assert.equal(f.context.AgentVideoMaskFixture.state.posts.length,0);
 records.set('agent-conversations:canvas',{chats:[{messages:[{name:'generation_submit',submittedTaskId:'qa-mask-task'}]}]});const response=await f.context.fetch('/api/generation/tasks',options).then(r=>r.json());assert.equal(response.outputs[0].duration,4);assert.equal(f.context.AgentVideoMaskFixture.state.posts[0].acknowledged,true);assert.equal(f.context.AgentVideoMaskFixture.state.posts[0].mask.frames,240);assert.equal(f.context.AgentVideoMaskFixture.state.posts[0].source.duration,8);assert.equal(f.context.AgentVideoMaskFixture.state.posts[0].replacement.width,512);assert(records.has('agent-qa-video-mask-fixture-tasks'));assert.equal(f.calls.length,0);
 const before=f.context.AgentVideoMaskFixture.state.posts.length;assert.equal((await f.context.fetch('/api/generation/tasks/qa-mask-task').then(r=>r.json())).id,'qa-mask-task');assert.equal(f.context.AgentVideoMaskFixture.state.posts.length,before);
});
test('production Agent confirmation uses shared native disclosure and refuses a changed approved provider',async()=>{
 const client=fs.readFileSync(path.join(root,'agent-client.js'),'utf8'),{toolPresentation}=await import('../src/features/agent-execution/presentation.mjs'),{executeTracedCall}=await import('../src/features/agent-execution/trace.mjs');
 for(const changedProvider of [false,true]){
  const f=boot({replace:true});let configuration=await f.context.fetch('/api/generation/config').then(r=>r.json()),dispatches=0;const call={name:'generation_submit',callId:'mask-confirmation',args:{kind:'video.replace',nodeId:'video-mask-source',prompt:'',referenceIds:['video-mask-reference']}},run={},d={activeRun:run,messages:[]};
  const source={id:'video-mask-source',type:'video',video:'asset:video'},reference={id:'video-mask-reference',type:'image',fullImage:'asset:image'},app={getState:()=>({nodes:[source,reference]}),projectIdentity:()=>({id:'qa-project'})};
  const context={app,window:{AgentTools:require('../agent-tools.js'),GenerationAPI:{configuration:async()=>configuration,getJobs:()=>[]}},call,run,d,draft:()=>d,runController:new AbortController(),DOMException,JSON,modules:name=>import(path.join(root,name)),save:()=>true,render:()=>{},generationJobs:null,confirmationModule:{getMode:()=> 'ask'}};
  const start=client.indexOf('     const definition=window.AgentTools.parse(call.name,call.args).definition;'),end=client.indexOf('     const executionOptions={',start),preflight=client.slice(start,end).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');
  vm.runInNewContext('async function preflight(){'+preflight+'this.videoMaskNotice=videoMaskNotice;this.videoMaskConfiguration=videoMaskConfiguration;this.videoMaskApprovalGuard=videoMaskApprovalGuard;}',context);await context.preflight();
  const changedStart=client.indexOf('      changed:trace=>{if(videoMaskNotice)'),changedEnd=client.indexOf('\n     };',changedStart);vm.runInNewContext('this.changed='+client.slice(changedStart,changedEnd).trim().replace(/^changed:/,''),context);
  const guardStart=client.indexOf("       if(videoMaskNotice&&name==='generation_submit'"),guardEnd=client.indexOf("       if(name.startsWith('scene_')",guardStart);vm.runInNewContext('async function guard(name,args){'+client.slice(guardStart,guardEnd)+'}',context);
  const receipt=await executeTracedCall(call,{changed:context.changed,confirm:trace=>{const info=toolPresentation(trace);assert.equal(info.action,'视频替换');assert.match(info.detail,/独立替代.*Wan VACE/);assert.match(info.detail,/fal CDN/);assert.match(info.detail,/替换图片/);assert.match(info.detail,/本机保留原声音/);assert.match(info.detail,/效果待验/);assert(!info.detail.includes('Replace the masked'));assert.equal(dispatches,0);if(changedProvider)configuration={...configuration,configurationId:'changed-provider'};return true;},execute:async(name,args)=>{await context.guard(name,args);dispatches++;return {taskId:'approved-mask-task'};}});
  assert.equal(dispatches,changedProvider?0:1,JSON.stringify(receipt));if(changedProvider)assert.match(receipt.result.error,/供应商配置已变化/);else assert.equal(receipt.result.taskId,'approved-mask-task');assert(d.messages[0].videoMaskDisclosure);
 }
});
