'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),{once}=require('node:events');
const {TaskService,httpProvider}=require('../generation-api.js'),{parse,definitions}=require('../agent-tools.js'),{createRelightAgentFixture}=require('./fixtures/relight-agent.cjs'),{createOpenAIRelightProvider}=require('../server/generation-openai-relight.cjs');
const root=path.resolve(__dirname,'..'),client=fs.readFileSync(path.join(root,'agent-client.js'),'utf8'),ui=fs.readFileSync(path.join(root,'generation-ui.js'),'utf8');
const lighting={angle:{preset:'top_front_right_45'},brightnessPercent:100,temperatureK:3000,rimEnabled:true,rimPreset:'low_back_45'},input={kind:'image.relight',nodeId:'source',prompt:'',relight:lighting};
const bytes=fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')),result=fs.readFileSync(path.join(root,'qa/agent-image-processing-result.png'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function fixture(t,options={}){
 const core=await import('../image-relight-core.mjs'),{captureAgentRelightApproval}=await import('../src/features/agent-generation/relight.mjs'),{prepareRelightMedia}=await import('../src/features/image-relight/media.mjs'),{prepareWorkflowInputs}=await import('../src/features/agent-workflows/media-transport.mjs'),{createApplicationRunner}=await import('../src/features/generation-results/application.mjs'),jobs=await import('../src/features/agent-generation/jobs.mjs');
 const config=createOpenAIRelightProvider({apiKey:'nonsecret-local-fixture',modelMap:{'image.relight':{kind:'image.relight',model:'gpt-image-2',semantics:'parameter-prompt-edit',quality:'high',outputSize:'auto'}},fetchImpl:()=>assert.fail('metadata-only provider cannot dispatch')}).metadata;
 const source={id:'source',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},state={nodes:[source],edges:[]};let project='a',nativeConfiguration=config,saveFails=false,saveCount=0,created=0,trace,persisted,connectionOptions;const posts=[],assetReads=[],records=new Map(),inPlace=new Map();
 const agentFixture=createRelightAgentFixture({nodeId:source.id,relight:lighting});
 const server=http.createServer(async(req,res)=>{
  if(req.url.startsWith('/api/agent/')){let body='';for await(const chunk of req)body+=chunk;const answer=agentFixture.handle(req.url,req.method,body?JSON.parse(body):undefined);res.writeHead(answer.status,{'content-type':'application/json'});res.end(JSON.stringify(answer.json));return;}

  if(req.url==='/result.png'){res.writeHead(200,{'content-type':'image/png'});res.end(result);return;}
  if(req.method==='GET'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(records.get(decodeURIComponent(req.url.split('/').at(-1)))));return;}
  let body='';for await(const chunk of req)body+=chunk;assert(persisted?.submittedTaskId,'durable Agent receipt must precede provider HTTP');const request=JSON.parse(body);posts.push(request);
  const value={id:persisted.submittedTaskId,request,status:'succeeded',outputs:[{type:'image',url:base+'/result.png',width:512,height:320}]};records.set(value.id,value);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value));
 });server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;t.after(()=>{server.closeAllConnections();server.close();});
 const full=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));t.after(()=>URL.revokeObjectURL(full));
 const localAssets={url:async key=>{assetReads.push(key);if(options.mediaGate)await options.mediaGate.promise;assert.equal(key,'asset:full','never resolve thumbnail');return full;}};
 const app={getState:()=>state,projectIdentity:()=>({id:project}),createConnected:(id,outputs,settings)=>{connectionOptions=settings;return outputs.map(output=>{created++;const node={...output,id:'result-'+created};state.nodes.push(node);state.edges.push({source:id,target:node.id});return node;});},saveProject:async()=>{saveCount++;if(options.saveGate)await options.saveGate.promise;if(saveFails)throw Error('disk full');}};
 const service=new TaskService({prepareInputs:(request,context)=>prepareRelightMedia(request,{...context,nativeConfiguration:config,baseUrl:base,localAssets,resolveMedia:async node=>({id:node.id,type:'image',url:await localAssets.url(node.fullImage)}),transport:(value,settings)=>prepareWorkflowInputs(value,{...settings,serialize:async blob=>'data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64')}),normalizePng:async(value,settings)=>{settings.validateSources();const sourceBytes=Buffer.from(value.url.split(',')[1],'base64');assert.deepEqual(sourceBytes,bytes);return {...value,width:sourceBytes.readUInt32BE(16),height:sourceBytes.readUInt32BE(20)};}})});service.setProvider(httpProvider({baseUrl:base+'/api/generation',recoverable:true}));
 const target={app,service,inPlace,submitJob:(request,settings)=>service.submit(request,options.historyFailure?{...settings,beforeDispatchReady:async()=>{throw Error('history gate failed');}}:settings),DOMException};
 vm.runInNewContext(ui.slice(ui.indexOf('  function runInPlace('),ui.indexOf('  function recoverInPlace(')),target);
 const start=ui.indexOf('      if(target&&!stored.resultIds){'),end=ui.indexOf('      if(!stored.resultIds&&resultWorkflow',start),context={app,inPlace,window:{},audioGuard:()=>{},recordSubtitleMedia:()=>{},validateJobMedia:async output=>assert.deepEqual(Buffer.from(await fetch(output.url).then(r=>r.arrayBuffer())),result),resultProvenance:()=>({})};
 vm.runInNewContext('async function apply(job){const stored=job,target=inPlace.get(job.id);'+ui.slice(start,end)+'}',context);
 const runner=createApplicationRunner({getJob:id=>service.jobs.get(id),apply:context.apply,changed:job=>{if(trace)jobs.attachGenerationJob(trace,job);if(!job.applying){const host=inPlace.get(job.id);job.applicationError?host?.reject(Error(job.applicationError)):host?.resolve(job);}}});
 service.subscribe(job=>{if(job.status==='running'&&options.changeAtRunning)nativeConfiguration={...config,configurationId:'changed'};if(job.status==='succeeded')void runner.run(job.id);else if(['failed','cancelled','configuration_required'].includes(job.status))inPlace.get(job.id)?.reject(Error(job.error||job.status));});
 if(options.changeAtConfigured)service.provider.isConfigured=async()=>{nativeConfiguration={...config,configurationId:'changed'};return true;};
 const api={runInPlace:target.runInPlace,cancel:id=>service.cancel(id),availability:async()=>{if(options.availabilityGate)await options.availabilityGate.promise;if(options.changeAtAvailability)nativeConfiguration={...config,configurationId:'changed'};return {configured:nativeConfiguration?.configured===true};},configuration:async()=>nativeConfiguration,configurationSnapshot:()=>nativeConfiguration};
 const fragment=client.slice(client.indexOf("  case 'generation_submit':{"),client.indexOf('   if(a.draftSourceId)',client.indexOf("  case 'generation_submit':{"))).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');
 const dispatch={app,window:{GenerationAPI:api},modules:name=>import(path.join(root,name))};vm.runInNewContext('async function dispatch(a,signal,onDepthSubmitted,approvedRelightConfiguration,relightApprovalGuard){switch("generation_submit"){'+fragment+'}default:throw Error("unhandled fixture branch");}}',dispatch);
 const {executeTracedCall,needsToolConfirmation}=await import('../src/features/agent-execution/trace.mjs');
 async function execute(args=input,{mode='ask',confirm=async()=>true,signal}={}){
  const parsed=parse('generation_submit',structuredClone(args)),call={name:'generation_submit',callId:'relight-call',args:parsed.args},approvalGuard=captureAgentRelightApproval(parsed.args,{app,signal}),approvedConfiguration=JSON.stringify(nativeConfiguration??null);
  const start=client.indexOf('       const onDepthSubmitted=async job=>'),end=client.indexOf('\n       return execute(',start),ack={d:{messages:[]},call,generationJobs:jobs,save:()=>{if(options.receiptFailure)return false;persisted=structuredClone(trace);return true;},flushConversation:async()=>{if(options.receiptGate)await options.receiptGate.promise;},executionRenderer:{updateTrace:()=>{}}};
  vm.runInNewContext(client.slice(start,end)+'\nthis.acknowledge=onDepthSubmitted;',ack);
  return executeTracedCall(call,{signal,confirm:needsToolConfirmation(parsed.definition,mode)?confirm:null,changed:value=>{trace=value;ack.d.messages=[value];},execute:(_name,args)=>dispatch.dispatch(args,signal,ack.acknowledge,approvedConfiguration,approvalGuard)});
 }
 async function settled(){for(let i=0;i<600;i++){const job=[...service.jobs.values()][0];if(job&&(['failed','cancelled'].includes(job.status)||job.status==='succeeded'&&!job.applying&&job.applicationStatus))return job;await tick();}throw Error('fixture task did not settle');}
 async function executeQa(args=input){const {runAgentRelightQa}=await import('../src/features/agent-generation/qa/relight-controls.mjs');return runAgentRelightQa(args,{app,api,parse,mode:'auto',persistReceipt:async value=>{persisted=structuredClone(value);return true;},changed:value=>trace=value});}
 return {base,agentFixture,execute,executeQa,settled,app,api,source,state,posts,assetReads,service,runner,config,get trace(){return trace;},get persisted(){return persisted;},get connectionOptions(){return connectionOptions;},get saveCount(){return saveCount;},setConfiguration:value=>nativeConfiguration=value,setProject:value=>project=value,setSaveFailure:value=>saveFails=value};
}
test('Agent schema preserves all original lighting controls and rejects defaults, unrelated fields and illegal rim combinations',async()=>{
 const core=await import('../image-relight-core.mjs'),{agentRelightParameters}=await import('../src/features/agent-generation/relight.mjs');
 assert.deepEqual(definitions.find(d=>d.name==='generation_submit').parameters.properties.relight.properties.angle.properties.preset.enum,core.anglePresets.map(p=>p.key));
 for(const angle of core.anglePresets){const relight={...lighting,angle:{preset:angle.key},rimEnabled:core.rimAllowed(angle.azimuthDeg,angle.elevationDeg)};assert.deepEqual(agentRelightParameters(parse('generation_submit',{...input,relight}).args.relight),core.requestParameters({...relight,brightnessLevel:relight.brightnessPercent}));}
 for(const brightnessPercent of core.brightnessStops)for(const temperatureK of core.temperatureStops)for(const rimPreset of Object.keys(core.rimPresets)){const relight={...lighting,brightnessPercent,temperatureK,rimPreset};assert.deepEqual(agentRelightParameters(relight),relight);}
 for(const key of Object.keys(lighting)){const relight={...lighting};delete relight[key];assert.throws(()=>parse('generation_submit',{...input,relight}));assert.throws(()=>agentRelightParameters(relight));}
 for(const patch of [{relight:undefined},{relight:{...lighting,extra:1}},{relight:{...lighting,angle:{preset:'front_0',azimuthDeg:0}}},{relight:{...lighting,angle:{preset:'back_180'}}},{model:'fallback'},{quality:'high'},{referenceIds:[]},{referenceIds:['other']},{referenceIds:['source','other']},{prompt:'new subject'},{count:2}])assert.throws(()=>parse('generation_submit',{...input,...patch}));
 assert.throws(()=>parse('generation_submit',{...input,kind:'image.generate'}));
});
test('approval performs zero media reads; receipt then full source bytes lead to one connected, actually saved result',async t=>{
 const gate=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>gate.promise});await tick();assert.equal(f.trace.status,'pending');assert.deepEqual(f.assetReads,[]);assert.equal(f.service.jobs.size,0);gate.resolve(true);
 const receipt=await pending,job=await f.settled();assert.equal(receipt.result.taskId,f.persisted.submittedTaskId);assert.equal(job.applied,true,job.applicationError);assert.equal(f.posts.length,1);assert.deepEqual(f.posts[0].parameters,lighting);assert.equal(f.posts[0].prompt,'');assert.equal(f.posts[0].inputs.length,1);assert.equal(f.posts[0].inputs[0].role,'source_image');assert.deepEqual(Buffer.from(f.posts[0].inputs[0].url.split(',')[1],'base64'),bytes);assert.equal(f.state.nodes.length,2);assert.equal(f.state.edges.length,1);assert.equal(f.saveCount,1);assert.equal(f.source.fullImage,'asset:full');assert.equal(f.connectionOptions.gap,200);assert.equal(f.state.nodes[1].fullImage,f.state.nodes[1].image);assert.deepEqual(f.state.nodes[1].relightParameters,{angle:{preset:'top_front_right_45',azimuthDeg:45,elevationDeg:45},brightnessLevel:100,temperatureK:3000,rimEnabled:true,rimPreset:'low_back_45'});
});
test('auto uses traced submission; denial and missing configuration do not create jobs or read media',async t=>{
 const f=await fixture(t);await f.execute(input,{mode:'auto',confirm:()=>assert.fail('auto must not ask')});assert.equal((await f.settled()).applied,true);
 for(const mode of ['denied','missing','null']){const g=await fixture(t);if(mode==='missing')g.setConfiguration({...g.config,configured:false});if(mode==='null')g.setConfiguration(null);const receipt=await g.execute(input,{mode:mode==='denied'?'ask':'auto',confirm:()=>false});assert.equal(g.posts.length,0);assert.equal(g.service.jobs.size,0);assert.deepEqual(g.assetReads,[]);if(mode!=='denied')assert.equal(receipt.result.status,'configuration_required');}
});
test('approval binds source object, full image, crop and project before any media read',async t=>{
 for(const mutation of ['source','fullImage','crop','selection','metadata','project','arguments']){const gate=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>gate.promise});await tick();if(mutation==='source')f.state.nodes[0]={...f.source};else if(mutation==='fullImage')f.source.fullImage='asset:changed';else if(mutation==='crop')f.source.crop={x:1,y:1,width:3,height:3};else if(mutation==='selection')f.source.selection={x:0,y:0,width:10,height:10};else if(mutation==='metadata')f.source.metadata={revision:2};else if(mutation==='project')f.setProject('other');gate.resolve(mutation==='arguments'?{allowed:true,args:{...input,relight:{...lighting,brightnessPercent:10}}}:true);const receipt=await pending;assert(receipt.result.error,mutation);assert.equal(f.service.jobs.size,0);assert.deepEqual(f.assetReads,[]);assert.equal(f.posts.length,0);}
});
test('async configuration and source drift fail closed through availability, preparation and immediate dispatch',async t=>{
 for(const options of [{changeAtAvailability:true},{changeAtConfigured:true},{changeAtRunning:true}]){const f=await fixture(t,options),receipt=await f.execute(input,{mode:'auto'});if(f.service.jobs.size)assert.equal((await f.settled()).status,'failed');else assert.match(receipt.result.error,/配置已变化/);assert.equal(f.posts.length,0);}
 for(const phase of ['availabilityGate','mediaGate'])for(const mutation of ['source','project','configuration','null','crop']){const gate=deferred(),f=await fixture(t,{[phase]:gate}),pending=f.execute(input,{mode:'auto'});await tick();if(mutation==='source')f.state.nodes[0]={...f.source};else if(mutation==='project')f.setProject('other');else if(mutation==='configuration')f.setConfiguration({...f.config,configurationId:'changed'});else if(mutation==='null')f.setConfiguration(null);else f.source.crop={x:2,y:2,width:3,height:3};gate.resolve();const receipt=await pending;if(f.service.jobs.size)assert.equal((await f.settled()).status,'failed');else assert(receipt.result.error);assert.equal(f.posts.length,0);}
});
test('failed receipt/history and cancellation before receipt prevent provider dispatch',async t=>{
 for(const option of ['receiptFailure','historyFailure']){const f=await fixture(t,{[option]:true});await f.execute(input,{mode:'auto'});await f.settled();assert.equal(f.posts.length,0);assert.deepEqual(f.assetReads,[]);}
 const gate=deferred(),f=await fixture(t,{receiptGate:gate}),controller=new AbortController(),pending=f.execute(input,{mode:'auto',signal:controller.signal});await tick();controller.abort();await assert.rejects(pending,{name:'AbortError'});gate.resolve();await tick();assert.equal(f.posts.length,0);assert.deepEqual(f.assetReads,[]);
});
test('result save waits and retry keeps task and node identities without generation repost',async t=>{
 const saveGate=deferred(),f=await fixture(t,{saveGate});await f.execute(input,{mode:'auto'});for(let i=0;i<100&&f.saveCount===0;i++)await tick();const pending=[...f.service.jobs.values()][0];assert.notEqual(pending.applied,true);assert.equal(pending.applying,true);saveGate.resolve();assert.equal((await f.settled()).applied,true);
 const g=await fixture(t);g.setSaveFailure(true);await g.execute(input,{mode:'auto'});const job=await g.settled();assert.equal(job.applied,false);assert.match(job.applicationError,/disk full/);const id=g.state.nodes[1].id;g.setSaveFailure(false);g.setConfiguration(null);await g.runner.run(job.id);assert.equal(job.applied,true,job.applicationError);assert.equal(g.state.nodes.length,2);assert.equal(g.state.nodes[1].id,id);assert.deepEqual(Array.from(job.resultIds),[id]);assert.equal(g.posts.length,1);
});
test('presentation exposes every approved parameter and independent editing semantics in detail, concise action in label',async()=>{
 const {toolPresentation}=await import('../src/features/agent-execution/presentation.mjs');const view=toolPresentation({name:'generation_submit',args:input,status:'pending'});assert.equal(view.label,'等待确认：图片打光 · source');for(const value of ['top_front_right_45','45°','100%','3000 K','开启','low_back_45','-45°','独立打光','结果尺寸由模型决定'])assert(view.detail.includes(value),value);assert(!view.detail.includes('积分'));
});

test('preexisting selections are rejected and modified results never duplicate on application retry',async t=>{
 const {captureAgentRelightApproval}=await import('../src/features/agent-generation/relight.mjs');
 for(const key of ['crop','imageCrop','clip','trim','selection','imageSelection','region']){const f=await fixture(t);f.source[key]={x:1};assert.throws(()=>captureAgentRelightApproval(input,{app:f.app}),/选区导出/);assert.equal(f.service.jobs.size,0);assert.deepEqual(f.assetReads,[]);}
 const f=await fixture(t);f.setSaveFailure(true);await f.execute(input,{mode:'auto'});const job=await f.settled();f.setSaveFailure(false);f.state.nodes[1].fullImage='asset:changed-result';await f.runner.run(job.id);assert.match(job.applicationError,/结果已变化/);assert.equal(job.applied,false);assert.equal(f.state.nodes.length,2);assert.equal(f.posts.length,1);
});

test('isolated QA helper uses traced approval, real task API and durable receipt with independent disclosure',async t=>{
 const f=await fixture(t),receipt=await f.executeQa();assert.equal(receipt.result.taskId,f.persisted.submittedTaskId);assert.match(f.trace.relightDisclosure,/独立打光/);assert.equal((await f.settled()).applied,true);assert.equal(f.posts.length,1);assert.deepEqual(f.posts[0].parameters,lighting);
});

test('shared local QA server feeds production Agent transport and actual client dispatch into the real generation HTTP gateway',async t=>{
 const f=await fixture(t),{requestAgent}=await import('../src/features/agent-stream/transport.mjs'),binding={projectId:'qa-relight-project',chatId:'qa-relight-chat'},transport={fetchImpl:(url,options)=>fetch(f.base+url,options)};
 const turn=await requestAgent('turn',{binding,message:'打光协议验收'},transport);assert.equal(turn.calls[0].args.kind,'image.relight');assert.deepEqual(turn.calls[0].args.relight,lighting);const receipt=await f.execute(turn.calls[0].args,{mode:'auto'});
 const continued=await requestAgent('continue',{binding,sessionId:turn.sessionId,results:[receipt]},transport);assert.equal(continued.done,true);assert.equal((await f.settled()).applied,true);assert.equal(f.posts.length,1);assert.equal(f.agentFixture.requests.length,2);assert.match(continued.text,/只证明提交/);
});

test('full UI Agent fixture fixes only model replies and checks durable task identity before forwarding generation',async()=>{
 const file=fs.readFileSync(path.join(root,'src/features/agent-generation/qa/relight-agent-fixture.js'),'utf8'),forwarded=[];let recordedId='task-a';
 const context={URL,Headers,Response,structuredClone,crypto:globalThis.crypto,document:{baseURI:'http://localhost:49799/'},location:{href:'http://localhost:49799/',origin:'http://localhost:49799'},AgentTools:{parse},RelightFixture:{ready:true},CanvasProjects:{id:()=> 'qa-project'},CanvasStore:{readRecord:async key=>{assert.equal(key,'agent-conversations:qa-project');return {chats:[{messages:[{name:'generation_submit',args:{kind:'image.relight'},submittedTaskId:recordedId}]}]};}},fetch:async(url,options)=>{forwarded.push({url,options});return Response.json({status:'succeeded',outputs:[]});}};context.window=context;vm.runInNewContext(file,context);
 const turn=await context.fetch('/api/agent/turn',{method:'POST',body:JSON.stringify({binding:{projectId:'qa-project',chatId:'chat'}})}).then(r=>r.json());assert.deepEqual(turn.calls[0].args.relight,lighting);assert.equal(forwarded.length,0);
 await context.fetch('/api/generation/tasks',{method:'POST',headers:{'Idempotency-Key':'task-a'},body:'{}'});assert.equal(forwarded.length,1);assert.equal(context.RelightAgentFixture.generationReceipts[0].acknowledged,true);recordedId='other-task';await assert.rejects(context.fetch('/api/generation/tasks',{method:'POST',headers:{'Idempotency-Key':'task-b'},body:'{}'}),/派发前原任务ID/);assert.equal(forwarded.length,1);
 await assert.rejects(context.fetch('/api/agent/other',{method:'POST',body:'{}'}),/未声明/);assert.equal(forwarded.length,1);context.RelightAgentFixture.setLighting({...lighting,temperatureK:8000});assert.equal(context.RelightAgentFixture.lighting.temperatureK,8000);assert.throws(()=>context.RelightAgentFixture.setLighting({...lighting,temperatureK:6500}));
});

async function actualApprovalFixture({initial=null,refreshGate,configurationGate}={}){
 const native=createOpenAIRelightProvider({apiKey:'nonsecret-local-fixture',modelMap:{'image.relight':{kind:'image.relight',model:'gpt-image-2',semantics:'parameter-prompt-edit',quality:'high',outputSize:'auto'}},fetchImpl:()=>assert.fail('metadata-only')}).metadata;
 let current=initial==='missing'?{...native,configured:false,missing:['GENERATION_API_KEY']}:initial,reads=0,mediaReads=0,created=0,project='qa-project';
 const routing=await import('../src/features/node-composer/provider-configuration.mjs'),localProvider={},service={provider:localProvider,jobs:new Map()};
 const configContext={AbortSignal,structuredClone,serverConfigured:false,serverConfigurationSnapshot:null,serverConfigurationRevision:0,localProvider,service,providerConfigurationReady:Promise.resolve(routing),taskNativeConfigurations:new Map(),taskConfigurationIds:new Map(),fetch:async url=>{assert.equal(url,'/api/generation/config');reads++;if(reads>1&&refreshGate)await refreshGate.promise;return Response.json(current);}};
 const configStart=ui.indexOf('  function refreshServerConfiguration('),configEnd=ui.indexOf('  function submitJob(',configStart);
 vm.runInNewContext(ui.slice(configStart,configEnd)+'\nthis.api={availability,configuration,configurationSnapshot};',configContext);
 assert.deepEqual(await configContext.api.configuration(),current);
 current=native;
 const controller=new AbortController(),source={id:'source',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},state={nodes:[source],edges:[]},app={getState:()=>state,projectIdentity:()=>({id:project}),createConnected:()=>{created++;assert.fail('approval must not create a result');}},run={},d={activeRun:null};d.activeRun=run;let active=d;
 const api={...configContext.api,configuration:async()=>{const value=await configContext.api.configuration();if(configurationGate)await configurationGate.promise;return value;}};
 const context={app,call:{name:'generation_submit',args:structuredClone(input)},runController:controller,d,run,draft:()=>active,window:{GenerationAPI:api,LocalAssets:{url:()=>{mediaReads++;assert.fail('approval must not read media');}}},DOMException,modules:name=>import(path.join(root,name))};
 const start=client.indexOf("     if(call.name==='generation_submit'&&call.args.kind==='image.relight'){"),end=client.indexOf('     const executionOptions=',start),fragment=client.slice(start,end).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');
 vm.runInNewContext('async function prepare(){let relightNotice,relightConfiguration,relightApprovalGuard;'+fragment+'return {relightNotice,relightConfiguration,relightApprovalGuard};}',context);
 return {prepare:context.prepare,source,state,controller,call:context.call,native,service,get reads(){return reads;},get mediaReads(){return mediaReads;},get created(){return created;},setProject:value=>project=value,switchChat:()=>active={},switchRun:()=>d.activeRun={},snapshot:configContext.api.configurationSnapshot};
}
test('actual client approval refreshes a previously null or missing cache before disclosing current valid configuration',async()=>{
 for(const initial of [null,'missing']){const f=await actualApprovalFixture({initial}),approved=await f.prepare();assert.deepEqual(JSON.parse(approved.relightConfiguration),f.native);assert.deepEqual(f.snapshot(),f.native);assert.match(approved.relightNotice,/独立打光/);assert(!approved.relightNotice.includes('无法确认'));assert.equal(f.reads,2);assert.equal(f.mediaReads,0);assert.equal(f.created,0);assert.equal(f.service.jobs.size,0);}
});
test('actual client approval guards source and conversation across config refresh and snapshot reads without media or tasks',async()=>{
 for(const phase of ['refreshGate','configurationGate'])for(const mutation of ['same-id','source','project','chat','run','parameters','cancel']){
  const gate=deferred(),f=await actualApprovalFixture({[phase]:gate}),pending=f.prepare();await tick();
  if(mutation==='same-id')f.state.nodes[0]={...f.source};else if(mutation==='source')f.source.fullImage='asset:changed';else if(mutation==='project')f.setProject('other');else if(mutation==='chat')f.switchChat();else if(mutation==='run')f.switchRun();else if(mutation==='parameters')f.call.args.relight.temperatureK=8000;else f.controller.abort();
  gate.resolve();await assert.rejects(pending);assert.equal(f.mediaReads,0);assert.equal(f.created,0);assert.equal(f.service.jobs.size,0);
 }
 const f=await actualApprovalFixture();f.switchChat();await assert.rejects(f.prepare(),{name:'AbortError'});assert.equal(f.reads,1,'changed conversation must fail before refresh');
});
