const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const resources=path.resolve(__dirname,'../src/features/agent-apps/resources'),proxy=fs.readFileSync(path.join(resources,'mcp-app-proxy.html'),'utf8');
async function load(name,version){
 const fetched=[],errors=[];let imported=0,complete;const done=new Promise(resolve=>{complete=resolve;}),inner={};Object.defineProperty(inner,'srcdoc',{set(value){complete({value});}});
 const context=vm.createContext({location:{pathname:'/src/features/agent-apps/resources/mcp-app-proxy.html'},inner,resourceLoaded:false,currentNonce:null,parentOrigin:'*',manifestPromise:null,stopProxyReadyAnnouncements(){},fetch:async url=>{fetched.push(url);const local=path.resolve(resources,url),data=fs.readFileSync(local,'utf8');assert.equal(local.startsWith(resources+path.sep),true);return {ok:true,json:async()=>JSON.parse(data),text:async()=>data};},localizeProductKitTransport:v=>v,localizeEcommerceBilling:v=>v,localizePrevisBilling:v=>v,buildCspPolicy:()=>"default-src 'none'",buildSrcdocWithCsp:(html,policy)=>{assert.equal(policy,"default-src 'none'");return html;},notifyParent:(method,params)=>{errors.push({method,params});complete({error:params.message});}});
 const a=proxy.indexOf('var RESOURCE_NAME_REGEX'),b=proxy.indexOf('// 注意: 本 proxy',a),c=proxy.indexOf('function handleResourceReady('),d=proxy.indexOf('window.addEventListener("message"',c);
 new vm.Script(proxy.slice(a,b)+proxy.slice(c,d)+';handleResourceReady({nonce:"qa-real-disk",resource:{name:'+JSON.stringify(name)+',version:'+JSON.stringify(version)+'}},"http://localhost:4173");',{importModuleDynamically(){imported++;throw Error('historical resource must not invoke v2 adapter');}}).runInContext(context);
 let timer;try{const output=await Promise.race([done,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('loader timed out')),1000);})]);return {...output,fetched,errors,imported};}finally{clearTimeout(timer);}
}
test('actual proxy loader resolves animatic v1 manifest and original disk resource without v2 adapter',async()=>{const result=await load('animatic','v1'),manifest=JSON.parse(fs.readFileSync(path.join(resources,'apps/manifest.json'),'utf8')),filename='animatic@v1.'+manifest.widgets['animatic@v1']+'.html',original=fs.readFileSync(path.join(resources,'apps',filename),'utf8');assert.equal(result.error,undefined);assert.deepEqual(result.errors,[]);assert.deepEqual(result.fetched,['./apps/manifest.json','./apps/'+filename]);assert.equal(result.imported,0);assert.equal(result.value,original);assert.match(result.value,/AN1 v=1;a=confirm/);});
test('historical blocking also resolves its own preserved disk HTML unchanged',async()=>{const result=await load('character-blocking','v1'),manifest=JSON.parse(fs.readFileSync(path.join(resources,'apps/manifest.json'),'utf8')),filename='character-blocking@v1.'+manifest.widgets['character-blocking@v1']+'.html';assert.equal(result.error,undefined);assert.equal(result.imported,0);assert.equal(result.value,fs.readFileSync(path.join(resources,'apps',filename),'utf8'));});
