const test = require('node:test'), assert = require('node:assert/strict'), zlib = require('node:zlib');
const runtimeModule = import('../src/features/agent-apps/actor-guide-runtime.mjs'), helperModule = import('../src/features/agent-apps/actor-emotion.mjs');
function crc(bytes) {let c=0xffffffff;for(const byte of bytes){c^=byte;for(let i=0;i<8;i++)c=c>>>1^(c&1?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(kind,bytes){const b=Buffer.alloc(bytes.length+12);b.writeUInt32BE(bytes.length);b.write(kind,4);bytes.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(){const h=Buffer.alloc(13);h.writeUInt32BE(512);h.writeUInt32BE(512,4);h[8]=8;h[9]=2;const pixels=Buffer.alloc(512*1537);for(let y=0;y<512;y++)pixels.fill(100+y%80,y*1537+1,(y+1)*1537);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
async function fixture(overrides={}) {
 const {createActorGuideRuntime}=await runtimeModule, helper=await helperModule;
 const source={id:'source',type:'video',video:'asset:source',x:5,y:6,width:446,height:250}, actor={id:'actor',type:'image',image:'asset:actor',x:12,y:13,width:200,height:200};
 const graph={nodes:[source,actor],edges:[]}, assets=new Map(), blobs=new Map(), counters={put:0,add:0,save:0,flush:0,conversation:0,decode:0,revoke:0};let active=true,project='project',serial=0;
 const data=helper.prepareActorEmotion({mode:'video',scene:'告别',source:{node_ref:'node/source',media_kind:'video'},actor:{binding_id:'aem_0123456789abcdef',name:'林岚',role:'主角',reference_nodes:[{node_ref:'node/actor',preview_url:'https://example.org/a.png'}]},face:{valence:-50,stance:-20,intensity:60},voice:{preset:'tender',intensity:40}});
 const trace={id:'trace',result:{response:data},appState:helper.initialActorEmotionState(data)},chat={id:'chat'};
 const app={getState:()=>graph,createConnected(id,outputs){counters.add++;const node={...structuredClone(outputs[0]),id:'guide-'+(++serial)};graph.nodes.push(node);graph.edges.push({id:'edge-'+serial,source:id,target:node.id});return[node];}};
 const localAssets={put:async blob=>{counters.put++;const id='asset:guide-'+counters.put;assets.set(id,blob);await overrides.onPut?.();return id;},url:async id=>{if(!assets.has(id))throw Error('missing asset');return id;}};
 const adapters={app,localAssets,store:{save:async()=>{counters.save++;await overrides.onSave?.();return true;},flush:async()=>{counters.flush++;}},getProjectId:()=>project,persistConversation:async()=>{counters.conversation++;await overrides.onConversation?.(counters.conversation);},createObjectURL:blob=>{const id='blob:test-'+(++serial);blobs.set(id,blob);return id;},revokeObjectURL:url=>{counters.revoke++;blobs.delete(url);},fetchImpl:async url=>({ok:assets.has(url),blob:async()=>assets.get(url)}),decodeImage:async url=>{counters.decode++;const blob=blobs.get(url);assert.ok(blob instanceof Blob);const bytes=Buffer.from(await blob.arrayBuffer());const length=bytes.readUInt32BE(33);assert.equal(zlib.inflateSync(bytes.subarray(41,41+length)).length,512*1537);await overrides.onDecode?.();return overrides.dimensions||{width:512,height:512};}};
 if(overrides.preparePreviews)adapters.preparePreviews=overrides.preparePreviews;
 const runtime=createActorGuideRuntime(adapters),context=runtime.capture(data,{trace,chat,isCurrent:()=>active});
 const args={binding:data.actor.binding_id,mode:data.mode,source_node_ref:data.source.node_ref,actor_reference_node_refs:['node/actor'],face:trace.appState.face,locale:data.locale,image_data_uri:'data:image/png;base64,'+png().toString('base64')};
 const options={callId:'actor-emotion-test-call',isCurrent:()=>active,sourceContext:context};
 return{runtime,context,args,options,trace,chat,source,actor,graph,assets,counters,adapters,setActive:value=>active=value,setProject:value=>project=value,save:()=>runtime.save(args,trace,chat,options)};
}
test('guide bytes persist to LocalAssets; real graph ID and durable conversation precede receipt',async()=>{const f=await fixture(),r=await f.save();assert.equal(r.node_ref,'node/'+f.graph.nodes[2].id);assert.equal(f.trace.actorExpressionGuide.node_ref,r.node_ref);assert.deepEqual([...Object.keys(r)].sort(),['binding','face','guide_sha256','node_ref']);assert.equal(f.counters.add,1);assert.equal(f.counters.put,1);assert.equal(f.counters.save,1);assert.equal(f.counters.flush,1);assert.equal(f.counters.conversation,1);assert.deepEqual(Buffer.from(await f.assets.get(f.graph.nodes[2].image).arrayBuffer()),png());assert.ok(f.counters.decode>=2);assert.equal(f.counters.revoke,f.counters.decode);});
test('normal dragging does not invalidate source snapshots',async()=>{const f=await fixture();f.source.x+=25;f.source.y-=12;f.actor.x+=30;f.actor.selected=true;assert.doesNotThrow(()=>f.context.guard());await f.save();});
test('source media edit, replacement content, deletion, and reference mutation reject before writes',async()=>{for(const mutate of[f=>f.source.video='asset:other',f=>f.graph.nodes[0]={...f.source,video:'asset:other'},f=>f.graph.nodes.splice(0,1),f=>f.actor.image='asset:other']){const f=await fixture();mutate(f);await assert.rejects(f.save());assert.equal(f.counters.put,0);assert.equal(f.counters.add,0);}});
test('source and chat/project changes during LocalAssets write prevent graph insertion',async()=>{for(const change of[f=>f.source.video='asset:changed',f=>f.setActive(false),f=>f.setProject('other')]){let f;f=await fixture({onPut:()=>change(f)});await assert.rejects(f.save());assert.equal(f.counters.put,1);assert.equal(f.counters.add,0);assert.equal(f.trace.actorExpressionGuide,undefined);}});
test('actual image decode failure or wrong dimensions produces no storage/node/receipt',async()=>{for(const options of[{dimensions:{width:256,height:512}},{onDecode:()=>{throw Error('decoder rejected');}}]){const f=await fixture(options);await assert.rejects(f.save());assert.equal(f.counters.put,0);assert.equal(f.counters.add,0);assert.equal(f.counters.revoke,1);}});
test('same call retries save without duplicate assets/nodes and edited call conflicts',async()=>{const f=await fixture(),a=await f.save(),b=await f.save();assert.deepEqual(a,b);assert.equal(f.counters.add,1);assert.equal(f.counters.put,1);f.args={...f.args,face:{...f.args.face,intensity:80}};f.trace.appState={...f.trace.appState,face:f.args.face};await assert.rejects(f.runtime.save(f.args,f.trace,f.chat,f.options),/相同/);});
test('undo/deletion prevents silent recreation of saved guide',async()=>{const f=await fixture();await f.save();f.graph.nodes.pop();await assert.rejects(f.save(),/删除或撤销/);assert.equal(f.counters.add,1);});
test('canvas save failure exposes no successful receipt; explicit retry keeps one node',async()=>{let fail=true;const f=await fixture({onSave:()=>{if(fail)throw Error('disk full');}});await assert.rejects(f.save(),/disk full/);assert.equal(f.trace.actorExpressionGuide,undefined);assert.equal(f.counters.add,1);fail=false;const r=await f.save();assert.equal(r.node_ref,'node/'+f.graph.nodes[2].id);assert.equal(f.counters.add,1);assert.equal(f.counters.put,1);});
test('conversation durability failure rolls back receipt then retries same visible node',async()=>{const f=await fixture({onConversation:n=>{if(n===1)throw Error('conversation failed');}});await assert.rejects(f.save(),/conversation failed/);assert.equal(f.trace.actorExpressionGuide,undefined);assert.equal(f.counters.conversation,2);assert.equal(f.counters.add,1);await f.save();assert.equal(f.counters.add,1);assert.ok(f.trace.actorExpressionGuide);});
test('post-insertion scope change persists graph and refuses success/trace receipt',async()=>{let f;f=await fixture({onSave:()=>f.setActive(false)});await assert.rejects(f.save(),/切换/);assert.equal(f.counters.add,1);assert.equal(f.counters.save,1);assert.equal(f.counters.flush,1);assert.equal(f.trace.actorExpressionGuide,undefined);});
test('restored runtime validates saved node/hash and rejects media mutation across reload',async()=>{const f=await fixture();await f.save();const restored=(await runtimeModule).createActorGuideRuntime(f.adapters),context=restored.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true});await context.validateGuideCurrent(context.readGuide());f.actor.image='asset:modified';const changed=restored.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true});await assert.rejects(changed.validateGuideCurrent(changed.readGuide()),/来源已变化/);});
test('restored runtime verifies actual saved asset bytes rather than filename or old hash',async()=>{const f=await fixture();await f.save();const node=f.graph.nodes[2];f.assets.set(node.image,new Blob(['not actual png'],{type:'image/png'}));await assert.rejects(f.context.validateGuideCurrent(f.context.readGuide()),/实际字节/);});
test('state changes during async decode reject before storage and graph write',async()=>{let f;f=await fixture({onDecode:()=>{f.trace.appState={...f.trace.appState,face:{...f.trace.appState.face,intensity:20}};}});await assert.rejects(f.save(),/保存状态/);assert.equal(f.counters.put,0);assert.equal(f.counters.add,0);});

test('show_app reference previews derive exclusively from real node media and replace caller URL',async()=>{
 const f=await fixture();
 // Fixture LocalAssets normally returns asset IDs; use a real inline source here.
 f.adapters.localAssets.url=async id=>{assert.equal(id,'asset:actor');return 'data:image/png;base64,'+png().toString('base64');};
 f.adapters.preparePreviews=async(items,{resolveUrl})=>{assert.deepEqual(items,[{name:'actor',type:'image',asset:'asset:actor'}]);const source=await resolveUrl(items[0].asset);assert.match(source,/^data:image\/png;base64,/);return[{name:'actor',imageUrl:source}];};
 const runtime=(await runtimeModule).createActorGuideRuntime(f.adapters),args={resource_uri:'ui://tapnow/actor-emotion@v1',data:{...f.trace.result.response,actor:{...f.trace.result.response.actor,reference_nodes:[{node_ref:'node/actor',preview_url:'https://evil.test/unrelated.png'}]}}};
 const result=await runtime.prepareAppArgs(args);assert.match(result.data.actor.reference_nodes[0].preview_url,/^data:image\/png;base64,/);assert.equal(args.data.actor.reference_nodes[0].preview_url,'https://evil.test/unrelated.png');assert.equal(f.counters.put,0);assert.equal(f.counters.add,0);
});
test('preview generation rejects missing refs, stale content, cancellation and mismatched actual preview',async()=>{
 for(const kind of ['stale','wrong','cancel']){let f;const controller=new AbortController();f=await fixture({preparePreviews:async()=>{if(kind==='stale')f.actor.image='asset:changed';if(kind==='cancel')controller.abort();return[{name:kind==='wrong'?'unrelated':'actor',imageUrl:'data:image/png;base64,'+png().toString('base64')}];}});await assert.rejects(f.runtime.prepareAppArgs({resource_uri:'ui://tapnow/actor-emotion@v1',data:f.trace.result.response},{signal:controller.signal}));assert.equal(f.counters.put,0);}
 const f=await fixture(),data=structuredClone(f.trace.result.response);data.actor.reference_nodes=[{node_ref:'node/absent'}];await assert.rejects(f.runtime.prepareAppArgs({resource_uri:'ui://tapnow/actor-emotion@v1',data}),/真实图片/);
});
test('preview preparation passes other application arguments through unchanged',async()=>{const f=await fixture(),args={resource_uri:'ui://tapnow/director-markup@v1',data:{draft:'正文'}};assert.equal(await f.runtime.prepareAppArgs(args),args);});

test('prepared result persists original source fingerprints and rejects reload rebinding after source edit',async()=>{
 const f=await fixture({preparePreviews:async()=>[{name:'actor',imageUrl:'data:image/png;base64,'+png().toString('base64')}]});
 const args=await f.runtime.prepareAppArgs({resource_uri:'ui://tapnow/actor-emotion@v1',data:f.trace.result.response});
 const result=f.runtime.bindPreparedResult({response:f.trace.result.response},args);assert.equal(result.actorSourceContext.projectId,'project');assert.equal(result.actorSourceContext.sourceSnapshots.length,2);
 f.trace.result=structuredClone(result);f.source.x+=50;assert.doesNotThrow(()=>f.runtime.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true}));
 f.actor.image='asset:changed';assert.throws(()=>f.runtime.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true}),/来源或参考已变化/);
});
test('binding prepared app result requires host preparation and rejects media edits between preparation and commit',async()=>{
 const f=await fixture({preparePreviews:async()=>[{name:'actor',imageUrl:'data:image/png;base64,'+png().toString('base64')}]});
 const original={resource_uri:'ui://tapnow/actor-emotion@v1',data:f.trace.result.response};assert.throws(()=>f.runtime.bindPreparedResult({response:original.data},original),/原始真实来源/);
 const args=await f.runtime.prepareAppArgs(original);f.source.video='asset:changed';assert.throws(()=>f.runtime.bindPreparedResult({response:original.data},args),/来源或参考已变化/);
});

test('official repeated confirmation with a fresh callId reuses identical saved guide pixels',async()=>{const f=await fixture(),a=await f.save(),b=await f.runtime.save(f.args,f.trace,f.chat,{...f.options,callId:'actor-emotion-test-new-call'});assert.deepEqual(a,b);assert.equal(f.counters.put,1);assert.equal(f.counters.add,1);});

test('controller guard and readGuide preserve true/identity contract',async()=>{const f=await fixture();assert.equal(f.context.guard(),true);await f.save();assert.equal(f.context.readGuide(),f.trace.actorExpressionGuide);assert.equal(f.context.readGuide(),f.context.readGuide());});
test('concurrent distinct callIds coalesce identical guide content before LocalAssets write',async()=>{let release;const barrier=new Promise(resolve=>release=resolve);const f=await fixture({onPut:()=>barrier});const a=f.save(),b=f.runtime.save(f.args,f.trace,f.chat,{...f.options,callId:'actor-emotion-test-second-call'});await new Promise(resolve=>setTimeout(resolve,20));release();assert.deepEqual(await a,await b);assert.equal(f.counters.put,1);assert.equal(f.counters.add,1);});

test('cached app/runtime imports initialize before LocalAssets script and resolve live assets only when actor uses them',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8');
 const start=source.indexOf(' function actorAssetStore()'),end=source.indexOf(" appCardsReady.catch",start);
 assert.ok(start>0&&end>start);const bootstrap=source.slice(start,end).replace(/import\(([^\n]*?)\)/g,'__import($1)');
 const runtime=await runtimeModule,window={},calls=[],app={getState:()=>({nodes:[],edges:[]}),createConnected(){}};
 const context=vm.createContext({window,app,canvasPersistence:{save:async()=>{},flush:async()=>{}},project:{id:'project'},panel:null,save:()=>true,flushConversation:async()=>{},draft:()=>({id:'chat'}),queueWidgetPrompt(){},saveAppState(){},getActorSourceContext(){},saveExpressionGuide(){},notice(){},render(){},__import:async uri=>uri.endsWith('integration.mjs')?{createAppController:()=>{calls.push('controller');return {};}}:runtime});
 vm.runInContext(bootstrap+';globalThis.ready=appCardsReady;globalThis.assets=actorAssets;globalThis.runtime=()=>actorGuideRuntime;',context);
 await context.ready;assert.deepEqual(calls,['controller']);assert.ok(context.runtime());assert.equal(window.LocalAssets,undefined);
 assert.throws(()=>context.assets.put(new Blob(['data'])),/本地素材存储尚未就绪/);
 window.LocalAssets={put:async blob=>{assert.equal(blob.size,4);return 'asset:late-ready';},url:async id=>'blob:'+id};
 assert.equal(await context.assets.put(new Blob(['data'])),'asset:late-ready');assert.equal(await context.assets.url('asset:late-ready'),'blob:asset:late-ready');
 window.LocalAssets={put:async()=> 'asset:new-store',url:async()=> 'blob:new-store'};assert.equal(await context.assets.put(new Blob(['data'])),'asset:new-store');
});
