const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cryptoNode=require('node:crypto');
const modelPromise=import('../src/features/agent-apps/character-blocking-v1.mjs'),runtimePromise=import('../src/features/agent-apps/character-blocking-v1-runtime.mjs');
const htmlPath=require.resolve('../src/features/agent-apps/resources/apps/character-blocking@v1.596deb3b.html');
function official(){
 const source=fs.readFileSync(htmlPath,'utf8'),context={};vm.createContext(context);
 const helpers=source.slice(source.indexOf('function lr(e)'),source.indexOf('const Am=')),locales=source.slice(source.indexOf('const Am='),source.indexOf(',Lm=document.getElementById')),summary=source.slice(source.indexOf('function Ue(e)'),source.indexOf('async function r$()'));
 vm.runInContext('const He=50,Zm=/^[a-z0-9][a-z0-9_-]{0,23}$/;let B,D,rt,Ee,people=[];function je(){return people;}function F_(e,n){let r=e;for(const[o,t]of Object.entries(n))r=r.split(`{${o}}`).join(String(t));return r;}'+helpers+locales+';'+summary+';globalThis.official={positions:Ss,token:L_,region:Z_,nudge:A_,locales:Am,message:(data,state)=>{people=data.characters;B=state.positions;D=Am[data.locale];rt=state.target;Ee=state.aspect_ratio;return n$()+" — "+L_(people.map(c=>c.id),B,rt,Ee);}};',context);return context.official;
}
const input=(locale='zh-CN')=>({locale,target:'image',aspect_ratio:'16:9',scene:'两人在车站一前一后',characters:[{id:'lin',name:'林岚',role:'旅客',x:300,y:600},{id:'zhou',name:'周宁',x:750,y:450}]});
test('preserved historical v1 HTML hash and actual CB1 position/state functions remain distinct from v3',async()=>{
 const m=await modelPromise,o=official(),source=fs.readFileSync(htmlPath,'utf8');assert.equal(cryptoNode.createHash('sha256').update(source).digest('hex'),'596deb3b4e840b54f9636d8641a00b1a698f02db7877a8fca94d42163cb68d24');
 const data=m.prepareCharacterBlockingV1(input()),state=m.initialCharacterBlockingV1State(data);assert.equal(data.version,1);assert.ok(!('facings'in state));assert.ok(!('facing'in data.characters[0]));assert.ok(!('portrait'in data.characters[0]));assert.deepEqual(state.positions,JSON.parse(JSON.stringify(o.positions(null,Object.fromEntries(data.characters.map(c=>[c.id,{x:c.x,y:c.y}]))))));
 assert.equal(m.characterBlockingV1Token(data,state),'CB1 v=1;target=image;ratio=16:9;pos=lin~300~600,zhou~750~450');assert.match(source,/function K_\(\)\{return\{positions:[\s\S]*?selected_id:Ne,snap:we,target:rt,aspect_ratio:Ee\}\}/);assert.deepEqual(JSON.parse(JSON.stringify(o.nudge({x:333,y:667},'right',{fine:false,snap:true}))),{x:400,y:650});
});
test('v1 exact shipped locale summary/token agree across coordinates, targets and ratios; stale or altered messages reject',async()=>{
 const m=await modelPromise,o=official();
 for(const locale of m.characterBlockingV1Locales){const data=m.prepareCharacterBlockingV1(input(locale)),state=m.initialCharacterBlockingV1State(data);
  for(const target of ['image','video'])for(const ratio of m.characterBlockingV1Ratios)for(const coordinate of [0,333,334,666,667,1000]){state.target=target;state.aspect_ratio=ratio;state.positions.lin={x:coordinate,y:coordinate};const message=o.message(data,state);assert.equal(m.characterBlockingV1Confirmation(data,state),message);assert.equal(m.characterBlockingV1Token(data,state),o.token(['lin','zhou'],state.positions,target,ratio));assert.equal((await m.resolveCharacterBlockingV1Reply(message,data,state)).kind,'confirmed');}
  const message=o.message(data,state),changed=structuredClone(state);changed.positions.lin.x=999;await assert.rejects(m.resolveCharacterBlockingV1Reply(message,data,changed));for(const bad of [message+' tool=delete','CB1 v=1',message.replace('CB1 v=1','CB3 v=3'),'已完成视频 '+message])await assert.rejects(m.resolveCharacterBlockingV1Reply(bad,data,state));await assert.rejects(m.resolveCharacterBlockingV1Reply(message,data,undefined));assert.deepEqual(await m.resolveCharacterBlockingV1Reply(o.locales[locale].reviseMsg,data,undefined),{kind:'revise',text:o.locales[locale].reviseMsg,metadata:{}});
 }
});
test('v1 rejects v3 facing/portrait schemas, incomplete saved positions and hidden permission fields',async()=>{
 const m=await modelPromise,data=m.prepareCharacterBlockingV1(input()),state=m.initialCharacterBlockingV1State(data);
 for(const bad of [{tools:['delete']},{version:3},{locale:'xx'},{target:'audio'},{aspect_ratio:'2:1'},{characters:[]},{characters:[{...input().characters[0],id:'A'}]},{characters:[{...input().characters[0],x:1.2}]},{characters:[{...input().characters[0],facing:180}]},{characters:[{...input().characters[0],portrait:{data_uri:'data:image/webp;base64,AAAA',source:'image-crop'}}]},{characters:[{...input().characters[0],portrait_source:{node_ref:'node/photo'}}]},{characters:[input().characters[0],input().characters[0]]}])assert.throws(()=>m.prepareCharacterBlockingV1({...input(),...bad}));
 for(const bad of [{facings:{lin:90,zhou:270}},{positions:{lin:state.positions.lin}},{positions:{...state.positions,ghost:{x:0,y:0}}},{positions:{...state.positions,lin:{x:0,y:0,z:1}}},{selected_id:'ghost'},{snap:'true'},{target:'audio'},{aspect_ratio:'2:1'}])assert.throws(()=>m.validateCharacterBlockingV1State({...state,...bad},data));
});
test('stable v1 handoff preserves source array order and ignores only view state; local output does not invent angles/photos/media',async()=>{
 const m=await modelPromise,data=m.prepareCharacterBlockingV1(input()),state=m.initialCharacterBlockingV1State(data),message=m.characterBlockingV1Confirmation(data,state),receipt=await m.resolveCharacterBlockingV1Reply(message,data,state),view={...state,positions:{zhou:state.positions.zhou,lin:state.positions.lin},snap:true,selected_id:'zhou'};
 assert.match(receipt.metadata.handoffId,/^blocking1_[a-f0-9]{64}$/);assert.equal((await m.resolveCharacterBlockingV1Reply(message,data,view)).metadata.handoffId,receipt.metadata.handoffId);assert.equal(receipt.result.version,1);assert.deepEqual(receipt.result.characters.map(c=>c.id),['lin','zhou']);assert.ok(receipt.result.characters.every(c=>!('facing'in c)&&!('portrait'in c)));assert.match(receipt.text,/没有头像或面向数据/);assert.match(receipt.text,/现有普通队列与生成API/);
 for(const update of [{target:'video'},{aspect_ratio:'9:16'},{positions:{...state.positions,lin:{x:301,y:600}}}]){const next={...state,...update};assert.notEqual((await m.resolveCharacterBlockingV1Reply(m.characterBlockingV1Confirmation(data,next),data,next)).metadata.handoffId,receipt.metadata.handoffId);}
 const renamed=m.prepareCharacterBlockingV1({...input(),scene:'新场景'});assert.notEqual((await m.resolveCharacterBlockingV1Reply(message,renamed,state)).metadata.handoffId,receipt.metadata.handoffId);
});
async function fixture(){const m=await modelPromise,{createCharacterBlockingV1Runtime}=await runtimePromise;let project='p1',current=true;const runtime=createCharacterBlockingV1Runtime({getProjectId:()=>project}),args={resource_uri:m.characterBlockingV1Uri,data:input()},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>current}),result=runtime.bindPreparedResult({kind:'mcp_app',resource_uri:m.characterBlockingV1Uri,response:m.prepareCharacterBlockingV1(prepared.data)},prepared),trace={id:'trace_v1',name:'show_app',status:'done',args:{resource_uri:m.characterBlockingV1Uri},result,appState:m.initialCharacterBlockingV1State(result.response)},chat={id:'chat_v1'},context=runtime.capture(result.response,{trace,chat,isCurrent:()=>current});return {m,runtime,args,prepared,result,trace,chat,context,setProject:value=>{project=value;},setCurrent:value=>{current=value;}};}
test('v1 runtime binds actual text input, restores saved host source, and never reads media or calls a model',async()=>{
 const originalFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('v1 must not network');};try{const f=await fixture(),state=f.trace.appState;await f.context.guard();const reply=await f.context.reply(f.m.characterBlockingV1Confirmation(f.result.response,state),state);assert.equal(reply.kind,'confirmed');const saved=structuredClone({trace:f.trace,chat:f.chat}),restored=f.runtime.capture(saved.trace.result.response,{trace:saved.trace,chat:saved.chat,isCurrent:()=>true});await restored.guard();restored.dispose();assert.throws(()=>f.runtime.bindPreparedResult(f.result,{...f.prepared}),/绑定/);}finally{globalThis.fetch=originalFetch;}
});
test('v1 handoff reads only actual saved trace state and rejects replacement/mutation during asynchronous receipt hashing',async()=>{
 const f=await fixture(),unsaved=structuredClone(f.trace.appState);unsaved.positions.lin.x=900;await assert.rejects(f.context.reply(f.m.characterBlockingV1Confirmation(f.result.response,unsaved),unsaved),/实际保存/);await assert.rejects(f.context.reply(f.m.characterBlockingV1Confirmation(f.result.response,f.trace.appState),structuredClone(f.trace.appState)),/实际保存/);
 for(const replace of [false,true]){
  const f=await fixture(),saved=f.trace.appState,message=f.m.characterBlockingV1Confirmation(f.result.response,saved),descriptor=Object.getOwnPropertyDescriptor(globalThis,'crypto'),original=globalThis.crypto;let release,started;const gate=new Promise(resolve=>{release=resolve;}),begun=new Promise(resolve=>{started=resolve;});
  Object.defineProperty(globalThis,'crypto',{configurable:true,value:{subtle:{digest:async(...args)=>{started();await gate;return original.subtle.digest(...args);}}}});
  try{const pending=f.context.reply(message,saved);await begun;if(replace)f.trace.appState=structuredClone(saved);else saved.positions.lin.x=900;release();await assert.rejects(pending,/保存状态.*已变化/);}finally{release();Object.defineProperty(globalThis,'crypto',descriptor);}
 }
});
test('wrong URI/context, changed input/scope, abort and disposal cannot reuse a v1 host source',async()=>{
 for(const change of [f=>f.setProject('p2'),f=>f.setCurrent(false),f=>{f.trace.id='other';},f=>{f.chat.id='other';},f=>{f.trace.result.response={...f.result.response};},f=>{f.result.response.characters[0].x=100;},f=>{f.result.characterBlockingV1SourceContext.projectId='other';},f=>{f.trace.args.resource_uri='ui://tapnow/character-blocking@v3';},f=>f.context.dispose()]){const f=await fixture();change(f);await assert.rejects(f.context.guard());assert.equal(f.context.isCurrent(),false);}
 const f=await fixture(),controller=new AbortController();controller.abort();await assert.rejects(f.context.guard(controller.signal));await assert.rejects(f.runtime.prepareAppArgs(f.args,{signal:controller.signal}));assert.throws(()=>f.runtime.capture(f.result.response,{trace:{...f.trace,result:{...f.result,characterBlockingV1SourceContext:undefined}},chat:f.chat,isCurrent:()=>true}));
});
