'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),{once}=require('node:events');
const {TaskService,httpProvider}=require('../generation-api.js'),{parse,definitions}=require('../agent-tools.js');
const root=path.resolve(__dirname,'..'),client=fs.readFileSync(path.join(root,'agent-client.js'),'utf8'),ui=fs.readFileSync(path.join(root,'generation-ui.js'),'utf8');
const input={kind:'image.upscale',nodeId:'source',prompt:'',upscale:{provider:'magnific',scaleFactor:3,sharpen:14,smartGrain:29,ultraDetail:41}},bytes=fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')),result=fs.readFileSync(path.join(root,'qa/agent-image-processing-result.png'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function configuration(){const {magnificProfile}=await import('../src/features/image-upscale/native-profile.mjs');return {configured:true,protocol:'magnific-native',capabilities:{kinds:['image.upscale'],models:{'image.upscale:magnific':{kind:'image.upscale',model:'magnific-v2'}},upscaleMagnific:magnificProfile}};}
async function fixture(t,options={}){
 const {captureAgentUpscaleApproval}=await import('../src/features/agent-generation/upscale.mjs'),{prepareWorkflowInputs}=await import('../src/features/agent-workflows/media-transport.mjs'),{createApplicationRunner}=await import('../src/features/generation-results/application.mjs'),jobs=await import('../src/features/agent-generation/jobs.mjs');
 const config=await configuration(),source={id:'source',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},target={id:'target',type:'image',tool:'enhance',image:'asset:old',params:{activeTab:'upscale',mode:'detailed'}},state={nodes:[source,...(options.existing?[target]:[])],edges:options.existing?[{source:'source',target:'target'}]:[]};let project='p',metadata=config,saveFails=false,saves=0,created=0,trace,persisted;const posts=[],reads=[],records=new Map(),inPlace=new Map();
 const server=http.createServer(async(req,res)=>{
  if(req.url==='/result.png'){res.writeHead(200,{'content-type':'image/png'});res.end(result);return;}
  if(req.method==='GET'){const value=structuredClone(records.get(decodeURIComponent(req.url.split('/').at(-1))));options.recoveryMutation?.(value.request);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value));return;}
  let body='';for await(const chunk of req)body+=chunk;assert(persisted?.submittedTaskId,'durable Agent receipt must precede HTTP');const request=JSON.parse(body);posts.push(request);const value={id:persisted.submittedTaskId,request,status:'succeeded',outputs:[{type:'image',url:base+'/result.png',width:512,height:320}]};records.set(value.id,value);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(options.unknown?{id:value.id,status:'unknown',request}:value));
 });server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;t.after(()=>{server.closeAllConnections();server.close();});
 const full=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));t.after(()=>URL.revokeObjectURL(full));
 const localAssets={url:async key=>{assert(persisted?.submittedTaskId,'durable receipt must precede media');reads.push(key);if(options.mediaGate)await options.mediaGate.promise;assert.equal(key,'asset:full');return full;}};
 const app={getState:()=>state,projectIdentity:()=>({id:project}),createConnected:(id,outputs)=>outputs.map(output=>{created++;const node={...output,id:'result-'+created};state.nodes.push(node);state.edges.push({source:id,target:node.id});return node;}),updateNode:(id,patch)=>Object.assign(state.nodes.find(node=>node.id===id),patch),saveProject:async()=>{saves++;if(options.saveGate)await options.saveGate.promise;if(saveFails)throw Error('disk full');}};
 const service=new TaskService({prepareInputs:async(request,context)=>{context.validateSources();request.inputs[0].url=await localAssets.url(request.inputs[0].url);context.validateSources();request.inputs[0].width=512;request.inputs[0].height=320;return prepareWorkflowInputs(request,{...context,serialize:async blob=>'data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64')});}});service.setProvider(httpProvider({baseUrl:base+'/tasks',recoverable:true}));
 const host={app,service,inPlace,submitJob:(request,settings)=>service.submit(request,options.historyFailure?{...settings,beforeDispatchReady:async()=>{throw Error('history failed');}}:settings),DOMException};vm.runInNewContext(ui.slice(ui.indexOf('  function runInPlace('),ui.indexOf('  function recoverInPlace(')),host);
 const start=ui.indexOf('      if(target?.verifyRequest){'),end=ui.indexOf('      if(!stored.resultIds&&resultWorkflow',start),context={app,inPlace,window:{},audioGuard:()=>{},recordSubtitleMedia:()=>{},validateJobMedia:async output=>assert.deepEqual(Buffer.from(await fetch(output.url).then(r=>r.arrayBuffer())),result),resultProvenance:()=>({provenance:{provider:'isolated-magnific-native',model:'magnific-v2',prompt:''}})};
 vm.runInNewContext('async function apply(job){const stored=job,target=inPlace.get(job.id);'+ui.slice(start,end)+'}',context);
 const runner=createApplicationRunner({getJob:id=>service.jobs.get(id),apply:context.apply,changed:job=>{if(trace)jobs.attachGenerationJob(trace,job);if(!job.applying){const target=inPlace.get(job.id);job.applicationError?target?.reject(Error(job.applicationError)):target?.resolve(job);}}});service.subscribe(job=>{if(job.status==='succeeded')void runner.run(job.id);else if(['failed','cancelled','configuration_required'].includes(job.status))inPlace.get(job.id)?.reject(Error(job.error||job.status));});
 const api={runInPlace:host.runInPlace,cancel:id=>service.cancel(id),availability:async()=>{if(options.availabilityGate)await options.availabilityGate.promise;return {configured:true};},configuration:async()=>metadata,configurationSnapshot:()=>metadata};
 const fragment=client.slice(client.indexOf("  case 'generation_submit':{"),client.indexOf('   if(a.draftSourceId)',client.indexOf("  case 'generation_submit':{"))).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')'),dispatch={app,window:{GenerationAPI:api},modules:name=>import(path.join(root,name))};vm.runInNewContext('async function dispatch(a,signal,onDepthSubmitted,approvedUpscaleConfiguration,upscaleApprovalGuard){switch("generation_submit"){'+fragment+'}default:throw Error("unhandled");}}',dispatch);
 const {executeTracedCall,needsToolConfirmation}=await import('../src/features/agent-execution/trace.mjs');
 async function execute(args=options.existing?{...input,targetNodeId:target.id}:input,{mode='ask',confirm=async()=>true,signal}={}){
  const parsed=parse('generation_submit',structuredClone(args)),call={name:'generation_submit',callId:'magnific-call',args:parsed.args},approvalGuard=captureAgentUpscaleApproval(parsed.args,{app,signal}),approvedConfiguration=JSON.stringify(metadata??null);
  const start=client.indexOf('       const onDepthSubmitted=async job=>'),end=client.indexOf('\n       return execute(',start),ack={d:{messages:[]},call,generationJobs:jobs,save:()=>{if(options.receiptFailure)return false;persisted=structuredClone(trace);return true;},flushConversation:async()=>{if(options.receiptGate)await options.receiptGate.promise;if(options.flushFailure)throw Error('receipt flush failed');},executionRenderer:{updateTrace:()=>{}}};vm.runInNewContext(client.slice(start,end)+'\nthis.acknowledge=onDepthSubmitted;',ack);
  return executeTracedCall(call,{signal,confirm:needsToolConfirmation(parsed.definition,mode)?confirm:null,changed:value=>{trace=value;ack.d.messages=[value];},execute:(_name,args)=>dispatch.dispatch(args,signal,ack.acknowledge,approvedConfiguration,approvalGuard)});
 }
 async function settled(){for(let i=0;i<600;i++){const job=[...service.jobs.values()][0];if(job&&(['failed','cancelled'].includes(job.status)||job.status==='succeeded'&&!job.applying&&job.applicationStatus))return job;await tick();}throw Error('Magnific task did not settle');}
 return {execute,settled,app,api,source,target,state,posts,reads,service,runner,config,get saves(){return saves;},get persisted(){return persisted;},setProject:value=>project=value,setConfiguration:value=>metadata=value,setSaveFailure:value=>saveFails=value};
}
test('Magnific tool schema requires complete controls while keeping existing Topaz dispatch arguments',async()=>{
 const {agentUpscaleParameters}=await import('../src/features/agent-generation/upscale.mjs');
 assert.deepEqual(agentUpscaleParameters(parse('generation_submit',input).args.upscale),input.upscale);
 assert.doesNotThrow(()=>parse('generation_submit',{kind:'image.upscale',nodeId:'source',prompt:'',model:'topazlabs'}));
 for(const patch of [{upscale:{}},{upscale:{...input.upscale,sharpen:undefined}},{upscale:{...input.upscale,scaleFactor:2.1}},{upscale:{...input.upscale,scaleFactor:9}},{upscale:{...input.upscale,smartGrain:-1}},{upscale:{...input.upscale,ultraDetail:101}},{upscale:{...input.upscale,provider:'topazlabs'}},{upscale:{...input.upscale,seed:1}},{prompt:'more detail'},{model:'magnific-v2'},{targetNodeId:'source'},{referenceIds:[]},{referenceIds:['other']},{count:2}])assert.throws(()=>parse('generation_submit',{...input,...patch}));
 assert.throws(()=>parse('generation_submit',{...input,kind:'image.generate'}));
 assert.throws(()=>parse('generation_submit',{kind:'image.generate',nodeId:'source',prompt:'',targetNodeId:'target'}));
});
test('formal approval and durable original receipt precede complete-source HTTP and a saved enhance version',async t=>{
 const gate=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>gate.promise});await tick();assert.equal(f.service.jobs.size,0);assert.deepEqual(f.reads,[]);gate.resolve(true);
 const receipt=await pending,job=await f.settled();assert.equal(receipt.result.taskId,f.persisted.submittedTaskId);assert.equal(job.applied,true,job.applicationError);assert.equal(f.posts.length,1);assert.deepEqual(f.posts[0].parameters,input.upscale);assert.equal(f.posts[0].prompt,'');assert.equal(f.posts[0].inputs[0].role,'source_image');assert.deepEqual([f.posts[0].inputs[0].width,f.posts[0].inputs[0].height],[512,320]);assert.deepEqual(Buffer.from(f.posts[0].inputs[0].url.split(',')[1],'base64'),bytes);assert.deepEqual(f.reads,['asset:full']);
 const target=f.state.nodes[1];assert.equal(target.tool,'enhance');assert.equal(target.params.upscaleProvider,'magnific');assert.equal(target.params.magnificUltraDetail,41);assert.equal(target.versions.length,1);assert.deepEqual(target.versions[0].parameters,input.upscale);assert.equal(f.source.fullImage,'asset:full');assert.equal(f.saves,1);
});
test('new and existing enhance save retries retain original task, node and single output version',async t=>{
 for(const existing of [false,true]){const f=await fixture(t,{existing});f.setSaveFailure(true);await f.execute();const job=await f.settled(),target=f.state.nodes.find(n=>n.tool==='enhance'),versions=structuredClone(target.versions);assert.equal(job.applicationStatus,'failed');assert.equal(target.versions.length,existing?2:1);const id=target.id;
 f.setSaveFailure(false);await f.runner.run(job.id);assert.equal(job.applied,true,job.applicationError);assert.equal(target.id,id);assert.deepEqual(target.versions,versions);assert.equal(f.posts.length,1);assert.equal(f.state.nodes.length,2);assert.equal(f.saves,2);}
});
test('receipt or flush failure blocks source reads and POST; rejection creates no task',async t=>{
 for(const options of [{receiptFailure:true},{flushFailure:true}]){const f=await fixture(t,options),r=await f.execute();assert.match(r.result.error,/保存|flush/);await tick();assert.deepEqual(f.reads,[]);assert.equal(f.posts.length,0);assert.equal(f.state.nodes.length,1);}
 const f=await fixture(t);await f.execute(input,{confirm:async()=>false});assert.equal(f.service.jobs.size,0);assert.equal(f.posts.length,0);
});
test('approval guards source identity, target parameters, incoming edge, project and all explicit controls',async t=>{
 const {captureAgentUpscaleApproval}=await import('../src/features/agent-generation/upscale.mjs');
 for(const mutation of ['source','same-id','target','edge','args','project','region','cancel']){const f=await fixture(t,{existing:true}),args={...structuredClone(input),targetNodeId:'target'},controller=new AbortController(),guard=captureAgentUpscaleApproval(args,{app:f.app,signal:controller.signal});
 if(mutation==='source')f.source.fullImage='asset:other';else if(mutation==='same-id')f.state.nodes[0]={...f.source};else if(mutation==='target')f.target.params.magnificSharpen=40;else if(mutation==='edge')f.state.edges[0]={...f.state.edges[0]};else if(mutation==='args')args.upscale.sharpen=99;else if(mutation==='project')f.setProject('other');else if(mutation==='region')f.source.imageRegion={x:1};else controller.abort();assert.throws(()=>guard(args));assert.equal(f.posts.length,0);}
});
test('changes during materialization, configuration await and saved result application cannot dispatch or cover targets',async t=>{
 for(const phase of ['mediaGate','availabilityGate']){const gate=deferred(),f=await fixture(t,{[phase]:gate}),pending=f.execute();await tick();f.source.fullImage='asset:changed';gate.resolve();await pending;await tick();assert.equal(f.posts.length,0);assert.equal(f.state.nodes.length,1);}
 const gate=deferred(),f=await fixture(t,{availabilityGate:gate}),pending=f.execute();await tick();f.setConfiguration({...f.config,protocol:'tasks-v1'});gate.resolve();assert.match((await pending).result.error,/配置已变化/);assert.equal(f.posts.length,0);
 const saveGate=deferred(),late=await fixture(t,{saveGate});await late.execute();for(let i=0;i<200&&late.saves===0;i++)await tick();late.source.selection={x:1};saveGate.resolve();const job=await late.settled();assert.equal(job.applicationStatus,'failed');assert.equal(late.posts.length,1);assert.equal(late.state.nodes.length,2);
});
test('Magnific unknown recovery reads original task and rejects changed four-parameter wire without resubmit',async t=>{
 const f=await fixture(t,{unknown:true,recoveryMutation:r=>{r.parameters.sharpen=88;}});await f.execute();for(let i=0;i<200&&[...f.service.jobs.values()][0]?.status!=='unknown';i++)await tick();const job=[...f.service.jobs.values()][0];assert.equal(job.status,'unknown');await f.service.recover(job.id);assert.equal(f.posts.length,1);assert.equal(f.state.nodes.length,1);
});
test('formal Magnific presentation exposes native protocol, exact controls, original source and target version intent',async()=>{
 const {toolPresentation,upscaleDisclosure}=await import('../src/features/agent-execution/presentation.mjs');
 for(const targetNodeId of [undefined,'target']){const view=toolPresentation({name:'generation_submit',args:{...input,...(targetNodeId?{targetNodeId}:{})},status:'pending',upscaleDisclosure:upscaleDisclosure(await configuration())});assert.match(view.detail,/Precision V2/);assert.match(view.detail,/放大 3 倍/);assert.match(view.detail,/锐化 14/);assert.match(view.detail,/智能颗粒 29/);assert.match(view.detail,/超细节 41/);assert.match(view.detail,/完整原尺寸来源 source/);assert.match(view.detail,targetNodeId?/既有增强节点 target/:/新建连接的增强节点/);assert.match(view.detail,/新版本/);}
});

async function actualApprovalFixture({initial=null,refreshGate,configurationGate}={}){
 const native=await configuration();let current=initial==='missing'?{...native,configured:false,missing:['GENERATION_API_KEY']}:initial,reads=0,project='p';
 const routing=await import('../src/features/node-composer/provider-configuration.mjs'),localProvider={},service={provider:localProvider,jobs:new Map()},configContext={AbortSignal,structuredClone,serverConfigured:false,serverConfigurationSnapshot:null,serverConfigurationRevision:0,localProvider,service,providerConfigurationReady:Promise.resolve(routing),taskNativeConfigurations:new Map(),taskConfigurationIds:new Map(),fetch:async()=>{reads++;if(reads>1&&refreshGate)await refreshGate.promise;return Response.json(current);}};
 const configStart=ui.indexOf('  function refreshServerConfiguration('),configEnd=ui.indexOf('  function submitJob(',configStart);vm.runInNewContext(ui.slice(configStart,configEnd)+'\nthis.api={availability,configuration,configurationSnapshot};',configContext);await configContext.api.configuration();current=native;
 const controller=new AbortController(),source={id:'source',type:'image',image:'asset:thumb',fullImage:'asset:full'},target={id:'target',type:'image',tool:'enhance',params:{mode:'detailed'},image:'asset:old'},state={nodes:[source,target],edges:[{source:source.id,target:target.id}]},app={getState:()=>state,projectIdentity:()=>({id:project})},run={},d={activeRun:null};d.activeRun=run;let active=d;
 const api={...configContext.api,configuration:async()=>{const value=await configContext.api.configuration();if(configurationGate)await configurationGate.promise;return value;},runInPlace:()=>assert.fail('approval must not create tasks')},context={app,call:{name:'generation_submit',args:{...structuredClone(input),targetNodeId:target.id}},runController:controller,d,run,draft:()=>active,window:{GenerationAPI:api,LocalAssets:{url:()=>assert.fail('approval must not read media')}},DOMException,modules:name=>import(path.join(root,name))};
 const start=client.indexOf("     if(call.name==='generation_submit'&&call.args.kind==='image.upscale'&&call.args.upscale){"),end=client.indexOf('     const executionOptions=',start),fragment=client.slice(start,end).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');vm.runInNewContext('async function prepare(){let upscaleNotice,upscaleConfiguration,upscaleApprovalGuard;'+fragment+'return {upscaleNotice,upscaleConfiguration,upscaleApprovalGuard};}',context);
 return {prepare:context.prepare,source,target,state,controller,call:context.call,native,service,get reads(){return reads;},setProject:value=>project=value,switchChat:()=>active={},switchRun:()=>d.activeRun={}};
}
test('actual Magnific approval refreshes stale null/missing cache before actual profile disclosure',async()=>{
 for(const initial of [null,'missing']){const f=await actualApprovalFixture({initial}),approved=await f.prepare();assert.deepEqual(JSON.parse(approved.upscaleConfiguration),f.native);assert.equal(f.reads,2);assert.match(approved.upscaleNotice,/Magnific Precision V2/);assert.equal(f.service.jobs.size,0);}
});
test('actual Magnific approval guards both configuration awaits with source, target, edge, args, project, chat, run and cancellation',async()=>{
 for(const phase of ['refreshGate','configurationGate'])for(const mutation of ['source','same-id','target','edge','args','project','chat','run','cancel']){const gate=deferred(),f=await actualApprovalFixture({[phase]:gate}),pending=f.prepare();await tick();if(mutation==='source')f.source.fullImage='asset:other';else if(mutation==='same-id')f.state.nodes[0]={...f.source};else if(mutation==='target')f.target.params.mode='standard';else if(mutation==='edge')f.state.edges[0]={...f.state.edges[0]};else if(mutation==='args')f.call.args.upscale.sharpen=87;else if(mutation==='project')f.setProject('other');else if(mutation==='chat')f.switchChat();else if(mutation==='run')f.switchRun();else f.controller.abort();gate.resolve();await assert.rejects(pending);assert.equal(f.service.jobs.size,0);}
 const f=await actualApprovalFixture();f.switchChat();await assert.rejects(f.prepare(),{name:'AbortError'});assert.equal(f.reads,1);
});
test('Magnific Agent refuses missing native configuration and ordinary gateway without reading any image',async t=>{
 for(const metadata of [null,{configured:false,protocol:'magnific-native'},{configured:true,protocol:'tasks-v1'}]){const f=await fixture(t);f.setConfiguration(metadata);const receipt=await f.execute();assert.equal(receipt.result.status,'configuration_required');assert.equal(f.service.jobs.size,0);assert.deepEqual(f.reads,[]);assert.equal(f.posts.length,0);}
});
test('isolated Magnific Agent fixture checks real durable receipt before forwarding a generation POST',async()=>{
 const script=fs.readFileSync(path.join(root,'src/features/agent-generation/qa/magnific-agent-fixture.js'),'utf8'),forwarded=[];let recordedId='task-a';
 const context={URL,Headers,Response,structuredClone,crypto:globalThis.crypto,document:{baseURI:'http://localhost:49799/'},location:{href:'http://localhost:49799/',origin:'http://localhost:49799'},AgentTools:{parse},MagnificFixture:{ready:true},CanvasProjects:{id:()=> 'qa-project'},CanvasStore:{readRecord:async key=>{assert.equal(key,'agent-conversations:qa-project');return {chats:[{messages:[{name:'generation_submit',args:{kind:'image.upscale',upscale:{provider:'magnific'}},submittedTaskId:recordedId}]}]};}},fetch:async(url,options)=>{forwarded.push({url,options});return Response.json({status:'succeeded',outputs:[]});}};context.window=context;vm.runInNewContext(script,context);
 const binding={projectId:'qa-project',chatId:'chat'};context.MagnificAgentFixture.setParameters(input.upscale);context.MagnificAgentFixture.useTarget('existing');
 const turn=await context.fetch('/api/agent/turn',{method:'POST',body:JSON.stringify({binding})}).then(r=>r.json());assert.deepEqual(turn.calls[0].args,{...input,nodeId:'magnific-source',targetNodeId:'existing'});assert.equal(forwarded.length,0);
 const options={method:'POST',headers:{'Idempotency-Key':'task-a'},body:'{}'};await context.fetch('/api/generation/tasks',options);assert.equal(forwarded.length,1);assert.equal(context.MagnificAgentFixture.generationReceipts[0].acknowledged,true);recordedId='another';await assert.rejects(context.fetch('/api/generation/tasks',options),/持久对话缺少/);assert.equal(forwarded.length,1);
 await assert.rejects(context.fetch('/api/agent/continue',{method:'POST',body:JSON.stringify({sessionId:turn.sessionId,binding:{...binding,chatId:'other'}})}),/绑定已变化/);assert.throws(()=>context.MagnificAgentFixture.setParameters({...input.upscale,model:'prompt-alternative'}));
});
