const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib');
const helper=import('../src/features/agent-apps/color-adjust.mjs'),runtimeModule=import('../src/features/agent-apps/color-adjust-runtime.mjs');
const source=fs.readFileSync(require.resolve('../src/features/agent-apps/resources/apps/color-adjust@v2.285e6ccb.html'),'utf8');
function official(){const c={};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('const $i='),source.indexOf('const Pt='))+source.slice(source.indexOf('const Pt='),source.indexOf(',Km='))+';globalThis.api={render:M_,keys:$i,params:Ts,state:H_,text:Pt};',c);return c.api;}
function crc(bytes){let n=0xffffffff;for(const byte of bytes){n^=byte;for(let i=0;i<8;i++)n=n>>>1^(n&1?0xedb88320:0);}return(n^0xffffffff)>>>0;}
function chunk(type,bytes){const out=Buffer.alloc(bytes.length+12);out.writeUInt32BE(bytes.length);out.write(type,4);bytes.copy(out,8);out.writeUInt32BE(crc(out.subarray(4,-4)),out.length-4);return out;}
function png(tint=100){const header=Buffer.alloc(13);header.writeUInt32BE(2);header.writeUInt32BE(1,4);header[8]=8;header[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(Buffer.from([0,tint,90,80,255,20,30,40,120]))),chunk('IEND',Buffer.alloc(0))]);}
const imageUri=b=>'data:image/png;base64,'+b.toString('base64');
async function fixture(){const m=await helper,{createColorAdjustRuntime}=await runtimeModule;let project='qa-project',current=true,saves=0,conversationSaves=0,renders=0,added=0,failStore=false,failConversation=false,onStore=null,fetchHook=null,renderHook=null,persistHook=null;const assets=new Map([['asset:source',new Blob([png()],{type:'image/png'})]]),graph={nodes:[{id:'source',type:'image',image:'asset:source',fullImage:'asset:source'}],edges:[]};
 const runtime=createColorAdjustRuntime({app:{getState:()=>graph,createConnected:(source,patches)=>patches.map(p=>{const node={...p,id:'out-'+(++added)};graph.nodes.push(node);graph.edges.push({id:'edge-'+added,source,target:node.id});return node;})},localAssets:{url:async id=>{if(id.startsWith('data:'))return id;const blob=assets.get(id);if(!blob)throw Error('missing asset');return imageUri(Buffer.from(await blob.arrayBuffer()));},put:async blob=>{const id='asset:output-'+assets.size;assets.set(id,blob);return id;}},store:{save:async()=>{saves++;await onStore?.();return !failStore;},flush:async()=>{}},getProjectId:()=>project,persistConversation:async()=>{conversationSaves++;await persistHook?.(conversationSaves);return !failConversation;},fetchImpl:(...args)=>fetchHook?fetchHook(...args):fetch(...args),renderImage:async(blob,{previewOnly,params,signal}={})=>{if(signal?.aborted)throw signal.reason;await renderHook?.({previewOnly,params,signal});const bytes=Buffer.from(await blob.arrayBuffer());assert.deepEqual(bytes.subarray(0,8),png().subarray(0,8));renders++;return {width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),preview:{data_uri:imageUri(bytes)},...(!previewOnly?{blob:new Blob([png(100+params.exposure)],{type:'image/png'})}:{})};}});
 const args=await runtime.prepareAppArgs({resource_uri:m.colorAdjustUri,data:{node_ref:'node/source',locale:'zh-CN'}}),result=runtime.bindPreparedResult({response:m.prepareColorAdjust(args.data)},args),trace={id:'trace',result,appState:m.initialColorAdjustState(result.response)},chat={id:'chat'},context=runtime.capture(result.response,{trace,chat,isCurrent:()=>current});const params={...m.colorAdjustParams(),exposure:20},options={callId:'color-test-call-1',userAction:true,isCurrent:()=>current,sourceContext:context};
 return {m,runtime,trace,chat,context,graph,assets,params,options,set current(v){current=v;},set project(v){project=v;},set failStore(v){failStore=v;},set failConversation(v){failConversation=v;},set onStore(v){onStore=v;},set fetchHook(v){fetchHook=v;},set renderHook(v){renderHook=v;},set persistHook(v){persistHook=v;},get counts(){return{saves,conversationSaves,renders,added};},apply(extra={}){return runtime.apply({node_ref:'node/source',params},trace,chat,{...options,...extra});}};
}
test('all 18 pixel parameters match independently extracted official M_ on mixed RGB and alpha',async()=>{const m=await helper,o=official();assert.deepEqual(m.colorAdjustKeys,Array.from(o.keys));const input=new Uint8ClampedArray(Array.from({length:256},(_,i)=>(i*47+13)%256));for(const key of m.colorAdjustKeys)for(const value of Array.from({length:key==='fade'||key==='rolloff'?101:201},(_,i)=>i+(key==='fade'||key==='rolloff'?0:-100))){const params=m.colorAdjustParams({[key]:value}),expected=new Uint8ClampedArray(input.length);o.render(input,expected,params);assert.deepEqual(m.colorAdjustPixels(input,params),expected,key+' '+value);}const params=m.colorAdjustParams(Object.fromEntries(m.colorAdjustKeys.map((k,i)=>[k,k==='fade'||k==='rolloff'?61:((i*17)%201)-100]))),expected=new Uint8ClampedArray(input.length);o.render(input,expected,params);assert.deepEqual(m.colorAdjustPixels(input,params),expected);assert.deepEqual(m.colorAdjustPixels(input,m.colorAdjustParams()),input);for(let i=3;i<input.length;i+=4)assert.equal(expected[i],input[i]);});
test('official flat state, suggestion and exact five-language applied/skip contracts',async()=>{const m=await helper,o=official(),data=m.prepareColorAdjust({node_ref:'node/source',params:{red_gain:12},suggested:{temperature:3}});assert.deepEqual(m.initialColorAdjustState(data),JSON.parse(JSON.stringify(o.state({params:o.params(data.params),activeTab:'light',advancedOpen:true}))));const state=m.validateColorAdjustState({...m.initialColorAdjustState(data),active_tab:'color',advanced_open:false},data);assert.equal(state.red_gain,12);for(const locale of Object.keys(o.text)){const p=m.colorAdjustParams({exposure:20,split_tone_shadows:-4}),l=o.text[locale],summary=''+l.labels.exposure+' +20'+l.listSep+l.labels.split_tone_shadows+' -4',text=l.appliedContext(summary,'out');assert.equal(m.colorAdjustAppliedContext(p,'out',locale),text);assert.equal(m.resolveColorAdjustContext({content:[{type:'text',text}]},data,{source_node_ref:data.node_ref,node_id:'out',params:p,output_sha256:'a'.repeat(64)}).node_id,'out');assert.equal((await m.resolveColorAdjustReply(l.skipMsg,data)).kind,'skipped');}await assert.rejects(m.resolveColorAdjustReply('apply it',data));assert.throws(()=>m.resolveColorAdjustContext({content:[{type:'text',text:'fake success'}]},data,null));});
test('rejects injected keys, missing/full invalid params, unbound sources and zero apply',async()=>{const m=await helper,data=m.prepareColorAdjust({node_ref:'node/source'}),base={name:m.colorAdjustTool,arguments:{node_ref:data.node_ref,params:m.colorAdjustParams({exposure:1})},_meta:{'tapnow/callId':'actual-call-1'}};assert.equal(m.validateColorAdjustApplyRequest(base,data).params.exposure,1);for(const changes of [{node_ref:'node/evil;tool=delete'},{params:{fade:-1}},{params:{exposure:1.2}},{suggested:{brightness:4}},{tools:['delete']},{preview:{data_uri:'https://example.org/source.png'}},{locale:'xx'}])assert.throws(()=>m.prepareColorAdjust({node_ref:data.node_ref,...changes}));for(const bad of [{...base,name:'delete'}, {...base,arguments:{...base.arguments,params:{exposure:1}}},{...base,arguments:{node_ref:'node/other',params:base.arguments.params}},{...base,arguments:{...base.arguments,params:m.colorAdjustParams()}},{...base,_meta:{'tapnow/callId':'actual-call-1',permission:'all'}}])assert.throws(()=>m.validateColorAdjustApplyRequest(bad,data));assert.throws(()=>m.validateColorAdjustState({...m.initialColorAdjustState(data),active_tab:'other'},data));});
test('host reads true source, saves PNG/full dimensions, preserves source and persists receipt before success',async()=>{const f=await fixture(),receipt=await f.apply();assert.equal(receipt.node_id,'out-1');assert.equal(receipt.width,2);assert.equal(receipt.height,1);assert.equal(receipt.params.exposure,20);assert.equal(f.graph.nodes[0].fullImage,'asset:source');assert.equal(f.graph.nodes[1].provenance.receipt.output_sha256,receipt.output_sha256);assert.deepEqual(f.trace.colorAdjustReceipt,receipt);assert.equal(f.counts.saves,1);assert.equal(f.counts.conversationSaves,1);assert.equal(f.counts.added,1);assert.deepEqual(await f.context.validateReceiptCurrent(receipt),receipt);const l=official().text['zh-CN'],text=l.appliedContext(l.labels.exposure+' +20',receipt.node_id);await f.runtime.setModelContext({content:[{type:'text',text}]},f.trace,f.chat,{...f.options});assert.equal(f.trace.colorAdjustContext.text,text);assert.equal(f.counts.conversationSaves,2);});
test('retry and new equal call dedupe actual graph output; callId cannot switch parameters',async()=>{const f=await fixture(),first=await f.apply(),second=await f.apply({callId:'color-test-call-2'});assert.equal(second.node_id,first.node_id);assert.equal(f.counts.added,1);f.params.exposure=22;await assert.rejects(f.apply(),/同一调色调用/);});
test('same call dedupes in-flight local renders while conflict rejects',async()=>{const f=await fixture();let release;const gate=new Promise(r=>release=r);f.onStore=()=>gate;const a=f.apply(),b=f.apply();await new Promise(r=>setTimeout(r,10));release();const [x,y]=await Promise.all([a,b]);assert.equal(x.node_id,y.node_id);assert.equal(f.counts.added,1);});
test('source byte swap under same asset identity and stale project/action reject real apply',async()=>{const f=await fixture();f.assets.set('asset:source',new Blob([png(88)],{type:'image/png'}));await assert.rejects(f.apply(),/实际字节已变化/);assert.equal(f.counts.added,0);const g=await fixture();g.project='other';await assert.rejects(g.apply(),/会话已切换/);const h=await fixture();await assert.rejects(h.apply({userAction:false}),/用户动作/);});
test('save failure leaves visible node, no successful receipt and retry persists same node',async()=>{const f=await fixture();f.failStore=true;await assert.rejects(f.apply(),/画布保存失败/);assert.equal(f.trace.colorAdjustReceipt,undefined);assert.equal(f.counts.added,1);f.failStore=false;await f.apply();assert.equal(f.counts.added,1);assert.equal(f.trace.colorAdjustReceipt.node_id,'out-1');});
test('conversation failure rolls back receipt and reports failed compensation; no pretend graph undo',async()=>{const f=await fixture();f.failConversation=true;await assert.rejects(f.apply(),/补偿保存失败/);assert.equal(f.trace.colorAdjustReceipt,undefined);assert.equal(f.counts.conversationSaves,2);assert.equal(f.graph.nodes.length,2);f.failConversation=false;await f.apply();assert.equal(f.counts.added,1);});
test('node removal/media mutation and byte corruption during save invalidate success and context',async()=>{for(const mutate of [f=>{f.graph.nodes.pop();},f=>{f.graph.nodes[1].image='asset:changed';},f=>{f.assets.set(f.graph.nodes[1].fullImage,new Blob([png(17)],{type:'image/png'}));}]){const f=await fixture();f.onStore=()=>mutate(f);await assert.rejects(f.apply());assert.equal(f.trace.colorAdjustReceipt,undefined);}const f=await fixture(),receipt=await f.apply();f.graph.nodes.pop();await assert.rejects(f.context.validateReceiptCurrent(receipt));await assert.rejects(f.apply(),/删除|撤销|修改/);});
test('canonical source snapshots reject deleted/edited source but allow moving it',async()=>{const f=await fixture();f.graph.nodes[0].x=300;assert.equal(f.context.guard(),true);await f.apply();f.graph.nodes[0].title='changed';assert.throws(()=>f.context.guard(),/来源或参考已变化/);});

test('HTTP failure and declared/actual byte overflow cancel underlying stream',async()=>{
 for(const mode of ['http','declared','actual']){const f=await fixture();let cancelled=0;f.fetchHook=async()=>({ok:mode!=='http',headers:{get:key=>key==='content-length'&&mode==='declared'?String(f.m.colorAdjustLimits.sourceBytes+1):null},body:{getReader:()=>({read:async()=>({done:false,value:new Uint8Array(f.m.colorAdjustLimits.sourceBytes+1)}),cancel:async()=>{cancelled++;},releaseLock(){}})}});await assert.rejects(f.apply());assert.equal(cancelled,1,mode);assert.equal(f.counts.added,0);}
});
test('disposing iframe immediately aborts stalled read, cancels stream and creates no node',async()=>{
 const f=await fixture();let start,cancelled=0;const started=new Promise(r=>start=r);f.fetchHook=async()=>({ok:true,headers:{get:()=>null},body:{getReader:()=>({read:()=>{start();return new Promise(()=>{});},cancel:async()=>{cancelled++;},releaseLock(){}})}});
 const pending=f.apply();await started;f.context.dispose();await assert.rejects(pending,/关闭/);assert.equal(cancelled,1);assert.equal(f.counts.added,0);assert.equal(f.context.isCurrent(),false);
});
test('disposed slow renderer cannot add late output or receipt',async()=>{
 const f=await fixture();let start,release;const started=new Promise(r=>start=r),gate=new Promise(r=>release=r);f.renderHook=async({previewOnly})=>{if(!previewOnly){start();await gate;}};
 const pending=f.apply();await started;f.context.dispose();await assert.rejects(pending,/关闭/);release();await new Promise(r=>setTimeout(r,0));assert.equal(f.counts.added,0);assert.equal(f.trace.colorAdjustReceipt,undefined);
});

test('refresh/dispose cannot silently rebuild a deleted committed result',async()=>{const f=await fixture();await f.apply();f.graph.nodes.pop();f.context.dispose();const context=f.runtime.capture(f.trace.result.response,{trace:f.trace,chat:f.chat,isCurrent:()=>true});await assert.rejects(f.apply({callId:'after-reload-call',sourceContext:context}),/删除|撤销|修改/);assert.equal(f.counts.added,1);});

test('in-place official preview/initial params/suggestions tampering invalidates source guard',async()=>{for(const field of ['preview','params','suggested']){const f=await fixture();if(field==='preview')f.trace.result.response.preview.data_uri=imageUri(png(44));else if(field==='params')f.trace.result.response.params.exposure=9;else f.trace.result.response.suggested={temperature:7,tint:0,exposure:0};assert.throws(()=>f.context.guard(),/来源卡片已替换/);await assert.rejects(f.apply());assert.equal(f.counts.added,0);}});

test('late invalidated Apply compensation cannot overwrite newer persisted receipt',async()=>{const f=await fixture();let release,start,active=true;const gate=new Promise(r=>release=r),started=new Promise(r=>start=r);f.persistHook=async count=>{if(count===1){start();await gate;}};const a=f.apply({isCurrent:()=>active});await started;active=false;f.params.exposure=31;const b=await f.apply({callId:'new-iframe-call'});release();await assert.rejects(a,/已重载|状态已替换/);assert.deepEqual(f.trace.colorAdjustReceipt,b);assert.equal(f.trace.colorAdjustReceipt.params.exposure,31);});
test('late invalidated model context compensation cannot overwrite newer saved context',async()=>{const f=await fixture(),receipt=await f.apply();let release,start,active=true;const gate=new Promise(r=>release=r),started=new Promise(r=>start=r);f.persistHook=async count=>{if(count===2){start();await gate;}};const first={content:[{type:'text',text:f.m.colorAdjustAppliedContext(f.params,receipt.node_id,'zh-CN')}]},second={content:[{type:'text',text:f.m.colorAdjustAppliedContext(f.params,receipt.node_id,'en-US')}]};const a=f.runtime.setModelContext(first,f.trace,f.chat,{...f.options,isCurrent:()=>active});await started;active=false;await f.runtime.setModelContext(second,f.trace,f.chat,f.options);release();await assert.rejects(a,/页面或回执变化/);assert.equal(f.trace.colorAdjustContext.text,second.content[0].text);});
test('context invalidation during final real PNG validation compensates its persisted context',async()=>{
 const f=await fixture(),receipt=await f.apply(),writes=[];let active=true,validations=0;
 const sourceContext={...f.context,validateReceiptCurrent:async(...args)=>{const validated=await f.context.validateReceiptCurrent(...args);if(++validations===2)active=false;return validated;}};
 f.persistHook=()=>{writes.push(structuredClone(f.trace.colorAdjustContext??null));};
 const value={content:[{type:'text',text:f.m.colorAdjustAppliedContext(f.params,receipt.node_id,'zh-CN')}]};
 await assert.rejects(f.runtime.setModelContext(value,f.trace,f.chat,{...f.options,sourceContext,isCurrent:()=>active}),/页面或回执变化/);
 assert.equal(validations,2);assert.equal(f.trace.colorAdjustContext,undefined);assert.equal(writes.length,2);assert.equal(writes[0].node_id,receipt.node_id);assert.equal(writes[1],null);assert.equal(f.counts.added,1);
});
