'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8'),start=source.indexOf(' async function readySubmissionLibrary('),end=source.indexOf(' async function runSubmission(',start),preflightEnd=source.indexOf('  const text=item.text.trim()',end);
const deferred=()=>{let resolve,reject;return{promise:new Promise((a,b)=>{resolve=a;reject=b;}),resolve:()=>resolve(),reject:error=>reject(error)};};
function fixture(){
 const gate=deferred(),item={id:'submission',text:'真实已排队任务'},chat={id:'chat',queuedMessages:[],messages:[]},state={chat,projectId:'project',saved:[],binds:0};
 const context=vm.createContext({window:{CanvasProjects:{id:()=>state.projectId},CanvasLibrary:{ready:()=>gate.promise}},project:{id:'project'},pageLeaving:false,chats:[chat],draft:()=>state.chat,validateSubmission(){},getLibrarySourceContext(){state.binds++;return{guard:async()=>{}};},composerModule:{referenceNodes:()=>[{kind:'library',scope:'personal'}]},save:()=>{state.saved.push(structuredClone(chat));return true;},JSON});
 vm.runInContext(source.slice(start,end)+'globalThis.waitLibrary=readySubmissionLibrary;'+source.slice(end,preflightEnd)+'return {preflightPassed:true,preparedLibrary};};globalThis.runPreflight=runSubmission;',context);
 return{gate,item,chat,state,context};
}
test('restored queued submission waits for actual library ready before sent-message/run creation and retains a durable queued copy',async()=>{
 const f=fixture(),pending=f.context.runPreflight(f.chat,f.item);assert.equal(f.state.saved[0].queuedMessages[0].id,f.item.id);assert.equal(f.chat.messages.length,0);assert.equal(f.chat.activeRun,undefined);f.gate.resolve();assert.equal((await pending).preflightPassed,true);assert.equal(f.chat.queuedMessages.length,0);assert.equal(f.state.saved.at(-1).queuedMessages.length,0);
});
test('ready failure or source cancellation/project/chat change pauses without beginning a run or losing original queued input',async()=>{
 for(const change of ['storage','project','chat','cancel','source']){const f=fixture(),pending=f.context.runPreflight(f.chat,f.item);if(change==='storage')f.gate.reject(Error('DB read failed'));else{if(change==='project')f.state.projectId='other';if(change==='chat')f.state.chat={id:'new-chat'};if(change==='cancel')f.chat.queuedMessages=[];if(change==='source')f.item.text='changed';f.gate.resolve();}const result=await pending;assert.ok(result.error,change);assert.equal(f.chat.messages.length,0);assert.equal(f.chat.activeRun,undefined);assert.equal(f.chat.queuedMessages.length,change==='cancel'?0:1);assert.equal(f.state.binds,0);}
});
test('queued picker source binding is validated after hydration and before any run starts',async()=>{const f=fixture();f.item.widgetOrigin={resourceUri:'ui://tapnow/library-picker@v1',traceId:'trace'};f.chat.messages.push({id:'trace',name:'show_app',status:'done',result:{resource_uri:f.item.widgetOrigin.resourceUri,response:{}}});const pending=f.context.runPreflight(f.chat,f.item);assert.equal(f.state.binds,0);f.gate.resolve();const result=await pending;assert.equal(result.preflightPassed,true);assert.equal(f.state.binds,1);assert.ok(result.preparedLibrary);assert.equal(f.chat.messages.length,1);});

test('actual loading queue button cancels the durable pending submission before hydration can begin a run',async()=>{
 const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric')),canvasPath=fabricRequire.resolve('canvas'),prior=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(prior)require.cache[canvasPath]=prior;else delete require.cache[canvasPath];const dom=new JSDOM('<body><aside></aside></body>'),document=dom.window.document;
 try{const f=fixture();f.context.window.CanvasLibrary.loaded=false;Object.defineProperty(f.context.window.CanvasLibrary,'items',{get(){throw Error('must not read unready library');}});Object.assign(f.context,{panel:document.querySelector('aside'),el:(tag,cls,text)=>{const element=document.createElement(tag);element.className=cls||'';if(text!==undefined)element.textContent=text;return element;},btn:(icon,label,fn,cls)=>{const element=document.createElement('button');element.textContent=label;element.setAttribute('aria-label',label);element.className=cls||'';element.onclick=fn;return element;},close(){},notice(){},clone:structuredClone,appQueueSaving:false,recoveryRunning:false,queueView:null,persistQueue:()=>f.context.save()});
 const loadingStart=source.indexOf(' function renderLibraryLoading('),loadingEnd=source.indexOf(' function render(){',loadingStart),changeStart=source.indexOf(' function changeQueue('),changeEnd=source.indexOf(' function editQueued(',changeStart);vm.runInContext(source.slice(loadingStart,loadingEnd)+source.slice(changeStart,changeEnd)+'function render(){renderLibraryLoading();}globalThis.renderLoading=render;',f.context);
 const pending=f.context.runPreflight(f.chat,f.item);f.context.renderLoading();const cancel=document.querySelector('[aria-label="取消排队"]');assert.ok(cancel);assert.match(document.querySelector('section').textContent,/真实已排队任务/);cancel.click();assert.equal(f.chat.queuedMessages.length,0);assert.equal(f.state.saved.at(-1).queuedMessages.length,0);f.gate.resolve();assert.match((await pending).error,/已变化/);assert.equal(f.chat.messages.length,0);assert.equal(f.chat.activeRun,undefined);assert.equal(f.state.binds,0);
 }finally{dom.window.close();}
});
