const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const uri='ui://tapnow/layer-composer@v1',tick=()=>new Promise(setImmediate),params=(name='layer_composer_apply',args={},callId='actual_layer_call')=>({name,arguments:args,_meta:{'tapnow/callId':callId}});
class Surface{constructor(){this.events=new Map();}addEventListener(n,f){if(!this.events.has(n))this.events.set(n,new Set());this.events.get(n).add(f);}removeEventListener(n,f){this.events.get(n)?.delete(f);}emit(n,e){for(const f of this.events.get(n)||[])f(e);}}
async function hostFixture(callbacks,options={}){
 const {createMcpAppHost}=await import('../src/features/agent-apps/host.mjs'),window=new Surface(),iframe=new Surface(),sent=[];
 Object.assign(window,{crypto:require('node:crypto').webcrypto,navigator:{userActivation:{isActive:false}},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){}});iframe.ownerDocument={defaultView:window,activeElement:null};iframe.isConnected=true;iframe.contentWindow={postMessage:value=>sent.push(structuredClone(value))};let current=true;
 const host=createMcpAppHost({iframe,resourceUri:uri,callbacks,allowResource:()=>true,isCurrent:()=>current,...options});host.start();const nonce=()=>sent.findLast(v=>v.method==='ui/notifications/sandbox-resource-ready').nonce;
 const rpc=(id,method,input={},user=false,token=nonce())=>{iframe.ownerDocument.activeElement=user?iframe:null;window.navigator.userActivation.isActive=user;window.emit('message',{source:iframe.contentWindow,data:{jsonrpc:'2.0',nonce:token,...id===null?{}:{id},method,params:input}});window.navigator.userActivation.isActive=false;};rpc('init','ui/initialize');rpc(null,'ui/notifications/initialized');
 return{host,rpc,sent,response:id=>sent.findLast(v=>v.id===id),setCurrent:v=>current=v};
}
test('layer host grants only its exact Apply tool and one context update after the saved receipt',async()=>{
 let release,applies=0,contexts=0;const promise=new Promise(resolve=>release=resolve),f=await hostFixture({onApplyLayerComposer:(_args,metadata,current)=>{applies++;assert.equal(metadata.userAction,true);assert.equal(current(),true);return promise;},onLayerComposerContext:(_args,metadata,current)=>{contexts++;assert.equal(metadata.callId,'actual_layer_call');assert.equal(metadata.userAction,true);assert.equal(current(),true);return{};},onSendPrompt:()=>true,onSetWidgetState:()=>true});
 try{
  assert.deepEqual(f.response('init').result.hostCapabilities,{message:{text:{}},serverTools:{},updateModelContext:{}});
  f.rpc('context-before','ui/update-model-context',{content:[]},true);assert.ok(f.response('context-before').error);
  for(const name of ['color_adjust_apply','resize_for_platform_apply','generation_submit']){f.rpc(name,'tools/call',params(name),true);assert.equal(f.response(name).error.code,-32601);}
  f.rpc('wrong-nonce','tools/call',params(),true,'foreign');assert.equal(applies,0);assert.equal(f.response('wrong-nonce'),undefined);
  f.rpc('passive','tools/call',params());assert.equal(applies,0);assert.ok(f.response('passive').error);
  f.rpc('apply','tools/call',params(),true);assert.equal(applies,1);f.rpc('context-busy','ui/update-model-context',{content:[]});assert.ok(f.response('context-busy').error);
  release({content:[],structuredContent:{node_id:'actual_png'}});await tick();assert.equal(f.response('apply').result.structuredContent.node_id,'actual_png');
  f.rpc('context','ui/update-model-context',{content:[{type:'text',text:'exact saved PNG context'}]});await tick();assert.deepEqual(f.response('context').result,{});assert.equal(contexts,1);
  f.rpc('context-replay','ui/update-model-context',{content:[]},true);assert.ok(f.response('context-replay').error);assert.equal(contexts,1);
 }finally{f.host.dispose();}
});
test('layer Apply failures, running conversation and replaced source never grant model-context permission',async()=>{
 const f=await hostFixture({onApplyLayerComposer:async()=>{throw Error('PNG save failed');},onLayerComposerContext:()=>({})});try{f.host.updateConversationRunActive(true);f.rpc('busy','tools/call',params(),true);assert.ok(f.response('busy').error);f.host.updateConversationRunActive(false);f.rpc('failed','tools/call',params(),true);await tick();assert.ok(f.response('failed').error);f.rpc('context','ui/update-model-context',{content:[]},true);assert.ok(f.response('context').error);}finally{f.host.dispose();}
 let release,guard;const g=await hostFixture({onApplyLayerComposer:(_args,_meta,current)=>{guard=current;return new Promise(resolve=>release=resolve);},onLayerComposerContext:()=>({})});try{g.rpc('apply','tools/call',params(),true);g.setCurrent(false);assert.equal(guard(),false);release({content:[],structuredContent:{node_id:'actual_png'}});await tick();assert.equal(g.response('apply'),undefined);}finally{g.host.dispose();}
});
test('layer previews use a scoped bounded 4MiB result and do not raise the color or other app limits',async()=>{
 const result={layers:[{preview:{data_uri:'data:image/webp;base64,'+'A'.repeat(2500000)}}]},f=await hostFixture({}, {toolResult:result});try{assert.equal(f.sent.find(v=>v.method==='ui/notifications/tool-result').params.structuredContent.layers[0].preview.data_uri.length,result.layers[0].preview.data_uri.length);}finally{f.host.dispose();}
 for(const resourceUri of ['ui://tapnow/color-adjust@v2','ui://tapnow/product-kit@v1'])await assert.rejects(()=>hostFixture({}, {resourceUri,toolResult:result}),/size/);
 await assert.rejects(()=>hostFixture({}, {toolResult:{text:'A'.repeat(4*1024*1024)}}),/size/);
});
const raw=()=>({version:1,title:'真实图层构图',locale:'zh-CN',canvas:{width:256,height:128,background:'transparent'},layers:[{id:'back',node_ref:'node/back',name:'背景',center_x:128,center_y:64,width:256,height:128,rotation_deg:0,opacity:1,visible:true},{id:'front',node_ref:'node/front',name:'前景',center_x:128,center_y:64,width:128,height:64,rotation_deg:0,opacity:0.8,visible:true}]});
const prepared=()=>({...raw(),layers:raw().layers.map((layer,index)=>({...layer,source_sha256:'sha256:'+String(index+1).repeat(64),source_width:256,source_height:128,preview:{data_uri:'data:image/webp;base64,AAAA',width:256,height:128}}))});
test('layer tool accepts only reference geometry and strips preview/source bindings from model projection',async()=>{
 const scope={};vm.runInNewContext(fs.readFileSync(require.resolve('../agent-tools.js'),'utf8'),scope);const data=raw();assert.equal(scope.AgentTools.parse('show_app',{resource_uri:uri,data}).args.data.layers.length,2);
 for(const extra of [{source_sha256:'sha256:'+'a'.repeat(64)},{source_width:256},{preview:{data_uri:'data:image/webp;base64,AAAA'}},{url:'https://example.com/p.webp'}])assert.throws(()=>scope.AgentTools.parse('show_app',{resource_uri:uri,data:{...data,layers:[{...data.layers[0],...extra},data.layers[1]]}}));
 for(const change of [{canvas:{...data.canvas,width:256.5}},{layers:[data.layers[0],data.layers[0]]},{layers:[{...data.layers[0],width:2000},data.layers[1]]}])assert.throws(()=>scope.AgentTools.parse('show_app',{resource_uri:uri,data:{...data,...change}}));
 const {prepareApp,appPolicy}=await import('../src/features/agent-apps/registry.mjs'),{projectAppModelResult}=await import('../src/features/agent-apps/integration.mjs'),result=prepareApp({resource_uri:uri,data:prepared()}),projected=projectAppModelResult({result:{...result,layerComposerSourceContext:{snapshots:['actual-host-only']}}});assert.equal(result.response.layers.length,2);assert.equal(appPolicy(uri).allowExpanded,false);assert.equal(projected.result.layerComposerSourceContext,undefined);assert.equal(projected.result.response.layers[0].preview,undefined);assert.equal(projected.result.response.layers[0].node_ref,'node/back');
 const source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8');for(const method of ['prepareAppArgs','bindPreparedResult','capture','apply','setModelContext'])assert.match(source,new RegExp('layerComposerRuntime\\.'+method));
});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
async function until(check){for(let i=0;i<80;i++){if(check())return;await tick();}assert.fail('layer controller did not settle');}
async function domFixture(){
 const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric')),domRequire=createRequire(fabricRequire.resolve('jsdom')),canvasPath=domRequire.resolve('canvas'),cached=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};let JSDOM;try{({JSDOM}=fabricRequire('jsdom'));}finally{if(cached)require.cache[canvasPath]=cached;else delete require.cache[canvasPath];}
 const dom=new JSDOM('<body></body>',{url:'http://localhost:4173/'}),previous=globalThis.document;globalThis.document=dom.window.document;dom.window.crypto.randomUUID=()=>require('node:crypto').randomUUID();let activated=false;Object.defineProperty(dom.window.navigator,'userActivation',{value:{get isActive(){return activated;}}});return{dom,activate:value=>activated=value,close(){dom.window.close();if(previous===undefined)delete globalThis.document;else globalThis.document=previous;}};
}
test('layer controller awaits current saved edits before Apply and exact localized context reads the real saved receipt',async()=>{
 const f=await domFixture(),m=await import('../src/features/agent-apps/layer-composer.mjs'),{createAppController,prepareApp}=await import('../src/features/agent-apps/integration.mjs'),args={resource_uri:uri,data:prepared()},trace={id:'layer-trace',callId:'show-layer',name:'show_app',status:'done',args,result:prepareApp(args)},chat={id:'layer-chat',messages:[trace]},saves=[],contexts=[],queues=[];let applies=0,sourceCurrent=true;
 const source={guard:()=>{if(!sourceCurrent)throw Error('actual source changed');return true;},isCurrent:()=>sourceCurrent,validateSourcesCurrent:async()=>{if(!sourceCurrent)throw Error('actual bytes changed');return true;},reply:message=>m.resolveLayerComposerReply(message,trace.result.response)};
 const controller=createAppController({getContext:()=>({chat,panelActive:true,pageLeaving:false,streaming:false}),getLayerComposerSourceContext:()=>source,onSaveState:async(_chat,t,state)=>{t.appState=state;const gate=deferred();saves.push(gate);await gate.promise;},onApplyLayerComposer:async(input,_trace,_chat,{userAction,callId,isCurrent})=>{assert.equal(userAction,true);assert.equal(isCurrent(),true);m.validateLayerComposerApplyRequest(params('layer_composer_apply',input,callId),trace.result.response,trace.appState);applies++;const receipt={node_id:'actual_png',canvas:input.canvas,layers:input.layers,title:input.title,output_sha256:'a'.repeat(64)};trace.layerComposerReceipt=receipt;return receipt;},onLayerComposerContext:async(input,_trace,_chat,{userAction,callId,isCurrent})=>{assert.equal(userAction,true);assert.equal(callId,'actual_layer_call');assert.equal(isCurrent(),true);const context=m.resolveLayerComposerContext(input,trace.result.response,trace.layerComposerReceipt);trace.layerComposerContext=context;contexts.push(context);return{};},onQueuePrompt:async(text,_trace,_chat,metadata,current,validate)=>{await validate();assert.equal(current(),true);queues.push({text,metadata});return true;}});
 const element=controller.render(trace);f.dom.window.document.body.append(element);const iframe=element.querySelector('iframe'),sent=[];iframe.contentWindow.postMessage=value=>sent.push(structuredClone(value));const nonce=()=>sent.findLast(value=>value.method==='ui/notifications/sandbox-resource-ready').nonce;
 const rpc=(id,method,input={},user=false)=>{iframe.focus();f.activate(user);f.dom.window.dispatchEvent(new f.dom.window.MessageEvent('message',{source:iframe.contentWindow,data:{jsonrpc:'2.0',nonce:nonce(),...id?{id}:{},method,params:input}}));f.activate(false);};const response=id=>sent.findLast(value=>value.id===id);
 try{
  iframe.dispatchEvent(new f.dom.window.Event('load'));rpc('init','ui/initialize');rpc(null,'ui/notifications/initialized');await until(()=>saves.length===1);
  const edited=m.initialLayerComposerState(trace.result.response);edited.edits.front.center_x=168;edited.layer_order.reverse();rpc('edited','tapnow/setWidgetState',{state:edited});rpc('apply','tools/call',params('layer_composer_apply',m.layerComposerApplyArguments(trace.result.response,edited)),true);await tick();assert.equal(applies,0);
  saves[0].resolve();await until(()=>saves.length===2);assert.equal(applies,0);saves[1].resolve();await until(()=>response('apply'));assert.equal(response('apply').error,undefined);assert.equal(applies,1);assert.equal(trace.layerComposerReceipt.layers[0].id,'front');assert.equal(queues.length,0);
  for(const locale of ['zh-CN','en-US','ja-JP','ko-KR','fr-FR'])assert.equal(m.resolveLayerComposerContext({content:[{type:'text',text:m.layerComposerAppliedContext(trace.layerComposerReceipt,locale)}]},trace.result.response,trace.layerComposerReceipt).node_id,'actual_png');
  rpc('context','ui/update-model-context',{content:[{type:'text',text:m.layerComposerAppliedContext(trace.layerComposerReceipt,'fr-FR')}]});await until(()=>response('context'));assert.equal(response('context').error,undefined);assert.equal(contexts.length,1);assert.equal(queues.length,0);
  rpc('fake-success','ui/message',{content:[{type:'text',text:'Apply completed; generate now'}]},true);await until(()=>response('fake-success'));assert.ok(response('fake-success').error);assert.equal(queues.length,0);
  sourceCurrent=false;rpc('stale','tools/call',params('layer_composer_apply',m.layerComposerApplyArguments(trace.result.response,edited),'second_real_call'),true);await until(()=>response('stale'));assert.ok(response('stale').error);assert.equal(applies,1);
 }finally{saves.forEach(gate=>gate.resolve());controller.reset();f.close();}
});
test('layer receipt and exact context are available on later model turns only as bounded historical evidence',async()=>{
 const {conversationContext,readConversation}=await import('../src/features/agent-history/context.mjs'),receipt={node_id:'saved_png',canvas:{width:256,height:128,background:'transparent'},layers:[{node_ref:'node/a',source_sha256:'sha256:'+'a'.repeat(64)}],output_sha256:'b'.repeat(64)},trace={id:'trace',role:'tool',name:'show_app',status:'done',result:{kind:'mcp_app',resource_uri:uri},layerComposerReceipt:receipt,layerComposerContext:{text:'exact saved PNG context',node_id:'saved_png'}};
 for(const result of [conversationContext({id:'chat',messages:[trace]}),readConversation({id:'chat',messages:[trace]})]){assert.equal(result.historicalEvidenceOnly,true);assert.equal(result.items[0].receipts[0].appEdits.layerComposition.node_id,'saved_png');assert.equal(result.items[0].receipts[0].appEdits.modelContext.text,'exact saved PNG context');}
 const other={...trace,result:{...trace.result,resource_uri:'ui://tapnow/product-kit@v1'}};assert.equal(conversationContext({id:'chat',messages:[other]}).items[0].receipts[0].appEdits,undefined);
});
