'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm'),{once}=require('node:events');
const {TaskService,httpProvider}=require('../generation-api.js'),{parse}=require('../agent-tools.js');
const root=path.resolve(__dirname,'..'),client=fs.readFileSync(path.join(root,'agent-client.js'),'utf8'),ui=fs.readFileSync(path.join(root,'generation-ui.js'),'utf8');
const input={kind:'video.replace',nodeId:'source',prompt:'',referenceIds:['replacement']},mask={encoding:'rle-zero-based-row-major',width:320,height:180,fps:30,frames:Array.from({length:240},(_,index)=>`${(20+Math.floor(index/10))*320+40} 20`)};
const config={configured:true,protocol:'fal-video-mask-native',capabilities:{kinds:['video.erase','video.replace'],models:{'video.erase':{kind:'video.erase'},'video.replace':{kind:'video.replace'}},videoMask:{semantics:'explicit-native-alternative',temporalMask:true,maskEncoding:mask.encoding,preservesSourceAudio:'local-remux',resolution:'720p',aspectRatio:'adaptive',maxCount:1,sourceFrames:{min:81,max:241},sourceFps:{min:5,max:30}}}};
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function fixture(t,options={}){
 const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs'),{prepareWorkflowInputs}=await import('../src/features/agent-workflows/media-transport.mjs'),{createApplicationRunner}=await import('../src/features/generation-results/application.mjs'),{captureAgentVideoMaskApproval}=await import('../src/features/agent-generation/video-mask.mjs'),jobs=await import('../src/features/agent-generation/jobs.mjs');
 const video=fs.readFileSync(path.join(root,'qa/trim-scenes.mp4')),image=fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')),result=fs.readFileSync(path.join(root,'qa/agent-video-mask-result.mp4'));
 const source={id:'source',type:'video',video:'asset:video',clip:{start:1,end:5},videoMask:{source:'asset:video',clip:'{"start":1,"end":5}',asset:'asset:mask',time:2,width:320,height:180,duration:8}},replacement={id:'replacement',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},state={nodes:[source,replacement],edges:[]};let project='a',configured=true,nativeConfiguration=config,saveFails=false,created=0,saveCount=0,trace,persisted;const posts=[],assetReads=[],records=new Map(),inPlace=new Map();
 const server=http.createServer(async(req,res)=>{
  if(req.url==='/result.mp4'){res.writeHead(200,{'content-type':'video/mp4'});res.end(result);return;}
  if(req.method==='GET'){const id=decodeURIComponent(req.url.split('/').at(-1));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(records.get(id)));return;}
  let body='';for await(const chunk of req)body+=chunk;const request=JSON.parse(body);assert(persisted?.submittedTaskId,'Agent durable task id must precede HTTP');posts.push(request);res.writeHead(200,{'content-type':'application/json'});const value={id:persisted.submittedTaskId,request,status:'succeeded',outputs:[{type:'video',url:base+'/result.mp4',width:320,height:180,duration:4}]};records.set(value.id,value);res.end(JSON.stringify(value));
 });server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;t.after(()=>{server.closeAllConnections();server.close();});
 const urls={mask:URL.createObjectURL(new Blob([JSON.stringify(options.invalidMask||mask)],{type:'application/json'})),video:URL.createObjectURL(new Blob([video],{type:'video/mp4'})),full:URL.createObjectURL(new Blob([image],{type:'image/png'}))};t.after(()=>Object.values(urls).forEach(URL.revokeObjectURL));
 const localAssets={url:async key=>{assetReads.push(key);if(key==='asset:mask'&&options.maskGate)await options.maskGate.promise;if(key==='asset:video'&&options.mediaGate)await options.mediaGate.promise;return urls[key.slice(6)]||assert.fail('unexpected/thumbnail asset '+key);}};
 const app={getState:()=>state,projectIdentity:()=>({id:project}),createConnected:(id,outputs)=>outputs.map(output=>{created++;const node={...output,id:'result-'+created};state.nodes.push(node);state.edges.push({source:id,target:node.id});return node;}),saveProject:async()=>{saveCount++;if(options.saveGate)await options.saveGate.promise;if(saveFails)throw Error('disk full');}};
 const service=new TaskService({prepareInputs:(request,context)=>prepareMaskedVideoMedia(request,{...context,nativeConfiguration:config,baseUrl:base,normalizeReference:async(input,settings)=>{settings.validateSources();const bytes=Buffer.from(input.url.split(',')[1],'base64');assert.deepEqual(bytes,image);assert.equal(bytes.readUInt32BE(16),512);assert.equal(bytes.readUInt32BE(20),320);return {...input,mimeType:'image/png'};},resolveMedia:async node=>{const url=await localAssets.url(node[node.type]);return {id:node.id,type:node.type,url,width:node.type==='video'?320:512,height:node.type==='video'?180:320,...(node.type==='video'?{duration:8}:{})};},transport:(value,settings)=>prepareWorkflowInputs(value,{...settings,serialize:async blob=>'data:'+blob.type+';base64,'+Buffer.from(await blob.arrayBuffer()).toString('base64')})})});service.setProvider(httpProvider({baseUrl:base+'/api/generation',recoverable:true}));
 const target={app,service,inPlace,submitJob:(request,settings)=>service.submit(request,options.historyFailure?{...settings,beforeDispatchReady:async()=>{throw Error('history gate failed');}}:settings),DOMException};
 vm.runInNewContext(ui.slice(ui.indexOf('  function runInPlace('),ui.indexOf('  function recoverInPlace(')),target);
 const start=ui.indexOf('      if(target&&!stored.resultIds){'),end=ui.indexOf('      if(!stored.resultIds&&resultWorkflow',start),context={app,inPlace,window:{},audioGuard:()=>{},recordSubtitleMedia:()=>{},validateJobMedia:async output=>{assert.deepEqual(Buffer.from(await fetch(output.url).then(r=>r.arrayBuffer())),result);},resultProvenance:()=>({})};
 vm.runInNewContext('async function apply(job){const stored=job,target=inPlace.get(job.id);'+ui.slice(start,end)+'}',context);
 const runner=createApplicationRunner({getJob:id=>service.jobs.get(id),apply:context.apply,changed:job=>{if(trace)jobs.attachGenerationJob(trace,job);if(!job.applying){const host=inPlace.get(job.id);job.applicationError?host?.reject(Error(job.applicationError)):host?.resolve(job);}}});
 service.subscribe(job=>{if(job.status==='running'&&options.changeAtRunning)nativeConfiguration={...config,configurationId:'unapproved-config'};if(job.status==='succeeded')void runner.run(job.id);else if(['failed','cancelled','configuration_required'].includes(job.status))inPlace.get(job.id)?.reject(Error(job.error||job.status));});
 if(options.changeAtConfigured)service.provider.isConfigured=async()=>{nativeConfiguration={...config,configurationId:'unapproved-config'};return true;};
 const api={runInPlace:target.runInPlace,cancel:id=>service.cancel(id),availability:async()=>{if(options.availabilityGate)await options.availabilityGate.promise;if(options.changeAtAvailability)nativeConfiguration={...config,configurationId:'unapproved-config'};return {configured};},configuration:async()=>nativeConfiguration,configurationSnapshot:()=>nativeConfiguration};
 const fragment=client.slice(client.indexOf("  case 'generation_submit':{"),client.indexOf('   if(a.draftSourceId)',client.indexOf("  case 'generation_submit':{"))).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');
 const dispatch={app,window:{GenerationAPI:api,LocalAssets:localAssets},modules:name=>import(path.join(root,name))};vm.runInNewContext('async function dispatch(a,signal,onDepthSubmitted,approvedVideoMaskConfiguration,videoMaskApprovalGuard){switch("generation_submit"){'+fragment+'}default:throw Error("unhandled fixture branch");}}',dispatch);
 const {executeTracedCall,needsToolConfirmation}=await import('../src/features/agent-execution/trace.mjs');
 async function execute(args=input,{mode='ask',confirm=async()=>true,signal}={}){
  const parsed=parse('generation_submit',args),call={name:'generation_submit',callId:'mask-call',args:parsed.args};
  const approvalGuard=captureAgentVideoMaskApproval(parsed.args,{app,signal}),approvedConfiguration=JSON.stringify(nativeConfiguration);
  const start=client.indexOf('       const onDepthSubmitted=async job=>'),end=client.indexOf('\n       return execute(',start),ack={d:{messages:[]},call,generationJobs:jobs,save:()=>{if(options.receiptFailure)return false;persisted=structuredClone(trace);return true;},flushConversation:async()=>{if(options.receiptGate)await options.receiptGate.promise;},executionRenderer:{updateTrace:()=>{}}};
  vm.runInNewContext(client.slice(start,end)+'\nthis.acknowledge=onDepthSubmitted;',ack);
  return executeTracedCall(call,{signal,confirm:needsToolConfirmation(parsed.definition,mode)?confirm:null,changed:value=>{trace=value;ack.d.messages=[value];},execute:(_name,args)=>dispatch.dispatch(args,signal,ack.acknowledge,approvedConfiguration,approvalGuard)});
 }
 async function settled(){for(let i=0;i<600;i++){const job=[...service.jobs.values()][0];if(job&&(job.status==='failed'||job.status==='cancelled'||job.status==='succeeded'&&!job.applying&&job.applicationStatus))return job;await tick();}throw Error('fixture task did not settle');}
 return {execute,settled,app,api,source,replacement,state,posts,assetReads,service,runner,get trace(){return trace;},get persisted(){return persisted;},get saveCount(){return saveCount;},setConfigured:value=>configured=value,setConfiguration:value=>nativeConfiguration=value,setProject:value=>project=value,setSaveFailure:value=>saveFails=value};
}
test('mask schema uses one explicit saved-mask operation, never accepts a rectangle or provider overrides',()=>{
 assert.equal(parse('generation_submit',input).args.kind,'video.replace');assert.equal(parse('generation_submit',{kind:'video.erase',nodeId:'source',prompt:''}).args.kind,'video.erase');
 for(const patch of [{referenceIds:[]},{referenceIds:['a','b']},{prompt:'redesign'},{count:2},{model:'other'},{duration:4},{resolution:'480p'},{position:[1,2,3]}])assert.throws(()=>parse('generation_submit',{...input,...patch}));assert.throws(()=>parse('generation_submit',{...input,kind:'video.erase'}));
});
test('actual Agent approval and durable receipt -> full source/mask/clip/replacement bytes -> connected saved result',{timeout:10000},async t=>{
 const pendingApproval=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>pendingApproval.promise});await tick();assert.equal(f.trace.status,'pending');assert.equal(f.posts.length,0);assert.deepEqual(f.assetReads,[]);pendingApproval.resolve(true);const receipt=await pending;assert.equal(receipt.result.taskId,f.persisted.submittedTaskId);const job=await f.settled();assert.equal(job.status,'succeeded',job.error||'');assert.equal(job.applied,true,job.applicationError||'');assert.equal(f.saveCount,1);assert.equal(f.posts.length,1);const sent=f.posts[0];assert.deepEqual(sent.parameters.sourceClip,{start:1,end:5});assert.deepEqual(sent.parameters.mask,mask);assert.equal(sent.inputs[0].duration,8);assert.equal(sent.inputs[0].durationMs,8000);assert.deepEqual(Buffer.from(sent.inputs[0].url.split(',')[1],'base64'),fs.readFileSync(path.join(root,'qa/trim-scenes.mp4')));assert.deepEqual(Buffer.from(sent.inputs[1].url.split(',')[1],'base64'),fs.readFileSync(path.join(root,'qa/agent-image-processing-source.png')));assert.equal(f.source.video,'asset:video');assert.equal(f.state.nodes.length,3);assert.equal(f.state.edges.length,1);assert.equal(f.state.nodes[2].title,'视频替换');assert(!f.assetReads.includes('asset:thumbnail'));
});
test('auto erase skips confirmation; denial, missing mask, unconfigured and invalid saved RLE do not dispatch',async t=>{
 const f=await fixture(t);await f.execute({...input,kind:'video.erase',referenceIds:[]},{mode:'auto',confirm:()=>assert.fail('automatic policy must not ask')});assert.equal((await f.settled()).applied,true);assert.equal(f.posts[0].inputs.length,1);
 for(const mode of ['denied','mask','configuration','invalid']){const g=await fixture(t,mode==='invalid'?{invalidMask:{...mask,frames:['0 10']}}:{});if(mode==='mask')g.source.videoMask=null;if(mode==='configuration')g.setConfigured(false);const receipt=await g.execute(input,{mode:mode==='denied'?'ask':'auto',confirm:()=>false});assert.equal(g.posts.length,0);assert.equal(g.service.jobs.size,0);if(mode!=='invalid')assert.equal(g.assetReads.length,0);if(mode==='mask')assert.match(receipt.result.error,/添加蒙层/);}
});
test('project/source/clip/mask/replacement guards span configuration, mask reads and full-source transport',async t=>{
 for(const point of ['availability','mask','media'])for(const mutation of ['project','source','clip','mask','replacement']){
  const gate=deferred(),f=await fixture(t,{[point==='availability'?'availabilityGate':point==='mask'?'maskGate':'mediaGate']:gate}),pending=f.execute(input,{mode:'auto'});await tick();if(mutation==='project')f.setProject('other');else if(mutation==='source')f.state.nodes[0]={...f.source};else if(mutation==='clip')f.source.clip.end=6;else if(mutation==='mask')f.source.videoMask.asset='asset:changed';else f.replacement.fullImage='asset:changed';gate.resolve();const receipt=await pending;if(point==='media')assert.equal((await f.settled()).status,'failed');else assert(receipt.result.error);assert.equal(f.posts.length,0);
 }
});
test('failed task receipt/history and cancellation waiting mask or receipt never reach provider',async t=>{
 for(const failure of ['receiptFailure','historyFailure']){const f=await fixture(t,{[failure]:true});await f.execute(input,{mode:'auto'});await f.settled();assert.equal(f.posts.length,0);assert(!f.assetReads.includes('asset:video'));}
 for(const phase of ['maskGate','receiptGate']){const gate=deferred(),f=await fixture(t,{[phase]:gate}),controller=new AbortController(),pending=f.execute(input,{mode:'auto',signal:controller.signal});await tick();controller.abort();await assert.rejects(pending,{name:'AbortError'});gate.resolve();await tick();assert.equal(f.posts.length,0);assert(!f.assetReads.includes('asset:video'));}
});
test('application save retry retains connected result IDs and never posts a second request',{timeout:10000},async t=>{
 const f=await fixture(t);f.setSaveFailure(true);await f.execute(input,{mode:'auto'});const job=await f.settled();assert.equal(job.status,'succeeded',job.error||'');assert.equal(job.applied,false);assert.match(job.applicationError,/disk full/);assert.equal(f.state.nodes.length,3);const id=f.state.nodes[2].id;f.setSaveFailure(false);f.setConfiguration(null);await f.runner.run(job.id);assert.equal(job.applied,true,job.applicationError);assert.equal(f.state.nodes.length,3);assert.equal(f.state.nodes[2].id,id);assert.deepEqual(Array.from(job.resultIds),[id]);assert.equal(f.posts.length,1);
});

test('approval binds project, original node, saved metadata and replacement before any asset read',async t=>{
 for(const mutation of ['project','source','clip','mask','mask-metadata','replacement','replacement-crop']){
  const gate=deferred(),f=await fixture(t),pending=f.execute(input,{confirm:()=>gate.promise});await tick();assert.deepEqual(f.assetReads,[]);
  if(mutation==='project')f.setProject('another-project');else if(mutation==='source')f.state.nodes[0]={...f.source,videoMask:{...f.source.videoMask}};else if(mutation==='clip')f.source.clip.end=6;else if(mutation==='mask')f.source.videoMask.asset='asset:new-mask';else if(mutation==='mask-metadata')f.source.videoMask.time=3;else if(mutation==='replacement')f.replacement.fullImage='asset:new-image';else f.replacement.crop={x:1,y:1,width:3,height:3};
  gate.resolve(true);const receipt=await pending;assert(receipt.result.error,mutation);assert.equal(f.posts.length,0);assert.equal(f.service.jobs.size,0);assert.deepEqual(f.assetReads,[]);
 }
});

test('approved configuration persists through availability, mask/media preparation, isConfigured and final dispatch',async t=>{
 const unknown=await fixture(t);unknown.setConfiguration(null);const unknownReceipt=await unknown.execute(input,{mode:'auto'});assert.equal(unknownReceipt.result.status,'configuration_required');assert.equal(unknown.service.jobs.size,0);assert.deepEqual(unknown.assetReads,[]);assert.equal(unknown.posts.length,0);
 for(const options of [{changeAtAvailability:true},{changeAtConfigured:true},{changeAtRunning:true}]){
  const f=await fixture(t,options),receipt=await f.execute(input,{mode:'auto'});if(f.service.jobs.size){const job=await f.settled();assert.equal(job.status,'failed');assert.match(job.error,/供应商配置已变化/);}else assert.match(receipt.result.error,/供应商配置已变化/);assert.equal(f.posts.length,0);
 }
 for(const phase of ['maskGate','mediaGate'])for(const replacementConfiguration of [{...config,configurationId:'unapproved-config'},null]){
  const gate=deferred(),f=await fixture(t,{[phase]:gate}),pending=f.execute(input,{mode:'auto'});await tick();f.setConfiguration(replacementConfiguration);gate.resolve();const receipt=await pending;if(f.service.jobs.size){const job=await f.settled();assert.equal(job.status,'failed');assert.match(job.error,/供应商配置已变化/);}else assert.match(receipt.result.error,/供应商配置已变化/);assert.equal(f.posts.length,0);
 }
});

test('fresh task service recovers original persisted ID and outputs using GET only',async t=>{const f=await fixture(t);await f.execute(input,{mode:'auto'});const original=await f.settled(),reloaded=new TaskService();reloaded.setProvider(f.service.provider);const restored=await reloaded.recover(f.persisted.submittedTaskId);assert.equal(restored.id,original.id);assert.equal(restored.recovered,true);assert.equal(restored.status,'succeeded');assert.deepEqual(restored.request.parameters.sourceClip,{start:1,end:5});assert.equal(f.posts.length,1);assert.equal(f.state.nodes.length,3);});

async function actualApprovalFixture({initial=null,refreshGate,configurationGate}={}){
 let current=initial==='missing'?{...config,configured:false,missing:['GENERATION_API_KEY']}:initial,reads=0,project='qa-project';
 const routing=await import('../src/features/node-composer/provider-configuration.mjs'),localProvider={},service={provider:localProvider,jobs:new Map()};
 const configContext={AbortSignal,structuredClone,serverConfigured:false,serverConfigurationSnapshot:null,serverConfigurationRevision:0,localProvider,service,providerConfigurationReady:Promise.resolve(routing),taskNativeConfigurations:new Map(),taskConfigurationIds:new Map(),fetch:async url=>{assert.equal(url,'/api/generation/config');reads++;if(reads>1&&refreshGate)await refreshGate.promise;return Response.json(current);}};
 const configStart=ui.indexOf('  function refreshServerConfiguration('),configEnd=ui.indexOf('  function submitJob(',configStart);
 vm.runInNewContext(ui.slice(configStart,configEnd)+'\nthis.api={availability,configuration,configurationSnapshot};',configContext);
 assert.deepEqual(await configContext.api.configuration(),current);current=config;
 const controller=new AbortController(),source={id:'source',type:'video',video:'asset:video',clip:{start:1,end:5},videoMask:{source:'asset:video',clip:'{"start":1,"end":5}',asset:'asset:mask',time:2,width:320,height:180,duration:8}},replacement={id:'replacement',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},state={nodes:[source,replacement],edges:[]},app={getState:()=>state,projectIdentity:()=>({id:project})},run={},d={activeRun:null};d.activeRun=run;let active=d;
 const api={...configContext.api,configuration:async()=>{const value=await configContext.api.configuration();if(configurationGate)await configurationGate.promise;return value;},runInPlace:()=>assert.fail('approval must not create tasks')};
 const context={app,call:{name:'generation_submit',args:structuredClone(input)},runController:controller,d,run,draft:()=>active,window:{GenerationAPI:api,LocalAssets:{url:()=>assert.fail('approval must not read media')}},DOMException,modules:name=>import(path.join(root,name))};
 const start=client.indexOf("     if(call.name==='generation_submit'&&['video.erase','video.replace'].includes(call.args.kind)){"),end=client.indexOf("     if(call.name==='generation_submit'&&call.args.kind==='image.relight'){",start),fragment=client.slice(start,end).replace(/await import\('([^']+)'\)/g,(_all,name)=>'await modules('+JSON.stringify(name)+')');
 vm.runInNewContext('async function prepare(){let videoMaskNotice,videoMaskConfiguration,videoMaskApprovalGuard;'+fragment+'return {videoMaskNotice,videoMaskConfiguration,videoMaskApprovalGuard};}',context);
 return {prepare:context.prepare,source,replacement,state,controller,call:context.call,service,get reads(){return reads;},setProject:value=>project=value,switchChat:()=>active={},switchRun:()=>d.activeRun={},snapshot:configContext.api.configurationSnapshot};
}
test('actual video-mask approval refreshes null or missing cached configuration before disclosure',async()=>{
 for(const initial of [null,'missing']){const f=await actualApprovalFixture({initial}),approved=await f.prepare();assert.deepEqual(JSON.parse(approved.videoMaskConfiguration),config);assert.deepEqual(f.snapshot(),config);assert.equal(f.reads,2);assert.match(approved.videoMaskNotice,/独立替代.*Wan VACE/);assert.equal(f.service.jobs.size,0);}
});
test('actual video-mask approval guards arguments, source and active conversation at each configuration await',async()=>{
 for(const phase of ['refreshGate','configurationGate'])for(const mutation of ['same-id','source','clip','mask','replacement','project','chat','run','arguments','cancel']){
  const gate=deferred(),f=await actualApprovalFixture({[phase]:gate}),pending=f.prepare();await tick();
  if(mutation==='same-id')f.state.nodes[0]={...f.source};else if(mutation==='source')f.source.video='asset:changed';else if(mutation==='clip')f.source.clip.end=6;else if(mutation==='mask')f.source.videoMask.time=3;else if(mutation==='replacement')f.replacement.fullImage='asset:changed';else if(mutation==='project')f.setProject('other');else if(mutation==='chat')f.switchChat();else if(mutation==='run')f.switchRun();else if(mutation==='arguments')f.call.args.kind='video.erase';else f.controller.abort();
  gate.resolve();await assert.rejects(pending);assert.equal(f.service.jobs.size,0);
 }
 const f=await actualApprovalFixture();f.switchChat();await assert.rejects(f.prepare(),{name:'AbortError'});assert.equal(f.reads,1,'changed conversation must fail before configuration refresh');
});
