const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm');
const ref = '/api/generation/media/01234567-89ab-4def-8123-0123456789ab';
const image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN9sAAAAASUVORK5CYII=';
const png = Buffer.from(image.split(',')[1], 'base64');
const uri = name => 'ui://tapnow/' + name + '@v1';
function adapters(type = 'image', bytes = png) {
  const graph = {nodes: [{id: 'source', type, ...(type === 'image' ? {image: ref, fullImage: ref} : {video: ref})}], edges: []}, calls = [];
  return {graph, calls, app: {getState: () => graph, createConnected: () => [], insertAsset: () => ({})}, getProjectId: () => 'project', localAssets: {url: async value => {assert.notEqual(value, ref, 'generated media bypasses asset resolution');return value;}, put: async () => 'asset:saved'}, store: {save: async () => true}, persistConversation: async () => true,
    fetchImpl: async (url, options) => {calls.push({url, options});assert.equal(url, ref);assert.equal(options.redirect, 'error');assert.equal(options.mode, 'same-origin');assert.equal(options.credentials, 'same-origin');return new Response(bytes, {headers: {'content-type': type === 'image' ? 'image/png' : 'video/mp4', 'content-length': String(bytes.length)}});}};
}
test('exact UUIDv4 generation ref is narrow, including no query, fragment, suffix, traversal or absolute URL', async () => {
  const {isGenerationMediaRef} = await import('../src/features/generation-results/media-ref.mjs');
  assert.equal(isGenerationMediaRef(ref), true);
  for (const value of [ref + '?x=1', ref + '#x', ref + '/x', ref.replace('4def', '3def'), ref.replace('8123', '7123'), '/api/generation/media/../x', 'https://example.com' + ref, '/assets/image.png']) assert.equal(isGenerationMediaRef(value), false);
});
test('color-adjust and platform-resize prepare and hash exact local generation media without document.baseURI', async () => {
  const color = await import('../src/features/agent-apps/color-adjust-runtime.mjs'), colorModel = await import('../src/features/agent-apps/color-adjust.mjs'), ca = adapters();
  const cr = color.createColorAdjustRuntime({...ca, renderImage: async () => ({width: 1, height: 1, preview: {data_uri: image}})}), cp = await cr.prepareAppArgs({resource_uri: colorModel.colorAdjustUri, data: {node_ref: 'node/source'}}), cb = cr.bindPreparedResult({response: colorModel.prepareColorAdjust(cp.data)}, cp);
  assert.match(cb.colorAdjustSourceContext.source_sha256, /^[a-f0-9]{64}$/);assert.equal(ca.calls.length, 1);
  const resize = await import('../src/features/agent-apps/platform-resize-runtime.mjs'), resizeModel = await import('../src/features/agent-apps/platform-resize.mjs'), ra = adapters();
  const rr = resize.createPlatformResizeRuntime({...ra, decodeImage: async () => ({width: 1, height: 1}), renderCrop: async () => ({blob: new Blob([png], {type: 'image/png'}), width: 1, height: 1, preview: {data_uri: image}})}), rp = await rr.prepareAppArgs({resource_uri: resizeModel.platformResizeUri, data: {image_id: 'node/source', platforms: [{platform: 'square', label_zh: '方图', label_en: 'Square', ratio_id: 'r_1_1'}]}});
  const bound = rr.bindPreparedResult({response: resizeModel.preparePlatformResize(rp.data)}, rp);assert.ok(bound.platformResizeSourceContext);assert.equal(ra.calls.length, 1);
});
test('character-blocking generated source remains hash-bound and invalid near-ref never fetches', async () => {
  const {createCharacterBlockingRuntime} = await import('../src/features/agent-apps/character-blocking-runtime.mjs'), m = await import('../src/features/agent-apps/character-blocking.mjs'), a = adapters(), webp = fs.readFileSync(require.resolve('../assets/e3150914a3d3ed79.webp'));
  const runtime = createCharacterBlockingRuntime({...a, renderPortrait: async () => ({data_uri: 'data:image/webp;base64,' + webp.toString('base64'), source: 'image-crop'})}), args = {resource_uri: m.characterBlockingUri, data: {locale: 'zh-CN', target: 'image', aspect_ratio: '16:9', scene: '车站', characters: [{id: 'lin', name: '林', x: 300, y: 600, portrait_source: {node_ref: 'node/source'}}]}};
  const prepared = await runtime.prepareAppArgs(args), trace = {id: 'trace', result: runtime.bindPreparedResult({response: m.prepareCharacterBlocking(prepared.data)}, prepared)}, context = runtime.capture(trace.result.response, {trace, chat: {id: 'chat'}, isCurrent: () => true});
  assert.equal(await context.guard(), true);assert.equal(a.calls.length, 2);assert.match(trace.result.characterBlockingSourceContext.sources[0].source_sha256, /^[a-f0-9]{64}$/);
  a.graph.nodes[0].fullImage = ref + '?download=1';await assert.rejects(runtime.prepareAppArgs(args), /先导入本地/);assert.equal(a.calls.length, 2);context.dispose();
});
test('product-kit exact generated image becomes real local thumbnail and confirmation guard rereads bytes', async () => {
  const {createProductKitRuntime} = await import('../src/features/agent-apps/product-kit-runtime.mjs'), m = await import('../src/features/agent-apps/product-kit.mjs'), html = fs.readFileSync(require.resolve('../src/features/agent-apps/resources/apps/product-kit@v1.758d09b3.html'), 'utf8'), at = html.indexOf('U_={version:1,locale:'), end = html.indexOf(',wm=document', at), data = structuredClone(vm.runInNewContext('(' + html.slice(at + 3, end) + ')')), a = adapters();delete data.product.thumbnail_url;
  const runtime = createProductKitRuntime({...a, renderImage: async () => ({width: 1, height: 1, data_uri: image})}), args = {resource_uri: m.productKitUri, data: {node_ref: 'node/source', ...data}}, prepared = await runtime.prepareAppArgs(args), trace = {id: 'trace', result: runtime.bindPreparedResult({response: m.prepareProductKit(prepared.data)}, prepared)}, context = runtime.capture(trace.result.response, {trace, chat: {id: 'chat'}, isCurrent: () => true});
  assert.equal(prepared.data.product.thumbnail_url, image);await context.validateSourceCurrent();assert.equal(a.calls.length, 2);a.graph.nodes[0].fullImage = 'https://files.tapnow.ai/image.png';await assert.rejects(runtime.prepareAppArgs(args), /不能访问/);assert.equal(a.calls.length, 2);context.dispose();
});
test('ad-review and cutlist-review generated videos retain real decode and byte hashes', async () => {
  const ad = await import('../src/features/agent-apps/ad-review-runtime.mjs'), am = await import('../src/features/agent-apps/ad-review.mjs'), a = adapters('video', Buffer.from('actual-video-fixture'));
  const runtime = ad.createAdReviewRuntime({...a, decodeVideo: async () => ({duration: 4, width: 32, height: 18}), createObjectURL: () => 'blob:decode', revokeObjectURL() {}}), prepared = await runtime.prepareAppArgs({resource_uri: am.adReviewUri, data: {stage: 'final_review', batch: {}, items: [{combo: 'C1', node_ref: 'node/source', media: 'video'}]}}), trace = {id: 'trace', result: runtime.bindPreparedResult({response: am.prepareAdReview(prepared.data)}, prepared)}, context = runtime.capture(trace.result.response, {trace, chat: {id: 'chat'}, isCurrent: () => true});
  await context.guard({verifyBytes: true});assert.equal(a.calls.length, 2);assert.match(trace.result.adReviewSourceContext.sources[0].mediaSha256, /^[a-f0-9]{64}$/);context.dispose();
  const cut = await import('../src/features/agent-apps/cutlist-review-runtime.mjs'), cm = await import('../src/features/agent-apps/cutlist-review.mjs'), c = adapters('video', Buffer.from('actual-video-fixture'));
  const cutRuntime = cut.createCutlistReviewRuntime({...c, decode: async () => ({duration: 4, width: 32, height: 18}), createObjectURL: () => 'blob:decode', revokeObjectURL() {}}), cutPrepared = await cutRuntime.prepareAppArgs({resource_uri: cm.cutlistReviewUri, data: {shots: [{id: 'source', label: '片段', media_duration_ms: 4000, in_ms: 0, out_ms: 3000, default_keep: true}]}}), cutTrace = {id: 'cut', result: cutRuntime.bindPreparedResult({response: cm.prepareCutlistReview(cutPrepared.data)}, cutPrepared)}, cutContext = cutRuntime.capture(cutTrace.result.response, {trace: cutTrace, chat: {id: 'chat'}, isCurrent: () => true});
  await cutContext.guard({verifyBytes: true});assert.equal(c.calls.length, 2);cutContext.dispose();
});
test('library-picker derives inline preview and imports exact generated source without iframe URL authority', async () => {
  const {createLibraryPickerRuntime} = await import('../src/features/agent-apps/library-picker-runtime.mjs'), m = await import('../src/features/agent-apps/library-picker.mjs'), a = adapters(), library = {items: [{id: 'item', name: '本地结果', folder: '测试', type: 'image', image: ref}], folders: ['测试']};
  const runtime = createLibraryPickerRuntime({...a, library, app: {...a.app, insertAsset: asset => {const node = {...asset, id: 'imported'};a.graph.nodes.push(node);return node;}}, createObjectURL: () => 'blob:http://localhost/generated-preview', revokeObjectURL: url => assert.equal(url, 'blob:http://localhost/generated-preview'), preparePreviews: async (items, {resolveUrl}) => {assert.equal(await resolveUrl(items[0].asset), 'blob:http://localhost/generated-preview');return [{name: 'item', imageUrl: image}];}}), prepared = await runtime.prepareAppArgs({resource_uri: m.libraryPickerUri, data: {}}), response = m.prepareLibraryPicker(prepared.data), trace = {id: 'trace', result: runtime.bindPreparedResult({response}, prepared)}, context = runtime.capture(response, {trace, chat: {id: 'chat'}, isCurrent: () => true}), found = await context.find({scope: 'private', query: '本地结果'}, {userAction: true});
  assert.equal(found.items[0].preview_url, image);assert.equal(found.items[0].source_url, 'library://private/item');await context.addToCanvas({asset: {media_type: 'image', name: '本地结果', source_url: found.items[0].source_url}}, {userAction: true});assert.equal(a.graph.nodes[1].fullImage, ref);assert.equal(a.calls.length, 1);
});
test('actor reference preparation resolves exact generated image and preserves host-created preview', async () => {
  const {createActorGuideRuntime} = await import('../src/features/agent-apps/actor-guide-runtime.mjs'), m = await import('../src/features/agent-apps/actor-emotion.mjs'), a = adapters();
  const runtime = createActorGuideRuntime({...a, preparePreviews: async (items, {resolveUrl}) => {assert.equal(await resolveUrl(items[0].asset), ref);return [{name: 'source', imageUrl: image}];}}), data = m.prepareActorEmotion({mode: 'image', scene: '车站', source: {node_ref: 'node/source', media_kind: 'image'}, actor: {binding_id: 'aem_0123456789abcdef', name: '林', role: '主角', reference_nodes: [{node_ref: 'node/source', preview_url: image}]}, face: {valence: 0, stance: 0, intensity: 50}}), prepared = await runtime.prepareAppArgs({resource_uri: uri('actor-emotion'), data});
  assert.equal(prepared.data.actor.reference_nodes[0].preview_url, image);
});
test('library generated previews are sequential and exhausted budget preserves selectable entries', async () => {
  const {createLibraryPickerRuntime} = await import('../src/features/agent-apps/library-picker-runtime.mjs'), m = await import('../src/features/agent-apps/library-picker.mjs'), a = adapters(), library = {items: [1, 2, 3].map(i => ({id: 'item' + i, name: '结果' + i, type: 'image', image: ref, folder: '测试'})), folders: ['测试']};let reads = 0, active = 0, peak = 0, rendered = 0;
  const runtime = createLibraryPickerRuntime({...a, library, fetchImpl: async () => {reads++;active++;peak = Math.max(peak, active);return new Response(new ReadableStream({start(controller) {controller.enqueue(new Uint8Array(8 * 1024 * 1024));controller.close();}}), {headers: {'content-type': 'image/png', 'content-length': String(8 * 1024 * 1024)}});}, createObjectURL: () => 'blob:http://localhost/preview', revokeObjectURL: () => {active--;}, preparePreviews: async items => {rendered++;return [{name: items[0].name, imageUrl: image}];}}), prepared = await runtime.prepareAppArgs({resource_uri: m.libraryPickerUri, data: {}}), response = m.prepareLibraryPicker(prepared.data), trace = {id: 'budget', result: runtime.bindPreparedResult({response}, prepared)}, context = runtime.capture(response, {trace, chat: {id: 'chat'}, isCurrent: () => true}), result = await context.find({scope: 'private', query: '结果'}, {userAction: true});
  assert.equal(reads, 2);assert.equal(rendered, 2);assert.equal(peak, 1);assert.equal(result.items.length, 3);assert.equal(result.items[2].preview_url, undefined);assert.equal(result.items[2].source_url, 'library://private/item3');assert.equal(m.validateLibraryPickerFindResult(result, response).items.length, 3);
});
test('production-progress reads actual applied generated result through exact local route', async () => {
  const {createProductionProgressRuntime} = await import('../src/features/agent-apps/production-progress-runtime.mjs'), m = await import('../src/features/agent-apps/production-progress.mjs'), a = adapters(), job = {id: 'job', status: 'succeeded', applied: true, request: {nodeId: 'source', kind: 'image.generate'}, resultIds: ['source'], outputs: [{type: 'image', url: ref}]}, chat = {id: 'chat', messages: [{id: 'submitted', name: 'generation_submit', status: 'done', result: {taskId: 'job'}}]};
  const runtime = createProductionProgressRuntime({...a, generationAPI: {getJobs: () => [job]}}), prepared = await runtime.prepareAppArgs({resource_uri: m.productionProgressUri, data: {node_ids: ['source']}}, {chat}), response = m.prepareProductionProgress(prepared.data), trace = {id: 'trace', result: runtime.bindPreparedResult({response}, prepared)};chat.messages.push(trace);
  const context = runtime.capture(response, {trace, chat, isCurrent: () => true}), result = await context.query({node_ids: ['source'], project_id: 'project'});assert.equal(result.structuredContent.items[0].status, 'done');assert.equal(result.structuredContent.items[0].media_url, image);assert.equal(a.calls.length, 1);context.dispose();
});
test('replaced library query stops its sequential media reads before the next entry', async () => {
  const {createLibraryPickerRuntime} = await import('../src/features/agent-apps/library-picker-runtime.mjs'), m = await import('../src/features/agent-apps/library-picker.mjs'), a = adapters(), library = {items: [1, 2, 3].map(i => ({id: 'item' + i, name: '结果' + i, type: 'image', image: ref, folder: '测试'})), folders: ['测试']};let reads = 0, release, started;
  const began = new Promise(resolve => {started = resolve;}), gate = new Promise(resolve => {release = resolve;});
  const runtime = createLibraryPickerRuntime({...a, library, fetchImpl: async () => {reads++;if (reads === 1) {started();await gate;}return new Response(png, {headers: {'content-type': 'image/png'}});}, createObjectURL: () => 'blob:http://localhost/preview', revokeObjectURL() {}, preparePreviews: async items => [{name: items[0].name, imageUrl: image}]}), prepared = await runtime.prepareAppArgs({resource_uri: m.libraryPickerUri, data: {}}), response = m.prepareLibraryPicker(prepared.data), trace = {id: 'epoch', result: runtime.bindPreparedResult({response}, prepared)}, context = runtime.capture(response, {trace, chat: {id: 'chat'}, isCurrent: () => true});
  const oldQuery = context.find({scope: 'private', query: '结果'}, {userAction: true}), rejected = assert.rejects(oldQuery, /被更新的请求替换/);await began;
  const current = await context.find({scope: 'private', query: '结果3'}, {userAction: true});release();await rejected;
  assert.equal(reads, 2);assert.equal(current.items[0].asset_id, 'item3');assert.equal(context.getVisibleAssets()[0].asset_id, 'item3');
});
