const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sourcePath=require.resolve('../src/features/agent-apps/resources/apps/color-adjust@v2.285e6ccb.html'),original=fs.readFileSync(sourcePath,'utf8'),modulePromise=import('../src/features/agent-apps/color-adjust-local-interactions.mjs');
const tick=()=>new Promise(setImmediate),deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject}},plain=value=>JSON.parse(JSON.stringify(value));
function section(html,from,to){const start=html.indexOf(from),end=html.indexOf(to,start);assert.ok(start>=0&&end>start,from);return html.slice(start,end)}
async function harness({save,apply,context,send}={}){
 const html=await(await modulePromise).localizeColorAdjustInteractions(original,'color-adjust','v2'),requests=[],tools=[],contexts=[],messages=[],handlers={},children=[],focused={isConnected:true,count:0,focus(){this.count++},blur(){}};
 const status={textContent:'',setAttribute(){},appendChild:child=>children.push(child)},root={inert:false,addEventListener:(type,fn)=>handlers[type]=fn};
 const c={JSON,Promise,setTimeout,clearTimeout,TextEncoder,structuredClone,document:{activeElement:focused,createElement:()=>({addEventListener(type,fn){this[type]=fn}})},navigator:{userActivation:{isActive:true}},window:{parent:{postMessage:message=>messages.push(message)},addEventListener:(type,fn,capture)=>{handlers['window-'+type]=fn;handlers['capture-'+type]=capture}},It:root,Bn:status,Ne:{disabled:false,textContent:''},ye:false,wi:false,be:'light',Ue:true,jt:null,Me:{node_ref:'node/qa-source',locale:'zh-CN'},Ke(){},xt(text){status.textContent=text;children.length=0},X:()=>({}),K_:()=> 'qa-apply-call-123',Ve:{request:async value=>{requests.push(plain(value.params.state));await save?.(value.params.state)},callServerTool:async value=>{tools.push(plain(value));return apply?apply(value):{structuredContent:{node_id:'qa-output'}}},updateModelContext:async value=>{contexts.push(plain(value));await context?.(value)},sendMessage:async value=>{messages.push(plain(value));await send?.(value)}}};
 vm.createContext(c);vm.runInContext(section(original,'const $i=','const Pt=')+section(original,'const Pt=',',Km=')+';globalThis.K=Pt["zh-CN"];globalThis.ae={...bi,exposure:20};'+section(original,'function Bm(e)','function ic()')+section(html,'const colorLocalCopy=','function xt(e,n)'),c);
 return{html,c,root,status,requests,tools,contexts,messages,handlers,children,focused,run:code=>vm.runInContext(code,c)};
}
test('pinned official bytes, all 18 pixel operations, palettes and five locales survive the narrow derivative',async()=>{
 const m=await modulePromise,h=await harness();assert.equal(require('node:crypto').createHash('sha256').update(original).digest('hex'),m.colorAdjustReferenceSha256);
 assert.equal(await m.localizeColorAdjustInteractions('other','product-kit','v1'),'other');await assert.rejects(m.localizeColorAdjustInteractions(original+' ','color-adjust','v2'),/integrity/);await assert.rejects(m.localizeColorAdjustInteractions(original,'color-adjust','v1'),/unsupported/);await assert.rejects(m.localizeColorAdjustInteractions(h.html,'color-adjust','v2'),/integrity/);
 assert.equal(section(h.html,'const $i=','const It='),section(original,'const $i=','const It='));require('esbuild').transformSync(h.html.match(/<script\b[^>]*>([\s\S]*?)<\/script>/)[1],{loader:'js',format:'esm'});assert.equal(fs.readFileSync(sourcePath,'utf8'),original);
 for(const locale of ['zh-CN','en-US','ja-JP','ko-KR','fr-FR']){h.c.Me.locale=locale;assert.ok(h.run('colorText().failed'));assert.ok(h.run('colorText().retry'));}
});
test('captured original swallows a rejected transaction; production derivative exposes a real retry control',async()=>{
 const originalContext={Kn:null,ae:{exposure:20},be:'light',Ue:true,H_:v=>({...v.params,active_tab:v.activeTab,advanced_open:v.advancedOpen}),X:()=>({}),Ve:{request:async()=>{throw Error('rejected')}}};vm.createContext(originalContext);vm.runInContext(section(original,'async function e$()','let wi='),originalContext);assert.equal(await vm.runInContext('e$()',originalContext),undefined);
 let fail=true;const h=await harness({save:()=>{if(fail)throw Error('private SDK details')}});assert.equal(await h.run('colorFlush()'),false);assert.match(h.status.textContent,/保存或交接失败/);assert.doesNotMatch(h.status.textContent,/private/);assert.equal(h.children[0].textContent,'重试保存');fail=false;h.children[0].click();await tick();assert.equal(h.requests.length,2);assert.equal(h.status.textContent,'');
});
test('slow saves coalesce high-frequency edits and cannot overtake the final flat 18-parameter snapshot',async()=>{
 const gate=deferred(),h=await harness({save:()=>h.requests.length===1?gate.promise:undefined}),first=h.run('e$()');await tick();h.run('ae.exposure=21');const second=h.run('e$()');for(let i=22;i<=70;i++){h.run('ae.exposure='+i);void h.run('e$()')}assert.equal(h.requests.length,1);gate.resolve();await Promise.all([first,second]);assert.equal(h.requests.length,2);assert.equal(h.requests[1].exposure,70);assert.equal(Object.keys(h.requests[1]).length,20);
 const unchanged=h.run('e$()');h.run('ae.temperature=12;be="color";Ue=false');const changed=h.run('e$()');await Promise.all([unchanged,changed]);assert.equal(h.requests.length,3);assert.equal(h.requests[2].temperature,12);assert.equal(h.requests[2].active_tab,'color');assert.equal(h.requests[2].advanced_open,false);
});
test('Apply saves before local tool output, freezes every control, locks duplicate clicks and restores focus',async()=>{
 const gate=deferred(),h=await harness({save:()=>gate.promise}),first=h.run('n$()');await h.run('n$()');await tick();assert.equal(h.root.inert,true);assert.equal(h.c.ye,true);assert.equal(h.tools.length,0);gate.resolve();await first;assert.equal(h.tools.length,1);assert.deepEqual(h.tools[0].arguments.params,Object.fromEntries(Object.keys(h.requests[0]).filter(key=>!['active_tab','advanced_open'].includes(key)).map(key=>[key,h.requests[0][key]])));assert.equal(h.contexts[0].content[0].text,'用户已在调色面板应用调整（曝光 +20），画布新节点 qa-output，源图保留。');assert.equal(h.root.inert,false);assert.equal(h.focused.count,1);
});
test('save failure blocks actual output; final parameter reset stays zero and cannot Apply',async()=>{
 const h=await harness({save:()=>{throw Error('no commit')}});await h.run('n$()');assert.equal(h.tools.length,0);assert.equal(h.contexts.length,0);assert.equal(h.root.inert,false);h.run('ae={...bi};Xm()');await h.run('n$()');assert.equal(h.requests.length,1);
});
test('expired activation requires a new Apply click after saving; context alone may finish under its actual output permit',async()=>{
 const gate=deferred(),h=await harness({save:()=>gate.promise}),pending=h.run('n$()');h.c.navigator.userActivation.isActive=false;gate.resolve();await pending;assert.equal(h.tools.length,0);assert.match(h.status.textContent,/再次点击应用/);h.c.navigator.userActivation.isActive=true;await h.run('n$()');assert.equal(h.requests.length,1);assert.equal(h.tools.length,1);assert.equal(h.contexts.length,1);
});
test('failed context retries only context for the same saved output instead of creating another image',async()=>{
 let fail=true;const h=await harness({context:()=>{if(fail)throw Error('context persistence rejected')}});await h.run('n$()');assert.equal(h.tools.length,1);assert.equal(h.contexts.length,1);assert.match(h.status.textContent,/图片已保存，上下文未保存/);assert.equal(h.children[0].textContent,'重试交接');fail=false;h.c.navigator.userActivation.isActive=false;h.children[0].click();await tick();assert.equal(h.tools.length,1);assert.equal(h.contexts.length,2);assert.deepEqual(h.contexts[1],h.contexts[0]);assert.equal(h.run('colorPendingContext'),null);assert.equal(h.run('jt'),null);
});
test('failed context survives real slider changes and reset; retry sends the saved old output, then permits a new Apply',async()=>{
 let fail=true;const h=await harness({context:()=>{if(fail)throw Error('context persistence rejected')}});await h.run('n$()');const saved=h.contexts[0],oldCall=h.run('jt');h.run('ae.exposure=31;Xm()');assert.ok(h.run('colorPendingContext'));assert.equal(h.run('jt'),oldCall);h.run('ae={...bi};Xm()');fail=false;h.c.navigator.userActivation.isActive=false;await h.run('n$()');assert.equal(h.tools.length,1);assert.equal(h.contexts.length,2);assert.deepEqual(h.contexts[1],saved);assert.match(h.status.textContent,/当前新参数尚未应用/);assert.equal(h.run('colorPendingContext'),null);h.run('ae.exposure=31;Xm()');h.c.navigator.userActivation.isActive=true;await h.run('n$()');assert.equal(h.tools.length,2);assert.equal(h.tools[1].arguments.params.exposure,31);assert.equal(h.contexts.length,3);
});
test('Skip stores final edits, waits, rejects failures and sends exactly the official message on retry',async()=>{
 let fail=true;const h=await harness({save:()=>{if(fail)throw Error('rejected')}});await h.run('t$(K.skipMsg)');assert.equal(h.messages.length,0);assert.equal(h.root.inert,false);fail=false;await h.run('t$(K.skipMsg)');assert.equal(h.messages.length,1);assert.equal(h.messages[0].content[0].text,'先不调色，继续刚才的事。');assert.equal(h.tools.length,0);
});
test('source disposal and unexpected edits during a slow Apply cannot dispatch the previous snapshot',async()=>{
 for(const change of ['colorEpoch++','colorDisposed=true','ae.exposure=31']){const gate=deferred(),h=await harness({save:()=>gate.promise}),pending=h.run('n$()');await tick();h.run(change);gate.resolve();await pending;assert.equal(h.tools.length,0);assert.equal(h.contexts.length,0);assert.equal(h.root.inert,false);}
});
test('the lifecycle contract persists before close, remains inert until resume, and restores the current control',async()=>{
 const gate=deferred(),h=await harness({save:()=>gate.promise});vm.runInContext(section(h.html,';(function(){let pending=','r$();</script>'),h.c);assert.equal(h.handlers['capture-message'],true);h.run('ki()');const pending=h.handlers['window-message']({source:h.c.window.parent,data:{jsonrpc:'2.0',id:'local-close-color-adjust',method:'freenow/lifecycleFlush'},stopImmediatePropagation(){}});await tick();assert.equal(h.root.inert,true);assert.equal(h.run('Kn'),null);assert.equal(h.messages.filter(v=>v.id).length,0);gate.resolve();await pending;assert.equal(h.messages.at(-1).result.flushed,true);assert.equal(h.root.inert,true);assert.equal(h.tools.length,0);await h.handlers['window-message']({source:h.c.window.parent,data:{jsonrpc:'2.0',method:'freenow/lifecycleResume',params:{id:'local-close-color-adjust'}},stopImmediatePropagation(){}});assert.equal(h.root.inert,false);assert.equal(h.focused.count,1);
});
test('failed close visibly preserves edits, restores controls, and retries the same snapshot without handoff',async()=>{
 let fail=true;const h=await harness({save:()=>{if(fail)throw Error('rejected')}});vm.runInContext(section(h.html,';(function(){let pending=','r$();</script>'),h.c);const emit=()=>h.handlers['window-message']({source:h.c.window.parent,data:{jsonrpc:'2.0',id:'local-close-color-retry',method:'freenow/lifecycleFlush'},stopImmediatePropagation(){}});await emit();assert.equal(h.messages.at(-1).error.code,-32000);assert.equal(h.root.inert,false);assert.equal(h.run('ae.exposure'),20);fail=false;await emit();assert.equal(h.messages.at(-1).result.flushed,true);assert.deepEqual(h.requests[0],h.requests[1]);assert.equal(h.tools.length,0);
});
test('closing an applied output with unresolved context preserves the page for an explicit context retry',async()=>{
 const h=await harness({context:()=>{throw Error('context save rejected')}});await h.run('n$()');vm.runInContext(section(h.html,';(function(){let pending=','r$();</script>'),h.c);await h.handlers['window-message']({source:h.c.window.parent,data:{jsonrpc:'2.0',id:'local-close-color-pending-context',method:'freenow/lifecycleFlush'},stopImmediatePropagation(){}});assert.equal(h.messages.at(-1).error.code,-32000);assert.equal(h.root.inert,false);assert.equal(h.tools.length,1);assert.ok(h.run('colorPendingContext'));assert.equal(h.children[0].textContent,'重试交接');
});
test('actual slider input schedules the last keyboard/pointer value before a change event; reset and suggestion retain official semantics',async()=>{
 const h=await harness();function node(){return{children:[],style:{},classList:{toggle(){},remove(){}},setAttribute(){},append(...items){this.children.push(...items)},appendChild(item){this.children.push(item);return item},addEventListener(type,fn){this[type]=fn}}}h.c.document.createElement=node;Object.assign(h.c,{Ps:{},je:false,Ie:null,Oi:null,Oe:null,Ui:{exposure:8,temperature:12,tint:-4},ar:{...h.c.ae},Wn:{},Km:['temperature','tint','exposure'],Ei(){},yi(){},ic(){h.c.Xm?.()}});
 vm.runInContext(section(h.html,'function rc(e)','function Bm(e)'),h.c);h.run('rc("exposure")');const range=h.c.Ps.exposure.input;range.value='31';range.input();assert.equal(h.c.ae.exposure,31);assert.notEqual(h.run('Kn'),null);await h.run('colorFlush()');assert.equal(h.requests.at(-1).exposure,31);
 vm.runInContext(section(h.html,'function Q_()','function Ei()'),h.c);const controls=h.run('Q_()'),suggest=controls.children[0].children[0],reset=controls.children[0].children[1];suggest.click();assert.equal(h.c.ae.exposure,8);assert.equal(h.c.ae.temperature,12);suggest.click();assert.equal(h.c.ae.exposure,20);reset.click();assert.equal(h.c.ae.exposure,0);assert.equal(h.c.ae.temperature,0);assert.equal(h.c.je,false);clearTimeout(h.run('Kn'));
});
test('keyboard comparison survives pending paint and releases on blur; advanced rebuild restores its toggle focus',async()=>{
 const h=await harness(),handlers={},canvas={tabIndex:-1,setAttribute(){},focus(){},addEventListener:(name,fn)=>handlers[name]=fn};let originals=0,paints=0;h.c.Dt={putImageData(){originals++}};h.c.Zt={};h.c.Gn={};h.c.yi=()=>{paints++};vm.runInContext(section(h.html,'let colorComparing=false;','let Si='),h.c);h.c.canvas=canvas;h.run('X_(canvas)');handlers.keydown({key:' ',preventDefault(){}});assert.equal(originals,1);assert.equal(h.run('colorComparing'),true);handlers.blur();assert.equal(h.run('colorComparing'),false);assert.equal(paints,1);
 vm.runInContext(section(h.html,'function Y_()','function Q_()'),h.c);h.run('colorComparing=true');assert.doesNotThrow(()=>h.run('Y_()'));assert.equal(originals,1);
 let focused=0;h.c.Ei=()=>{h.c.Ut={focus(){focused++}}};h.c.ki=()=>{};vm.runInContext('globalThis.toggle='+h.html.match(/n\.addEventListener\("click",(\(\)=>\{if\(ye\|\|wi\)return;Ue=!Ue;Ei\(\);Ke\(\);ki\(\);Ut\?\.focus\(\{preventScroll:true\}\)\})\)/)[1],h.c);h.c.toggle();assert.equal(h.c.Ue,false);assert.equal(focused,1);
});
