const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
globalThis.crypto=crypto.webcrypto;
const root='../src/features/agent-apps/',modules=Promise.all([import(root+'previs.mjs'),import(root+'previs-runtime.mjs')]);
const data=()=>({version:3,title:'真实镜头计划',sheets:[{sheet_id:'board',sheet_node_ref:'node/source',shots:[{shot_code:'S1',cell:0,duration:3,move:'push_in',size:'MS',script_text:'镜头中的真实人物'}]}],generation_spec:{model:'configured-test-model',aspect_ratio:'16:9'}});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN6UAAAAASUVORK5CYII=','base64');
async function fixture(options={}){
 const [m,r]=await modules,source={id:'source',type:'image',image:'asset:source',fullImage:'asset:source',x:0,y:0,width:300,height:180},graph={nodes:[source],edges:[]},chat={id:'chat',messages:[]},trace={id:'trace'};let current=true,saves=0,posts=0,gets=0,jobNo=0,configured=options.configured!==false;const jobs=[],assets=new Map([['asset:source',png]]),dispatches=[];
 const localAssets={url:async ref=>{const bytes=assets.get(ref);if(!bytes)throw Error('lost asset');return 'data:image/png;base64,'+bytes.toString('base64');}},fetchImpl=async(url,opts)=>{if(url.startsWith('http:')){const response=new Response(png,{headers:{'content-type':'image/png'}});Object.defineProperty(response,'url',{value:options.foreignPeer?'http://wrong.test/':url});return response;}return fetch(url,opts);};
 const generationAPI={availability:async()=>({configured}),getJobs:()=>jobs,submit(request,hooks){posts++;const job={id:'real-job-'+(++jobNo),request:structuredClone(request),status:'queued',applied:false};jobs.push(job);const dispatch=Promise.resolve().then(async()=>{await options.dispatchGate;return hooks.beforeDispatchReady({jobId:job.id});}).then(()=>{hooks.beforeDispatch();job.status='running';}).catch(e=>{job.status='failed';job.error=e.message;});dispatches.push(dispatch);return job;},recover:async id=>{gets++;const job=jobs.find(j=>j.id===id);if(job)job.status='running';return job;}};
 const app={getState:()=>graph,createConnected(sourceId,patches){assert.ok(graph.nodes.some(n=>n.id===sourceId));return patches.map(p=>{const node={...structuredClone(p),id:'target-'+(graph.nodes.length),x:400,y:0};graph.nodes.push(node);graph.edges.push({id:'edge-'+node.id,source:sourceId,target:node.id});return node;});},addNode(_type,_point,_image,title,patch){const node={...patch,title,id:'target-'+graph.nodes.length,x:0,y:0};graph.nodes.push(node);return node;}};
 const runtime=r.createPrevisRuntime({app,localAssets,generationAPI,store:{save:async()=>options.graphFail?false:true},getProjectId:()=> 'project',persistConversation:async()=>{saves++;return options.save?.(trace,saves)??true;},fetchImpl,getOrigin:()=> 'http://localhost:4173',renderPreview:async()=>{await options.preview?.(graph,trace);return {width:1,height:1,preview:{data_uri:'data:image/webp;base64,AAAA',width:1,height:1}};},renderCell:async()=> 'data:image/png;base64,'+png.toString('base64')});
 const raw=options.data||data(),args=await runtime.prepareAppArgs({resource_uri:m.previsUri,data:raw});trace.result=runtime.bindPreparedResult({resource_uri:m.previsUri,response:m.preparePrevis(args.data)},args);trace.appState=m.initialPrevisState(trace.result.response);chat.messages.push(trace);const context=runtime.capture(trace.result.response,{trace,chat,isCurrent:()=>current});
 const request=(plan='plan-1')=>({plan_id:plan,shot_code:'S1',source:{kind:'cell',sheet_node_ref:'node/source',cell:0}});
 function complete(){const job=jobs[0],node=graph.nodes.find(n=>n.id===job.request.nodeId);assets.set('asset:result',png);node.image=node.fullImage='asset:result';job.status='succeeded';job.applied=true;job.resultIds=[node.id];job.outputs=[{type:'image',url:'asset:result'}];return node;}
 return {m,r,runtime,context,trace,chat,graph,source,assets,jobs,generationAPI,request,complete,dispatch:()=>Promise.all(dispatches),setCurrent:v=>current=v,counters:()=>({saves,posts,gets}),setConfigured:v=>configured=v};
}
test('official policy, cells, duration/state budgets and edited reply are exact',async()=>{const [m]=await modules,d=m.preparePrevis(data()),state=m.initialPrevisState(d);assert.deepEqual(m.previsPolicy,{allowExpanded:true,autoExpandOnReady:true});assert.equal(m.previsCells().length,9);state.edits.S1={dur:4,move:'pan_left',curve:'linear',trans:'dissolve',script_text:'修改镜头'};const details={type:'app_reply',reply_id:crypto.randomUUID(),action:'previs_reply',payload:m.previsReplyPayload(d,state)};assert.equal(m.validatePrevisReply(details,d,state).edits[0].duration,4);assert.deepEqual(m.previsStateFromPayload(d,details.payload).edits,state.edits);assert.throws(()=>m.validatePrevisReply({...details,payload:{...details.payload,order:[]}},d,state));assert.throws(()=>m.validatePrevisState({...state,order:['foreign']},d));assert.throws(()=>m.preparePrevis({...data(),sheets:[{...data().sheets[0],shots:[data().sheets[0].shots[0],data().sheets[0].shots[0]]}]}));});
test('preflight precedes debounced save, final reply requires real saved edits, repeat apply keeps revision',async()=>{const f=await fixture(),state=structuredClone(f.trace.appState);state.edits.S1={dur:5,move:'static',curve:'smooth',trans:'cut'};const details={type:'app_reply',reply_id:crypto.randomUUID(),action:'previs_reply',payload:f.m.previsReplyPayload(f.trace.result.response,state)};const preflight=await f.context.preflightReply(details);await assert.rejects(f.context.validateReply(details),/已保存/);f.trace.appState=state;details.expected_manifest_revision=preflight.manifest_revision;const result=await f.context.applyReply(details);assert.equal(result.manifest.sheets[0].shots[0].duration,5);assert.equal((await f.context.applyReply(details)).manifest_revision,result.manifest_revision);assert.equal(f.trace.previsReplies.length,1);});
test('unconfigured variants never reserve nodes or submit a task',async()=>{const f=await fixture({configured:false});await assert.rejects(f.context.submitVariants(f.request(),{callId:'actual-call-id'}),e=>e.code==='configuration_required');assert.equal(f.graph.nodes.length,1);assert.equal(f.counters().posts,0);});
test('variants reserve real targets, persist identity before dispatch, duplicate plans reuse one task',async()=>{const f=await fixture(),reply=await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();assert.equal(reply.structuredContent.node_id,'node/target-1');assert.equal(f.trace.previsJobs[0].job_id,f.jobs[0].id);const second=await f.context.submitVariants(f.request(),{callId:'other-call-id'});assert.equal(second.structuredContent.task_id,f.jobs[0].id);assert.equal(f.counters().posts,1);assert.equal(f.jobs[0].request.inputs[0].type,'image');assert.equal(f.jobs[0].request.parameters.count,1);});
test('only actual applied media becomes completed, output hashes reject replacement and undo prevents recreation',async()=>{const f=await fixture();await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();const first=await f.context.lookupVariants({source_refs:['node/source']});assert.equal(first.structuredContent.items[0].status,'pending');const node=f.complete(),ready=await f.context.lookupVariants({source_refs:['node/source']});assert.equal(ready.structuredContent.items[0].status,'completed');assert.match(f.trace.previsJobs[0].receipt.output_sha256,/^[a-f0-9]{64}$/);f.assets.set('asset:result',Buffer.from('changed'));await assert.rejects(f.context.lookupVariants({source_refs:['node/source']}),/像素改变/);f.graph.nodes.splice(f.graph.nodes.indexOf(node),1);await assert.rejects(f.context.submitVariants(f.request(),{callId:'repeat-call-id'}),/撤销/);assert.equal(f.counters().posts,1);});
test('GET recovery preserves original job and never POSTs again',async()=>{const f=await fixture();await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.jobs[0].status='unknown';await f.context.lookupVariants({source_refs:['node/source']});assert.equal(f.counters().gets,1);assert.equal(f.counters().posts,1);assert.equal(f.trace.previsJobs[0].job_id,'real-job-1');});
test('source mutation or failed graph persistence prevents dispatch',async()=>{const f=await fixture();f.source.image=f.source.fullImage='asset:changed';await assert.rejects(f.context.submitVariants(f.request(),{callId:'actual-call-id'}),/变化/);assert.equal(f.counters().posts,0);const g=await fixture({graphFail:true});await assert.rejects(g.context.submitVariants(g.request(),{callId:'actual-call-id'}),/保存失败/);assert.equal(g.counters().posts,0);});
test('exact generation media peer restriction rejects redirects and foreign response URLs',async()=>{const ref='/api/generation/media/'+crypto.randomUUID(),raw=data();raw.sheets[0].sheet_node_ref='node/source';const [m,r]=await modules,graph={nodes:[{id:'source',type:'image',image:ref}],edges:[]};const runtime=r.createPrevisRuntime({app:{getState:()=>graph,createConnected(){}},localAssets:{url(){}},store:{save(){}},getProjectId:()=> 'project',persistConversation(){},getOrigin:()=> 'http://localhost:4173',fetchImpl:async()=>{const response=new Response(png,{headers:{'content-type':'image/png'}});Object.defineProperty(response,'url',{value:'http://evil.test/not-source'});return response;},renderPreview:async()=>assert.fail('foreign pixels decoded')});await assert.rejects(runtime.prepareAppArgs({resource_uri:m.previsUri,data:raw}),e=>e.code==='nonlocal_source');});
test('missing sheets require accepted reply and normal user action, generated sheets project trusted new sources',async()=>{const raw=data();delete raw.sheets[0].sheet_node_ref;const f=await fixture({data:raw}),details={type:'app_reply',reply_id:crypto.randomUUID(),action:'previs_reply',payload:f.m.previsReplyPayload(f.trace.result.response,f.trace.appState)};await f.context.applyReply(details);const args={reply_id:details.reply_id,shot_codes:['S1']},opts={userAction:true,isCurrent:()=>true,sourceContext:f.context};await assert.rejects(f.runtime.generateSheets(args,f.trace,f.chat,opts),/实际接受/);f.trace.previsReplies[0].status='accepted';f.trace.previsReplies[0].run_id='real-agent-submission';f.trace.appReplyReceipts=[{reply_id:details.reply_id,run_id:'real-agent-submission'}];await f.runtime.generateSheets(args,f.trace,f.chat,opts);await f.dispatch();f.complete();const result=await f.context.querySheets();assert.equal(result.manifest.sheets[0].sheet_node_ref,'node/target-1');assert.equal(result.projection.previsSourceContext.sources[0].source_sha256,f.trace.previsJobs[0].receipt.output_sha256);const nextTrace={...f.trace,result:{...f.trace.result,...result.projection}},nextContext=f.runtime.capture(nextTrace.result.response,{trace:nextTrace,chat:f.chat,isCurrent:()=>true});assert.equal(await nextContext.validateSourcesCurrent(),true);assert.equal(f.counters().posts,1);});

test('completed receipt rejects result mutation during preview decode and source persistence',async()=>{let mutate=false;const f=await fixture({preview:graph=>{if(mutate){const node=graph.nodes.at(-1);node.fullImage=node.image='asset:changed';}}});await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.complete();await f.context.lookupVariants({source_refs:['node/source']});mutate=true;await assert.rejects(f.context.lookupVariants({source_refs:['node/source']}),e=>e.code==='output_changed');assert.equal(f.counters().posts,1);});

test('explicit terminal retry uses one existing target and retains both actual task IDs',async()=>{const f=await fixture();await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.jobs[0].status='failed';const second=await f.context.submitVariants(f.request(),{callId:'retry-call-id'});await f.dispatch();assert.equal(second.structuredContent.node_id,'node/target-1');assert.equal(f.graph.nodes.length,2);assert.equal(f.counters().posts,2);assert.deepEqual(f.trace.previsJobs.map(r=>r.job_id),['real-job-1','real-job-2']);await f.context.submitVariants(f.request(),{callId:'retry-call-id'});assert.equal(f.counters().posts,2);});

test('selected variants carry real textures and source hashes into a fresh trusted projection',async()=>{const f=await fixture();await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.complete();await f.context.lookupVariants({source_refs:['node/source']});const record=f.trace.previsJobs[0],image={kind:'cell',texture_id:'variant-'+record.target_ref,sheet_node_ref:record.target_ref,cell:4};f.trace.appState.edits.S1={dur:3,move:'push_in',curve:'smooth',trans:'cut',image};f.trace.appState.variants.S1={plan_id:record.plan_id,call_id:'actual-call-id',status:'ready',node_id:record.target_ref};const details={type:'app_reply',reply_id:crypto.randomUUID(),action:'previs_reply',payload:f.m.previsReplyPayload(f.trace.result.response,f.trace.appState)};const applied=await f.context.applyReply(details);assert.ok(applied.manifest.textures.some(t=>t.sheet_node_ref===record.target_ref));const projection=await f.context.querySheets();assert.ok(projection.projection.previsSourceContext.sources.some(s=>s.node_ref===record.target_ref&&s.source_sha256===record.receipt.output_sha256));assert.equal(projection.manifest.sheets[0].shots[0].image.cell,4);});

test('disposing a temporary authorized tool context does not cancel its durable task, real scope changes still do',async()=>{let release;const gate=new Promise(resolve=>release=resolve),f=await fixture({dispatchGate:gate});await f.context.submitVariants(f.request(),{callId:'actual-call-id'});f.context.dispose();release();await f.dispatch();assert.equal(f.jobs[0].status,'running');let releaseBad;const badGate=new Promise(resolve=>releaseBad=resolve),g=await fixture({dispatchGate:badGate});await g.context.submitVariants(g.request(),{callId:'actual-call-id'});g.context.dispose();g.setCurrent(false);releaseBad();await g.dispatch();assert.equal(g.jobs[0].status,'failed');});

test('selected variant deletion while confirm is saving rolls back the prepared reply and commits compensation',async()=>{let remove=false;const f=await fixture({save:trace=>{if(remove&&trace.previsReplies){const target=f.graph.nodes.find(n=>n.id==='target-1');f.graph.nodes.splice(f.graph.nodes.indexOf(target),1);}return true;}});await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.complete();await f.context.lookupVariants({source_refs:['node/source']});const record=f.trace.previsJobs[0];f.trace.appState.edits.S1={dur:3,move:'push_in',curve:'smooth',trans:'cut',image:{kind:'cell',texture_id:'variant-'+record.target_ref,sheet_node_ref:record.target_ref,cell:2}};f.trace.appState.variants.S1={plan_id:record.plan_id,call_id:'actual-call-id',status:'ready',node_id:record.target_ref};const details={type:'app_reply',reply_id:crypto.randomUUID(),action:'previs_reply',payload:f.m.previsReplyPayload(f.trace.result.response,f.trace.appState)};remove=true;await assert.rejects(f.context.applyReply(details),e=>e.code==='output_changed');assert.equal(f.trace.previsReplies,undefined);assert.equal(f.trace.previsManifest,undefined);});

test('reload GET verifies the previously saved selected variant and restores only its real texture without POST or canvas application',async()=>{const f=await fixture();await f.context.submitVariants(f.request(),{callId:'actual-call-id'});await f.dispatch();f.complete();await f.context.lookupVariants({source_refs:['node/source']});const record=f.trace.previsJobs[0],job=structuredClone(f.jobs[0]);f.trace.appState.edits.S1={dur:3,move:'push_in',curve:'smooth',trans:'cut',size:'ELS',image:{kind:'cell',texture_id:'variant-'+record.target_ref,sheet_node_ref:record.target_ref,cell:0}};f.trace.appState.variants.S1={plan_id:record.plan_id,call_id:'actual-call-id',status:'ready',node_id:record.target_ref};const savedState=structuredClone(f.trace.appState),beforeNodes=JSON.stringify(f.graph.nodes);f.jobs.length=0;let gets=0;f.generationAPI.recover=async id=>{gets++;assert.equal(id,record.job_id);const restored={...structuredClone(job),recovered:true,applied:false};delete restored.resultIds;f.jobs.push(restored);return restored;};const value=await f.context.querySelectedVariants();assert.equal(gets,1);assert.equal(f.counters().posts,1);assert.equal(value.changed,true);assert.ok(value.projection.response.textures.some(t=>t.texture_id==='variant-'+record.target_ref&&t.image_url));assert.ok(value.projection.previsSourceContext.sources.some(s=>s.node_ref===record.target_ref&&s.source_sha256===record.receipt.output_sha256));assert.deepEqual(f.trace.appState,savedState);assert.equal(JSON.stringify(f.graph.nodes),beforeNodes);assert.equal(f.jobs[0].applied,false);f.assets.set('asset:result',Buffer.from('changed'));await assert.rejects(f.context.querySelectedVariants(),e=>e.code==='output_changed');assert.equal(f.counters().posts,1);});
