const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const {parse}=require('../agent-tools.js'),tick=()=>new Promise(setImmediate),deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
const uri=name=>'ui://tapnow/'+name+'@'+(name==='previs'?'v3':'v2');
class Surface{constructor(){this.events=new Map();}addEventListener(n,f){if(!this.events.has(n))this.events.set(n,new Set());this.events.get(n).add(f);}removeEventListener(n,f){this.events.get(n)?.delete(f);}emit(n,v){for(const f of this.events.get(n)||[])f(v);}}
async function hostFixture(name,callbacks){
 const {createMcpAppHost}=await import('../src/features/agent-apps/host.mjs'),window=new Surface(),iframe=new Surface(),sent=[];let seq=0;
 Object.assign(window,{crypto:crypto.webcrypto,navigator:{userActivation:{isActive:false}},setTimeout:()=>++seq,clearTimeout(){},setInterval:()=>++seq,clearInterval(){}});
 const document={defaultView:window,activeElement:null};Object.assign(iframe,{ownerDocument:document,isConnected:true,contentWindow:{postMessage:m=>sent.push(structuredClone(m))}});
 const host=createMcpAppHost({iframe,resourceUri:uri(name),toolInput:{},toolResult:{},isCurrent:()=>true,allowResource:()=>true,callbacks});host.start();
 const rpc=(id,method,params={},gesture=false)=>{document.activeElement=gesture?iframe:null;window.navigator.userActivation.isActive=gesture;window.emit('message',{source:iframe.contentWindow,data:{jsonrpc:'2.0',nonce:sent.findLast(m=>m.method==='ui/notifications/sandbox-resource-ready').nonce,...(id===null?{}:{id}),method,params}});window.navigator.userActivation.isActive=false;};
 rpc('init','ui/initialize');rpc(null,'ui/notifications/initialized');return {host,rpc,sent,response:id=>sent.findLast(m=>m.id===id),close:()=>host.dispose()};
}
const call=(name,extra={})=>({name,arguments:{actual:'scope'},_meta:{'tapnow/callId':'actual-call-id'},...extra}),receipt={content:[],structuredContent:{task_id:'real-task',status:'pending'}};
for(const name of ['animatic','previs','ecommerce-photoset'])test(name+' host tools stay scoped to actual user action and passive lookups',async()=>{
 const calls=[],tool=name==='ecommerce-photoset'?'ecommerce_photoset_generate':name+'_variants_submit',f=await hostFixture(name,{onGenerationAppTool:(n,a,o)=>{calls.push({n,a,o});return receipt;}});
 try{f.rpc('passive','tools/call',call(tool));await tick();assert.match(f.response('passive').error.message,/user action/);f.rpc('unknown','tools/call',call('canvas_delete'),true);await tick();assert.equal(f.response('unknown').error.code,-32601);f.rpc('submit','tools/call',call(tool),true);await tick();assert.deepEqual(f.response('submit').result,receipt);assert.equal(calls.length,1);assert.equal(calls[0].o.userAction,true);assert.equal(calls[0].o.callId,'actual-call-id');f.host.updateConversationRunActive(true);f.rpc('busy','tools/call',call(tool),true);await tick();assert.match(f.response('busy').error.message,/idle/);if(name!=='ecommerce-photoset'){f.rpc('lookup','tools/call',{name:name+'_variants_lookup',arguments:{source_refs:[]}});await tick();assert.deepEqual(f.response('lookup').result,receipt);assert.equal(calls[1].o.userAction,false);}f.rpc('authority','tools/call',call(tool,{_meta:{'tapnow/callId':'actual-call-id',approved:true}}),true);await tick();assert.ok(f.response('authority').error);}finally{f.close();}
});
test('generation configuration errors preserve domain reason without a generated success',async()=>{const f=await hostFixture('animatic',{onGenerationAppTool:()=>{throw Object.assign(Error('请先配置本机图像生成服务'),{code:'configuration_required'});}});try{f.rpc('blocked','tools/call',call('animatic_variants_submit'),true);await tick();assert.equal(f.response('blocked').error.code,-32000);assert.match(f.response('blocked').error.message,/配置/);assert.equal(f.response('blocked').result,undefined);}finally{f.close();}});
const reply_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',manifest_revision='a'.repeat(64),details={type:'app_reply',reply_id,action:'previs_reply',payload:{schema_version:'previs_reply.v1',decision:'confirm',edits:[],deleted_shot_codes:[],order:['A'],variant_selections:[]}};
test('previs preflight grants one exact deferred reply and returns the actual queue identity',async()=>{
 const calls=[],f=await hostFixture('previs',{onValidateAppReply:()=>({manifest_revision}),onAppReply:(d,o)=>{calls.push({d,o});return {reply_id:d.reply_id,run_id:'actual-submission',deduped:false};},onAppReplyRunStatus:()=>({status:'waiting'})});
 try{f.rpc('preflight','tapnow/validateAppReply',details,true);await tick();assert.equal(f.response('preflight').result.manifest_revision,manifest_revision);const message={role:'user',content:[],details:{...details,expected_manifest_revision:manifest_revision}};f.rpc('different','ui/message',{...message,details:{...message.details,payload:{...details.payload,order:['B']}}});await tick();assert.ok(f.response('different').error);assert.equal(calls.length,0);f.host.updateConversationRunActive(true);f.rpc('busy','ui/message',message);await tick();assert.match(f.response('busy').error.message,/busy/);assert.equal(calls.length,0);f.host.updateConversationRunActive(false);f.rpc('accept','ui/message',message);await tick();assert.deepEqual(f.response('accept').result,{reply_id,run_id:'actual-submission',deduped:false});assert.equal(calls[0].o.userAction,true);f.rpc('twice','ui/message',message);await tick();assert.ok(f.response('twice').error);f.rpc('status','tapnow/getAppReplyRunStatus',{run_id:'actual-submission'});await tick();assert.deepEqual(f.response('status').result,{status:'waiting'});f.rpc('scope','tapnow/getAppReplyRunStatus',{run_id:'actual-submission',reply_id});await tick();assert.ok(f.response('scope').error);}finally{f.close();}
});
test('previs updateData clears preflight authority and other apps reject structured replies',async()=>{
 const f=await hostFixture('previs',{onValidateAppReply:()=>({manifest_revision}),onAppReply:()=>({reply_id,run_id:'real',deduped:false})});try{f.rpc('preflight','tapnow/validateAppReply',details,true);await tick();f.host.updateData({toolResult:{},widgetState:null});f.rpc('reply','ui/message',{role:'user',content:[],details:{...details,expected_manifest_revision:manifest_revision}});await tick();assert.ok(f.response('reply').error);}finally{f.close();}
 const g=await hostFixture('animatic',{onSendPrompt:()=>true,onGenerationAppTool:()=>receipt});try{g.rpc('reply','ui/message',{role:'user',content:[],details},true);await tick();assert.ok(g.response('reply').error);}finally{g.close();}
});
test('ecommerce estimate never fabricates Tapies cost and rejects invalid counts',async()=>{const f=await hostFixture('ecommerce-photoset',{onGenerationAppTool:()=>receipt});try{f.rpc('cost','tapnow/estimateGenerationCost',{model:'configured',ratio:'1:1',image_size:'1K',times:3,request_count:2});await tick();assert.deepEqual({...f.response('cost').result,reason:undefined},{status:'unavailable',reason:undefined,item_count:2,output_count:6});assert.doesNotMatch(f.response('cost').result.reason,/Tapies/);for(const [i,input]of [{times:0,request_count:2},{times:16,request_count:2},{times:1,request_count:33}].entries()){f.rpc('invalid'+i,'tapnow/estimateGenerationCost',input);await tick();assert.ok(f.response('invalid'+i).error);}}finally{f.close();}});
const shot={shot_code:'A',cell:0,duration:2,move:'static',size:'MS',script_text:'actual'},plan={version:2,sheets:[{sheet_id:'S',shots:[shot]}],beats:[{beat_id:'beat',text:'节奏',shot_codes:['A']}]};
test('raw app tools accept script or real node plans and reject model media/duplicate scopes',()=>{
 const args={resource_uri:uri('animatic'),data:plan};assert.equal(parse('show_app',args).definition.mutates,false);assert.doesNotThrow(()=>parse('show_app',{...args,data:{...plan,sheets:[{sheet_id:'S',shots:[{...shot,node_ref:'node/source'}]}]}}));for(const data of [{...plan,beats:[{beat_id:'beat',text:'节奏',shot_codes:['invented']}]},{...plan,sheets:[{sheet_id:'S',shots:[{...shot,image:{url:'data:image/png;base64,AAAA'}}]}]},{...plan,sheets:[{sheet_id:'S',shots:[shot,shot]}]}])assert.throws(()=>parse('show_app',{...args,data}));assert.doesNotThrow(()=>parse('show_app',{resource_uri:uri('previs'),data:{sheets:[{sheet_id:'S',shots:[{shot_code:'A',cell:0,duration:2,move:'static',dialogue:{text:'line',est_duration:100}}]}]}}));
 assert.doesNotThrow(()=>parse('show_app',{resource_uri:uri('ecommerce-photoset'),data:{mode:'amazon',product_context:{product_label:'产品',product_node_ids:['actual']},requirements:[{sequence:1,theme:'主题',visual_requirement:'画面',copy_requirement:'文案'}],params:{model:'configured',aspect_ratio:'1:1',resolution:'1K',image_variant_count:2}}}));
 const generate={trace_id:'actual-trace',reply_id,shot_codes:['A']};assert.equal(parse('previs_generate_sheet',generate).definition.mutates,true);assert.throws(()=>parse('previs_generate_sheet',{...generate,approved:true}));
});
function queueFixture(){
 const source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8'),start=source.indexOf(' function queueWidgetPrompt('),end=source.indexOf(' const previsProjectionWork=',start),trace={id:'trace',name:'show_app',status:'done',callId:'call',result:{resource_uri:uri('previs')},appState:{}},chat={id:'chat',messages:[trace],queuedMessages:[]},events=[];let gate=null,valid=true;
 const context={recoveryRunning:false,appQueueSaving:false,pageLeaving:false,panel:{},draft:()=>chat,busy:false,queueRunner:{running:false,drain(){events.push('drain');}},queueModule:{captureSubmission:input=>({id:'actual-submission',text:input.text})},modelModule:{prepareSessionSelection:()=>({})},composerModule:{textDocument:text=>({text})},clone:structuredClone,validateSubmission(){},persistQueue(){events.push('persist');},flushConversation:async()=>{events.push('flush');if(gate)await gate.promise;},track:fn=>fn(),render(){}};
 vm.runInNewContext(source.slice(start,end)+';globalThis.queue=queueWidgetPrompt;',context);return {context,trace,chat,events,setGate:v=>gate=v,setCurrent:v=>valid=v,queue:commit=>context.queue('exact reply',trace,chat,{appReplyId:reply_id,appReplyFingerprint:manifest_revision},()=>valid,async()=>{if(!valid)throw Error('actual source changed');},commit)};
}
test('previs durable queue binds accepted callback before drain and dedupes exact submission identity',async()=>{const f=queueFixture();let commit=0;const result=await f.queue(async receipt=>{commit++;assert.equal(f.context.appQueueSaving,true);assert.equal(f.chat.queuedMessages[0].id,receipt.run_id);f.events.push('accepted');});assert.deepEqual(JSON.parse(JSON.stringify(result)),{reply_id,run_id:'actual-submission',deduped:false});assert.equal(f.trace.appReplyReceipts[0].run_id,'actual-submission');assert.equal(f.chat.queuedMessages[0].widgetOrigin.appReplyId,reply_id);assert.deepEqual(f.events,['persist','flush','accepted','drain']);f.context.recoveryRunning=true;assert.equal((await f.queue()).deduped,true);assert.equal(commit,1);assert.throws(()=>f.context.queue('changed',f.trace,f.chat,{appReplyId:reply_id,appReplyFingerprint:'b'.repeat(64)}),/不能改变/);});
test('previs failed save/acceptance compensates queue and receipts without starting a run',async()=>{for(const failure of ['source','accept']){const f=queueFixture(),gate=deferred();f.setGate(gate);const pending=f.queue(async()=>{throw Error('accepted receipt save failed');});assert.equal(f.chat.queuedMessages.length,1);assert.equal(f.context.appQueueSaving,true);if(failure==='source')f.setCurrent(false);f.setGate(null);gate.resolve();await assert.rejects(pending,failure==='source'?/source changed/:/save failed/);assert.equal(f.chat.queuedMessages.length,0);assert.equal(f.trace.appReplyReceipts,undefined);assert.equal(f.context.appQueueSaving,false);assert.ok(!f.events.includes('drain'));assert.equal(f.events.filter(e=>e==='persist').length,2);}});
test('ecommerce local billing derivative is exact-hash bound, covers five languages and preserves confirm logic',async()=>{
 const source=fs.readFileSync('src/features/agent-apps/resources/apps/ecommerce-photoset@v2.a7b6a057.html','utf8'),proxy=fs.readFileSync('src/features/agent-apps/resources/mcp-app-proxy.html','utf8'),begin=proxy.indexOf('// ECOMMERCE_LOCAL_BILLING:BEGIN'),end=proxy.indexOf('// ECOMMERCE_LOCAL_BILLING:END'),fn=vm.runInNewContext(proxy.slice(begin,end)+';localizeEcommerceBilling',{crypto:crypto.webcrypto,TextEncoder,Uint8Array}),result=await fn(source,'ecommerce-photoset','v2');
 assert.equal(crypto.createHash('sha256').update(source).digest('hex'),'a7b6a057ceeb55ec0cef26e35d33e18c42c53aec26b2c1d6032e04294b401861');assert.doesNotMatch(result,/Tapies/);assert.match(result,/未提供费用估算/);assert.match(result,/已配置供应商按实际用量计费/);assert.equal((result.match(/confirmBillingWarning:/g)||[]).length,5);const removeBilling=v=>v.replace(/(?:estimatingCost|estimateUnavailable|confirmBilling|confirmBillingWarning):"(?:[^"\\]|\\.)*"/g,'LOCAL-BILLING');assert.equal(removeBilling(result),removeBilling(source));assert.equal(await fn(source,'animatic','v2'),source);await assert.rejects(fn(source+' ','ecommerce-photoset','v2'),/integrity/);await assert.rejects(fn(source,'ecommerce-photoset','v3'),/version/);
});
test('three registered app policies match official presentation and photoset state limit',async()=>{const {appPolicy,getApp}=await import('../src/features/agent-apps/registry.mjs');for(const name of ['animatic','previs'])assert.deepEqual({...appPolicy(uri(name)),proxyUrl:undefined},{allowExpanded:true,autoExpandOnReady:true,proxyUrl:undefined});assert.equal(appPolicy(uri('ecommerce-photoset')).allowExpanded,false);assert.equal(getApp(uri('ecommerce-photoset')).stateLimit,128*1024);});
test('trusted configuration classification data is narrowly scoped and previs statuses follow actual receipts',async()=>{
 const f=await hostFixture('previs',{onGenerationAppTool:()=>{throw Object.assign(Error('本机服务未配置'),{code:'configuration_required'});}});try{f.rpc('blocked','tools/call',call('previs_variants_submit'),true);await tick();assert.deepEqual(f.response('blocked').error.data,{code:'configuration_required',providerDispatched:false});f.host.updateAppReplyStatus(reply_id,'running');assert.deepEqual(f.sent.at(-1).params,{reply_id,reply_run_status:'running'});assert.equal(f.host.updateAppReplyStatus(reply_id,'running'),false);f.host.updateAppReplyStatus(reply_id,'completed');assert.equal(f.sent.at(-1).params.reply_run_status,'completed');assert.throws(()=>f.host.updateAppReplyStatus(reply_id,'invented'),/actual/);}finally{f.close();}
 const g=await hostFixture('animatic',{onGenerationAppTool:()=>{throw Object.assign(Error('actual task failed'),{code:'submit_failed'});}});try{g.rpc('fail','tools/call',call('animatic_variants_submit'),true);await tick();assert.equal(g.response('fail').error.data,undefined);assert.equal(g.host.updateAppReplyStatus(reply_id,'running'),false);}finally{g.close();}
});
test('previs completed sheet projection can refresh in several batches and preserves new user edits',async()=>{
 const m=await import('../src/features/agent-apps/previs.mjs'),source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8'),begin=source.indexOf(' const previsProjectionWork='),end=source.indexOf(' async function appReplyRunStatus(',begin),data=m.preparePrevis({sheets:[{sheet_id:'S1',shots:[{shot_code:'A',cell:0,duration:2,move:'static'}]},{sheet_id:'S2',shots:[{shot_code:'B',cell:0,duration:2,move:'static'}]}]}),state=m.initialPrevisState(data);state.edits.A={dur:3,move:'push_in',curve:'smooth',trans:'cut'};
 const trace={id:'trace',result:{resource_uri:uri('previs'),response:data},appState:state,previsJobs:[{kind:'sheet'}],previsReplies:[{reply_id,manifest_revision,status:'accepted',run_id:'real',payload:m.previsReplyPayload(data,state)}]},chat={messages:[trace]};let phase=1,queries=0,saves=0;
 const context={WeakMap,restorePrevisSelectionProjection:async()=>{},track:fn=>fn(),pageLeaving:false,panel:{},draft:()=>chat,__module:m,save:()=>{saves++;return true;},flushConversation:async()=>{},render(){},getGenerationAppSourceContext:()=>({guard:()=>true,dispose(){},validateSourcesCurrent:async()=>true,querySheets:async()=>{queries++;const manifest=m.applyPrevisPayload(data,trace.previsReplies[0].payload);manifest.sheets[0].sheet_node_ref='node/real-first';if(phase===2)manifest.sheets[1].sheet_node_ref='node/real-second';return {changed:true,projection:{response:manifest,previsSourceContext:{actual:true}}};}})};
 vm.runInNewContext(source.slice(begin,end).replace("await import('./src/features/agent-apps/previs.mjs')",'__module')+';globalThis.refresh=refreshPrevisProjection;',context);
 await context.refresh(trace,chat);assert.equal(trace.result.response.sheets[0].sheet_node_ref,'node/real-first');assert.equal(trace.appState.edits.A,undefined);assert.equal(trace.previsProjectionReceipt.reply_id,reply_id);phase=2;await context.refresh(trace,chat);assert.equal(trace.result.response.sheets[1].sheet_node_ref,'node/real-second');assert.equal(trace.projection_revision.part_index,2);assert.equal(queries,2);trace.appState.edits.A={dur:4,move:'static',curve:'smooth',trans:'cut'};await context.refresh(trace,chat);assert.equal(queries,2);assert.equal(trace.appState.edits.A.dur,4);assert.equal(saves,2);
});
test('previs actual run status reads queue, active identity, pending question, interruption and committed completion',async()=>{
 const source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8'),begin=source.indexOf(' async function appReplyRunStatus('),end=source.indexOf(' function send(){',begin),trace={id:'trace',result:{resource_uri:uri('previs')},appReplyReceipts:[{reply_id,run_id:'real',status:'waiting'}]},item={id:'real',widgetOrigin:{resourceUri:uri('previs'),traceId:'trace',appReplyId:reply_id}},chat={messages:[trace],queuedMessages:[item]},context={draft:()=>chat,pendingResolve:null,refreshPrevisProjection:async()=>{}};
 vm.runInNewContext(source.slice(begin,end)+';globalThis.status=appReplyRunStatus;globalThis.mark=markAppReplyRun;',context);const status=async()=> (await context.status({run_id:'real'},trace,chat)).status;assert.equal(await status(),'waiting');chat.activeRun={submissionId:'other'};assert.equal(await status(),'waiting');chat.queuedMessages=[];chat.activeRun.submissionId='real';assert.equal(await status(),'running');context.pendingResolve=()=>{};assert.equal(await status(),'waiting');context.pendingResolve=null;delete chat.activeRun;chat.interruptedRuns=[{submissionId:'real'}];assert.equal(await status(),'unknown');chat.interruptedRuns=[];context.mark(chat,item,'completed');assert.equal(await status(),'inactive');assert.equal((await context.status({run_id:'invented'},trace,chat)).status,'unknown');
});
test('new app ledgers remain historical evidence and omit actual media/secrets',async()=>{
 const {readConversation}=await import('../src/features/agent-history/context.mjs'),traces=['animatic','previs','ecommerce-photoset'].map((name,i)=>({id:'trace'+i,role:'tool',name:'show_app',status:'done',result:{kind:'mcp_app',resource_uri:uri(name),response:{}},animaticJobs:[{job_id:'real'}],appReplyReceipts:[{run_id:'actual-submission',status:'completed'}],ecommercePhotosetOperations:[{call_id:'actual-call',output:'data:image/png;base64,AAAA',secret:'credential'}]})),result=readConversation({id:'chat',messages:traces});assert.equal(result.historicalEvidenceOnly,true);const json=JSON.stringify(result);assert.match(json,/actual-submission/);assert.match(json,/photoSetOperations/);assert.match(json,/actual-call/);assert.doesNotMatch(json,/AAAA|credential|data:image/);
});
test('previs exact display derivative removes fixed credits and preserves known pre-dispatch configuration errors',async()=>{
 const source=fs.readFileSync('src/features/agent-apps/resources/apps/previs@v3.584fd5b2.html','utf8'),proxy=fs.readFileSync('src/features/agent-apps/resources/mcp-app-proxy.html','utf8'),begin=proxy.indexOf('// PREVIS_LOCAL_BILLING:BEGIN'),end=proxy.indexOf('// PREVIS_LOCAL_BILLING:END'),fn=vm.runInNewContext(proxy.slice(begin,end)+';localizePrevisBilling',{crypto:crypto.webcrypto,TextEncoder,Uint8Array}),result=await fn(source,'previs','v3');assert.doesNotMatch(result,/26 credits|26 积分/);assert.match(result,/费用由供应商决定/);const changes=JSON.parse(proxy.slice(begin,end).match(/var changes = (.*);/)[1]);let restored=result;for(const [original,local]of changes)restored=restored.replace(local,original);assert.equal(restored,source);assert.match(result,/configurationRequired/);const scripts=[...result.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]);for(const script of scripts)require('node:child_process').execFileSync(process.execPath,['--input-type=module','--check'],{input:script});await assert.rejects(fn(source+' ','previs','v3'),/integrity/);
});
async function controllerFixture(name){
 const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric')),domRequire=createRequire(fabricRequire.resolve('jsdom')),canvasPath=domRequire.resolve('canvas'),cached=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};let JSDOM;try{({JSDOM}=fabricRequire('jsdom'));}finally{if(cached)require.cache[canvasPath]=cached;else delete require.cache[canvasPath];}
 const dom=new JSDOM('<body></body>',{url:'http://localhost:4173/'}),previous=globalThis.document;globalThis.document=dom.window.document;dom.window.crypto.randomUUID=()=>crypto.randomUUID();Object.defineProperty(dom.window.navigator,'userActivation',{value:{isActive:true}});
 const {createAppController,prepareApp}=await import('../src/features/agent-apps/integration.mjs'),model=await import('../src/features/agent-apps/'+name+'.mjs'),data=name==='animatic'?{version:2,sheets:[{sheet_id:'S',shots:[shot]}]}:{mode:'freeform',product_context:{product_label:'actual product',product_node_ids:['actual']},requirements:[{sequence:1,theme:'主题',visual_requirement:'画面',copy_requirement:'文案'}],params:{model:'configured',aspect_ratio:'1:1',resolution:'1K',image_variant_count:1}},args={resource_uri:uri(name),data},trace={id:'trace',name:'show_app',status:'done',args,result:prepareApp(args)},chat={id:'chat',messages:[trace]},sent=[],queues=[],calls=[],errors=[];let captures=0,disposals=0;
 const validate=model[name==='animatic'?'validateAnimaticState':'validateEcommercePhotosetState'],controller=createAppController({getContext:()=>({chat,panelActive:true,pageLeaving:false,streaming:false}),getGenerationAppSourceContext:response=>{captures++;const bound=trace.result;return {guard:()=>{if(bound!==trace.result)throw Error('source changed');return true;},isCurrent:()=>bound===trace.result,validateSourcesCurrent:async()=>true,validateState:s=>validate(s,response),reply:async(text,state)=>{validate(state,response);return {text:'verified '+text,metadata:{}};},dispose:()=>disposals++};},onSaveState:async(c,t,s)=>{t.appState=s;},onGenerationAppTool:async(...a)=>{calls.push(a);return {task_id:'actual-task',status:'pending'};},onGenerationAppContext:async()=>({saved:true}),onQueuePrompt:async(text,t,c,m,guard,verify)=>{assert.equal(guard(),true);await verify();queues.push(text);return true;},onError:message=>errors.push(message)});
 const element=controller.render(trace);dom.window.document.body.append(element);const iframe=element.querySelector('iframe');iframe.contentWindow.postMessage=m=>sent.push(structuredClone(m));const rpc=(id,method,params={})=>dom.window.dispatchEvent(new dom.window.MessageEvent('message',{source:iframe.contentWindow,data:{jsonrpc:'2.0',nonce:sent.findLast(m=>m.method==='ui/notifications/sandbox-resource-ready')?.nonce,...id?{id}:{},method,params}})),response=id=>sent.findLast(m=>m.id===id);iframe.dispatchEvent(new dom.window.Event('load'));rpc('init','ui/initialize');rpc(null,'ui/notifications/initialized');iframe.focus();for(let i=0;i<30&&!trace.appState;i++)await tick();assert.ok(trace.appState);return {trace,controller,rpc,response,sent,queues,calls,errors,count:()=>({captures,disposals}),close(){controller.reset();dom.window.close();if(previous===undefined)delete globalThis.document;else globalThis.document=previous;}};
}
for(const name of ['animatic','ecommerce-photoset'])test(name+' production controller confirms saved state, unwraps scoped task receipts and recaptures projected sources',async()=>{
 const f=await controllerFixture(name);try{f.rpc('message','ui/message',{content:[{type:'text',text:'exact saved confirmation'}]});for(let i=0;i<30&&!f.response('message');i++)await tick();assert.equal(f.response('message').error,undefined);assert.equal(f.queues.length,1);assert.deepEqual(f.errors,[]);f.rpc('tool','tools/call',call(name==='animatic'?'animatic_variants_submit':'ecommerce_photoset_generate'));for(let i=0;i<30&&!f.response('tool');i++)await tick();assert.deepEqual(f.response('tool').result,{content:[],structuredContent:{task_id:'actual-task',status:'pending'}});assert.equal(f.calls.length,1);const old=f.trace.result;f.trace.result={...old,response:{...old.response,title:'materialized real sheet'}};f.trace.projection_revision={message_sequence:0,part_index:1};f.controller.render(f.trace);assert.deepEqual(f.count(),{captures:2,disposals:1});const update=f.sent.findLast(m=>m.method==='tapnow/updateData'&&m.params.toolResult);assert.equal(update.params.revision.part_index,1);assert.equal(update.params.toolResult.title,'materialized real sheet');}finally{f.close();}
});
test('selected previs texture restore preserves saved edits and persists source projection before recapture',async()=>{
 const source=fs.readFileSync(require.resolve('../agent-client.js'),'utf8'),begin=source.indexOf(' const previsSelectionWork='),end=source.indexOf(' const previsProjectionWork=',begin),state={edits:{A:{image:{kind:'cell',sheet_node_ref:'node/actual-variant',texture_id:'variant',cell:0},dur:3}},variants:{A:{status:'ready',node_id:'node/actual-variant'}}},trace={id:'trace',result:{resource_uri:uri('previs'),response:{textures:[]}},appState:state},chat={messages:[trace]},events=[];let reads=0;
 const context={WeakMap,Promise,pageLeaving:false,panel:{},draft:()=>chat,previsRuntime:{},track:fn=>fn(),save:()=>{events.push('save');return true;},flushConversation:async()=>{events.push('flush');},render:()=>events.push('render'),getGenerationAppSourceContext:response=>({guard:()=>true,dispose:()=>events.push('dispose'),validateSourcesCurrent:async()=>events.push('verify'),querySelectedVariants:async options=>{assert.equal(options.recover,true);reads++;return {changed:!response.textures.length,projection:{response:{textures:[{texture_id:'variant',sheet_node_ref:'node/actual-variant',image_url:'data:image/png;base64,REAL'}]},previsSourceContext:{sources:[{node_ref:'node/actual-variant',source_sha256:'a'.repeat(64)}]}}};}})};
 vm.runInNewContext(source.slice(begin,end)+';globalThis.restore=restorePrevisSelectionProjection;',context);await context.restore(trace,chat);assert.equal(trace.appState,state);assert.equal(trace.appState.edits.A.dur,3);assert.equal(trace.result.response.textures[0].sheet_node_ref,'node/actual-variant');assert.equal(trace.result.previsSourceContext.sources[0].source_sha256,'a'.repeat(64));assert.ok(events.indexOf('flush')<events.indexOf('verify'));assert.ok(events.indexOf('verify')<events.indexOf('render'));assert.equal(trace.projection_revision.part_index,1);await context.restore(trace,chat);await context.restore(trace,chat);assert.equal(reads,2,'same restored response and edits coalesce readonly verification');
});
