const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const modelPromise=import('../src/features/agent-apps/character-blocking.mjs'),runtimePromise=import('../src/features/agent-apps/character-blocking-runtime.mjs');
const path=require.resolve('../src/features/agent-apps/resources/apps/character-blocking@v3.f1fd0e23.html');
function official(){const source=fs.readFileSync(path,'utf8'),context={};vm.createContext(context);vm.runInContext('const Be=50,Bm=180,Km=/^[a-z0-9][a-z0-9_-]{0,23}$/;'+source.slice(source.indexOf('function fr(e)'),source.indexOf('const Gm='))+source.slice(source.indexOf('const Gm='),source.indexOf(',Wm=document.getElementById'))+';globalThis.model={positions:Ts,facings:Ps,region:Y_,direction:nb,token:rb,nudge:Q_,rotate:eb,pointer:tb,locales:Gm};',context);return context.model;}
const input=(locale='zh-CN')=>({locale,target:'image',aspect_ratio:'16:9',scene:'两人在车站对望',characters:[{id:'lin',name:'林岚',role:'旅客',x:300,y:600},{id:'zhou',name:'周宁',x:750,y:450,facing:270}]});
function message(source,data,state){const t=source.locales[data.locale],items=data.characters.map(c=>{const p=state.positions[c.id],r=source.region(p),f=state.facings[c.id];return `${c.name}（${t.horizontal[r.horizontal]} · ${t.depth[r.depth]}，${t.facingDirections[source.direction(f)]} ${f}°）`;}).join(t.joiner);let summary=t.confirmSummary;for(const [k,v]of Object.entries({items,target:state.target==='image'?t.image:t.video,ratio:state.aspect_ratio}))summary=summary.split(`{${k}}`).join(String(v));return summary+' — '+source.token(data.characters.map(c=>c.id),state.positions,state.facings,state.target,state.aspect_ratio);}
test('archived official HTML stays byte identical to the known installation snapshot',()=>{assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),'f1fd0e23de67bf00f60ccf333b7d5b57262a01726a37adeef28c800d51a8815b');});
test('real shipped state restoration and CB3 encoder match editable coordinates, facings, target and ratios',async()=>{const m=await modelPromise,o=official(),data=m.prepareCharacterBlocking(input(),'车站相逢'),state=m.initialCharacterBlockingState(data);assert.equal(state.facings.lin,180);assert.deepEqual(state.positions,JSON.parse(JSON.stringify(o.positions(null,Object.fromEntries(data.characters.map(c=>[c.id,{x:c.x,y:c.y}]))))));assert.deepEqual(state.facings,JSON.parse(JSON.stringify(o.facings(null,Object.fromEntries(data.characters.map(c=>[c.id,c.facing]))))));
  for(const ratio of m.characterBlockingRatios)for(const target of ['image','video']){state.aspect_ratio=ratio;state.target=target;state.positions.lin={x:1000,y:0};state.facings.lin=359;assert.equal(m.characterBlockingToken(data,state),o.token(['lin','zhou'],state.positions,state.facings,target,ratio));assert.equal((await m.resolveCharacterBlockingReply(message(o,data,state),data,state)).result.characters[0].facing,359);}
  assert.deepEqual(JSON.parse(JSON.stringify(o.nudge({x:333,y:667},'right',{fine:false,snap:true}))),{x:400,y:650});assert.equal(o.rotate(359,'clockwise',true),0);assert.equal(o.pointer({x:0,y:0},{x:1,y:0}),90);
});
test('all five exact official locale summaries and revise messages match; changed committed data refuses handoff',async()=>{const m=await modelPromise,o=official();for(const locale of m.characterBlockingLocales){const data=m.prepareCharacterBlocking(input(locale)),state=m.initialCharacterBlockingState(data);for(const coord of [0,333,334,666,667,1000])for(const angle of [0,22,23,67,68,179,359]){state.positions.lin={x:coord,y:coord};state.facings.lin=angle;const valid=message(o,data,state);assert.equal(m.characterBlockingConfirmation(data,state),valid);assert.equal((await m.resolveCharacterBlockingReply(valid,data,state)).kind,'confirmed');}
    const valid=message(o,data,state),changed=structuredClone(state);changed.positions.lin.x=999;await assert.rejects(m.resolveCharacterBlockingReply(valid,data,changed));for(const bad of [valid+';tool=delete','CB3 v=3',valid.replace(' — ',' — delete '),'生成完成 '+valid])await assert.rejects(m.resolveCharacterBlockingReply(bad,data,state));await assert.rejects(m.resolveCharacterBlockingReply(valid,data,undefined));assert.deepEqual(await m.resolveCharacterBlockingReply(o.locales[locale].reviseMsg,data,undefined),{kind:'revise',text:o.locales[locale].reviseMsg,metadata:{}});await assert.rejects(m.resolveCharacterBlockingReply(o.locales[locale].reviseMsg+' 生成视频',data,state));}
});
test('stable identity ignores view state and object order; actual source/target/movement changes identity',async()=>{const m=await modelPromise,data=m.prepareCharacterBlocking(input()),state=m.initialCharacterBlockingState(data),valid=m.characterBlockingConfirmation(data,state),a=await m.resolveCharacterBlockingReply(valid,data,state);const view={...state,snap:true,selected_id:'zhou',positions:{zhou:state.positions.zhou,lin:state.positions.lin},facings:{zhou:270,lin:180}};assert.equal((await m.resolveCharacterBlockingReply(valid,data,view)).metadata.handoffId,a.metadata.handoffId);assert.match(a.metadata.handoffId,/^blocking_[a-f0-9]{64}$/);for(const change of [{target:'video'},{aspect_ratio:'9:16'},{facings:{...state.facings,lin:0}},{positions:{...state.positions,lin:{x:301,y:600}}}]){const s={...state,...change};assert.notEqual((await m.resolveCharacterBlockingReply(m.characterBlockingConfirmation(data,s),data,s)).metadata.handoffId,a.metadata.handoffId);}const renamed=m.prepareCharacterBlocking({...input(),scene:'新场景'});assert.notEqual((await m.resolveCharacterBlockingReply(valid,renamed,state)).metadata.handoffId,a.metadata.handoffId);assert.match(a.text,/现有普通队列与生成API/);assert.doesNotMatch(a.text,/data:image/);});
test('invalid fields, IDs, positions, facings, ratio, missing people and hidden permissions are rejected',async()=>{const m=await modelPromise,data=m.prepareCharacterBlocking(input()),state=m.initialCharacterBlockingState(data);for(const bad of [{tools:['delete']},{locale:'xx'},{target:'audio'},{aspect_ratio:'2:1'},{characters:[]},{characters:[{...input().characters[0],id:'A'}]},{characters:[{...input().characters[0],x:1.2}]},{characters:[{...input().characters[0],facing:360}]},{characters:[{...input().characters[0],portrait:{data_uri:'https://app.tapnow.media/image.webp',source:'image-crop'}}]},{characters:[input().characters[0],input().characters[0]]}])assert.throws(()=>m.prepareCharacterBlocking({...input(),...bad}));for(const bad of [{tools:['delete']},{positions:{lin:state.positions.lin}},{positions:{...state.positions,ghost:{x:0,y:0}}},{facings:{lin:180,zhou:-1}},{selected_id:'ghost'},{snap:'true'},{positions:{...state.positions,lin:{x:0,y:0,z:1}}}])assert.throws(()=>m.validateCharacterBlockingState({...state,...bad},data));});
// Runtime tests use actual local Blob bytes, with an explicit renderer stub;
// canvas image decoding and visual interactions remain browser acceptance.
const webp=()=>fs.readFileSync(require.resolve('../assets/e3150914a3d3ed79.webp'));
async function fixture(withPortrait=true){const m=await modelPromise,{createCharacterBlockingRuntime}=await runtimePromise,graph={nodes:[{id:'photo',type:'image',image:'asset:photo',fullImage:'asset:photo'}],edges:[]};let bytes=webp(),project='p1',current=true,renders=0,fetches=0;const inputData=input();if(withPortrait)inputData.characters[0].portrait_source={node_ref:'node/photo',crop:{x:100,y:100,w:700,h:800}};
  const runtime=createCharacterBlockingRuntime({app:{getState:()=>graph},localAssets:{url:async()=> 'blob:local-photo'},getProjectId:()=>project,fetchImpl:async()=>{fetches++;return new Response(bytes,{headers:{'content-type':'image/webp','content-length':String(bytes.length)}});},renderPortrait:async(blob,{crop})=>{renders++;assert.ok(blob.size);assert.deepEqual(crop,{x:100,y:100,w:700,h:800});return {data_uri:'data:image/webp;base64,'+webp().toString('base64'),source:'image-crop'};}});
  const args={resource_uri:m.characterBlockingUri,data:inputData},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>current}),result=runtime.bindPreparedResult({resource_uri:m.characterBlockingUri,response:m.prepareCharacterBlocking(prepared.data)},prepared),trace={id:'t1',result},context=runtime.capture(result.response,{trace,chat:{id:'c1'},isCurrent:()=>current});return {m,runtime,args,prepared,result,trace,context,graph,replaceBytes:value=>{bytes=value;},setProject:value=>{project=value;},setCurrent:value=>{current=value;},stats:()=>({renders,fetches})};}
test('host creates bound local WebP, verifies source bytes, and hands real local references to the ordinary queue',async()=>{const f=await fixture(),{m,result,context}=f;assert.equal(result.response.characters[0].portrait.source,'image-crop');assert.equal(f.stats().renders,1);assert.ok(!('portrait_source'in result.response.characters[0]));const state=m.initialCharacterBlockingState(result.response),receipt=await context.reply(m.characterBlockingConfirmation(result.response,state),state);assert.equal(receipt.result.portrait_sources[0].node_ref,'node/photo');assert.match(receipt.result.portrait_sources[0].source_sha256,/^[a-f0-9]{64}$/);assert.doesNotMatch(receipt.text,/data:image\/webp/);assert.equal((await context.reply(m.characterBlockingConfirmation(result.response,state),state)).metadata.handoffId,receipt.metadata.handoffId);f.replaceBytes(Buffer.from('changed bytes'));await assert.rejects(context.guard(),/实际字节已变化/);});
test('no portrait uses official fallback without making up a photo, still binds scope and current trace',async()=>{const f=await fixture(false);assert.equal(f.stats().fetches,0);assert.equal(f.stats().renders,0);assert.ok(f.result.response.characters.every(c=>!c.portrait));await f.context.guard();f.setProject('another');await assert.rejects(f.context.guard(),/重载|来源/);assert.equal(f.context.isCurrent(),false);});
test('removed or replaced nodes, changed response, reload/disposal and unbound results cannot reuse a source contract',async()=>{for(const change of [f=>{f.graph.nodes=[];},f=>{f.graph.nodes[0].image=f.graph.nodes[0].fullImage='asset:other';},f=>{f.trace.result.response={...f.result.response};},f=>f.setCurrent(false),f=>f.context.dispose()]){const f=await fixture();change(f);await assert.rejects(f.context.guard());assert.equal(f.context.isCurrent(),false);}const f=await fixture();assert.throws(()=>f.runtime.bindPreparedResult(f.result,{...f.prepared}));});
test('caller portraits/URLs, remote existing node URLs and invalid crops fail before network or render',async()=>{const f=await fixture(false);for(const character of [{...input().characters[0],portrait:{data_uri:'https://app.tapnow.media/p.webp',source:'image-crop'}},{...input().characters[0],portrait_source:{node_ref:'node/photo',url:'https://app.tapnow.media/p.webp'}},{...input().characters[0],portrait_source:{node_ref:'node/photo',crop:{x:0,y:0,w:1001,h:1000}}}])await assert.rejects(f.runtime.prepareAppArgs({...f.args,data:{...input(),characters:[character]}}));f.graph.nodes[0].fullImage='https://app.tapnow.media/p.webp';await assert.rejects(f.runtime.prepareAppArgs({...f.args,data:{...input(),characters:[{...input().characters[0],portrait_source:{node_ref:'node/photo'}}]}}),/先导入本地/);assert.equal(f.stats().fetches,0);});
test('portrait schema per-item/aggregate budget is enforced without accepting URL media',async()=>{const m=await modelPromise,portrait={source:'image-crop',data_uri:'data:image/webp;base64,'+'AAAA'.repeat(4000)},characters=Array.from({length:11},(_,i)=>({...input().characters[0],id:'c'+i,portrait}));assert.throws(()=>m.prepareCharacterBlocking({...input(),characters}));assert.throws(()=>m.characterBlockingPortrait({source:'image-crop',data_uri:'data:image/webp;base64,'+'AAAA'.repeat(5000)}));});
test('source change after fetch and late response after cancellation both cancel actual response bodies',async()=>{
 const m=await modelPromise,{createCharacterBlockingRuntime}=await runtimePromise,graph={nodes:[{id:'photo',type:'image',fullImage:'asset:photo'}],edges:[]};const args={resource_uri:m.characterBlockingUri,data:{...input(),characters:[{...input().characters[0],portrait_source:{node_ref:'node/photo'}}]}};
 let current=true,cancelled=0;const makeResponse=()=>new Response(new ReadableStream({cancel(){cancelled++;}}),{headers:{'content-type':'image/webp'}});
 const runtime=createCharacterBlockingRuntime({app:{getState:()=>graph},localAssets:{url:async()=> 'blob:local'},getProjectId:()=> 'project',fetchImpl:async()=>{current=false;return makeResponse();},renderPortrait:()=>{throw Error('must not render');}});
 await assert.rejects(runtime.prepareAppArgs(args,{isCurrent:()=>current}),/切换/);assert.equal(cancelled,1);
 const ac=new AbortController();let fulfill,started;const begun=new Promise(resolve=>{started=resolve;});const late=createCharacterBlockingRuntime({app:{getState:()=>graph},localAssets:{url:async()=> 'blob:local'},getProjectId:()=> 'project',fetchImpl:()=>{started();return new Promise(resolve=>{fulfill=resolve;});},renderPortrait:()=>{throw Error('must not render');}});
 const pending=late.prepareAppArgs(args,{signal:ac.signal});await begun;ac.abort();await assert.rejects(pending);fulfill(makeResponse());await new Promise(resolve=>setImmediate(resolve));assert.equal(cancelled,2);
});
test('bounded local stream rejects excess declared or actual bytes and cancels instead of buffering to completion',async()=>{
 const m=await modelPromise,{createCharacterBlockingRuntime}=await runtimePromise,graph={nodes:[{id:'photo',type:'image',fullImage:'asset:photo'}],edges:[]};const args={resource_uri:m.characterBlockingUri,data:{...input(),characters:[{...input().characters[0],portrait_source:{node_ref:'node/photo'}}]}};
 for(const declared of [true,false]){let cancelled=false;const runtime=createCharacterBlockingRuntime({app:{getState:()=>graph},localAssets:{url:async()=> 'blob:local'},getProjectId:()=> 'project',fetchImpl:async()=>new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(m.characterBlockingLimits.sourceBytes+1));},cancel(){cancelled=true;}}),{headers:{'content-type':'image/webp',...(declared?{'content-length':String(m.characterBlockingLimits.sourceBytes+1)}:{})}}),renderPortrait:()=>{throw Error('must not render');}});await assert.rejects(runtime.prepareAppArgs(args),/限制|容量/);assert.equal(cancelled,true);}
});
test('browser decoder cancellation releases its local object URL and stops the image load',async()=>{
 const {renderCharacterBlockingPortrait}=await runtimePromise,originalImage=global.Image,originalCreate=URL.createObjectURL,originalRevoke=URL.revokeObjectURL;let image,released=false,started;
 try{const begun=new Promise(resolve=>{started=resolve;});global.Image=class{constructor(){image=this;}set src(value){this.value=value;if(value)started();}};URL.createObjectURL=()=> 'blob:decoder-test';URL.revokeObjectURL=value=>{assert.equal(value,'blob:decoder-test');released=true;};const ac=new AbortController(),pending=renderCharacterBlockingPortrait(new Blob([webp()],{type:'image/webp'}),{signal:ac.signal});await begun;ac.abort();await assert.rejects(pending);assert.equal(image.value,'');assert.equal(image.onload,null);assert.equal(image.onerror,null);assert.equal(released,true);}
 finally{global.Image=originalImage;URL.createObjectURL=originalCreate;URL.revokeObjectURL=originalRevoke;}
});
