const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric'));
const canvasPath=fabricRequire.resolve('canvas'),previousCanvas=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(previousCanvas)require.cache[canvasPath]=previousCanvas;else delete require.cache[canvasPath];
function fixture(){
 const dom=new JSDOM('<body><div id="canvas"></div><div id="node-toolbar"></div><input id="outside"></body>'),window=dom.window,document=window.document;
 const core=require('../audio-core.js'),nodes=[{id:'a',type:'audio',title:'A',x:10,y:10,width:300,height:300,audioConfig:core.transition({prompt:'hello'},'seed-audio-1-0')},{id:'b',type:'audio',title:'B',x:10,y:10,width:300,height:300,audioConfig:core.transition({prompt:'other'},'seed-audio-1-0')},{id:'ref',type:'text',title:'参考文本',content:'text'}],state={nodes,selected:['a'],edges:[],view:{x:0,y:0,scale:1}},writes=[];
 document.querySelector('#canvas').getBoundingClientRect=()=>({left:0,top:0,right:1000,width:1000});
 Object.assign(window,{AudioCore:core,UI_ICONS:{},CanvasApp:{getState:()=>state,getNodeElement:()=>null,updateNode(id,patch){writes.push({id,patch});Object.assign(nodes.find(n=>n.id===id),patch);document.dispatchEvent(new window.Event('canvas:render'));},disconnect(){},saveSelection(){}},NodeActions:{notify(){},colors(){}},GenerationAPI:{getJobs:()=>[],subscribe(){}},VoiceInput:{bind(){}},LocalAssets:{}});
 const source=fs.readFileSync(require.resolve('../audio-ui.js'),'utf8').replace(/import\([^)]*\)/g,'(new Promise(()=>{}))').replace('let voiceUI=null','let voiceUI=voiceMenuModule');
 vm.runInNewContext(source,{voiceMenuModule,window,document,AbortController,DOMException,Event:window.Event,structuredClone,console,innerWidth:1000,innerHeight:800,ResizeObserver:class{observe(){}disconnect(){}},setTimeout,clearTimeout,requestAnimationFrame(){},cancelAnimationFrame(){}});
 const trigger=label=>document.querySelector('.audio-editor').querySelector('[aria-label="'+label+'"]'),pop=()=>document.querySelector('.audio-popover'),key=(target,key,extra={})=>{const e=new window.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...extra});target.dispatchEvent(e);return e;},render=()=>document.dispatchEvent(new window.Event('canvas:render'));
 return{dom,window,document,state,nodes,writes,trigger,pop,key,render,useVoice(){for(const n of nodes.filter(n=>n.type==='audio'))n.audioConfig=core.transition(n.audioConfig,'elevenlabs-v3','Text-to-Speech');render();},open(label){const b=trigger(label);b.focus();b.click();return pop();},close(){window.dispatchEvent(new window.Event('pagehide'));dom.window.close();}};
}
let voiceMenuModule;test.before(async()=>{voiceMenuModule=await import('../src/features/audio-voices/menu.mjs');});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const tick=()=>new Promise(resolve=>setTimeout(resolve,5));
test('model and scene menus expose radio navigation and Escape returns to rebuilt trigger',()=>{
 const f=fixture();try{let p=f.open('选择音频模型');assert.equal(p.getAttribute('role'),'menu');assert.equal(f.document.activeElement.getAttribute('aria-checked'),'true');f.key(f.document.activeElement,'End');assert.equal(f.document.activeElement,p.lastElementChild);f.key(f.document.activeElement,'Home');assert.equal(f.document.activeElement,p.firstElementChild);f.key(f.document.activeElement,'ArrowDown');f.key(f.document.activeElement,'Enter'); // Native button activation is separately exercised by click.
 p.querySelector('[aria-label="ElevenLabs V3"]').click();assert.equal(f.pop(),null);assert.equal(f.document.activeElement,f.trigger('选择音频模型'));p=f.open('选择音频场景');assert.equal(p.querySelectorAll('[role="menuitemradio"]').length,3);const escaped=f.key(f.document.activeElement,'Escape');assert.equal(escaped.defaultPrevented,true);assert.equal(f.pop(),null);assert.equal(f.document.activeElement,f.trigger('选择音频场景'));assert.equal(f.trigger('选择音频场景').getAttribute('aria-expanded'),'false');}finally{f.close();}
});
test('Tab stays native, inner or IME Escape wins, and external focus closes without stealing focus',()=>{
 const f=fixture();try{const p=f.open('音频参数'),field=p.querySelector('button');const tab=f.key(field,'Tab');assert.equal(tab.defaultPrevented,false);f.key(field,'Escape',{isComposing:true});assert.equal(f.pop(),p);field.addEventListener('keydown',e=>{if(e.key==='Escape')e.stopPropagation();},{once:true});f.key(field,'Escape');assert.equal(f.pop(),p);const outside=f.document.querySelector('#outside');outside.focus();assert.equal(f.pop(),null);assert.equal(f.document.activeElement,outside);f.open('选择参考素材');f.trigger('音频生成提示词').focus();assert.equal(f.pop(),null);}finally{f.close();}
});
test('outside pointer, editor pointer, window blur and pagehide dismiss; trigger toggles',()=>{
 const f=fixture();try{for(const kind of ['outside','editor','blur','pagehide']){f.open('选择音频模型');if(kind==='blur'||kind==='pagehide')f.window.dispatchEvent(new f.window.Event(kind));else(kind==='editor'?f.trigger('音频生成提示词'):f.document.querySelector('#outside')).dispatchEvent(new f.window.Event('pointerdown',{bubbles:true}));assert.equal(f.pop(),null,kind);}f.open('选择音频模型');f.trigger('选择音频模型').click();assert.equal(f.pop(),null);assert.equal(f.document.activeElement,f.trigger('选择音频模型'));}finally{f.close();}
});
test('parameter refresh preserves chosen option focus and rebuilt trigger attributes',()=>{
 const f=fixture();try{const p=f.open('音频参数'),option=p.querySelector('[data-focus-key="输出格式:mp3"]');option.focus();option.click();assert.notEqual(f.pop(),p);assert.equal(f.document.activeElement.dataset.focusKey,'输出格式:mp3');assert.equal(f.document.activeElement.getAttribute('aria-pressed'),'true');assert.equal(f.trigger('音频参数').getAttribute('aria-expanded'),'true');f.key(f.document.activeElement,'Escape');assert.equal(f.document.activeElement,f.trigger('音频参数'));}finally{f.close();}
});
test('old focusout timers cannot close a reopened menu; hidden or changed nodes dismiss',async()=>{
 const f=fixture();try{const p=f.open('音频参数');p.querySelector('button').dispatchEvent(new f.window.FocusEvent('focusout',{bubbles:true}));f.trigger('选择音频模型').click();const reopened=f.pop();await tick();assert.equal(f.pop(),reopened);f.state.selected=['b'];f.render();assert.equal(f.pop(),null);f.useVoice();f.open('选择音色');f.nodes[1].audioMode='upload';f.render();assert.equal(f.pop(),null);assert.equal(f.document.querySelector('.audio-editor').hidden,true);}finally{f.close();}
});
test('voice provider completions cannot populate closed, reopened, switched or provider-replaced menus',async()=>{
 for(const kind of ['closed','reopened','node','provider','hidden']){const f=fixture(),old=deferred(),next=deferred();try{f.useVoice();f.window.AudioAPI.setVoiceProvider({listVoices:()=>old.promise});f.open('选择音色');await Promise.resolve();const staleRow=f.pop();if(kind==='closed')f.key(f.document.activeElement,'Escape');if(kind==='reopened'){f.key(f.document.activeElement,'Escape');f.open('选择音色');}if(kind==='node'){f.state.selected=['b'];f.render();}if(kind==='hidden'){f.nodes[0].audioMode='upload';f.render();}if(kind==='provider'){f.window.AudioAPI.setVoiceProvider({listVoices:()=>next.promise});f.open('选择音色');}old.resolve([{id:'old',name:'旧音色'}]);await tick();if(kind==='reopened')assert.match(f.pop().textContent,/旧音色/);else assert.doesNotMatch(f.document.body.textContent,/旧音色/,kind);assert.equal(staleRow.isConnected,false);if(kind==='provider'){next.resolve([{id:'new',name:'新音色'}]);await tick();assert.match(f.pop().textContent,/新音色/);assert.doesNotMatch(f.pop().textContent,/旧音色/);}}finally{f.close();}}
});
test('a prior menu request cannot replace a newer voice list or report late errors',async()=>{
 const f=fixture(),old=deferred(),next=deferred();let count=0;try{f.useVoice();f.window.AudioAPI.setVoiceProvider({listVoices:()=>++count===1?old.promise:next.promise});f.open('选择音色');await Promise.resolve();f.key(f.document.activeElement,'Escape');f.open('选择音色');await Promise.resolve();next.resolve([{id:'new',name:'新音色'}]);await tick();old.resolve([{id:'old',name:'旧音色'}]);await tick();assert.match(f.pop().textContent,/新音色/);assert.doesNotMatch(f.pop().textContent,/旧音色/);const row=f.pop().querySelector('[aria-label="新音色"]');f.key(f.document.activeElement,'Escape');row.click();assert.equal(f.writes.length,0);const rejected=deferred();f.window.AudioAPI.setVoiceProvider({listVoices:()=>rejected.promise});f.open('选择音色');await Promise.resolve();f.key(f.document.activeElement,'Escape');rejected.reject(Error('stale failure'));await tick();assert.doesNotMatch(f.document.body.textContent,/stale failure/);}finally{f.close();}
});
test('public listVoices also rejects provider replacement and setVoices supersession',async()=>{
 const f=fixture(),old=deferred();try{f.useVoice();f.window.AudioAPI.setVoiceProvider({listVoices:()=>old.promise});const pending=f.window.AudioAPI.listVoices();f.window.AudioAPI.setVoiceProvider(null);f.window.AudioAPI.setVoices([{id:'local',name:'本地音色'}]);old.resolve([{id:'old',name:'旧音色'}]);const result=await pending;assert.deepEqual(JSON.parse(JSON.stringify(result.voices)),[{id:'local',name:'本地音色'}]);}finally{f.close();}
});
test('voice refresh retains a focused cached row or returns to search when it disappears',async()=>{
 for(const retain of [true,false]){const f=fixture(),next=deferred();let calls=0;try{f.useVoice();f.window.AudioAPI.setVoiceProvider({listVoices:()=>++calls===1?Promise.resolve([{id:'cached',name:'缓存音色'}]):next.promise});await f.window.AudioAPI.listVoices();f.open('选择音色');await Promise.resolve();f.pop().querySelector('[aria-label="缓存音色"]').focus();next.resolve([{id:retain?'cached':'new',name:'刷新音色'}]);await tick();assert.ok(f.pop());assert.equal(f.document.activeElement.getAttribute('aria-label'),retain?'刷新音色':'搜索音色');}finally{f.close();}}
});
test('choosing a catalog ID persists it and carries it unchanged into node generation request',async()=>{
 const f=fixture();try{f.useVoice();f.window.AudioAPI.setVoiceProvider({listVoices:async()=>[{id:'provider-stable-123',name:'目录音色'}]});f.open('选择音色');await tick();f.pop().querySelector('[aria-label="目录音色"]').click();assert.equal(f.nodes[0].audioConfig.params.voice_id,'provider-stable-123');const request=await f.window.AudioAPI.buildRequest('a');assert.equal(request.parameters.voice_id,'provider-stable-123');assert.equal(request.parameters.model,'eleven_v3');}finally{f.close();}
});
