const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric')),domRequire=createRequire(fabricRequire.resolve('jsdom'));
const canvasPath=domRequire.resolve('canvas'),previousCanvas=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(previousCanvas)require.cache[canvasPath]=previousCanvas;else delete require.cache[canvasPath];
function fixture(){
 const dom=new JSDOM('<body><div id="node-toolbar"></div><section id="panel"></section></body>'),document=dom.window.document,calls=[],nodes=[{id:'a',type:'audio',audio:'/a.wav',audioMode:'upload',title:'A',x:0,y:0},{id:'b',type:'audio',audio:'/b.wav',audioMode:'upload',title:'B'}],state={nodes,selected:['a'],view:{x:0,y:0,scale:1}},shells=new Map();
 for(const node of nodes){const shell=document.createElement('div');shell.innerHTML='<div class="node-body"></div>';document.body.append(shell);shells.set(node.id,shell);}
 const context={app:{getState:()=>state,getNodeElement:id=>shells.get(id),saveSelection:()=>calls.push(['save',state.selected[0]])},window:{NodeActions:{colors:(n,b)=>calls.push(['pin',n,b])}},current:null,lastStored:null,advanced:false,config:null,players:new Map(),drafts:new Map(),saveTimers:new Map(),core:{transition:value=>value},panel:document.querySelector('#panel'),$:(s)=>document.querySelector(s),el:(tag,cls)=>{const node=document.createElement(tag);node.className=cls||'';return node;},icon:()=>'',button(label,icon,fn){const b=document.createElement('button');b.setAttribute('aria-label',label);b.onclick=fn;return b;},makePlayer(){const wrap=document.createElement('div');return {wrap,dispose(){wrap.remove();}};},upload(){},closePop(){},position(){},positionToolbar(){},clearTimeout,download:n=>calls.push(['download',n]),preview:n=>calls.push(['preview',n])};
 vm.createContext(context);const source=fs.readFileSync(require.resolve('../audio-ui.js'),'utf8'),start=source.indexOf(' const audioBodies='),end=source.indexOf(' window.GenerationAPI.subscribe',start);vm.runInContext('let resourceDisplay;'+source.slice(source.indexOf(' const pendingOriginalAudio='),source.indexOf('\n',source.indexOf(' const pendingOriginalAudio=')))+source.slice(start,end),context);context.render();
 return{dom,document,state,calls,context,render:detail=>context.render({detail}),bar:()=>document.querySelector('#node-toolbar'),buttons:()=>[...document.querySelector('#node-toolbar').children],close(){dom.window.close();}};
}
test('ordinary full renders and viewport frames preserve audio buttons, focus and child identities',()=>{
 const f=fixture();try{const buttons=f.buttons();buttons[1].focus();const observer=new f.dom.window.MutationObserver(()=>{});observer.observe(f.bar(),{childList:true,subtree:true});for(let i=0;i<90;i++){f.state.nodes[0].x+=.125;f.render();f.render({viewportOnly:true});}assert.deepEqual(f.buttons(),buttons);assert.equal(f.document.activeElement,buttons[1]);assert.equal(observer.takeRecords().length,0);observer.disconnect();assert.equal(f.buttons().length,4);}finally{f.close();}
});
test('same-id node/source replacement keeps buttons but actions resolve current media and metadata',()=>{
 const f=fixture();try{const buttons=f.buttons(),replacement={...f.state.nodes[0],audio:'/changed.wav',title:'Changed'};f.state.nodes[0]=replacement;f.render();assert.deepEqual(f.buttons(),buttons);buttons[0].click();buttons[1].click();buttons[2].click();buttons[3].click();assert.equal(f.calls[0][1],replacement);assert.equal(f.calls[1][1],replacement);assert.deepEqual(f.calls[2],['save','a']);assert.equal(f.calls[3][1],replacement);const latest={...replacement,audio:'/latest.wav'};f.state.nodes[0]=latest;buttons[1].click();assert.equal(f.calls.at(-1)[1],latest,'event-time lookup also protects a callback before the next render');}finally{f.close();}
});
test('node/selection/type changes and detached callbacks cannot execute stale toolbar actions',()=>{
 const f=fixture();try{const original=f.buttons(),callback=original[1].onclick;f.state.selected=['b'];f.render();assert.notEqual(f.buttons()[1],original[1]);callback();assert.equal(f.calls.length,0);f.buttons()[1].click();assert.equal(f.calls[0][1],f.state.nodes[1]);f.state.selected=[];f.buttons()[0].click();assert.equal(f.calls.length,1);f.state.selected=['b'];f.state.nodes[1].type='image';f.buttons()[0].click();assert.equal(f.calls.length,1);f.state.nodes.pop();f.buttons()[1].click();assert.equal(f.calls.length,1);}finally{f.close();}
});
test('media availability, foreign toolbar contents and replaced toolbar nodes invalidate cached structure',()=>{
 const f=fixture();try{const original=f.buttons();f.state.nodes[0].audio=null;f.render();assert.equal(f.buttons().length,1);original[1].onclick();assert.equal(f.calls.length,0);f.state.nodes[0].audio='/restored.wav';f.render();assert.equal(f.buttons().length,4);const before=f.buttons();f.bar().replaceChildren(f.document.createElement('button'));f.render();assert.notEqual(f.buttons()[0],before[0]);assert.equal(f.buttons().length,4);const old=f.bar(),stale=f.buttons()[1].onclick,replacement=old.cloneNode(false);old.replaceWith(replacement);stale();assert.equal(f.calls.length,0);f.render();assert.equal(f.buttons().length,4);assert.equal(f.buttons()[0].parentNode,replacement);f.buttons()[3].click();assert.equal(f.calls[0][1],f.state.nodes[0]);}finally{f.close();}
});
