const test=require('node:test'),assert=require('node:assert/strict');
const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric')),canvasPath=fabricRequire.resolve('canvas'),previousCanvas=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(previousCanvas)require.cache[canvasPath]=previousCanvas;else delete require.cache[canvasPath];
let createVoiceProvider,createVoiceChoices;test.before(async()=>{({createVoiceProvider}=await import('../src/features/audio-voices/client.mjs'));({createVoiceChoices}=await import('../src/features/audio-voices/menu.mjs'));});
const tick=()=>new Promise(r=>setTimeout(r,5)),deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('same-origin real catalog keeps stable IDs, server pagination, and never forwards upstream preview URLs',async()=>{
 let call;const provider=createVoiceProvider({fetcher:async(url,options)=>{call={url,options};return Response.json({configured:true,provider:'elevenlabs',voices:[{id:'stable/id',name:'真实名称',previewUrl:'https://upstream.invalid/sample'}],hasMore:true,nextCursor:'cursor1'});}}),signal=new AbortController().signal;
 const result=await provider.listVoices({signal,search:'中文'});assert.match(call.url,/^\/api\/generation\/voices\?/);assert.equal(call.options.signal,signal);assert.equal(call.options.redirect,'error');assert.equal(new URL(call.url,'http://localhost').searchParams.get('search'),'中文');assert.equal(result.voices[0].id,'stable/id');assert.equal(result.voices[0].previewRef,'stable/id');assert.equal(result.voices[0].previewUrl,undefined);assert.equal(result.nextCursor,'cursor1');
});
test('unconfigured, malformed catalog, and cancellation retain explicit failure semantics',async()=>{
 const provider=createVoiceProvider({fetcher:async()=>Response.json({error:'尚未配置',code:'voice_catalog_configuration_required'},{status:503})});await assert.rejects(provider.listVoices(),e=>e.code==='voice_catalog_configuration_required');
 const invalid=createVoiceProvider({fetcher:async()=>Response.json({configured:true,voices:[{id:'x',name:'a'},{id:'x',name:'b'}]})});await assert.rejects(invalid.listVoices(),e=>e.code==='voice_catalog_invalid');
 const pending=deferred(),controller=new AbortController(),cancelled=createVoiceProvider({fetcher:()=>pending.promise});const work=cancelled.listVoices({signal:controller.signal});controller.abort();pending.resolve(Response.json({configured:true,voices:[]}));await assert.rejects(work,{name:'AbortError'});
});
test('preview requests stable ID through fixed local endpoint and rejects non-audio or empty bodies',async()=>{
 let url;const provider=createVoiceProvider({fetcher:async value=>{url=value;return new Response(new Blob(['real audio bytes'],{type:'audio/wav'}));}});const blob=await provider.previewVoice({id:'x/y',previewUrl:'https://bad.invalid'});assert.equal(url,'/api/generation/voices/x%2Fy/preview?model=eleven_v3');assert.equal(blob.type,'audio/wav');assert.equal(await blob.text(),'real audio bytes');
 for(const response of [new Response('html',{headers:{'content-type':'text/html'}}),new Response('',{headers:{'content-type':'audio/wav'}})])await assert.rejects(createVoiceProvider({fetcher:async()=>response}).previewVoice({id:'x'}),e=>e.code==='voice_preview_invalid');
});
function fixture(options={}){const dom=new JSDOM('<body><section></section><section></section></body>'),roots=dom.window.document.querySelectorAll('section'),played=[],revoked=[];class Audio{pause(){this.paused=true;}removeAttribute(){}load(){}async play(){played.push(this);}}
 const urls={createObjectURL:()=> 'blob:test/'+(played.length+1),revokeObjectURL:url=>revoked.push(url)},mount=(root,settings)=>createVoiceChoices(root,{AudioClass:Audio,URLApi:urls,listVoices:async()=>({configured:true,voices:[{id:'v1',name:'音色一',previewRef:'v1'},{id:'v2',name:'音色二',previewRef:'v2'}]}),previewVoice:async()=>new Blob(['audio'],{type:'audio/wav'}),onSelect:()=>{},...options,...settings});return {dom,roots,played,revoked,mount};}
test('menu displays failure/retry, searches, and selects a stable ID',async()=>{
 let calls=0,chosen;const f=fixture(),ui=f.mount(f.roots[0],{listVoices:async()=>{if(++calls===1)throw Object.assign(Error('未配置音色服务'),{code:'voice_catalog_configuration_required'});return {configured:true,voices:[{id:'stable',name:'真实音色'}]};},onSelect:id=>chosen=id});try{await tick();assert.equal(f.roots[0].querySelector('p').dataset.state,'unconfigured');f.roots[0].querySelector('.voice-catalog-retry').click();await tick();f.roots[0].querySelector('[aria-label="真实音色"]').click();assert.equal(chosen,'stable');const input=f.roots[0].querySelector('input');input.value='不存在';input.dispatchEvent(new f.dom.window.Event('input'));assert.equal(f.roots[0].querySelectorAll('.voice-catalog-select').length,0);}finally{ui.dispose();f.dom.window.close();}
});
test('closed menu aborts directory and rejects late entries',async()=>{
 const f=fixture(),pending=deferred();let signal;const ui=f.mount(f.roots[0],{listVoices:options=>{signal=options.signal;return pending.promise;}});ui.dispose();assert.equal(signal.aborted,true);pending.resolve({configured:true,voices:[{id:'late',name:'迟到音色'}]});await tick();assert.doesNotMatch(f.roots[0].textContent,/迟到音色/);f.dom.window.close();
});
test('previews are mutually exclusive, close cancels late bytes, and every object URL is revoked',async()=>{
 const f=fixture(),pending=deferred();let signal;const first=f.mount(f.roots[0],{previewVoice:(voice,options)=>{signal=options.signal;return pending.promise;}}),second=f.mount(f.roots[1]);try{await tick();f.roots[0].querySelector('[aria-label="试听 音色一"]').click();f.roots[1].querySelector('[aria-label="试听 音色二"]').click();await tick();assert.equal(signal.aborted,true);pending.resolve(new Blob(['late'],{type:'audio/wav'}));await tick();assert.equal(f.played.length,1);second.dispose();assert.equal(f.played[0].paused,true);assert.equal(f.revoked.length,1);}finally{first.dispose();second.dispose();f.dom.window.close();}
});
test('pagination preserves prior stable IDs and loads the returned next cursor',async()=>{
 const f=fixture(),calls=[],ui=f.mount(f.roots[0],{listVoices:async options=>{calls.push(options.cursor);return options.cursor?{configured:true,voices:[{id:'second',name:'第二页'}],hasMore:false}:{configured:true,voices:[{id:'first',name:'第一页'}],hasMore:true,nextCursor:'actual-next'};}});try{await tick();assert.equal(f.roots[0].querySelector('.voice-catalog-more').hidden,false);f.roots[0].querySelector('.voice-catalog-more').click();await tick();assert.deepEqual(calls,[undefined,'actual-next']);assert.equal(f.roots[0].querySelectorAll('.voice-catalog-select').length,2);assert.equal(f.roots[0].querySelector('.voice-catalog-more').hidden,true);}finally{ui.dispose();f.dom.window.close();}
});
test('Agent confirmed stable voice ID is retained through the actual audio request converter',async()=>{
 const core=require('../audio-core.js'),{audioRequestConfig}=await import('../src/features/agent-generation/audio.mjs'),source=core.transition({prompt:'实际文本'},'elevenlabs-v3','Text-to-Speech'),config=audioRequestConfig(core,source,{kind:'audio.generate',model:'elevenlabs',audioScene:'Text-to-Speech',voice:'provider-stable-123',prompt:'待生成文本'});assert.equal(config.params.voice_id,'provider-stable-123');assert.equal(config.model,'eleven_v3');assert.equal(config.prompt,'待生成文本');
});
test('typing search cancels the previous directory and rejects its late response before fetching the new query',async()=>{
 const f=fixture(),pending=deferred(),calls=[],ui=f.mount(f.roots[0],{listVoices:options=>{calls.push(options);return calls.length===1?pending.promise:Promise.resolve({configured:true,voices:[{id:'new',name:'新搜索音色'}]});}});try{const input=f.roots[0].querySelector('input');input.value='新搜索';input.dispatchEvent(new f.dom.window.Event('input'));assert.equal(calls[0].signal.aborted,true);pending.resolve({configured:true,voices:[{id:'old',name:'新搜索旧响应'}]});await tick();assert.doesNotMatch(f.roots[0].textContent,/旧响应/);await new Promise(r=>setTimeout(r,260));assert.equal(calls[1].search,'新搜索');assert.match(f.roots[0].textContent,/新搜索音色/);}finally{ui.dispose();f.dom.window.close();}
});
