const test=require('node:test'),assert=require('node:assert/strict'),{capture,instantiate}=require('../canvas-clipboard.js');
const nodes=[{id:'g',type:'group',x:50000.25,y:-2000.5,width:800,height:400},{id:'a',type:'image',parentId:'g',x:50100.25,y:-1900.5,width:200,height:200,generation:{referenceIds:['b'],referenceBindings:[{nodeId:'b'}]}},{id:'b',type:'image',parentId:'g',x:50400.25,y:-1900.5,width:200,height:200},{id:'ext',type:'text',x:40000,y:-1000,width:300,height:300}],edges=[{id:'in',source:'ext',target:'a'},{id:'ab',source:'a',target:'b'},{id:'out',source:'a',target:'ext'}];
const ids=()=>{let i=0;return()=>`new-${++i}`;};
test('group clipboard uses absolute coordinates once and retains only incoming reference edges',()=>{const snapshot=capture(nodes,edges,['g']);assert.equal(snapshot.nodes.length,3);const graph=instantiate(snapshot,nodes,{x:100.25,y:200.5},0,.25,ids());assert.equal(graph.nodes[1].x,200.25);assert.equal(graph.nodes[1].y,300.5);assert.equal(graph.nodes[1].parentId,graph.nodes[0].id);assert.deepEqual(graph.nodes[1].generation.referenceIds,[graph.nodes[2].id]);assert.deepEqual(graph.nodes[1].generation.referenceBindings,[{nodeId:graph.nodes[2].id}]);assert.equal(graph.edges.length,2);assert.equal(graph.edges[0].source,'ext');assert.deepEqual(graph.selected,[graph.nodes[0].id]);assert.equal(nodes[1].x,50100.25);});
test('paste offsets repeat by 40 screen pixels at fractional zoom',()=>{const snap=capture(nodes,edges,['a']);const graph=instantiate(snap,nodes,{x:10,y:20},2,.25,ids());assert.equal(graph.nodes[0].x,330);assert.equal(graph.nodes[0].y,340);assert.equal(graph.nodes[0].parentId,undefined);});
test('deleted external sources do not produce dangling edges',()=>{const snap=capture(nodes,edges,['a']);assert.equal(instantiate(snap,[],{x:0,y:0},0,1,ids()).edges.length,0);});
test('pile copies own members and selects only its root',()=>{const pile=[{id:'p',type:'pile',x:100,y:200,width:200,height:200,memberIds:['a','b']},...nodes.slice(1,3).map(n=>({...n,parentId:undefined}))];const graph=instantiate(capture(pile,[],['p']),pile,{x:0,y:0},0,1,ids());assert.equal(graph.nodes.length,3);assert.deepEqual(graph.nodes[0].memberIds,graph.nodes.slice(1).map(n=>n.id));assert.deepEqual(graph.selected,[graph.nodes[0].id]);});
test('studio and empty selection reject rather than silently losing scene state',()=>{assert.throws(()=>capture([{id:'s',type:'studio'}],[],['s']),/3D/);assert.throws(()=>capture(nodes,edges,[]),/选择/);});

test('copied reference order remaps internal sources and keeps outside references',()=>{const snap=capture(nodes,edges,['g']);snap.nodes.find(n=>n.id==='a').generation={referenceOrder:['node:b','node:ext','saved:0'],promptReferenceBindings:[{renderText:'Image 1',referenceKey:'node:b'},{renderText:'Image 2',referenceKey:'node:ext'}]};const result=instantiate(snap,nodes,{x:0,y:0},0,1,ids());const a=result.nodes.find(n=>n.generation?.referenceOrder),b=result.nodes.find(n=>n.type==='image'&&n!==a);assert.deepEqual(a.generation.referenceOrder,['node:'+b.id,'node:ext','saved:0']);assert.deepEqual(a.generation.promptReferenceBindings.map(ref=>ref.referenceKey),['node:'+b.id,'node:ext']);});
test('copy of reversed deep groups traverses linearly and preserves original node order',()=>{
  let reads=0;const deep=Array.from({length:2000},(_,i)=>({id:'g'+i,type:'group',get parentId(){reads++;return i?'g'+(i-1):undefined;},x:50000.125+i,y:-2000.375,width:300,height:200})).reverse();
  const graph=capture(deep,[],['g0']);assert.equal(graph.nodes.length,2000);assert.equal(graph.nodes[0].id,'g1999');assert.equal(graph.nodes.at(-1).id,'g0');
  assert(reads<=deep.length*5,'parent indexing, structured clone, and root detachment must stay linear');assert.equal(graph.nodes[0].x,51999.125);
  const cycle=capture([{id:'p',type:'pile',memberIds:['q']},{id:'q',type:'pile',memberIds:['p']}],[],['p']);assert.equal(cycle.nodes.length,2);
});
