const test=require('node:test'),assert=require('node:assert/strict'),G=require('../canvas-groups.js'),dagre=require('../assets/dagre-local.js');
const fixture=()=>[{id:'a',type:'image',x:53284.3,y:-2180.48,width:435,height:250},{id:'b',type:'text',x:53800.25,y:-1800.8,width:300,height:150},{id:'c',type:'video',x:54500,y:-2000,width:435,height:250}];
test('group and ungroup preserve fractional absolute world coordinates',()=>{const nodes=fixture(),before=structuredClone(nodes),g=G.group(nodes,['a','b'],'g');assert.deepEqual(g,{id:'g',type:'group',title:'新建组',layoutType:'horizontal',createdBy:'client',...G.bounds(before.slice(0,2))});assert.equal(nodes[1].x,before[0].x);assert.equal(nodes[2].y,before[1].y);assert.deepEqual(G.ungroup(nodes,'g'),['a','b']);assert.deepEqual(nodes,before);});
test('moving group and selected child together translates each descendant once',()=>{const nodes=fixture();G.group(nodes,['a','b'],'g');const snapshot=G.positions(nodes,['g','a']);G.translate(nodes,snapshot,43.375,-19.5);assert.equal(nodes.find(n=>n.id==='a').x,53284.3+43.375);const spacing=nodes.find(n=>n.id==='b').x-nodes.find(n=>n.id==='a').x;G.translate(nodes,snapshot,17,29,true);assert.ok(Math.abs(nodes.find(n=>n.id==='b').x-nodes.find(n=>n.id==='a').x-spacing)<1e-8);});
test('auto grouping uses complete containment and unparents only after complete separation',()=>{const nodes=fixture();const g=G.group(nodes,['a','b'],'g'),a=nodes.find(n=>n.id==='a');a.x=g.x-100;G.autoGroup(nodes,['a']);assert.equal(a.parentId,'g');a.x=g.x-a.width-1;G.autoGroup(nodes,['a']);assert.equal(a.parentId,undefined);a.x=g.x+20;a.y=g.y+20;nodes.unshift({id:'small',type:'group',x:a.x-10,y:a.y-10,width:a.width+20,height:a.height+20});G.autoGroup(nodes,['a']);assert.equal(a.parentId,'small');});
test('selecting grouped and ungrouped nodes expands the existing group without displacement',()=>{const nodes=fixture();G.group(nodes,['a','b'],'g');const before=nodes.map(n=>[n.id,n.x,n.y]);const g=G.group(nodes,['a','c'],'unused');assert.equal(g.id,'g');assert.equal(nodes.length,4);for(const n of nodes.filter(n=>n.type!=='group'))assert.deepEqual([n.id,n.x,n.y],before.find(r=>r[0]===n.id));assert.equal(nodes.find(n=>n.id==='c').parentId,'g');});
test('source grid dimensions and layout spacing match three 435 by 250 nodes',()=>{const nodes=fixture().map(n=>({...n,width:435,height:250})),g=G.group(nodes,['a','b','c'],'g');G.layout(nodes,[],['g'],'grid',dagre);assert.equal(g.width,1270);assert.equal(g.height,900);assert.deepEqual(nodes.filter(n=>n.type!=='group').map(n=>[n.x-g.x,n.y-g.y]),[[100,100],[735,100],[100,550]]);});
test('Dagre horizontal layout respects dependencies, branches and cycles without coordinate drift',()=>{const nodes=fixture(),g=G.group(nodes,['a','b','c'],'g'),edges=[{source:'a',target:'b'},{source:'a',target:'c'}];G.layout(nodes,edges,['g'],'horizontal',dagre);const [a,b,c]=['a','b','c'].map(id=>nodes.find(n=>n.id===id));assert.equal(a.x,g.x+100);assert.equal(b.x+b.width/2,c.x+c.width/2);assert.ok(b.x>=a.x+a.width+200);assert.ok(Math.abs(b.y-c.y)>=150+200);G.layout(nodes,[...edges,{source:'c',target:'a'}],['g'],'horizontal',dagre);assert.ok(nodes.every(n=>[n.x,n.y,n.width,n.height].every(Number.isFinite)));});
test('group resize keeps opposite edges and enforces the original ten-unit minimum',()=>{const b={x:100,y:200,width:400,height:300},r=G.resizeBounds(b,'nw',500,500);assert.deepEqual(r,{x:490,y:490,width:10,height:10});assert.deepEqual(G.resizeBounds(b,'se',50,75),{x:100,y:200,width:450,height:375});});
