const {test}=require('node:test');
const assert=require('node:assert/strict');
const core=require('../canvas-piles.js');
const legacy=(nodes,point,excluded=[],sources=[])=>nodes.find(n=>n.type==='pile'&&!excluded.includes(n.id)&&point.x>=n.x&&point.x<=n.x+n.width&&point.y>=n.y&&point.y<=n.y+n.height&&(!sources.length||core.plan(nodes,[n.id,...sources])));
function fixture(count=12){const nodes=[{id:'source',type:'image'}];for(let p=0;p<count;p++){const memberIds=[];for(let i=0;i<(p===count-1?49:50);i++){const id=`m${p}-${i}`;nodes.push({id,type:i%2?'text':'image'});memberIds.push(id);}nodes.push({id:`pile${p}`,type:'pile',x:.125,y:-.375,width:100,height:80,memberIds});}return nodes;}

test('overlapping full piles skip to the first eligible target without changing source order',()=>{const nodes=fixture();assert.equal(core.dropTarget(nodes,{x:50,y:30},[],['source']).id,'pile11');assert.equal(core.dropTarget(nodes,{x:50,y:30},[],['source']),legacy(nodes,{x:50,y:30},[],['source']));});
test('hit testing retains boundaries, exclusions, missing/group/member source and gallery behavior',()=>{const nodes=fixture(3);nodes.push({id:'group',type:'group'});for(const point of [{x:.125,y:-.375},{x:100.125,y:79.625},{x:100.126,y:40},{x:NaN,y:0}])for(const excluded of [[],['pile0'],['pile2']])for(const sources of [[],['source'],['source','source'],['missing'],['group'],['m0-0'],['pile0']])assert.equal(core.dropTarget(nodes,point,excluded,sources),legacy(nodes,point,excluded,sources));});
test('each pointer sample observes in-place membership edits and removals',()=>{const nodes=fixture(2),point={x:50,y:30};assert.equal(core.dropTarget(nodes,point,[],['source']).id,'pile1');const first=nodes.find(n=>n.id==='pile0');const removed=first.memberIds.pop();assert.equal(core.dropTarget(nodes,point,[],['source']),first);first.memberIds.push(removed);assert.equal(core.dropTarget(nodes,point,[],['source']).id,'pile1');nodes.splice(nodes.findIndex(n=>n.id==='source'),1);assert.equal(core.dropTarget(nodes,point,[],['source']),undefined);});
test('overlap validation builds one membership index, and misses/gallery hits need none',()=>{const nodes=fixture(24);let reads=0;for(const pile of nodes.filter(n=>n.type==='pile')){const ids=pile.memberIds;Object.defineProperty(pile,'memberIds',{get(){reads++;return ids;}});}core.dropTarget(nodes,{x:50,y:30},[],['source']);assert.equal(reads,48);reads=0;core.dropTarget(nodes,{x:500,y:30},[],['source']);assert.equal(reads,0);core.dropTarget(nodes,{x:50,y:30});assert.equal(reads,0);});
