const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../canvas-piles.js'),G=require('../canvas-groups.js'),T=require('../templates-core.js'),A=require('../pile-archive.js'),tools=require('../agent-tools.js');
const fixture=()=>[{id:'a',type:'video',x:228892,y:183938,width:435,height:250},{id:'b',type:'video',x:229337,y:183741,width:435,height:250},{id:'c',type:'video',x:228917,y:184205,width:435,height:250}];
test('stack retains real node identities and exact world coordinates',()=>{const nodes=fixture(),before=structuredClone(nodes),p=P.stack(nodes,['a','b','c'],'p');assert.deepEqual(nodes.slice(0,3),before);assert.deepEqual(p.memberIds,['a','b','c']);assert.equal(p.x,229114.5);assert.equal(p.y,183973);assert.deepEqual([...P.index(nodes).owner.keys()],['a','b','c']);});
test('source 128-spacing center-first scatter and .5 precision',()=>{const nodes=fixture();P.stack(nodes,['a','b','c'],'p');P.unstack(nodes,'p');assert.deepEqual(nodes.map(({id,x,y})=>({id,x,y})),[{id:'a',x:229396,y:183784},{id:'b',x:228833,y:183784},{id:'c',x:229114.5,y:184162}]);});
test('gallery exact original three-video coordinates and padded bounds',()=>{const layout=P.gallery(fixture());assert.deepEqual(layout.items.map(n=>[n.x,n.y]),[[-708.5,-105],[-217.5,-105],[273.5,-105]]);assert.equal(layout.bounds.left,-820.5);assert.equal(P.displaySize({type:'text',width:800,height:400}).width,320);});
test('join flattens piles preserving target center and caps 50',()=>{const nodes=[...fixture(),...fixture().map(n=>({...n,id:n.id+'2',x:n.x+5000}))];const target=P.stack(nodes,['a','b'],'p'),center=target.x+target.width/2;P.stack(nodes,['a2','b2','c2'],'q');P.join(nodes,'p',['q','c']);assert.deepEqual(target.memberIds,['a','b','a2','b2','c2','c']);assert.equal(target.x+target.width/2,center);assert.ok(!nodes.some(n=>n.id==='q'));assert.equal(P.plan(Array.from({length:51},(_,i)=>({...fixture()[0],id:String(i)})),Array.from({length:51},(_,i)=>String(i))),null);});
test('release keeps exact point and dissolves last pair at center',()=>{const nodes=fixture(),p=P.stack(nodes,['a','b','c'],'p'),center={x:p.x+p.width/2,y:p.y+p.height/2};P.release(nodes,'p','a',{x:-200000.25,y:100.75});assert.equal(nodes[0].x,-200000.25);assert.deepEqual(p.memberIds,['b','c']);P.release(nodes,'p','b',{x:12,y:13});assert.ok(!nodes.includes(p));assert.equal(nodes[2].x,center.x-nodes[2].width/2);});
test('group move includes pile members once and never auto-groups hidden nodes',()=>{const nodes=fixture();nodes.push({id:'g',type:'group',x:220000,y:180000,width:10000,height:10000});nodes.slice(0,3).forEach(n=>n.parentId='g');const p=P.stack(nodes,['a','b','c'],'p');assert.equal(p.parentId,'g');const before=structuredClone(nodes),snapshot=G.positions(nodes,['g','p']);assert.equal(snapshot.length,5);G.translate(nodes,snapshot,11.25,-5.75);G.autoGroup(nodes,snapshot.map(n=>n.id));for(const n of nodes){const b=before.find(b=>b.id===n.id);assert.equal(n.x,b.x+11.25);assert.equal(n.y,b.y-5.75);}assert.equal(nodes[0].parentId,undefined);});
test('template remaps hidden members/edges without duplicate parent offsets',()=>{const nodes=fixture();nodes.push({id:'g',type:'group',x:220000,y:180000,width:10000,height:10000});nodes.slice(0,3).forEach(n=>n.parentId='g');P.stack(nodes,['a','b','c'],'p');const graph=T.capture(nodes,[{id:'ab',source:'a',target:'b'}],'g');assert.equal(graph.nodes.length,4);assert.equal(graph.width,515);let i=0;const result=T.instantiate({name:'pile',graph},{x:40.125,y:-999.25},()=>String(i++)),pile=result.nodes.find(n=>n.type==='pile'),members=P.index(result.nodes).members.get(pile.id);assert.equal(members.length,3);assert.ok(members.every(n=>!n.parentId));assert.equal(pile.x,80.125);assert.equal(members[1].x-members[0].x,445);assert.equal(result.edges[0].source,members[0].id);assert.equal(G.descendants(result.nodes,[result.group.id]).size,5);graph.nodes.find(n=>n.type==='pile').memberIds.push('missing');assert.throws(()=>T.instantiate({graph},{x:0,y:0}),/引用/);});
test('ownership deterministic and invalid stack atomic',()=>{const nodes=fixture();nodes.push({id:'z',type:'pile',memberIds:['a','b']},{id:'p',type:'pile',memberIds:['a','c']});assert.equal(P.index(nodes).owner.get('a'),'p');const before=structuredClone(nodes);assert.throws(()=>P.stack(nodes,['a','b'],'new'));assert.deepEqual(nodes,before);});
test('Agent validates stack/release with mutation confirmation',()=>{assert.ok(tools.parse('canvas_stack',{ids:['a','b']}).definition.mutates);assert.throws(()=>tools.parse('canvas_stack',{ids:['a']}));assert.throws(()=>tools.parse('canvas_pile_release',{pileId:'p',id:'a',x:Infinity,y:0}));});
test('ZIP preserves CRC32 and Unicode filenames',async()=>{assert.equal(A.crc32(new TextEncoder().encode('123456789')),0xcbf43926);const bytes=new Uint8Array(await A.zip([{name:'视频.txt',bytes:new TextEncoder().encode('真实内容')}]).arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(6,true),0x800);assert.equal(v.getUint16(bytes.length-14,true),1);});

test('reconcile deletes stale references and dissolves singleton at pile center',()=>{const nodes=fixture(),p=P.stack(nodes,['a','b','c'],'p'),center=p.x+p.width/2;nodes.splice(0,2);assert.deepEqual(P.reconcile(nodes),['p']);assert.equal(nodes.length,1);assert.equal(nodes[0].x+nodes[0].width/2,center);});

test('pile previews share a render index while keeping three-argument refresh and media updates',()=>{
 const fs=require('node:fs'),vm=require('node:vm');let indexCalls=0;
 class Element{
  constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.attributes={};}
  setAttribute(key,value){this.attributes[key]=value;}
  append(...children){this.children.push(...children);}
  replaceChildren(...children){this.children=children;}
  querySelector(){return this.body;}
  querySelectorAll(){return this.children.flatMap(child=>[...(child.className==='pile-media'?[child]:[]),...child.querySelectorAll()]);}
 }
 const window={CanvasPiles:{...P,index(nodes){indexCalls++;return P.index(nodes);}},PileMotion:require('../canvas-pile-motion.js'),CANVAS_GROUP_ICONS:{},UI_ICONS:{image:'image'}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../canvas-piles-ui.js'),'utf8'),{window,document:{createElement:tag=>new Element(tag),addEventListener(){}}});
 const nodes=[],entries=[];
 for(let i=0;i<100;i++){const members=Array.from({length:4},(_,j)=>({id:`${i}-${j}`,type:'image',title:`图片${j}`,image:`/${i}-${j}.png`,x:i*1000+.125,y:j*500+.375,width:435,height:250})),pile={id:`pile${i}`,type:'pile',memberIds:members.map(n=>n.id)};nodes.push(...members,pile);const element=new Element('node');element.body=new Element('body');entries.push({pile,element});}
 let shared=P.index(nodes);for(const {pile,element}of entries)window.CanvasPilesUI.refresh(pile,element,nodes,shared);assert.equal(indexCalls,0);
 const first=entries[0],cards=first.element.body.children.slice();nodes[0].x+=.125;
 shared=P.index(nodes);for(const {pile,element}of entries)window.CanvasPilesUI.refresh(pile,element,nodes,shared);assert.equal(indexCalls,0);assert.deepEqual(first.element.body.children,cards);
 nodes[0].image='/new.png';first.pile.memberIds.reverse();window.CanvasPilesUI.refresh(first.pile,first.element,nodes,P.index(nodes));
 const media=first.element.body.children.flatMap(card=>card.children.filter(child=>child.className==='pile-media'));
 assert.equal(media.at(-1).children[0].src,'/new.png');assert.notEqual(first.element.body.children[0],cards[0]);
 const before=JSON.stringify(first.element.body);window.CanvasPilesUI.refresh(first.pile,first.element,nodes);assert.equal(indexCalls,1);assert.equal(JSON.stringify(first.element.body),before);
});
