const test=require('node:test'),assert=require('node:assert/strict'),{TaskService}=require('../generation-api.js');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZXkAAAAASUVORK5CYII=','base64'),resultUrl='/api/generation/media/12345678-abcd-4abc-8abc-123456789abc';
const load=()=>Promise.all([import('../src/features/agent-apps/ecommerce-photoset-runtime.mjs'),import('../src/features/agent-apps/ecommerce-photoset.mjs')]);
async function fixture(options={}){const [r,m]=await load();let project='p',current=true,bytes=png,saveCount=0,posts=0,lookups=0,persisted;const graph={nodes:[{id:'product',type:'image',image:'asset:product',fullImage:'asset:product',x:0,y:0,width:320,height:320}],edges:[]},chat={id:'chat',messages:[]};const app={getState:()=>graph,createConnected:(id,patches)=>patches.map(p=>{const n={...structuredClone(p),id:crypto.randomUUID(),x:500,y:0};graph.nodes.push(n);graph.edges.push({id:crypto.randomUUID(),source:id,target:n.id});return n;})};const service=new TaskService();service.setProvider({isConfigured:async()=>options.configured!==false,generate:async request=>{posts++;assert.equal(persisted.ecommercePhotosetOperations.some(r=>r.task_id=== [...service.jobs.values()].find(j=>j.request===request)?.id),true);if(options.unknown)throw Object.assign(Error('interrupted'),{code:'unknown'});return {outputs:[{type:'image',url:resultUrl,width:1,height:1}]};},lookup:async id=>{lookups++;const original=service.jobs.get(id);return {id,request:original?.request||structuredClone(options.remoteRequest),status:'succeeded',outputs:[{type:'image',url:resultUrl,width:1,height:1}]};}});
 const api={submit:(req,opts)=>service.submit(req,opts),getJobs:()=>[...service.jobs.values()],availability:async()=>({configured:options.configured!==false}),recover:id=>service.recover(id),cancel:id=>service.cancel(id)},fetchImpl=async(url,opts)=>{if(options.remoteAsset)return new Response(png,{headers:{'content-type':'image/png'}});if(options.fetch) return options.fetch(url,opts);return new Response(bytes,{headers:{'content-type':'image/png'}});};
 const runtime=r.createEcommercePhotosetRuntime({app,localAssets:{url:async()=>options.remoteAsset?'https://example.org/product.png':'blob:product'},store:{save:async()=>options.canvasFail?false:true},getProjectId:()=>project,persistConversation:async()=>{saveCount++;await options.saveHook?.(saveCount,chat.messages[0]);if(options.saveFail) return false;persisted=structuredClone(chat.messages[0]);return true;},generationAPI:api,fetchImpl,renderImage:async()=>({width:1,height:1}),getOrigin:()=> 'http://localhost:5173',timeoutMs:options.timeout||1000});
 const data={mode:'amazon',product_context:{product_label:'真实输入',product_node_ids:['product']},requirements:[{sequence:1,theme:'主图',visual_requirement:'真实结构',copy_requirement:''},{sequence:2,theme:'细节',visual_requirement:'可见结构',copy_requirement:''}],params:{model:'gpt-image-2',aspect_ratio:'1:1',resolution:'2K',image_variant_count:1,quality:'medium'},locale:'zh-CN'},args={resource_uri:m.ecommercePhotosetUri,data},prepared=await runtime.prepareAppArgs(args),trace={id:'trace',result:runtime.bindPreparedResult({response:m.prepareEcommercePhotoset(prepared.data)},prepared)};chat.messages.push(trace);trace.appState=m.initialEcommercePhotosetState(data);const context=runtime.capture(trace.result.response,{trace,chat,isCurrent:()=>current});
 function request(callId='call'){trace.appState.pending={call_id:callId,sequences:[1,2]};for(const row of Object.values(trace.appState.rows))row.status='pending';return {product_context:structuredClone(data.product_context),requirements:data.requirements.map(r=>({...r,template_key:''})),params:structuredClone(data.params),confirmation:{schema_version:'app_generation_confirmation.v1',item_count:2,output_count:2,acknowledged:true},locale:'zh-CN'};}
 const generate=(req,callId='call')=>runtime.generate(req,trace,chat,{callId,userAction:true,isCurrent:()=>current,sourceContext:context});return {m,runtime,trace,chat,graph,api,service,context,request,generate,setProject:p=>project=p,setCurrent:c=>current=c,swap:b=>bytes=b,stats:()=>({posts,lookups,saveCount,persisted}),tick:()=>new Promise(r=>setImmediate(r))};}
test('real TaskService dispatches one task per row only after durable task receipt, immutable full pixels, duplicates dedupe',async()=>{const f=await fixture(),args=f.request(),result=await f.generate(args);assert.equal(result.items.length,2);await f.tick();assert.equal(f.stats().posts,2);assert.equal(f.service.jobs.size,2);for(const job of f.service.jobs.values()){assert.equal(job.status,'succeeded');assert.equal(job.request.inputs[0].url,'data:image/png;base64,'+png.toString('base64'));assert.equal(job.outputs[0].url,resultUrl);assert.equal(job.request.parameters.outputQuality,'medium');}const again=await f.generate(args);assert.deepEqual(again,result);assert.equal(f.stats().posts,2);assert.equal(f.graph.nodes.length,3);});
test('official final submitted save and page close do not invalidate already accepted TaskService guard',async()=>{const f=await fixture(),result=await f.generate(f.request());for(const item of result.items){f.trace.appState.rows[item.sequence].status='submitted';f.trace.appState.rows[item.sequence].node_id=item.node_id;}delete f.trace.appState.pending;f.context.validateState(f.trace.appState);f.context.dispose();await f.tick();assert.ok([...f.service.jobs.values()].every(j=>j.status==='succeeded'));});
test('unconfigured API creates no placeholder, dispatch, or fake success',async()=>{const f=await fixture({configured:false}),result=await f.generate(f.request());assert.equal(result.configuration_required,true);assert.equal(result.items.length,0);assert.ok(result.failed_items.every(r=>r.reason==='configuration_required'));assert.equal(f.stats().posts,0);assert.equal(f.graph.nodes.length,1);});
test('unknown tasks recover original identity by lookup; repeated confirmation does not POST again',async()=>{const f=await fixture({unknown:true}),first=await f.generate(f.request());await f.tick();assert.ok([...f.service.jobs.values()].every(j=>j.status==='unknown'));const second=await f.generate(f.request());assert.deepEqual(second.items,first.items);assert.equal(f.stats().posts,2);assert.equal(f.stats().lookups,2);assert.ok([...f.service.jobs.values()].every(j=>j.status==='succeeded'));});
test('save failure and canvas save failure prevent provider dispatch',async()=>{for(const key of ['saveFail','canvasFail']){const f=await fixture({[key]:true});await assert.rejects(f.generate(f.request()));await f.tick();assert.equal(f.stats().posts,0);}});
test('source byte replacement, session/project changes and injected saved status are rejected',async()=>{const f=await fixture(),args=f.request();f.swap(Buffer.from('changed'));await assert.rejects(f.generate(args),{code:'source_changed'});assert.equal(f.stats().posts,0);f.swap(png);f.setProject('other');await assert.rejects(f.generate(args));f.setProject('p');f.setCurrent(false);await assert.rejects(f.generate(args));f.setCurrent(true);const state=structuredClone(f.trace.appState);state.rows[1].status='submitted';state.rows[1].node_id='fake';assert.throws(()=>f.context.validateState(state),{code:'invalid_receipt'});});
test('a deleted submitted task node cannot silently recreate output',async()=>{const f=await fixture(),args=f.request(),result=await f.generate(args);await f.tick();f.graph.nodes=f.graph.nodes.filter(n=>n.id!==result.items[0].node_id);await assert.rejects(f.generate(args),{code:'output_changed'});assert.equal(f.stats().posts,2);});
test('remote asset resolver and generated response peer mismatch are blocked before decoding',async()=>{await assert.rejects(fixture({remoteAsset:true}),{code:'nonlocal_source'});const f=await fixture();f.graph.nodes[0].image=f.graph.nodes[0].fullImage=resultUrl;const runtime=f.runtime;await assert.rejects(runtime.prepareAppArgs({resource_uri:f.m.ecommercePhotosetUri,data:f.trace.result.response}),{code:'nonlocal_source'});});
test('duplicate concurrent confirmation shares a pending task set',async()=>{const f=await fixture(),args=f.request(),[a,b]=await Promise.all([f.generate(args),f.generate(args)]);assert.deepEqual(a,b);await f.tick();assert.equal(f.stats().posts,2);assert.equal(f.service.jobs.size,2);});
test('context uses actual persisted accepted receipts even before official finally-save, rejects invented nodes',async()=>{const f=await fixture(),result=await f.generate(f.request()),value={content:[{type:'text',text:'E-commerce photo set submitted sequences '+result.items.map(r=>r.sequence+':'+r.node_id+':'+f.trace.appState.rows[r.sequence].theme).join(',')+'. Canvas nodes are the source of truth.'}]};await f.runtime.setModelContext(value,f.trace,f.chat,{sourceContext:f.context,userAction:true,isCurrent:()=>true});assert.deepEqual(f.trace.ecommercePhotosetContext,value);await assert.rejects(f.runtime.setModelContext({content:[{type:'text',text:value.content[0].text.replace(result.items[0].node_id,'fake')}]},f.trace,f.chat,{sourceContext:f.context,userAction:true,isCurrent:()=>true}));});
test('taskId persistence gate cannot dispatch while durable conversation transaction remains pending',async()=>{let release,entered;const blocked=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const f=await fixture({saveHook:async n=>{if(n===2){entered();await gate;}}}),pending=f.generate(f.request());await blocked;await f.tick();assert.equal(f.stats().posts,0);assert.equal([...f.service.jobs.values()][0].status,'queued');release();const receipt=await pending;assert.equal(receipt.items.length,2);await f.tick();assert.equal(f.stats().posts,2);});
test('fresh callId for equivalent unknown request recovers saved jobs without creating duplicate tasks',async()=>{const f=await fixture({unknown:true}),first=await f.generate(f.request('a'),'a');await f.tick();const second=await f.generate(f.request('b'),'b');assert.deepEqual(second.items,first.items);assert.equal(f.service.jobs.size,2);assert.equal(f.stats().posts,2);assert.equal(f.stats().lookups,2);assert.ok(f.trace.ecommercePhotosetOperations.every(r=>r.callIds.includes('b')));});
