const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {createDurableGenerationService}=require('../server/generation-durable.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const reply=value=>({ok:true,json:async()=>value}),result={outputs:[{type:'text',text:'实际供应商结果'}],status:'succeeded'};
const request={kind:'text.generate',nodeId:'node',prompt:'原始请求',parameters:{count:1}},key='stable-key-1';
function memoryStore(records=[]){const data=new Map(records.map(record=>[record.id,structuredClone(record)]));let writes=0,failAt=0;return {data,setFailAt(value){failAt=value;},get writes(){return writes;},readAll:async()=>[...data.values()].map(value=>structuredClone(value)),write:async record=>{writes++;if(writes===failAt)throw Object.assign(Error('disk full'),{code:'storage_error'});data.set(record.id,JSON.parse(JSON.stringify(record)));}};}
function service(store,fetchImpl,extra={}){return createDurableGenerationService({store,baseUrl:'https://provider.test',apiKey:'never-store-this-secret',fetchImpl,...extra});}
test('durable idempotency survives restart, rejects replacement requests and polls original provider task only once concurrently',async t=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'canvas-generation-durable-'));const calls=[],gate=deferred();
 const fetchImpl=async(url,options)=>{calls.push([url,options.method]);if(options.method==='POST')return reply({id:'remote/id',status:'running',progress:20});await gate.promise;return reply({...result,id:'remote/id'});};
 let current=createDurableGenerationService({directory,baseUrl:'https://provider.test',apiKey:'never-store-this-secret',fetchImpl});t.after(async()=>{await current.close();await fs.rm(directory,{recursive:true,force:true});});
 const [first,duplicate]=await Promise.all([current.submit(request,{idempotencyKey:key}),current.submit(structuredClone(request),{idempotencyKey:key})]);assert.equal(first.id,duplicate.id);await current.get(first.id);assert.equal(calls.filter(([,method])=>method==='POST').length,1);await assert.rejects(()=>current.submit({...request,prompt:'替换旧请求'},{idempotencyKey:key}),{code:'idempotency_conflict'});
 await current.close();current=createDurableGenerationService({directory,baseUrl:'https://provider.test',apiKey:'rotated-secret',fetchImpl});await current.ready;
 const a=current.lookup(key),b=current.get(first.id);await tick();assert.equal(calls.filter(([,method])=>method==='GET').length,1);gate.resolve();const recovered=await a;await b;assert.equal(recovered.status,'succeeded');assert.deepEqual(recovered.outputs,result.outputs);assert.equal(calls[1][0],'https://provider.test/tasks/remote%2Fid');assert.equal((await current.submit(request,{idempotencyKey:key})).id,first.id);assert.equal(calls.filter(([,method])=>method==='POST').length,1);
 const disk=await fs.readFile(path.join(directory,first.id+'.json'),'utf8');assert.ok(!disk.includes('never-store-this-secret'));assert.ok(!disk.includes('rotated-secret'));assert.ok(!disk.includes('Authorization'));assert.equal((await fs.stat(path.join(directory,first.id+'.json'))).mode&0o777,0o600);
 const rival=createDurableGenerationService({directory,baseUrl:'https://provider.test',apiKey:'other',fetchImpl:()=>assert.fail()});await assert.rejects(rival.ready,{code:'storage_error'});await rival.close();await current.close();await fs.writeFile(path.join(directory,first.id+'.json'),'{broken');current=createDurableGenerationService({directory,fetchImpl:()=>assert.fail()});await assert.rejects(current.ready,{code:'storage_error'});await assert.rejects(()=>current.submit(request,{idempotencyKey:'fresh-key-2'}),{code:'storage_error'});
});
test('POST uncertainty without provider identity survives restart as unknown and never replays submission',async()=>{
 const store=memoryStore();let posts=0;const fetchImpl=async()=>{assert.equal([...store.data.values()][0].submissionState,'dispatching');posts++;throw Error('connection lost after provider may have accepted');};let current=service(store,fetchImpl),job=await current.submit(request,{idempotencyKey:key});job=await current.get(job.id);assert.equal(job.status,'unknown');assert.equal(job.recovery.retryableLookup,false);await current.close();current=service(store,fetchImpl);await current.ready;
 assert.equal((await current.lookup(key)).status,'unknown');assert.equal((await current.submit(request,{idempotencyKey:key})).id,job.id);assert.equal(posts,1);await current.close();
});
test('checkpoint failures block dispatch or expose unknown instead of unsaved success; credentials are rejected before persistence',async()=>{
 for(const failAt of [1,3,4]){const store=memoryStore();store.setFailAt(failAt);let calls=0;const current=service(store,async()=>{calls++;return reply({id:'remote',...result});});
  if(failAt===1){await assert.rejects(()=>current.submit(request,{idempotencyKey:key}),{code:'storage_error'});assert.equal(calls,0);const reserved=await current.submit(request,{idempotencyKey:key});assert.equal(reserved.status,'unknown');assert.equal(reserved.code,'storage_error');assert.equal((await current.submit(request,{idempotencyKey:key})).id,reserved.id);assert.equal(calls,0);}
  else{const first=await current.submit(request,{idempotencyKey:key}),job=await current.get(first.id);assert.equal(job.status,'unknown');assert.equal(job.code,'storage_error');assert.equal(job.outputs,undefined);assert.equal(calls,failAt===3?0:1);assert.equal((await current.get(first.id)).status,'unknown');assert.equal(calls,failAt===3?0:1);}
  await current.close();
 }
 const store=memoryStore(),current=service(store,()=>assert.fail());for(const credential of [{apiKey:'secret'},{parameters:{Authorization:'Bearer secret'}},{inputs:[{credentials:{token:'secret'}}]}])await assert.rejects(()=>current.submit({...request,...credential},{idempotencyKey:key}),{code:'credentials_forbidden'});assert.equal(store.writes,0);await current.close();
});
test('cancel checkpoint blocks late outputs, discovers late provider ID only to cancel it, and restart never applies it',async()=>{
 const store=memoryStore(),gate=deferred(),started=deferred(),methods=[];const current=service(store,async(_url,options)=>{methods.push(options.method);if(options.method==='POST'){started.resolve();await gate.promise;return reply({id:'remote',...result});}return reply({status:'cancelled'});});
 const job=await current.submit(request,{idempotencyKey:key});await started.promise;const cancelled=await current.cancel(job.id);assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.cancellation.providerCancellation,'unconfirmed');gate.resolve();for(let i=0;i<5;i++)await tick();const final=await current.get(job.id);assert.equal(final.status,'cancelled');assert.equal(final.outputs,undefined);assert.equal(final.cancellation.providerCancellation,'confirmed');assert.deepEqual(methods,['POST','DELETE']);await current.close();
 const restored=service(store,()=>assert.fail('cancelled job must never poll or post'));assert.equal((await restored.lookup(key)).status,'cancelled');await restored.close();
 const broken=memoryStore(),late=deferred(),sent=deferred(),unsafe=service(broken,async()=>{sent.resolve();await late.promise;return reply({id:'late',...result});}),unconfirmed=await unsafe.submit(request,{idempotencyKey:key});await sent.promise;broken.setFailAt(broken.writes+1);await assert.rejects(()=>unsafe.cancel(unconfirmed.id),{code:'storage_error'});late.resolve();for(let i=0;i<5;i++)await tick();const blocked=await unsafe.get(unconfirmed.id);assert.equal(blocked.status,'unknown');assert.equal(blocked.outputs,undefined);await unsafe.close();
});
test('known provider IDs recover GET failures, reject changed gateway identity, and never accept success without actual outputs',async()=>{
 const store=memoryStore();let phase=0,posts=0,gets=0;let current=service(store,async(_url,options)=>{if(options.method==='POST'){posts++;return reply({id:'remote',status:'running'});}gets++;if(phase===0)throw Error('GET unavailable');if(phase===1)return reply({id:'remote',status:'succeeded'});return reply({id:'remote',...result});});
 const created=await current.submit(request,{idempotencyKey:key});await current.get(created.id);assert.equal((await current.get(created.id)).recovery.retryableLookup,true);phase=1;const empty=await current.get(created.id);assert.equal(empty.status,'unknown');assert.equal(empty.code,'missing_outputs');assert.equal(empty.outputs,undefined);await current.close();
 current=service(store,()=>assert.fail('changed provider must not receive original task ID'),{baseUrl:'https://different.test'});assert.equal((await current.get(created.id)).code,'provider_configuration_changed');await current.close();current=service(store,async()=>{gets++;return reply({id:'remote',...result});});assert.equal((await current.get(created.id)).status,'succeeded');assert.equal(posts,1);await current.close();
 const saved=store.data.get(created.id);saved.outputs=[];store.data.set(created.id,saved);const invalid=service(store,()=>assert.fail('loading corrupt outputs must not dispatch'));await invalid.ready;const receipt=await invalid.submit(request,{idempotencyKey:key});assert.equal(receipt.status,'unknown');assert.equal(receipt.code,'stored_outputs_invalid');assert.equal(receipt.outputs,undefined);await invalid.close();
});

test('outputs are accepted only for explicit success or legacy missing status, never unknown or running responses',async()=>{
 for(const status of ['unknown','running','queued','failed','cancelled','configuration_required',null,'unexpected',undefined,'succeeded']){
  const store=memoryStore(),current=service(store,async()=>reply({id:'remote',outputs:result.outputs,...(status===undefined?{}:{status})})),created=await current.submit(request,{idempotencyKey:key}),job=await current.get(created.id);
  if(status===undefined||status==='succeeded'){assert.equal(job.status,'succeeded');assert.deepEqual(store.data.get(job.id).outputs,result.outputs);}else{assert.equal(job.status,'unknown');assert.equal(job.code,'contradictory_outputs');assert.equal(job.outputs,undefined);assert.equal(store.data.get(job.id).outputs,undefined);}await current.close();
 }
 const store=memoryStore(),current=service(store,async()=>reply({id:'remote',status:'unknown'})),created=await current.submit(request,{idempotencyKey:key});assert.equal((await current.get(created.id)).status,'unknown');await current.close();
});
test('cancel or close during GET drops late outputs; close during success persistence waits for its durable checkpoint',async()=>{
 for(const stop of ['cancel','close']){
  const store=memoryStore(),gate=deferred(),polling=deferred(),current=service(store,async(_url,options)=>{if(options.method==='POST')return reply({id:'remote',status:'running'});if(options.method==='DELETE')return reply({status:'cancelled'});polling.resolve();await gate.promise;return reply({id:'remote',...result});});
  const created=await current.submit(request,{idempotencyKey:key});await current.get(created.id);const pending=current.get(created.id);await polling.promise;if(stop==='cancel')await current.cancel(created.id);else await current.close();const writes=store.writes;gate.resolve();const value=await pending;assert.notEqual(value.status,'succeeded');assert.equal(value.outputs,undefined);assert.equal(store.data.get(created.id).outputs,undefined);assert.equal(store.writes,writes);await current.close();
 }
 const store=memoryStore(),persist=store.write,entered=deferred(),release=deferred();store.write=async record=>{if(record.status==='succeeded'){entered.resolve();await release.promise;}return persist(record);};
 const current=service(store,async(_url,options)=>reply(options.method==='POST'?{id:'remote',status:'running'}:{id:'remote',...result})),created=await current.submit(request,{idempotencyKey:key});await current.get(created.id);const poll=current.get(created.id);await entered.promise;let closed=false;const closing=current.close().then(()=>closed=true);await tick();assert.equal(closed,false);assert.notEqual(store.data.get(created.id).status,'succeeded');release.resolve();const value=await poll;await closing;assert.equal(value.status,'succeeded');assert.equal(store.data.get(created.id).status,'succeeded');assert.deepEqual(store.data.get(created.id).outputs,result.outputs);
});

test('scene provenance survives durable restart and malformed time ranges are rejected',async()=>{
 for(const sourceRange of [{start:2,end:4},{start:4,end:2},{start:-1,end:2},{start:0,end:Infinity},{start:0,end:2,extra:true}]){
 const store=memoryStore(),output={type:'video',url:'data:video/mp4;base64,AAAA',text:'镜头描述',sourceRange};let current=service(store,async()=>reply({status:'succeeded',outputs:[output]}));const job=await current.submit({...request,kind:'video.analyze'},{idempotencyKey:'scene-provenance'}),done=await current.get(job.id);await current.close();
 if(sourceRange.start===2){assert.equal(done.status,'succeeded');current=service(store,()=>assert.fail('must not dispatch again'));await current.ready;const restored=await current.get(job.id);assert.deepEqual(restored.outputs[0].sourceRange,{start:2,end:4});assert.equal(restored.outputs[0].text,'镜头描述');assert.equal(restored.outputs[0].clip,undefined);await current.close();}else assert.equal(done.status,'unknown');
 }
});
