'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createVideoReshootProvider,parseVideoReshootModelMap}=require('../server/generation-video-reshoot.cjs');
const {createDurableGenerationService}=require('../server/generation-durable.cjs');
const {createGenerationMediaStore}=require('../server/generation-media-store.cjs');
const {createGenerationMediaMaterializer}=require('../server/generation-media-materializer.cjs');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{Readable}=require('node:stream');
const profile={ratios:['adaptive'],durations:[-1],resolutions:['720p','1080p'],audio:true,maxImages:0,maxVideos:1,maxAudios:0,videoDurationRange:{min:4,max:30,totalMax:30},omniReferenceTaskType:'edit'};
const modelMap={'seedance-2.5':{kind:'video.reshoot',model:'operator-real-model',capabilityMode:'prompt_simulation',resolution:'720p',generateAudio:true,profile}};
const a={azimuth:0,distance:.2,elevation:0},b={azimuth:135,distance:.85,elevation:-45};
const request={kind:'video.reshoot',nodeId:'source',prompt:'主体红衣保持一致',inputs:[{type:'video',role:'source_video',nodeId:'source',url:'https://media.test/selected.mp4',width:1280,height:720,duration:8,durationMs:8000,sourceRange:{start:2,end:10}}],parameters:{modelId:'seedance-2.5',schemaVersion:1,intent:'video_multi_view',capabilityMode:'prompt_simulation',aspectRatio:'adaptive',duration:8,candidateCount:1,sourceClip:null,resolution:'1080p',generateAudio:false,tracks:['unchanged','static','cut','dynamic'].map((mode,i)=>({segmentId:'seg-'+i,name:'分镜'+i,startTime:i*2,endTime:(i+1)*2,mode,pointA:a,...['cut','dynamic'].includes(mode)?{pointB:b}:{},instruction:mode==='unchanged'?'':'仅本段指令'+i}))}};
const clone=()=>structuredClone(request),response=value=>new Response(JSON.stringify(value)),provider=fetchImpl=>createVideoReshootProvider({baseUrl:'https://ark.test/api/v3',apiKey:'synthetic-test',modelMap,fetchImpl}),tick=()=>new Promise(r=>setImmediate(r));
function store(){const data=new Map();return {data,readAll:async()=>[...data.values()].map(x=>structuredClone(x)),write:async j=>{data.set(j.id,structuredClone(j));return j;}};}
test('explicit mapping exposes honest camera limitations and no private operator model or key',()=>{
 const p=provider(()=>assert.fail());assert.equal(p.configured,true);assert.equal(p.metadata.protocol,'ark-video-reshoot-edit');assert.deepEqual(p.metadata.capabilities.kinds,['video.reshoot']);assert.equal(p.metadata.capabilities.videoReshoot.nativeCameraControl,false);assert.equal(p.metadata.capabilities.videoReshoot.exactUnchangedSegments,false);assert.equal(p.metadata.capabilities.remoteCancellation,false);assert.equal(p.cancel,undefined);assert(!JSON.stringify(p.metadata).includes('operator-real-model'));assert(!JSON.stringify(p.metadata).includes('synthetic-test'));
 for(const change of [e=>e.capabilityMode='native',e=>e.profile.omniReferenceTaskType='auto',e=>e.profile.durations=[8],e=>e.profile.maxImages=1,e=>e.profile.videoDurationRange.min=2,e=>e.unknown='ignored']){const m=structuredClone(modelMap);change(m['seedance-2.5']);assert.throws(()=>parseVideoReshootModelMap(m));}
 assert.equal(createVideoReshootProvider({baseUrl:'https://ark.test',modelMap}).configured,false);
});
test('all camera modes, segment labels, instructions and exact coordinates reach Ark edit request without source-model or spec substitution',async()=>{
 let body;const p=provider(async(url,o)=>{assert.equal(url,'https://ark.test/api/v3/contents/generations/tasks');assert.equal(o.method,'POST');body=JSON.parse(o.body);return response({id:'original-reshoot'});});
 await p.submit(request);assert.equal(body.model,'operator-real-model');assert.equal(body.omni_reference_task_type,'edit');assert.equal(body.duration,-1);assert.equal(body.ratio,'adaptive');assert.equal(body.resolution,'1080p');assert.equal(body.generate_audio,false);
 const prompt=body.content[0].text;for(const t of request.parameters.tracks){assert(prompt.includes(t.segmentId));assert(prompt.includes(t.name));if(t.mode!=='unchanged')assert(prompt.includes(t.instruction));if(t.pointB)assert(prompt.includes(JSON.stringify(t.pointB)));}assert.match(prompt,/preserve the original source video exactly/);assert.match(prompt,/hard cut between views/);assert.match(prompt,/smooth A→B camera motion/);assert.match(prompt,/主体红衣/);assert.deepEqual(body.content[1],{type:'video_url',video_url:{url:request.inputs[0].url},role:'reference_video'});assert.equal(request.inputs[0].role,'source_video');assert.equal(request.parameters.duration,8);
});
test('malformed plans, hidden instructions, local media, clips and unsupported fields fail before POST',async()=>{
 let calls=0;const p=provider(()=>{calls++;assert.fail();});
 const mutations=[r=>r.kind='video.generate',r=>r.parameters.capabilityMode='native',r=>r.parameters.modelId='source-model',r=>r.parameters.providerParameters={model:'other'},r=>r.parameters.providerParameters={model:'seedance-2.5',audio:false},r=>r.parameters.extra='lost',r=>r.parameters.candidateCount=2,r=>r.parameters.aspectRatio='16:9',r=>r.parameters.sourceClip={start:2,end:10},r=>r.inputs[0].clip={start:2,end:10},r=>r.inputs[0].url='data:video/mp4;base64,AAAA',r=>r.inputs[0].url='/local.mp4',r=>r.inputs[0].width=320,r=>r.inputs[0].duration=3,r=>r.inputs[0].durationMs=9000,r=>r.inputs[0].sourceRange.end=11,r=>r.inputs.push({...r.inputs[0]}),r=>r.parameters.tracks[0].instruction='hidden text',r=>r.parameters.tracks[1].startTime=2.1,r=>r.parameters.tracks[3].endTime=7,r=>r.parameters.tracks[2].pointB.distance=2,r=>r.parameters.tracks[1].pointB={...a},r=>r.parameters.tracks[1].segmentId='seg-0',r=>r.parameters.tracks[2].pointB=null,r=>r.parameters.tracks[2].preset='lost',r=>r.parameters.resolution='4k',r=>r.parameters.generateAudio='false',r=>r.parameters.apiKey='must-reject'];
 for(const change of mutations){const r=clone();change(r);await assert.rejects(()=>p.submit(r),e=>['unsupported_generation','configuration_required','credentials_forbidden'].includes(e.code)&&e.providerDispatched!==true);}
 assert.equal(calls,0);
});
test('query keeps original task identity and cannot invent dimensions, duration or a source copy',async()=>{
 const urls=[],p=provider(async(url,o)=>{urls.push([url,o.method]);return response({id:'original-reshoot',status:'succeeded',duration:8,content:{video_url:'https://media.test/new.mp4'}});});assert.deepEqual(await p.poll('original-reshoot'),{id:'original-reshoot',status:'succeeded',outputs:[{type:'video',url:'https://media.test/new.mp4',sourceFileId:'original-reshoot'}]});assert.deepEqual(urls,[['https://ark.test/api/v3/contents/generations/tasks/original-reshoot','GET']]);await assert.rejects(()=>provider(async()=>response({id:'changed',status:'running'})).poll('original-reshoot'),{code:'unknown'});
});
test('unknown creation survives restart and idempotent resubmission without another POST',async()=>{
 const disk=store();let calls=0;const p=provider(async()=>{calls++;return new Response('not-json');});let service=createDurableGenerationService({store:disk,provider:p});const job=await service.submit(request,{idempotencyKey:'reshoot-unknown'});await tick();await tick();assert.equal((await service.get(job.id)).status,'unknown');await service.close();service=createDurableGenerationService({store:disk,provider:p});await service.ready;assert.equal((await service.submit(request,{idempotencyKey:'reshoot-unknown'})).id,job.id);assert.equal(calls,1);await service.close();
});
test('cancellation suppresses late creation without claiming remote cancellation or exposing results',async()=>{
 const disk=store();let release,start;const gate=new Promise(r=>release=r),started=new Promise(r=>start=r);let posts=0;const p=provider(async()=>{posts++;start();await gate;return response({id:'late-original'});});const service=createDurableGenerationService({store:disk,provider:p});const j=await service.submit(request,{idempotencyKey:'reshoot-cancel'});await started;assert.equal((await service.cancel(j.id)).status,'cancelled');release();await tick();await tick();const result=await service.get(j.id);assert.equal(result.status,'cancelled');assert.equal(result.outputs,undefined);assert.equal(posts,1);await service.close();
});
test('accepted task recovery archives actual MP4 bytes once before exposing success and survives second restart',async t=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'freenow-reshoot-')),disk=store(),mp4=await fs.readFile(path.join(__dirname,'../src/features/video-generation/qa/media/2.mp4'));let complete=false,posts=0,gets=0,downloads=0,service,media;
 const p=provider(async(_url,o)=>{if(o.method==='POST'){posts++;return response({id:'archive-original'});}gets++;return response({id:'archive-original',status:complete?'succeeded':'running',...complete?{content:{video_url:'https://media.test/new.mp4'}}:{}});});
 function open(){media=createGenerationMediaStore({directory});service=createDurableGenerationService({store:disk,provider:p,mediaMaterializer:createGenerationMediaMaterializer({store:media,download:async(url,{kind,onBytes})=>{assert.equal(url,'https://media.test/new.mp4');assert.equal(kind,'video');downloads++;onBytes(mp4.length);return {stream:Readable.from([mp4]),mime:'video/mp4',maxBytes:mp4.length,expectedBytes:mp4.length};}})});}
 t.after(async()=>{await service?.close();await media?.close();await fs.rm(directory,{recursive:true,force:true});});open();const job=await service.submit(request,{idempotencyKey:'reshoot-archive'});await tick();await tick();assert.equal(disk.data.get(job.id).providerTaskId,'archive-original');await service.close();await media.close();complete=true;open();await service.ready;const result=await service.lookup('reshoot-archive');assert.equal(result.status,'succeeded');assert.match(result.outputs[0].url,/^\/api\/generation\/media\//);assert.equal(result.outputs[0].sourceFileId,'archive-original');assert.equal(result.outputs[0].duration,undefined);assert.deepEqual(await fs.readFile(path.join(directory,result.outputs[0].url.split('/').at(-1)+'.bin')),mp4);assert.equal(posts,1);assert.equal(downloads,1);const before=gets;await service.close();await media.close();open();await service.ready;assert.deepEqual((await service.lookup('reshoot-archive')).outputs,result.outputs);assert.equal(gets,before);assert.equal(downloads,1);
});

test('an all-unchanged camera plan is a no-op and cannot dispatch even through the adapter directly',async()=>{
 let posts=0;const p=provider(()=>{posts++;assert.fail('no-op cannot call model');}),r=clone();for(const t of r.parameters.tracks){t.mode='unchanged';t.instruction='';delete t.pointB;}await assert.rejects(()=>p.submit(r),/无需生成/);assert.equal(posts,0);
});
