'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createMiniMaxMusicProvider,parseMiniMaxMusicModelMap,MAX_JSON_BYTES}=require('../server/generation-minimax-music.cjs');
const core=require('../audio-core.js'),key='synthetic-minimax-music-contract-key',mp3=fs.readFileSync(path.join(__dirname,'fixtures/elevenlabs-tone-44100.mp3'));
const request={kind:'audio.generate',prompt:'夜晚骑行的原创流行歌曲',inputs:[],parameters:{model:'music-2.6',scene:'Music',virtualModel:'minimax-music-26',lyric_mode:false,force_instrumental:false,lyrics:''}};
const params=changes=>({...request,parameters:{...request.parameters,...changes}});
const receipt=(bytes=mp3)=>({base_resp:{status_code:0,status_msg:'success'},data:{status:2,audio:bytes.toString('hex')},extra_info:{music_size:bytes.length,music_sample_rate:44100},trace_id:'not-a-recoverable-task'});
const json=(value=receipt(),headers={})=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json',...headers}});
const provider=options=>createMiniMaxMusicProvider({apiKey:key,fetchImpl:async()=>json(),...options});
function wave(){const bytes=Buffer.alloc(44+4800);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(24000,24);bytes.writeUInt32LE(48000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(4800,40);for(let i=0;i<2400;i++)bytes.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*440/24000)*5000),44+i*2);return bytes;}
test('MiniMax exact native POST keeps real hex audio identity, no subtitles or remote task identity',async()=>{
 let calls=0;const native=provider({fetchImpl:async(url,options)=>{calls++;assert.equal(String(url),'https://api.minimax.io/v1/music_generation');assert.equal(options.method,'POST');assert.equal(options.headers.Authorization,'Bearer '+key);assert.equal(options.redirect,'error');assert.equal(options.headers['Accept-Encoding'],'identity');assert.deepEqual(JSON.parse(options.body),{model:'music-2.6',prompt:request.prompt,stream:false,output_format:'hex',audio_setting:{format:'mp3',sample_rate:44100,bitrate:128000},lyrics_optimizer:true,is_instrumental:false});return json();}});
 const result=await native.submit(request);assert.deepEqual(result,{status:'succeeded',outputs:[{type:'audio',url:'data:audio/mpeg;base64,'+mp3.toString('base64')}]});assert.equal(calls,1);assert.equal(native.poll,undefined);assert.equal(native.cancel,undefined);assert.equal(native.isPollable(),false);assert.equal(native.metadata.capabilities.accountEligibility,'existing-paid-music-api-user');assert.equal(native.metadata.capabilities.remoteRecovery,false);assert.equal(JSON.stringify(native.metadata).includes(key),false);assert.equal(native.fingerprint,provider({apiKey:'rotated-contract-key'}).fingerprint);
});
test('actual AudioCore nodes auto, custom and instrumental use all matching parameters',async()=>{
 const bodies=[],native=provider({fetchImpl:async(_url,options)=>{bodies.push(JSON.parse(options.body));return json();}});
 for(const mode of ['auto','custom','instrumental']){const node=core.transition({prompt:mode==='custom'?'':request.prompt},'minimax-music-26','Music');Object.assign(node.params,{lyric_mode:mode==='custom',force_instrumental:mode==='instrumental',lyrics:mode==='custom'?'[Verse]\n灯火与晚风\n[Chorus]\n一路向前':''});await native.submit({...request,prompt:node.prompt,parameters:{...node.params,model:node.model,scene:node.scene,virtualModel:node.virtualModel}});}
 assert.equal(bodies[0].lyrics_optimizer,true);assert.equal(bodies[1].lyrics,'[Verse]\n灯火与晚风\n[Chorus]\n一路向前');assert.equal(bodies[1].prompt,'');assert.equal(bodies[1].lyrics_optimizer,false);assert.equal(bodies[2].is_instrumental,true);assert.equal(bodies[2].lyrics_optimizer,false);assert.equal(Object.hasOwn(bodies[2],'lyrics'),false);
});
test('Agent catalog reuses MiniMax icon and core transition preserves lyrics, format and sampling',async()=>{
 const {audioModels,audioModel,audioSpec,createAudioDraft,audioRequestConfig,validateAudioDraft,normalizeAudio}=await import('../src/features/agent-generation/audio.mjs');
 const {videoModels}=await import('../src/features/agent-generation/video-catalog.mjs');assert.equal(audioModel('music-2.6').icon,videoModels.find(m=>m.id==='MiniMax-H3').icon);assert.equal(audioModels.filter(m=>m.virtual==='minimax-music-26').length,1);
 let transitions=0;const wrapped={transition(...args){transitions++;return core.transition(...args);}},bodies=[],native=provider({fetchImpl:async(_url,options)=>{bodies.push(JSON.parse(options.body));return json();}});
 for(const lyricsMode of ['auto','custom','instrumental']){const args={kind:'audio.generate',model:'music-2.6',audioScene:'Music',lyricsMode,prompt:lyricsMode==='custom'?'':request.prompt,lyrics:lyricsMode==='custom'?'[Verse]\n原样换行':''};const draft=createAudioDraft(args);validateAudioDraft(draft);assert.equal(audioSpec(draft).lyricsLimit,3500);const node=audioRequestConfig(wrapped,{},args);assert.equal(node.params.format,'mp3');assert.equal(node.params.sample_rate,44100);await native.submit({...request,prompt:node.prompt,parameters:{...node.params,model:node.model,scene:node.scene,virtualModel:node.virtualModel}});}
 assert.equal(transitions,3);assert.equal(bodies[1].lyrics,'[Verse]\n原样换行');const wav=audioRequestConfig(core,{}, {kind:'audio.generate',model:'music-2.6',prompt:'纯音乐',lyricsMode:'instrumental',audioFormat:'wav',sampleRate:24000});assert.equal(wav.params.format,'wav');assert.equal(wav.params.sample_rate,24000);
 const residual=normalizeAudio({model:'music-2.6',prompt:'保留用户歌词',lyricsMode:'auto',lyrics:'不丢失'});assert.equal(residual.lyrics,'不丢失');assert.throws(()=>validateAudioDraft(residual),/清空歌词/);assert.throws(()=>audioRequestConfig(core,{},residual),/清空歌词/);assert.throws(()=>validateAudioDraft(createAudioDraft({model:'music-2.6',prompt:'a'.repeat(2001)})),/2000/);assert.throws(()=>validateAudioDraft(createAudioDraft({model:'music-2.6',prompt:'p',lyricsMode:'custom',lyrics:'a'.repeat(3501)})),/3500/);
 const source=core.transition({prompt:'source'},'minimax-music-26','Music');Object.assign(source.params,{lyric_mode:true,force_instrumental:true,lyrics:'冲突歌词'});assert.throws(()=>createAudioDraft({kind:'audio.generate',nodeId:'source'},[{id:'source',audioConfig:source}]),/参数冲突/);assert.throws(()=>audioRequestConfig(core,source,{kind:'audio.generate',nodeId:'source'}),/参数冲突/);
 source.params.force_instrumental=false;Object.assign(source.params,{format:'wav',sample_rate:24000});const restored=createAudioDraft({kind:'audio.generate',nodeId:'source'},[{id:'source',audioConfig:source}]);assert.equal(restored.lyrics,'冲突歌词');assert.equal(restored.audioFormat,'wav');assert.equal(restored.sampleRate,24000);assert.equal(audioRequestConfig(core,source,{kind:'audio.generate',nodeId:'source'}).params.lyrics,'冲突歌词');
});
test('official China origin and explicit alias map stay exact; incompatible configs are unavailable',async()=>{
 const native=provider({baseUrl:'https://api.minimax.cn',modelMap:{'music-local.alias':{kind:'audio.generate',model:'music-2.6'}},fetchImpl:async(url,options)=>{assert.equal(String(url),'https://api.minimax.cn/v1/music_generation');assert.equal(JSON.parse(options.body).model,'music-2.6');return json();}});await native.submit(params({model:'music-local.alias'}));
 for(const options of [{apiKey:''},{apiKey:'bad\nkey'},{modelMap:{}},{baseUrl:'https://tapnow.media'},{baseUrl:'https://example.test/v1'},{modelMap:{x:{kind:'audio.generate',model:'music-3.0'}}},{modelMap:{x:{kind:'audio.generate',model:'music-2.6',audioSetting:{format:'pcm'}}}},{modelMap:{x:{kind:'audio.generate',model:'music-2.6',audioSetting:{format:'wav',bitrate:128000}}}},{modelMap:{x:{kind:'audio.generate',model:'music-2.6',audioSetting:{sampleRate:16000,bitrate:256000}}}}]){const unavailable=provider(options);assert.equal(unavailable.configured,false);assert.throws(()=>unavailable.prepare(request),{code:'configuration_required'});}
 assert.throws(()=>parseMiniMaxMusicModelMap({x:{kind:'audio.generate',model:'music-2.6',unknown:true}}));
});
test('unsupported settings and conflicting lyrics fail before any network call',async()=>{
 let calls=0;const native=provider({fetchImpl:()=>{calls++;throw Error();}});
 for(const changes of [{duration:30},{enable_subtitle:true},{voice:'voice'},{stream:true},{output_format:'url'},{count:2},{times:0},{scene:'Sound'},{model:'music_v1'},{modelId:'other'},{virtualModel:'elevenlabs-v3'},{format:'wav'},{sample_rate:24000},{bitrate:64000},{lyric_mode:'true'},{force_instrumental:1},{lyrics:1},{lyrics:'残留歌词'},{force_instrumental:true,lyrics:'残留歌词'},{lyric_mode:true,force_instrumental:true,lyrics:'冲突'},{lyric_mode:true,lyrics:''},{lyric_mode:true,lyrics:'a'.repeat(3501)}])await assert.rejects(native.submit(params(changes)));
 for(const changes of [{prompt:''},{prompt:'a'.repeat(2001)},{count:2},{kind:'audio.subtitle'},{inputs:[{type:'audio',url:'data:audio/mpeg;base64,AAAA'}]},{references:[{type:'text',text:'unexpanded'}]}])await assert.rejects(native.submit({...request,...changes}));assert.equal(calls,0);
});
test('text references are composed once and official prompt boundaries are enforced',async()=>{
 const bodies=[],native=provider({fetchImpl:async(_url,options)=>{bodies.push(JSON.parse(options.body));return json();}}),text='温柔中文流行歌曲';
 for(const prompt of ['正文',text+'\n正文'])await native.submit({...request,prompt,inputs:[{type:'text',text}]});assert.equal(bodies[0].prompt,text+'\n正文');assert.equal(bodies[1].prompt,bodies[0].prompt);await native.submit({...request,prompt:'a'.repeat(2000)});await assert.rejects(native.submit({...request,prompt:'a'.repeat(1999),inputs:[{type:'text',text:'ref'}]}));
});
test('WAV configuration accepts actual PCM bytes and duration, rejects codec, length and sampling mismatch',async()=>{
 const bytes=wave(),modelMap={'music-2.6':{kind:'audio.generate',model:'music-2.6',audioSetting:{format:'wav',sampleRate:24000}}},value=receipt(bytes);value.extra_info.music_sample_rate=24000;
 const native=provider({modelMap,fetchImpl:async(_url,options)=>{assert.deepEqual(JSON.parse(options.body).audio_setting,{format:'wav',sample_rate:24000});return json(value);}});assert.deepEqual((await native.submit(params({format:'wav',sample_rate:24000}))).outputs,[{type:'audio',url:'data:audio/wav;base64,'+bytes.toString('base64'),duration:.1}]);
 const badCodec=Buffer.from(bytes);badCodec.writeUInt16LE(65535,20);const badRate=Buffer.from(bytes);badRate.writeUInt32LE(48000,24);
 for(const bad of [mp3,bytes.subarray(0,bytes.length-3),badCodec,badRate])await assert.rejects(provider({modelMap,fetchImpl:async()=>json({...value,data:{status:2,audio:bad.toString('hex')}})}).submit(request),{code:'unknown'});
});
test('malformed or incomplete hex and false audio metadata never become success',async()=>{
 const values=[{...receipt(),data:{status:2,audio:''}},{...receipt(),data:{status:2,audio:'abc'}},{...receipt(),data:{status:2,audio:'zz'}},receipt(Buffer.from('not-audio')),receipt(mp3.subarray(0,mp3.length-7)),{...receipt(),data:{status:1,audio:mp3.toString('hex')}},{...receipt(),extra_info:{music_size:mp3.length+1}},{...receipt(),extra_info:{music_sample_rate:24000}},{...receipt(),base_resp:{status_code:'0'}}];
 for(const value of values){let calls=0;await assert.rejects(provider({fetchImpl:async()=>{calls++;return json(value);}}).submit(request),{code:'unknown'});assert.equal(calls,1);}
});
test('declared MIME, encoding and body limits reject untrusted receipts with one POST',async()=>{
 for(const headers of [{'content-type':'text/html'},{'content-encoding':'gzip'},{'content-length':'0'},{'content-length':'bad'},{'content-length':String(MAX_JSON_BYTES+1)},{'content-length':'1'}]){let calls=0;await assert.rejects(provider({fetchImpl:async()=>{calls++;return json(receipt(),headers);}}).submit(request),{code:'unknown'});assert.equal(calls,1);}
});
test('explicit MiniMax refusal is a terminal failed receipt, incomplete HTTP is unknown',async()=>{
 await assert.rejects(provider({fetchImpl:async()=>json({base_resp:{status_code:1008,status_msg:'private '+key}})}).submit(request),{code:'unknown'});
 // Credential-free vendor rejection is confirmed; status_msg is never echoed.
 const result=await provider({fetchImpl:async()=>json({base_resp:{status_code:1008,status_msg:'account not eligible'}})}).submit(request);assert.equal(result.status,'failed');assert.equal(result.code,'provider_rejected');assert.equal(result.outputs,undefined);assert.equal(result.id,undefined);assert.equal(JSON.stringify(result).includes('account not eligible'),false);
 await assert.rejects(provider({fetchImpl:async()=>new Response('refused',{status:401})}).submit(request),{code:'unknown'});
});
test('credential echo inside JSON or actual MP3 metadata is refused without leaking the key',async()=>{
 const offset=mp3.toString('ascii',0,3)==='ID3'?10+mp3[6]*2097152+mp3[7]*16384+mp3[8]*128+mp3[9]:0,tag=Buffer.alloc(10+key.length);tag.write('ID3');tag[3]=3;tag[9]=key.length;tag.write(key,10);
 for(const value of [{...receipt(),trace_id:key},receipt(Buffer.concat([tag,mp3.subarray(offset)]))])await assert.rejects(provider({fetchImpl:async()=>json(value)}).submit(request),error=>error.code==='unknown'&&!error.message.includes(key));
});
test('abort, stalled reads and late fetch remain unknown or cancelled with a single POST',async()=>{
 const before=new AbortController();before.abort(Error('cancel before'));await assert.rejects(provider({fetchImpl:()=>assert.fail()}).submit(request,{signal:before.signal}),/cancel before/);
 let release,calls=0,lateCancelled=false;const timeout=provider({timeoutMs:10,fetchImpl:()=>{calls++;return new Promise(resolve=>{release=resolve;});}});await assert.rejects(timeout.submit(request),{code:'unknown'});release(new Response(new ReadableStream({cancel(){lateCancelled=true;}}),{headers:{'content-type':'application/json'}}));await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);assert.equal(lateCancelled,true);
 let start,cancelled=false;const begun=new Promise(resolve=>{start=resolve;}),abort=new AbortController(),native=provider({fetchImpl:async()=>new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(Buffer.from('{')));start();},cancel(){cancelled=true;}}),{headers:{'content-type':'application/json'}})}),pending=native.submit(request,{signal:abort.signal});await begun;await new Promise(resolve=>setImmediate(resolve));abort.abort(Error('cancel read'));await assert.rejects(pending,/cancel read/);assert.equal(cancelled,true);
 let stallCalls=0,stallCancelled=false;await assert.rejects(provider({timeoutMs:10,fetchImpl:async()=>{stallCalls++;return new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(Buffer.from('{')));},cancel(){stallCancelled=true;}}),{headers:{'content-type':'application/json'}});}}).submit(request),{code:'unknown'});assert.equal(stallCalls,1);assert.equal(stallCancelled,true);
});
