'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {createOpenAIMaskedEditProvider,parseOpenAIMaskedEditModelMap,REDRAW_PREFIX,FIRST_PREFIX,MAX_RESPONSE_BYTES,validSize}=require('../server/generation-openai-masked-edit.cjs');
const {encodeRGBA,decodePNG,alphaMask,crc32,MAX_PIXELS}=require('../server/generation-png-alpha.cjs');
const key='synthetic-openai-mask-contract-key',pixels=Buffer.from([250,10,20,255, 25,240,35,0, 40,55,230,128, 200,150,20,255]),source=encodeRGBA(2,2,pixels),sourceUrl='data:image/png;base64,'+source.toString('base64'),output=encodeRGBA(1024,1024,Buffer.alloc(1024*1024*4,255)),outputB64=output.toString('base64'),reference=fs.readFileSync(path.join(__dirname,'fixtures/red.jpg'));
const profile=(kind='image.erase',extra={})=>({kind,model:'gpt-image-2',allowDynamicSize:true,qualityMap:{low:'low',medium:'medium',high:'high'},maxCount:4,...extra});
const request={kind:'image.erase',prompt:'只擦除透明选区并自然补全环境',sourceNodeId:'source',inputs:[{type:'image',nodeId:'source',url:sourceUrl}],parameters:{model:'gpt-image-2',aspectRatio:'auto',imageSize:'1K',quality:'low',targetWidth:1024,targetHeight:1024,times:1}};
const provider=(options={})=>createOpenAIMaskedEditProvider({apiKey:key,modelMap:{'gpt-image-2':profile()},client:{images:{edit:async body=>({data:Array.from({length:body.n},()=>({b64_json:outputB64}))})}},...options});
const response=(data=[{b64_json:outputB64}],headers={},status=200)=>new Response(JSON.stringify({data}),{status,headers:{'content-type':'application/json',...headers}});
const changed=parameters=>({...request,parameters:{...request.parameters,...parameters}});
function pngChunk(type,data){const bytes=Buffer.alloc(data.length+12);bytes.writeUInt32BE(data.length);bytes.write(type,4);data.copy(bytes,8);bytes.writeUInt32BE(crc32(bytes.subarray(4,-4)),bytes.length-4);return bytes;}
function filteredRGBA(filter){const width=2,height=2,row=width*4,raw=Buffer.alloc((row+1)*height);const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};for(let y=0;y<height;y++){raw[y*(row+1)]=filter;for(let x=0;x<row;x++){const i=y*row+x,a=x>=4?pixels[i-4]:0,b=y?pixels[i-row]:0,c=y&&x>=4?pixels[i-row-4]:0;raw[y*(row+1)+1+x]=(pixels[i]-(filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):paeth(a,b,c)))&255;}}return Buffer.concat([source.subarray(0,33),pngChunk('IDAT',zlib.deflateSync(raw)),pngChunk('IEND',Buffer.alloc(0))]);}
test('PNG parser reconstructs all filters and derives a separate exact-coordinate alpha-zero mask',()=>{
 for(const filter of [0,1,2,3,4]){const bytes=filteredRGBA(filter),image=decodePNG(bytes);assert.deepEqual(image.pixels,pixels);assert.equal(image.width,2);assert.equal(image.height,2);const mask=alphaMask(bytes);assert.equal(mask.editablePixels,1);assert.equal(mask.preservedPixels,3);assert.deepEqual(decodePNG(mask.bytes).pixels,Buffer.from([0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,255]));assert.equal(mask.width,2);assert.equal(mask.height,2);assert.notDeepEqual(mask.bytes,bytes);}
});
test('PNG integrity, alpha and decompression bounds reject before dispatch',()=>{
 const crcBad=Buffer.from(source);crcBad[crcBad.length-1]^=1;const ihdr=Buffer.from(source.subarray(16,29));ihdr[12]=1;const interlaced=Buffer.concat([source.subarray(0,8),pngChunk('IHDR',ihdr),source.subarray(33)]);const hugeIHDR=Buffer.from(ihdr);hugeIHDR[12]=0;hugeIHDR.writeUInt32BE(65535);hugeIHDR.writeUInt32BE(65535,4);const huge=Buffer.concat([source.subarray(0,8),pngChunk('IHDR',hugeIHDR),source.subarray(33)]),bomb=Buffer.concat([source.subarray(0,33),pngChunk('IDAT',zlib.deflateSync(Buffer.alloc(1000))),pngChunk('IEND',Buffer.alloc(0))]),trailingStream=Buffer.concat([source.subarray(0,33),pngChunk('IDAT',Buffer.concat([zlib.deflateSync(Buffer.alloc(18)),Buffer.from('extra')])),pngChunk('IEND',Buffer.alloc(0))]);
 for(const bytes of [crcBad,interlaced,huge,bomb,trailingStream,source.subarray(0,-1),Buffer.concat([source,Buffer.from('extra')])])assert.throws(()=>decodePNG(bytes),{code:'unsupported_generation'});
 const rgbIHDR=Buffer.from(source.subarray(16,29));rgbIHDR[9]=2;const rgb=Buffer.concat([source.subarray(0,8),pngChunk('IHDR',rgbIHDR),pngChunk('IDAT',zlib.deflateSync(Buffer.from([0,250,10,20,25,240,35,0,40,55,230,200,150,20]))),pngChunk('IEND',Buffer.alloc(0))]);assert.equal(decodePNG(rgb).channels,3);assert.throws(()=>alphaMask(rgb));
 assert.throws(()=>decodePNG(Buffer.concat([source.subarray(0,33),pngChunk('PLTE',Buffer.alloc(0)),source.subarray(33)])));
 for(const alpha of [0,255]){const rgba=Buffer.alloc(16,alpha);assert.throws(()=>alphaMask(encodeRGBA(2,2,rgba)),/同时含/);}assert.throws(()=>encodeRGBA(MAX_PIXELS+1,1,Buffer.alloc(0)));
});
test('actual installed SDK multipart sends source first and true PNG mask, exact size/quality/count and one POST',async()=>{
 let calls=0;const native=provider({client:undefined,fetchImpl:async(url,options)=>{calls++;assert.equal(String(url),'https://api.openai.com/v1/images/edits');assert.equal(options.redirect,'error');assert.equal(new Headers(options.headers).get('authorization'),'Bearer '+key);assert.equal(new Headers(options.headers).get('accept-encoding'),'identity');const form=await new Request(url,{...options,duplex:'half'}).formData(),images=form.getAll('image[]');assert.equal(images.length,1);assert.equal(images[0].name,'main.png');assert.deepEqual(Buffer.from(await images[0].arrayBuffer()),source);const mask=Buffer.from(await form.get('mask').arrayBuffer());assert.deepEqual(decodePNG(mask).pixels,decodePNG(alphaMask(source).bytes).pixels);assert.equal(form.get('size'),'1024x1024');assert.equal(form.get('quality'),'low');assert.equal(form.get('n'),'2');assert.equal(form.get('stream'),'false');assert.equal(form.get('output_format'),'png');assert.equal(form.get('input_fidelity'),null);assert.equal(form.get('model'),'gpt-image-2');return response([{b64_json:outputB64},{b64_json:outputB64}]);}});
 const result=await native.submit(changed({times:2}));assert.equal(result.status,'succeeded');assert.deepEqual(result.outputs,[{type:'image',url:'data:image/png;base64,'+outputB64,width:1024,height:1024},{type:'image',url:'data:image/png;base64,'+outputB64,width:1024,height:1024}]);assert.equal(calls,1);assert.equal(native.poll,undefined);assert.equal(native.cancel,undefined);assert.equal(native.metadata.capabilities.maskedEdits['gpt-image-2'].maskCoordinatePolicy,'unscaled-source-pixels');assert.equal(native.fingerprint,provider({apiKey:'rotated-key'}).fingerprint);assert.equal(JSON.stringify(native.metadata).includes(key),false);
});
test('real redraw core request with a reference maps last main to first and preserves user suffix',async()=>{
 const redraw=await import('../image-redraw-core.mjs'),settings=await import('../image-outpaint-core.mjs'),suffix='只重绘橙色帽子。 Image 1 in this quoted lyric stays verbatim.\n继续保留纹理',prompt=redraw.prompt(suffix,true);assert.equal(prompt,REDRAW_PREFIX+suffix);let posted;
 const native=provider({modelMap:{'gpt-image-2':profile('image.redraw')},client:{images:{edit:async body=>{posted=body;return {data:[{b64_json:outputB64}]};}}}}),draft={...request,kind:'image.redraw',prompt,inputs:[{type:'image',nodeId:'reference',url:'data:image/jpeg;base64,'+reference.toString('base64')},request.inputs[0]],parameters:{model:'gpt-image-2',...settings.parameters({model:'gpt-image-2',resolution:'1K',quality:'low'},{width:2,height:2}),times:1}};
 const result=await native.submit(draft);assert.equal(result.status,'succeeded');assert.equal(posted.prompt,FIRST_PREFIX+suffix);assert.deepEqual(Buffer.from(await posted.image[0].arrayBuffer()),source);assert.deepEqual(Buffer.from(await posted.image[1].arrayBuffer()),reference);assert.equal(posted.mask.type,'image/png');assert.equal(posted.image[1].type,'image/jpeg');assert.equal(decodePNG(Buffer.from(await posted.mask.arrayBuffer())).width,2);
 await assert.rejects(native.submit({...draft,prompt:'普通图生图不能冒充蒙版重绘'}),{code:'unsupported_generation'});await assert.rejects(native.submit({...draft,inputs:[...draft.inputs,request.inputs[0]]}),{code:'unsupported_generation'});
});
test('outpaint keeps original canvas x/y and source/mask pixels while target uses verified dynamic rectangle size',async()=>{
 const settings=await import('../image-outpaint-core.mjs'),rgba=Buffer.alloc(6*4*4);for(let y=1;y<3;y++)for(let x=2;x<4;x++){const i=(y*6+x)*4;rgba[i]=210;rgba[i+3]=255;}const bytes=encodeRGBA(6,4,rgba),target=settings.outputPixels({width:6,height:4},'1K'),rectOutput=encodeRGBA(target.targetWidth,target.targetHeight,Buffer.alloc(target.targetWidth*target.targetHeight*4,255));let posted;
 const native=provider({modelMap:{'gpt-image-2':profile('image.outpaint')},client:{images:{edit:async body=>{posted=body;return {data:[{b64_json:rectOutput.toString('base64')}]};}}}}),draft={...request,kind:'image.outpaint',prompt:settings.prompt,inputs:[{type:'image',nodeId:'source',url:'data:image/png;base64,'+bytes.toString('base64')}],parameters:{model:'gpt-image-2',...settings.parameters({model:'gpt-image-2',resolution:'1K',quality:'medium'},{width:6,height:4}),times:1,canvas:{width:6,height:4,x:2,y:1}}};
 const before=structuredClone(draft);await native.submit(draft);assert.deepEqual(draft,before);assert.equal(posted.size,target.targetWidth+'x'+target.targetHeight);assert.deepEqual(Buffer.from(await posted.image[0].arrayBuffer()),bytes);assert.deepEqual(decodePNG(Buffer.from(await posted.mask.arrayBuffer())).pixels.filter((_,i)=>i%4===3),rgba.filter((_,i)=>i%4===3));await assert.rejects(native.submit({...draft,parameters:{...draft.parameters,canvas:{width:7,height:4,x:2,y:1}}}));
});
test('explicit model profiles and strict size/quality maps are required without provider alias guessing',async()=>{
 for(const options of [{apiKey:'',client:undefined},{modelMap:{}},{apiKey:'bad\nkey'},{baseUrl:'https://tapnow.media/v1'},{modelMap:{'gpt-image-2':profile('image.erase',{model:'gpt-image-1.5'})}},{modelMap:{'gpt-image-2':profile('image.erase',{kind:'image.generate'})}},{modelMap:{'gpt-image-2':profile('image.erase',{qualityMap:{low:'high'}})}},{modelMap:{'gpt-image-2':profile('image.erase',{allowDynamicSize:false,sizeMap:{'1K|1024x1024':'1536x1024'}})}},{modelMap:{'gpt-image-2':profile('image.erase',{allowDynamicSize:false})}}]){const native=provider(options);assert.equal(native.configured,false);assert.throws(()=>native.prepare(request),{code:'configuration_required'});}
 assert.throws(()=>parseOpenAIMaskedEditModelMap({alias:profile('image.erase',{mask:false})}));const strict=provider({modelMap:{'gpt-image-2':profile('image.erase',{allowDynamicSize:false,sizeMap:{'1K|1024x1024':'1024x1024'}})}});assert.equal((await strict.submit(request)).status,'succeeded');await assert.rejects(strict.submit(changed({targetWidth:1536,targetHeight:1024})),{code:'configuration_required'});
 let model;const aliased=provider({modelMap:{'display-alias':profile('image.erase',{model:'gpt-image-2-2026-04-21'})},client:{images:{edit:async body=>{model=body.model;return {data:[{b64_json:outputB64}]};}}}});await aliased.submit(changed({model:'display-alias'}));assert.equal(model,'gpt-image-2-2026-04-21');
});
test('unsupported parameters, absent alpha selection, wrong references and size constraints cause zero dispatch',async()=>{
 let calls=0;const native=provider({client:{images:{edit:()=>{calls++;throw Error();},generate:()=>assert.fail('never generate')}}});
 for(const p of [{mask:sourceUrl},{prompt:'ignored'},{providerParameters:{model:'gpt-image-2'}},{aspectRatio:'1:1'},{enableGoogleSearch:true},{format:'jpeg'},{input_fidelity:'high'},{modelId:'other'},{canvas:{width:2,height:2,x:0,y:0}},{times:2,count:1},{times:5},{quality:'unknown'},{targetWidth:1025},{targetHeight:256},{targetWidth:4096},{targetWidth:16,targetHeight:16},{targetWidth:3840,targetHeight:3840}])await assert.rejects(native.submit(changed(p)));
 for(const changes of [{inputs:[]},{inputs:[...request.inputs,...request.inputs]},{inputs:[{type:'image',url:'https://example.test/source.png'}]},{inputs:[{type:'image',url:'data:image/jpeg;base64,'+reference.toString('base64')}]},{inputs:[{...request.inputs[0],width:3}]},{sourceNodeId:'another'},{inputs:[{type:'image',url:'data:image/png;base64,'+encodeRGBA(2,2,Buffer.alloc(16,255)).toString('base64')}]},{kind:'image.generate'},{references:[{type:'image',url:sourceUrl}]},{prompt:'a'.repeat(32001)}])await assert.rejects(native.submit({...request,...changes}));assert.equal(calls,0);for(const size of ['1024x1024','1536x1024','2880x2880','3840x2160'])assert.equal(validSize(size),true);
});
test('malformed actual output, result count and size mismatch stay unknown and never rePOST',async()=>{
 const crcBad=Buffer.from(output);crcBad[crcBad.length-1]^=1;
 for(const data of [[],[{url:'https://example.test/result.png'}],[{b64_json:source.toString('base64')}],[{b64_json:crcBad.toString('base64')}],[{b64_json:outputB64},{b64_json:outputB64}],[{b64_json:outputB64,url:'https://other.test/result'}],[{b64_json:'AA=='}]]){let calls=0;const native=provider({client:{images:{edit:async()=>{calls++;return {data};}}}});await assert.rejects(native.submit(request),{code:'unknown'});assert.equal(calls,1);}
});
test('official SDK 4xx receipt becomes terminal failed; uncertain transport and spoofed client error remain unknown',async()=>{
 for(const status of [400,401,403,404,422,429]){let calls=0;const native=provider({client:undefined,fetchImpl:async()=>{calls++;return new Response(JSON.stringify({error:{message:'private vendor detail',type:'invalid_request_error'}}),{status,headers:{'content-type':'application/json'}});}});const result=await native.submit(request);assert.equal(result.status,'failed');assert.equal(result.code,'provider_rejected');assert.equal(result.outputs,undefined);assert.equal(JSON.stringify(result).includes('private vendor detail'),false);assert.equal(calls,1);}
 for(const status of [408,409,500]){let calls=0;await assert.rejects(provider({client:undefined,fetchImpl:async()=>{calls++;return new Response('{"error":{"message":"uncertain"}}',{status,headers:{'content-type':'application/json'}});}}).submit(request),{code:'unknown'});assert.equal(calls,1);}
 await assert.rejects(provider({client:{images:{edit:async()=>{throw Object.assign(Error('spoofed rejection'),{status:400});}}}}).submit(request),{code:'unknown'});
});
test('bounded SDK response refuses MIME, encoding, content length and secret echoes without retry',async()=>{
 for(const headers of [{'content-type':'text/html'},{'content-encoding':'gzip'},{'content-length':'1'},{'content-length':'0'},{'content-length':String(MAX_RESPONSE_BYTES+1)}]){let calls=0;await assert.rejects(provider({client:undefined,fetchImpl:async()=>{calls++;return response(undefined,headers);}}).submit(request),{code:'unknown'});assert.equal(calls,1);}
 for(const value of [{data:[{b64_json:outputB64}],usage:{echo:key}},{error:{message:key}}])await assert.rejects(provider({client:undefined,fetchImpl:async()=>new Response(JSON.stringify(value),{status:value.error?400:200,headers:{'content-type':'application/json'}})}).submit(request),e=>e.code==='unknown'&&!e.message.includes(key));
});
test('abort, SDK ignoring signal, late fetch and stalled body do not create a second POST',async()=>{
 const before=new AbortController();before.abort(Error('before submit'));await assert.rejects(provider({client:{images:{edit:()=>assert.fail()}}}).submit(request,{signal:before.signal}),/before submit/);
 let release,calls=0;const native=provider({timeoutMs:10,client:{images:{edit:()=>{calls++;return new Promise(resolve=>{release=resolve;});}}}});await assert.rejects(native.submit(request),{code:'unknown'});release({data:[{b64_json:outputB64}]});await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);
 let fetchRelease,lateCancelled=false,fetchCalls=0;await assert.rejects(provider({client:undefined,timeoutMs:10,fetchImpl:()=>{fetchCalls++;return new Promise(resolve=>{fetchRelease=resolve;});}}).submit(request),{code:'unknown'});fetchRelease(new Response(new ReadableStream({cancel(){lateCancelled=true;}}),{headers:{'content-type':'application/json'}}));await new Promise(resolve=>setImmediate(resolve));assert.equal(fetchCalls,1);assert.equal(lateCancelled,true);
 let bodyCancelled=false;await assert.rejects(provider({client:undefined,timeoutMs:10,fetchImpl:async()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(Buffer.from('{')));},cancel(){bodyCancelled=true;}}),{headers:{'content-type':'application/json'}})}).submit(request),{code:'unknown'});assert.equal(bodyCancelled,true);
});
test('native browser media preparation resolves reference bytes and actual decoded dimensions without changing source alpha',async()=>{
 const {prepareMaskedEditMedia}=await import('../src/features/image-editor/masked-edit-media.mjs');const native=provider({modelMap:{'gpt-image-2':profile('image.redraw')}}),refUrl='data:image/jpeg;base64,'+reference.toString('base64'),draft={...request,kind:'image.redraw',prompt:REDRAW_PREFIX+'红色帽子',inputs:[{type:'image',nodeId:'reference',url:'asset:reference'},request.inputs[0]]},calls=[];let guards=0;
 const prepared=await prepareMaskedEditMedia(draft,{baseUrl:'http://127.0.0.1:4173/',nativeConfiguration:native.metadata,validateSources:()=>{guards++;},resolveMedia:async(node,options)=>{calls.push({node,options});return options.decodeImage===false?{url:node.image==='asset:reference'?'blob:http://127.0.0.1:4173/ref':node.image}:{url:node.image,width:node.id==='source'?2:1,height:node.id==='source'?2:1};},transport:async(value,options)=>{assert.equal(options.inlineImages,true);assert.equal(options.maxMediaBytes,50*1024*1024-1);return {...value,inputs:value.inputs.map((v,i)=>({...v,url:i===0?refUrl:v.url}))};}});
 assert.equal(guards>=8,true);assert.equal(calls.length,4);assert.equal(prepared.inputs[0].url,refUrl);assert.equal(prepared.inputs[0].width,1);assert.equal(prepared.inputs[1].url,sourceUrl);assert.equal(prepared.inputs[1].width,2);assert.deepEqual(draft.inputs[0],{type:'image',nodeId:'reference',url:'asset:reference'});
 const tasks={protocol:'tasks-v1'};assert.equal(await prepareMaskedEditMedia(draft,{nativeConfiguration:tasks}),draft);
});
test('browser native media cancellation, replaced source and original-site references reject before network',async()=>{
 const {prepareMaskedEditMedia}=await import('../src/features/image-editor/masked-edit-media.mjs'),metadata=provider({modelMap:{'gpt-image-2':profile('image.redraw')}}).metadata,draft={...request,kind:'image.redraw',prompt:REDRAW_PREFIX+'用户文本',inputs:[{type:'image',url:'https://tapnow.media/ref.png'},request.inputs[0]]};let reads=0;
 await assert.rejects(prepareMaskedEditMedia(draft,{nativeConfiguration:metadata,resolveMedia:()=>{reads++;assert.fail();}}),{code:'original_service_blocked'});assert.equal(reads,0);
 const controller=new AbortController();controller.abort(Error('cancel media'));await assert.rejects(prepareMaskedEditMedia({...request,kind:'image.redraw'},{nativeConfiguration:metadata,signal:controller.signal,resolveMedia:()=>assert.fail()}),/cancel media/);
 let changedSource=false;await assert.rejects(prepareMaskedEditMedia({...request,kind:'image.redraw'},{nativeConfiguration:metadata,validateSources:()=>{if(changedSource)throw Error('source replaced');},resolveMedia:async()=>{changedSource=true;return {url:sourceUrl};},transport:()=>assert.fail()}),/source replaced/);
});
