'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
test('legacy fixture writes only a new isolated QA project with real video Blob and absent thumbnail fields',async()=>{
  const {seedLegacyHistory}=await import('../qa/generation-history-legacy-fixture.mjs');let serial=0,record,graph,put=0,flushed=0;const calls=[],video=new Blob(['fixed actual video'],{type:'video/mp4'}),root={location:{href:'http://localhost:4000/qa/generation-history-app.html?session=legacy-test'},CANVAS_DB_NAME:'qa-generation-history:legacy-test:canvas',LOCAL_ASSETS_DB_NAME:'qa-generation-history:legacy-test:assets',CanvasStore:{readRecord:async key=>{calls.push(key);return null;},save:async(value,id)=>graph={value,id},writeRecord:async(key,value)=>record={key,value},flush:async()=>flushed++},LocalAssets:{put:async blob=>{assert.equal(blob,video);put++;return 'asset:real-qa-video';}}};const result=await seedLegacyHistory({root,fetchImpl:async source=>{assert.equal(source,'http://localhost:4000/qa/video-cut-fixture.mp4');return {ok:true,blob:async()=>video};},validate:async(type,source)=>{assert.equal(type,'video');assert.equal(source,'blob:qa-source');return {width:320,height:240,duration:1};},createUrl:()=> 'blob:qa-source',revokeUrl:url=>calls.push(url),uuid:()=> 'fixture-'+(++serial),now:()=>Date.parse('2026-10-02T08:00:00Z')});
  assert.equal(put,1);assert.equal(flushed,1);assert.equal(graph.id,result.projectId);assert.deepEqual(graph.value.nodes,[]);assert.equal(record.key,'agent-generation-history:'+result.projectId);assert.equal(record.value.rows[0].archiveStatus,'ready');assert.equal(record.value.rows[0].mediaRef,'asset:real-qa-video');assert.equal(Object.hasOwn(record.value.rows[0],'thumbnailRef'),false);assert.equal(Object.hasOwn(record.value.rows[0],'thumbnailStatus'),false);assert.equal(new URL(result.href).searchParams.get('project'),result.projectId);assert.equal(record.value.receipts[0].recoverable,false);assert.ok(calls.includes('blob:qa-source'));
});
test('production route or mismatched browser store namespace refuses fixture before any read/write/media action',async()=>{
  const {seedLegacyHistory}=await import('../qa/generation-history-legacy-fixture.mjs');let calls=0;for(const change of [{href:'http://localhost:4000/'},{canvas:'tapnow-canvas-replica'},{assets:'tapnow-local-assets'}]){const root={location:{href:change.href || 'http://localhost:4000/qa/generation-history-app.html?session=test'},CANVAS_DB_NAME:change.canvas || 'qa-generation-history:test:canvas',LOCAL_ASSETS_DB_NAME:change.assets || 'qa-generation-history:test:assets',CanvasStore:{readRecord:async()=>{calls++;}},LocalAssets:{put:async()=>{calls++;}}};await assert.rejects(seedLegacyHistory({root,fetchImpl:async()=>{calls++;}}),/仅允许/);}assert.equal(calls,0);
});
