'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {createElevenLabsProvider,MAX_AUDIO_BYTES}=require('../server/generation-elevenlabs.cjs');
const {createGenerationRouter}=require('../server/generation-router.cjs');
const {createGenerationGateway}=require('../server/generation.cjs');
const {createDurableGenerationService}=require('../server/generation-durable.cjs');
const {readGenerationRoutingConfig}=require('../server/generation-routing-config.cjs');
const key='synthetic-elevenlabs-private-key',request={kind:'audio.generate',prompt:'你好，真实音频合同。',inputs:[],parameters:{model:'eleven_v3',scene:'Text-to-Speech',virtualModel:'elevenlabs-v3',voice_id:'stable_voice_123',stability:.5}};
const mp3=require('node:fs').readFileSync(path.join(__dirname,'fixtures/elevenlabs-tone-44100.mp3'));
const audio=(bytes=mp3,mime='audio/mpeg',headers={})=>new Response(bytes,{headers:{'content-type':mime,...headers}});
const provider=options=>createElevenLabsProvider({apiKey:key,fetchImpl:async()=>audio(),...options});
const params=changes=>({...request,parameters:{...request.parameters,...changes}});
function wave({codec=1,sampleRate=24000}={}){const bytes=Buffer.alloc(44+4800);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(codec,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(sampleRate,24);bytes.writeUInt32LE(sampleRate*2,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(bytes.length-44,40);for(let i=0;i<2400;i++)bytes.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*440/sampleRate)*5000),44+2*i);return bytes;}
test('native Eleven API uses exact model and stable voice ID, binary identity and one POST',async()=>{
 let calls=0;const native=provider({fetchImpl:async(url,options)=>{calls++;assert.equal(String(url),'https://api.elevenlabs.io/v1/text-to-speech/stable_voice_123?output_format=mp3_44100_128');assert.equal(options.method,'POST');assert.equal(options.headers['xi-api-key'],key);assert.equal(options.redirect,'error');assert.equal(options.headers['Accept-Encoding'],'identity');assert.deepEqual(JSON.parse(options.body),{text:request.prompt,model_id:'eleven_v3',voice_settings:{stability:.5}});return audio();}});
 assert.equal(native.configured,true);assert.equal(native.metadata.capabilities.models.eleven_v3.kind,'audio.generate');assert.equal(native.metadata.capabilities.remoteRecovery,false);assert.equal(native.poll,undefined);assert.equal(native.cancel,undefined);
 const result=await native.submit(request);assert.deepEqual(result,{status:'succeeded',outputs:[{type:'audio',url:'data:audio/mpeg;base64,'+mp3.toString('base64')}]});assert.equal(calls,1);assert.equal(JSON.stringify(native.metadata).includes(key),false);
 const rotated=provider({apiKey:'rotated-key'});assert.equal(rotated.fingerprint,native.fingerprint);
});
test('key-only default map is explicit, empty map and wrong origin/model stay unavailable',()=>{
 for(const options of [{apiKey:''},{modelMap:{}},{baseUrl:'https://tapnow.media'},{baseUrl:'https://example.test/v1'},{apiKey:'bad\nkey'},{modelMap:{eleven_v3:{kind:'audio.generate',model:'eleven_multilingual_v2'}}},{modelMap:{eleven_v3:{kind:'audio.generate',model:'eleven_v3',voiceMap:{alias:'another'}}}},{modelMap:{eleven_v3:{kind:'audio.generate',model:'eleven_v3',outputFormat:'opus_48000_128'}}}]){const native=provider(options);assert.equal(native.configured,false);assert.throws(()=>native.prepare(request),{code:'configuration_required'});}
});
test('node and Agent audio contracts are accepted without another-provider aliasing',async()=>{
 const core=require('../audio-core.js'),{audioRequestConfig}=await import('../src/features/agent-generation/audio.mjs');
 const node=core.transition({prompt:'节点正文'},'elevenlabs-v3','Text-to-Speech');node.params.voice_id='stable_voice_123';let posted;
 const native=provider({fetchImpl:async(_url,options)=>{posted=JSON.parse(options.body);return audio();}});await native.submit({...request,prompt:node.prompt,parameters:{...node.params,model:node.model,virtualModel:node.virtualModel,scene:node.scene}});assert.equal(posted.text,'节点正文');
 const draft=audioRequestConfig(core,{}, {kind:'audio.generate',model:'elevenlabs',audioScene:'Text-to-Speech',prompt:'Agent 正文',voice:'stable_voice_123',stability:.5});await native.submit({...request,prompt:draft.prompt,parameters:{...draft.params,model:draft.model,scene:draft.scene,virtualModel:draft.virtualModel}});assert.equal(posted.text,'Agent 正文');assert.equal(posted.model_id,'eleven_v3');
});
test('unsupported settings, cloning, contradictions and absent real voice fail before network',async()=>{
 let calls=0;const native=provider({fetchImpl:()=>{calls++;throw Error();}});
 for(const changes of [{scene:'Music'},{scene:'Sound'},{model:'music_v1'},{modelId:'other'},{voice_id:123},{voice_id:''},{voice:'different'},{virtualModel:'openai'},{stability:-.01},{stability:1.1},{stability:.3},{stability:'0.5'},{stability:NaN},{duration:30},{speed:1.2},{speech_rate:25},{format:'wav'},{sample_rate:24000},{count:2},{lyrics:'lyrics'},{apiKey:key}])await assert.rejects(native.submit(params(changes)));
 for(const changes of [{prompt:''},{prompt:'a'.repeat(3001)},{kind:'audio.clone'},{inputs:[{type:'audio',url:'data:audio/wav;base64,AAAA'}]},{references:[{type:'text',text:'unexpanded'}]}])await assert.rejects(native.submit({...request,...changes}));
 assert.equal(calls,0);
});
test('text references are read once, never silently split or sent as generation instructions',async()=>{
 const bodies=[],native=provider({fetchImpl:async(_url,options)=>{bodies.push(JSON.parse(options.body));return audio();}}),prefix='朗读参考文字';for(const prompt of ['正文',prefix+'\n正文'])await native.submit({...request,prompt,inputs:[{type:'text',text:prefix}]});assert.equal(bodies[0].text,prefix+'\n正文');assert.equal(bodies[1].text,bodies[0].text);
});
test('configured WAV output keeps exact PCM bytes and sampling rather than renaming MP3',async()=>{
 const bytes=wave(),native=provider({modelMap:{eleven_v3:{kind:'audio.generate',model:'eleven_v3',outputFormat:'wav_24000'}},fetchImpl:async(url)=>{assert.equal(new URL(url).searchParams.get('output_format'),'wav_24000');return audio(bytes,'audio/wav');}});const result=await native.submit(request);assert.deepEqual(result.outputs,[{type:'audio',url:'data:audio/wav;base64,'+bytes.toString('base64'),duration:.1}]);
 for(const value of [audio(wave({codec:65535}),'audio/wav'),audio(wave({sampleRate:48000}),'audio/wav'),audio(mp3)]){const invalid=provider({modelMap:{eleven_v3:{kind:'audio.generate',model:'eleven_v3',outputFormat:'wav_24000'}},fetchImpl:async()=>value});await assert.rejects(invalid.submit(request),{code:'unknown'});}
});
test('MP3 sampling and bitrate match the configured official output format on every frame',async()=>{
 const wrongSampling=require('node:fs').readFileSync(path.join(__dirname,'fixtures/speech-tone.mp3')),wrongBitrate=Buffer.alloc(208*2);for(const offset of [0,208])wrongBitrate.writeUInt32BE(0xfffb5000,offset);const mixedRate=Buffer.alloc(417+384);mixedRate.writeUInt32BE(0xfffb9000,0);mixedRate.writeUInt32BE(0xfffb9400,417);const mixedBitrate=Buffer.alloc(417+208);mixedBitrate.writeUInt32BE(0xfffb9000,0);mixedBitrate.writeUInt32BE(0xfffb5000,417);
 for(const bytes of [wrongSampling,wrongBitrate,mixedRate,mixedBitrate]){const native=provider({fetchImpl:async()=>audio(bytes)});await assert.rejects(native.submit(params({sample_rate:44100})),{code:'unknown'});}
});
test('otherwise valid MP3 metadata cannot echo the server credential',async()=>{
 const start=mp3.toString('ascii',0,3)==='ID3'?10+mp3[6]*2097152+mp3[7]*16384+mp3[8]*128+mp3[9]:0,tag=Buffer.alloc(10+key.length);tag.write('ID3');tag[3]=3;tag[9]=key.length;tag.write(key,10);const bytes=Buffer.concat([tag,mp3.subarray(start)]);const native=provider({fetchImpl:async()=>audio(bytes)});await assert.rejects(native.submit(request),e=>e.code==='unknown'&&!e.message.includes(key));
});
test('malformed, oversized and credential echo output remains unknown with zero retry',async()=>{
 const keyed=Buffer.concat([mp3.subarray(0,0),Buffer.from('ID3'+key)]);const cases=[()=>audio(Buffer.from('ID3this is not audio')),()=>audio(mp3.subarray(0,mp3.length-7)),()=>audio(Buffer.alloc(0)),()=>audio(mp3,'application/json'),()=>audio(mp3,'audio/mpeg',{'content-length':String(mp3.length+1)}),()=>audio(mp3,'audio/mpeg',{'content-length':String(MAX_AUDIO_BYTES+1)}),()=>audio(mp3,'audio/mpeg',{'content-encoding':'gzip'}),()=>audio(keyed),()=>new Response('private '+key,{status:429}),()=>new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(MAX_AUDIO_BYTES+1));controller.close();}}),{headers:{'content-type':'audio/mpeg'}})];
 for(const make of cases){let calls=0;const native=provider({fetchImpl:async()=>{calls++;return make();}});await assert.rejects(native.submit(request),e=>e.code==='unknown'&&!e.message.includes(key));assert.equal(calls,1);}
});
test('redirect is rejected by real HTTP fetch before any destination call',async t=>{
 let secondary=0;const target=http.createServer((_req,res)=>{secondary++;res.end(mp3);});await new Promise(resolve=>target.listen(0,'127.0.0.1',resolve));const source=http.createServer((_req,res)=>{res.writeHead(307,{Location:`http://127.0.0.1:${target.address().port}/audio`});res.end(key);});await new Promise(resolve=>source.listen(0,'127.0.0.1',resolve));t.after(()=>{source.closeAllConnections();target.closeAllConnections();source.close();target.close();});const native=provider({baseUrl:`http://127.0.0.1:${source.address().port}`,fetchImpl:fetch});await assert.rejects(native.submit(request),{code:'unknown'});assert.equal(secondary,0);
});
test('abort, timeout and late response cannot become success or dispatch another POST',async()=>{
 const before=new AbortController();before.abort(Error('cancel before'));await assert.rejects(provider({fetchImpl:()=>assert.fail()}).submit(request,{signal:before.signal}),/cancel before/);
 let started,readerCancelled=false;const begin=new Promise(resolve=>{started=resolve;}),abort=new AbortController(),native=provider({fetchImpl:async()=>new Response(new ReadableStream({start(){started();},cancel(){readerCancelled=true;}}),{headers:{'content-type':'audio/mpeg'}})});const pending=native.submit(request,{signal:abort.signal});await begin;await new Promise(resolve=>setImmediate(resolve));abort.abort(Error('cancel during'));await assert.rejects(pending,/cancel during/);assert.equal(readerCancelled,true);
 let release,calls=0,lateCancelled=false;const timeout=provider({timeoutMs:10,fetchImpl:()=>{calls++;return new Promise(resolve=>{release=resolve;});}});await assert.rejects(timeout.submit(request),{code:'unknown'});release(new Response(new ReadableStream({cancel(){lateCancelled=true;}}),{headers:{'content-type':'audio/mpeg'}}));await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,1);assert.equal(lateCancelled,true);
});
test('routed default native map works and another provider never receives Eleven aliases',async()=>{
 const routing=readGenerationRoutingConfig({GENERATION_PROVIDERS:JSON.stringify({eleven:{protocol:'elevenlabs-native',apiKeyEnv:'ELEVENLABS_API_KEY'},other:{protocol:'tasks-v1',apiKeyEnv:'OTHER_KEY',baseUrl:'https://other-provider.test'}}),GENERATION_ROUTES:JSON.stringify({'audio.generate':{models:{eleven_v3:'eleven'},default:'other'}}),ELEVENLABS_API_KEY:key,OTHER_KEY:'synthetic-other-key'}),urls=[];
 const router=createGenerationRouter({...routing,fetchImpl:async url=>{urls.push(String(url));return audio();}});assert.equal(router.configured,true);assert.equal(router.metadata.providers.eleven.capabilities.models.eleven_v3.kind,'audio.generate');assert.equal((await router.submit(request)).status,'succeeded');assert.equal(urls.length,1);assert.equal(new URL(urls[0]).hostname,'api.elevenlabs.io');
 const empty=createGenerationRouter({providers:{eleven:{protocol:'elevenlabs-native',apiKey:key,modelMap:{}}},routes:{'audio.generate':{models:{eleven_v3:'eleven'}}},fetchImpl:()=>assert.fail()});assert.equal(empty.configured,false);assert.throws(()=>empty.prepare(request),{code:'configuration_required'});
});
test('production gateway archives actual audio, restores it and never resubmits unknown receipts',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'elevenlabs-native-gateway-')),directory=path.join(root,'tasks');let calls=0;let gateway=createGenerationGateway({directory,protocol:'elevenlabs-native',apiKey:key,fetchImpl:async()=>{calls++;return audio();}});await gateway.ready;t.after(async()=>{await gateway.close();await fs.rm(root,{recursive:true,force:true});});let value;const json=(_res,_status,result)=>{value=result;},body=async()=>request;
 const settle=async taskId=>{for(let i=0;i<100;i++){await gateway.handle({method:'GET',headers:{}},{},'/api/generation/tasks/'+taskId,{json,body});if(!['queued','running'].includes(value.status))return;await new Promise(resolve=>setTimeout(resolve,5));}assert.fail('local native task did not settle');};
 await gateway.handle({method:'POST',headers:{'idempotency-key':'elevenlabs-native-success'}},{},'/api/generation/tasks',{json,body});const id=value.id;await settle(id);assert.equal(value.status,'succeeded');assert.match(value.outputs[0].url,/^\/api\/generation\/media\/[a-f0-9-]{36}$/);const mediaUrl=value.outputs[0].url,resourceId=mediaUrl.split('/').at(-1);assert.deepEqual(await fs.readFile(path.join(root,'tasks-media',resourceId+'.bin')),mp3);assert.equal(calls,1);
 const record=await fs.readFile(path.join(directory,id+'.json'),'utf8');assert.equal(record.includes(key),false);await gateway.close();gateway=createGenerationGateway({directory,protocol:'elevenlabs-native',apiKey:'rotated-key',fetchImpl:()=>assert.fail('no regeneration after restart')});await gateway.ready;await gateway.handle({method:'GET',headers:{}},{},'/api/generation/tasks/by-key/elevenlabs-native-success',{json,body});assert.equal(value.status,'succeeded');assert.equal(value.outputs[0].url,mediaUrl);assert.equal(calls,1);
 await gateway.close();gateway=createGenerationGateway({directory,protocol:'elevenlabs-native',apiKey:key,fetchImpl:async()=>{calls++;throw Error('connection lost after POST');}});await gateway.ready;await gateway.handle({method:'POST',headers:{'idempotency-key':'elevenlabs-native-unknown'}},{},'/api/generation/tasks',{json,body});const unknownId=value.id;await settle(unknownId);assert.equal(value.status,'unknown');assert.equal(value.outputs,undefined);assert.equal(value.recovery.pollable,false);await gateway.close();gateway=createGenerationGateway({directory,protocol:'elevenlabs-native',apiKey:key,fetchImpl:()=>assert.fail('unknown receipt must never retry')});await gateway.ready;await gateway.handle({method:'POST',headers:{'idempotency-key':'elevenlabs-native-unknown'}},{},'/api/generation/tasks',{json,body});assert.equal(value.id,unknownId);assert.equal(value.status,'unknown');assert.equal(calls,2);
});
test('durable cancel retains original receipt without accepting late audio',async t=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'elevenlabs-native-cancel-'));let started,release;const begin=new Promise(resolve=>{started=resolve;}),native=provider({fetchImpl:()=>{started();return new Promise(resolve=>{release=resolve;});}}),service=createDurableGenerationService({directory,provider:native});await service.ready;t.after(async()=>{await service.close();await fs.rm(directory,{recursive:true,force:true});});const first=await service.submit(request,{idempotencyKey:'elevenlabs-native-cancel'});await begin;await service.cancel(first.id);release(audio());const final=await service.get(first.id);assert.equal(final.status,'cancelled');assert.equal(final.outputs,undefined);assert.equal((await service.submit(request,{idempotencyKey:'elevenlabs-native-cancel'})).id,first.id);
});
