'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),{gzipSync,gunzipSync}=require('node:zlib');
const {createGenerationGateway}=require('../server/generation.cjs');
const {createGenerationRouter}=require('../server/generation-router.cjs');
const {createGenerationMediaDownloader}=require('../server/generation-media-download.cjs');
const {createGenerationMediaStore}=require('../server/generation-media-store.cjs');
const {createGenerationMediaMaterializer}=require('../server/generation-media-materializer.cjs');
const alias='worldlabs-marble-1.1',key='synthetic-marble-private-key',modelMap={[alias]:{kind:'world.generate',model:'marble-1.1',displayModel:'Marble 1.1',modes:['TEXT_TO_WORLD']}},operationId='marble_operation_original',worldId='marble_world_original';
const request={kind:'world.generate',prompt:'本机合同测试庭院',inputs:[],parameters:{model:alias,provider:'worldlabs',modelType:'TEXT_TO_WORLD',outputType:'world',representation:'gaussianSplat',isPano:false,count:1,marbleParams:{splatResolution:'500k'}}};
const response=value=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});
const accepted=()=>({operation_id:operationId,done:false,response:null,error:null});
const sourceUrls={selected:'https://cdn.worldlabs.ai/selected_500k.spz?signature=fixture-only',low:'https://cdn.worldlabs.ai/low_100k.spz?signature=fixture-only',full:'https://cdn.worldlabs.ai/full.spz?signature=fixture-only',mesh:'https://cdn.worldlabs.ai/collider.glb?signature=fixture-only',image:'https://cdn.worldlabs.ai/pano.png?signature=fixture-only'};
function complete(){return {operation_id:operationId,done:true,error:null,metadata:{world_id:worldId},response:{world_id:worldId,model:'marble-1.1',world_marble_url:'https://marble.worldlabs.ai/world/'+worldId+'?view=fixture#preview',world_prompt:{type:'text'},assets:{thumbnail_url:sourceUrls.image,splats:{spz_urls:{'500k':sourceUrls.selected,'100k':sourceUrls.low,full_res:sourceUrls.full},semantics_metadata:{metric_scale_factor:1.25,ground_plane_offset:-.5}},mesh:{collider_mesh_url:sourceUrls.mesh,full_res_mesh_url:sourceUrls.mesh},imagery:{pano_url:sourceUrls.image}}}};}
function apiTransport({done=true,corrupt=false}={},calls=[]){return async(url,options)=>{calls.push({url:String(url),method:options.method});assert.equal(options.headers['WLT-Api-Key'],key);assert.equal(options.redirect,'error');if(options.method==='POST'){assert.equal(String(url),'https://api.worldlabs.ai/marble/v1/worlds:generate');assert.deepEqual(JSON.parse(options.body),{model:'marble-1.1',world_prompt:{type:'text',text_prompt:request.prompt}});return response(accepted());}assert.equal(String(url),'https://api.worldlabs.ai/marble/v1/operations/'+operationId);const result=done?complete():accepted();if(corrupt)result.operation_id='another_operation';return response(result);};}
function spz(){const expanded=Buffer.alloc(35);expanded.write('NGSP');expanded.writeUInt32LE(2,4);expanded.writeUInt32LE(1,8);expanded[13]=12;return gzipSync(expanded);}
function glb(){const bytes=Buffer.alloc(24);bytes.write('glTF');bytes.writeUInt32LE(2,4);bytes.writeUInt32LE(24,8);bytes.writeUInt32LE(4,12);bytes.write('JSON',16);bytes.write('{}  ',20);return bytes;}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/sr8AAAAASUVORK5CYII=','base64'),spzBytes=spz(),glbBytes=glb();
const resources=new Map([[sourceUrls.selected,{bytes:spzBytes,mime:'application/octet-stream'}],[sourceUrls.low,{bytes:spzBytes,mime:'application/octet-stream'}],[sourceUrls.full,{bytes:spzBytes,mime:'application/octet-stream'}],[sourceUrls.mesh,{bytes:glbBytes,mime:'model/gltf-binary'}],[sourceUrls.image,{bytes:png,mime:'image/png'}]]);
function mediaTransport(calls,{invalidSpz=false}={}){return(url,options,callback)=>{
 const expected=resources.get(url.href);assert.ok(expected,'only actual server-owned fixture descriptors may be downloaded');const bytes=invalidSpz&&url.pathname.endsWith('.spz')?gzipSync(Buffer.from('not a Gaussian Splat')):expected.bytes;
 const outgoing=new EventEmitter();outgoing.destroy=()=>{};outgoing.end=()=>{calls.push({url:url.href,headers:options.headers});assert.equal(options.headers['WLT-Api-Key'],undefined);assert.equal(options.headers.Authorization,undefined);options.lookup(url.hostname,{all:true},(error,answers)=>{assert.ifError(error);assert.deepEqual(answers,[{address:'93.184.216.34',family:4}]);});queueMicrotask(()=>{const incoming=new PassThrough();incoming.socket={remoteAddress:'93.184.216.34'};incoming.statusCode=200;incoming.headers={'content-type':expected.mime,'content-length':String(bytes.length)};callback(incoming);incoming.end(bytes);});};return outgoing;
 };}
const single={protocol:'marble-native',apiKey:key,modelMap};
const routed={providers:{original:{protocol:'marble-native',apiKey:key,modelMap}},routes:{'world.generate':{models:{[alias]:'original'}}}};
async function integration(t,config,transport,mediaOptions={}){
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'marble-native-integration-')),mediaCalls=[];let gateway,store;const open=async(next=config,nextTransport=transport)=>{
  store=createGenerationMediaStore({directory:path.join(directory,'media'),maxBytes:256*1024*1024});const downloader=createGenerationMediaDownloader({lookup:async()=>[{address:'93.184.216.34',family:4}],requestImpl:mediaTransport(mediaCalls,mediaOptions)}),materializer=createGenerationMediaMaterializer({store,download:downloader.download});
  gateway=createGenerationGateway({...next,directory:path.join(directory,'tasks'),mediaStore:store,mediaMaterializer:materializer,fetchImpl:nextTransport});await gateway.ready;return gateway;
 };await open();
 const json=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));},body=async req=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');};
 const server=http.createServer(async(req,res)=>{try{await gateway.handle(req,res,new URL(req.url,'http://local').pathname,{json,body});}catch(error){json(res,400,{code:error.code,error:'integration fixture request failed'});}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
 t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await gateway.close();await fs.rm(directory,{recursive:true,force:true});});
 async function get(url){const result=await fetch(origin+url);assert.equal(result.status,200);return result.json();}
 async function submit(idempotencyKey){const result=await fetch(origin+'/api/generation/tasks',{method:'POST',headers:{'content-type':'application/json','idempotency-key':idempotencyKey},body:JSON.stringify(request)});assert.equal(result.status,202);return result.json();}
 async function settle(id){for(let i=0;i<100;i++){const result=await get('/api/generation/tasks/'+id);if(!['queued','running'].includes(result.status))return result;await new Promise(resolve=>setTimeout(resolve,5));}assert.fail('local Marble fixture did not settle');}
 async function reopen(next,nextTransport){await gateway.close();return open(next,nextTransport);}
 return {origin,directory,mediaCalls,get,submit,settle,reopen,get store(){return store;}};
}
test('Marble registration without a Key reports unavailable and sends zero generation or media requests',async t=>{
 for(const config of [{protocol:'marble-native',modelMap},{providers:{original:{protocol:'marble-native',modelMap}},routes:routed.routes}]){let calls=0;const local=await integration(t,config,()=>{calls++;assert.fail('no Key cannot dispatch');});const metadata=await local.get('/api/generation/config');assert.equal(metadata.configured,false);const created=await local.submit('marble-no-key-'+(config.protocol?'single':'routed')),job=await local.settle(created.id);assert.equal(job.status,'configuration_required');assert.equal(job.outputs,undefined);assert.equal(calls,0);assert.equal(local.mediaCalls.length,0);}
});
test('single and routed readiness require the exact Marble alias and operation',async t=>{
 const {providerConfigured,resolveProviderConfiguration,configurationReadiness}=await import('../src/features/node-composer/provider-configuration.mjs');
 for(const config of [single,routed]){const local=await integration(t,config,()=>assert.fail('readiness is read-only')),metadata=await local.get('/api/generation/config');assert.equal(metadata.configured,true);assert.equal(providerConfigured(metadata,request),true);assert.equal(providerConfigured(metadata,{...request,parameters:{model:'unconfigured-world-alias'}}),false);assert.equal(providerConfigured(metadata,{...request,kind:'model.generate'}),false);const selected=resolveProviderConfiguration(metadata,request);assert.equal(selected.protocol,'marble-native');assert.equal(selected.capabilities.models[alias].label,'Marble 1.1');assert.deepEqual(selected.capabilities.worldGeneration[alias].modes,['TEXT_TO_WORLD']);if(config.providers)assert.equal(configurationReadiness(metadata).find(item=>item.provider==='original').configured,true);}
});
test('actual router encodes the original operation/model/mode/LOD and rejects mismatched poll receipts',async()=>{
 const calls=[],router=createGenerationRouter({...routed,fetchImpl:apiTransport({},calls)}),task=await router.submit(request);assert.equal(task.status,'queued');assert.match(task.id,/^rg1\./);const [providerId,stamp,raw]=JSON.parse(Buffer.from(task.id.slice(4),'base64url').toString('utf8'));assert.equal(providerId,'original');assert.match(stamp,/^[a-f0-9]{64}$/);assert.deepEqual(JSON.parse(Buffer.from(raw.slice(4),'base64url').toString('utf8')),['marble-1.1','TEXT_TO_WORLD','500k',operationId]);const result=await router.poll(task.id);assert.equal(result.id,task.id);assert.equal(result.outputs[0].world.worldId,worldId);assert.equal(result.outputs[0].world.splatResolution,'500k');assert.deepEqual(calls.map(call=>call.method),['POST','GET']);
 const mismatched=createGenerationRouter({...routed,fetchImpl:apiTransport({corrupt:true},calls)});await assert.rejects(mismatched.poll(task.id),{code:'provider_identity_mismatch'});assert.equal(calls.filter(call=>call.method==='POST').length,1);
});
test('production single/routed gateway validates and archives real SPZ plus nested world metadata and auxiliary bytes',async t=>{
 for(const config of [single,routed]){const calls=[],local=await integration(t,config,apiTransport({},calls)),created=await local.submit('marble-real-world-'+(config.protocol?'single':'routed')),job=await local.settle(created.id);assert.equal(job.status,'succeeded');assert.equal(job.providerStatus,'succeeded');assert.equal(job.localization.state,'ready');const output=job.outputs[0];assert.equal(output.format,'spz');assert.equal(output.representation,'gaussianSplat');assert.equal(output.sourceFileId,worldId);assert.equal(output.world.worldId,worldId);assert.equal(output.world.model,'marble-1.1');assert.equal(output.world.coordinateSystem,'marble_raw_opencv');assert.deepEqual(output.world.assets.splats.semanticsMetadata,{metricScaleFactor:1.25,groundPlaneOffset:-.5});assert.equal(output.world.marbleUrl,'https://marble.worldlabs.ai/world/'+worldId);assert.equal(output.world.assets.splats.spzUrls['500k'],output.url);assert.equal(output.world.assets.mesh.colliderMeshUrl,output.world.assets.mesh.fullResMeshUrl);assert.equal(output.world.assets.imagery.panoUrl,output.poster);
  const localUrls=[...Object.values(output.world.assets.splats.spzUrls),output.world.assets.mesh.colliderMeshUrl,output.poster];for(const url of localUrls)assert.match(url,/^\/api\/generation\/media\/[a-f0-9-]{36}$/);assert.equal(new Set(localUrls).size,5);assert.equal(JSON.stringify(job).includes('cdn.worldlabs.ai'),false);assert.equal(JSON.stringify(job).includes('signature='),false);assert.equal(JSON.stringify(job).includes(key),false);assert.equal(local.mediaCalls.length,5);
  const media=await fetch(local.origin+output.url);assert.equal(media.status,200);const savedBytes=Buffer.from(await media.arrayBuffer());assert.deepEqual(savedBytes,spzBytes);assert.equal(gunzipSync(savedBytes).toString('ascii',0,4),'NGSP');const manifest=await local.store.info(output.url.split('/').at(-1),{taskId:created.id});assert.equal(manifest.format,'spz');assert.equal(manifest.bytes,spzBytes.length);const mesh=await fetch(local.origin+output.world.assets.mesh.colliderMeshUrl);assert.deepEqual(Buffer.from(await mesh.arrayBuffer()),glbBytes);const image=await fetch(local.origin+output.poster);assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);
  const record=JSON.parse(await fs.readFile(path.join(local.directory,'tasks',created.id+'.json'),'utf8'));assert.ok(record.providerTaskId);assert.equal(record.outputs[0].world.worldId,worldId);assert.equal(record.providerResult.outputs[0].url,sourceUrls.selected);assert.equal(JSON.stringify(record).includes(key),false);assert.equal(calls.filter(call=>call.method==='POST').length,1);
  await local.reopen(config,()=>assert.fail('success must restore local bytes without API request'));const restored=await local.get('/api/generation/tasks/by-key/marble-real-world-'+(config.protocol?'single':'routed'));assert.equal(restored.status,'succeeded');assert.deepEqual(restored.outputs,job.outputs);assert.deepEqual(Buffer.from(await(await fetch(local.origin+output.url)).arrayBuffer()),spzBytes);assert.equal(calls.filter(call=>call.method==='POST').length,1);
 }
});
test('route change recovers original Marble operation through its provider identity without replaying POST',async t=>{
 const calls=[],local=await integration(t,routed,apiTransport({done:false},calls)),created=await local.submit('marble-original-route-recovery');let running=await local.get('/api/generation/tasks/'+created.id);for(let i=0;i<10&&!running.recovery?.pollable;i++)running=await local.get('/api/generation/tasks/'+created.id);assert.equal(running.status,'running');assert.equal(running.recovery.pollable,true);
 const changed={providers:{...routed.providers,replacement:{protocol:'tasks-v1',apiKey:'synthetic-unrelated-key',baseUrl:'https://unrelated-world-provider.test'}},routes:{'world.generate':{models:{[alias]:'replacement'}}}};
 await local.reopen(changed,async(url,options)=>{assert.equal(new URL(url).hostname,'api.worldlabs.ai','original identity must not call the replacement route');return apiTransport({},calls)(url,options);});const restored=await local.get('/api/generation/tasks/by-key/marble-original-route-recovery');assert.equal(restored.status,'succeeded');assert.equal(restored.id,created.id);assert.equal(restored.outputs[0].world.worldId,worldId);assert.equal(calls.filter(call=>call.method==='POST').length,1);assert.equal((await local.submit('marble-original-route-recovery')).id,created.id);assert.equal(calls.filter(call=>call.method==='POST').length,1);
});
test('mismatched operation stays unknown, with no partial local world or second POST',async t=>{
 const calls=[],local=await integration(t,routed,apiTransport({corrupt:true},calls)),created=await local.submit('marble-mismatched-operation'),job=await local.settle(created.id);assert.equal(job.status,'unknown');assert.equal(job.outputs,undefined);assert.equal(local.mediaCalls.length,0);assert.equal((await local.submit('marble-mismatched-operation')).id,created.id);assert.equal(calls.filter(call=>call.method==='POST').length,1);
});
test('invalid gzip SPZ remains a localization failure and never becomes a successful world',async t=>{
 const calls=[],local=await integration(t,routed,apiTransport({},calls),{invalidSpz:true}),created=await local.submit('marble-invalid-spz-bytes'),job=await local.settle(created.id);assert.equal(job.status,'unknown');assert.equal(job.providerStatus,'succeeded');assert.equal(job.localization.state,'failed');assert.equal(job.outputs,undefined);assert.equal(job.localization.errorCode,'media_format_invalid');assert.equal(calls.filter(call=>call.method==='POST').length,1);const records=await fs.readdir(path.join(local.directory,'media'));for(const filename of records.filter(name=>name.endsWith('.json'))){const record=JSON.parse(await fs.readFile(path.join(local.directory,'media',filename),'utf8'));assert.notEqual(record.format,'spz');}
});
