const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createRequire}=require('node:module'),fabricRequire=createRequire(require.resolve('fabric'));
const canvasPath=fabricRequire.resolve('canvas'),previousCanvas=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(previousCanvas)require.cache[canvasPath]=previousCanvas;else delete require.cache[canvasPath];
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};},tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture({ready=Promise.resolve(),use=async()=>{},items=[]}={}){
 const dom=new JSDOM('<body><nav class="side-tools"><button aria-label="素材库"></button><button aria-label="模板"></button><button aria-label="历史"></button></nav><button class="agent"></button><button class="avatar"></button><button class="share"></button><div id="canvas"></div><input id="outside"></body>',{url:'http://local.test'}),window=dom.window,document=window.document,reads=[],inputs=[],stored=new Map([['tapnow-template-intro','dismissed'],['tapnow-library',JSON.stringify(items)]]),notifications=[];
 const template={id:'local-template',name:'本地模板',image:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',graph:{nodes:[],edges:[]}},app={notify:e=>notifications.push(e),getState:()=>({nodes:[],selected:[],edges:[],view:{x:0,y:0,scale:1}}),insertAsset(){},preview(){}};
 const create=document.createElement.bind(document);document.createElement=tag=>{const e=create(tag);if(tag==='input'){inputs.push(e);if(e.type==='file')e.click=()=>{};}return e;};
 window.HTMLDialogElement.prototype.showModal=function(){this.open=true;this.querySelector('button,input')?.focus();};window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'));};window.HTMLInputElement.prototype.click=function(){if(this.type!=='file')window.HTMLElement.prototype.click.call(this);};
 class FileReader{readAsDataURL(file){this.file=file;reads.push(this);}}
 let record,writeFailure=null;const iconContext={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../ui-icons.js'),'utf8'),iconContext);
 Object.assign(window,{CanvasStore:{async readRecord(){return record;},async writeRecord(_key,value){if(writeFailure)throw writeFailure;record={...structuredClone(value),storageRevision:(record?.storageRevision||0)+1};return {storageRevision:record.storageRevision};}},LocalAssets:{put(file){const pending=deferred();pending.file=file;reads.push(pending);return pending.promise;}},CanvasApp:app,UI_ICONS:iconContext.window.UI_ICONS,SIDEBAR_DATA:{template:[template],history:[]},TemplateAPI:{ready,list:()=>[template],use},ReplicaUI:{createPresenceMotion(element){return{enter(){},exit(){element.inert=true;element.setAttribute('aria-hidden','true');},destroy(){}};}}});
 vm.runInNewContext(fs.readFileSync(require.resolve('../sidebars.js'),'utf8').replace(/import\([^)]*\)/g,'(new Promise(()=>{}))'),{window,document,localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)},crypto:{randomUUID:()=> 'asset-'+reads.length},innerWidth:1100,innerHeight:800,FileReader,console,structuredClone,CustomEvent:window.CustomEvent});
 const trigger=name=>document.querySelector('.side-tools button[aria-label="'+name+'"]'),open=name=>{trigger(name).focus();trigger(name).click();return document.querySelector('#left-panel-'+(name==='素材库'?'library':'templates'));},pick=async()=>{document.querySelector('#left-panel-library .panel-plus').click();Array.from(document.querySelector('.context-popup').querySelectorAll('button')).find(b=>b.textContent==='上传图片').click();const input=inputs.at(-1);Object.defineProperty(input,'files',{value:[{name:'选择的图片.png',type:'image/png'}],configurable:true});const operation=input.onchange();await tick();const pending=reads.at(-1);pending.operation=operation;return pending;};
 return{dom,window,document,stored,setWriteFailure:error=>writeFailure=error,get record(){return record;},notifications,trigger,open,pick,reads,close(){window.dispatchEvent(new window.Event('pagehide'));dom.window.close();}};
}
test('late chosen-file upload persists once but cannot reopen a closed drawer or replace a new panel',async()=>{
 for(const target of ['closed','templates','reopened']){const f=fixture();try{await f.window.CanvasLibrary.ready();const origin=f.open('素材库'),reader=await f.pick();origin.querySelector('.back-panel').click();assert.equal(origin.isConnected,true);assert.equal(origin.inert,true);let next=null;if(target==='templates')next=f.open('模板');if(target==='reopened')next=f.open('素材库');const focus=f.document.activeElement;reader.result='asset:chosen';reader.resolve(reader.result);await reader.operation;assert.equal(f.record.items.length,1);assert.equal(f.window.CanvasLibrary.items[0].image,reader.result);assert.equal(f.document.activeElement,focus);assert.equal(f.document.querySelector('#left-panel-library'),target==='reopened'?next:null);if(target==='templates')assert.equal(f.document.querySelector('#left-panel-templates'),next);}finally{f.close();}}
});
test('same-owner uploads refresh the current folder without recreating drawer or losing search focus',async()=>{
 const f=fixture();try{await f.window.CanvasLibrary.ready();const origin=f.open('素材库');Array.from(origin.querySelectorAll('.folder-row')).find(b=>b.textContent.includes('Others')).click();const reader=await f.pick(),search=origin.querySelector('input');search.value='选择';search.dispatchEvent(new f.window.Event('input'));search.focus();reader.result='asset:chosen';reader.resolve(reader.result);await reader.operation;assert.equal(f.document.querySelector('#left-panel-library'),origin);assert.equal(f.document.activeElement,search);assert.equal(search.value,'选择');assert.equal(f.window.CanvasLibrary.items[0].folder,'Others');assert.match(origin.textContent,/选择的图片/);}finally{f.close();}
});
test('template use is single-flight and its late success cannot close a replacement panel',async()=>{
 const pending=deferred();let calls=0;const f=fixture({use:()=>{calls++;return pending.promise;}});try{f.open('模板');const card=f.document.querySelector('.template-card');card.focus();card.click();const dialog=f.document.querySelector('dialog'),use=Array.from(dialog.querySelectorAll('button')).find(b=>b.textContent==='使用模板');const operation=use.onclick();use.onclick();assert.equal(calls,1);assert.equal(use.disabled,true);assert.equal(use.getAttribute('aria-busy'),'true');dialog.close();const replacement=f.open('素材库'),focus=f.document.activeElement;pending.resolve();await operation;assert.equal(f.document.querySelector('#left-panel-library'),replacement);assert.equal(f.document.activeElement,focus);assert.equal(replacement.inert,undefined);}finally{f.close();}
});
test('template list updates retain card focus and modal close resolves the rebuilt source card',async()=>{
 const f=fixture();try{f.open('模板');let card=f.document.querySelector('.template-card');card.focus();f.document.dispatchEvent(new f.window.Event('templates:changed'));assert.notEqual(f.document.activeElement,card);assert.equal(f.document.activeElement.dataset.templateId,'local-template');card=f.document.activeElement;card.click();const dialog=f.document.querySelector('dialog');f.document.dispatchEvent(new f.window.Event('templates:changed'));assert.equal(card.isConnected,false);dialog.close();assert.equal(f.document.activeElement.dataset.templateId,'local-template');assert.equal(f.document.activeElement.isConnected,true);}finally{f.close();}
});
test('template readiness cannot render a closed owner or report an error on a newer panel',async()=>{
 for(const fail of [false,true]){const pending=deferred(),f=fixture({ready:pending.promise});try{const old=f.open('模板'),before=old.querySelector('.panel-scroll').innerHTML;f.trigger('模板').click();assert.equal(old.isConnected,false);const next=f.open('素材库');fail?pending.reject(Error('storage denied')):pending.resolve();await tick();assert.equal(old.querySelector('.panel-scroll').innerHTML,before);assert.equal(f.document.querySelector('#left-panel-library'),next);assert.deepEqual(f.notifications,[]);}finally{f.close();}}
});
test('a personal template readiness failure preserves public templates and shows a visible error in my templates',async()=>{
 const pending=deferred(),f=fixture({ready:pending.promise});try{const panel=f.open('模板');pending.reject(Error('storage denied'));await tick();assert.ok(panel.querySelector('.template-card'));Array.from(panel.querySelectorAll('.template-tabs button')).find(button=>button.textContent==='我的模板').click();assert.match(panel.textContent,/模板读取失败：storage denied/);}finally{f.close();}
});
function templateFixture(){
 const f=fixture(),{window,document}=f,pending=deferred();let request;const context={window,document,console,structuredClone,crypto:{randomUUID:()=> 't'},innerWidth:1100,innerHeight:800,CustomEvent:window.CustomEvent,Option:window.Option,indexedDB:{open(){request={};return request;}}};window.CanvasProjects={id:()=> 'project-a',registerNavigationGuard(){}};window.TemplatesCore={capture:()=>({nodes:[]})};
 vm.runInNewContext(fs.readFileSync(require.resolve('../templates-ui.js'),'utf8').replace(/import\([^)]*\)/g,'(new Promise(()=>{}))'),context);
 request.result={transaction(){const tx={objectStore:()=>({getAll:()=>({result:[]})})};pending.promise.then(()=>tx.oncomplete());return tx;}};request.onsuccess();
 return{...f,pending};
}
test('delayed template-create readiness cannot open after explicit close, outside focus, blur or project change',async()=>{
 for(const kind of ['close','focus','blur','project']){const f=templateFixture();try{const anchor=f.trigger('模板');anchor.focus();const opening=f.window.TemplateAPI.open('group',anchor);if(kind==='close')f.window.TemplateAPI.close();if(kind==='focus')f.document.querySelector('#outside').focus();if(kind==='blur')f.window.dispatchEvent(new f.window.Event('blur'));if(kind==='project')f.window.CanvasProjects.id=()=> 'project-b';f.pending.resolve();await opening;assert.equal(f.document.querySelector('.template-create'),null,kind);}finally{f.close();}}
});

test('active library upload refresh preserves the same existing asset tile focus',async()=>{
 const f=fixture({items:[{id:'existing',name:'现有素材',type:'image',folder:'Others',image:'data:image/png;base64,existing'}]});try{await f.window.CanvasLibrary.ready();const panel=f.open('素材库');Array.from(panel.querySelectorAll('.folder-row')).find(b=>b.textContent.includes('Others')).click();const reader=await f.pick(),tile=panel.querySelector('.asset-tile');tile.focus();reader.result='asset:chosen';reader.resolve(reader.result);await reader.operation;assert.notEqual(f.document.activeElement,tile);assert.equal(f.document.activeElement.dataset.assetId,'existing');assert.equal(f.document.activeElement.isConnected,true);}finally{f.close();}
});

test('template preview closes to the active tab if its source card disappeared',()=>{
 const f=fixture();try{const panel=f.open('模板'),card=f.document.querySelector('.template-card');card.focus();card.click();const dialog=f.document.querySelector('dialog');f.window.SIDEBAR_DATA.template=[];f.document.dispatchEvent(new f.window.Event('templates:changed'));dialog.close();assert.equal(f.document.activeElement,panel.querySelector('.template-tabs .chosen'));assert.equal(f.document.activeElement.isConnected,true);}finally{f.close();}
});

test('personal library and template chrome reuse existing SVG resources with readable names',async()=>{
 const f=fixture();try{await f.window.CanvasLibrary.ready();const canonical=source=>{const node=f.document.createElement('div');node.innerHTML=source;return node.innerHTML;},panel=f.open('素材库');for(const [label,name]of [['AI 角色','user'],['添加素材','plus'],['收藏','star'],['关闭素材库','arrowLeft']]){const b=panel.querySelector('[aria-label="'+label+'"]');assert.ok(b);assert.equal(b.querySelector('[aria-hidden="true"]').innerHTML,canonical(f.window.UI_ICONS[name]));assert.ok(b.querySelector('svg'));}assert.ok(panel.querySelector('.folder-more svg'));assert.doesNotMatch(panel.textContent,/♙|★|···|‹/);panel.querySelector('[aria-label="关闭素材库"]').click();const templates=f.open('模板'),expand=templates.querySelector('[aria-label="浏览全部模板"]');assert.equal(expand.querySelector('[aria-hidden="true"]').innerHTML,canonical(f.window.UI_ICONS.expand));templates.querySelector('.template-card').click();assert.ok(f.document.querySelector('[aria-label="关闭模板预览"] svg'));assert.doesNotMatch(templates.textContent,/⤢/);}finally{f.close();}
});

test('presence restores CSSOM pointer-events priority after closing and reopening',()=>{
 const f=fixture();try{const context={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(require.resolve('../component-library/ui.js'),'utf8'),context);const element=f.document.createElement('section');element.style.setProperty('pointer-events','auto','important');const motion=context.module.exports.createPresenceMotion(element);motion.enter();motion.exit();assert.equal(element.style.pointerEvents,'none');assert.equal(element.style.getPropertyPriority('pointer-events'),'important');motion.enter();assert.equal(element.style.pointerEvents,'auto');assert.equal(element.style.getPropertyPriority('pointer-events'),'important');motion.exit();motion.destroy();assert.equal(element.style.pointerEvents,'auto');const replacement=context.module.exports.createPresenceMotion(element);replacement.enter();assert.equal(element.style.pointerEvents,'auto');replacement.destroy();}finally{f.close();}
});

test('real save dialog disables stale-revision retry and exposes draft export without closing or deleting prepared media',async()=>{
 const f=fixture();try{await f.window.CanvasLibrary.ready();const source={id:'source',type:'image',title:'未保存原图',image:'data:image/png;base64,AAAA'};f.setWriteFailure(Object.assign(Error('changed revision'),{name:'AgentConversationConflictError'}));f.document.dispatchEvent(new f.window.CustomEvent('canvas:save-assets',{detail:[source]}));const dialog=f.document.querySelector('.save-library-dialog'),save=[...dialog.querySelectorAll('button')].find(button=>button.textContent==='保存');await save.onclick();assert.equal(dialog.isConnected,true);assert.equal(save.disabled,true);assert.ok([...dialog.querySelectorAll('button')].some(button=>button.textContent==='导出未保存素材'));assert.equal(f.window.CanvasLibrary.items[0].image,source.image);assert.equal(f.record.items.length,0);[...dialog.querySelectorAll('button')].find(button=>button.textContent==='保留草稿并关闭').click();const library=f.open('素材库');assert.match(library.textContent,/先导出并确认本机文件/);assert.ok([...library.querySelectorAll('button')].some(button=>button.textContent==='导出未保存素材'));assert.ok(![...library.querySelectorAll('button')].some(button=>button.textContent==='重试保存'));}finally{f.close();}
});
