'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createHash}=require('node:crypto'),{pathToFileURL}=require('node:url'),{createRequire}=require('node:module');
const fabricRequire=createRequire(require.resolve('fabric')),canvasPath=fabricRequire.resolve('canvas'),prior=require.cache[canvasPath];require.cache[canvasPath]={id:canvasPath,loaded:true,exports:{createCanvas:undefined}};const {JSDOM}=fabricRequire('jsdom');if(prior)require.cache[canvasPath]=prior;else delete require.cache[canvasPath];
const root=path.resolve(__dirname,'..'),remote='https://files.tapnow.media/archive/original.png?token=private',unknown='https://files.tapnow.media/archive/missing.png?token=private',local='/assets/original.png',hash=value=>createHash('sha256').update(value).digest('hex'),index={version:1,algorithm:'sha256-exact-utf8',entries:{[hash(remote)]:{ref:local,sha256:hash('real bytes'),bytes:10}}};
const gate=()=>{let resolve;const promise=new Promise(done=>resolve=done);return{promise,resolve};};
const item=()=>({id:'saved',name:'原名称',type:'image',folder:'收藏',image:remote,fullImage:remote,mediaKey:'image:'+remote,provenance:{url:remote}});
const template=()=>({id:'template',name:'旧模板',tags:[],description:'保留说明',updatedAt:1,createdAt:1,image:remote,graph:{version:1,width:100,height:100,nodes:[{id:'node',type:'image',x:0,y:0,width:50,height:50,image:remote,generation:{prompt:remote,refs:[remote]},editorDoc:{canvas:{objects:[{type:'image',src:remote}]}},provenance:{url:remote}}],edges:[]}});
function fixture(t,{items=[item()],templates=[template()],locked=true}={}){
 const dom=new JSDOM('<body><nav class="side-tools"><button aria-label="素材库"></button><button aria-label="模板"></button><button aria-label="历史"></button></nav><button class="agent"></button><button class="avatar"></button><button class="share"></button><main id="canvas"></main></body>',{url:'http://localhost:4173/'});t.after(()=>dom.window.close());const {window}=dom,{document}=window,storage=new Map([['tapnow-library',JSON.stringify(items)],['tapnow-template-intro','dismissed']]),records=new Map(templates.map(row=>[row.id,structuredClone(row)])),notifications=[],libraryRecords=new Map();let storageFailure=false,dbFailure=false,lockTail=Promise.resolve(),writes=0,inserts=0;
 if(locked)Object.defineProperty(window.navigator,'locks',{value:{request(_name,fn){const pending=lockTail.catch(()=>{}).then(fn);lockTail=pending;return pending;}}});
 window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'));};
 const app={notify:value=>notifications.push(value),getState:()=>({nodes:[],edges:[],selected:[],view:{x:0,y:0,scale:1}}),preview(){inserts++;},insertAsset(){inserts++;},insertGraph(){inserts++;},focusNode(){}};
 Object.assign(window,{CanvasStore:{async readRecord(key){return structuredClone(libraryRecords.get(key));},async writeRecord(key,value,{expectedRevision,canCommit}={}){if(dbFailure)throw Error('disk full');const revision=libraryRecords.get(key)?.storageRevision||0;if(expectedRevision!==revision)throw Object.assign(Error('conflict'),{name:'AgentConversationConflictError'});if(canCommit&&canCommit()!==true)throw Object.assign(Error('changed'),{name:'CanvasRecordCommitRejectedError'});libraryRecords.set(key,{...structuredClone(value),storageRevision:revision+1});return {storageRevision:revision+1};}},CanvasApp:app,CanvasProjects:{registerNavigationGuard(){}},UI_ICONS:new Proxy({},{get:()=>'<svg></svg>'}),SIDEBAR_DATA:{template:[]},TemplatesCore:{capture:()=>template().graph,instantiate:()=>({group:{id:'group'},nodes:[],edges:[]})},WorkflowAPI:{executable:()=>false},EDITOR_DATA:{nodes:{}}});
 const db={transaction(_name,mode){let pending=0,aborted=false,scheduled=false;const staged=new Map(),tx={abort(){aborted=true;queueMicrotask(()=>tx.onabort?.());},objectStore(){return{getAll:()=>request(()=>[...records.values()].map(value=>structuredClone(value))),get:key=>request(()=>structuredClone(records.get(key))),put(value){staged.set(value.id,structuredClone(value));}};}};function complete(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(pending||aborted)return;if(mode==='readwrite'&&dbFailure){tx.error=Error('disk full');tx.onabort?.();return;}for(const [key,value]of staged){records.set(key,value);writes++;}tx.oncomplete?.();});}function request(read){const result={};pending++;queueMicrotask(()=>{result.result=read();result.onsuccess?.();pending--;complete();});return result;}complete();return tx;}};
 const context={window,document,URL,console,structuredClone,CustomEvent:window.CustomEvent,Option:window.Option,crypto:{randomUUID:()=> 'new-item'},innerWidth:1100,innerHeight:800,localStorage:{getItem:key=>storage.get(key)||null,setItem(key,value){if(storageFailure)throw Error('quota');storage.set(key,value);}},indexedDB:{open(){const request={};queueMicrotask(()=>{request.result=db;request.onsuccess();});return request;}},__import:specifier=>specifier.includes('local-resource-migration')?import(pathToFileURL(path.join(root,specifier)).href):new Promise(()=>{})};
 vm.createContext(context);for(const file of ['sidebars.js','templates-ui.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8').replace(/import\(([^)]+)\)/g,'__import($1)'),context);
 return{window,document,storage,records,notifications,libraryRecords,get libraryItems(){return libraryRecords.get('agent-library:personal-v1').items;},ready:Promise.all([window.TemplateAPI.ready,window.CanvasLibrary.ready()]),setStorageFailure:value=>storageFailure=value,setDbFailure:value=>dbFailure=value,get writes(){return writes;},get inserts(){return inserts;}};
}

test('both authoritative stores migrate complete media references, retain unknowns/identity and remain idempotent',async t=>{
 const libraryItem=item();libraryItem.audio=unknown;const row=template();row.video=unknown;const f=fixture(t,{items:[libraryItem],templates:[row]});await f.ready;
 const [a,b]=await Promise.all([f.window.CanvasLibrary.migrateResources({index,hashSource:hash}),f.window.TemplateAPI.migrateResources({index,hashSource:hash})]);
 assert.equal(a.persisted,true);assert.equal(b.persisted,true);assert.equal(a.status,'pending_import');assert.equal(b.status,'pending_import');const saved=f.libraryItems[0],savedTemplate=f.records.get('template');assert.equal(saved.fullImage,local);assert.equal(saved.audio,unknown);assert.equal(saved.mediaKey,libraryItem.mediaKey);assert.deepEqual(saved.provenance,libraryItem.provenance);assert.equal(f.window.CanvasLibrary.isFavorite({id:'canvas-node',type:'image',fullImage:local}),true);
 assert.equal(savedTemplate.graph.nodes[0].generation.refs[0],local);assert.equal(savedTemplate.graph.nodes[0].editorDoc.canvas.objects[0].src,local);assert.equal(savedTemplate.graph.nodes[0].generation.prompt,remote);assert.equal(savedTemplate.updatedAt,1);assert.equal(savedTemplate.video,unknown);assert.ok(!JSON.stringify([a,b]).includes('private'));
 assert.equal((await f.window.CanvasLibrary.migrateResources({index,hashSource:hash})).persisted,false);assert.equal((await f.window.TemplateAPI.migrateResources({index,hashSource:hash})).persisted,false);assert.equal(f.writes,1);
});

test('quota or aborted IndexedDB migration never swaps authoritative cache or reports success, and retry works',async t=>{
 const f=fixture(t);await f.ready;const beforeLibrary=structuredClone(f.window.CanvasLibrary.items),beforeTemplates=f.window.TemplateAPI.list();f.setStorageFailure(true);f.setDbFailure(true);
 await assert.rejects(f.window.CanvasLibrary.migrateResources({index,hashSource:hash}),/disk full/);await assert.rejects(f.window.TemplateAPI.migrateResources({index,hashSource:hash}),/disk full/);assert.deepEqual(structuredClone(f.window.CanvasLibrary.items),beforeLibrary);assert.deepEqual(f.window.TemplateAPI.list(),beforeTemplates);assert.equal(f.window.CanvasLibrary.migrationStatus().persisted,false);assert.equal(f.window.TemplateAPI.migrationStatus().status,'migration_failed');assert.equal(f.records.get('template').image,remote);
 f.setStorageFailure(false);f.setDbFailure(false);assert.equal((await f.window.CanvasLibrary.migrateResources({index,hashSource:hash})).persisted,true);assert.equal((await f.window.TemplateAPI.migrateResources({index,hashSource:hash})).persisted,true);
});

test('edits made while async mapping runs win without a stale library/template replacement',async t=>{
 const f=fixture(t);await f.ready;const entered=gate(),release=gate(),{migrateLibrarySnapshot,migrateTemplateSnapshot}=await import('../src/features/local-resource-migration/snapshot.mjs');let calls=0;const wait=fn=>async(...args)=>{if(++calls===2)entered.resolve();await release.promise;return fn(...args);};
 const a=f.window.CanvasLibrary.migrateResources({index,hashSource:hash,migrate:wait(migrateLibrarySnapshot)}),b=f.window.TemplateAPI.migrateResources({index,hashSource:hash,migrate:wait(migrateTemplateSnapshot)});await entered.promise;
 f.window.CanvasLibrary.items[0].name='当前编辑';f.window.CanvasLibrary.toggleFavorite({id:'new',type:'text',title:'本页新增',content:'真实内容'});await f.window.TemplateAPI.save('group',{name:'当前编辑',tags:[],description:'新版'},'template');release.resolve();await f.window.CanvasLibrary.flush();
 assert.equal((await a).status,'local_edits');assert.equal((await b).status,'local_edits');assert.equal(f.libraryItems[0].name,'当前编辑');assert.equal(f.records.get('template').name,'当前编辑');assert.equal(f.records.get('template').image,remote);
});

test('cross-window stored edits are compared inside commit and never overwritten by migration',async t=>{
 const f=fixture(t);await f.ready;const entered=gate(),release=gate(),{migrateLibrarySnapshot,migrateTemplateSnapshot}=await import('../src/features/local-resource-migration/snapshot.mjs');let calls=0;const wait=fn=>async(...args)=>{if(++calls===2)entered.resolve();await release.promise;return fn(...args);};
 const a=f.window.CanvasLibrary.migrateResources({index,hashSource:hash,migrate:wait(migrateLibrarySnapshot)}),b=f.window.TemplateAPI.migrateResources({index,hashSource:hash,migrate:wait(migrateTemplateSnapshot)});await entered.promise;
 const other=item();other.name='另一个窗口';f.libraryRecords.set('agent-library:personal-v1',{version:1,items:[other],folders:[],storageRevision:2});f.records.get('template').description='另一个窗口修改';release.resolve();assert.equal((await a).status,'local_edits');assert.equal((await b).status,'local_edits');assert.equal(f.libraryItems[0].name,'另一个窗口');assert.equal(f.records.get('template').description,'另一个窗口修改');assert.equal(f.writes,0);
});

test('official media cannot acquire src, preview or canvas insertion; missing index/lock retains originals',async t=>{
 const fallback=item();fallback.image='/assets/local-poster.png';fallback.fullImage='';fallback.type='video';fallback.nodeId='legacy-video';const f=fixture(t,{items:[fallback]});f.window.EDITOR_DATA.nodes['legacy-video']={video:remote};await f.ready;f.document.querySelector('[aria-label="素材库"]').click();[...f.document.querySelectorAll('.library-shortcut')].find(row=>row.textContent==='收藏').click();const image=f.document.querySelector('.asset-tile img'),tile=f.document.querySelector('.asset-tile');assert.equal(image.getAttribute('src'),'/assets/local-poster.png');tile.click();tile.ondblclick();assert.equal(f.inserts,0);assert.match(f.notifications.join(' '),/需迁移/);
 const row=f.records.get('template');row.graph.nodes[0].image='/assets/already-local.png';f.window.TemplateAPI.list()[0].graph.nodes[0].image='/assets/already-local.png';await assert.rejects(f.window.TemplateAPI.use('template'),/尚未迁移/);assert.equal(f.inserts,0);
 for(const state of ['index_missing','index_invalid','index_unavailable']){assert.equal((await f.window.CanvasLibrary.migrateResources({indexState:{state,index:null}})).persisted,false);assert.equal((await f.window.TemplateAPI.migrateResources({indexState:{state,index:null}})).status,state);}assert.equal(f.window.CanvasLibrary.items[0].image,'/assets/local-poster.png');const mapped=await f.window.CanvasLibrary.migrateResources({index,hashSource:hash});assert.equal(mapped.persisted,true);assert.equal(f.window.CanvasLibrary.items[0].video,local);assert.equal(f.libraryItems[0].video,local);const currentTile=f.document.querySelector('.asset-tile');currentTile.click();currentTile.ondblclick();assert.equal(f.inserts,2);f.document.querySelector('[aria-label="模板"]').click();[...f.document.querySelectorAll('.template-tabs button')].find(button=>button.textContent==='我的模板').click();assert.equal(f.document.querySelector('.template-card img').hasAttribute('src'),false);f.document.querySelector('.template-card').click();assert.equal(f.document.querySelector('.template-preview img').hasAttribute('src'),false);
 const noLock=fixture(t,{locked:false});await noLock.ready;assert.equal((await noLock.window.CanvasLibrary.migrateResources({index,hashSource:hash})).status,'ready');assert.equal(noLock.window.CanvasLibrary.items[0].image,local);
});
