'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{pathToFileURL}=require('node:url');
const source=fs.readFileSync(require.resolve('../sidebars.js'),'utf8'),key='agent-library:personal-v1';
const defer=()=>{let resolve;return{promise:new Promise(done=>resolve=done),resolve:value=>resolve(value)};};
function database(){let failure=null,tail=Promise.resolve(),delay=null;const records=new Map(),writes=[];return {records,writes,fail(value){failure=value;},delay(value){delay=value;},adapter:{async readRecord(id){if(delay)await delay;return structuredClone(records.get(id));},writeRecord(id,value,options={}){const captured=structuredClone(value);const next=tail.catch(()=>{}).then(()=>{if(failure)throw failure;const current=records.get(id)?.storageRevision||0;if(options.expectedRevision!==current)throw Object.assign(Error('另一窗口已更新记录'),{name:'AgentConversationConflictError'});if(options.canCommit&&options.canCommit()!==true)throw Object.assign(Error('提交资格已变化'),{name:'CanvasRecordCommitRejectedError'});captured.storageRevision=current+1;records.set(id,captured);writes.push(captured);return {storageRevision:current+1};});tail=next;return next;}}};}
function fixture({db=database(),legacy=new Map(),readError=null,noStore=false}={}){
 const notices=[],events=[],guards=[],listeners={};let serial=0,reads=0;const window={CanvasStore:noStore?undefined:db.adapter,CanvasApp:{notify:value=>notices.push(value),getState:()=>({nodes:[]}),render(){}},CanvasProjects:{registerNavigationGuard:fn=>guards.push(fn)},addEventListener(type,fn){(listeners[type]??=[]).push(fn);},EDITOR_DATA:{nodes:{}}};
 const document={dispatchEvent:e=>events.push(e.type)},context=vm.createContext({window,document,structuredClone,Blob,Uint8Array,fetch,btoa,CustomEvent:class{constructor(type){this.type=type;}},crypto:{randomUUID:()=> 'saved-'+(++serial)},localStorage:{getItem(id){reads++;if(readError)throw readError;return legacy.get(id)??null;},setItem(){throw Error('quota');}},__import:specifier=>import(pathToFileURL(path.resolve(__dirname,'..',specifier)).href)});
 vm.runInContext(source.slice(0,source.indexOf('  function migrationText')).replace(/import\(([^)]+)\)/g,'__import($1)')+'window.probe={persist:persistLibrary,writes:()=>libraryWrites};})();',context);
 return{api:window.CanvasLibrary,window,context,db,legacy,notices,guards,events,unload(){const event={prevented:false,preventDefault(){this.prevented=true;}};for(const fn of listeners.beforeunload||[])fn(event);return event;},get reads(){return reads;}};
}
const old=()=>({id:'old',type:'image',name:'原始',image:'data:image/png;base64,'+'A'.repeat(6*1024*1024),folder:'角色',provenance:{source:'保留'}});
test('large legacy media migrate once to a single record without any localStorage writes; reload uses committed authority',async()=>{
 const legacy=new Map([['tapnow-library',JSON.stringify([old()])],['tapnow-folders','["个人目录"]']]),before=new Map(legacy),f=fixture({legacy});assert.throws(()=>f.api.items,/正在读取/);await f.api.ready();assert.equal(f.api.items[0].image.length,old().image.length);assert.deepEqual(legacy,before);assert.equal(f.db.writes.length,1);assert.ok(f.api.folders.includes('个人目录'));
 f.api.toggleFavorite({id:'text',type:'text',title:'新增'});await f.api.flush();const reload=fixture({db:f.db,legacy,readError:Error('storage disabled')});await reload.api.ready();assert.equal(reload.reads,0);assert.equal(reload.api.items.length,2);assert.deepEqual(legacy,before);
});
test('unavailable or malformed legacy source cannot initialize an empty authority and remains retryable',async()=>{
 for(const options of [{readError:Error('storage unavailable')},{legacy:new Map([['tapnow-library','broken']])},{legacy:new Map([['tapnow-folders','{}']])}]){const f=fixture(options);await assert.rejects(f.api.ready());assert.equal(f.db.writes.length,0);assert.equal(f.api.loaded,false);assert.throws(()=>f.api.items);}
});
test('existing malformed record never falls back to older legacy or overwrites it',async()=>{
 const db=database();db.records.set(key,{version:1,items:null,folders:[],storageRevision:3});const f=fixture({db,legacy:new Map([['tapnow-library',JSON.stringify([old()])]])});await assert.rejects(f.api.ready(),/无效/);assert.equal(f.reads,0);assert.equal(db.writes.length,0);
});
test('pre-ready favorites wait for hydration and preserve the existing library',async()=>{
 const db=database(),gate=defer();db.delay(gate.promise);const f=fixture({db,legacy:new Map([['tapnow-library',JSON.stringify([{id:'old',type:'text',name:'旧素材'}])]])}),favorite=f.api.toggleFavorite({id:'text',type:'text',title:'收藏'});assert.equal(f.api.loaded,false);gate.resolve();assert.equal(await favorite,true);await f.api.flush();assert.equal(f.api.items.length,2);assert.equal(db.records.get(key).items.length,2);
});
test('two hydrated tabs use explicit revisions; stale writes retain memory drafts without overwriting authority',async()=>{
 const db=database(),one=fixture({db});await one.api.ready();const two=fixture({db});await two.api.ready();one.api.toggleFavorite({id:'one',type:'text',title:'窗口一'});await one.api.flush();two.api.toggleFavorite({id:'two',type:'text',title:'窗口二'});await assert.rejects(two.api.flush(),/另一窗口/);assert.equal(db.records.get(key).items[0].name,'窗口一');assert.equal(two.api.items[0].name,'窗口二');assert.match(two.guards[0](),/尚未保存/);
});
test('failed record commit preserves the prepared draft; retry keeps its ID and folders atomically',async()=>{
 const f=fixture();await f.api.ready();f.db.fail(Error('disk full'));f.api.toggleFavorite({id:'n',type:'text',title:'真实草稿'});await assert.rejects(f.api.flush(),/disk full/);const id=f.api.items[0].id;assert.equal(f.db.records.get(key).items.length,0);f.db.fail(null);await f.api.retrySave();await f.api.flush();assert.equal(f.db.records.get(key).items[0].id,id);assert.deepEqual(f.db.records.get(key).folders,[]);
});
test('legacy source changed during its initial migration aborts commit and does not overwrite the changed source',async()=>{
 const legacy=new Map(),db=database(),write=db.adapter.writeRecord;db.adapter.writeRecord=(id,value,options)=>{legacy.set('tapnow-library','[{"id":"other","name":"另一窗口"}]');return write(id,value,options);};const f=fixture({db,legacy});await assert.rejects(f.api.ready(),/提交资格/);assert.equal(db.writes.length,0);assert.match(legacy.get('tapnow-library'),/另一窗口/);
});
test('resource migration writes IDB record, keeps old source read-only, and rejects edits during mapping',async()=>{
 const remote='https://files.tapnow.media/archive/x.png',legacy=new Map([['tapnow-library',JSON.stringify([{id:'old',name:'旧图',type:'image',image:remote}])]]),f=fixture({legacy});await f.api.ready();const before=legacy.get('tapnow-library'),report=await f.api.migrateResources({index:{},migrate:async items=>({snapshot:items.map(item=>({...item,image:'/assets/local.png'})),changes:[{}],unresolved:[],summary:{changed:1}})});assert.equal(report.persisted,true);assert.equal(f.db.records.get(key).items[0].image,'/assets/local.png');assert.equal(legacy.get('tapnow-library'),before);
 const gate=defer(),entered=defer(),pending=f.api.migrateResources({index:{},migrate:async items=>{entered.resolve();await gate.promise;return {snapshot:items,changes:[{}],unresolved:[],summary:{changed:1}};}});await entered.promise;f.api.toggleFavorite({id:'n',type:'text',title:'新草稿'});await f.window.probe.writes();gate.resolve();assert.equal((await pending).status,'local_edits');
});
test('missing durable store is read-only and cannot write a false empty library',async()=>{const f=fixture({noStore:true});await assert.rejects(f.api.ready(),/只读/);assert.equal(f.db.writes.length,0);});

test('pending pre-ready favorite intent protects page unload until its write has committed',async()=>{
 const db=database(),gate=defer();db.delay(gate.promise);const f=fixture({db}),favorite=f.api.toggleFavorite({id:'intent',type:'text',title:'等待中的收藏'});assert.equal(f.unload().prevented,true);assert.match(f.guards[0](),/正在保存/);gate.resolve();await favorite;await f.api.flush();assert.equal(f.unload().prevented,false);assert.equal(db.records.get(key).items[0].name,'等待中的收藏');
});
test('CAS conflicts disable blind retries and export full local draft bytes without touching current authority',async()=>{
 const db=database(),one=fixture({db});await one.api.ready();const two=fixture({db});await two.api.ready();one.api.toggleFavorite({id:'one',type:'text',title:'当前权威'});await one.api.flush();two.api.toggleFavorite({id:'two',type:'image',title:'本地草稿',image:'asset:local-png'});await assert.rejects(two.api.flush(),/另一窗口/);assert.equal(two.api.conflict,true);assert.match(two.guards[0](),/导出草稿/);const before=structuredClone(db.records.get(key)),writeCount=db.writes.length;await assert.rejects(two.api.retrySave(),/先导出草稿/);assert.equal(db.writes.length,writeCount);
 const bytes=Uint8Array.from([137,80,78,71,13,10,26,10]),media=new Blob([bytes],{type:'image/png'});two.window.LocalAssets={url:async ref=>{assert.equal(ref,'asset:local-png');return URL.createObjectURL(media);}};const blob=await two.api.exportDraft(),bundle=JSON.parse(await blob.text());assert.equal(bundle.format,'freenow-library-draft');assert.equal(bundle.items[0].name,'本地草稿');assert.equal(bundle.media['asset:local-png'].bytes,8);assert.deepEqual(Buffer.from(bundle.media['asset:local-png'].dataUrl.split(',')[1],'base64'),Buffer.from(bytes));assert.deepEqual(db.records.get(key),before);assert.equal(two.api.conflict,true);assert.equal(two.unload().prevented,true);
});

test('QA reports summarize large data URLs without mutating original comparison evidence',()=>{
 const qa=fs.readFileSync(require.resolve('../src/features/library-asset-roundtrip/qa/controls.mjs'),'utf8'),a=qa.indexOf('function report('),b=qa.indexOf('async function prepare(',a),output={textContent:''},context=vm.createContext({output,window:{}}),raw='data:image/png;base64,'+'A'.repeat(8*1024*1024),evidence={display:{resolvedSource:raw},picker:{resolvedSource:'blob:local'},originalHashExact:true,passed:true};vm.runInContext(qa.slice(a,b)+'globalThis.reportForTest=report;',context);context.reportForTest(evidence);assert.ok(output.textContent.length<300);assert.match(output.textContent,/data:image\/png;base64,\[8388630 characters\]/);assert.equal(evidence.display.resolvedSource,raw);assert.equal(context.window.LIBRARY_ROUNDTRIP_QA_REPORT.passed,true);assert.equal(context.window.LIBRARY_ROUNDTRIP_QA_REPORT.picker.resolvedSource,'blob:local');
});
