const {test}=require('node:test'),assert=require('node:assert/strict');
const api=import('../media-review-core.mjs');
const tick=()=>new Promise(r=>setTimeout(r,0));
const example={id:'one',type:'video',video:'qa/playlist-red.mp4'};
test('review identity follows source, type and trimmed region, shares media copies',async()=>{const {media}=await api;assert.equal(media(example).key,media({...example,id:'two'}).key);assert.notEqual(media(example).key,media({...example,video:'new.mp4'}).key);assert.notEqual(media(example).key,media({...example,clip:{start:1,end:2}}).key);assert.equal(media({id:'empty',type:'image'}),null);assert.equal(media({id:'a',type:'image',image:'https://files.tapnow.media/x?variant_name=medium'}).key,media({id:'b',type:'image',image:'https://files.tapnow.media/x'}).key);});
test('review mapping rejects missing or unknown outcomes and missing pending ID',async()=>{const {result}=await api;assert.equal(result({status:'ASSET_REVIEW_STATUS_REJECTED',reject_reason:'ASSET_REJECT_REASON_INVALID_PARAMETER'}).status,'rejected_invalid');for(const value of [null,{}, {status:'success'},{status:'processing'}])assert.throws(()=>result(value));});
test('unconfigured review does not approve, submit or create media',async()=>{const {ReviewService,media}=await api;const service=new ReviewService();assert.equal((await service.submit(media(example))).status,'configuration_required');assert.equal(service.trace.length,1);});
test('eligibility rejection prevents submit',async()=>{const {ReviewService,media}=await api;let calls=0;const s=new ReviewService({adapter:{eligibility:async()=>({allowed:false,message:'不可用'}),submit:()=>calls++,poll:()=>{}}});assert.equal((await s.submit(media(example))).status,'unavailable');assert.equal(calls,0);});
test('deduplicates shared pending reviews and polls to approval',async()=>{const {ReviewService,media}=await api;let calls=0,polls=0;const s=new ReviewService({interval:1,adapter:{submit:async()=>{calls++;return {status:'pending',requestId:'job'};},poll:async id=>{assert.equal(id,'job');polls++;return {status:'approved'};}}});const input=media(example),first=s.submit(input),second=s.submit(input);assert.equal(first,second);assert.equal((await first).status,'approved');await s.submit(input);assert.equal(calls,1);assert.equal(polls,1);assert(!JSON.stringify(s.trace).includes(example.video));});
test('cancel ignores a late provider response and permits retry',async()=>{const {ReviewService,media}=await api;let resolve;const s=new ReviewService({adapter:{submit:()=>new Promise(r=>resolve=r),poll:async()=>({status:'approved'})}}),input=media(example);const promise=s.submit(input);await tick();assert(s.cancel(input));resolve({status:'approved'});await promise;assert.equal(s.get(input).status,'unknown');s.setAdapter({submit:async()=>({status:'rejected'}),poll:()=>{}});assert.equal((await s.submit(input)).status,'rejected');});
test('invalid provider result fails and a subsequent retry succeeds',async()=>{const {ReviewService,media}=await api;let calls=0;const s=new ReviewService({adapter:{submit:async()=>++calls===1?{status:'unexpected'}:{status:'approved'},poll:()=>{}}}),input=media(example);assert.equal((await s.submit(input)).status,'failed');assert.equal((await s.submit(input)).status,'approved');});
test('persisted pending review resumes by ID without submitting twice',async()=>{const {ReviewService,media}=await api;const input=media(example);let writes,submits=0;const s=new ReviewService({read:()=>[{key:input.key,status:'pending',requestId:'old'}],write:rows=>writes=rows,adapter:{submit:()=>submits++,poll:async id=>{assert.equal(id,'old');return {status:'approved'};}}});assert(s.get(input).interrupted);await s.submit(input);assert.equal(submits,0);assert.equal(writes[0].status,'approved');const reloaded=new ReviewService({read:()=>writes});assert.equal(reloaded.get(input).status,'approved');assert.equal(reloaded.get(media({...example,video:'changed.mp4'})).status,'unknown');});
test('poll failure retains ID and retries poll, not submission',async()=>{const {ReviewService,media}=await api;let submits=0,polls=0;const s=new ReviewService({interval:1,adapter:{submit:async()=>{submits++;return {status:'pending',requestId:'job'};},poll:async()=>{if(++polls===1)throw Error('network');return {status:'approved'};}}}),input=media(example);assert.equal((await s.submit(input)).status,'failed');assert.equal((await s.submit(input)).status,'approved');assert.equal(submits,1);});
test('hung provider is bounded and storage quota does not forge failure',async()=>{const {ReviewService,media}=await api;const input=media(example),s=new ReviewService({timeout:15,adapter:{submit:()=>new Promise(()=>{}),poll:()=>{}}});assert.equal((await s.submit(input)).status,'failed');assert.equal(s.running.size,0);s.setAdapter({submit:async()=>({status:'approved'}),poll:()=>{}});s.write=()=>{throw Error('quota');};const final=await s.submit(input);assert.equal(final.status,'approved');assert(final.persistenceError);});
test('gateway contract transports source and status, keeps credentials off request body',async()=>{const {httpAdapter,media}=await api;const calls=[],a=httpAdapter({fetcher:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>url.endsWith('config')?{configured:false}:{status:'approved'}};}});const signal=new AbortController().signal;assert.equal((await a.eligibility(media(example),{signal})).configurationRequired,true);await a.submit(media(example),{signal});await a.poll('a/b',{signal});assert.equal(calls[2].url,'/api/media-reviews/a%2Fb');const body=JSON.parse(calls[1].options.body);assert.equal(body.source.url,example.video);assert.equal(body.source.type,'video');assert(body.clientRequestId);assert.equal(calls[1].options.signal,signal);});
test('interrupted request survives missing provider and reload without double submission',async()=>{const {ReviewService,media}=await api;const input=media(example);let saved=[{key:input.key,status:'pending',requestId:'old'}];const s=new ReviewService({read:()=>saved,write:rows=>saved=rows,adapter:{eligibility:async()=>({allowed:false,configurationRequired:true}),submit:()=>assert.fail(),poll:()=>assert.fail()}});await s.submit(input);assert.equal(saved[0].requestId,'old');const reload=new ReviewService({read:()=>saved,adapter:{submit:()=>assert.fail(),poll:async()=>({status:'approved'})}});assert.equal((await reload.submit(input)).status,'approved');});
test('resubmitting a rejected review cannot reuse old completed request after failure',async()=>{const {ReviewService,media}=await api;const input=media(example);let saved=[{key:input.key,status:'rejected',requestId:'old'}],calls=0;const s=new ReviewService({read:()=>saved,adapter:{submit:async()=>{if(++calls===1)throw Error('offline');return {status:'approved'};},poll:()=>assert.fail()}});assert.equal((await s.submit(input)).status,'failed');assert.equal(s.get(input).requestId,undefined);assert.equal((await s.submit(input)).status,'approved');assert.equal(calls,2);});

test('canvas drag normalization avoids relative URL exceptions and reuses a 500-node absolute working set',async()=>{
 const {media}=await import('../media-review-core.mjs?drag-cache');const NativeURL=globalThis.URL;let parses=0;
 globalThis.URL=class extends NativeURL{constructor(...args){parses++;super(...args);}};
 try{
  const nodes=Array.from({length:500},(_,i)=>({id:'drag-'+i,type:'image',image:'assets/image-'+i+'.webp'}));
  for(let frame=0;frame<90;frame++)for(const node of nodes)media(node);assert.equal(parses,0);
  for(const [i,node]of nodes.entries())node.image='https://files.tapnow.media/drag-'+i+'?variant_name=small&keep=1';
  for(let frame=0;frame<90;frame++)for(const node of nodes){const value=media(node);assert.equal(value.url,node.image);assert.ok(!JSON.parse(value.key)[1].includes('variant_name'));}
  assert.equal(parses,500);
  for(let i=0;i<1100;i++)media({id:'evict-'+i,type:'image',image:'https://files.tapnow.media/evict-'+i});const before=parses;media(nodes[0]);assert.equal(parses,before+1);
 }finally{globalThis.URL=NativeURL;}
});
test('cached URL normalization never caches node metadata or in-place clip changes',async()=>{
 const {media}=await api,node={id:'source',type:'video',video:'https://files.tapnow.media/clip?variant_name=small',clip:{start:.125,end:2},sourceFileId:'file-one'},initial=media(node);
 node.clip.start=.375;let value=media(node);assert.notEqual(value.key,initial.key);assert.equal(initial.clip.start,.125);assert.equal(value.clip.start,.375);
 node.currentSourceFileId='file-two';node.id='copy';value=media(node);assert.equal(value.fileId,'file-two');assert.equal(value.nodeId,'copy');assert.equal(value.key,media({...node,id:'another',sourceFileId:'other'}).key);
 node.video='https://files.tapnow.media/clip?variant_name=full';const variant=media(node);assert.equal(variant.key,value.key);assert.equal(variant.url,node.video);
 node.video='https://files.tapnow.media/different?variant_name=full';assert.notEqual(media(node).key,variant.key);
 node.type='audio';node.audio='asset:local-sound';value=media(node);assert.equal(value.type,'audio');assert.equal(value.url,node.audio);assert.equal(value.clip,null);
 delete node.audio;const defaults={audio:'qa/sound.wav'};assert.equal(media(node,defaults).url,'qa/sound.wav');defaults.audio='qa/other.wav';assert.equal(media(node,defaults).url,'qa/other.wav');
 const image={id:'image',type:'image',image:'qa/preview.png',fullImage:'asset:full'};assert.equal(media(image).url,'asset:full');image.fullImage='';assert.equal(media(image).url,'qa/preview.png');
});
test('shared canonical media keeps a review alive until the last copy changes and cancellation ignores late approval',async()=>{
 const {ReviewService,media}=await api;let finish,submits=0;
 const service=new ReviewService({adapter:{submit:()=>{submits++;return new Promise(resolve=>finish=resolve);},poll:()=>assert.fail()}});
 const first={id:'first',type:'video',video:'https://files.tapnow.media/shared?variant_name=small',clip:{start:0,end:2}},copy={...first,id:'copy',video:'https://files.tapnow.media/shared?variant_name=full',clip:{...first.clip}},input=media(first),promise=service.submit(input);await tick();assert.equal(service.submit(media(copy)),promise);assert.equal(submits,1);
 const reconcile=()=>{const keys=new Set([first,copy].map(node=>media(node).key));for(const key of service.running.keys())if(!keys.has(key))service.cancel({key});};
 first.clip.start=1;reconcile();assert.equal(service.running.size,1);copy.clip.start=1;reconcile();assert.equal(service.running.size,0);finish({status:'approved'});await promise;assert.equal(service.get(input).status,'unknown');assert.equal(service.get(media(copy)).status,'unknown');
});
