const test=require('node:test'),assert=require('node:assert/strict'),modulePromise=import('../media-preview-core.mjs');
test('media fit uses contain geometry without rounding source coordinates',async()=>{const c=await modulePromise,r=c.fit({left:10.25,top:20.375,width:500.125,height:400},{width:864,height:496});assert.equal(r.width,500.125);assert.equal(r.left,10.25);assert.equal(r.height,500.125*496/864);});
test('preview reserves source side panels and prompt remains 32px below media',async()=>{const c=await modulePromise,l=c.layout(889,1011,{width:864,height:496});assert.equal(l.box.width,425);assert.equal(l.frame.top,64+(771-l.frame.height)/2);assert.equal(l.promptTop,l.frame.top+l.frame.height+32);assert.equal(l.history,56);assert.equal(l.facts,176);});
test('history current resource is first and duplicate URLs collapse',async()=>{const c=await modulePromise,n={type:'video',video:'b',width:435,height:250,videoHistory:[{prompt:'A',parameters:{model:'one'},options:[{video:'a'}]},{prompt:'B',parameters:{model:'two'},options:[{video:'b'},{video:'a'}]}]},r=c.resources(n);assert.deepEqual(r.map(r=>r.src),['b','a']);assert.equal(r[0].prompt,'B');assert.equal(r[0].model,'two');});
test('image main patch keeps generation parameters and restores image dimensions',async()=>{const c=await modulePromise,p=c.mainPatch({type:'image',width:435},{src:'portrait',width:180,height:320,prompt:'new',generation:{model:'historical'}},{model:'current',count:4});assert.equal(p.image,'portrait');assert.equal(p.generation.model,'historical');assert.equal(p.generation.count,4);assert.equal(p.height,435*320/180);});
test('inspection maps preview into full contain region with zero drift',async()=>{const c=await modulePromise,l=c.layout(889,1011,{width:864,height:496}),bounds=c.constraints(l.frame,l.inspect),t=c.transform({zoom:1,panX:0,panY:0},bounds);assert.ok(Math.abs(t.scale-l.inspect.width/l.frame.width)<1e-12);assert.equal(l.frame.left+l.frame.width/2+t.x,l.inspect.left+l.inspect.width/2);});
test('zoom anchor stays at pointer except at pan limits and limits are bounded',async()=>{const c=await modulePromise,b={minZoom:.5,fitOffsetX:0,fitOffsetY:0,fitWidth:800,fitHeight:600},v=c.zoomAt({zoom:1,panX:0,panY:0},2,{x:100,y:50},b);assert.equal(v.panX,-100);assert.equal(v.panY,-50);const end=c.bound({zoom:99,panX:99999,panY:-99999},b);assert.deepEqual(end,{zoom:5,panX:1600,panY:-1200});});
test('zoom-out below contain removes panning and wheel matches source sensitivity',async()=>{const c=await modulePromise,b={minZoom:.4,fitWidth:800,fitHeight:600};assert.deepEqual(c.bound({zoom:.6,panX:100,panY:100},b),{zoom:.6,panX:0,panY:0});assert.equal(c.wheelZoom(1,-10000,false,.4),2**.12);assert.equal(c.wheelZoom(1,10000,true,.4),.4);});
test('time output supports empty, long videos and nonnegative clocks',async()=>{const c=await modulePromise;assert.equal(c.time(NaN),'00:00');assert.equal(c.time(125.8),'02:05');assert.equal(c.time(-1),'00:00');});
