const test=require('node:test'),assert=require('node:assert/strict');
const {TaskService}=require('../generation-api.js');
const ready=Promise.all([import('../src/features/node-composer/recognition-media.mjs'),import('../src/features/agent-workflows/media-resolver.mjs'),import('../src/features/agent-workflows/media-transport.mjs')]);
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jCn0AAAAASUVORK5CYII=',url='data:image/png;base64,'+png;
const request={kind:'image.recognize',nodeId:'source',inputs:[{type:'image',url:'asset:target'}],parameters:{point:{x:.375,y:.625},binding:{sourceNodeId:'source',targetNodeId:'target',markId:'mark'},output:{format:'json',boxOrder:['top','left','bottom','right'],coordinates:'normalized-0-1'}}};
const nativeConfiguration={protocol:'openai-native',capabilities:{analysis:{'image.recognize':{kind:'image.recognize',operation:'point-detection',transport:'inline',maxImages:1}}}};
const baseUrl='http://localhost:4173/',serialize=async b=>'data:'+b.type+';base64,'+Buffer.from(await b.arrayBuffer()).toString('base64');
function options(resolver,transport,extra={}){const probed=[],fetched=[];return {probed,fetched,config:{baseUrl,nativeConfiguration,resolveMedia:resolver.createWorkflowMediaResolver({baseUrl,localAssets:{url:async()=> 'blob:http://localhost:4173/fixture'},createImage:()=>({naturalWidth:1,naturalHeight:1,decode:async()=>{},removeAttribute(){},set src(v){probed.push(v);queueMicrotask(()=>this.onload?.());}})}),transport:(value,o)=>transport.prepareWorkflowInputs(value,{...o,serialize,fetchImpl:async(u,opts)=>{fetched.push({u,opts});return new Response(Buffer.from(png,'base64'),{headers:{'content-type':'image/png'}});}}),...extra}};}
test('focus native resolves original asset, inlines once, decodes submitted pixels and preserves point/binding/output',async()=>{
 const [media,resolver,transport]=await ready,o=options(resolver,transport);let guards=0;const out=await media.prepareRecognitionMedia(request,{...o.config,validateSources:()=>guards++});assert.equal(out.inputs[0].url,url);assert.equal(out.inputs[0].width,1);assert.deepEqual(out.parameters,request.parameters);assert.deepEqual(o.probed,[url]);assert.equal(o.fetched.length,1);assert.equal(o.fetched[0].opts.credentials,'omit');assert.equal(o.fetched[0].opts.redirect,'error');assert.ok(guards>=4);assert.equal(request.inputs[0].url,'asset:target');
});
test('gateway transport remains unchanged; absent native mapping and invalid input fail before reading assets',async()=>{
 const [media]=await ready;assert.equal(await media.prepareRecognitionMedia(request,{nativeConfiguration:{protocol:'tasks-v1'}}),request);
 for(const args of [{...nativeConfiguration,capabilities:{}},{...nativeConfiguration,capabilities:{analysis:{'image.recognize':{kind:'image.recognize',operation:'point-detection',transport:'inline',maxImages:2}}}}])await assert.rejects(media.prepareRecognitionMedia(request,{nativeConfiguration:args,resolveMedia:()=>assert.fail()}),/配置/);
 await assert.rejects(media.prepareRecognitionMedia({...request,inputs:[{type:'video',url:'x'}]},{nativeConfiguration,resolveMedia:()=>assert.fail()}),/一张/);
});
test('credentials/private addresses/corrupt pixels reject before dispatch without unchecked Image network probes',async()=>{
 const [media,resolver,transport]=await ready;
 for(const source of ['https://user:secret@public.test/p.png','http://192.168.0.2/p.png']){const o=options(resolver,transport);await assert.rejects(media.prepareRecognitionMedia({...request,inputs:[{type:'image',url:source}]},o.config));assert.deepEqual(o.probed,[]);assert.deepEqual(o.fetched,[]);}
 const o=options(resolver,transport,{resolveMedia:async(node,opts)=>{if(opts.decodeImage!==false)throw Error('actual pixels invalid');return {url:node.image};}});await assert.rejects(media.prepareRecognitionMedia({...request,inputs:[{type:'image',url}]},o.config),/actual pixels invalid/);
});
test('source invalidation or cancellation during inline transport prevents native dispatch',async()=>{
 const [media]=await ready;for(const cancelled of [true,false]){let release,begin,changed=false,calls=0;const started=new Promise(r=>begin=r),service=new TaskService({prepareInputs:(request,{signal,validateSources})=>media.prepareRecognitionMedia(request,{nativeConfiguration,signal,validateSources,resolveMedia:async n=>({url:n.image,width:1,height:1}),transport:async r=>{begin();await new Promise(r=>release=r);return {...r,inputs:[{type:'image',url}]};}})});service.setProvider({generate:async()=>{calls++;return {outputs:[{type:'text',text:'{}'}]};}});const job=service.submit(request,{beforeDispatch:()=>{if(changed)throw Error('source changed');}});await started;if(cancelled)service.cancel(job.id);else changed=true;release();for(let i=0;i<15&&['running','queued'].includes(job.status);i++)await new Promise(r=>setImmediate(r));assert.equal(job.status,cancelled?'cancelled':'failed');assert.equal(calls,0);assert.equal(job.providerDispatched,undefined);}
});
test('actual focus request crosses media preparation and installed SDK Responses using only explicit kind mapping',async()=>{
 const [media,resolver,transport]=await ready,o=options(resolver,transport),calls=[];
 const {createOpenAINativeProvider}=require('../server/generation-openai.cjs'),result={items:[{label_name:'固定识别测试',label_desc:'仅契约测试',box_2d:[.1,.1,.9,.9]}]};
 const provider=createOpenAINativeProvider({apiKey:'test-only',baseUrl:'https://isolated-provider.test/v1',modelMap:{'image.recognize':{kind:'image.recognize',model:'configured-vision-model'}},fetchImpl:async(address,options)=>{calls.push({address:String(address),body:JSON.parse(options.body)});return new Response(JSON.stringify({id:'response-test',status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(result),annotations:[]}]}]}),{headers:{'content-type':'application/json'}});}});
 const prepared=JSON.parse(JSON.stringify(await media.prepareRecognitionMedia(request,{...o.config,nativeConfiguration:provider.metadata}))),out=await provider.submit(prepared);assert.deepEqual(JSON.parse(out.outputs[0].text),result);assert.equal(calls.length,1);assert.equal(calls[0].address,'https://isolated-provider.test/v1/responses');assert.equal(calls[0].body.model,'configured-vision-model');assert.equal(calls[0].body.input[0].content[1].image_url,url);assert.equal(calls[0].body.store,false);assert.equal(calls[0].body.text.format.strict,true);assert.deepEqual(prepared.parameters.point,request.parameters.point);assert.ok(!JSON.stringify(provider.metadata).includes('configured-vision-model'));
 const unmapped=createOpenAINativeProvider({client:{},modelMap:{other:{kind:'image.recognize',model:'m'}}});assert.throws(()=>unmapped.prepare(prepared),{code:'configuration_required'});assert.throws(()=>provider.prepare({...prepared,parameters:{...prepared.parameters,model:'wrong'}}),{code:'configuration_required'});
});
test('recovered focus results cannot lose their session binding by becoming ordinary text nodes',async()=>{
 const {importRecoveredOutputs}=await import('../src/features/generation-results/recovery.mjs');let calls=0;await assert.rejects(importRecoveredOutputs({request,status:'succeeded',outputs:[{type:'text',text:'{}'}]},{app:{getState(){calls++;return {nodes:[]};}}}),/焦点识别/);assert.equal(calls,0);
});
