'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');

function dom(){
  let document;
  class Element{
    constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attrs={};this.dataset={};this.style={};this.events={};this.value='';this.className='';this.classList={add:c=>this.className+=' '+c,remove:c=>this.className=this.className.split(' ').filter(x=>x!==c).join(' '),contains:c=>this.className.split(' ').includes(c),toggle:(c,on)=>{on??=!this.classList.contains(c);on?this.classList.add(c):this.classList.remove(c);return on;}};}
    append(...children){for(const child of children){if(typeof child==='string')continue;child.remove();child.parent=this;this.children.push(child);}}
    replaceChildren(...children){this.children.forEach(c=>c.parent=null);this.children=[];this.append(...children);}
    remove(){if(this.parent){this.parent.children=this.parent.children.filter(c=>c!==this);this.parent=null;}}
    get isConnected(){return this===document.body||this===document.head||!!this.parent?.isConnected;}
    setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){if(k.startsWith('data-'))return this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())];return this.attrs[k]??(k==='aria-label'?this.ariaLabel:k==='role'?this.role:k==='id'?this.id:undefined);}removeAttribute(k){delete this.attrs[k];}
    matches(selector){return selector.split(',').some(raw=>{let s=raw.trim();if(s.includes(' ')){const at=s.lastIndexOf(' ');return this.matches(s.slice(at+1))&&!!this.parent?.closest(s.slice(0,at));}let valid=true;s=s.replace(/\[([^=\]^]+)(\^=|=)?["']?([^\]"']*)["']?\]/g,(_,key,op,value)=>{const actual=key==='open'?this.open:key==='hidden'?this.hidden:this.getAttribute(key);valid&&=op==='='?actual===value:op==='^='?String(actual||'').startsWith(value):!!actual;return '';});const tag=s.match(/^[a-z]+/i)?.[0];if(tag&&tag.toUpperCase()!==this.tagName)return false;for(const cls of s.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(cls[1]))return false;const id=s.match(/#([\w-]+)/)?.[1];return valid&&(!id||this.id===id);});}
    closest(s){return this.matches(s)?this:this.parent?.closest(s)||null;}contains(node){return node===this||this.children.some(c=>c.contains(node));}
    querySelectorAll(s){return this.children.flatMap(c=>[...(c.matches(s)?[c]:[]),...c.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0]||null;}
    addEventListener(type,fn,options){(this.events[type]??=[]).push({fn,capture:options===true||!!options?.capture});}removeEventListener(){}focus(){document.activeElement=this;}getBoundingClientRect(){return {left:10,right:210,top:10,bottom:50,width:200,height:40};}
    showModal(){this.open=true;this.querySelector('input,button')?.focus();}close(){this.open=false;this.onclose?.();for(const {fn}of this.events.close||[])fn();}insertAdjacentHTML(){}
  }
  document={events:{},createElement:tag=>new Element(tag),addEventListener:Element.prototype.addEventListener,removeEventListener(){},querySelector:s=>document.body.querySelector(s),querySelectorAll:s=>document.body.querySelectorAll(s)};
  document.body=new Element('body');document.head=new Element('head');document.activeElement=document.body;
  function dispatch(type,target,extra={}){const e={type,target,key:'',defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},stopPropagation(){this.stopped=true;},stopImmediatePropagation(){this.stopped=this.immediate=true;},...extra};for(const {fn,capture}of document.events[type]||[])if(capture){fn(e);if(e.immediate)return e;}for(let node=target;node;node=node.parent){node['on'+type]?.(e);if(!e.immediate)for(const {fn,capture}of node.events[type]||[])if(!capture){fn(e);if(e.immediate)break;}if(e.stopped)break;}if(!e.stopped)for(const {fn,capture}of document.events[type]||[])if(!capture){fn(e);if(e.immediate)break;}if(type==='keydown'&&e.key==='Escape'&&!e.defaultPrevented){const modal=document.querySelector('dialog[open]');if(modal){const cancel={preventDefault(){this.defaultPrevented=true;}};modal.oncancel?.(cancel);for(const {fn}of modal.events.cancel||[])fn(cancel);if(!cancel.defaultPrevented)modal.close();}}return e;}
  return {document,Element,dispatch};
}
function base(){
 const f=dom(),{document,Element}=f;const notifications=[],storage=new Map();const app={notify:text=>notifications.push(text),getState:()=>({nodes:[],selected:[],edges:[],view:{x:0,y:0,scale:1}})};
 const guards=[];const context={URL,document,window:{CanvasApp:app,CanvasProjects:{registerNavigationGuard:fn=>{guards.push(fn);return()=>guards.splice(guards.indexOf(fn),1);}},addEventListener(){}},innerWidth:1200,innerHeight:800,localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},crypto:{randomUUID:()=> 'uuid'},AbortController,ResizeObserver:class{observe(){}disconnect(){}},structuredClone,console,queueMicrotask};
 vm.runInNewContext(fs.readFileSync(require.resolve('../src/shared/draft-dismissal.mjs'),'utf8').replace('export function','function').replace('import.meta.url',JSON.stringify('http://localhost/src/shared/draft-dismissal.mjs'))+';this.confirmDiscard=confirmDiscard;',context);f.context=context;f.guards=guards;f.notifications=notifications;return f;
}
function sidebar(){
 const f=base(),{document,Element,context}=f;const tools=new Element('nav');tools.className='side-tools';document.body.append(tools);for(const label of ['素材库','模板','历史']){const b=new Element('button');b.setAttribute('aria-label',label);tools.append(b);}for(const cls of ['agent','avatar','share']){const b=new Element('button');b.className=cls;document.body.append(b);}context.window.UI_ICONS={folder:'',arrowRight:''};context.window.SIDEBAR_DATA={template:[{name:'Template',image:'test.png'}],history:[]};
 let record;context.window.CanvasStore={async readRecord(){return record;},async writeRecord(_key,value){record={...structuredClone(value),storageRevision:(record?.storageRevision||0)+1};return {storageRevision:record.storageRevision};}};context.CustomEvent=class{constructor(type){this.type=type;}};document.dispatchEvent=event=>f.dispatch(event.type,document.body,event);
 const source=fs.readFileSync(require.resolve('../sidebars.js'),'utf8').replace(/  import\('\.\/src\/features\/generation-results\/entry.mjs'\).*\n/,'');vm.runInNewContext(source,context);return f;
}
function openLibrary(f){const trigger=f.document.querySelector('.side-tools button[aria-label="素材库"]');trigger.focus();trigger.onclick();return trigger;}
test('native dialog Escape closes the dialog and preserves its library drawer',async()=>{const f=sidebar();await f.context.window.CanvasLibrary.ready();openLibrary(f);f.dispatch('canvas:save-assets',f.document.body,{detail:[{id:'image',type:'image',image:'test.png',title:'Image'}]});const dialog=f.document.querySelector('dialog');assert.ok(dialog.open);f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(dialog.isConnected,false);assert.ok(f.document.querySelector('.left-panel'));});
test('one Escape closes only the library menu, restores trigger, and next Escape closes drawer',async()=>{const f=sidebar();await f.context.window.CanvasLibrary.ready();const trigger=openLibrary(f),plus=f.document.querySelector('.panel-plus');plus.focus();plus.onclick();assert.equal(plus.getAttribute('aria-expanded'),'true');f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(f.document.querySelector('.context-popup'),null);assert.ok(f.document.querySelector('.left-panel'));assert.equal(f.document.activeElement,plus);f.dispatch('keydown',plus,{key:'Escape'});assert.equal(f.document.querySelector('.left-panel'),null);assert.equal(f.document.activeElement,trigger);});
test('menu outside respects trigger so repeated clicks toggle; drawer outside remains open',async()=>{const f=sidebar();await f.context.window.CanvasLibrary.ready();openLibrary(f);const plus=f.document.querySelector('.panel-plus');plus.onclick();f.dispatch('pointerdown',plus);plus.onclick();assert.equal(f.document.querySelector('.context-popup'),null);f.dispatch('pointerdown',f.document.body);assert.ok(f.document.querySelector('.left-panel'));});
test('library menu Tab preserves origin until focus leaves; Shift-Tab to its trigger closes after focus settles',async()=>{
 const f=sidebar();await f.context.window.CanvasLibrary.ready();openLibrary(f);const plus=f.document.querySelector('.panel-plus');plus.onclick();
 const menu=f.document.querySelector('.context-popup'),origin=f.document.activeElement,event=f.dispatch('keydown',origin,{key:'Tab',shiftKey:true});
 assert.equal(event.defaultPrevented,false);assert.ok(menu.isConnected);assert.notEqual(menu.inert,true);assert.equal(f.document.activeElement,origin);
 plus.focus();f.dispatch('focusin',plus);
 assert.equal(f.document.querySelector('.context-popup'),null);assert.equal(f.document.activeElement,plus);assert.ok(f.document.querySelector('.left-panel'));
});
test('a foreign popup removed by an earlier bubble listener does not expose drawer to the same Escape',async()=>{const f=sidebar();await f.context.window.CanvasLibrary.ready();const foreign=new f.Element('section');foreign.role='menu';f.document.body.append(foreign);const handlers=f.document.events.keydown;handlers.splice(handlers.findIndex(h=>!h.capture),0,{capture:false,fn:()=>foreign.remove()});openLibrary(f);f.dispatch('keydown',f.document.body,{key:'Escape'});assert.equal(foreign.isConnected,false);assert.ok(f.document.querySelector('.left-panel'));});
test('share Escape removes one transient layer and retains underlying drawer',async()=>{const f=sidebar();await f.context.window.CanvasLibrary.ready();openLibrary(f);const trigger=f.document.querySelector('.share');trigger.onclick();f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(f.document.querySelector('.share-menu'),null);assert.ok(f.document.querySelector('.left-panel'));assert.equal(f.document.activeElement,trigger);});

function subjectEditor(){const f=base(),{context,document}=f;context.el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';e.textContent=text;return e;};context.button=(text,fn,cls)=>{const b=context.el('button',cls,text);b.onclick=fn;return b;};context.loadStyles=()=>{};context.assetPreviews=()=>({hide(){},bind(){},destroy(){}});context.bindAssetSort=()=>({cancel(){},destroy(){}});context.panelWidth=()=>()=>{};context.panelMotion=panel=>({enter(){},exit(){panel.remove();}});context.saveSubject=()=>{};context.preview=()=>context.el('img');context.assetIcons={};context.pickSubjectAssets=()=>({close(){}});const source=fs.readFileSync(require.resolve('../src/features/subject-library/editor.mjs'),'utf8').replace(/^import .*\n/gm,'').replace('export function','function');vm.runInNewContext(source+';this.editSubject=editSubject;',context);return {...f,open:()=>context.editSubject()};}
test('subject editor protects dirty drafts with a page dialog; Escape preserves draft and navigation is blocked',()=>{const f=subjectEditor();let editor=f.open();assert.equal(editor.close(),true);assert.equal(f.document.querySelector('dialog'),null);editor=f.open();const name=editor.element.querySelector('input');name.value='Changed';assert.match(f.guards[0](),/未保存/);assert.equal(editor.close(),false);const confirmation=f.document.querySelector('dialog');assert.ok(confirmation.open);f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(confirmation.isConnected,false);assert.ok(editor.element.isConnected);assert.equal(name.value,'Changed');const done=editor.element.querySelector('footer').children.at(-1);done.onclick();assert.equal(f.guards.length,0);assert.equal(editor.close(),true);});
test('subject discard performs requested continuation only after explicit acceptance',()=>{const f=subjectEditor(),editor=f.open();editor.element.querySelector('input').value='Changed';let continued=0;assert.equal(editor.close({onDiscard:()=>continued++}),false);assert.equal(continued,0);f.document.querySelector('[data-action="discard"]').onclick();assert.equal(continued,1);assert.equal(editor.element.isConnected,false);assert.equal(f.guards.length,0);});

async function templates(){const f=base(),{context}=f;context.window.TemplatesCore={capture:()=>({nodes:[]})};context.indexedDB={open(){const request={};queueMicrotask(()=>{request.result={transaction(){const tx={objectStore:()=>({getAll:()=>({result:[]})})};queueMicrotask(()=>tx.oncomplete());return tx;}};request.onsuccess();});return request;}};vm.runInNewContext(fs.readFileSync(require.resolve('../templates-ui.js'),'utf8').replace("import('./src/shared/draft-dismissal.mjs')",'Promise.resolve({confirmDiscard})'),context);await context.window.TemplateAPI.ready;return {...f,open:()=>context.window.TemplateAPI.open('group')};}
test('template cancellation keeps dirty form behind page confirmation and blocks navigation',async()=>{const f=await templates();await f.open();assert.equal(f.context.window.TemplateAPI.close(),true);assert.equal(f.document.querySelector('dialog'),null);await f.open();f.document.querySelector('input[aria-label="模板名称"]').value='Changed';assert.match(f.guards[0](),/未保存/);assert.equal(f.context.window.TemplateAPI.close(),false);await Promise.resolve();await Promise.resolve();const confirmation=f.document.querySelector('dialog');assert.ok(confirmation);f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(confirmation.isConnected,false);assert.ok(f.document.querySelector('.template-create'));assert.equal(f.context.window.TemplateAPI.close(),false);await Promise.resolve();await Promise.resolve();f.document.querySelector('[data-action="discard"]').onclick();assert.equal(f.document.querySelector('.template-create'),null);assert.equal(f.guards[0](),null);});
test('template tag Escape cancels only pending tag and modal Escape does not close background form',async()=>{const f=await templates();await f.open();const tags=f.document.querySelector('.template-tag-list');tags.querySelector('button').onclick();const input=tags.querySelector('input');input.value='Tag';f.dispatch('keydown',input,{key:'Escape'});assert.equal(tags.querySelector('input'),null);assert.ok(f.document.querySelector('.template-create'));const dialog=new f.Element('dialog');f.document.body.append(dialog);dialog.showModal();f.dispatch('keydown',dialog,{key:'Escape'});assert.ok(f.document.querySelector('.template-create'));assert.equal(f.document.querySelector('.draft-dismissal-dialog'),null);});

function groupsMenu({x=100,y=180,view={x:0,y:0,scale:1}}={}){const f=base(),{context,document,Element}=f;const bar=new Element('nav');bar.id='node-toolbar';bar.offsetWidth=320;bar.offsetHeight=40;document.body.append(bar);const header=new Element('header');header.className='project-bar';header.getBoundingClientRect=()=>({bottom:56});document.body.append(header);const node={id:'group',type:'group',x,y,width:240,height:200};context.window.CANVAS_GROUP_ICONS={};context.window.CanvasGroups=require('../canvas-groups.js');context.window.CanvasPiles={plan:()=>false};context.window.CanvasApp.layoutNodes=()=>{};context.window.CanvasApp.updateNode=()=>{};vm.runInNewContext(fs.readFileSync(require.resolve('../canvas-groups-ui.js'),'utf8'),context);context.window.CanvasGroupsUI.toolbar([node],bar,{nodes:[node],view,canvas:{getBoundingClientRect:()=>({left:0,top:0,width:1200,height:800})}});return {...f,node,bar,trigger:label=>bar.querySelector('button[aria-label="'+label+'"]'),click:button=>button.onclick({stopPropagation(){}})};}
test('group menus toggle on same trigger and preserve upper modal Escape, then restore own trigger',()=>{const f=groupsMenu(),trigger=f.trigger('布局');f.click(trigger);const menu=f.document.querySelector('.canvas-group-pop');assert.equal(f.document.activeElement,menu.children[0]);f.dispatch('pointerdown',trigger);f.click(trigger);assert.equal(f.document.querySelector('.canvas-group-pop'),null);assert.equal(f.document.activeElement,trigger);f.click(trigger);const dialog=new f.Element('dialog');dialog.append(new f.Element('button'));f.document.body.append(dialog);dialog.showModal();f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(dialog.open,false);assert.ok(f.document.querySelector('.canvas-group-pop'));f.document.querySelector('.canvas-group-pop button').focus();f.dispatch('keydown',f.document.activeElement,{key:'Escape'});assert.equal(f.document.querySelector('.canvas-group-pop'),null);assert.equal(f.document.activeElement,trigger);assert.equal(trigger.getAttribute('aria-expanded'),'false');});
test('group toolbar stays operable at all viewport edges without changing world geometry',()=>{for(const [x,y]of [[-2000,-2000],[10000,-2000],[-2000,10000],[10000,10000]]){const f=groupsMenu({x,y}),left=parseFloat(f.bar.style.left),top=parseFloat(f.bar.style.top);assert.ok(left>=8&&left<=872);assert.ok(top>=64&&top<=752);assert.equal(f.node.x,x);assert.equal(f.node.y,y);}const f=groupsMenu();assert.equal(f.bar.style.left,'60px');assert.equal(f.bar.style.top,'84px');});
test('group palette keyboard and unrelated trigger click dismiss independently',()=>{const f=groupsMenu(),trigger=f.trigger('背景颜色');f.click(trigger);const p=f.document.querySelector('.canvas-group-pop');assert.equal(f.document.activeElement,p.children[0]);f.dispatch('keydown',f.document.activeElement,{key:'ArrowRight'});assert.equal(f.document.activeElement,p.children[1]);f.dispatch('pointerdown',f.trigger('创建模板'));assert.equal(f.document.querySelector('.canvas-group-pop'),null);assert.equal(trigger.getAttribute('aria-expanded'),'false');});
test('pile gallery consumes only its own Escape/Tab and yields to native or nested menu layers',()=>{const f=base(),{context,document,Element}=f;let cancelled=0;context.window.CanvasPiles={};context.window.CANVAS_GROUP_ICONS={};const source=fs.readFileSync(require.resolve('../canvas-piles-ui.js'),'utf8').replace(' window.CanvasPilesUI=', ' window.setTestGallery=value=>gallery=value;window.CanvasPilesUI=');vm.runInNewContext(source,context);const root=new Element('section');root.role='dialog';root.className='pile-gallery';const button=new Element('button');root.append(button);document.body.append(root);context.window.setTestGallery({root,phase:'open',cancelDrag:()=>{cancelled++;return true;}});let arrows=0;button.onkeydown=e=>{if(e.key==='ArrowRight')arrows++;};f.dispatch('keydown',button,{key:'ArrowRight'});assert.equal(arrows,1);const menu=new Element('section');menu.role='menu';root.append(menu);f.dispatch('keydown',menu,{key:'Escape'});assert.equal(cancelled,0);const dialog=new Element('dialog');document.body.append(dialog);dialog.showModal();f.dispatch('keydown',button,{key:'Escape'});assert.equal(cancelled,0);assert.equal(dialog.open,false);const escape=f.dispatch('keydown',button,{key:'Escape'});assert.equal(cancelled,1);assert.equal(escape.defaultPrevented,true);});
