const test=require('node:test'),assert=require('node:assert/strict');
const crop=import('../studio-panorama-crop.mjs'),math=import('../studio-panorama-math.mjs'),three=import('three');
test('crop ray-plane conversion round trips rotated camera and offset viewport',async()=>{
 const c=await crop,m=await math,T=await three,camera=new T.PerspectiveCamera(67,1.45,.03,1000);camera.quaternion.setFromEuler(new T.Euler(.37,2.9,-.15,'YXZ'));const basis=c.cropBasis({quaternion:camera.quaternion.toArray()}),bounds={minX:-2,maxX:3,minY:-1,maxY:2},viewport={left:139,top:212,width:870,height:600};
 const corners=m.projectRegion(c.cropDirections(bounds,basis),camera,viewport);for(let i=0;i<4;i++){const actual=c.directionOnPatchPlane(m.screenDirection(corners[i].x,corners[i].y,viewport,camera),basis),expected=c.handlePoint(bounds,['tl','tr','br','bl'][i]);assert.ok(Math.abs(actual.x-expected.x)<1e-8);assert.ok(Math.abs(actual.y-expected.y)<1e-8);}
 assert.equal(c.directionOnPatchPlane(basis.forward.map(x=>-x),basis),null);
});
test('all eight crop handles preserve opposite edges and minimum span',async()=>{
 const c=await crop,b={minX:-2,maxX:2,minY:-3,maxY:3};for(const h of c.cropHandles){const next=c.resizePatchCrop(b,h,{x:h.includes('l')?100:-100,y:h.includes('t')?-100:100});assert.ok(next.maxX-next.minX>=.5);assert.ok(next.maxY-next.minY>=.5);if(!h.includes('l'))assert.equal(next.minX,b.minX);if(!h.includes('r'))assert.equal(next.maxX,b.maxX);if(!h.includes('t'))assert.equal(next.maxY,b.maxY);if(!h.includes('b'))assert.equal(next.minY,b.minY);}
 assert.throws(()=>c.resizePatchCrop(b,'tl',{x:NaN,y:0}),/无效/);assert.equal(c.validCropBounds({...b,maxX:Infinity}),false);assert.equal(c.validCropBounds({...b,maxY:b.minY}),false);
});
test('crop hit selects smallest enabled patch and handles panorama seam',async()=>{
 const c=await crop,T=await three,basis=c.cropBasis({quaternion:new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),Math.PI).toArray()}),large={id:'large',kind:'local',crop:{basis,bounds:{minX:-4,maxX:4,minY:-4,maxY:4}}},small={...large,id:'small',crop:{basis,bounds:{minX:-1,maxX:1,minY:-1,maxY:1}}};assert.equal(c.hitPatch([0,0,1],[large,small]),'small');assert.equal(c.hitPatch([0,0,1],[large,{...small,enabled:false}]),'large');assert.equal(c.hitPatch([0,0,1],[{...small,deletedAt:1}]),null);assert.equal(c.hitPatch([0,0,-1],[small]),null);
});
test('crop changes real mask pixels while history undo restores original bounds',async()=>{
 const c=await crop,{PanoramaHistory}=await math,{maskPanoramaPixels}=await import('../studio-panorama-layers.mjs'),basis=c.cropBasis({quaternion:[0,0,0,1]}),patch={id:'p',kind:'local',crop:{basis,bounds:{minX:-4,maxX:4,minY:-4,maxY:4}}},history=new PanoramaHistory({anchor:{patches:[patch]}}),w=200,h=100,overlay=Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===0||i%4===3?255:0);
 const render=p=>maskPanoramaPixels(new Uint8ClampedArray(w*h*4),overlay,w,h,c.effectivePatchRegions(p));assert.equal(render(patch)[(50*w+100)*4],255);history.change({anchor:{patches:[{...patch,crop:{basis,bounds:{minX:1,maxX:4,minY:-4,maxY:4}}}]}});assert.equal(render(history.state.anchor.patches[0])[(50*w+100)*4],0);history.undo();assert.equal(render(history.state.anchor.patches[0])[(50*w+100)*4],255);
});
test('crop drag becomes stale after session, selection or revision change',async()=>{const c=await crop,e={id:'s',history:{revision:4},selectedPatchId:'p'},drag={token:'s',revision:4,id:'p'};assert.equal(c.currentCropDrag(e,drag),true);for(const changed of [{...e,id:'next'},{...e,selectedPatchId:null},{...e,history:{revision:5}}])assert.equal(c.currentCropDrag(changed,drag),false);});
test('Agent crop schema rejects nonfinite, oversized and missing bounds',()=>{const {parse}=require('../agent-tools.js');const args={action:'crop_patch',id:'p',crop:{minX:-2,maxX:2,minY:-1,maxY:1}};assert.deepEqual(parse('scene_panorama',args).args,args);assert.throws(()=>parse('scene_panorama',{...args,crop:{...args.crop,minX:NaN}}),/number/);assert.throws(()=>parse('scene_panorama',{...args,crop:{...args.crop,maxX:10001}}),/number/);assert.throws(()=>parse('scene_panorama',{...args,crop:{minX:0}}),/required/);});
