const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../qa/video-mask-native-fixture.js'),'utf8');
function boot({mode='pipeline',getterFails=false,immutableOpen=false}={}){
 let originalCalls=0;const writes=[],dbCalls=[],stored={};const sandbox={URL,URLSearchParams,Response,crypto:{randomUUID:()=> 'synthetic-session'},location:{href:'http://127.0.0.1:55555/?mode='+mode,origin:'http://127.0.0.1:55555',search:'?mode='+mode},setTimeout,clearTimeout,document:{documentElement:{dataset:{}},write:s=>writes.push(s)},fetch:async()=>{originalCalls++;return Response.json({realLocalGateway:true});},indexedDB:{open:(...args)=>{dbCalls.push(args);return {};}}};sandbox.window={...sandbox};
 Object.defineProperty(sandbox.window,'localStorage',{configurable:true,get(){if(getterFails)throw Error('storage blocked');return {getItem:k=>stored[k]??null,setItem:(k,v)=>stored[k]=v,removeItem:k=>delete stored[k]};}});
 if(immutableOpen)Object.defineProperty(sandbox.indexedDB,'open',{writable:false,configurable:false});vm.runInNewContext(source,sandbox);return {sandbox:sandbox.window,writes,dbCalls,stored,originalCalls:()=>originalCalls};
}
test('isolated QA bootstrap failure disables subsequent scripts and makes zero true gateway/media requests',async()=>{
 for(const options of [{getterFails:true,immutableOpen:true},{immutableOpen:true},{getterFails:true}]){const b=boot(options),s=b.sandbox;assert.equal(s.VideoMaskFixture.ready,false,JSON.stringify(options));assert.match(s.CANVAS_DB_NAME,/^qa-video-mask:synthetic-session:/);assert.match(s.LOCAL_ASSETS_DB_NAME,/^qa-video-mask:synthetic-session:/);assert.match(b.writes.join(''),/script-src &#39;none&#39;/);assert.equal((await (await s.fetch('/api/generation/config')).json()).configured,false);await assert.rejects(()=>s.fetch('/qa/native-video-mask-source.mp4'),/isolation failed/);await s.fetch('/api/generation/tasks',{method:'POST',body:'{}'});await assert.rejects(()=>s.fetch('https://queue.fal.run/model'),/禁止外部请求/);assert.equal(b.originalCalls(),0);assert.deepEqual(b.dbCalls,[]);}
});
test('successful QA initialization prefixes all stores and only pipeline mode forwards same-origin gateway',async()=>{
 for(const mode of ['native','pipeline']){const b=boot({mode}),s=b.sandbox;assert.equal(s.VideoMaskFixture.ready,true);s.indexedDB.open('unlisted-subject-library',2);s.localStorage.setItem('canvas-key','isolated');assert.match(b.dbCalls[0][0],/^qa-video-mask:synthetic-session:/);assert.match(Object.keys(b.stored)[0],/^qa-video-mask:synthetic-session:/);await s.fetch('/api/generation/config');assert.equal(b.originalCalls(),mode==='pipeline'?1:0);await assert.rejects(()=>s.fetch('/api/anything-else'),/禁止其他 API/);await assert.rejects(()=>s.fetch('https://example.com/video.mp4'),/禁止外部请求/);assert.equal(b.originalCalls(),mode==='pipeline'?1:0);}
});
