'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto');
const {createReplicateSam2SegmentationService}=require('../server/video-segmentation-replicate.cjs');
const {createVideoSegmentationAdapter}=require('../server/video-segmentation.cjs');
const sha=value=>createHash('sha256').update(value).digest('hex');
const bytes=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(12)]);
const request={kind:'video.segment',nodeId:'approval-fixture-node',sourceVideoUrl:'data:video/mp4;base64,'+bytes.toString('base64'),width:4,height:2,duration:1.5,time:.5,selection:{x:.25,y:0,width:.5,height:1},pointPrompts:[{x:2,y:1,time:.5,label:1}]};
const approved=config=>({'X-Segmentation-Model-Version':config.version,'X-Segmentation-Provider-Fingerprint':config.providerFingerprint});
async function fixture(t,{holdSecondUpload=false}={}){
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'sam2-approval-')),calls={body:0,prepare:0,source:0,media:0,upload:0,submit:0,poll:0,cancel:0};let service,block=holdSecondUpload;
 const options={directory,prepareRequest:async value=>{calls.prepare++;return createVideoSegmentationAdapter().prepareRequest(value);},downloader:{async download(){calls.source++;return {mime:'video/mp4',stream:(async function*(){yield bytes;})(),close(){}};}},mediaTools:{async prepareSegmentationMedia(){calls.media++;return {source:{sha256:sha(bytes),width:4,height:2,fps:2,numFrames:3,duration:1.5},prompt:{frameIndex:1,time:.5,pts:.5,x:2,y:1},branches:['forward','reverse'].map(direction=>({direction,bytes,sha256:sha(bytes),firstFrameSha256:sha(Buffer.alloc(24)),numFrames:2,sourceIndices:direction==='forward'?[1,2]:[1,0]}))};}},transport:{async upload(_bytes,{signal}){calls.upload++;if(block&&calls.upload===2)await new Promise((_,reject)=>{signal.addEventListener('abort',()=>reject(new Error('fixture interrupted')),{once:true});});return {id:'File-'+calls.upload,url:'https://api.replicate.com/v1/files/File-'+calls.upload};},inputFor(url){return {input_video:url};},async submit(_input,{onIdentity}){const id='prediction'+(++calls.submit);await onIdentity(id);return {id,status:'processing'};},async poll(id){calls.poll++;return {id,status:'processing'};},async cancel(id){calls.cancel++;return {id,status:'canceled',confirmed:true};}}};
 service=createReplicateSam2SegmentationService({...options,apiKey:'approval-account-a-fixture-token'});await service.ready;
 const server=http.createServer((req,res)=>service.handle(req,res,new URL(req.url,'http://localhost').pathname,{json:(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));},body:async req=>{calls.body++;const parts=[];for await(const part of req)parts.push(part);return JSON.parse(Buffer.concat(parts));}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const local='http://127.0.0.1:'+server.address().port;
 t.after(async()=>{await service.close();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true});});
 async function wait(id,predicate){const until=Date.now()+3000;for(;;){const record=JSON.parse(await fs.readFile(path.join(directory,id+'.json'),'utf8'));if(predicate(record)){await new Promise(resolve=>setTimeout(resolve,15));return record;}if(Date.now()>until)throw Error('approval fixture timed out');await new Promise(resolve=>setTimeout(resolve,5));}}
 return {local,calls,directory,config:()=>service.config(),wait,async restart(key='approval-account-a-fixture-token'){await service.close();block=false;service=createReplicateSam2SegmentationService({...options,apiKey:key});await service.ready;}};
}
test('approved identity HTTP create rejects missing and wrong headers before parsing body or any source/provider work',async t=>{
 const f=await fixture(t),config=f.config(),id=randomUUID(),zero={...f.calls};
 for(const headers of [{},{'X-Segmentation-Model-Version':config.version},{...approved(config),'X-Segmentation-Model-Version':'old-model-version'},{...approved(config),'X-Segmentation-Provider-Fingerprint':'old-provider-fingerprint'}]){
  const response=await fetch(f.local+'/api/video-segmentation/tasks',{method:'POST',headers:{'Idempotency-Key':id,...headers},body:'not even JSON'});assert.equal(response.status,409);const result=await response.json();assert.equal(result.code,'segmentation_configuration_identity_mismatch');assert.ok(!JSON.stringify(result).includes('fixture-token'));assert.deepEqual(f.calls,zero);
 }
 await assert.rejects(fs.stat(path.join(f.directory,id+'.json')),{code:'ENOENT'});
 const correct=await fetch(f.local+'/api/video-segmentation/tasks',{method:'POST',headers:{'Idempotency-Key':id,...approved(config)},body:JSON.stringify(request)});assert.equal(correct.status,202);assert.equal((await correct.json()).id,id);await f.wait(id,record=>record.branches.every(branch=>branch.predictionId)&&record.branches.length===2);assert.deepEqual(f.calls,{body:1,prepare:1,source:1,media:1,upload:2,submit:2,poll:0,cancel:0});
});
test('approved identity HTTP resume rejects unapproved requests but accepts current approval after same-config restart; GET/cancel need no approval',async t=>{
 const f=await fixture(t,{holdSecondUpload:true}),config=f.config(),id=randomUUID();const created=await fetch(f.local+'/api/video-segmentation/tasks',{method:'POST',headers:{'Idempotency-Key':id,...approved(config)},body:JSON.stringify(request)});assert.equal(created.status,202);await f.wait(id,record=>record.branches[0]?.predictionId&&record.branches[1]?.status==='uploading');await f.restart();const before={...f.calls};
 for(const headers of [{},{...approved(config),'X-Segmentation-Provider-Fingerprint':'unapproved'}]){const response=await fetch(f.local+'/api/video-segmentation/tasks/'+id+'/resume',{method:'POST',headers,body:'not JSON'});assert.equal(response.status,409);assert.equal((await response.json()).code,'segmentation_configuration_identity_mismatch');assert.deepEqual(f.calls,before);}
 const lookup=await fetch(f.local+'/api/video-segmentation/tasks/'+id);assert.equal(lookup.status,200);assert.equal((await lookup.json()).status,'needs_resume');assert.equal(f.calls.poll,before.poll+1);
 const resumed=await fetch(f.local+'/api/video-segmentation/tasks/'+id+'/resume',{method:'POST',headers:approved(config),body:'{}'});assert.equal(resumed.status,202);await f.wait(id,record=>record.branches[1]?.predictionId);assert.equal(f.calls.submit,2);assert.equal(f.calls.source,1);assert.equal(f.calls.media,1);
 const cancelled=await fetch(f.local+'/api/video-segmentation/tasks/'+id+'/cancel',{method:'POST',body:'{}'});assert.equal(cancelled.status,200);assert.equal((await cancelled.json()).status,'cancelled');assert.equal(f.calls.cancel,2);
});
test('A-to-B HTTP restart rejects stale create approval and old receipt resume before body or any new provider call',async t=>{
 const f=await fixture(t),configA=f.config(),id=randomUUID();const created=await fetch(f.local+'/api/video-segmentation/tasks',{method:'POST',headers:{'Idempotency-Key':id,...approved(configA)},body:JSON.stringify(request)});assert.equal(created.status,202);await f.wait(id,record=>record.branches.every(branch=>branch.predictionId)&&record.branches.length===2);await f.restart('approval-account-b-fixture-token');const configB=f.config(),before={...f.calls};assert.notEqual(configB.providerFingerprint,configA.providerFingerprint);
 for(const route of ['/api/video-segmentation/tasks','/api/video-segmentation/tasks/'+id+'/resume']){const response=await fetch(f.local+route,{method:'POST',headers:{'Idempotency-Key':randomUUID(),...approved(configA)},body:'not JSON'});assert.equal(response.status,409);assert.equal((await response.json()).code,'segmentation_configuration_identity_mismatch');assert.deepEqual(f.calls,before);}
 const oldReceipt=await fetch(f.local+'/api/video-segmentation/tasks/'+id+'/resume',{method:'POST',headers:approved(configB),body:'{}'});assert.equal(oldReceipt.status,409);assert.equal((await oldReceipt.json()).code,'segmentation_provider_changed');assert.deepEqual({...f.calls,body:before.body},before);
 const read=await fetch(f.local+'/api/video-segmentation/tasks/'+id);assert.equal(read.status,409);assert.equal((await read.json()).code,'segmentation_provider_changed');assert.equal(f.calls.poll,before.poll);
});
