const test=require('node:test'),assert=require('node:assert/strict');
const profile={durations:[-1],resolutions:['720p','1080p'],audio:true,maxImages:0,maxVideos:1,maxAudios:0,videoDurationRange:{min:4,max:30,totalMax:30},omniReferenceTaskType:'edit'};
const config={configured:true,protocol:'ark-video-reshoot-edit',capabilities:{kinds:['video.reshoot'],models:{'seedance-2.5':{kind:'video.reshoot'}},videoReshoot:{models:{'seedance-2.5':{resolution:'720p',generateAudio:true,profile}}}}};
async function request(url='https://media.test/source.mp4'){const c=await import('../src/features/video-reshoot/core.mjs');return c.request({id:'source',generation:{modelId:'wrong-source-model',resolution:'1080p',generateAudio:false}},c.initial(8),url);}
test('fixed official alias inherits source specs and exposes experimental execution boundaries',async()=>{const r=await request(),{reshootRequestState}=await import('../src/features/video-reshoot/native-profile.mjs');assert.equal(r.parameters.modelId,'seedance-2.5');assert.equal(r.parameters.resolution,'1080p');assert.equal(r.parameters.generateAudio,false);const state=reshootRequestState(config,r);assert(state.ready);assert.match(state.hint,/实验性.*1080p.*无声/);assert.match(state.hint,/不保证.*逐帧/);});
test('native local-video and selected-clip restrictions block before decoding, trimming or transport',async()=>{const {prepareReshootMedia}=await import('../src/features/video-reshoot/media.mjs');for(const url of ['asset:source','/qa/trim-scenes.mp4','data:video/mp4;base64,AAAA','blob:https://app/uuid'])await assert.rejects(async()=>prepareReshootMedia(await request(url),{nativeConfiguration:config,resolveMedia:()=>assert.fail('no decode'),transport:()=>assert.fail('no transport')}),/独立 HTTPS/);const r=await request();r.parameters.sourceClip={start:2,end:10};await assert.rejects(()=>prepareReshootMedia(r,{nativeConfiguration:config,resolveMedia:()=>assert.fail('no trim')}),/媒体上传/);});
test('media resolver must supply actual duration and geometry and cannot silently change camera plan duration',async()=>{const {prepareReshootMedia}=await import('../src/features/video-reshoot/media.mjs'),r=await request();for(const actual of [{url:r.inputs[0].url,width:1280,height:720,duration:7},{url:r.inputs[0].url,width:320,height:180,duration:8},{url:r.inputs[0].url,width:1280,height:720},{url:'data:video/mp4;base64,AAAA',width:1280,height:720,duration:8}])await assert.rejects(()=>prepareReshootMedia(r,{nativeConfiguration:config,resolveMedia:async()=>actual,transport:()=>assert.fail('no transmit')}));const options={nativeConfiguration:config,resolveMedia:async()=>({url:r.inputs[0].url,width:1280,height:720,duration:8}),transport:async r=>r};const actual=await prepareReshootMedia(r,options);assert.equal(actual.inputs[0].durationMs,8000);assert.equal(r.inputs[0].duration,undefined);await assert.rejects(()=>prepareReshootMedia(r,{...options,transport:async input=>({...input,inputs:[{...input.inputs[0],url:'data:video/mp4;base64,AAAA'}]})}),/独立 HTTPS/);});
test('gateway clips are materialized once with duration and range identity, original request retained',async()=>{const {prepareReshootMedia}=await import('../src/features/video-reshoot/media.mjs'),r=await request('asset:source');r.parameters.sourceClip={start:2,end:10};let reads=0;const actual=await prepareReshootMedia(r,{resolveMedia:async node=>{reads++;assert.deepEqual(node.clip,{start:2,end:10});return {url:'data:video/mp4;base64,AAAA',width:1280,height:720,duration:8};},transport:async r=>r});assert.equal(reads,1);assert.equal(actual.parameters.sourceClip,null);assert.deepEqual(actual.inputs[0].sourceRange,{start:2,end:10});assert.deepEqual(r.parameters.sourceClip,{start:2,end:10});});
test('abort, close, project switch, node replacement or source mutation invalidate async source ownership',async()=>{const {sourceGuard}=await import('../src/features/video-reshoot/core.mjs');for(const kind of ['abort','close','project','replace','url','clip']){const node={id:'source',video:'asset:source'},nodes=[node],controller=new AbortController();let project='a',alive=true;const app={projectIdentity:()=>({id:project}),getState:()=>({nodes})},guard=sourceGuard(app,node,{signal:controller.signal,isAlive:()=>alive});guard();if(kind==='abort')controller.abort(Error('cancelled'));if(kind==='close')alive=false;if(kind==='project')project='b';if(kind==='replace')nodes[0]={...node};if(kind==='url')node.video='changed';if(kind==='clip')node.clip={start:0,end:8};assert.throws(guard,/cancelled|已取消|来源/);}});
test('source mutation or cancellation during media read prevents any transport',async()=>{const {prepareReshootMedia}=await import('../src/features/video-reshoot/media.mjs');for(const abort of [true,false]){const r=await request(),controller=new AbortController();let changed=false;await assert.rejects(()=>prepareReshootMedia(r,{signal:controller.signal,validateSources:()=>{if(changed)throw Error('source changed');},resolveMedia:async()=>{if(abort)controller.abort(Error('cancelled'));else changed=true;return {url:r.inputs[0].url,width:1280,height:720,duration:8};},transport:()=>assert.fail('no transport')}),/cancelled|source changed/);}});
test('unconfigured and unsupported spec preflight preserve chosen parameters without fallback',async()=>{const {reshootRequestState}=await import('../src/features/video-reshoot/native-profile.mjs'),r=await request();assert.equal(reshootRequestState({...config,configured:false},r).ready,false);r.parameters.modelId='other';assert.equal(reshootRequestState(config,r).ready,false);r.parameters.modelId='seedance-2.5';r.parameters.resolution='4k';assert.equal(reshootRequestState(config,r).ready,false);assert.equal(r.parameters.resolution,'4k');});

test('source generation settings changed during real TaskService configuration lookup cannot dispatch stale resolution/audio',async()=>{
 const {TaskService}=require('../generation-api.js'),c=await import('../src/features/video-reshoot/core.mjs'),{prepareReshootMedia}=await import('../src/features/video-reshoot/media.mjs');
 for(const field of ['resolution','generateAudio']){
  const node={id:'source',video:'https://media.test/source.mp4',generation:{resolution:'1080p',generateAudio:false}},app={projectIdentity:()=>({id:'qa-project'}),getState:()=>({nodes:[node]})};let release,start,dispatches=0,reads=0;
  const pending=new Promise(r=>release=r),started=new Promise(r=>start=r),guard=c.sourceGuard(app,node),service=new TaskService({prepareInputs:(request,context)=>prepareReshootMedia(request,{...context,resolveMedia:async()=>{reads++;return {url:node.video,width:1920,height:1080,duration:8};},transport:async r=>r})});
  service.setProvider({isConfigured:async()=>{start();await pending;return true;},generate:()=>{dispatches++;assert.fail('must not send old settings');}});
  const job=service.submit(c.request(node,c.initial(8),node.video),{beforeDispatch:guard});await started;node.generation[field]=field==='resolution'?'720p':true;release();for(let i=0;i<20&&job.status==='queued';i++)await new Promise(r=>setImmediate(r));assert.equal(job.status,'failed');assert.match(job.error,/生成设置/);assert.equal(reads,0);assert.equal(dispatches,0);
 }
});
test('all-unchanged plan rejects in frontend before configuration or media work, while imported defaults remain explicit',async()=>{
 const c=await import('../src/features/video-reshoot/core.mjs'),state=c.initial(8);state.segments[0].mode='unchanged';assert.throws(()=>c.request({id:'imported'},state,'asset:source'),/无需生成/);assert.deepEqual(c.reshootSettings({id:'imported'}),{modelId:'seedance-2.5',capabilityMode:'prompt_simulation',resolution:'720p',generateAudio:true});
});
