const {test}=require('node:test'),assert=require('node:assert/strict');
const modules=()=>import('../src/features/video-mask/recovery.mjs');
const ID='11111111-1111-4111-8111-111111111111';
// Invoke the actual production method with decoder/DOM boundary stubs. This
// checks its guards, not video pixels or browser rendering.
async function maskLoaderFixture({mutable=false,transportData='data:video/mp4;base64,YWJj',duringRead}={}){
 const m=await modules(),core=await import('../src/features/video-mask/core.mjs'),f=fixture();f.node.sourceFileId='source-v1';if(mutable)f.node.video='/qa/public-source.mp4';const receipt=m.createSegmentationReceipt(options(f));receipt.status='applied';receipt.maskAsset='asset:mask';receipt.inputSha256=await m.fingerprintSourceData('data:video/mp4;base64,YWJj');f.node.videoMask={source:f.node.video,clip:receipt.clip,asset:'asset:mask',time:.5,width:4,height:2,duration:1,timeline:'full-source',taskId:receipt.taskId};
 let reads=0,transports=0,paints=0,decodes=0;const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/features/video-mask/ui.mjs'),'utf8'),start=source.indexOf('  async loadMask(saved){'),end=source.indexOf('  clearMask(){',start),mask={width:4,height:2,fps:2,frames:['0 2','6 2']};
 const loadMask=Function('core','openVideoFrames','window','fetch','transport','fingerprintSourceData','return ({'+source.slice(start,end)+'}).loadMask')(core,async()=>{decodes++;return {at:async()=>({}),dispose(){}};},{LocalAssets:{url:async value=>value}},async()=>{reads++;return {json:async()=>{duringRead?.(f,receipt);return mask;}};},async(_s,_signal,guard,inline)=>{assert.equal(inline,true);guard();transports++;return transportData;},m.fingerprintSourceData);
 const editor={taskReceipt:receipt,source:f.node.video,clip:receipt.clip,video:{videoWidth:4,videoHeight:2},duration:1,listeners:new AbortController(),alive:true,guard:core.sourceGuard(f.app,f.node),receiptGuard:value=>m.assertReceiptCurrent(f.app,f.node,value),node:()=>f.node,makeThumbnail:()=> 'thumb',renderMask(){},paint(){paints++;},error(message){this.lastError=message;}};
 return {f,receipt,editor,load:()=>loadMask.call(editor,f.node.videoMask),get reads(){return reads;},get transports(){return transports;},get paints(){return paints;},get decodes(){return decodes;}};
}
function fixture(){const values=new Map(),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},node={id:'n',type:'video',video:'asset:immutable',width:4,height:2,clip:{start:.5,end:1}},state={nodes:[node],edges:[]};let project='p',updates=0;const app={projectIdentity:()=>({id:project}),getState:()=>state,updateNode(_id,patch){updates++;Object.assign(node,patch);}};return {values,storage,node,app,state,get updates(){return updates;},switchProject(){project='q';}};}
function options(f){return {app:f.app,node:f.node,source:f.node.video,rect:{x:0,y:0,width:.5,height:.5},time:.5,configuration:{protocol:'replicate-sam2-native',version:'fixed-v1',providerFingerprint:'fixed-origin'},uuid:()=>ID};}
test('intent UUID and source/clip/content identity persist before any POST and task status GET',async()=>{
 const m=await modules(),f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));let posts=0,gets=0;
 const observer=m.createTaskObservation({store,receipt,api:{create:async(_request,{idempotencyKey})=>{posts++;assert.equal(idempotencyKey,ID);assert.equal(store.read('p','n').dispatched,true);return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'running'};},get:async()=>{gets++;assert.equal(store.read('p','n').taskId,ID);return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'succeeded',mask:{frames:[]}};}},guard:()=>m.assertReceiptCurrent(f.app,f.node,receipt),delay:async()=>{}});
 const initial=await observer.create({kind:'video.segment'});await observer.observe({initial});assert.equal(posts,1);assert.equal(gets,1);assert.equal(receipt.sourceFingerprint,m.sourceFingerprint(f.node));assert.equal(receipt.clip,'{"start":0.5,"end":1}');
});
test('blocked receipt writes prevent dispatch and polling; retry retains the same task UUID',async()=>{
 const m=await modules(),f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));let blocked=true,posts=0,gets=0;const original=f.storage.setItem;f.storage.setItem=(...args)=>{if(blocked)throw Error('quota');return original(...args);};const observer=m.createTaskObservation({store,receipt,api:{create:async()=>{posts++;return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'unknown'};},get:async()=>{gets++;return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'unknown'};}}});
 await assert.rejects(observer.create({}),{code:'segmentation_receipt_save_failed'});await assert.rejects(observer.observe(),{code:'segmentation_receipt_save_failed'});assert.equal(posts+gets,0);assert.equal(receipt.taskId,ID);blocked=false;await observer.create({});assert.equal(posts,1);
});
test('second pre-dispatch receipt failure does not incorrectly mark an intent as sent',async()=>{
 const m=await modules(),f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));let calls=0;const original=f.storage.setItem;f.storage.setItem=(...args)=>{if(++calls===2)throw Error('quota');return original(...args);};let posts=0;const observer=m.createTaskObservation({store,receipt,api:{create:()=>posts++}});await assert.rejects(observer.create({}),{code:'segmentation_receipt_save_failed'});assert.equal(posts,0);assert.equal(receipt.dispatched,false);assert.equal(receipt.status,'intent');
});
test('lost creation response and reload recover only by known UUID GET, never create or auto resume',async()=>{
 const m=await modules(),f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));let posts=0,gets=0,resumes=0;const api={create:async()=>{posts++;throw Error('lost response');},get:async id=>{gets++;assert.equal(id,ID);return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'needs_resume',canResume:true};},resume:async()=>{resumes++;return {id:ID,version:'fixed-v1',providerFingerprint:'fixed-origin',status:'running'};}};
 await assert.rejects(m.createTaskObservation({store,receipt,api}).create({}),/lost/);const recovered=store.read('p','n');assert.equal(recovered.dispatched,true);const observer=m.createTaskObservation({store,receipt:recovered,api});const task=await observer.observe();assert.equal(task.status,'needs_resume');assert.equal(posts,1);assert.equal(gets,1);assert.equal(resumes,0);await assert.rejects(observer.resume({configuration:{protocol:'replicate-sam2-native',configured:true,version:'new-version'}}),/配置或模型版本/);assert.equal(resumes,0);await observer.resume({configuration:{protocol:'replicate-sam2-native',configured:true,version:'fixed-v1',providerFingerprint:'fixed-origin'}});assert.equal(resumes,1);
});
test('receipt isolated by project/node rejects conflict, source changes, clip, mask and same-id object substitution',async()=>{
 const m=await modules();for(const change of ['project','source','clip','mask','content','object']){const f=fixture(),receipt=m.createSegmentationReceipt(options(f));if(change==='project')f.switchProject();if(change==='source')f.node.video='asset:replacement';if(change==='clip')f.node.clip.end=.9;if(change==='mask')f.node.videoMask={asset:'asset:other'};if(change==='content')f.node.sourceFileId='other';if(change==='object')f.state.nodes[0]={...f.node};assert.throws(()=>m.assertReceiptCurrent(f.app,f.node,receipt),/变化/);}
 const f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));store.save(receipt);assert.equal(store.read('q','n'),null);assert.equal(store.read('p','other'),null);const copy=structuredClone(receipt);store.save(receipt);assert.throws(()=>store.save(copy),/另一窗口/);assert.throws(()=>store.remove(copy),/变化/);
});
test('completed full-source mask uses actual save, beforeCommit and flush; failed save retries one asset and mutation',async()=>{
 const m=await modules(),f=fixture(),receipt=m.createSegmentationReceipt(options(f)),journal=m.createReceiptStore(f.storage);journal.save(receipt);let puts=0,saves=0,flushes=0;const mask={width:4,height:2,fps:2,frames:['0 2','6 2']},media={width:4,height:2,duration:1};const application=m.createMaskApplication({app:f.app,node:f.node,receipt,receiptStore:journal,localAssets:{put:async()=>{puts++;return 'asset:mask';}},store:{save:async(snapshot,project,{beforeCommit})=>{saves++;assert.equal(snapshot.nodes[0],f.node);assert.equal(project,'p');assert.equal(beforeCommit(),true);if(saves===1)throw Error('disk failure');},flush:async()=>flushes++}});
 await assert.rejects(application.apply(mask,media),/disk failure/);assert.equal(receipt.status,'intent');assert.equal(f.updates,1);assert.equal(journal.read('p','n').maskAsset,'asset:mask');await application.apply(mask,media);assert.equal(f.updates,1);assert.equal(puts,1);assert.equal(saves,2);assert.equal(flushes,1);assert.equal(receipt.status,'applied');assert.equal(f.node.videoMask.timeline,'full-source');assert.equal(f.node.videoMask.duration,1);assert.equal(f.node.videoMask.time,.5);assert.equal(f.node.clip.start,.5);
});
test('hydrated pending mask asset reuses the already applied patch; stale beforeCommit rejects an old project',async()=>{
 const m=await modules(),f=fixture(),receipt=m.createSegmentationReceipt(options(f)),mask={width:4,height:2,fps:2,frames:['0 2','6 2']},media={width:4,height:2,duration:1};receipt.maskAsset='asset:mask';f.node.videoMask={source:receipt.source,clip:receipt.clip,asset:receipt.maskAsset,time:.5,width:4,height:2,duration:1,timeline:'full-source',taskId:ID};let saves=0;const application=m.createMaskApplication({app:f.app,node:f.node,receipt,localAssets:{put:()=>assert.fail('duplicate asset')},store:{save:async(_s,_id,{beforeCommit})=>{saves++;f.switchProject();beforeCommit();},flush:()=>assert.fail('stale flush')}});await assert.rejects(application.apply(mask,media),/变化/);assert.equal(f.updates,0);assert.equal(saves,1);
});
test('native transport posts only with UUID header and GET/resume/cancel remain separate same-origin routes',async()=>{
 const {nativeTasksProvider}=await import('../src/features/video-mask/segmentation.mjs'),calls=[];const api=nativeTasksProvider({fetchImpl:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({id:ID,protocol:'replicate-sam2-native',status:'unknown'})};}});await api.create({kind:'video.segment'},{idempotencyKey:ID});await api.get(ID);await api.resume(ID);await api.cancel(ID);assert.deepEqual(calls.map(c=>[c.url,c.options.method]),[['/api/video-segmentation/tasks','POST'],['/api/video-segmentation/tasks/'+ID,'GET'],['/api/video-segmentation/tasks/'+ID+'/resume','POST'],['/api/video-segmentation/tasks/'+ID+'/cancel','POST']]);assert.equal(calls[0].options.headers['Idempotency-Key'],ID);assert.equal(calls[0].options.headers.Authorization,undefined);assert.equal(calls[1].options.body,undefined);assert.ok(calls.every(c=>c.options.redirect==='error'));
});
test('actual source bytes bind the receipt to server archival SHA256 and reject a different native source',async()=>{
 const m=await modules(),digest=await m.fingerprintSourceData('data:video/mp4;base64,YWJj');assert.equal(digest,'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');const f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f));receipt.inputSha256=digest;const observer=m.createTaskObservation({store,receipt,api:{get:async()=>({id:ID,status:'succeeded',version:'fixed-v1',providerFingerprint:'fixed-origin',source:{sha256:'wrong'}})}});await assert.rejects(observer.observe(),/来源字节/);await assert.rejects(m.fingerprintSourceData('https://example.test/video.mp4'),/实际视频字节/);
});
test('inline node media remains out of recovery receipts while source changes still invalidate the receipt',async()=>{
 const m=await modules(),f=fixture();f.node.video='data:video/mp4;base64,YWJj';f.node.image='data:image/png;base64,aW1hZ2U=';f.node.videoMask={source:f.node.video,asset:'asset:old'};const receipt=m.createSegmentationReceipt(options(f));const json=JSON.stringify(receipt);assert.equal(json.includes('YWJj'),false);assert.equal(json.includes('aW1hZ2U='),false);m.assertReceiptCurrent(f.app,f.node,receipt);f.node.video='data:video/mp4;base64,YWJk';assert.throws(()=>m.assertReceiptCurrent(f.app,f.node,receipt),/变化/);
});
test('late original task response after abort cannot publish status, save a completed receipt or poll again',async()=>{
 const m=await modules(),f=fixture(),store=m.createReceiptStore(f.storage),receipt=m.createSegmentationReceipt(options(f)),controller=new AbortController();let finish,started,onStatus=0,gets=0;const began=new Promise(resolve=>started=resolve);const observer=m.createTaskObservation({store,receipt,onStatus:()=>onStatus++,api:{create:async()=>{started();return new Promise(resolve=>finish=resolve);},get:()=>gets++}});const pending=observer.create({},{signal:controller.signal});await began;controller.abort();finish({id:ID,status:'succeeded',version:'fixed-v1',providerFingerprint:'fixed-origin'});await assert.rejects(pending,{name:'AbortError'});assert.equal(onStatus,0);assert.equal(gets,0);assert.equal(store.read('p','n').status,'unknown');
});
test('actual applied loadMask rejects changed source fingerprint after reopening and during awaited mask read',async()=>{
 const initial=await maskLoaderFixture();initial.f.node.sourceFileId='source-v2';await initial.load();assert.match(initial.editor.lastError,/来源或项目已变化/);assert.equal(initial.editor.mask,undefined);assert.equal(initial.reads,0);assert.equal(initial.paints,0);
 const delayed=await maskLoaderFixture({duringRead:f=>f.node.sourceFileId='source-v2'});await delayed.load();assert.match(delayed.editor.lastError,/来源或项目已变化/);assert.equal(delayed.editor.mask,undefined);assert.equal(delayed.decodes,0);assert.equal(delayed.paints,0);
});
test('actual applied loadMask rereads mutable source bytes and rejects mismatched SHA256 before mask display',async()=>{
 const changed=await maskLoaderFixture({mutable:true,transportData:'data:video/mp4;base64,YWJk'});await changed.load();assert.equal(changed.transports,1);assert.equal(changed.reads,0);assert.equal(changed.editor.mask,undefined);assert.equal(changed.paints,0);assert.match(changed.editor.lastError,/实际字节已变化/);
 const current=await maskLoaderFixture({mutable:true});await current.load();assert.equal(current.transports,1);assert.equal(current.reads,1);assert.equal(current.editor.mask.frames.length,2);assert.equal(current.paints,1);assert.equal(current.editor.lastError,undefined);
});
test('actual applied loadMask rejects a receipt that changes while reading its mask',async()=>{
 const changed=await maskLoaderFixture({duringRead:(_f,receipt)=>receipt.status='succeeded'});await changed.load();assert.equal(changed.editor.mask,undefined);assert.equal(changed.paints,0);assert.match(changed.editor.lastError,/任务记录已变化/);
});
test('actual unsubmitted intent recovery rejects a changed provider fingerprint before paid POST',async()=>{
 const m=await modules(),source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/features/video-mask/ui.mjs'),'utf8'),start=source.indexOf('  async recoverRecognition('),end=source.indexOf('  async finishTask(',start),recover=Function('segmentation','assertResumeConfiguration','return ({'+source.slice(start,end)+'}).recoverRecognition')({refreshConfiguration:async()=>({protocol:'replicate-sam2-native',configured:true,version:'fixed-v1',providerFingerprint:'other-account'})},m.assertResumeConfiguration);
 let posts=0;const editor={taskReceipt:{dispatched:false,modelVersion:'fixed-v1',providerFingerprint:'old-account',rect:{x:0,y:0,width:.5,height:.5},time:.5,taskId:ID},pendingSegmentationRequest:{kind:'video.segment'},ready:true,alive:true,video:{pause(){},currentTime:0},listeners:new AbortController(),paint(){},selectionGuard:()=>()=>{},receiptGuard(){},consent:async()=>true,observation:()=>({create:async()=>{posts++;throw Error('paid POST happened');}}),error(message){this.lastError=message;}};await recover.call(editor);assert.equal(posts,0);assert.match(editor.lastError,/配置或模型版本已变化/);assert.equal(editor.taskReceipt.taskId,ID);
});
test('actual applied editor guard blocks source metadata drift while preserving another mask task contract',async()=>{
 const m=await modules(),f=fixture();f.node.sourceFileId='source-v1';const receipt=m.createSegmentationReceipt(options(f));receipt.status='applied';receipt.maskAsset='asset:mask';f.node.videoMask={asset:'asset:mask',taskId:ID};const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/features/video-mask/ui.mjs'),'utf8'),start=source.indexOf('  guard(){'),end=source.indexOf('  async readiness(',start),guard=Function('assertReceiptCurrent','app','mediaSource','return ({'+source.slice(start,end)+'}).guard')(m.assertReceiptCurrent,f.app,node=>node.video),editor={taskReceipt:receipt,sourceNode:f.node,sourceGuard(){}};guard.call(editor);f.node.sourceFileId='source-v2';assert.throws(()=>guard.call(editor),/来源或项目已变化/);f.node.videoMask.taskId='different-old-task';assert.doesNotThrow(()=>guard.call(editor));
});
test('actual editor placement bounds the scrollable recovery panel within short viewports and keeps source geometry',()=>{
 const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../src/features/video-mask/ui.mjs'),'utf8'),start=source.indexOf('  place(){'),end=source.indexOf('  bindSelection(){',start);for(const viewportHeight of [720,480,240]){const node={x:405,y:168,width:469,height:264},app={getState:()=>({view:{x:0,y:0,scale:1}})},place=Function('app','document','innerWidth','innerHeight','return ({'+source.slice(start,end)+'}).place')(app,{querySelector:()=>({getBoundingClientRect:()=>({left:0,top:0})})},1280,viewportHeight),editor={alive:true,node:()=>node,root:{style:{}},panel:{style:{}}};place.call(editor);assert.equal(editor.root.style.top,'168px');assert.equal(editor.root.style.height,'264px');assert.equal(editor.panel.style.width,'500px');const top=168+parseFloat(editor.panel.style.top),height=parseFloat(editor.panel.style.maxHeight);assert.ok(top>=16);assert.ok(top+height<=viewportHeight-16);assert.ok(height>=Math.min(220,viewportHeight-32));if(viewportHeight===720)assert.equal(top,444);}
});
