const test=require('node:test'),assert=require('node:assert/strict');
const {TaskService}=require('../generation-api.js');
const config={configured:true,protocol:'fal-video-mask-native',capabilities:{kinds:['video.erase','video.replace'],models:{'video.erase':{kind:'video.erase'},'video.replace':{kind:'video.replace'}},videoMask:{semantics:'explicit-native-alternative',temporalMask:true,maskEncoding:'rle-zero-based-row-major',preservesSourceAudio:'local-remux',resolution:'720p',aspectRatio:'adaptive',maxCount:1,sourceFrames:{min:81,max:241},sourceFps:{min:5,max:30}}}};
const mask={encoding:'rle-zero-based-row-major',width:320,height:180,fps:30,frames:Array.from({length:240},(_,i)=>`${(20+Math.floor(i/10))*320+40} 20`)};
async function request(mode='remove'){const {editRequest}=await import('../src/features/video-mask/core.mjs');return editRequest({id:'source',clip:{start:1,end:5}},mode,'asset:source',mask,mode==='replace'?{nodeId:'reference',url:'asset:replacement'}:null);}
test('native readiness discloses independent alternative, actual upload types and fixed action mapping',async()=>{const {maskedVideoRequestState}=await import('../src/features/video-mask/native-profile.mjs');for(const mode of ['remove','replace']){const state=maskedVideoRequestState(config,await request(mode));assert.equal(state.ready,true);assert.match(state.hint,/独立替代.*Wan VACE.*上传来源片段、蒙层/);if(mode==='replace')assert.match(state.hint,/替换图片.*按参考图替换.*原尺寸转 PNG/);else assert.match(state.hint,/按所选目标移除/);}});
test('unconfigured, incomplete native fidelity, excessive source frames and fps reject before media read',async()=>{const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs'),r=await request();for(const mutate of [m=>m.configured=false,m=>delete m.capabilities.videoMask,m=>m.capabilities.videoMask.preservesSourceAudio=false,m=>m.capabilities.videoMask.sourceFrames.max=100,m=>m.capabilities.videoMask.maxFullMaskFrames=239,m=>m.capabilities.videoMask.sourceFps.max=24]){const m=structuredClone(config);mutate(m);await assert.rejects(()=>prepareMaskedVideoMedia(r,{nativeConfiguration:m,resolveMedia:()=>assert.fail('must not read'),transport:()=>assert.fail('must not transport')}));}});
test('source and replacement resolve only after preflight, retaining full mask and sourceClip for server joint crop',async()=>{const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs'),r=await request('replace');let reads=0,checks=0;const result=await prepareMaskedVideoMedia(r,{nativeConfiguration:config,validateSources:()=>checks++,resolveMedia:async node=>{reads++;assert.equal(node.clip,undefined);return {url:node.type==='video'?'data:video/mp4;base64,AAAA':'data:image/png;base64,AAAA',width:node.type==='video'?320:512,height:node.type==='video'?180:512,...node.type==='video'?{duration:8}:{}};},transport:async input=>input,normalizeReference:async input=>input});assert.equal(reads,2);assert(checks>=5);assert.deepEqual(result.parameters.sourceClip,{start:1,end:5});assert.deepEqual(result.parameters.mask,mask);assert.equal(result.inputs[0].durationMs,8000);assert.equal(r.inputs[0].duration,undefined);assert.equal(result.inputs[1].role,'replacement_image');});
test('mismatched actual full source timeline or cancelled/source-changed media cannot transport',async()=>{const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs'),r=await request();for(const actual of [{url:'data:video/mp4;base64,AAAA',width:320,height:180,duration:6},{url:'data:video/mp4;base64,AAAA',width:640,height:360,duration:8}])await assert.rejects(()=>prepareMaskedVideoMedia(r,{nativeConfiguration:config,resolveMedia:async()=>actual,transport:()=>assert.fail('no transmit')}));for(const cancel of [true,false]){let changed=false;const controller=new AbortController();await assert.rejects(()=>prepareMaskedVideoMedia(r,{signal:controller.signal,nativeConfiguration:config,validateSources:()=>{if(changed)throw Error('source changed');},resolveMedia:async()=>{if(cancel)controller.abort(Error('cancelled'));else changed=true;return {url:'data:video/mp4;base64,AAAA',width:320,height:180,duration:8};},transport:()=>assert.fail('no transmit')}),/cancelled|source changed/);}});
test('project, node identity, clip, mask and fullImage replacement guards reject delayed ownership changes',async()=>{const {sourceGuard}=await import('../src/features/video-mask/core.mjs');for(const mutation of ['project','source','replace-source','clip','mask','image','replace-image','closed','reference-clear']){const node={id:'source',video:'asset:video',videoMask:{asset:'asset:mask'}},image={id:'ref',image:'small',fullImage:'asset:full'},nodes=[node,image],ref={nodeId:'ref',url:'asset:full'};let project='a',alive=true,current=ref;const app={projectIdentity:()=>({id:project}),getState:()=>({nodes})},guard=sourceGuard(app,node,{isAlive:()=>alive,maskAsset:'asset:mask',reference:ref,referenceNode:image,getReference:()=>current});guard();if(mutation==='project')project='b';if(mutation==='source')node.video='other';if(mutation==='replace-source')nodes[0]={...node};if(mutation==='clip')node.clip={start:1,end:5};if(mutation==='mask')node.videoMask.asset='new';if(mutation==='image')image.fullImage='other';if(mutation==='replace-image')nodes[1]={...image};if(mutation==='closed')alive=false;if(mutation==='reference-clear')current=null;assert.throws(guard,/变化|已取消/);}});
test('production TaskService unconfigured or async guard failure prevents all preparation and dispatch',async()=>{const c=await import('../src/features/video-mask/core.mjs');for(const change of ['unconfigured','project','replace-image']){const node={id:'source',video:'asset:source',videoMask:{asset:'asset:mask'}},image={id:'ref',fullImage:'asset:replacement'},nodes=[node,image];let project='a',release,start,reads=0,posts=0;const pending=new Promise(r=>release=r),started=new Promise(r=>start=r),app={projectIdentity:()=>({id:project}),getState:()=>({nodes})},guard=c.sourceGuard(app,node,{maskAsset:'asset:mask',reference:{nodeId:'ref',url:'asset:replacement'},referenceNode:image}),service=new TaskService({prepareInputs:()=>{reads++;assert.fail('no read');}});service.setProvider({isConfigured:async()=>{start();await pending;return change!=='unconfigured';},generate:()=>{posts++;assert.fail('no dispatch');}});const job=service.submit(await request('replace'),{beforeDispatch:guard});await started;if(change==='project')project='b';if(change==='replace-image')nodes[1]={...image};release();for(let i=0;i<20&&job.status==='queued';i++)await new Promise(r=>setImmediate(r));assert.equal(job.status,change==='unconfigured'?'configuration_required':'failed');assert.equal(reads,0);assert.equal(posts,0);}});

test('unaligned clip boundaries, clip beyond full timeline and target outside selection reject before reading',async()=>{
 const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs');for(const change of [r=>r.parameters.sourceClip={start:1.01,end:5.01},r=>r.parameters.sourceClip={start:4,end:8.01},r=>r.parameters.mask.frames=r.parameters.mask.frames.map((_x,i)=>i<30?'0 1':'')]){const r=structuredClone(await request());change(r);await assert.rejects(()=>prepareMaskedVideoMedia(r,{nativeConfiguration:config,resolveMedia:()=>assert.fail('must not read'),transport:()=>assert.fail('must not transmit')}));}
});

test('native replacement PNG normalization decodes all accepted formats, preserves pixels/geometry and rejects changed or oversized images',async()=>{
 const {normalizeMaskReference}=await import('../src/features/video-mask/reference-png.mjs');for(const mime of ['image/jpeg','image/webp','image/png']){let decoded=0,drawn=0,closed=0;const result=await normalizeMaskReference({url:'data:'+mime+';base64,AAAA',width:512,height:256},{fetchImpl:async()=>({ok:true,blob:async()=>new Blob(['pixels'],{type:mime})}),decode:async blob=>{assert.equal(blob.type,mime);decoded++;return {width:512,height:256,close:()=>closed++};},canvasFactory:()=>({getContext:()=>({drawImage:(_bitmap,x,y)=>{assert.deepEqual([x,y],[0,0]);drawn++;}}),toBlob:(callback,type)=>callback(new Blob(['PNG'],{type}))}),serialize:async png=>{assert.equal(png.type,'image/png');return 'data:image/png;base64,UE5H';}});assert.equal(result.url,'data:image/png;base64,UE5H');assert.deepEqual([result.width,result.height],[512,256]);assert.deepEqual([decoded,drawn,closed],[1,1,1]);}
 for(const bad of ['changed','oversize','cancel']){let closed=0;const controller=new AbortController();await assert.rejects(()=>normalizeMaskReference({url:'data:image/png;base64,AAAA',width:512,height:256},{signal:controller.signal,maxBytes:bad==='oversize'?1:100,fetchImpl:async()=>({ok:true,blob:async()=>new Blob(['PNG'],{type:'image/png'})}),decode:async()=>{if(bad==='cancel')controller.abort(Error('cancelled'));return {width:1024,height:256,close:()=>closed++};},canvasFactory:()=>assert.fail('no render')}));assert.equal(closed,bad==='oversize'?0:1);}
});
test('PNG conversion occurs only for selected native protocol and remains guarded after conversion',async()=>{
 const {prepareMaskedVideoMedia}=await import('../src/features/video-mask/media.mjs');for(const protocol of ['tasks-v1','fal-video-mask-native']){let conversions=0;const m=structuredClone(config);m.protocol=protocol;const result=await prepareMaskedVideoMedia(await request('replace'),{nativeConfiguration:m,resolveMedia:async node=>({url:node.type==='video'?'data:video/mp4;base64,AAAA':'data:image/jpeg;base64,AAAA',width:node.type==='video'?320:512,height:node.type==='video'?180:512,...node.type==='video'?{duration:8}:{}}),transport:async input=>input,normalizeReference:async input=>{conversions++;return {...input,url:'data:image/png;base64,AAAA'};}});assert.equal(conversions,protocol==='tasks-v1'?0:1);assert.match(result.inputs[1].url,protocol==='tasks-v1'?/image\/jpeg/:/image\/png/);}
 const r=await request('replace');let changed=false;await assert.rejects(()=>prepareMaskedVideoMedia(r,{nativeConfiguration:config,validateSources:()=>{if(changed)throw Error('reference changed');},resolveMedia:async node=>({url:'data:'+node.type+'/png;base64,AAAA',width:node.type==='video'?320:512,height:node.type==='video'?180:512,...node.type==='video'?{duration:8}:{}}),transport:async input=>input,normalizeReference:async input=>{changed=true;return input;}}),/reference changed/);
});
