'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{createHash,randomUUID}=require('node:crypto'),zlib=require('node:zlib'),{spawnSync}=require('node:child_process');
const {createReplicateSam2SegmentationService}=require('../server/video-segmentation-replicate.cjs');
const {createReplicateSegmentationTransport,SAM2_VERSION}=require('../server/video-segmentation-replicate-transport.cjs');
const {createVideoSegmentationAdapter}=require('../server/video-segmentation.cjs');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),token='sam2-fixture-private-token';
function crc(buffer){let n=0xffffffff;for(const b of buffer){n^=b;for(let i=0;i<8;i++)n=n&1?(n>>>1)^0xedb88320:n>>>1;}return (n^0xffffffff)>>>0;}
function chunk(type,data){const typeBytes=Buffer.from(type),out=Buffer.alloc(12+data.length);out.writeUInt32BE(data.length);typeBytes.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([typeBytes,data])),8+data.length);return out;}
function png(index){const header=Buffer.alloc(13);header.writeUInt32BE(4);header.writeUInt32BE(2,4);header[8]=8;const raw=Buffer.alloc(10);raw[index<4?index+1:index+2]=255;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
const mediaResult=spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','color=c=black:s=4x2:r=2:d=1.5','-an','-c:v','libx264rgb','-crf','0','-movflags','frag_keyframe+empty_moov','-f','mp4','pipe:1'],{maxBuffer:1024*1024});
assert.equal(mediaResult.status,0,mediaResult.stderr?.toString());const sourceBytes=mediaResult.stdout;
const input={kind:'video.segment',nodeId:'test-node',sourceVideoUrl:'data:video/mp4;base64,'+sourceBytes.toString('base64'),width:4,height:2,duration:1.5,time:.5,selection:{x:.25,y:0,width:.5,height:1},pointPrompts:[{x:2,y:1,time:.5,label:1}]};
const mediaTools={async prepareSegmentationMedia(){return {source:{sha256:sha(sourceBytes),width:4,height:2,fps:2,numFrames:3,duration:1.5,pts:[0,.5,1]},prompt:{frameIndex:1,time:.5,pts:.5,x:2,y:1},branches:['forward','reverse'].map(direction=>({direction,mime:'video/mp4',bytes:sourceBytes,sha256:sha(sourceBytes),firstFrameSha256:sha(Buffer.alloc(24)),numFrames:2,sourceIndices:direction==='forward'?[1,2]:[1,0]}))};}};
async function fixture(t,{losePost=false,immediate=false,secondFailure=false,badVersion=false,echoToken=false,expired=false,outputFailure=false,cancelStatus='canceled',blockedSecondUpload=false,blockedPrediction=false,secondUploadFails=false,holdForwardTailDownload=false}={}){
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'sam2-native-')),predictions=new Map(),calls=[],downloadCalls=[];let files=0,posts=0,polls=0,cancels=0,downloads=0,allowDownload=!outputFailure,releaseForwardTail;const forwardTailGate=new Promise(resolve=>releaseForwardTail=resolve);
 const server=http.createServer(async(req,res)=>{const parts=[];for await(const part of req)parts.push(part);const raw=Buffer.concat(parts);calls.push({method:req.method,path:req.url,authorization:req.headers.authorization});const json=value=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(value));};
  if(req.url==='/v1/files'){files++;if(secondUploadFails&&files===2){res.writeHead(413,{'Content-Type':'application/json'});res.end(JSON.stringify({detail:'Files must be less than 100MB in size'}));return;}if(blockedSecondUpload&&files===2)return;assert.match(raw.toString(),/name="content"; filename="(forward|reverse)\.mp4"/);const boundary=/boundary=(.*)$/.exec(req.headers['content-type'])[1],prefix=raw.indexOf('\r\n\r\n')+4,suffix=raw.indexOf('\r\n--'+boundary,prefix),bytes=raw.subarray(prefix,suffix);return json({id:'File-'+files,content_type:'video/mp4',size:bytes.length,checksums:{sha256:sha(bytes)},expires_at:new Date(Date.now()+3600000).toISOString(),urls:{get:'https://api.replicate.com/v1/files/File-'+files}});}
  if(req.url==='/v1/predictions'&&req.method==='POST'){posts++;const request=JSON.parse(raw),id='prediction'+posts,output=['https://replicate.delivery/run'+posts+'/frame_00000.png','https://replicate.delivery/run'+posts+'/frame_00001.png'],status=secondFailure&&posts===2?'failed':immediate?'succeeded':'processing';const value={id,model:'meta/sam-2-video',version:badVersion?'bad':request.version,input:request.input,status,output,...(echoToken?{logs:token}:{})};predictions.set(id,value);if(blockedPrediction)return;if(losePost){req.socket.destroy();return;}return json(value);}
  const match=/^\/v1\/predictions\/(prediction\d+)(\/cancel)?$/.exec(req.url);if(match){const value=predictions.get(match[1]);if(match[2]){cancels++;return json({...value,status:cancelStatus});}polls++;return json({...value,version:SAM2_VERSION,status:value.status==='failed'?'failed':'succeeded',...(expired?{data_removed:true}:{}),logs:undefined});}
  if(req.url.startsWith('/run')){if(holdForwardTailDownload&&req.url==='/run1/frame_00001.png')await forwardTailGate;downloads++;downloadCalls.push(req.headers.authorization);if(!allowDownload&&downloads===2){res.writeHead(404);res.end();return;}return res.end(png(req.url.startsWith('/run1')?(req.url.endsWith('00000.png')?0:1):(req.url.endsWith('00000.png')?0:2)));}
  res.writeHead(404);res.end();
 });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const local='http://127.0.0.1:'+server.address().port;
 const fetchImpl=async(url,options)=>{assert.equal(new URL(url).origin,'https://api.replicate.com');assert.equal(options.headers.Authorization,'Bearer '+token);assert.equal(options.redirect,'error');return fetch(local+new URL(url).pathname,options);};
 const downloader={async download(url,{kind,onBytes=()=>{}}){let bytes;if(url.startsWith('data:'))bytes=sourceBytes;else {assert.equal(new URL(url).hostname,'replicate.delivery');const reply=await fetch(local+new URL(url).pathname);if(!reply.ok)throw Object.assign(Error('private'),{code:'media_download_not_found'});bytes=Buffer.from(await reply.arrayBuffer());}return {mime:kind==='source'?'video/mp4':'image/png',stream:(async function*(){onBytes(bytes.length);yield bytes;})(),close(){}};}};
 const prepareRequest=createVideoSegmentationAdapter().prepareRequest||(async request=>{const {segmentationRequest}=await import('../src/features/video-mask/core.mjs');return segmentationRequest({nodeId:request.nodeId,source:request.sourceVideoUrl,rect:request.selection,time:request.time,width:request.width,height:request.height,duration:request.duration});});
 const options={directory,apiKey:token,mediaTools,prepareRequest,fetchImpl,downloader};let service=createReplicateSam2SegmentationService(options);await service.ready;
 t.after(async()=>{await service.close();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true});});
 async function wait(id,predicate=task=>task.status!=='preparing'&&task.branches.length&&task.branches.every(b=>!['pending','uploading','dispatching'].includes(b.status))){const deadline=Date.now()+5000;for(;;){const record=JSON.parse(await fs.readFile(path.join(directory,id+'.json'),'utf8')),task={...record,branches:record.branches.map(branch=>({...branch,downloadedFrames:branch.archives.length}))};if(predicate(task)){await new Promise(resolve=>setTimeout(resolve,25));return task;}if(Date.now()>deadline)throw Error('Fixture wait timed out '+JSON.stringify(task));await new Promise(resolve=>setTimeout(resolve,5));}}
 return {directory,options,calls,downloadCalls,releaseForwardTail,stats:()=>({files,posts,polls,cancels,downloads}),service:()=>service,wait,allowDownload:()=>allowDownload=true,async restart(overrides={}){await service.close();service=createReplicateSam2SegmentationService({...options,...overrides});await service.ready;return service;}};
}
test('native HTTP fixtures archive every real PNG and merge exact full-source timeline; idempotent receipt never dispatches again',async t=>{const f=await fixture(t,{immediate:true}),id=randomUUID();const initial=await f.service().createTask(input,{idempotencyKey:id});assert.equal(initial.id,id);const task=await f.wait(id,task=>task.status==='succeeded');assert.deepEqual(task.mask.frames,['2 1','0 1','1 1']);assert.equal(f.stats().posts,2);assert.equal(task.branches[0].downloadedFrames,2);assert.equal(f.downloadCalls.every(value=>value===undefined),true);await f.service().createTask(input,{idempotencyKey:id});assert.equal(f.stats().posts,2);await assert.rejects(f.service().createTask({...input,time:1,pointPrompts:[{...input.pointPrompts[0],time:1}]},{idempotencyKey:id}),{code:'segmentation_identity_mismatch'});const text=await fs.readFile(path.join(f.directory,id+'.json'),'utf8');assert.ok(!text.includes(token)&&!text.includes('data:video')&&!JSON.stringify(await f.service().getTask(id)).includes('https://'));await f.restart();assert.equal((await f.service().getTask(id)).status,'succeeded');assert.equal(f.stats().posts,2);});
test('lost first prediction POST remains unknown across GET, duplicate create, explicit resume and restart; no second POST',async t=>{const f=await fixture(t,{losePost:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});const task=await f.wait(id,task=>task.status==='unknown');assert.equal(task.branches[0].predictionId,undefined);assert.equal(f.stats().posts,1);await f.service().getTask(id);await f.service().createTask(input,{idempotencyKey:id});await assert.rejects(f.service().resumeTask(id),{code:'segmentation_resume_forbidden'});await f.restart();assert.equal((await f.service().getTask(id)).status,'unknown');assert.equal(f.stats().posts,1);});
test('restart polls original known IDs without new POST and explicitly resumes a pending second branch',async t=>{const f=await fixture(t,{badVersion:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});const unknown=await f.wait(id,task=>task.status==='unknown');assert.equal(unknown.branches[0].predictionId,'prediction1');assert.equal(f.stats().posts,1);await f.restart();const recovered=await f.service().getTask(id);assert.equal(recovered.status,'needs_resume');assert.equal(recovered.canResume,true);assert.equal(recovered.branches[0].downloadedFrames,2);assert.equal(f.stats().posts,1);await f.service().resumeTask(id);await f.wait(id,task=>task.status==='unknown');assert.equal(f.stats().posts,2);assert.equal((await f.service().getTask(id)).status,'succeeded');});
test('legal prediction identity persists before echoed credential rejection, then same-ID GET recovers without extra inference',async t=>{const f=await fixture(t,{echoToken:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});const unknown=await f.wait(id,task=>task.status==='unknown');assert.equal(unknown.branches[0].predictionId,'prediction1');assert.equal(f.stats().posts,1);assert.ok(!(await fs.readFile(path.join(f.directory,id+'.json'),'utf8')).includes(token));const recovered=await f.service().getTask(id);assert.equal(recovered.status,'needs_resume');assert.equal(f.stats().posts,1);});
test('partial successful output archive is resumable locally without POST and full mask stays withheld',async t=>{const f=await fixture(t,{immediate:true,outputFailure:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});const partial=await f.wait(id,task=>task.status==='unknown');assert.equal(partial.branches[0].downloadedFrames,1);assert.equal(partial.mask,undefined);assert.equal(f.stats().posts,1);await f.restart();f.allowDownload();const task=await f.service().getTask(id);assert.equal(task.status,'needs_resume');assert.equal(task.branches[0].downloadedFrames,2);assert.equal(f.stats().posts,1);await f.service().resumeTask(id);await f.wait(id,task=>task.status==='succeeded');assert.equal(f.stats().posts,2);});
test('failed sibling preserves querying and archiving the already-paid running prediction',async t=>{const f=await fixture(t,{secondFailure:true,cancelStatus:'succeeded'}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='failed'&&task.branches[0].status==='archived');const task=await f.service().getTask(id);assert.equal(task.status,'failed');assert.equal(task.branches[0].status,'archived');assert.equal(task.mask,undefined);assert.equal(f.stats().posts,2);assert.equal(f.stats().polls,1);});
test('cancel covers both known prediction IDs and reports remote terminal separately from cancellation',async t=>{const f=await fixture(t,{cancelStatus:'succeeded'}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='running'&&task.branches.every(b=>b.predictionId));const task=await f.service().cancelTask(id);assert.equal(task.status,'cancelled');assert.equal(task.remoteCancellation,'confirmed');assert.equal(task.branches.every(b=>b.remoteCancellation==='already_terminal'),true);assert.equal(f.stats().cancels,2);await f.service().getTask(id);assert.equal(f.stats().posts,2);});
test('expired prediction output never creates a replacement task',async t=>{const f=await fixture(t,{expired:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='running'&&task.branches.every(b=>b.predictionId));const task=await f.service().getTask(id);assert.equal(task.status,'unknown');assert.equal(task.code,'segmentation_output_expired');assert.equal(task.mask,undefined);assert.equal(f.stats().posts,2);await assert.rejects(f.service().resumeTask(id),{code:'segmentation_resume_forbidden'});});
test('native localhost task routes expose safe receipt, GET requires existing ID and create requires pre-saved UUID',async t=>{const f=await fixture(t,{immediate:true});const server=http.createServer((req,res)=>f.service().handle(req,res,new URL(req.url,'http://localhost').pathname,{json:(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));},body:async(req)=>{const parts=[];for await(const part of req)parts.push(part);return JSON.parse(Buffer.concat(parts));}}));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const local='http://127.0.0.1:'+server.address().port,id=randomUUID();assert.equal((await fetch(local+'/api/video-segmentation/tasks/'+id)).status,404);assert.equal(f.stats().posts,0);assert.equal((await fetch(local+'/api/video-segmentation/tasks',{method:'POST',headers:{'X-Segmentation-Model-Version':f.service().config().version,'X-Segmentation-Provider-Fingerprint':f.service().config().providerFingerprint},body:JSON.stringify(input)})).status,400);const response=await fetch(local+'/api/video-segmentation/tasks',{method:'POST',headers:{'Idempotency-Key':id,'X-Segmentation-Model-Version':f.service().config().version,'X-Segmentation-Provider-Fingerprint':f.service().config().providerFingerprint},body:JSON.stringify(input)});assert.equal(response.status,202);assert.equal((await response.json()).id,id);await f.wait(id,task=>task.status==='succeeded');const receipt=await fetch(local+'/api/video-segmentation/tasks/'+id);assert.ok(!(await receipt.text()).includes(token));});
test('changed credential fingerprint blocks recovery; corrupted archived pixels are not published after restart',async t=>{const f=await fixture(t,{immediate:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='succeeded');await fs.writeFile(path.join(f.directory,'files',id,'forward-0.png'),png(3));await f.restart();const task=await f.service().getTask(id);assert.equal(task.status,'failed');assert.equal(task.code,'segmentation_archive_integrity');assert.equal(task.mask,undefined);assert.equal(f.stats().posts,2);});
test('transport rejects wrong model/version/id, external upload references and credential result links without contacting them',async()=>{let calls=0,saved;const base={id:'prediction1',model:'meta/sam-2-video',version:SAM2_VERSION,input:{},status:'succeeded',output:['https://replicate.delivery/frame_00000.png']};for(const extra of [{model:'other/model'},{version:'bad'},{output:['https://other.test/frame_00000.png']},{output:['https://replicate.delivery/frame_00000.png?token='+token]}]){const transport=createReplicateSegmentationTransport({apiKey:token,fetchImpl:async()=>{calls++;return Response.json({...base,...extra});}});await assert.rejects(transport.submit({},{onIdentity:async id=>saved=id}),error=>/^segmentation_/.test(error.code)&&!error.message.includes(token));assert.equal(saved,'prediction1');}assert.equal(calls,4);});

test('close during second upload preserves first archive and requires explicit resume after restart',async t=>{const f=await fixture(t,{immediate:true,blockedSecondUpload:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.branches[0]?.status==='archived'&&task.branches[1]?.status==='uploading');await f.restart();const pending=await f.service().getTask(id);assert.equal(pending.status,'needs_resume');assert.equal(pending.branches[0].downloadedFrames,2);assert.equal(f.stats().posts,1);await f.service().resumeTask(id);await f.wait(id,task=>task.status==='succeeded');assert.equal(f.stats().posts,2);});
test('close in persisted POST intent without receipt restores unknown and never retries',async t=>{const f=await fixture(t,{blockedPrediction:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.branches[0]?.status==='dispatching');await f.restart();const unknown=await f.service().getTask(id);assert.equal(unknown.status,'unknown');assert.equal(unknown.branches[0].predictionId,undefined);await assert.rejects(f.service().resumeTask(id),{code:'segmentation_resume_forbidden'});assert.equal(f.stats().posts,1);assert.equal(f.stats().files,1);});
test('account credential change refuses known-ID query or pending-branch resume before any network',async t=>{const f=await fixture(t,{badVersion:true}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='unknown');await f.restart({apiKey:'changed-account-fixture-token'});await assert.rejects(f.service().getTask(id),{code:'segmentation_provider_changed'});await assert.rejects(f.service().resumeTask(id),{code:'segmentation_provider_changed'});assert.equal(f.stats().posts,1);assert.equal(f.stats().polls,0);});
test('single writer lease rejects concurrent process owners for segmentation records',async t=>{const f=await fixture(t),other=createReplicateSam2SegmentationService(f.options);await assert.rejects(other.ready,{code:'storage_error'});await other.close();const id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='running'&&task.branches.every(b=>b.predictionId));assert.equal(f.stats().posts,2);});

test('second Files failure actively settles the accepted processing sibling despite no second prediction ID',async t=>{const f=await fixture(t,{secondUploadFails:true,cancelStatus:'succeeded'}),id=randomUUID();await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.status==='failed'&&task.branches[0].status==='archived');const task=await f.service().getTask(id);assert.equal(task.status,'failed');assert.equal(task.mask,undefined);assert.equal(task.branches[1].predictionId,undefined);assert.equal(task.branches[0].downloadedFrames,2);assert.equal(task.branches[0].remoteCancellation,'already_terminal');assert.deepEqual(f.stats(),{files:2,posts:1,polls:1,cancels:1,downloads:2});});

test('GET during authorized forward archive reports running with resume disabled while reverse is still pending',async t=>{const f=await fixture(t,{immediate:true,holdForwardTailDownload:true}),id=randomUUID();t.after(f.releaseForwardTail);await f.service().createTask(input,{idempotencyKey:id});await f.wait(id,task=>task.branches[0]?.status==='downloading'&&task.branches[0].downloadedFrames===1&&task.branches[1]?.status==='pending');const task=await f.service().getTask(id);assert.equal(task.status,'running');assert.equal(task.canResume,false);assert.equal(task.branches[0].downloadedFrames,1);assert.equal(task.branches[1].status,'pending');assert.equal(f.stats().posts,1);f.releaseForwardTail();await f.wait(id,task=>task.status==='succeeded');const finished=await f.service().getTask(id);assert.equal(finished.status,'succeeded');assert.deepEqual(finished.mask.frames,['2 1','0 1','1 1']);assert.equal(f.stats().posts,2);});
