'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const {createVoiceCatalog}=require('../server/voice-catalog.cjs');
const {createGenerationMediaDownloader}=require('../server/generation-media-download.cjs');
const key='synthetic-voice-key',cdn='https://storage.googleapis.com/eleven-public-prod/voice-preview.mp3';
const raw=()=>({voices:[{voice_id:'voice_1',name:'真实合成测试音色',labels:{language:'zh',gender:'female'},category:'premade',description:'test voice',preview_url:cdn,sharing:{email:'private@example.test'}}],has_more:false,next_page_token:null});
const response=value=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});
const configured=options=>createVoiceCatalog({apiKey:key,fetchImpl:async()=>response(raw()),...options});
function wave(){const bytes=Buffer.alloc(44+4800);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(24000,24);bytes.writeUInt32LE(48000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(bytes.length-44,40);for(let i=0;i<2400;i++)bytes.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*440/24000)*5000),44+i*2);return bytes;}
async function fixture(t,listener){const server=http.createServer(listener);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);}));return `http://127.0.0.1:${server.address().port}`;}
test('unconfigured, unknown provider/model, forbidden configured origin make no requests',async()=>{
 let calls=0;for(const options of [{},{apiKey:key,provider:'unknown'},{apiKey:key,baseUrl:'https://API.TAPNOW.AI./'},{apiKey:key,baseUrl:'https://example.test/'+key},{apiKey:key,baseUrl:'http://localhost:4173',localPort:4173}]){const service=createVoiceCatalog({...options,fetchImpl:()=>{calls++;}});await assert.rejects(service.list(),e=>e.status===503&&e.code==='voice_catalog_configuration_required');service.close();}
 const service=configured();await assert.rejects(service.list({model:'openai-speech'}),e=>e.status===503&&e.code==='voice_catalog_model_unavailable');assert.equal(calls,0);service.close();
});
test('real v2 contract, bounded pagination and normalization never publish remote/private fields',async()=>{
 const calls=[];const service=configured({fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});return response({...raw(),has_more:true,next_page_token:'next-page'});}});
 const result=await service.list({model:'elevenlabs',search:'中文',cursor:'prior',pageSize:30});assert.equal(result.provider,'elevenlabs');assert.equal(result.model,'eleven_v3');assert.equal(result.hasMore,true);assert.equal(result.nextCursor,'next-page');assert.deepEqual(result.voices[0].labels,{language:'zh',gender:'female'});assert.equal(result.voices[0].previewUrl,'/api/generation/voices/voice_1/preview?model=eleven_v3');assert.equal(JSON.stringify(result).includes('storage.googleapis.com'),false);assert.equal(JSON.stringify(result).includes('private@example'),false);
 assert.equal(calls[0].url.pathname,'/v2/voices');assert.equal(calls[0].url.searchParams.get('next_page_token'),'prior');assert.equal(calls[0].url.searchParams.get('search'),'中文');assert.equal(calls[0].options.headers['xi-api-key'],key);assert.equal(calls[0].options.redirect,'error');assert.equal(calls[0].options.method,'GET');
 result.voices[0].name='mutated';assert.notEqual((await service.list({search:'中文',cursor:'prior',pageSize:30})).voices[0].name,'mutated');assert.equal(calls.length,1);await assert.rejects(service.list({pageSize:101}),e=>e.status===400);service.close();
});
test('raw and encoded credential echoes, unsafe preview origins and malformed paging are rejected',async()=>{
 for(const value of [{...raw(),extra:key},{...raw(),next_page_token:encodeURIComponent(key)},{...raw(),voices:[{...raw().voices[0],preview_url:'https://tapnow.media/preview.mp3'}]},{...raw(),voices:[{...raw().voices[0],preview_url:'http://127.0.0.1/preview.mp3'}]},{...raw(),voices:[{...raw().voices[0],name:'bad\u0000name'}]},{...raw(),voices:[{...raw().voices[0],voice_id:123}]},{...raw(),has_more:true,next_page_token:null}]){const service=configured({fetchImpl:async()=>response(value)});await assert.rejects(service.list(),e=>e.code==='voice_catalog_response_rejected');await assert.rejects(service.preview({id:'voice_1'}),e=>e.status===404);service.close();}
 const repeated=configured({fetchImpl:async()=>response({...raw(),has_more:true,next_page_token:'same-cursor'})});await assert.rejects(repeated.list({cursor:'same-cursor'}),e=>e.code==='voice_catalog_response_rejected');repeated.close();
});
test('catalog rejects redirects and oversized streams without exposing upstream error text',async t=>{
 let targetCalls=0;const target=await fixture(t,(_req,res)=>{targetCalls++;res.end('leaked');});const origin=await fixture(t,(_req,res)=>{res.writeHead(307,{Location:target});res.end(key);});const service=configured({baseUrl:origin,fetchImpl:fetch});await assert.rejects(service.list(),e=>e.code==='voice_catalog_upstream_failed'&&!e.message.includes(key));assert.equal(targetCalls,0);service.close();
 for(const value of [new Response('x',{status:302,headers:{location:target}}),new Response('x'.repeat(1024*1024+1),{headers:{'content-type':'application/json'}}),new Response('private '+key,{status:401})]){const catalog=configured({fetchImpl:async()=>value});await assert.rejects(catalog.list(),e=>e.status===502&&!e.message.includes(key));catalog.close();}
});
test('same-origin preview route returns actual verified WAV bytes, ranges and bounded cache',async t=>{
 const bytes=wave(),downloader=createGenerationMediaDownloader({limits:{audio:8*1024*1024}});let downloads=0,time=0;
 const service=configured({now:()=>time,previewTtlMs:10,downloader:{download:async(url,options)=>{downloads++;assert.equal(url,cdn);assert.equal(options.kind,'audio');assert.equal(options.headers,undefined);return downloader.download('data:audio/wav;base64,'+bytes.toString('base64'),options);}}});t.after(()=>service.close());
 const origin=await fixture(t,(req,res)=>service.handle(req,res,new URL(req.url,'http://local').pathname,{json:(res,status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));}}));
 const list=await (await fetch(origin+'/api/generation/voices')).json();const local=list.voices[0].previewUrl;const result=await fetch(origin+local);assert.equal(result.status,200);assert.equal(result.headers.get('content-type'),'audio/wav');assert.deepEqual(Buffer.from(await result.arrayBuffer()),bytes);assert.equal(downloads,1);
 const range=await fetch(origin+local,{headers:{Range:'bytes=10-19'}});assert.equal(range.status,206);assert.equal(range.headers.get('content-range'),`bytes 10-19/${bytes.length}`);assert.deepEqual(Buffer.from(await range.arrayBuffer()),bytes.subarray(10,20));
 const head=await fetch(origin+local,{method:'HEAD'});assert.equal(head.headers.get('content-length'),String(bytes.length));assert.equal((await head.arrayBuffer()).byteLength,0);assert.equal(downloads,1);
 const badRange=await fetch(origin+local,{headers:{Range:'bytes=999999-'}});assert.equal(badRange.status,416);
 time=11;await service.preview({id:'voice_1'});assert.equal(downloads,2);await assert.rejects(service.preview({id:'arbitrary_url'}),e=>e.code==='voice_preview_unavailable');
 const mutation=await fetch(origin+'/api/generation/voices',{method:'POST'});assert.equal(mutation.status,405);
});
test('preview format failure and byte metadata credential echo never enter cache',async()=>{
 const metadata=Buffer.alloc(8+key.length+key.length%2);metadata.write('LIST');metadata.writeUInt32LE(key.length,4);metadata.write(key,8);const withKey=Buffer.concat([wave(),metadata]);withKey.writeUInt32LE(withKey.length-8,4);
 for(const data of [Buffer.from('not audio'),withKey]){let calls=0;const real=createGenerationMediaDownloader();const service=configured({downloader:{download:async(_url,options)=>{calls++;return real.download('data:audio/wav;base64,'+data.toString('base64'),options);}}});await service.list();await assert.rejects(service.preview({id:'voice_1'}),e=>e.code==='voice_catalog_response_rejected');await assert.rejects(service.preview({id:'voice_1'}),e=>e.code==='voice_catalog_response_rejected');assert.equal(calls,2);service.close();}
});
test('catalog cancellation, deadline, concurrency and close abort live read requests',async()=>{
 let observed;const service=configured({maxConcurrent:1,fetchImpl:(_url,{signal})=>{observed=signal;return new Promise(()=>{});}}),abort=new AbortController();const pending=service.list({signal:abort.signal});await new Promise(resolve=>setImmediate(resolve));assert.ok(observed);await assert.rejects(service.list(),e=>e.status===429);abort.abort();await assert.rejects(pending,e=>e.code==='voice_catalog_cancelled');assert.equal(observed.aborted,true);service.close();
 const timeout=configured({timeoutMs:20,fetchImpl:async()=>new Response(new ReadableStream({start(){}}),{headers:{'content-type':'application/json'}})});const keepAlive=setTimeout(()=>{},100);try{await assert.rejects(timeout.list(),e=>e.code==='voice_catalog_timeout'&&e.status===504);}finally{clearTimeout(keepAlive);timeout.close();}
 const closing=configured({fetchImpl:()=>new Promise(()=>{})});const request=closing.list();await new Promise(resolve=>setImmediate(resolve));closing.close();await assert.rejects(request,e=>e.code==='voice_catalog_cancelled');
});
test('missing previews and refreshed removals remain explicit without generated fallbacks',async()=>{
 let time=0,value=raw(),downloads=0;const service=configured({now:()=>time,catalogTtlMs:10,fetchImpl:async()=>response(value),downloader:{download(){downloads++;throw Error();}}});await service.list();time=11;value={...raw(),voices:[{...raw().voices[0],preview_url:null}]};const result=await service.list();assert.equal(result.voices[0].previewUrl,undefined);await assert.rejects(service.preview({id:'voice_1'}),e=>e.status===404);assert.equal(downloads,0);service.close();
});
test('catalog refresh cannot publish a removed preview that finished late',async()=>{
 let time=0,value=raw(),resume,started;const began=new Promise(resolve=>{started=resolve;}),ready=new Promise(resolve=>{resume=resolve;});const service=configured({now:()=>time,catalogTtlMs:10,fetchImpl:async()=>response(value),downloader:{download:async()=>({mime:'audio/wav',stream:(async function*(){started();await ready;yield wave();})(),close(){}})}});
 await service.list();const pending=service.preview({id:'voice_1'});await began;time=11;value={...raw(),voices:[{...raw().voices[0],preview_url:null}]};await service.list();resume();await assert.rejects(pending,e=>e.code==='voice_preview_unavailable');await assert.rejects(service.preview({id:'voice_1'}),e=>e.code==='voice_preview_unavailable');service.close();
});
test('MP3 previews require complete frames rather than an ID3-only signature',async()=>{
 const frames=Buffer.alloc(417*2);for(const offset of [0,417])frames.writeUInt32BE(0xfffb9000,offset);
 const real=createGenerationMediaDownloader(),fixtures=[{bytes:Buffer.from('ID3this is not audio'),valid:false},{bytes:frames,valid:true},{bytes:require('node:fs').readFileSync(require('node:path').join(__dirname,'fixtures/speech-tone.mp3')),valid:true}];for(const {bytes,valid} of fixtures){const service=configured({downloader:{download:async(_url,options)=>real.download('data:audio/mpeg;base64,'+bytes.toString('base64'),options)}});await service.list();if(valid){const result=await service.preview({id:'voice_1'});assert.equal(result.mime,'audio/mpeg');assert.deepEqual(result.bytes,bytes);}else await assert.rejects(service.preview({id:'voice_1'}),e=>e.code==='voice_catalog_response_rejected');service.close();}
});
test('WAV previews reject unknown codecs and inconsistent PCM fields',async()=>{
 const invalidCodec=wave(),invalidRate=wave();invalidCodec.writeUInt16LE(65535,20);invalidRate.writeUInt32LE(123,28);const real=createGenerationMediaDownloader();for(const bytes of [invalidCodec,invalidRate]){const service=configured({downloader:{download:async(_url,options)=>real.download('data:audio/wav;base64,'+bytes.toString('base64'),options)}});await service.list();await assert.rejects(service.preview({id:'voice_1'}),e=>e.code==='voice_catalog_response_rejected');service.close();}
});
