'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createHash}=require('node:crypto');
const modules=Promise.all([import('three'),import('../src/features/world-node/splat-contract.mjs'),import('../src/features/world-node/splat-io.mjs'),import('../src/features/studio-v2/model-io.mjs'),import('../src/features/studio-v2/playback.mjs'),import('../src/features/studio-v2/scene-export.mjs')]);
const fixturePath=require.resolve('../qa/fixtures/spz/source.json'),fixture=JSON.parse(fs.readFileSync(fixturePath)),bytes=fs.readFileSync(require.resolve('../qa/fixtures/spz/hornedlizard.spz'));
test('real Niantic SPZ bytes have a pinned source/hash and decode-budget header, distinct from GLB',async()=>{
 const [,contract]=await modules;assert.equal(bytes.length,fixture.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),fixture.sha256);const header=await contract.inspectSplatHeader(new Blob([bytes]));assert.equal(header.count,786233);assert.equal(header.degree,3);assert.equal(header.expandedBytes,50318928);assert.equal(header.version,2);
});
test('bad/truncated gzip, SPZ count bombs and cancelled reads fail before Spark allocation',async()=>{
 const [,contract]=await modules;await assert.rejects(()=>contract.inspectSplatHeader(new Blob(['fake .spz'])),{code:'world_splat_invalid'});const header=new Uint8Array(16),view=new DataView(header.buffer);view.setUint32(0,0x5053474e,true);view.setUint32(4,2,true);view.setUint32(8,contract.splatLimits.splats+1,true);assert.throws(()=>contract.parseSplatHeader(header),{code:'world_splat_budget'});assert.throws(()=>contract.parseSplatHeader(header.subarray(0,8)),{code:'world_splat_invalid'});const abort=new AbortController();abort.abort(Error('cancelled'));await assert.rejects(()=>contract.inspectSplatHeader(new Blob([bytes]),{signal:abort.signal}),/cancelled/);
});
test('high Gaussian groups survive real JSON/GLB reload with source refs and animation, without embedding GPU data',async t=>{
 const [THREE,,splat,io,{cloneDocument,ScenePlayback},exporter]=await modules;const prior={FileReader:global.FileReader,ProgressEvent:global.ProgressEvent};global.FileReader=class{readAsArrayBuffer(blob){blob.arrayBuffer().then(value=>{this.result=value;this.onloadend?.();});}};global.ProgressEvent=class extends Event{constructor(type,fields){super(type);Object.assign(this,fields);}};t.after(()=>Object.assign(global,prior));
 const scene=new THREE.Scene(),descriptor={version:1,format:'spz',url:'asset:real-niantic-local',count:786233,bounds:[[-2,-1,-2],[2,1,2]]},group=splat.splatProxy(descriptor,{id:'gaussian',name:'真实高斯'});group.position.set(2,1,-3);group.rotation.y=.35;scene.add(group);const clip=new THREE.AnimationClip('高斯移动',2,[new THREE.VectorKeyframeTrack(group.uuid+'.position',[0,2],[2,1,-3,4,1,-3])]);
 const clone=cloneDocument(scene),snapshot=await new THREE.ObjectLoader().parseAsync(clone.toJSON());assert.deepEqual(splat.splatObjects(snapshot)[0].userData.worldSplat,descriptor);assert.equal(snapshot.children[0].children.length,0);const blob=await io.exportGlb(clone,[clip]);assert.ok(blob.size<12000);const loaded=(await io.inspectModel(new File([blob],'gaussian-document.glb'))).loaded;
 const restored=splat.splatObjects(loaded.scene)[0];assert.deepEqual(restored.userData.worldSplat,descriptor);assert.deepEqual(restored.position.toArray(),group.position.toArray());assert.equal(restored.userData.studioId,'gaussian');assert.equal(loaded.animations.length,1);assert.ok(splat.spatialBounds(restored).getSize(new THREE.Vector3()).x>4);const rt={content:loaded.scene,animations:loaded.animations};assert.equal(new ScenePlayback(rt).catalog()[0].objectTracks.length,1);
 const runtime={content:scene,assertReady(){},assertTargetNode(){},revision:1,sessionId:'qa',async flush(){assert.fail('do not serialize an incomplete GLB export');}};await assert.rejects(()=>exporter.exportSceneDocument(runtime),/GLB 无法包含完整 SPZ/);io.disposeLoadedModel(loaded);
});
test('Gaussian descriptor rejects oversized counts/bad bounds and external/credentialed sources',async()=>{
 const [,contract,splat]=await modules;const d={version:1,format:'spz',url:'asset:valid',count:1,bounds:[[0,0,0],[1,1,1]]};for(const invalid of [{...d,count:Infinity},{...d,count:2500001},{...d,bounds:[[2,0,0],[1,1,1]]}])assert.throws(()=>contract.validateSplatDescriptor(invalid));for(const source of ['https://provider.example/scene.spz','https://user:pass@localhost/scene.spz','/api/agent/config','/assets/a.spz?token=x'])assert.throws(()=>splat.assertLocalSplatSource(source));assert.equal(splat.assertLocalSplatSource('asset:valid'),'asset:valid');
});
function deferred(){let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};}
async function contextFixture({stalledRead=false,stalledSort=false}={}){
 const [THREE,contract,splat]=await modules,counters={meshes:0,meshDisposals:0,sparks:0,sparkDisposals:0,sorts:0,dirty:0},read=deferred(),sort=deferred();
 class Spark extends THREE.Group{constructor(options){super();this.options=options;this.renderSize=new THREE.Vector2();counters.sparks++;}async update({scene}){counters.sorts++;let visible=0;scene.traverseVisible(o=>{if(o.isTestSplat)visible++;});assert.equal(visible,1,'only this context\'s source is visible while accumulating');if(stalledSort)await sort.promise;}dispose(){counters.sparkDisposals++;}}
 const context={THREE,Promise,Map,Set,AbortController,DOMException,Error,JSON,splatObjects:splat.splatObjects,splatLimits:contract.splatLimits,splatAxisScale:splat.splatAxisScale,splatLodPolicy:{targetSplats:250000,minPixelSize:2},SplatLodController:class{async select(){}async release(){}disposeTextures(){}},loadSpark:async()=>({SparkRenderer:Spark}),readLocalSplat:async()=>{if(stalledRead)await read.promise;return new Blob(['contract boundary']);},decodeSplat:async()=>{const mesh=new THREE.Group();mesh.isTestSplat=true;mesh.dispose=()=>counters.meshDisposals++;counters.meshes++;return {mesh,header:{count:1}};}};vm.createContext(context);const source=fs.readFileSync(require.resolve('../src/features/world-node/splat-io.mjs'),'utf8');vm.runInContext(source.slice(source.indexOf('export class SplatContext')).replace('export class','class')+'\nglobalThis.Context=SplatContext;',context);
 const renderer={domElement:{width:1280,height:720},getDrawingBufferSize(size){return size.set(1280,720);}},scene=new THREE.Scene(),root=new THREE.Group(),proxy=splat.splatProxy({version:1,format:'spz',url:'asset:actual-fixture',count:1,bounds:[[0,0,0],[1,1,1]]});root.add(proxy);scene.add(root);const manager=new context.Context(renderer,scene,{onDirty:()=>counters.dirty++}),camera=new THREE.PerspectiveCamera(50,16/9,.01,100);camera.position.z=4;camera.updateMatrixWorld(true);return {manager,root,proxy,scene,camera,counters,read,sort};
}
test('per-context Gaussian sorting is awaited, idle draws coalesce and disposal waits for in-flight sorting',async()=>{
 const f=await contextFixture({stalledSort:true});await f.manager.prepare(f.root);const update=f.manager.enqueue(f.camera);await new Promise(resolve=>setImmediate(resolve));assert.equal(f.counters.sorts,1);for(let i=0;i<30;i++)f.manager.render(f.root,f.camera,()=>{});assert.equal(f.counters.sorts,1);const disposal=f.manager.dispose();assert.equal(f.counters.meshDisposals,0);f.sort.resolve();await update;await disposal;await f.manager.dispose();assert.equal(f.counters.meshDisposals,1);assert.equal(f.counters.sparkDisposals,1);assert.equal(f.manager.layer.parent,null);assert.equal(f.counters.dirty,0);
});
test('a closed context releases a late decoded Gaussian and never adopts it',async()=>{
 const f=await contextFixture({stalledRead:true}),preparing=f.manager.prepare(f.root);await new Promise(resolve=>setImmediate(resolve));await f.manager.dispose();f.read.resolve();await assert.rejects(preparing,/已关闭/);assert.equal(f.counters.meshDisposals,1);assert.equal(f.manager.entries.size,0);
});
test('idle ready Gaussian frames do not continually reschedule sort and rebind preserves a document clone',async()=>{
 const f=await contextFixture();await f.manager.settle(f.root,f.camera);for(let i=0;i<120;i++)f.manager.render(f.root,f.camera,()=>{});await new Promise(resolve=>setImmediate(resolve));assert.equal(f.counters.sorts,1);const [,,, ,{cloneDocument}]=await modules,newRoot=cloneDocument(f.root);f.manager.rebind(newRoot);assert.equal([...f.manager.entries.keys()][0],newRoot.children[0]);newRoot.children[0].position.x=3;await f.manager.settle(newRoot,f.camera);assert.equal(f.counters.sorts,2);await f.manager.dispose();assert.equal(f.counters.meshDisposals,1);
});
test('real SPZ framing ignores distant environment only for the camera hint and preserves full spatial bounds',async()=>{
 const [THREE,,splat]=await modules,raw=require('node:zlib').gunzipSync(bytes),count=raw.readUInt32LE(8),full=new THREE.Box3();const mesh={splats:{getNumSplats:()=>count},forEachSplat(callback){const center=new THREE.Vector3();for(let i=0;i<count;i++){for(let axis=0;axis<3;axis++){const value=raw.readUIntLE(16+9*i+axis*3,3);center.setComponent(axis,(value>=8388608?value-16777216:value)/4096);}full.expandByPoint(center);callback(i,center);}}};mesh.forEachSplat(()=>{});const frame=splat.splatFramingBounds(mesh,full);assert.ok(full.getSize(new THREE.Vector3()).x>399);assert.ok(frame.getSize(new THREE.Vector3()).x<6);const descriptor={version:1,format:'spz',url:'asset:real',count,bounds:[full.min.toArray(),full.max.toArray()],framingBounds:[frame.min.toArray(),frame.max.toArray()]},proxy=splat.splatProxy(descriptor);assert.ok(splat.spatialBounds(proxy).getSize(new THREE.Vector3()).x>399);assert.ok(splat.spatialBounds(proxy,undefined,{framing:true}).getSize(new THREE.Vector3()).x<6);
});
test('deleting the last source hides the old Gaussian accumulator even while its sort finishes',async()=>{
 const f=await contextFixture({stalledSort:true});await f.manager.prepare(f.root);const update=f.manager.enqueue(f.camera);await new Promise(resolve=>setImmediate(resolve));f.proxy.removeFromParent();f.manager.prune(f.root);let shown=true;f.manager.render(f.root,f.camera,()=>{shown=f.manager.layer.visible;});assert.equal(shown,false);f.sort.resolve();await update;await new Promise(resolve=>setImmediate(resolve));f.manager.render(f.root,f.camera,()=>assert.equal(f.manager.layer.visible,false));assert.equal(f.manager.spark,null);assert.equal(f.counters.sparkDisposals,1);await f.manager.dispose();assert.equal(f.counters.meshDisposals,1);
});
async function shotClass(){const [THREE,,splat]=await modules,context={THREE,Error,splatObjects:splat.splatObjects,SplatContext:class{async settle(){await this.pending;}async dispose(){this.disposed=true;}}};vm.createContext(context);const source=fs.readFileSync(require.resolve('../src/features/studio-v2/shot-renderer.mjs'),'utf8');vm.runInContext(source.slice(source.indexOf('export class ShotRenderer')).replace('export class','class')+'\nglobalThis.Shot=ShotRenderer;',context);return {Shot:context.Shot,THREE,splat};}
test('shot previews without a camera never attempt Gaussian sorting; last removal disposes the shot context',async()=>{
 const {Shot,THREE,splat}=await shotClass(),root=new THREE.Group();root.add(splat.splatProxy({version:1,format:'spz',url:'asset:real',count:1,bounds:[[0,0,0],[1,1,1]]}));const shot=Object.create(Shot.prototype);shot.runtime={content:root,find:()=>null};shot.canvas={clientWidth:200,clientHeight:100};shot.renderer={setScissorTest(){},setClearColor(){},clear(){},setSize(){}};assert.equal(shot.render(),false);assert.equal(shot.preparing,undefined);root.clear();let disposed=0;shot.gaussian={async dispose(){disposed++;}};await shot.ready();assert.equal(disposed,1);assert.equal(shot.gaussian,null);assert.equal(shot.preparedRoot,root);
});
test('shot readiness never marks an asynchronously replaced document as prepared',async()=>{
 const {Shot,THREE,splat}=await shotClass(),root=new THREE.Group();root.add(splat.splatProxy({version:1,format:'spz',url:'asset:real',count:1,bounds:[[0,0,0],[1,1,1]]}));const shot=Object.create(Shot.prototype),pending=deferred();shot.runtime={content:root};shot.canvas={clientWidth:200,clientHeight:100};shot.renderer={setSize(){}};shot.camera=()=>new THREE.PerspectiveCamera();shot.gaussian={settle:()=>pending.promise};const ready=shot.ready();shot.runtime.content=root.clone();pending.resolve();assert.equal(await ready,false);assert.equal(shot.preparedRoot,null);assert.equal(shot.runtime.dirty,true);
});

test('local SPZ follows Niantic RUB while explicit Marble RDF flips Y/Z exactly once',async()=>{const [THREE,contract,splat]=await modules;assert.deepEqual(splat.splatAxisScale({}).toArray(),[1,1,1]);assert.deepEqual(splat.splatAxisScale({coordinateSystem:'spz_rub'}).toArray(),[1,1,1]);assert.deepEqual(splat.splatAxisScale({coordinateSystem:'marble_raw_opencv'}).toArray(),[1,-1,-1]);const f=await contextFixture();await f.manager.prepare(f.root);assert.deepEqual([...f.manager.entries.values()][0].matrix.elements,new THREE.Matrix4().elements);f.proxy.userData.worldSplat.coordinateSystem='marble_raw_opencv';f.manager.sync();assert.ok([...f.manager.entries.values()][0].matrix.equals(new THREE.Matrix4().makeScale(1,-1,-1)));await f.manager.dispose();assert.throws(()=>contract.validateSplatDescriptor({version:1,format:'spz',url:'asset:local',count:1,bounds:[[0,0,0],[1,1,1]],coordinateSystem:'unknown'}));});
async function materializationFixture({renderFailure=false,settleGate}={}){
 const [THREE,contract,splat]=await modules,{materializationScope,readModelBlob}=await import('../src/features/world-node/materialization.mjs'),{assertReadableMediaSource,assertReadableResultMedia}=await import('../src/features/generation-results/media-ref.mjs'),puts=[],released={mesh:0,renderer:0},box=new THREE.Box3(new THREE.Vector3(-1,-1,-1),new THREE.Vector3(1,1,1));
 class Renderer{setPixelRatio(){}setSize(){}render(){if(renderFailure)throw Error('GPU draw failed');}dispose(){released.renderer++;}forceContextLoss(){}}
 class Context{constructor(){this.entries=new Map();this.layer=new THREE.Group();}render(root,camera,draw){return draw();}async settle(){await settleGate?.promise;}async dispose(){if(this.disposed)return;this.disposed=true;for(const mesh of this.entries.values())mesh.dispose();}}
 const context={THREE:{...THREE,WebGLRenderer:Renderer},decodeSplat:async()=>{const mesh=new THREE.Group();mesh.dispose=()=>released.mesh++;return {mesh,header:{count:786233},bounds:box,framingBounds:box};},splatProxy:splat.splatProxy,splatAxisScale:splat.splatAxisScale,spatialBounds:splat.spatialBounds,SplatContext:Context,splatLimits:contract.splatLimits,disposeModel:(await modules)[3].disposeModel,materializationScope,readModelBlob,assertReadableMediaSource,assertReadableResultMedia,assertWorldRendererSupport:(await import('../src/features/world-node/render-capabilities.mjs')).assertWorldRendererSupport,structuredClone,Blob,File,URL:class extends URL{static createObjectURL(){return 'blob:http://localhost/qa-graphics-boundary';}static revokeObjectURL(){}},AbortController,DOMException,setTimeout,clearTimeout,setInterval,clearInterval,devicePixelRatio:1,previewLights(){},viewportFov:()=>45,DEFAULT_FOCAL:35,window:{CanvasApp:{},LocalAssets:{url:async value=>value,put:async blob=>{puts.push(blob);return 'asset:'+puts.length;}},LocalMedia:{asDataUrl:async()=> 'data:image/png;base64,QA'}},document:{createElement:()=>({toBlob:fn=>fn(new Blob(['explicit graphics test boundary'],{type:'image/png'}))})},fetch:async()=>new Response(bytes)};
 vm.createContext(context);const source=fs.readFileSync(require.resolve('../src/features/world-node/resource.mjs'),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');vm.runInContext(source+'\nglobalThis.materialize=materialize;',context);return {context,puts,released};
}
test('SPZ production materialization preserves exact source bytes, MIME, suffix and source/coordinate metadata after graphics boundary succeeds',async()=>{
 const f=await materializationFixture(),ref='/api/generation/media/12345678-1234-4234-8234-000000000001',world={coordinateSystem:'marble_raw_opencv',id:'real-source-world',assets:{splats:{semanticsMetadata:{metricScaleFactor:2,groundPlaneOffset:1}}}};const result=await f.context.materialize({url:ref,filename:'wrong-name.glb',format:'spz',representation:'gaussianSplat',world},'world');assert.equal(f.puts[0].name,'wrong-name.spz');assert.equal(f.puts[0].type,'application/octet-stream');assert.equal(createHash('sha256').update(Buffer.from(await f.puts[0].arrayBuffer())).digest('hex'),fixture.sha256);assert.equal(result.worldResource.splat.coordinateSystem,'marble_raw_opencv');assert.equal(result.worldResource.splat.count,786233);assert.equal(result.worldResource.splat.metricScaleFactor,2);assert.deepEqual(result.worldResource.world,world);assert.equal(f.released.mesh,1);assert.equal(f.released.renderer,1);
});
test('SPZ production materialization never writes a success resource when drawing or in-flight sorting/capture fails/cancels',async()=>{
 const ref='/api/generation/media/12345678-1234-4234-8234-000000000001',failed=await materializationFixture({renderFailure:true});await assert.rejects(failed.context.materialize({url:ref,format:'spz'}),/GPU draw failed/);assert.equal(failed.puts.length,0);assert.equal(failed.released.mesh,1);assert.equal(failed.released.renderer,1);
 const gate=deferred(),cancelled=await materializationFixture({settleGate:gate}),abort=new AbortController(),pending=cancelled.context.materialize({url:ref,format:'spz'},'world',{signal:abort.signal});await new Promise(resolve=>setImmediate(resolve));abort.abort();await assert.rejects(pending,{name:'AbortError'});gate.resolve();assert.equal(cancelled.puts.length,0);assert.equal(cancelled.released.mesh,1);assert.equal(cancelled.released.renderer,1);
});

test('Marble metric and ground-plane conversion is applied once and survives JSON restoration',async()=>{const [THREE,,splat]=await modules,descriptor={version:1,format:'spz',url:'asset:marble',count:1,bounds:[[-1,-2,-1],[1,2,1]],coordinateSystem:'marble_raw_opencv',metricScaleFactor:2,groundPlaneOffset:1},proxy=splat.splatProxy(descriptor);assert.deepEqual(proxy.scale.toArray(),[2,2,2]);assert.deepEqual(proxy.position.toArray(),[0,1,0]);const bounds=splat.spatialBounds(proxy);assert.equal(bounds.min.y,-3);assert.equal(bounds.max.y,5);const restored=await new THREE.ObjectLoader().parseAsync(proxy.toJSON());assert.deepEqual(restored.position.toArray(),[0,1,0]);assert.deepEqual(restored.scale.toArray(),[2,2,2]);assert.deepEqual(splat.spatialBounds(restored).min.toArray(),bounds.min.toArray());});

test('small declared SPZ counts cannot hide extra expanded payload before official decoder allocation',async()=>{const [,contract]=await modules,zlib=require('node:zlib'),header=Buffer.alloc(16);header.writeUInt32LE(0x5053474e,0);header.writeUInt32LE(2,4);header.writeUInt32LE(1,8);header[13]=12;const expected=contract.parseSplatHeader(header).expandedBytes,exact=Buffer.concat([header,Buffer.alloc(expected-16)]);assert.equal((await contract.inspectSplatHeader(new Blob([zlib.gzipSync(exact)]))).count,1);for(const payload of [Buffer.concat([exact,Buffer.alloc(1024*1024)]),exact.subarray(0,exact.length-1)])await assert.rejects(()=>contract.inspectSplatHeader(new Blob([zlib.gzipSync(payload)])),{code:'world_splat_invalid'});const extensions=Buffer.from(header);extensions[14]=2;assert.throws(()=>contract.parseSplatHeader(extensions),{code:'world_splat_invalid'});});
test('proxy and camera layer-only changes reschedule native accumulation while the Spark presentation accepts that view',async()=>{const f=await contextFixture();await f.manager.settle(f.root,f.camera);assert.equal(f.counters.sorts,1);assert.equal(f.manager.spark.layers.mask,-1);f.proxy.layers.set(1);await f.manager.enqueue(f.camera);assert.equal([...f.manager.entries.values()][0].layers.mask,2);assert.equal(f.counters.sorts,2);f.camera.layers.set(1);await f.manager.enqueue(f.camera);assert.equal(f.counters.sorts,3);assert.equal(f.manager.spark.layers.test(f.camera.layers),true);await f.manager.dispose();});
