'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {Worker:ThreadWorker}=require('node:worker_threads');
const modules=Promise.all([import('three'),import('../src/features/world-node/splat-lod.mjs'),import('../src/features/world-node/splat-io.mjs')]);
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
// Only the browser Worker transport is adapted. Decoding, tiny-lod merges,
// hierarchy traversal, index texture data and raycast run the installed WASM.
class NativeWorker {
 static workers=new Set();
 constructor(url){NativeWorker.workers.add(this);const code=decodeURIComponent(String(url).split(',').slice(1).join(','));this.thread=new ThreadWorker("const {parentPort}=require('node:worker_threads');globalThis.self=globalThis;const listeners=new Map();globalThis.addEventListener=(name,fn)=>{if(name==='message'){const handler=data=>fn({data});listeners.set(fn,handler);parentPort.on('message',handler);}};globalThis.removeEventListener=(name,fn)=>{parentPort.off('message',listeners.get(fn));listeners.delete(fn);};globalThis.postMessage=(value,options)=>parentPort.postMessage(value,Array.isArray(options)?options:options?.transfer||[]);parentPort.on('message',data=>globalThis.onmessage?.({data}));\n"+code,{eval:true});this.thread.on('message',data=>this.onmessage?.({data}));this.thread.on('error',error=>this.onerror?.(error));}
 postMessage(value,options){this.thread.postMessage(value,options?.transfer||[]);}
 addEventListener(name,run){if(name==='error')this.thread.on('error',run);}
 terminate(){NativeWorker.workers.delete(this);return this.thread.terminate();}
}
test('real SPZ builds official tiny-lod, selects different near/far details within budget, retains exact indices for native picking and releases trees/textures',async t=>{
 const [THREE,{buildSplatLod,SplatLodController,splatLodPolicy},{splatFramingBounds}]=await modules,priorWorker=global.Worker,priorNavigator=Object.getOwnPropertyDescriptor(global,'navigator');global.Worker=NativeWorker;Object.defineProperty(global,'navigator',{value:{platform:'MacIntel',maxTouchPoints:0,userAgent:'Node native LOD test'},configurable:true});
 const sdk=await import('@sparkjsdev/spark'),bytes=fs.readFileSync(require.resolve('../qa/fixtures/spz/hornedlizard.spz')),mesh=new sdk.SplatMesh({fileBytes:bytes,fileType:sdk.SplatFileType.SPZ,lod:false,raycastable:true}),renderer={getContext:()=>({getExtension:()=>null}),properties:{has:()=>false}},spark=new sdk.SparkRenderer({renderer,enableLod:true,lodSplatCount:splatLodPolicy.targetSplats,lodRenderScale:splatLodPolicy.minPixelSize,lodRaycast:false,lodCleanupTimeoutMs:0,autoUpdate:false}),lod=new SplatLodController(spark);
 t.after(async()=>{lod.disposeTextures();mesh.dispose();spark.dispose();await Promise.all([...NativeWorker.workers].map(worker=>worker.terminate()));global.Worker=priorWorker;if(priorNavigator)Object.defineProperty(global,'navigator',priorNavigator);else delete global.navigator;});
 await mesh.initialized;const original=mesh.packedSplats.packedArray,originalCount=mesh.splats.getNumSplats();assert.equal(originalCount,786233);await buildSplatLod(mesh);assert.equal(mesh.packedSplats.packedArray,original);assert.equal(mesh.splats.getNumSplats(),originalCount);assert.ok(mesh.userData.worldLod.treeCount>originalCount);assert.ok(mesh.userData.worldLod.treeBytes>0);
 const center=splatFramingBounds(mesh,mesh.getBoundingBox()).getCenter(new THREE.Vector3()),camera=new THREE.PerspectiveCamera(50,16/9,.01,1000),direction=new THREE.Vector3(.7,.3,1).normalize();spark.renderSize.set(1280,720);
 const select=async distance=>{camera.position.copy(center).addScaledVector(direction,distance);camera.lookAt(center);camera.updateMatrixWorld(true);await lod.select(camera,[mesh]);const instance=spark.lodInstances.get(mesh);assert.ok(instance.numSplats>0);assert.ok(instance.numSplats<=splatLodPolicy.targetSplats);const data=instance.indices.subarray(0,instance.numSplats);assert.ok(data.every(index=>index<mesh.userData.worldLod.treeCount));return {count:instance.numSplats,indices:Array.from(data),instance};};
 const near=await select(6),far=await select(70);assert.notEqual(near.count,far.count);assert.ok(far.count<near.count);assert.notDeepEqual(near.indices.slice(0,100),far.indices.slice(0,100));assert.equal(far.instance.texture.image.data,far.instance.indices);
 const copied=Array.from(far.instance.texture.image.data.subarray(0,far.count));assert.deepEqual(copied,far.indices);await select(6);assert.notDeepEqual(Array.from(spark.lodInstances.get(mesh).texture.image.data.subarray(0,100)),copied.slice(0,100));
 const context={renderer,time:0,deltaTime:0,viewToWorld:camera.matrixWorld,camera,renderSize:spark.renderSize,globalEdits:[],lodIndices:spark.lodInstances.get(mesh)};mesh.update(context);assert.equal(mesh.context.enableLod.value,true);assert.equal(mesh.context.numSplats.value,spark.lodInstances.get(mesh).numSplats);assert.equal(mesh.context.lodIndices.value.image.data,spark.lodInstances.get(mesh).indices);const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);assert.ok(ray.intersectObject(mesh).length>0);
 let textureDisposals=0;spark.lodInstances.get(mesh).texture.addEventListener('dispose',()=>textureDisposals++);await lod.release(mesh);assert.equal(textureDisposals,1);assert.equal(spark.lodInstances.size,0);assert.equal(spark.lodIds.size,0);assert.equal(spark.lodIdToSplats.size,0);assert.equal(mesh.packedSplats.packedArray,original);
 t.diagnostic(JSON.stringify({sourceCount:originalCount,treeCount:mesh.userData.worldLod.treeCount,treeBytes:mesh.userData.worldLod.treeBytes,near:near.count,far:far.count,budget:splatLodPolicy.targetSplats}));
});
async function controllerFixture({failure=false}={}){
 const [THREE,{SplatLodController}]=await modules,gate=deferred(),camera=new THREE.PerspectiveCamera(50,1,.1,100),mesh=new THREE.Group();camera.updateMatrixWorld(true);mesh.packedSplats={lodSplats:{}};let released=0;
 const worker={exclusive:async callback=>callback(worker),call:async()=>{released++;}},spark={enableDriveLod:true,current:{viewToWorld:new THREE.Matrix4()},lodInstances:new Map(),lodIds:new Map(),lodIdToSplats:new Map(),renderer:{properties:{has:()=>false}},ensureLodWorker(){this.lodWorker=worker;return worker;},updateLodIndices(map,values){for(const [id,value]of Object.entries(values)){const old=this.lodInstances.get(map.get(id));if(old)old.numSplats=value.numSplats;else{const texture=new THREE.DataTexture(value.indices,4096,1);this.lodInstances.set(map.get(id),{...value,texture});}}},driveLod({visibleGenerators}){this.ensureLodWorker().tryExclusive(async()=>{await gate.promise;if(failure)throw Error('native traversal failed');for(const value of visibleGenerators)this.updateLodIndices(new Map([[value.uuid,value]]),{[value.uuid]:{lodId:7,numSplats:2,indices:new Uint32Array([this.generation||0,4])}});});}};
 const lod=new SplatLodController(spark);return {spark,lod,gate,mesh,camera,worker,get released(){return released;}};
}
test('native traversal task is awaited and its failures have an owner; pinned instance hooks are restored',async()=>{
 const f=await controllerFixture(),nativeEnsure=f.spark.ensureLodWorker,nativeUpdate=f.spark.updateLodIndices;let done=false;const pending=f.lod.select(f.camera,[f.mesh]).then(()=>done=true);await new Promise(resolve=>setImmediate(resolve));assert.equal(done,false);f.gate.resolve();await pending;assert.equal(done,true);assert.equal(f.spark.ensureLodWorker,nativeEnsure);assert.equal(f.spark.updateLodIndices,nativeUpdate);f.spark.renderer.properties.has=()=>true;f.spark.generation=99;await f.lod.select(f.camera,[f.mesh]);const value=f.spark.lodInstances.get(f.mesh);assert.equal(value.indices[0],99);assert.equal(value.texture.image.data[0],99);
 const bad=await controllerFixture({failure:true}),ensure=bad.spark.ensureLodWorker,update=bad.spark.updateLodIndices,failed=bad.lod.select(bad.camera,[bad.mesh]);bad.gate.resolve();await assert.rejects(failed,/native traversal failed/);assert.equal(bad.spark.ensureLodWorker,ensure);assert.equal(bad.spark.updateLodIndices,update);
});
test('hidden and mismatched camera layers do not enter official traversal; context textures are disposed before clearing',async()=>{
 const f=await controllerFixture();f.gate.resolve();f.mesh.visible=false;await f.lod.select(f.camera,[f.mesh]);assert.equal(f.spark.lodInstances.size,0);f.mesh.visible=true;f.mesh.layers.set(1);await f.lod.select(f.camera,[f.mesh]);assert.equal(f.spark.lodInstances.size,0);f.camera.layers.set(1);await f.lod.select(f.camera,[f.mesh]);assert.equal(f.spark.lodInstances.size,1);let disposed=0;f.spark.lodInstances.get(f.mesh).texture.addEventListener('dispose',()=>disposed++);f.lod.disposeTextures();f.lod.disposeTextures();assert.equal(disposed,1);assert.equal(f.spark.lodInstances.size,0);
});
async function contextFixture(){
 const [THREE,lod,splat]=await modules,gate=deferred(),sort=deferred(),counters={selections:0,sorts:0,meshDisposals:0,sparkDisposals:0,drawn:[]};
 class Spark extends THREE.Group{
  constructor(options){super();this.options=options;this.renderSize=new THREE.Vector2();this.current={viewToWorld:new THREE.Matrix4()};this.renderer={properties:{has:()=>false}};this.lodInstances=new Map();this.lodIds=new Map();this.lodIdToSplats=new Map();this.worker={exclusive:async callback=>callback(this.worker),call:async()=>{}};}
  ensureLodWorker(){this.lodWorker=this.worker;return this.worker;}
  driveLod({visibleGenerators}){this.ensureLodWorker().tryExclusive(async()=>{counters.selections++;await gate.promise;const map=new Map(visibleGenerators.map(mesh=>[mesh.uuid,mesh])),values={};for(const mesh of visibleGenerators)values[mesh.uuid]={lodId:9,numSplats:25,indices:new Uint32Array([0,1])};this.updateLodIndices(map,values);});}
  updateLodIndices(meshes,values){for(const [id,value]of Object.entries(values)){const mesh=meshes.get(id),texture=new THREE.DataTexture(value.indices,4096,1);this.lodInstances.set(mesh,{...value,texture});this.lodIds.set(mesh.packedSplats.lodSplats,{lodId:9});this.lodIdToSplats.set(9,mesh.packedSplats.lodSplats);}}
  async update({scene}){counters.sorts++;scene.traverse(mesh=>{if(mesh.packedSplats){const instance=this.lodInstances.get(mesh);mesh.context={numSplats:{value:instance?.numSplats||100},enableLod:{value:!!instance},lodIndices:{value:instance?.texture}};}});scene.traverseVisible(mesh=>{if(mesh.packedSplats){const instance=this.lodInstances.get(mesh);assert.ok(instance,'first GPU accumulation requires actual native selection');counters.drawn.push(instance.numSplats);}});await sort.promise;}
  dispose(){counters.sparkDisposals++;}
 }
 const box=new THREE.Box3(new THREE.Vector3(-1,-1,-1),new THREE.Vector3(1,1,1)),context={THREE,Promise,Map,Set,AbortController,DOMException,Error,JSON,splatObjects:splat.splatObjects,splatLimits:{sceneSplats:2500000},splatAxisScale:splat.splatAxisScale,splatLodPolicy:lod.splatLodPolicy,SplatLodController:lod.SplatLodController,loadSpark:async()=>({SparkRenderer:Spark}),readLocalSplat:async()=>new Blob(),decodeSplat:async()=>{const mesh=new THREE.Group();mesh.packedSplats={getNumSplats:()=>100,lodSplats:{getNumSplats:()=>150}};mesh.dispose=()=>counters.meshDisposals++;mesh.raycast=(ray,hits)=>{mesh.lastRaycastCount=mesh.context.numSplats.value;mesh.lastRaycastIndices=mesh.context.lodIndices.value;hits.push({object:mesh,distance:5,point:ray.ray.at(5,new THREE.Vector3())});};return {mesh,header:{count:100},bounds:box};}};
 vm.createContext(context);const source=fs.readFileSync(require.resolve('../src/features/world-node/splat-io.mjs'),'utf8');vm.runInContext(source.slice(source.indexOf('export class SplatContext')).replace('export class','class')+'\nglobalThis.Context=SplatContext;',context);
 const scene=new THREE.Scene(),root=new THREE.Group(),proxy=splat.splatProxy({version:1,format:'spz',url:'asset:fixture',count:100,bounds:[[-1,-1,-1],[1,1,1]]});scene.add(root);root.add(proxy);const renderer={domElement:{width:1280,height:720},getDrawingBufferSize:size=>size.set(1280,720)},manager=new context.Context(renderer,scene),camera=new THREE.PerspectiveCamera(50,16/9,.01,100);camera.position.z=5;camera.updateMatrixWorld(true);return {manager,root,proxy,camera,counters,gate,sort};
}
test('first accumulation and export readiness await native selection and GPU sort; idle rendering reuses settled LOD',async()=>{
 const f=await contextFixture(),pending=f.manager.settle(f.root,f.camera);await new Promise(resolve=>setImmediate(resolve));assert.equal(f.counters.selections,1);assert.equal(f.counters.sorts,0);assert.equal(f.manager.lastKey,undefined);for(let i=0;i<30;i++)f.manager.render(f.root,f.camera,()=>{});assert.equal(f.counters.selections,1);f.gate.resolve();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.counters.sorts,1);assert.deepEqual(f.counters.drawn,[25]);assert.equal(f.manager.lastKey,undefined);f.sort.resolve();await pending;assert.ok(f.manager.lastKey);for(let i=0;i<30;i++)f.manager.render(f.root,f.camera,()=>{});await new Promise(resolve=>setImmediate(resolve));assert.equal(f.counters.selections,1);await f.manager.dispose();assert.equal(f.counters.meshDisposals,1);assert.equal(f.counters.sparkDisposals,1);
});
test('closing during native selection drains its worker, avoids late GPU accumulation and releases late index textures',async()=>{
 const f=await contextFixture();await f.manager.prepare(f.root);const pending=f.manager.enqueue(f.camera);await new Promise(resolve=>setImmediate(resolve));const spark=f.manager.spark,disposal=f.manager.dispose();assert.equal(f.counters.meshDisposals,0);assert.equal(f.counters.sparkDisposals,0);f.gate.resolve();await pending;await disposal;assert.equal(f.counters.sorts,0);assert.equal(spark.lodInstances.size,0);assert.equal(f.counters.meshDisposals,1);assert.equal(f.counters.sparkDisposals,1);assert.equal(f.manager.layer.parent,null);
});
test('removing the final source during native traversal releases its worker tree and hides stale drawing',async()=>{
 const f=await contextFixture();await f.manager.prepare(f.root);const pending=f.manager.enqueue(f.camera);await new Promise(resolve=>setImmediate(resolve));const spark=f.manager.spark;f.proxy.removeFromParent();f.manager.prune(f.root);f.manager.render(f.root,f.camera,()=>assert.equal(f.manager.layer.visible,false));f.gate.resolve();f.sort.resolve();await pending;await new Promise(resolve=>setImmediate(resolve));await f.manager.dispose();assert.equal(spark.lodInstances.size,0);assert.equal(spark.lodIds.size,0);assert.equal(f.counters.meshDisposals,1);assert.equal(f.counters.sparkDisposals,1);
});
test('cancelling derived LOD construction releases the source only after its late native build settles',async()=>{
 const [THREE]=await modules,{materializationScope}=await import('../src/features/world-node/materialization.mjs'),gate=deferred(),abort=new AbortController();let disposed=0,started=false;const mesh={initialized:Promise.resolve(),splats:{getNumSplats:()=>1},getBoundingBox:()=>new THREE.Box3(new THREE.Vector3(0,0,0),new THREE.Vector3(1,1,1)),userData:{},dispose:()=>disposed++};
 const context={materializationScope,inspectSplatHeader:async()=>({count:1}),loadSpark:async()=>({SplatMesh:class{constructor(){return mesh;}},SplatFileType:{SPZ:'spz'}}),buildSplatLod:async()=>{started=true;await gate.promise;},splatFramingBounds:(_,box)=>box,Error,Promise};vm.createContext(context);const source=fs.readFileSync(require.resolve('../src/features/world-node/splat-io.mjs'),'utf8'),start=source.indexOf('export async function decodeSplat'),end=source.indexOf('// Far environment',start);vm.runInContext(source.slice(start,end).replace('export async','async')+'\nglobalThis.decode=decodeSplat;',context);const pending=context.decode(new Blob(['boundary']),{signal:abort.signal});await new Promise(resolve=>setImmediate(resolve));assert.equal(started,true);abort.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(disposed,0);gate.resolve();await new Promise(resolve=>setImmediate(resolve));assert.equal(disposed,1);
});
async function pickingFixture(){const [THREE]=await modules,{pickPixel,nearestSceneHit}=await import('../src/features/studio-v2/scene-hit.mjs'),gate=deferred(),source=fs.readFileSync(require.resolve('../src/features/studio-v2/runtime.mjs'),'utf8'),start=source.indexOf('  async pick('),end=source.indexOf('  animatedCamera(',start),context={pickPixel,nearestSceneHit};vm.createContext(context);vm.runInContext('class Runtime{'+source.slice(start,end)+'}\nglobalThis.Runtime=Runtime;',context);const rt=new context.Runtime(),root=new THREE.Group(),proxy=new THREE.Group();proxy.userData.studioId='gaussian';root.add(proxy);const camera=new THREE.PerspectiveCamera(50,1,.1,100);camera.position.z=5;camera.updateMatrixWorld(true);let rays=0,gpu=0,selected;
 Object.assign(rt,{loadStatus:'ready',pickRevision:0,revision:1,content:root,camera,renderer:{domElement:{width:200,height:200,getBoundingClientRect:()=>({left:0,top:0,width:100,height:100,right:100,bottom:100})}},motion:{pick:()=>false},playback:{},assertTargetNode(){},splatContext:{settle:()=>gate.promise,pick(){rays++;return {proxy,depth:.5};}},picker:{async pickHit(){gpu++;return null;}},scene:new THREE.Scene(),cameraPresentations:{layer:new THREE.Group()},find:()=>proxy,select:id=>selected=id,onError:error=>{throw error;}});return {rt,gate,get rays(){return rays;},get gpu(){return gpu;},get selected(){return selected;}};}
test('runtime mouse selection waits current LOD before native raycast and GPU mesh depth',async()=>{const f=await pickingFixture(),pending=f.rt.pick(50,50);assert.equal(f.rays,0);assert.equal(f.gpu,0);f.gate.resolve();assert.equal(await pending,true);assert.equal(f.rays,1);assert.equal(f.gpu,1);assert.equal(f.selected,'gaussian');});
test('a document revision invalidated during LOD settlement never proceeds to native raycast or GPU selection',async()=>{const f=await pickingFixture(),pending=f.rt.pick(50,50);f.rt.revision++;f.gate.resolve();assert.equal(await pending,false);assert.equal(f.rays,0);assert.equal(f.gpu,0);assert.equal(f.selected,undefined);});
test('shared scene main settle → shot update → cached main pick retains its own selected LOD without rescheduling',async()=>{
 const f=await contextFixture();f.gate.resolve();f.sort.resolve();await f.manager.settle(f.root,f.camera);const mainMesh=f.manager.entries.get(f.proxy),mainIndex=f.manager.spark.lodInstances.get(mainMesh).texture,shot=new f.manager.constructor(f.manager.renderer,f.manager.scene);await shot.settle(f.root,f.camera);const shotMesh=shot.entries.get(f.proxy);assert.notEqual(mainMesh,shotMesh);assert.equal(mainMesh.context.numSplats.value,25);assert.equal(mainMesh.context.enableLod.value,true);assert.equal(mainMesh.context.lodIndices.value,mainIndex);assert.equal(shotMesh.context.lodIndices.value,shot.spark.lodInstances.get(shotMesh).texture);const selections=f.counters.selections,sorts=f.counters.sorts;await f.manager.settle(f.root,f.camera);assert.equal(f.counters.selections,selections);assert.equal(f.counters.sorts,sorts);assert.ok(f.manager.pick(f.camera,.5,.5,{root:f.root}));assert.equal(mainMesh.lastRaycastCount,25);assert.equal(mainMesh.lastRaycastIndices,mainIndex);await shot.dispose();await f.manager.dispose();assert.equal(f.counters.meshDisposals,2);assert.equal(f.counters.sparkDisposals,2);
});
test('installed Spark prepareGenerate accepts a Group accumulation root and never frameUpdates another hidden view',async()=>{
 const [THREE]=await modules,sdk=await import('@sparkjsdev/spark'),scene=new THREE.Scene(),main=new THREE.Group(),shot=new THREE.Group(),camera=new THREE.PerspectiveCamera(50,1,.1,100);camera.position.z=5;camera.updateMatrixWorld(true);scene.add(main,shot);shot.visible=false;
 const make=()=>{const mesh=new sdk.SplatMesh({constructSplats:packed=>{packed.pushSplat(new THREE.Vector3(),new THREE.Vector3(.1,.1,.1),new THREE.Quaternion(),1,new THREE.Color('red'));packed.pushSplat(new THREE.Vector3(1,0,0),new THREE.Vector3(.1,.1,.1),new THREE.Quaternion(),1,new THREE.Color('blue'));}});return mesh;},a=make(),b=make();await Promise.all([a.initialized,b.initialized]);main.add(a);shot.add(b);const derived=new sdk.PackedSplats();derived.pushSplat(new THREE.Vector3(),new THREE.Vector3(.2,.2,.2),new THREE.Quaternion(),1,new THREE.Color('red'));a.packedSplats.lodSplats=derived;const indices=new Uint32Array([0]),texture=new THREE.DataTexture(indices,1,1,THREE.RedIntegerFormat,THREE.UnsignedIntType),selection={numSplats:1,indices,texture},current=new sdk.SplatAccumulator(),previous=new sdk.SplatAccumulator();let otherUpdates=0;b.onFrame=()=>otherUpdates++;
 try{const result=current.prepareGenerate({renderer:{},scene:main,timer:{getElapsed:()=>0,getDelta:()=>0},camera,sortRadial:true,renderSize:new THREE.Vector2(1280,720),previous,lodInstances:new Map([[a,selection]])});assert.deepEqual(result.visibleGenerators,[a]);assert.equal(otherUpdates,0);assert.equal(a.context.enableLod.value,true);assert.equal(a.context.numSplats.value,1);assert.equal(a.context.lodIndices.value,texture);assert.equal(a.parent,main);assert.equal(main.parent,scene);}finally{a.dispose();b.dispose();texture.dispose();current.dispose();previous.dispose();}
});
