let playback=null;
function stopPlayback(owner){if(!playback||owner&&playback.owner!==owner)return;const old=playback;playback=null;old.controller.abort();old.audio?.pause();if(old.audio){old.audio.removeAttribute('src');old.audio.load();}if(old.url)old.URL.revokeObjectURL(old.url);old.onState?.('idle');}
export function createVoiceChoices(root,{listVoices,previewVoice,value,onSelect,isCurrent=()=>true,onLayout=()=>{},initialVoices=[],model='eleven_v3',AudioClass,URLApi}={}){
 const doc=root.ownerDocument,view=doc.defaultView,make=(tag,cls,text)=>{const node=doc.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
 const search=make('input'),list=make('div','voice-catalog-list'),status=make('p','audio-status generation-menu-empty'),retry=make('button','voice-catalog-retry','重试'),more=make('button','voice-catalog-more','加载更多音色');search.type='search';search.placeholder='搜索';search.setAttribute('aria-label','搜索音色');retry.type=more.type='button';retry.hidden=more.hidden=true;status.setAttribute('role','status');root.append(search,status,list,retry,more);
 let searchTimer=null,disposed=false,request=null,serial=0,voices=initialVoices,configured=true,nextCursor=null,query='';const owner={},current=()=>!disposed&&isCurrent()&&root.isConnected;
 function show(){if(!current())return;const focusKey=list.contains(doc.activeElement)?doc.activeElement.dataset.focusKey:null;list.replaceChildren();const text=search.value.trim().toLocaleLowerCase(),filtered=voices.filter(v=>(v.name+' '+Object.values(v.labels||{}).join(' ')+' '+(v.description||'')).toLocaleLowerCase().includes(text));
  for(const voice of filtered){const line=make('div','voice-catalog-row'),choose=make('button','voice-catalog-select',voice.name);choose.type='button';choose.dataset.focusKey='voice:'+voice.id;choose.setAttribute('aria-label',voice.name);choose.setAttribute('aria-pressed',String(value===voice.id));choose.onclick=()=>{if(current())onSelect(voice.id);};line.append(choose);
   if(voice.previewRef||voice.previewUrl){const listen=make('button','voice-catalog-preview','试听');listen.type='button';listen.setAttribute('aria-label','试听 '+voice.name);listen.dataset.focusKey='preview:'+voice.id;listen.onclick=async()=>{if(!current())return;if(playback?.owner===owner&&playback.id===voice.id){stopPlayback(owner);return;}stopPlayback();const controller=new AbortController(),state={owner,id:voice.id,controller,URL:URLApi||view.URL,onState:state=>{if(current()&&listen.isConnected){listen.textContent=state==='idle'?'试听':state==='loading'?'加载…':'停止';listen.setAttribute('aria-pressed',String(state!=='idle'));}}};playback=state;state.onState('loading');
    try{const blob=await previewVoice(voice,{model,signal:controller.signal});if(!current()||controller.signal.aborted||playback!==state)return;if(!blob?.size||!/^audio\//i.test(blob.type))throw Error('试听返回内容无效');state.url=state.URL.createObjectURL(blob);state.audio=new (AudioClass||view.Audio)();state.audio.src=state.url;state.audio.onended=()=>stopPlayback(owner);state.audio.onerror=()=>{if(playback===state){stopPlayback(owner);if(current())status.textContent='试听失败，请重试';}};await state.audio.play();if(!current()||controller.signal.aborted||playback!==state){state.audio.pause();return;}state.onState('playing');
    }catch(error){if(controller.signal.aborted||playback!==state)return;stopPlayback(owner);if(current()){status.textContent='试听失败：'+error.message;status.dataset.state='error';}}
   };line.append(listen);}list.append(line);
  }
  if(!request)status.textContent=!configured?'尚未配置音色服务':!filtered.length?(voices.length?'没有匹配的音色':'暂无可用音色'):'';if(focusKey)([...list.querySelectorAll('button')].find(b=>b.dataset.focusKey===focusKey)||search).focus({preventScroll:true});onLayout();
 }
 async function load(append=false){clearTimeout(searchTimer);searchTimer=null;request?.abort();stopPlayback(owner);const controller=new AbortController(),token=++serial;request=controller;status.textContent='加载音色…';status.dataset.state='loading';retry.hidden=true;more.hidden=true;root.setAttribute('aria-busy','true');
  try{const result=await listVoices({model,signal:controller.signal,search:query,cursor:append?nextCursor:undefined});if(!current()||controller.signal.aborted||token!==serial)return;const state=Array.isArray(result)?{voices:result,configured:true}:result;if(!Array.isArray(state?.voices))throw Error('音色目录格式无效');configured=state.configured===true;voices=append?[...new Map([...voices,...state.voices].map(v=>[v.id,v])).values()]:state.voices;nextCursor=state.nextCursor||null;more.hidden=!state.hasMore;request=null;status.dataset.state=configured?'ready':'unconfigured';show();
  }catch(error){if(!current()||controller.signal.aborted||token!==serial)return;request=null;voices=[];configured=false;status.dataset.state=/configuration_required|model_unavailable/.test(error.code||'')?'unconfigured':'error';status.textContent=error.message;retry.hidden=false;list.replaceChildren();onLayout();}
  finally{if(current()&&token===serial)root.setAttribute('aria-busy','false');}
 }
 search.oninput=()=>{stopPlayback(owner);request?.abort();request=null;serial++;root.setAttribute('aria-busy','false');show();clearTimeout(searchTimer);searchTimer=setTimeout(()=>{query=search.value.trim();void load();},250);};search.onsearch=()=>{query=search.value.trim();void load();};retry.onclick=()=>{query=search.value.trim();void load();};more.onclick=()=>void load(true);show();void load();search.focus({preventScroll:true});
 return {dispose(){if(disposed)return;disposed=true;serial++;clearTimeout(searchTimer);request?.abort();stopPlayback(owner);},reload:()=>load()};
}
