import {el,button,preview,loadStyles} from './ui.mjs';
import {listSubjects,saveSubject,archiveSubject,readySubjects} from './store.mjs';
import {editSubject} from './editor.mjs';
import {managerIcons} from './manager-icons.mjs';
import {subjectPreview} from './manager-preview.mjs';
import {panelWidth,panelMotion} from './panel-layout.mjs';
const iconButton=(label,action,icon,cls='')=>{const b=button(label,action,cls);b.innerHTML=managerIcons[icon];return b;};
export function openSubjectManager({onBack,onApply,onClose=()=>{}}) {
  loadStyles();const root=el('aside','subject-manager'),abort=new AbortController();root.ariaLabel='个人主体库';root.dataset.libraryView='element-library';
  const pending=new Set();
  let mode='grid',closed=false,loading=true,loadError=null,editor=null,menu=null,hover=null,hoverTimer,leaveTimer,renameId=null,confirmation=null;
  const header=el('header'),back=iconButton('返回',onBack,'back'),toggle=iconButton('列表视图',()=>{mode=mode==='grid'?'list':'grid';draw();},'grid');header.append(back,el('h2','','主体库'),toggle);
  const scroll=el('div','subject-manager-scroll'),items=el('div','subject-manager-items');scroll.append(items);root.append(header,scroll);
  function hidePreview(){clearTimeout(hoverTimer);clearTimeout(leaveTimer);hover?.dispose();hover?.remove();hover=null;}
  function queuePreview(card,subject){if(menu||renameId)return;clearTimeout(leaveTimer);clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>{hidePreview();if(!card.isConnected)return;hover=subjectPreview(subject,()=>apply(subject));document.body.append(hover);const r=card.getBoundingClientRect();hover.style.left=Math.max(8,Math.min(innerWidth-hover.offsetWidth-24,r.right+12))+'px';hover.style.top=Math.max(16,Math.min(innerHeight-hover.offsetHeight-16,r.top+r.height/2-hover.offsetHeight/2))+'px';hover.onpointerenter=()=>clearTimeout(leaveTimer);hover.onpointerleave=()=>leaveTimer=setTimeout(hidePreview,150);},300);}
  async function apply(subject){if(pending.has(subject.id))return;hidePreview();closeMenu();pending.add(subject.id);draw();try{await onApply(subject,{signal:abort.signal});}catch(error){if(!abort.signal.aborted)window.CanvasApp?.notify('主体素材导入失败：'+error.message);}finally{pending.delete(subject.id);draw();}}
  function edit(subject){hidePreview();closeMenu();root.hidden=true;editor=editSubject({subject,scope:'personal',onClose(){editor=null;if(!closed){root.hidden=false;draw();const card=subject&&[...items.querySelectorAll('[data-subject-id]')].find(item=>item.dataset.subjectId===subject.id);(card?.querySelector('.subject-manager-thumb')||items.querySelector('.subject-manager-create'))?.focus({preventScroll:true});}}});}
  function rename(subject){hidePreview();closeMenu();renameId=subject.id;draw();const input=items.querySelector('input');input?.focus();input?.setSelectionRange(0,0);}
  function closeMenu(){if(!menu)return;menu.trigger.setAttribute('aria-expanded','false');menu.element.remove();menu=null;}
  function showMenu(subject,trigger){if(menu?.trigger===trigger){closeMenu();return;}closeMenu();hidePreview();const popup=el('div','subject-manager-menu');popup.role='menu';popup.ariaLabel=subject.name+'的更多操作';
    for(const [text,icon,action]of [['添加到画布','apply',()=>apply(subject)],['编辑主体','edit',()=>edit(subject)],['重命名','rename',()=>rename(subject)],['删除','delete',()=>confirmDelete(subject)]]){if(icon==='delete')popup.append(el('hr'));const b=iconButton(text,()=>{closeMenu();action();},icon,icon==='delete'?'destructive':'');b.role='menuitem';b.append(el('span','',text));popup.append(b);}
    document.body.append(popup);const r=trigger.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(innerWidth-248,r.right-240))+'px';popup.style.top=Math.max(8,Math.min(innerHeight-popup.offsetHeight-8,r.bottom+4))+'px';trigger.setAttribute('aria-expanded','true');menu={element:popup,trigger};popup.querySelector('button').focus();
    popup.onkeydown=e=>{e.stopPropagation();const rows=[...popup.querySelectorAll('button')],index=rows.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();rows[e.key==='Home'?0:e.key==='End'?rows.length-1:(index+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length].focus();}if(e.key==='Escape'){e.preventDefault();closeMenu();trigger.focus();}};
  }
  function confirmDelete(subject){const dialog=el('dialog','subject-delete-dialog');confirmation=dialog;dialog.ariaLabel='删除主体';dialog.append(el('h2','','删除主体'),el('p','','确定删除“'+subject.name+'”吗？此操作不会删除原始素材。'));const footer=el('footer');footer.append(button('取消',()=>dialog.close()),button('删除',async event=>{const trigger=event.currentTarget;trigger.disabled=true;try{await archiveSubject(subject.id);dialog.close();}catch(error){window.CanvasApp?.notify(error.message);}finally{trigger.disabled=false;}},'destructive'));dialog.append(footer);dialog.onkeydown=e=>e.stopPropagation();dialog.onclose=()=>{confirmation=null;dialog.remove();};document.body.append(dialog);dialog.showModal();}
  function draw(){if(closed)return;hidePreview();root.dataset.view=mode;toggle.ariaLabel=mode==='grid'?'列表视图':'网格视图';toggle.setAttribute('aria-pressed',String(mode==='list'));toggle.innerHTML=managerIcons[mode];items.replaceChildren();const create=button('新建主体',()=>edit(),'subject-manager-create');create.replaceChildren();const glyph=button('',null,'','plus');const tile=el('span','subject-manager-thumb');tile.append(...glyph.childNodes);create.append(tile,el('span','','新建主体'));create.disabled=loading||!!loadError;items.append(create);if(loading||loadError){items.append(el('p','',loadError?'主体库读取失败：'+loadError.message:'正在读取主体库…'));return;}
    for(const subject of listSubjects('personal')){const card=el('div','subject-manager-card');card.dataset.subjectId=subject.id;const media=button(subject.name,()=>edit(subject),'subject-manager-thumb');media.disabled=pending.has(subject.id);media.setAttribute('aria-busy',String(pending.has(subject.id)));media.replaceChildren(preview(subject.assets.find(a=>a.image||['image','video'].includes(a.type))||subject.assets[0]));const dots=iconButton('更多操作：'+subject.name,()=>showMenu(subject,dots),'more','subject-manager-more');dots.disabled=pending.has(subject.id);dots.setAttribute('aria-haspopup','menu');dots.setAttribute('aria-expanded','false');card.append(media,dots);
      if(renameId===subject.id){const input=el('input','subject-manager-rename');input.ariaLabel='重命名主体';input.maxLength=50;input.value=subject.name;let finished=false;const finish=async save=>{if(finished)return;finished=true;renameId=null;const name=input.value.trim();if(save&&name&&name!==subject.name){pending.add(subject.id);try{await saveSubject({...subject,name,updatedAt:Date.now()});}catch(error){window.CanvasApp?.notify(error.message);}finally{pending.delete(subject.id);}}draw();};input.onkeydown=e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();finish(true);}if(e.key==='Escape'){e.preventDefault();finish(false);}};input.onblur=()=>finish(true);card.append(input);}else card.append(button('重命名：'+subject.name,()=>rename(subject),'subject-manager-name'));
      const name=card.querySelector('.subject-manager-name');if(name)name.textContent=subject.name;
      card.onpointerenter=()=>queuePreview(card,subject);card.onpointerleave=()=>{clearTimeout(hoverTimer);leaveTimer=setTimeout(hidePreview,150);};card.oncontextmenu=e=>{e.preventDefault();showMenu(subject,dots);};items.append(card);
    }
  }
  const releaseWidth=panelWidth(root,{onStart:()=>{hidePreview();closeMenu();}}),motion=panelMotion(root);
  const observer=new ResizeObserver(entries=>{items.style.setProperty('--subject-cols',entries[0].contentRect.width>=447?4:2);});observer.observe(root);
  document.addEventListener('subjects:changed',draw,{signal:abort.signal});document.addEventListener('pointerdown',e=>{if(menu&&!menu.element.contains(e.target)&&!menu.trigger.contains(e.target))closeMenu();},{capture:true,signal:abort.signal});scroll.addEventListener('scroll',()=>{hidePreview();closeMenu();},{signal:abort.signal});
  root.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape')onBack();};window.addEventListener('resize',()=>{hidePreview();closeMenu();},{signal:abort.signal});
  function destroy({onDiscard}={}){if(closed)return true;if(editor?.close({onDiscard:()=>{destroy();onDiscard?.();}})===false)return false;closed=true;hidePreview();closeMenu();abort.abort();observer.disconnect();releaseWidth();confirmation?.close();motion.exit();onClose();return true;}
  document.body.append(root);motion.enter();draw();readySubjects().then(()=>{loading=false;draw();},error=>{loading=false;loadError=error;draw();});return {element:root,destroy};
}
