import {createEasingUI} from './motion-easing-ui.mjs';
import * as THREE from 'three';
import {el,button} from './dom.mjs';
import {icons} from './icons.mjs';
import {bindInspectorNumberField} from './inspector-number-field.mjs';

export function createMotionUI(runtime){
  const editor=runtime.motion,easing=createEasingUI(editor),root=el('section','_timeline_1m1ec_1');root.ariaLabel='运镜编辑';let zoom=1,drag=null,editingInspector=false,inspector,fields=[],keyButtons=[],ruler,head,line,clock,play,scroller,sheet;
  const run=fn=>{try{fn();}catch(error){failure.textContent=error.message;failure.hidden=false;}},failure=el('p','_error_1m1ec_103');failure.role='alert';failure.hidden=true;
  for(const name of ['pointerdown','keydown','wheel'])root.addEventListener(name,event=>{if(runtime.exporting){event.preventDefault();event.stopImmediatePropagation();}},{capture:true,passive:false});
  root.onkeydown=e=>{e.stopPropagation();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'&&!e.target.matches('input')){e.preventDefault();run(()=>editor.undo(e.shiftKey));}};
  function pose(){const p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3();editor.pose(editor.times[editor.selected]??runtime.playback.time).decompose(p,q,s);return {position:p.toArray(),rotation:new THREE.Euler().setFromQuaternion(q,'XYZ').toArray().slice(0,3).map(THREE.MathUtils.radToDeg),scale:s.toArray()};}
  // Keep field DOM connected while a sibling focus change commits its draft.
  function editInspector(field,axis,value){editingInspector=true;try{run(()=>editor.edit(field,axis,value));}finally{editingInspector=false;}}
  function renderInspector(){
    fields=[];inspector.replaceChildren();const time=editor.times[editor.selected],editable=time!==undefined;inspector.ariaLabel=editable?'镜头关键帧':'当前画面参数';inspector.dataset.editable=String(editable);const heading=el('div','_panelHeading_t2l87_38'),identity=el('div','_identity_t2l87_45'),readout=el('span','_time_t2l87_59');readout.dataset.motionTime='';if(editable){const title=el('strong','_title_t2l87_51');title.append(el('span','_keyIcon_t2l87_70'),document.createTextNode('关键帧 '+(editor.selected+1)));identity.append(title);}identity.append(readout);if(editable)identity.append(button('返回实时预览','关闭',()=>editor.select(-1)));heading.append(identity);
    if(editable){const actions=el('div','_actions_t2l87_25');actions.role='toolbar';actions.ariaLabel='调整关键点';for(const [mode,label,icon] of [['translate','移动','移动'],['rotate','转向','旋转'],['scale','缩放','缩放']]){const b=button(label,icon,()=>editor.setMode(mode),'',label);b.setAttribute('aria-pressed',String(editor.mode===mode));if(mode==='scale')b.title='改变相机节点的缩放，不是镜头变焦。';actions.append(b);}const wrapper=el('span','_deleteAction_t2l87_31'),remove=button('删除整组关键帧','删除',()=>run(()=>editor.remove()));const reason=editor.deleteReason();remove.disabled=!!reason;wrapper.title=reason||'删除此关键帧，其他关键帧的时间保持不变；可撤销';wrapper.append(remove);actions.append(wrapper);heading.append(actions);}
    inspector.append(heading);const properties=el('div','_properties_t2l87_4');for(const [field,label] of [['position','位置'],['rotation','旋转'],['scale','缩放']]){const group=el('fieldset','_property_t2l87_10'),axes=el('div','_axes_t2l87_21');group.append(el('legend','',label+(field==='rotation'?' (°)':'')),axes);for(let axis=0;axis<3;axis++){const wrapper=el('div',editable?'_field_1i3al_1':'_readOnlyField_t2l87_77'),handle=el('span',editable?'_axis_1i3al_20':'','XYZ'[axis]),input=el(editable?'input':'output',editable?'_input_1i3al_29':'');input.ariaLabel=label+' '+'XYZ'[axis];wrapper.append(handle,input);axes.append(wrapper);const format=()=>String(Number(pose()[field][axis].toFixed(field==='rotation'?1:3)));fields.push({field,axis,input,format});if(!editable)continue;input.type='number';input.step='any';input.value=format();const numeric=bindInspectorNumberField(input,{read:()=>pose()[field][axis],format,commit:value=>editInspector(field,axis,value)});let gesture=null;
      handle.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();input.focus({preventScroll:true});numeric.cancel();gesture={x:e.clientX,value:pose()[field][axis],started:false};handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(!gesture)return;const delta=e.clientX-gesture.x;if(!gesture.started){if(Math.abs(delta)<3)return;editor.beginGesture();gesture.started=true;}gesture.x=e.clientX;gesture.value+=delta*(field==='rotation'?.1:.01)*(e.shiftKey?.1:1);run(()=>editor.edit(field,axis,gesture.value,{gesture:true}));input.value=format();};handle.onpointerup=handle.onpointercancel=handle.onlostpointercapture=()=>{if(!gesture)return;const started=gesture.started;gesture=null;if(started)editor.endGesture();};}properties.append(group);}inspector.append(properties);
  }
  function renderTimeline(){
    const duration=Math.max(.1,editor.times.at(-1)||0);sheet.style.width=zoom*100+'%';ruler.replaceChildren();keyButtons=[];const power=10**Math.floor(Math.log10(duration/(10*zoom))),spacing=[1,2,5,10].map(n=>n*power).find(n=>n>=duration/(10*zoom));for(let t=0;t<=duration;t+=spacing){const tick=el('span','_tick_1aeqb_32',spacing<1?Number((t*1000).toFixed(3))+' ms':Number(t.toFixed(3))+' s');tick.style.left=t/duration*100+'%';ruler.append(tick);}head=el('span','_headHandle_1aeqb_106');ruler.append(head);const lane=el('div','_lane_1aeqb_43');line=el('span','_headLine_1aeqb_97');lane.append(line);sheet.querySelector('._row_1aeqb_59').replaceChildren(lane);
    function seek(e){const rect=e.currentTarget.getBoundingClientRect();editor.seek(Math.max(0,Math.min(duration,(e.clientX-rect.left)/rect.width*duration)));}for(const surface of [ruler,lane]){surface.onpointerdown=e=>{if(e.button!==0||e.target.closest('button'))return;e.preventDefault();surface.setPointerCapture(e.pointerId);seek(e);};surface.onpointermove=e=>{if(surface.hasPointerCapture(e.pointerId))seek(e);};surface.onpointerup=e=>{if(surface.hasPointerCapture(e.pointerId))surface.releasePointerCapture(e.pointerId);};}
    editor.times.forEach((time,index)=>{const b=button(`运镜 关键帧 ${index+1}, ${time.toFixed(2)} s`,null,e=>{if(e.detail===0)editor.select(index);},'_key_1aeqb_62');b.title='运镜 · '+time.toFixed(2)+' s';b.style.left=time/duration*100+'%';const diamond=el('span','','◆');diamond.ariaHidden='true';b.append(diamond);b.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();b.focus({preventScroll:true});editor.select(index);drag={time,next:time,x:e.clientX,width:lane.getBoundingClientRect().width,moved:false,min:index?editor.times[index-1]+.001:0,max:index<editor.times.length-1?editor.times[index+1]-.001:7200};b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(!drag)return;if(Math.abs(e.clientX-drag.x)>3)drag.moved=true;if(!drag.moved)return;drag.next=Math.max(drag.min,Math.min(drag.max,drag.time+(e.clientX-drag.x)/drag.width*duration));b.style.left=drag.next/duration*100+'%';runtime.playback.seek(drag.next);};const cancel=()=>{drag=null;b.style.left=time/duration*100+'%';tick();};b.onpointerup=e=>{const state=drag;drag=null;if(b.hasPointerCapture(e.pointerId))b.releasePointerCapture(e.pointerId);if(state?.moved)run(()=>editor.move(state.time,state.next));};b.onpointercancel=b.onlostpointercapture=cancel;b.onkeydown=e=>{if(e.key==='Escape')cancel();};keyButtons.push(b);lane.append(b);});
  }
  function render(){root.hidden=!editor.open;if(!editor.open)return;failure.hidden=true;const header=el('header'),start=el('div','_headerStart_1m1ec_189');clock=el('output','_clock_1m1ec_196');start.append(el('strong','_heading_1m1ec_58','运镜编辑'),clock);play=button('播放或暂停整段运镜','播放',()=>{editor.select(-1);runtime.playback.toggle();},'_playButton_1m1ec_202');const actions=el('div','_headerActions_1m1ec_148'),zoomLabel=el('label','_zoom_1m1ec_207'),slider=el('input');slider.type='range';slider.min=1;slider.max=12;slider.step=.5;slider.value=zoom;slider.ariaLabel='时间轴缩放';slider.oninput=()=>{zoom=Number(slider.value);renderTimeline();tick();};zoomLabel.append(slider);actions.append(easing.element,zoomLabel,button('关闭运镜编辑','关闭',()=>editor.close()));header.append(start,play,actions);const body=el('div','_body_1m1ec_139'),timeline=el('div','_editor_1aeqb_1');scroller=el('div','_scroll_1aeqb_11');sheet=el('div','_sheet_1aeqb_18');ruler=el('div','_ruler_1aeqb_26');ruler.role='slider';ruler.tabIndex=0;ruler.ariaLabel='运镜播放头';ruler.onkeydown=e=>{const p=runtime.playback,time=e.key==='Home'?0:e.key==='End'?editor.times.at(-1):e.key==='ArrowLeft'?p.time-1/30:e.key==='ArrowRight'?p.time+1/30:null;if(time!==null){e.preventDefault();editor.seek(time);}};sheet.append(ruler,el('div','_row_1aeqb_59'));scroller.append(sheet);timeline.append(scroller);scroller.addEventListener('wheel',e=>{if(!e.ctrlKey||drag)return;e.preventDefault();const offset=e.clientX-scroller.getBoundingClientRect().left,fraction=(scroller.scrollLeft+offset-16)/Math.max(1,scroller.scrollWidth-32);zoom=Math.max(1,Math.min(12,zoom*Math.exp(-e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?scroller.clientWidth:1)*.01)));slider.value=zoom;renderTimeline();scroller.scrollLeft=fraction*(scroller.scrollWidth-32)+16-offset;tick();},{passive:false});inspector=el('section','_panel_t2l87_34');body.append(timeline,inspector,failure);root.replaceChildren(header,body);renderTimeline();renderInspector();tick();easing.refresh();}
  function tick(){if(!editor.open||!ruler)return;const duration=editor.times.at(-1)||0,time=drag?.next??runtime.playback.time;clock.hidden=editor.selected<0;clock.textContent=`${time.toFixed(2)} / ${duration.toFixed(2)} s`;play.innerHTML=icons[runtime.playback.playing?'暂停':'播放'];ruler.setAttribute('aria-valuemin','0');ruler.setAttribute('aria-valuemax',duration);ruler.setAttribute('aria-valuenow',Math.min(time,duration));head.style.left=line.style.left=time/Math.max(.1,duration)*100+'%';head.textContent=Math.min(time,duration).toFixed(2)+'s';keyButtons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===editor.selected)));const readout=inspector.querySelector('[data-motion-time]');if(readout)readout.textContent=editor.selected>=0?editor.times[editor.selected].toFixed(2)+' s':`${time.toFixed(2)} / ${duration.toFixed(2)} s`;for(const f of fields){if(f.input===document.activeElement)continue;if(f.input.tagName==='OUTPUT')f.input.textContent=f.format();else f.input.value=f.format();}root.parentElement.dataset.keySelected=String(editor.selected>=0);}
  return {element:root,refresh(reason){if(!editor.open)easing.refresh();if(reason==='motion-select'){renderInspector();tick();}else if(reason==='scene'&&editingInspector||['playback','playback-tick','motion-value','transform','saved','save-error'].includes(reason))tick();else render();},dispose(){easing.dispose();}};
}
