import {motionTracks,keyTimes} from './motion-data.mjs';
import * as THREE from 'three';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';
export function cloneDocument(root){const copy=cloneSkeleton(root);const mirror=(a,b)=>{b.uuid=a.uuid;a.children.forEach((child,index)=>mirror(child,b.children[index]));};mirror(root,copy);return copy;}
export class ScenePlayback {
  constructor(runtime){this.runtime=runtime;this.index=-1;this.target='camera';this.time=0;this.playing=false;this.rest=new Map();}
  catalog(){const root=this.runtime.content;return this.runtime.animations.map((clip,index)=>{const cameras=new Set(),objectTracks=[];for(const track of clip.tracks){let node;try{node=THREE.PropertyBinding.findNode(root,THREE.PropertyBinding.parseTrackName(track.name).nodeName);}catch{}if(!node)continue;let objects=false;node.traverse(o=>{if(o.isCamera)cameras.add(o.userData.studioId);if(o.isMesh||o.isBone||o.isLight||o.userData?.worldSplat)objects=true;});if(objects)objectTracks.push(track);}return {index,name:clip.name,duration:clip.duration,cameraIds:[...cameras],objectTracks};});}
  // A chosen shot motion survives temporary object-only playback.
  selectedMotion(){return this.catalog().find(clip=>clip.index===this.runtime.motionIndex&&clip.cameraIds.includes(this.runtime.shotId))||null;}
  toggleMotion(){const selected=this.selectedMotion();if(!selected)return;if(this.index!==selected.index||this.target!=='camera')this.select(selected.index,'camera');else this.toggle();}
  seekMotion(time){const selected=this.selectedMotion();if(!selected)return;if(this.index!==selected.index||this.target!=='camera')this.select(selected.index,'camera',{play:false});this.seek(time);}
  remember(){this.rest.clear();this.runtime.content.traverse(o=>this.rest.set(o.uuid,{position:o.position.clone(),quaternion:o.quaternion.clone(),scale:o.scale.clone(),weights:o.morphTargetInfluences?.slice()}));}
  restore(){this.runtime.content.traverse(o=>{const state=this.rest.get(o.uuid);if(!state)return;o.position.copy(state.position);o.quaternion.copy(state.quaternion);o.scale.copy(state.scale);if(state.weights)o.morphTargetInfluences.splice(0,state.weights.length,...state.weights);o.updateMatrix();});this.runtime.content.updateMatrixWorld(true);}
  stop(notify=false){this.playing=false;this.previewCameraMatrix=null;this.mixer?.stopAllAction();if(this.mixer)this.mixer.uncacheRoot(this.runtime.content);this.restore();this.rest.clear();this.mixer=null;this.index=-1;this.time=0;this.runtime.dirty=true;if(notify)this.runtime.onChange?.('playback');}
  select(index,target='camera',{play=true}={}){const info=this.catalog().find(entry=>entry.index===index);if(!info||target==='objects'&&!info.objectTracks.length)throw Error('动画不存在或没有匹配的轨道');const selectedCamera=this.runtime.find(this.runtime.shotId);selectedCamera?.updateWorldMatrix(true,false);const heldPose=target==='objects'?(this.previewCameraMatrix||selectedCamera?.matrixWorld)?.clone():null;this.stop();this.previewCameraMatrix=heldPose;this.remember();this.index=index;this.target=target;const original=this.runtime.animations[index];this.clip=target==='objects'?new THREE.AnimationClip(original.name,-1,info.objectTracks):original;const camera=this.runtime.find(this.runtime.shotId);this.duration=target==='camera'&&camera?(keyTimes(motionTracks(this.runtime.content,camera,original)).at(-1)??this.clip.duration):this.clip.duration;this.mixer=new THREE.AnimationMixer(this.runtime.content);this.action=this.mixer.clipAction(this.clip).setLoop(THREE.LoopOnce,1);this.action.clampWhenFinished=true;this.action.play();this.playing=play;this.apply(0);this.runtime.onChange?.('playback');}
  apply(time){this.time=Math.max(0,Math.min(this.duration||0,time));if(this.action){this.action.enabled=true;this.action.paused=false;this.mixer.setTime(this.time);this.runtime.content.updateMatrixWorld(true);}this.runtime.dirty=true;}
  seek(time){this.playing=false;this.apply(time);this.runtime.onChange?.('playback');}
  toggle(){if(this.index<0)return;if(this.runtime.motion?.open&&this.runtime.motion.selected>=0)this.runtime.motion.select(-1);if(this.time>=this.duration)this.apply(0);this.playing=!this.playing;this.runtime.onChange?.('playback');}
  update(dt){if(!this.playing)return;this.apply(this.time+dt);if(this.time>=this.duration)this.playing=false;this.runtime.onChange?.('playback-tick');}
  document(){const copy=cloneDocument(this.runtime.content);copy.traverse(o=>{const state=this.rest.get(o.uuid);if(!state)return;o.position.copy(state.position);o.quaternion.copy(state.quaternion);o.scale.copy(state.scale);if(state.weights)o.morphTargetInfluences.splice(0,state.weights.length,...state.weights);o.updateMatrix();});return copy;}
}
