import {el,button} from './dom.mjs';
import {icons} from './icons.mjs';
import {classes as c} from './classes.mjs';
import {ShotRenderer} from './shot-renderer.mjs';
import {exportMotion} from './video-export.mjs';
export function createShotPreview(runtime){
  const row=el('div',c.motionPreviewRow),slot=el('div',c.previewSlot),panel=el('section',c.preview);panel.ariaLabel='镜头预览';row.append(slot);slot.append(panel);let expanded=false,collapsed=false,busy=false,error='',result=null;
  const header=el('header'),heading=button('收起镜头预览','收起镜头预览',()=>{collapsed=!collapsed;expanded=false;refresh();},c.previewHeading),title=el('span'),expand=button('放大镜头预览','放大镜头预览',()=>{expanded=!expanded;collapsed=false;refresh();});const cameraIcon=el('span');cameraIcon.innerHTML=icons['相机'];heading.append(cameraIcon,title);header.append(heading,expand);const content=el('div',c.previewContent),body=el('div',c.previewBody),canvas=el('canvas');canvas.ariaLabel='当前镜头拍到的画面';body.append(canvas);const empty=el('p','','还没有镜头，可让 Agent 添加');body.append(empty);const play=button('播放运镜',null,()=>runtime.playback.toggleMotion(),c.previewPlayback),playIcon=el('span',c.previewPlaybackIcon);play.append(playIcon);body.append(play);const footer=el('footer',c.previewActions),ratios=el('fieldset','_control_zjgpv_1'),presets=el('div','_presets_zjgpv_7');ratios.ariaLabel='画面比例';ratios.append(presets);const ratioButtons=[];
  for(const [id,label,width,height] of [['original','原始比例'],['1:1','1:1',1,1],['9:16','9:16',9,16],['16:9','16:9',16,9]]){const b=button(label,id==='original'?'原始比例':null,()=>runtime.setShotRatio(width?{width,height}:null),'_ratio_zjgpv_15');b.title=label;if(width){const glyph=el('span','_glyph_zjgpv_49'),inner=el('span');glyph.style.cssText='width:12px;height:12px';inner.style.width=(width>=height?12:12*width/height)+'px';inner.style.height=(width>=height?12*height/width:12)+'px';glyph.append(inner);b.append(glyph);}b.append(el('small','',id==='original'?'原始':label));presets.append(b);ratioButtons.push({b,width,height});}
  const timeline=el('div','_timeline_th2jb_1'),track=el('div','_seekTrack_th2jb_41'),seek=el('input');seek.type='range';seek.min=0;seek.step='any';seek.ariaLabel='预览播放进度';seek.onpointerdown=()=>runtime.playback.seekMotion(Number(seek.value));seek.oninput=()=>runtime.playback.seekMotion(Number(seek.value));seek.onkeydown=e=>{e.stopPropagation();const p=runtime.playback;if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();p.seekMotion(e.key==='Home'?0:e.key==='End'?p.duration:(e.key==='ArrowLeft'?Math.ceil(p.time*30-1e-6)-1:Math.floor(p.time*30+1e-6)+1)/30);}};track.append(seek);const readout=el('div','_readout_th2jb_17'),time=el('output'),toggle=button('播放运镜','播放',()=>runtime.playback.toggleMotion());readout.append(time,toggle);timeline.append(track,readout);
  const hint=el('p',c.sectionHint,'选择一段运镜，即可预览和导出视频。'),exportButton=button('导出视频到画布','导出视频',async()=>{busy=true;error='';result=null;refresh();try{result=await exportMotion(runtime,progress=>{progressText.textContent=progress.stage==='rendering'?'正在生成视频 '+Math.round(progress.progress*100)+'%':'正在添加到画布…';});}catch(e){error=e.message;}finally{busy=false;refresh();}},c.exportButton,'导出视频到画布'),progressText=el('output'),failure=el('div');failure.role='alert';footer.append(ratios,timeline,exportButton,hint,progressText,failure);content.append(body,footer);panel.append(header,content);panel.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();expanded=false;refresh();}};
  const renderer=new ShotRenderer(runtime,canvas);runtime.shotRenderer=renderer;
  function tick(){const p=runtime.playback,active=p.target==='camera'&&p.index===runtime.motionIndex,playing=active&&p.playing,ended=active&&p.duration>0&&p.time>=p.duration-1e-3;seek.max=p.duration||0;seek.value=p.time;seek.setAttribute('aria-valuetext',`${p.time.toFixed(2)} / ${(p.duration||0).toFixed(2)} 秒`);time.textContent=`${p.time.toFixed(2)} / ${(p.duration||0).toFixed(2)} s`;const label=ended?'重新播放运镜':playing?'暂停运镜':'播放运镜';play.ariaLabel=label;play.dataset.ended=String(ended);play.dataset.playing=String(playing);playIcon.innerHTML=icons[ended?'重新播放运镜':playing?'暂停':'播放'];toggle.ariaLabel=playing?'暂停运镜':'播放运镜';toggle.innerHTML=icons[playing?'暂停':'播放'];}
  function refresh(){const camera=runtime.find(runtime.shotId),p=runtime.playback,hasMotion=!!camera&&!!p.selectedMotion();row.hidden=runtime.loadStatus!=='ready'||!runtime.content.children.length;panel.classList.toggle(c.expanded,expanded);content.hidden=collapsed;heading.ariaLabel=collapsed?'展开镜头预览':'收起镜头预览';heading.setAttribute('aria-expanded',String(!collapsed));heading.querySelector('svg').classList.toggle(c.collapsedChevron,collapsed);title.textContent=camera?.name||'镜头预览';expand.disabled=!camera;expand.ariaLabel=expanded?'缩小镜头预览':'放大镜头预览';expand.setAttribute('aria-expanded',String(expanded));expand.innerHTML=icons[expanded?'缩小镜头预览':'放大镜头预览'];empty.hidden=!!camera;play.hidden=!hasMotion;play.disabled=busy;ratios.disabled=!camera||busy;const ratio=runtime.shotRatios[runtime.shotId];for(const {b,width,height} of ratioButtons)b.setAttribute('aria-pressed',String(width?!!ratio&&ratio.width*height===ratio.height*width:!ratio));timeline.hidden=!expanded||!hasMotion||p.target==='objects';seek.disabled=toggle.disabled=busy;exportButton.hidden=!hasMotion;exportButton.disabled=busy;hint.hidden=hasMotion&&!(expanded&&p.target==='objects');hint.textContent=p.index>=0&&p.target==='objects'?'正在单独预览人物和物体。播放运镜可恢复镜头运动。':'选择一段运镜，即可预览和导出视频。';progressText.hidden=!busy&&!result;if(result)progressText.textContent='视频已添加到画布';failure.replaceChildren();if(error)failure.append(el('p','','视频导出失败'),el('small','',error),button('重试导出',null,()=>exportButton.click(),'','重试导出'));failure.hidden=!error;tick();runtime.dirty=true;}
  return {element:row,refresh,tick,dispose(){renderer.dispose();runtime.shotRenderer=null;}};
}
