import {createMotionUI} from './motion-ui.mjs';
import {createSceneExportController,sceneSize} from './scene-export.mjs';
import {createShotPreview} from './shot-preview.mjs';
import {defaultLighting} from './runtime.mjs';
import {createScenePanel} from './scene-panel.mjs';
import {el,button} from './dom.mjs';
import {objectInspector} from './object-inspector.mjs';
import {classes as c} from './classes.mjs';
import {inspectModel,disposeLoadedModel} from './model-io.mjs';
import {createStudioComposer} from '../agent-scene/studio-composer.mjs';
import {bindTooltip} from '../agent-composer/tooltip.mjs';
import {bindPopoverFocus,focusPopover,focusPopoverTrigger,preservePopoverFocus} from './popover-focus.mjs';
export function createUI({root,runtime,onClose}){
  let popup=null,popupTrigger=null,finalizePopup=null,disposePopupFocus=null,disposed=false,prepared=null,modelFile=null,resources=[],generation=0,loading=false,importing=false,error='',currentTab='shooting';
  let exportItem=null,exportDetail=null;
  const sceneExport=createSceneExportController(runtime,{onChange:state=>{if(!exportItem?.isConnected)return;exportItem.disabled=!state.available||state.busy;exportItem.setAttribute('aria-busy',String(state.busy));exportDetail.textContent=state.error?'无法计算文件大小，请重试':state.busy?'正在导出…':state.size!==null?sceneSize(state.size):state.calculating?'正在计算文件大小…':'待计算文件大小';exportItem.title=state.error||state.filename;}});
  const scenePanel=createScenePanel(runtime);let lastPlaying=false;
  const controls=[];let composerReady=false;
  function act(fn){return async()=>{try{await fn();}catch(e){notice(e.message);}};}
  function tip(b,text){controls.push(bindTooltip(b,{text:()=>text}));return b;}
  function notice(message){status.textContent=message;status.hidden=false;}
  function releasePrepared(){if(prepared)disposeLoadedModel(prepared.loaded,{retain:runtime.content});prepared=null;}
  function closePopup(restoreFocus=!!popup?.contains(document.activeElement)){if(importing)return false;const trigger=popupTrigger,isImport=popup?.ariaLabel==='添加模型';disposePopupFocus?.();disposePopupFocus=null;finalizePopup?.();finalizePopup=null;generation++;releasePrepared();loading=false;popup?.remove();popup=null;trigger?.setAttribute('aria-expanded','false');popupTrigger=null;if(restoreFocus)focusPopoverTrigger(trigger,isImport?root.querySelector('button[aria-label="添加模型"]'):null);}
  function openPopup(trigger,label,cls=''){
    if(importing){notice('模型正在添加并保存，请等待完成');return null;}if(popupTrigger===trigger){closePopup();return null;}closePopup(false);const node=el('div','studio-v2-popover '+cls);node.role='dialog';node.ariaLabel=label;node.tabIndex=-1;document.body.append(node);popup=node;popupTrigger=trigger;trigger.setAttribute('aria-expanded','true');disposePopupFocus=bindPopoverFocus(node,{trigger,canDismiss:()=>!importing,onDismiss:()=>closePopup(false)});return node;
  }
  function placePopup(){if(!popup||!popupTrigger?.isConnected)return;const r=popupTrigger.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(innerWidth-popup.offsetWidth-8,r.left))+'px';popup.style.top=Math.max(8,Math.min(innerHeight-popup.offsetHeight-8,r.bottom+8))+'px';}
  const abort=new AbortController();document.addEventListener('pointerdown',e=>{if(!importing&&!popup?.contains(e.target)&&!popupTrigger?.contains(e.target))closePopup(false);},{capture:true,signal:abort.signal});document.addEventListener('keydown',e=>{if(popup&&e.key==='Escape'&&!e.defaultPrevented&&!e.isComposing&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopImmediatePropagation();if(importing){notice('模型正在添加并保存，请等待完成');return;}closePopup(true);}},{signal:abort.signal});window.addEventListener('resize',placePopup,{signal:abort.signal});
  function help(trigger){const p=openPopup(trigger,'视角操作提示',c.navigationHints);if(!p)return;p.append(el('span','','点击场景后'));for(const [keys,label] of [[['拖动'],'转向'],[['滚轮'],'远近'],[['W','S'],'前后'],[['A','D'],'左右'],[['Q','E'],'升降'],[['Shift'],'加速'],...(runtime.selected?[[['F'],'聚焦'],[['P'],'移动'],[['R'],'旋转'],[['T'],'缩放']]:[])]){const line=el('span');keys.forEach(k=>line.append(el('kbd','',k)));line.append(document.createTextNode(label));p.append(line);}placePopup();p.focus();}
  async function inspect(){const token=++generation;releasePrepared();loading=true;error='';renderImport();try{const next=await inspectModel(modelFile,resources);if(disposed||token!==generation){disposeLoadedModel(next.loaded);return;}releasePrepared();prepared=next;}catch(e){if(token===generation)error=e.message;}finally{if(token===generation){loading=false;renderImport();}}}
  async function add(kind){if(importing)return;const originPopup=popup,sceneIndex=kind?null:Number(popup.querySelector('select')?.value??prepared.defaultScene);importing=true;renderImport();try{if(kind)await runtime.add(kind);else await runtime.importPrepared(prepared,sceneIndex);releasePrepared();modelFile=null;resources=[];importing=false;if(popup===originPopup)closePopup(true);notice('模型已添加并保存');}catch(e){importing=false;if(e.applied){releasePrepared();if(popup===originPopup)closePopup(true);notice('场景保存失败，本地修改已保留：'+e.message);}else{error=e.message;renderImport();}}}
  function importMenu(trigger){const p=openPopup(trigger,'添加模型','studio-v2-import');if(!p)return;prepared=null;modelFile=null;resources=[];error='';loading=false;renderImport();p.querySelector('button:not(:disabled)')?.focus({preventScroll:true});}
  function renderImport(){if(!popup||popup.ariaLabel!=='添加模型')return;const p=popup,restoreFocus=preservePopoverFocus(p);p.replaceChildren();const file=el('input');file.type='file';file.accept='.gltf,.glb';file.hidden=true;file.ariaLabel='选择模型文件';file.disabled=importing;file.onchange=()=>{if(importing)return;modelFile=file.files[0];resources=[];releasePrepared();inspect();};const extra=el('input');extra.type='file';extra.multiple=true;extra.hidden=true;extra.ariaLabel='补充关联资源';extra.disabled=importing;extra.onchange=()=>{if(importing)return;resources=[...new Map([...resources,...extra.files].map(f=>[f.name,f])).values()];inspect();};p.append(file,extra);
    const upload=button('上传模型','上传模型glTF 2.0 · .gltf / .glb',()=>file.click(),'studio-v2-upload');const copy=el('span');copy.append(el('strong','',modelFile?.name||'上传模型'),el('small','',modelFile?(modelFile.size/1024/1024).toFixed(2)+' MiB':'glTF 2.0 · .gltf / .glb'));upload.append(copy);upload.disabled=importing;upload.ondragover=e=>{e.preventDefault();upload.classList.add('dragover');};upload.ondragleave=()=>upload.classList.remove('dragover');upload.ondrop=e=>{e.preventDefault();upload.classList.remove('dragover');if(importing)return;const files=[...e.dataTransfer.files],models=files.filter(f=>/\.(gltf|glb)$/i.test(f.name));if(models.length!==1){error='请选择一个 .gltf 或 .glb 模型文件。';renderImport();return;}modelFile=models[0];resources=files.filter(f=>f!==modelFile);inspect();};p.append(upload);
    if(modelFile){const row=el('div','studio-v2-resource');const resourceButton=button('补充关联资源',null,()=>extra.click(),'','添加文件');resourceButton.disabled=importing;row.append(el('span','',resources.length?'已添加 '+resources.length+' 个关联文件':'需要关联资源？'),resourceButton);p.append(row);if(prepared?.scenes.length>1){const label=el('label','studio-v2-scene-option','导入场景');const select=el('select');select.ariaLabel='导入场景';select.disabled=importing;for(const scene of prepared.scenes){const option=el('option','',scene.name);option.value=scene.index;select.append(option);}select.value=prepared.defaultScene;label.append(select);p.append(label);}const addButton=button('添加到场景',null,()=>add(),'studio-v2-add',importing?'正在保存…':loading?'正在检查…':'添加到场景');addButton.disabled=importing||loading||!prepared;p.append(addButton);}
    p.append(el('hr'),el('p','studio-v2-muted','基础图形'));for(const [kind,name] of [['cube','立方体'],['sphere','球体'],['pyramid','四棱锥']]){const b=button(name,name,()=>add(kind),'studio-v2-shape',name);b.disabled=importing;b.setAttribute('aria-busy',String(importing));p.append(b);}if(error){const message=el('div','studio-v2-error',error);message.role='alert';p.append(message);}p.append(el('p','studio-v2-muted','合并后的场景最大 12 MiB，添加后自动保存。'));placePopup();restoreFocus();}
  function lightingMenu(trigger){
    const p=openPopup(trigger,'光照设置','_panel_fdwir_1');if(!p)return;p.append(el('h3','_heading_fdwir_13','光照'));const fields=[],finishers=[];
    const reset=button('恢复默认光照','撤销',()=>{runtime.setLighting(defaultLighting);sync();},'_reset_fdwir_49','恢复默认光照');
    function sync(){for(const {key,input,output} of fields){input.value=runtime.lighting[key];output.textContent=Math.round(runtime.lighting[key])+'°';}reset.disabled=runtime.lighting.azimuth===defaultLighting.azimuth&&runtime.lighting.elevation===defaultLighting.elevation;}
    for(const [key,label,aria,min,max] of [['azimuth','绕场景旋转','绕场景旋转光照',0,360],['elevation','光源高度','光源高度',-90,90]]){
      const row=el('label','_slider_fdwir_18'),heading=el('span','',label),output=el('output'),input=el('input');input.type='range';input.min=min;input.max=max;input.step=1;input.ariaLabel=aria;heading.append(output);row.append(heading,input);let editing=false;
      input.oninput=()=>{if(!editing){runtime.beginEdit();editing=true;}runtime.setLighting({[key]:Number(input.value)},{history:false,notify:false});sync();};const finish=()=>{if(editing){editing=false;runtime.commit();}};input.onchange=input.onblur=finish;finishers.push(finish);
      if(key==='elevation'){const ends=el('span','_ends_fdwir_45');ends.ariaHidden='true';for(const label of ['下方','水平','上方'])ends.append(el('span','',label));row.append(ends);}fields.push({key,input,output});p.append(row);
    }
    finalizePopup=()=>finishers.forEach(finish=>finish());p.append(reset);sync();placePopup();focusPopover(p);
  }
  function createExportItem(){exportItem=button('导出场景(glb)文件','下载',act(async()=>{const result=await sceneExport.download();if(result){notice('场景已导出：'+result.filename+' · '+sceneSize(result.size));closePopup();}}),'studio-v2-shape','');const text=el('span','studio-v2-export-copy'),label=el('span','','导出场景(glb)文件');exportDetail=el('small');text.append(label,exportDetail);exportItem.append(text);sceneExport.sync();sceneExport.prepare().catch(()=>{});return exportItem;}
  const empty=el('div',c.emptyScene),guidance=el('section',c.emptyGuidance);guidance.ariaLabel='开始搭建场景';const h1=el('h1');const orb=button('打开 Agent',null,()=>openAgent(false),'studio-v2-orb');orb.append(Object.assign(el('img'),{src:'/assets/agent.webp',alt:''}));h1.append(orb,document.createTextNode('要拍摄什么场景？'));guidance.append(h1);
  const composer=createStudioComposer({nodeId:runtime.nodeId,onError:notice,beforeOpen:closePopup,onState:()=>{if(composerReady)refresh('agent');}});guidance.append(composer.element);
  function openAgent(){composer.open();}
  const hint=el('p',c.emptyImportHint,'或者');const importButton=button('导入模型','导入模型',()=>importMenu(importButton),'','导入模型');hint.append(importButton);guidance.append(hint);empty.append(guidance);root.append(empty);
  const ui=el('div',c.workspaceUi),toolbar=el('div',c.workspaceToolbar),start=el('nav',c.toolbarStart);start.ariaLabel='3D 片场';const back=tip(button('返回画布','返回画布',act(async()=>{sceneExport.cancel();await onClose();}),c.iconToggle),'返回画布'),helpButton=button('视角操作帮助','视角操作帮助',()=>help(helpButton),c.iconToggle);start.append(back,helpButton);const primary=el('div',c.toolbarPrimary),addButton=tip(button('添加模型','添加模型',()=>importMenu(addButton),c.modelAddTrigger),'添加模型');primary.append(addButton);const end=el('div',c.sceneViewTools);const frame=tip(button('查看全景','聚焦',()=>{runtime.focus(runtime.content);runtime.focusView();},c.iconToggle),'查看整场布景');const more=button('更多','更多',()=>{const p=openPopup(more,'更多','studio-v2-import');if(!p)return;p.append(button(runtime.grid.visible?'隐藏地面网格':'显示地面网格','场景',()=>{runtime.setGrid(!runtime.grid.visible);closePopup();},'studio-v2-shape',runtime.grid.visible?'隐藏地面网格':'显示地面网格'),createExportItem());sceneExport.sync();placePopup();focusPopover(p);},c.iconToggle);const light=tip(button('光照','光照',()=>lightingMenu(light),c.iconToggle),'光照');end.append(light,frame,more);toolbar.append(start,primary,end);ui.append(toolbar);const panels=el('div',c.workspacePanels);ui.append(panels);root.append(ui);const preview=createShotPreview(runtime);ui.append(preview.element);const motionUI=createMotionUI(runtime);preview.element.prepend(motionUI.element);
  const status=el('output','studio-v2-notice');status.hidden=true;root.append(status);const loadingStatus=el('div',c.status);loadingStatus.role='status';root.append(loadingStatus);const saveStatus=el('div',c.editStatus);saveStatus.role='alert';saveStatus.hidden=true;root.append(saveStatus);const corner=el('div',c.emptyAgentCorner),agent=button('打开片场 Agent',null,()=>openAgent(false),'studio-v2-orb');agent.append(Object.assign(el('img'),{src:'/assets/agent.webp',alt:''}));corner.append(agent);root.append(corner);
  function refreshScenePanel(){const section=panels.querySelector('section[aria-label="片场设置"]'),active=section?.contains(document.activeElement)?document.activeElement.dataset.animationIndex:null;if(section){const next=scenePanel.render();section.replaceWith(next);if(active!==null&&active!==undefined)next.querySelector('[data-animation-index="'+active+'"]')?.focus({preventScroll:true});}lastPlaying=runtime.playback.playing;}
  function renderPanels(){lastPlaying=runtime.playback.playing;panels.replaceChildren();if(!runtime.content.children.length)return;panels.append(scenePanel.render());
    if(runtime.selected){const right=el('div',c.rightPanels);right.append(objectInspector(runtime));panels.append(right);}
  }
  function refresh(reason){sceneExport.sync();if(reason==='agent'){empty.hidden=runtime.loadStatus!=='ready'||!!runtime.content.children.length||!!composer.state?.hasSubmitted;return;}motionUI.refresh(reason);if(reason==='playback-tick'){preview.tick();if(lastPlaying!==runtime.playback.playing)refreshScenePanel();return;}if(reason==='playback')refreshScenePanel();preview.refresh();const ready=runtime.loadStatus==='ready',populated=ready&&!!runtime.content.children.length;empty.hidden=!ready||populated||!!composer.state?.hasSubmitted;ui.dataset.guidance=String(ready&&!populated);primary.hidden=end.hidden=!populated;panels.hidden=!ready;corner.hidden=!ready;loadingStatus.hidden=ready;
    if(!ready){loadingStatus.replaceChildren(el('p','',runtime.loadStatus==='error'?'场景加载失败':'正在加载 3D 场景…'));if(runtime.loadError)loadingStatus.append(el('small','',runtime.loadError.message),button('重新加载',null,act(()=>runtime.initialize()),'','重新加载'));}
    const recovering=!!runtime.reloading;back.disabled=recovering;panels.inert=preview.element.inert=primary.inert=end.inert=empty.inert=corner.inert=recovering;
    saveStatus.hidden=!runtime.saveError&&!recovering;if(!saveStatus.hidden){
      const retry=button('重试保存',null,act(async()=>{if(importing)throw Error('模型正在添加并保存，请等待完成');await runtime.flush();refresh('saved');}),'','重试保存');
      const discard=button('放弃修改并重新加载',null,act(async()=>{if(importing)throw Error('模型正在添加并保存，请等待完成');finalizePopup?.();closePopup(false);await runtime.discardEditsAndReload();notice('已重新加载已保存场景');runtime.focusView();}),'','放弃修改并重新加载');
      retry.disabled=discard.disabled=!!runtime.saving||recovering;discard.setAttribute('aria-busy',String(recovering));
      saveStatus.replaceChildren(el('p','',recovering?'正在重新加载已保存场景…':'场景保存失败，本地修改已保留'));if(runtime.saveError)saveStatus.append(el('small','',runtime.saveError.message));saveStatus.append(retry,discard);
    }
    if(!['transform','saved','save-error','save-start','save-idle','reload-start','reload-idle','motion-select','motion-value','playback'].includes(reason))renderPanels();
  }
  composerReady=true;refresh();return {refresh,notice,assertCanClose(){if(importing)throw Error('模型正在添加并保存，请等待完成');finalizePopup?.();},dispose(){disposed=true;sceneExport.dispose();composer.destroy();abort.abort();closePopup();preview.dispose();motionUI.dispose();controls.forEach(c=>c.destroy());window.VoiceInput.cancel();}};
}
