import {ShotRenderer} from './shot-renderer.mjs';
export async function exportMotion(runtime,onProgress=()=>{},{signal}={}){
  const assertActive=()=>{if(signal?.aborted)throw signal.reason??new DOMException('视频导出已取消','AbortError');};assertActive();
  const playback=runtime.playback;if(!playback.selectedMotion())throw Error('请先选择运镜');if(runtime.exporting)throw Error('视频正在导出');
  const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(type=>globalThis.MediaRecorder?.isTypeSupported(type));if(!mime)throw Error('当前浏览器没有可用的视频编码器');
  await runtime.flush();assertActive();if(runtime.exporting)throw Error('视频正在导出');const revision=runtime.revision,previous={index:playback.index,target:playback.target,time:playback.time,playing:playback.playing,previewCameraMatrix:playback.previewCameraMatrix?.clone()};runtime.exporting=true;let duration;
  const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;left:-10000px;top:0;width:1280px;height:720px;pointer-events:none';canvas.ariaHidden='true';document.body.append(canvas);let shot,stream,recorder,frame;
  let rejectAbort;const aborted=new Promise((_,reject)=>{rejectAbort=reject;});aborted.catch(()=>{});const abort=()=>rejectAbort(signal.reason??new DOMException('视频导出已取消','AbortError'));signal?.addEventListener('abort',abort,{once:true});
  try{assertActive();if(!playback.selectedMotion())throw Error('所选运镜已改变，请重新选择');playback.select(runtime.motionIndex,'camera',{play:false});duration=playback.duration;shot=new ShotRenderer(runtime,canvas);shot.renderer.setPixelRatio(1);const camera=shot.camera();const aspect=camera.isPerspectiveCamera?camera.aspect:(camera.right-camera.left)/(camera.top-camera.bottom);const maxWidth=aspect>=1?1280:720,maxHeight=aspect>=1?720:1280,height=Math.max(2,Math.floor(Math.min(maxHeight,maxWidth/aspect)/2)*2),width=Math.max(2,Math.floor(height*aspect/2)*2);canvas.style.width=width+'px';canvas.style.height=height+'px';playback.apply(0);await shot.ready({width,height});assertActive();shot.render();const poster=canvas.toDataURL('image/png');stream=canvas.captureStream(30);const chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6000000});const completed=new Promise((resolve,reject)=>{recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onerror=event=>reject(event.error||Error('视频编码失败'));recorder.onstop=resolve;});completed.catch(()=>{});recorder.start(100);const start=performance.now();
    await Promise.race([Promise.all([new Promise((resolve,reject)=>{const tick=async now=>{try{assertActive();if(runtime.closed||runtime.revision!==revision)throw Error('片场发生变化，本次导出已取消');const time=Math.min(duration,(now-start)/1000);playback.apply(time);runtime.updateLighting();await shot.ready({width,height});assertActive();shot.render();onProgress({stage:'rendering',progress:time/duration});if(time>=duration){recorder.stop();resolve();}else frame=requestAnimationFrame(tick);}catch(error){reject(error);}};frame=requestAnimationFrame(tick);}),completed]),aborted]);
    assertActive();if(!chunks.length)throw Error('未收到视频编码结果');onProgress({stage:'saving',progress:1});assertActive();let blob=new Blob(chunks,{type:mime});if(window.LocalMedia?.process)blob=await Promise.race([window.LocalMedia.process('finalize',blob,{duration}),aborted]);assertActive();const url=await Promise.race([window.LocalAssets.put(blob),aborted]);assertActive();
    if(runtime.closed||runtime.revision!==revision||!window.CanvasApp.getState().nodes.some(node=>node.id===runtime.nodeId))throw Error('来源片场已改变，未添加视频');
    assertActive();const nodes=window.CanvasApp.createConnected(runtime.nodeId,[{type:'video',title:'3D 片场运镜',video:url,image:poster,width,height,duration,videoMetadata:{width,height,duration},provenance:{kind:'studio-render',sceneId:runtime.nodeId,shotId:runtime.shotId,animation:playback.index},createdAt:new Date().toISOString()}]);const nodeId=nodes[0]?.id;if(!nodeId)throw Error('画布未创建视频节点');try{await window.CanvasStore.flush();}catch(error){Object.assign(error,{applied:true,nodeId});throw error;}return {nodeId,duration,width,height};
  }finally{signal?.removeEventListener('abort',abort);cancelAnimationFrame(frame);if(recorder&&recorder.state!=='inactive'){try{recorder.stop();}catch{}}stream?.getTracks().forEach(track=>track.stop());await shot?.dispose();canvas.remove();try{if(previous.index>=0){playback.select(previous.index,previous.target,{play:false});playback.previewCameraMatrix=previous.previewCameraMatrix;playback.apply(previous.time);playback.playing=previous.playing;}else playback.stop();}finally{runtime.exporting=false;runtime.dirty=true;}}
}
