import * as THREE from 'three';
import {point} from './core.mjs';
export function createStage(mount,image,onChange,onHandle){
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,1,.1,100),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(216,216);renderer.setPixelRatio(Math.min(devicePixelRatio,2));mount.append(renderer.domElement);camera.position.set(0,1,15);camera.lookAt(0,0,0);
  const shell=new THREE.Mesh(new THREE.SphereGeometry(6.464,64,64),new THREE.ShaderMaterial({uniforms:{baseColor:{value:new THREE.Color('#cccccc')}},vertexShader:'varying vec3 n;varying vec3 v;void main(){n=normalize(normalMatrix*normal);vec4 p=modelViewMatrix*vec4(position,1.);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 baseColor;varying vec3 n;varying vec3 v;void main(){float e=pow(1.-max(dot(normalize(n),normalize(v)),0.),2.);gl_FragColor=vec4(mix(baseColor,vec3(0.),e*.5),.08+e*.45);}',transparent:true,side:THREE.FrontSide,depthWrite:false}));scene.add(shell, new THREE.AmbientLight(0xf2f2f7,.55));for(const [color,intensity,pos]of[[0xfff6df,1.05,[4,7,9]],[0xc5d9ff,.42,[-6,3,-2]],[0xffffff,.28,[0,2,-8]]]){const light=new THREE.DirectionalLight(color,intensity);light.position.set(...pos);scene.add(light);}
  const handles=['#d8d8de','#c4a484'].map(color=>{const group=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.35,metalness:.55});const body=new THREE.Mesh(new THREE.SphereGeometry(.38,24,24),mat);body.scale.set(1.05,.85,1.15);const lens=new THREE.Mesh(new THREE.CylinderGeometry(.2,.24,.38,32),mat);lens.rotation.x=Math.PI/2;lens.position.z=.55;const glass=new THREE.Mesh(new THREE.CircleGeometry(.16,32),new THREE.MeshPhysicalMaterial({color,roughness:.06,metalness:.12,transparent:true,opacity:.9}));glass.position.z=.75;group.add(body,lens,glass);scene.add(group);return group;});
  const subject=new THREE.Mesh(new THREE.PlaneGeometry(3.2,1.8),new THREE.MeshBasicMaterial({color:0x3a3a3f,side:THREE.DoubleSide}));scene.add(subject);
  let alive=true,frame,active='a',state,drag,texture,view='front';const target=new THREE.Vector3(0,1,15),coords=new THREE.Vector2(),ray=new THREE.Raycaster();
  if(image)new THREE.TextureLoader().load(image,t=>{if(!alive){t.dispose();return;}texture=t;t.colorSpace=THREE.SRGBColorSpace;subject.material.map=t;subject.material.color.set(0xffffff);subject.material.needsUpdate=true;subject.scale.set(1,(t.image.height/t.image.width)/(1.8/3.2),1);},undefined,()=>{});
  function place(group,p){const az=p.azimuth*Math.PI/180,el=p.elevation*Math.PI/180;group.position.set(6.4*Math.cos(el)*Math.sin(az),6.4*Math.sin(el),6.4*Math.cos(el)*Math.cos(az));group.lookAt(0,0,0);}
  function update(s,handle){state=s;active=handle;place(handles[0],s.pointA);handles[1].visible=!!s.pointB;if(s.pointB)place(handles[1],s.pointB);const p=handle==='b'&&s.pointB?s.pointB:s.pointA;subject.scale.x=1.3-p.distance*.8;subject.scale.y=subject.scale.x*(texture?(texture.image.height/texture.image.width)/(1.8/3.2):1);renderer.domElement.dataset.camera=JSON.stringify(p);}
  const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('role','application');canvas.setAttribute('aria-label','拖动相机调整视角');
  canvas.onpointerdown=e=>{if(e.button!==0||!state)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);let handle=active;if(state.pointB){const r=canvas.getBoundingClientRect();coords.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(coords,camera);for(const [i,h]of handles.entries()){if(ray.ray.intersectsSphere(new THREE.Sphere(h.position,1.6))){handle=i?'b':'a';break;}}}active=handle;onHandle(handle);drag={x:e.clientX,y:e.clientY,p:{...(handle==='b'?state.pointB:state.pointA)}};canvas.style.cursor='grabbing';};
  canvas.onpointermove=e=>{if(!drag)return;const p=point({...drag.p,azimuth:drag.p.azimuth+(e.clientX-drag.x)*.8,elevation:drag.p.elevation-(e.clientY-drag.y)*.8});place(handles[active==='b'?1:0],p);drag.value=p;};
  canvas.onpointerup=canvas.onpointercancel=()=>{if(!drag)return;const value=drag.value||drag.p;drag=null;canvas.style.cursor='crosshair';onChange(active,value);};
  canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!state)return;e.preventDefault();const p=active==='b'?state.pointB:state.pointA;onChange(active,point({...p,azimuth:p.azimuth+(e.key==='ArrowLeft'?-5:e.key==='ArrowRight'?5:0),elevation:p.elevation+(e.key==='ArrowUp'?5:e.key==='ArrowDown'?-5:0)}));};
  function render(){if(!alive)return;camera.position.lerp(target,.08);camera.lookAt(0,0,0);renderer.render(scene,camera);frame=requestAnimationFrame(render);}render();
  return {update,setView(value){view=value;target.set(...(view==='perspective'?[11,8,10]:[0,1,15]));},dispose(){alive=false;cancelAnimationFrame(frame);texture?.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});renderer.dispose();canvas.remove();}};
}
