import * as core from './core.mjs';
import {reshootRequestState} from './native-profile.mjs';
import {mediaSource} from '../video-creation/core.mjs';
import {openVideoFrames} from '../video-media/frames.mjs';
import {createStage} from './stage.mjs';
import icons from './icons.mjs';
const app=window.CanvasApp,el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const button=(label,fn,icon=false)=>{const b=el('button','',icon?'':label);b.type='button';b.setAttribute('aria-label',label);if(icon){b.innerHTML=icons[label]||'';b.dataset.tooltip=label;}b.onclick=fn;return b;};
let current;
class Reshoot {
  constructor(node){
    this.sourceNode=node;this.projectId=app.projectIdentity().id;this.id=node.id;this.source=mediaSource(node);this.clip=JSON.stringify(node.clip||null);this.alive=true;this.listeners=new AbortController();this.guard=core.sourceGuard(app,node,{signal:this.listeners.signal,isAlive:()=>this.alive});this.handle='a';this.time=0;this.offset=0;this.duration=0;this.state=core.initial(5);this.loaded=false;this.initialView={...app.getState().view};
    this.root=el('section','video-reshoot');this.root.setAttribute('aria-label','视频重拍');this.root.tabIndex=-1;document.body.append(this.root);document.body.classList.add('video-reshoot-active');this.root.onpointerdown=e=>e.stopPropagation();this.root.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();this.close();}};
    const timeline=el('div','reshoot-timeline'),head=el('header');this.count=el('span');this.range=el('span');const actions=el('div');this.play=button('播放',()=>this.togglePlay(),true);this.split=button('在此处剪切',()=>{this.state=core.split(this.state,this.time,crypto.randomUUID());this.handle='a';this.dirty=true;this.paint();},true);this.reset=button('重置整段',()=>{this.state=core.reset(this.state,this.duration);this.handle='a';this.dirty=true;this.paint();},true);actions.append(this.play,this.split,this.reset,button('关闭',()=>this.close(),true));head.append(this.count,this.range,actions);
    this.track=el('div','reshoot-track');this.track.title='拖动定位 · 双击命名 · 可剪切处显示剪刀';this.track.setAttribute('role','slider');this.track.setAttribute('aria-label','分镜时间轴');this.track.setAttribute('aria-valuemin','0');this.track.tabIndex=0;this.thumbs=el('div','reshoot-thumbnails');this.shots=el('div','reshoot-shots');this.playhead=el('div','reshoot-playhead');this.track.append(this.thumbs,this.shots,this.playhead);this.ends=el('div','reshoot-ends');this.ends.append(el('span','','0.0s'),el('span','','—'));timeline.append(head,this.track,this.ends);
    let dragging=false;const seek=e=>{const r=this.track.getBoundingClientRect();this.seek((e.clientX-r.left)/r.width*this.duration);};this.track.onpointerdown=e=>{if(e.button!==0||!this.loaded)return;e.preventDefault();this.track.setPointerCapture(e.pointerId);dragging=true;this.player()?.pause();seek(e);};this.track.onpointermove=e=>{if(dragging)seek(e);};this.track.onpointerup=this.track.onpointercancel=()=>dragging=false;this.track.ondblclick=()=>this.rename();this.track.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();this.seek(e.key==='Home'?0:e.key==='End'?this.duration:this.time+(e.key==='ArrowLeft'?-.1:.1));}if(e.key==='Enter')this.rename();};
    this.modeRow=el('div','reshoot-mode-row');this.modeRow.append(el('span','','镜头变化'));this.modeButtons=el('div','reshoot-mode-buttons');for(const [mode,label]of Object.entries(core.modes)){const b=button(label,()=>{this.change(s=>core.setMode(s,mode));this.handle='a';this.paint();});b.dataset.mode=mode;this.modeButtons.append(b);}this.modeRow.append(this.modeButtons);this.handles=el('div','reshoot-handles');this.handles.setAttribute('role','group');this.handles.setAttribute('aria-label','开始视角 / 结束视角');for(const [id,label]of[['a','开始视角'],['b','结束视角']]){const b=button(label,()=>{this.handle=id;this.paint();});b.dataset.handle=id;this.handles.append(b);}
    this.body=el('div','reshoot-body');const stageBox=el('div','reshoot-stage');this.stageMount=el('div','reshoot-stage-mount');const views=el('div','reshoot-view-tabs');for(const [id,label]of[['perspective','透视'],['front','正面']]){const b=button(label,()=>{this.stage?.setView(id);[...views.children].forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});b.setAttribute('aria-pressed',String(id==='front'));views.append(b);}this.hint=el('span','reshoot-stage-hint','拖动相机调整视角');stageBox.append(this.stageMount,views,this.hint);
    const fields=el('div','reshoot-fields');this.angleLabel=el('span','reshoot-label','视角');this.angles=el('div','reshoot-angles');for(const [id,label,azimuth,elevation]of core.presets){const b=button(label,()=>this.change(s=>core.setPoint(s,this.handle,{...this.point(),azimuth,elevation})));b.dataset.preset=id;this.angles.append(b);}this.scaleLabel=el('span','reshoot-label','景别');this.scales=el('div','reshoot-scales');for(const [label,distance]of core.scales){const b=button(label,()=>this.change(s=>core.setPoint(s,this.handle,{...this.point(),distance})));b.dataset.distance=distance;this.scales.append(b);}const prompt=el('div','reshoot-prompt');this.placeholder=el('span','reshoot-placeholder','补充镜头要求，例如：缓慢绕到人物侧后方（可选）');const mount=el('div');prompt.append(this.placeholder,mount);fields.append(this.angleLabel,this.angles,this.scaleLabel,this.scales,prompt);this.body.append(stageBox,fields);this.unchanged=el('div','reshoot-unchanged','该时间段保持原视频，不调整视角与景别');this.unchanged.setAttribute('role','note');
    const footer=el('footer'),submit=el('div','creation-submit-group'),cost=el('span','creation-cost');cost.innerHTML=window.CANVAS_MENU_ICONS.creationCost;cost.append(el('span','','—'));cost.title='由接入的生成服务返回用量';this.generate=button('生成视频',()=>this.submit(),true);this.generate.className='creation-generate';submit.append(cost,this.generate);footer.append(submit);this.status=el('p','reshoot-status','正在读取视频…');this.status.setAttribute('role','status');this.root.append(timeline,this.modeRow,this.handles,this.body,this.unchanged,footer,this.status);
    this.editor=window.TextEditor.createPrompt({element:mount,onUpdate:text=>{core.active(this.state).instruction=text;this.dirty=true;this.placeholder.hidden=!!text.trim();}});this.editor.view.dom.setAttribute('aria-label','补充镜头要求');
    try{this.stage=createStage(this.stageMount,node.image,(h,p)=>this.change(s=>core.setPoint(s,h,p)),h=>{this.handle=h;this.paint();});}catch(e){this.error('相机预览不可用：'+e.message);}
    const opts={signal:this.listeners.signal};document.addEventListener('canvas:render',()=>{const n=this.node();if(!n||mediaSource(n)!==this.source||JSON.stringify(n.clip||null)!==this.clip||!app.getState().selected.includes(this.id)){this.close();return;}this.place();},opts);window.addEventListener('resize',()=>{this.fit();this.place();},opts);this.fit(true);this.paint();this.root.focus({preventScroll:true});this.load();this.tick();
  }
  node(){return app.projectIdentity().id===this.projectId&&app.getState().nodes.includes(this.sourceNode)?this.sourceNode:null;}
  async readiness(request){const available=await window.GenerationAPI.availability({request,signal:this.listeners.signal});this.guard();if(available.configured!==true)return {ready:false,reason:available.reason||'视频重拍服务尚未配置',hint:''};const metadata=await window.GenerationAPI.configuration();this.guard();return metadata?reshootRequestState(metadata,request):{ready:true,reason:'',hint:''};}
  async refreshReadiness(){const ticket=this.readinessTicket=(this.readinessTicket||0)+1;this.ready=false;this.generate.disabled=true;try{this.guard();const request=core.request(this.node(),this.state,this.source),state=await this.readiness(request);if(ticket!==this.readinessTicket)return;this.ready=state.ready;this.status.hidden=false;this.status.textContent=[this.operationError,state.reason,state.hint||'实验性相机提示词；不保证运镜精确执行或“不变”段逐帧一致，原片保留。'].filter(Boolean).join(' ');this.generate.disabled=!this.ready||this.busy;}catch(e){if(this.alive&&ticket===this.readinessTicket)this.error(e.message);}}
  player(){return document.querySelector(`.node[data-id="${this.id}"] video.node-video`);}
  point(){const s=core.active(this.state);return this.handle==='b'&&s.pointB?s.pointB:s.pointA;}
  change(fn){try{const id=this.state.activeSegmentId;this.state={...this.state,segments:this.state.segments.map(s=>s.segmentId===id?fn(s):s)};if(!core.moving(core.active(this.state)))this.handle='a';this.dirty=true;this.paint();}catch(e){this.error(e.message);}}
  fit(animated=false){const n=this.node(),box=document.querySelector('#canvas').getBoundingClientRect();if(!n)return;cancelAnimationFrame(this.fitFrame);const to=core.fitViewport(n,box.width,box.height,this.initialView),from={...app.getState().view};if(!animated||matchMedia('(prefers-reduced-motion:reduce)').matches){app.setView(to);return;}const start=performance.now(),frame=now=>{if(!this.alive)return;const t=Math.min(1,(now-start)/280),p=1-(1-t)**3;app.setView({x:from.x+(to.x-from.x)*p,y:from.y+(to.y-from.y)*p,scale:from.scale+(to.scale-from.scale)*p});if(t<1)this.fitFrame=requestAnimationFrame(frame);};this.fitFrame=requestAnimationFrame(frame);}

  place(){const n=this.node();if(!n||!this.alive)return;const {view}=app.getState(),r=document.querySelector('#canvas').getBoundingClientRect(),w=Math.min(600,innerWidth-40);this.root.style.width=w+'px';this.root.style.left=Math.max(20,Math.min(innerWidth-w-20,r.left+(n.x+n.width/2)*view.scale+view.x-w/2))+'px';this.root.style.top=r.top+(n.y+n.height)*view.scale+view.y+8+'px';}
  paint(){const s=core.active(this.state),index=this.state.segments.indexOf(s),moving=core.moving(s);this.count.textContent=`分镜 ${index+1}/${this.state.segments.length}`;this.range.textContent=`${s.startTime.toFixed(1)}–${s.endTime.toFixed(1)}s`;this.shots.replaceChildren();this.state.segments.forEach((s,i)=>{const b=button(`${s.name||'分镜 '+(i+1)}, ${s.startTime.toFixed(1)}–${s.endTime.toFixed(1)}s`,()=>{});b.style.left=s.startTime/(this.duration||s.endTime)*100+'%';b.style.width=(s.endTime-s.startTime)/(this.duration||s.endTime)*100+'%';b.setAttribute('aria-pressed',String(s.segmentId===this.state.activeSegmentId));b.replaceChildren(el('strong','',s.name||'分镜 '+(i+1)),el('span','',`${s.startTime.toFixed(1)}s–${s.endTime.toFixed(1)}s`));b.onkeydown=e=>{if(e.key==='Enter'){this.state.activeSegmentId=s.segmentId;this.paint();this.rename();}};this.shots.append(b);});
    for(const b of this.modeButtons.children){b.setAttribute('aria-pressed',String(s.mode===b.dataset.mode));b.disabled=['cut','dynamic'].includes(b.dataset.mode)&&s.endTime-s.startTime<.5;b.title=b.disabled?'片段低于 0.5 秒仅支持不变或固定机位':b.textContent;}
    this.handles.hidden=!moving;for(const b of this.handles.children)b.setAttribute('aria-pressed',String(b.dataset.handle===this.handle));this.body.hidden=s.mode==='unchanged';this.unchanged.hidden=s.mode!=='unchanged';this.hint.hidden=moving;const label=this.handle==='a'?'开始视角':'结束视角';this.angleLabel.textContent=moving?label:'视角';this.scaleLabel.textContent=moving?label+' · 景别':'景别';const p=this.point();for(const [i,b]of [...this.angles.children].entries()){const preset=core.presets[i];b.setAttribute('aria-pressed',String(Math.abs(p.azimuth-preset[2])<.5&&Math.abs(p.elevation-preset[3])<.5));}const nearest=core.scales.reduce((a,b)=>Math.abs(b[1]-p.distance)<Math.abs(a[1]-p.distance)?b:a);for(const b of this.scales.children)b.setAttribute('aria-pressed',String(+b.dataset.distance===nearest[1]));this.stage?.update(s,this.handle);if(this.editor.getText()!==(s.instruction||''))this.editor.commands.setContent({type:'doc',content:[{type:'paragraph',content:s.instruction?[{type:'text',text:s.instruction}]:[]}]},{emitUpdate:false});this.placeholder.hidden=!!s.instruction?.trim();for(const e of [this.modeRow,this.handles,this.body,this.track])e.inert=!!this.busy;this.generate.disabled=!this.loaded||this.busy||!this.ready;if(this.loaded&&!this.busy)void this.refreshReadiness();this.play.disabled=!this.loaded;this.reset.disabled=!this.loaded||this.state.segments.length===1;this.syncTime();this.place();}
  async load(){try{if(!this.source)throw Error('来源视频尚不可用');this.guard();const src=await window.LocalAssets.url(this.source);this.guard();this.frames=await openVideoFrames(src,this.listeners.signal);if(!this.alive){this.frames.dispose();return;}this.guard();const n=this.node();this.offset=n.clip?.start||0;this.duration=Math.min(this.frames.duration,n.clip?.end??this.frames.duration)-this.offset;if(this.offset<0||this.duration<=0||n.clip?.end>this.frames.duration+.1)throw Error('视频范围无效');const draft=n.reshootDraft;this.state=draft?.source===this.source&&draft.clip===this.clip&&draft.duration===this.duration?structuredClone(draft.cameraState):core.initial(this.duration);this.loaded=true;this.status.hidden=true;this.ends.lastChild.textContent=this.duration.toFixed(1)+'s';this.track.setAttribute('aria-valuemax',this.duration);this.paint();for(let i=0;i<12;i++){const canvas=await this.frames.at(this.offset+this.duration*i/12,160);this.guard();const img=el('img');img.src=canvas.toDataURL('image/jpeg',.7);img.alt='';this.thumbs.append(img);}this.frames.dispose();this.frames=null;}catch(e){if(this.alive)this.error(e.message);}}
  syncTime(){this.playhead.style.left=this.time/(this.duration||1)*100+'%';this.track.setAttribute('aria-valuenow',this.time.toFixed(3));this.split.disabled=!this.loaded||!core.canSplit(this.state,this.time);}
  seek(value){if(!this.loaded)return;this.time=Math.max(0,Math.min(this.duration-.001,value));const v=this.player();if(v)v.currentTime=this.offset+this.time;const s=this.state.segments.find(s=>this.time>=s.startTime&&this.time<s.endTime);if(s&&s.segmentId!==this.state.activeSegmentId){this.state.activeSegmentId=s.segmentId;this.handle='a';this.paint();}this.syncTime();}
  togglePlay(){const v=this.player();if(!v)return this.error('播放器尚未就绪');if(v.paused){if(this.time>=this.duration-.05)this.seek(0);v.play().catch(e=>this.error(e.message));}else v.pause();}
  tick(){if(!this.alive)return;const v=this.player();if(v&&!v.paused){this.time=Math.max(0,v.currentTime-this.offset);if(this.time>=this.duration){v.pause();this.seek(0);}this.syncTime();}const label=v&&!v.paused?'暂停':'播放';if(this.play.getAttribute('aria-label')!==label){this.play.setAttribute('aria-label',label);this.play.dataset.tooltip=label;this.play.innerHTML=label==='播放'?icons['播放']:window.CANVAS_MENU_ICONS.playerPause;}this.raf=requestAnimationFrame(()=>this.tick());}
  rename(){const s=core.active(this.state),d=el('dialog','reshoot-rename'),label=el('label','','分镜名称'),input=el('input');input.value=s.name||'分镜 '+(this.state.segments.indexOf(s)+1);input.setAttribute('aria-label','分镜名称');input.maxLength=100;label.append(input);const done=()=>{this.change(v=>({...v,name:input.value.trim()}));d.close();};d.append(label,button('取消',()=>d.close()),button('完成',done));input.onkeydown=e=>{if(e.key==='Enter')done();};document.body.append(d);d.onclose=()=>d.remove();d.showModal();input.focus();input.select();this.nameDialog=d;}
  error(message){this.operationError=message;this.status.hidden=false;this.status.textContent=message;}
  async submit(){
    if(this.busy||!this.loaded)return;this.player()?.pause();this.saveDraft();this.busy=true;this.paint();const snapshot=structuredClone(this.state),id=this.id;
    try{this.operationError='';this.guard();const req=core.request(this.node(),snapshot,this.source),ready=await this.readiness(req);this.guard();if(!ready.ready)throw Error(ready.reason);
      await window.GenerationAPI.runInPlace(req,{type:'video',guard:this.guard,apply:async output=>{this.guard();return app.createConnected(id,[{...output,video:output.video||output.url,image:output.poster,title:output.title||'视频重拍',reshootPlan:snapshot}]);}},{signal:this.listeners.signal});if(this.alive)this.close();
    }catch(e){if(this.alive)this.error(e.message);else if(e.name!=='AbortError'&&e.code!=='cancelled')app.notify(e.message);}finally{this.busy=false;if(this.alive)this.paint();}
  }
  saveDraft(){const n=this.node();if(this.dirty&&this.loaded&&n&&mediaSource(n)===this.source&&JSON.stringify(n.clip||null)===this.clip){this.dirty=false;app.updateNode(this.id,{reshootDraft:{source:this.source,clip:this.clip,duration:this.duration,cameraState:structuredClone(this.state)}});}}
  close(){if(!this.alive)return;this.alive=false;cancelAnimationFrame(this.raf);cancelAnimationFrame(this.fitFrame);this.player()?.pause();this.listeners.abort();this.frames?.dispose();this.nameDialog?.close();this.stage?.dispose();this.editor.destroy();this.root.remove();document.body.classList.remove('video-reshoot-active');if(current===this)current=null;this.saveDraft();app.render();}
}
export function open(node){if(current?.id===node.id){current.close();return;}current?.close();window.NodeActions.close();window.NodeActions.closePop();app.select(node.id);current=new Reshoot(node);return current;}
