import {createDepthAgentHost} from '/src/features/agent-workflows/depth-agent.mjs';
import {inspectionMedia} from '/src/features/agent-vision/inspect.mjs';
import {createLocalClipResolver} from '/src/features/agent-workflows/local-clip-resolver.mjs';
const app=window.CanvasApp,api=window.GenerationAPI,f=window.VideoDepthFixture,panel=document.createElement('aside');panel.ariaLabel='视频深度隔离验收控制';panel.style.cssText='position:fixed;right:12px;top:65px;z-index:80;background:#171717;color:#eee;padding:12px;font:12px sans-serif;width:300px;max-height:45vh;overflow:auto';panel.onpointerdown=e=>e.stopPropagation();
const title=document.createElement('strong');title.textContent='生产视频节点 / Agent 深度链 · 本地灰度边界';const note=document.createElement('p');note.textContent=f.mode==='pipeline'?'真实gateway、全帧FFmpeg验证、归档、CanvasStore与LocalAssets；mock fal只返回仓库固定灰度视频，不证明深度质量。':'真实媒体与存储，配置隔离；POST始终403，无伪造结果。';const controls=document.createElement('div'),frames=document.createElement('div'),out=document.createElement('pre');out.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere';panel.append(title,note,controls,frames,out);document.body.append(panel);
const source=()=>app.getState().nodes.find(n=>n.id==='depth-source');
let failNodeSave=false;const originalSave=window.CanvasStore.save.bind(window.CanvasStore);window.CanvasStore.save=(snapshot,...args)=>{if(failNodeSave&&snapshot?.nodes?.some(n=>n.id!==source()?.id&&typeof n.video==='string'&&n.video.startsWith('/api/generation/media/')))return Promise.reject(Error('隔离QA深度节点结果保存失败；关闭失败开关后重试原任务应用'));return originalSave(snapshot,...args);};let prepared,jobId,turn=0,busy=false,failSave=false;
const resolveClip=createLocalClipResolver({getNode:id=>app.getState().nodes.find(n=>n.id===id),localMedia:window.LocalMedia});
const host=createDepthAgentHost({getNodes:()=>app.getState().nodes,getIdentity:id=>app.getState().nodes.find(n=>n.id===id),getMessages:()=>[],validateFormSubmission:window.AgentTools.validateFormSubmission,localAssets:window.LocalAssets,baseUrl:document.baseURI,resolveClip,getConfiguration:async({signal}={})=>{await api.availability({kind:'video.depth',signal});return api.configuration();},runInPlace:(...args)=>api.runInPlace(...args),createConnected:(...args)=>app.createConnected(...args),persist:async()=>{if(failSave){failSave=false;throw Error('隔离QA一次保存失败；请重试原任务应用');}await app.saveProject();}});
const begin=()=>{host.beginTurn('qa-turn-'+(++turn));prepared=null;f.turn=turn;write();};begin();
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.type='button';b.style.cssText='margin:3px;padding:6px';b.onclick=()=>Promise.resolve().then(fn).catch(e=>{f.lastError=e.message;write();});controls.append(b);return b;}
button('创建普通视频生成节点',()=>{const node=app.addConnectionNode(source().id,'right',{type:'video',title:'普通视频生成 · 深度入口验收',x:source().x+500,y:source().y,width:400,height:260,generation:{model:'Seedance 2.0',prompt:'这个旧提示词应在选择深度模型后清空',refs:[],count:1}});f.targetId=node.id;app.select(node.id,true);write();});
button('选择普通视频目标',()=>{if(!f.targetId)f.targetId=app.getState().nodes.find(n=>n.title==='普通视频生成 · 深度入口验收')?.id;if(!f.targetId)throw Error('请先创建普通节点');app.select(f.targetId,true);write();});
button('切换节点结果保存失败',()=>{failNodeSave=!failNodeSave;write();});
button('取消普通节点任务',()=>{const job=api.getJobs().filter(j=>j.request.kind==='video.depth'&&j.request.nodeId===f.targetId).at(-1);if(!job)throw Error('普通节点还没有任务');api.cancel(job.id);write();});
button('准备实际视频参考',async()=>{if(busy)return;busy=true;try{prepared=await host.prepare({stage:'convert',sourceId:'depth-source'});frames.replaceChildren();for(const pixel of inspectionMedia(prepared)){const image=document.createElement('img');image.src=pixel.imageUrl;image.alt='实际来源抽样帧';image.width=96;frames.append(image);}f.lastError=null;f.disclosure=prepared.disclosure;}finally{busy=false;write();}});
button('确认已查看并转换',async()=>{if(busy)return;busy=true;try{if(prepared)host.acceptInspections([{result:prepared}]);const result=await host.execute('depth_video_convert',{sourceId:'depth-source'},{authorize:async()=>{},onSubmitted:job=>{jobId=job.id;write();}});f.result=result;f.lastError=null;}finally{busy=false;write();}});
button('模拟下一次保存失败',()=>{failSave=true;f.lastError='下次真实结果创建后模拟一次保存失败';write();});
button('重试原任务应用',async()=>{if(!jobId)throw Error('尚无原任务');await api.retryApplication(jobId);f.lastError=null;write();});
button('新轮次（清空查看回执）',begin);button('取消原任务',async()=>{if(jobId)await api.cancel(jobId);write();});
button('配置服务',()=>api.configure());button('刷新验收记录',write);
if(f.mode!=='pipeline'){button('切换缺配置 / 原生配置',()=>{f.mode=f.mode==='unconfigured'?'native':'unconfigured';begin();});button('延迟下一次配置',()=>{f.armDelay=true;write();});button('释放配置',()=>{f.release();write();});}
button('修改来源身份',()=>{app.updateNode('depth-source',{video:'/qa/trim-scenes.mp4'});prepared=null;write();});
button('恢复并真实保存来源',async()=>{const response=await fetch('/src/features/video-generation/qa/media/2.mp4'),asset=await window.LocalAssets.put(await response.blob());app.updateNode('depth-source',{video:asset});await app.saveProject();begin();});
if(f.mode==='pipeline'){button('让下一原任务状态未知',async()=>{await fetch('/api/generation/fixture-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'unknown'})});write();});button('释放原供应商任务',async()=>{await fetch('/api/generation/fixture-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'release'})});write();});button('查询恢复原任务',async()=>{if(!jobId)throw Error('尚无原任务');await api.recover(jobId);write();});}
if(f.mode==='pipeline')button('查询后端归档审计',async()=>{f.serverAudit=await (await fetch('/api/generation/fixture-audit')).json();write();});
function actualDepthFooterAudit(){const panel=document.getElementById('node-editor'),prompt=panel?.querySelector('.prompt-editor');const controls=['model-trigger','quality-trigger','voice-trigger','count-trigger','generate-trigger'];const complete=controls.every(cls=>!!panel?.querySelector('.'+cls)),readOnly=prompt?.getAttribute('contenteditable')==='false',voiceLocked=panel?.querySelector('.voice-trigger')?.disabled===true;return {state:complete&&readOnly&&voiceLocked?'pass':'fail',complete,readOnly,voiceLocked,count:panel?.querySelector('.count-trigger')?.textContent,model:panel?.querySelector('.model-trigger')?.textContent,specification:panel?.querySelector('.quality-trigger')?.textContent};}
document.addEventListener('click',event=>{const choice=event.target.closest?.('.model-option');if(choice?.textContent.includes('Depth Anything Video'))queueMicrotask(()=>{const audit=actualDepthFooterAudit();audit.modelPopoverClosed=document.getElementById('parameter-popover')?.hidden===true;if(!audit.modelPopoverClosed)audit.state='fail';f.depthModelSelectionAudit=audit;write();});});
function auditSummary(_key,value){if(typeof value!=='string')return value;if(value.startsWith('data:'))return {kind:'inline-media',mime:value.slice(5,value.indexOf(';')>5?value.indexOf(';'):value.indexOf(',')),encodedCharacters:value.length};if(value.startsWith('blob:'))return {kind:'blob-media',urlCharacters:value.length};if(/^https?:/.test(value)&&value.length>240)return {kind:'url',urlCharacters:value.length,preview:value.slice(0,160)+'…'};return value;}
function write(){out.textContent=JSON.stringify({ready:f.ready,mode:f.mode,session:f.session,targetId:f.targetId,depthModelSelectionAudit:f.depthModelSelectionAudit,failNodeSave,dbNames:f.dbNames(),turn,busy,prepared:!!prepared,posts:f.posts,mediaPrepares:f.mediaPrepares,mediaReads:f.mediaReads,configReads:f.configReads,pendingConfigs:f.pendingConfigs,requests:f.requests,blockedAPI:f.blockedAPI,blockedExternal:f.blockedExternal,disclosure:f.disclosure,jobs:api.getJobs().filter(j=>j.request.kind==='video.depth').map(j=>({id:j.id,status:j.status,applied:j.applied,applicationError:j.applicationError,resultIds:j.resultIds})),nodes:app.getState().nodes.map(n=>({id:n.id,type:n.type,video:n.video,videoMetadata:n.videoMetadata,generation:n.generation,videoHistory:n.videoHistory,provenance:n.provenance})),serverAudit:f.serverAudit,result:f.result,lastError:f.lastError},auditSummary,2);}
api.subscribe(write);const timer=setInterval(write,300);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});write();
