'use strict';
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
let active=0;
function validate(input){if(!Array.isArray(input?.clips)||input.clips.length<1||input.clips.length>50)throw Error('请选择1–50个片段');let duration=0,bytes=0;const clips=input.clips.map(c=>{if(!Number.isFinite(c.start)||c.start<0||!Number.isFinite(c.duration)||c.duration<=0||c.start+c.duration>36000||typeof c.data!=='string'||!/^[A-Za-z0-9+/]+={0,2}$/.test(c.data))throw Error('片段格式或时间无效');duration+=c.duration;const data=Buffer.from(c.data,'base64');bytes+=data.length;return {start:c.start,duration:c.duration,data};});if(duration>600||bytes>80*1024*1024)throw Error('本地合并最多10分钟、80 MB');return clips;}
async function processPlaylist(req,res){if(active>=2)throw Error('本地合并队列已满');active++;let dir,child,aborted=false;const cancel=()=>{aborted=true;child?.kill('SIGTERM');};req.on('aborted',cancel);const onClose=()=>{if(!res.writableEnded)cancel();};res.on('close',onClose);
 const run=args=>new Promise((resolve,reject)=>{if(aborted)return reject(Error('合并已取消'));const processHandle=child=spawn(process.env.FFMPEG_PATH||'ffmpeg',['-hide_banner','-loglevel','error','-nostdin',...args],{stdio:['ignore','ignore','pipe']});let error='',timedOut=false;const timer=setTimeout(()=>{timedOut=true;processHandle.kill('SIGKILL');},120000);processHandle.stderr.on('data',b=>error=(error+b).slice(-1500));processHandle.once('error',e=>{clearTimeout(timer);reject(Error(e.code==='ENOENT'?'未安装 FFmpeg':e.message));});processHandle.once('close',code=>{clearTimeout(timer);code===0?resolve():reject(Error(aborted?'合并已取消':timedOut?'合并超时':'媒体处理失败：'+error.replaceAll(dir||'','[temporary]')));});});
 try{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>112*1024*1024)throw Error('合并请求超过112 MB');chunks.push(chunk);}const clips=validate(JSON.parse(Buffer.concat(chunks).toString('utf8')));dir=await fs.mkdtemp(path.join(os.tmpdir(),'canvas-playlist-'));
 for(let i=0;i<clips.length;i++){const c=clips[i],input=path.join(dir,'input-'+i),output=path.join(dir,`part-${i}.mp4`);await fs.writeFile(input,c.data);
 // Decode only uploaded bytes, never server-side URLs or arbitrary paths. Normalize each part to the same streams before concatenation.
 const common=['-protocol_whitelist','file,pipe','-format_whitelist','mov,matroska,webm','-ss',String(c.start),'-i',input,'-f','lavfi','-i','anullsrc=channel_layout=stereo:sample_rate=48000','-t',String(c.duration),'-map','0:v:0'];
 const end=['-vf','scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,fps=30,setsar=1','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-ar','48000','-ac','2','-af','apad','-movflags','+faststart','-y',output];
 // Optional audio mapping cannot select a fallback stream. Probe stream presence without trusting file metadata from the client.
 try{await run([...common,'-map','0:a:0',...end]);}catch(e){if(aborted||!e.message.includes('matches no streams'))throw e;await run([...common,'-map','1:a:0',...end]);}
 }
 const list=path.join(dir,'parts.txt'),output=path.join(dir,'merged.mp4');await fs.writeFile(list,clips.map((_,i)=>`file 'part-${i}.mp4'`).join('\n'));await run(['-protocol_whitelist','file,pipe','-f','concat','-safe','1','-i',list,'-c','copy','-movflags','+faststart','-y',output]);const data=await fs.readFile(output);res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':data.length,'Cache-Control':'no-store'});res.end(data);
 }finally{active--;req.off('aborted',cancel);res.off('close',onClose);if(dir){for(const f of await fs.readdir(dir))await fs.unlink(path.join(dir,f));await fs.rmdir(dir);}}
}
module.exports={processPlaylist,validate};
