const app=window.CanvasApp,f=window.PanoramaEditFixture,panel=document.createElement('aside');panel.setAttribute('aria-label','全景局部编辑隔离验收');panel.style.cssText='position:fixed;left:12px;top:65px;z-index:2000;background:#171717;color:white;padding:10px;font:12px sans-serif;max-width:300px';panel.onpointerdown=e=>e.stopPropagation();panel.innerHTML='<strong>全景局部编辑 · 正式 Studio</strong><p>公开合成立方体/球体，隔离数据库。正式 SDK、crop、mask、球面回投和归档；供应商返回是固定合成 PNG，无真实 Key、无模型调用。</p>';const output=document.createElement('pre');output.style.cssText='max-height:230px;overflow:auto';
const source=()=>app.getState().nodes.find(node=>node.id==='panorama-studio'),active=()=>window.StudioAPI.active;
const add=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>Promise.resolve().then(fn).catch(error=>{f.error=error.message;write();});panel.append(b);};
const save=window.CanvasStore.save.bind(window.CanvasStore);window.CanvasStore.save=(state,id,options)=>{if(options?.beforeCommit){f.saveAttempts++;if(f.failSave){f.failSave=false;return Promise.reject(Error('隔离夹具：模拟一次全景事务保存失败'));}}return save(state,id,options);};
add('打开正式全景编辑',async()=>{await window.StudioAPI.execute('open',{nodeId:source().id});await window.StudioAPI.execute('panorama',{action:'open'});});
add('添加中央框选',()=>window.StudioAPI.execute('panorama',{action:'region',rect:{x:.38,y:.33,width:.22,height:.26}}));
add('缺 Key / 合成已配置',async()=>{f.configured=!f.configured;await active()?.refreshPanoramaReadiness();write();});
add('延迟下次配置',()=>{f.armDelay=true;});add('释放迟到配置',()=>f.release());
add('改变片场光照',()=>{const s=active();s.data.environment.intensity=s.data.environment.intensity===1?1.25:1;s.environment();s.persist();});
add('关闭编辑器',()=>active()?.closePanoramaEditor());add('下一次保存失败',()=>{f.failSave=true;});
add('重试原结果保存',async()=>{const job=window.GenerationAPI.getJobs().findLast(job=>job.request.kind==='panorama.edit'&&job.applicationError);if(!job)throw Error('没有待重试的原结果');await window.GenerationAPI.retryApplication(job.id);});
add('查看数据库回读',async()=>{f.saved=await window.CanvasStore.load(app.projectIdentity().id);write();});
panel.append(output);document.body.append(panel);
function write(){const e=active()?.panoramaEditor;output.textContent=JSON.stringify({configured:f.configured,posts:f.posts,serverAudit:f.serverAudit,pendingConfigurations:f.pendingConfigurations,saveAttempts:f.saveAttempts,pendingSaves:e?.pendingSaves?.size,blockedExternal:f.blockedExternal,blockedAPI:f.blockedAPI,databases:f.databases(),jobs:window.GenerationAPI.getJobs().map(j=>({id:j.id,status:j.status,applied:j.applied,applicationError:j.applicationError,kind:j.request.kind})),requests:f.requests,nodes:app.getState().nodes.length,patches:source()?.studio?.panoramaSessions?.map(a=>({id:a.id,patches:a.patches.length})),savedPatches:f.saved?.nodes?.find(n=>n.id==='panorama-studio')?.studio?.panoramaSessions?.map(a=>({id:a.id,patches:a.patches.length})),open:!!e,error:f.error},null,2);}
window.GenerationAPI.subscribe(write);setInterval(write,300);setInterval(async()=>{try{f.serverAudit=await (await fetch('/api/generation/fixture-audit')).json();}catch(error){f.error=error.message;}},1000);write();
