import {open} from '../../../../image-relight-ui.mjs';
const app=window.CanvasApp,f=window.RelightFixture,panel=document.createElement('aside');panel.setAttribute('aria-label','打光隔离验收');panel.style.cssText='position:fixed;left:78px;top:65px;z-index:80;background:#171717;color:white;padding:10px;font:12px sans-serif;max-width:310px';panel.onpointerdown=e=>e.stopPropagation();panel.innerHTML='<strong>打光隔离验收 · 正式面板/Three</strong><p>公开合成素材；内存偏好、独立数据库；供应商 API 合成边界，未调用模型、无真实 Key。pipeline 模式走正式 SDK、网关和归档；结果只是陶瓶测试图。</p>';const output=document.createElement('pre');output.style.maxHeight='230px';output.style.overflow='auto';
const source=()=>app.getState().nodes.find(node=>node.id==='relight-source');
const add=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>Promise.resolve().then(fn).catch(error=>{f.error=error.message;write();});panel.append(b);};
const save=app.saveProject.bind(app);app.saveProject=async()=>{f.saveAttempts++;if(f.failSave){f.failSave=false;throw Error('隔离夹具：模拟一次保存失败');}return save();};
add('打开正式打光',()=>open(source()));add('缺 Key / 合成已配置',async()=>{f.configured=!f.configured;await window.ImageRelight.active?.refreshReadiness();write();});add('延迟下次配置',()=>{f.armDelay=true;});add('释放迟到配置',()=>f.release());add('切换来源 fullImage',()=>{const n=source();app.updateNode(n.id,{fullImage:n.fullImage===f.sourceAsset?f.otherAsset:f.sourceAsset});});add('下一次保存失败',()=>{f.failSave=true;});add('重试原结果保存',async()=>{const job=window.GenerationAPI.getJobs().findLast(job=>job.request.kind==='image.relight'&&job.applicationError);if(!job)throw Error('没有待重试的原结果');await window.GenerationAPI.retryApplication(job.id);});
panel.append(output);document.body.append(panel);
function write(){output.textContent=JSON.stringify({pipeline:f.pipeline,serverAudit:f.serverAudit,agentReceipts:window.RelightAgentFixture?.generationReceipts,configured:f.configured,posts:f.posts,pendingConfigurations:f.pendingConfigurations,saveAttempts:f.saveAttempts,blockedExternal:f.blockedExternal,blockedAPI:f.blockedAPI,databases:f.databases(),jobs:window.GenerationAPI.getJobs().map(j=>({id:j.id,status:j.status,applied:j.applied,applicationError:j.applicationError,kind:j.request.kind})),requests:f.requests,nodes:app.getState().nodes.length,panelAlive:window.ImageRelight.active?.alive??false,error:f.error},null,2);}
const blob=await (await fetch('/src/features/image-relight/qa/source.png')).blob();const existing=source();if(existing?.fullImage?.startsWith('asset:')){f.sourceAsset=existing.fullImage;f.otherAsset=await window.LocalAssets.put(blob);}else{f.sourceAsset=await window.LocalAssets.put(blob);f.otherAsset=await window.LocalAssets.put(blob);app.updateNode(existing.id,{image:f.sourceAsset,fullImage:f.sourceAsset});await save();}f.seeded=true;window.GenerationAPI.subscribe(write);setInterval(write,300);write();

if(f.pipeline)setInterval(async()=>{try{f.serverAudit=await (await fetch('/api/generation/fixture-audit')).json();write();}catch(error){f.error=error.message;}},1000);
