'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createOpenAIRelightProvider}=require('../../../../server/generation-openai-relight.cjs');
const {encodeRGBA}=require('../../../../server/generation-png-alpha.cjs');
const config=()=>createOpenAIRelightProvider({apiKey:'synthetic-relight-frontend-contract',modelMap:{'image.relight':{kind:'image.relight',model:'gpt-image-2',semantics:'parameter-prompt-edit',quality:'high',outputSize:'auto'}},fetchImpl:()=>assert.fail('No real network')}).metadata;
const request=()=>({kind:'image.relight',prompt:'',nodeId:'source',inputs:[{type:'image',role:'source_image',url:'asset:full',nodeId:'source'}],parameters:{angle:{preset:'front_0'},brightnessPercent:50,temperatureK:5600,rimEnabled:true,rimPreset:'back_0'}});
const state=()=>{const node={id:'source',type:'image',image:'asset:thumbnail',fullImage:'asset:full'},nodes=[node];let project='a',selected=['source'],creates=0;const app={projectIdentity:()=>({id:project}),getState:()=>({nodes,selected}),createConnected:(_id,outputs)=>{creates++;const n={...outputs[0],id:'result'};nodes.push(n);selected=['result'];return [n];},saveProject:async()=>{}};return {app,node,nodes,setProject:value=>project=value,setSelection:value=>selected=value,get creates(){return creates;}};};

test('published native kind-only profile is ready and discloses independent parameter editing',async()=>{const {relightRequestState}=await import('../native-profile.mjs');for(const r of [{kind:'image.relight'},request()]){const result=relightRequestState(config(),r);assert.equal(result.ready,true);assert.match(result.hint,/独立打光.*不保证.*物理.*尺寸/);}for(const mutate of [c=>c.configured=false,c=>delete c.capabilities.relight,c=>c.capabilities.relight.temperatureK.pop(),c=>c.capabilities.relight.semantics='physical']){const c=config();mutate(c);assert.equal(relightRequestState(c,request()).ready,false);}});
test('native metadata requires the exact compressed PNG rejection set independent of order',async()=>{
 const {relightRequestState}=await import('../native-profile.mjs'),reordered=config();
 reordered.capabilities.relight.rejectedPNGMetadataChunks.reverse();
 assert.equal(relightRequestState(reordered,request()).ready,true);
 for(const chunks of [undefined,[],['zTXt','iTXt'],['zTXt','iTXt','iCCP','eXIf'],['zTXt','iTXt','iTXt'],['zTXt','iTXt','ICC'],'zTXt/iTXt/iCCP']){
  const metadata=config();metadata.capabilities.relight.rejectedPNGMetadataChunks=chunks;
  for(const candidate of [{kind:'image.relight'},request()]){const state=relightRequestState(metadata,candidate);assert.equal(state.ready,false);assert.match(state.reason,/PNG.*元数据/);}
 }
});
test('explicit request validates every control, forbids free angles/hidden model/rim adjustment',async()=>{const {assertRelightRequest}=await import('../native-profile.mjs'),core=await import('../../../../image-relight-core.mjs');for(const angle of core.anglePresets)for(const brightnessPercent of core.brightnessStops)for(const temperatureK of core.temperatureStops){const r=request();Object.assign(r.parameters,{angle:{preset:angle.key},brightnessPercent,temperatureK,rimEnabled:core.rimAllowed(angle.azimuthDeg,angle.elevationDeg)});assert.equal(assertRelightRequest(r),r);}for(const change of [r=>r.parameters.rimPreset='other',r=>r.parameters.angle={azimuthDeg:20,elevationDeg:20},r=>r.parameters.brightnessPercent=70,r=>r.parameters.temperatureK=5500,r=>r.parameters.model='hidden',r=>r.prompt='extra',r=>r.parameters.angle.preset='back_180']){const r=request();change(r);assert.throws(()=>assertRelightRequest(r));}});
test('source guard rejects project/same-id object/full image/thumbnail/region/selection mutations',async()=>{const {createRelightSourceGuard,assertRelightSourceScope}=await import('../source-guard.mjs');for(const mutate of [s=>s.setProject('b'),s=>s.nodes[0]={...s.node},s=>s.node.fullImage='other',s=>s.node.image='other',s=>s.node.crop={x:1},s=>s.node.imageSelection={x:1},s=>s.node.metadata={revision:2},s=>s.setSelection([])]){const s=state(),guard=createRelightSourceGuard(s.app,s.node,{requireSelection:true});guard();mutate(s);assert.throws(guard,/变化/);}for(const key of ['crop','imageCrop','clip','trim','selection','imageSelection','region'])assert.throws(()=>assertRelightSourceScope({[key]:{}}),/完整图片/);});
test('unconfigured and cancelled preflight cannot touch source bytes; preparation retains original parameters',async()=>{const {prepareRelightMedia}=await import('../media.mjs');await assert.rejects(()=>prepareRelightMedia(request(),{nativeConfiguration:{...config(),configured:false},resolveMedia:()=>assert.fail('No read'),transport:()=>assert.fail('No transport')}));let changed=false,reads=0;const r=request(),prepared=await prepareRelightMedia(r,{nativeConfiguration:config(),resolveMedia:async()=>{reads++;return {url:'data:image/png;base64,AAAA'};},transport:async r=>r,normalizePng:async input=>({...input,width:512,height:320})});assert.equal(reads,1);assert.deepEqual(prepared.parameters,r.parameters);assert.equal(prepared.inputs[0].role,'source_image');assert.deepEqual([prepared.inputs[0].width,prepared.inputs[0].height],[512,320]);for(const cancelled of [true,false]){const controller=new AbortController();changed=false;await assert.rejects(()=>prepareRelightMedia(r,{signal:controller.signal,nativeConfiguration:config(),validateSources:()=>{if(changed)throw Error('source changed');},resolveMedia:async()=>{if(cancelled)controller.abort(Error('cancelled'));else changed=true;return {url:'data:image/png;base64,AAAA'};},transport:()=>assert.fail('No dispatch')}),/cancelled|source changed/);}});
test('real PNG decode preserves supported bytes; alternate PNG/JPEG/WebP normalize at original dimensions',async()=>{const {normalizeRelightPng}=await import('../media.mjs'),png=encodeRGBA(13,9,Buffer.alloc(13*9*4,255));for(const type of ['image/png','image/jpeg','image/webp','indexed-png']){let drawn=0,closed=0;const indexed=Buffer.from(png);indexed[25]=3;const blob=new Blob([type==='image/png'?png:type==='indexed-png'?indexed:'synthetic-format-for-injected-decoder'],{type:type==='indexed-png'?'image/png':type}),input={type:'image',role:'source_image',url:'data:'+blob.type+';base64,ORIGINAL',width:13,height:9};const output=await normalizeRelightPng(input,{fetchImpl:async()=>({ok:true,blob:async()=>blob}),decode:async()=>({width:13,height:9,close:()=>closed++}),canvasFactory:()=>({getContext:()=>({drawImage:(_b,x,y)=>{drawn++;assert.deepEqual([x,y],[0,0]);}}),toBlob:(cb,type)=>cb(new Blob(['normalized'],{type}))}),serialize:async()=> 'data:image/png;base64,NORMALIZED'});assert.equal(closed,1);assert.equal(drawn,type==='image/png'?0:1);assert.equal(output.url,type==='image/png'?input.url:'data:image/png;base64,NORMALIZED');assert.deepEqual([output.width,output.height],[13,9]);}});
test('cancellation immediately rejects pending decode and disposes its late bitmap',async()=>{const {normalizeRelightPng}=await import('../media.mjs');const controller=new AbortController();let release,started,closed=0;const decoding=new Promise(resolve=>release=resolve),waiting=new Promise(resolve=>started=resolve);const pending=normalizeRelightPng({url:'data:image/png;base64,AAAA'},{signal:controller.signal,fetchImpl:async()=>({ok:true,blob:async()=>new Blob([encodeRGBA(1,1,Buffer.alloc(4,255))],{type:'image/png'})}),decode:()=>{started();return decoding;},canvasFactory:()=>assert.fail('No canvas')});await waiting;controller.abort(Error('closed'));await assert.rejects(pending,/closed/);release({width:512,height:320,close:()=>closed++});await new Promise(resolve=>setImmediate(resolve));assert.equal(closed,1);});
test('failed-save retry waits for persistence and reuses exactly one original result',async()=>{const {createRelightResultApplication}=await import('../result-application.mjs'),{createApplicationRunner}=await import('../../generation-results/application.mjs');const s=state();let saves=0,release;const waiting=new Promise(resolve=>release=resolve);s.app.saveProject=async()=>{if(++saves===1)throw Error('disk failed');await waiting;};const target=createRelightResultApplication({app:s.app,node:s.node,parameters:request().parameters}),job={id:'job',status:'succeeded',outputs:[{type:'image',url:'asset:actual'}]},runner=createApplicationRunner({getJob:()=>job,apply:()=>target.apply(job.outputs[0])});await runner.run('job');assert.equal(job.applied,false);assert.equal(s.creates,1);assert.match(job.applicationError,/disk failed/);const retry=runner.run('job');await new Promise(resolve=>setImmediate(resolve));assert.equal(job.applied,false);assert.equal(s.creates,1);release();await retry;assert.equal(job.applied,true);assert.equal(saves,2);assert.equal(s.nodes[1].fullImage,'asset:actual');s.nodes[1]={...s.nodes[1]};await assert.rejects(()=>target.apply(job.outputs[0]),/结果节点已变化/);assert.equal(s.creates,1);});
test('configuration snapshots reject a late provider/configuration change',async()=>{const {createRelightConfigurationGuard}=await import('../source-guard.mjs');let metadata=config();const guard=createRelightConfigurationGuard({configurationSnapshot:()=>metadata},metadata,request());guard();metadata={...metadata,configurationId:'rotated'};assert.throws(guard,/配置已变化/);});

test('PNG transparency/compressed metadata normalizes at full dimensions, animation rejects, and source id is bound',async()=>{
 const {normalizeRelightPng}=await import('../media.mjs'),{createRelightSourceGuard}=await import('../source-guard.mjs'),png=encodeRGBA(2,2,Buffer.alloc(16,255));
 const chunk=type=>Buffer.concat([Buffer.alloc(4),Buffer.from(type),Buffer.alloc(4)]),withChunk=type=>Buffer.concat([png.subarray(0,png.length-12),chunk(type),png.subarray(png.length-12)]);
 let decoded=0,drawn=0;const options={fetchImpl:async()=>({ok:true,blob:async()=>new Blob([withChunk('tRNS')],{type:'image/png'})}),decode:async()=>{decoded++;return {width:2,height:2,close(){}};},canvasFactory:()=>({getContext:()=>({drawImage:()=>drawn++}),toBlob:cb=>cb(new Blob([png],{type:'image/png'}))}),serialize:async()=> 'data:image/png;base64,RGBA'};
 for(const type of ['tRNS','zTXt','iTXt','iCCP']){
  const input={url:'data:image/png;base64,ORIGINAL',width:2,height:2},normalized=await normalizeRelightPng(input,{...options,fetchImpl:async()=>({ok:true,blob:async()=>new Blob([withChunk(type)],{type:'image/png'})})});
  assert.deepEqual([normalized.width,normalized.height],[input.width,input.height]);assert.equal(normalized.url,'data:image/png;base64,RGBA');
 }
 assert.equal(decoded,4);assert.equal(drawn,4);
 for(const kind of ['acTL','fcTL','fdAT'])await assert.rejects(()=>normalizeRelightPng({url:'data:image/png;base64,ANIMATED'},{...options,fetchImpl:async()=>({ok:true,blob:async()=>new Blob([withChunk(kind)],{type:'image/png'})}),decode:()=>assert.fail('Animation must reject before decode')}),/动画 PNG/);
 const s=state(),guard=createRelightSourceGuard(s.app,s.node);s.node.id='other';assert.throws(guard,/变化/);
});
