import {captureResultSnapshot,assertResultSnapshot} from '../generation-results/plan.mjs';
import {isGenerationMediaRef} from '../generation-results/media-ref.mjs';
import {renderLayerComposerPreview} from './layer-composer-runtime.mjs';
import {previsUri,previsLimits as limits,previsNodeId,previsCells,preparePrevis,validatePrevisState,validatePrevisReply,applyPrevisPayload,previsCanonical,previsHash,previsStateFromPayload} from './previs.mjs';
const clone=v=>structuredClone(v),failure=(code,message)=>Object.assign(Error(message),{code}),fail=(code,message)=>{throw failure(code,message);};
const abort=signal=>{if(signal?.aborted)throw signal.reason||failure('cancelled','预演操作已取消');};
const local=v=>isGenerationMediaRef(v)||typeof v==='string'&&/^(?:asset:[A-Za-z0-9_-]+$|blob:|data:image\/(?:png|jpeg|webp);base64,)/.test(v);
const fields=(v,keys)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))fail('invalid_previs','预演参数字段无效');};
async function wait(promise,signal,disposeLate){abort(signal);if(!signal)return promise;return new Promise((resolve,reject)=>{const stop=()=>reject(signal.reason);signal.addEventListener('abort',stop,{once:true});Promise.resolve(promise).then(v=>{signal.removeEventListener('abort',stop);try{if(signal.aborted){try{disposeLate?.(v);}catch{}abort(signal);}resolve(v);}catch(error){reject(error);}},e=>{signal.removeEventListener('abort',stop);reject(e);});});}
export async function renderPrevisCell(blob,index,{signal}={}){
 const url=URL.createObjectURL(blob),image=new Image();try{await wait(new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(failure('decode_failed','图板原像素无法解码'));image.src=url;}),signal);const rect=previsCells()[index],canvas=document.createElement('canvas'),scale=Math.min(1,768/Math.max(image.naturalWidth*rect.w,image.naturalHeight*rect.h));canvas.width=Math.max(1,Math.round(image.naturalWidth*rect.w*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*rect.h*scale));const context=canvas.getContext('2d');if(!context)fail('canvas_unavailable','真实镜头裁片不可用');context.drawImage(image,image.naturalWidth*rect.x,image.naturalHeight*rect.y,image.naturalWidth*rect.w,image.naturalHeight*rect.h,0,0,canvas.width,canvas.height);const data_uri=canvas.toDataURL('image/png');if(data_uri.length>2*1024*1024)fail('input_limit','真实镜头裁片超过生成输入预算');return data_uri;}finally{image.onload=image.onerror=null;image.src='';URL.revokeObjectURL(url);}
}
export function createPrevisRuntime({app,localAssets,store,generationAPI,getProjectId,persistConversation,fetchImpl=(...args)=>fetch(...args),getOrigin=()=>globalThis.location?.origin,renderPreview=renderLayerComposerPreview,renderCell=renderPrevisCell}={}){
 for(const [name,fn]of Object.entries({'app.getState':app?.getState,'app.createConnected':app?.createConnected,'localAssets.url':localAssets?.url,'store.save':store?.save,getProjectId,persistConversation}))if(typeof fn!=='function')throw TypeError(name+' adapter is required');
 const preparations=new WeakMap(),operations=new Map(),graph=()=>app.getState();
 function source(ref){const node=graph().nodes.find(n=>n.id===previsNodeId(ref));if(node?.type!=='image'||!local(node.fullImage||node.image))fail('nonlocal_source','预演图板须来自当前真实本地图片节点');return node;}
 async function read(media,{signal,check=()=>{}}={}){
  const timed=new AbortController(),timer=setTimeout(()=>timed.abort(failure('media_timeout','预演媒体读取超时')),limits.timeoutMs);signal=signal?AbortSignal.any([signal,timed.signal]):timed.signal;let reader,body;
  try{check();abort(signal);if(!local(media))fail('nonlocal_source','预演只允许本地素材或精确生成媒体引用');const generated=isGenerationMediaRef(media);let url;if(generated){const origin=new URL(getOrigin());if(!['http:','https:'].includes(origin.protocol)||origin.href!==origin.origin+'/'||origin.username||origin.password)fail('nonlocal_source','预演需要精确同源媒体');url=new URL(media,origin.origin).href;}else url=media.startsWith('asset:')?await wait(localAssets.url(media),signal):media;
   if(typeof url!=='string'||!generated&&!/^(?:blob:|data:image\/(?:png|jpeg|webp);base64,)/.test(url))fail('nonlocal_source','本地预演素材不得解析为HTTP地址');check();if(url.startsWith('data:')&&url.length>Math.ceil(limits.sourceBytes*4/3)+64)fail('media_limit','图板源像素超限');const response=await wait(fetchImpl(url,{signal,redirect:'error',...(generated?{mode:'same-origin',credentials:'same-origin'}:{})}),signal,response=>{Promise.resolve(response?.body?.cancel?.()).catch(()=>{});});body=response?.body;reader=body?.getReader?.();check();abort(signal);if(generated&&(response.redirected||response.url!==url||['opaque','opaqueredirect'].includes(response.type)))fail('nonlocal_source','图板媒体响应并非精确同源');if(!response?.ok||!reader)fail('media_unavailable','图板须可进行有界本地读取');const mime=response.headers?.get('content-type')?.split(';')[0];if(!['image/png','image/jpeg','image/webp'].includes(mime))fail('media_type','图板格式须为PNG/JPEG/WebP');if(Number(response.headers?.get('content-length'))>limits.sourceBytes)fail('media_limit','图板源像素超限');const chunks=[];let total=0;for(;;){const item=await wait(reader.read(),signal);check();abort(signal);if(item.done)break;total+=item.value.byteLength;if(total>limits.sourceBytes)fail('media_limit','图板实际字节超限');chunks.push(item.value);}if(!total)fail('media_unavailable','图板没有真实像素');const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}const sha256=await wait(previsHash(bytes),signal);check();return {blob:new Blob([bytes],{type:mime}),sha256,bytes:total};
  }catch(error){try{Promise.resolve(reader?reader.cancel():body?.cancel?.()).catch(()=>{});}catch{}throw error;}finally{clearTimeout(timer);try{reader?.releaseLock();}catch{}}
 }
 async function prepareAppArgs(args,{isCurrent=()=>true,signal}={}){
  if(args.resource_uri!==previsUri)return args;if(args.data?.textures||args.data?.sheets?.some(s=>s.texture_id||s.image_url||s.cells||s.shots?.some(s=>s.image||s.variant)))fail('invalid_source','预览、纹理和媒体来源由宿主建立');const response=preparePrevis(args.data,args.title),projectId=getProjectId(),bindings=[];
  for(const sheet of response.sheets){if(!sheet.sheet_node_ref)continue;const node=source(sheet.sheet_node_ref);bindings.push({sheet_id:sheet.sheet_id,node_ref:sheet.sheet_node_ref,media:node.fullImage||node.image,snapshot:captureResultSnapshot(graph().nodes,graph().edges,node.id)});}
  const check=()=>{abort(signal);if(!isCurrent()||getProjectId()!==projectId)fail('stale_previs','预演画布或会话已切换');for(const b of bindings)assertResultSnapshot(b.snapshot,graph().nodes,graph().edges);};check();response.textures=[];let bytes=0,previewBytes=0;
  for(const binding of bindings){const actual=await read(binding.media,{signal,check});bytes+=actual.bytes;if(bytes>limits.totalBytes)fail('media_limit','全部图板来源超过64MiB');binding.source_sha256=actual.sha256;const preview=await wait(renderPreview(actual.blob,{signal}),signal);check();previewBytes+=preview.preview.data_uri.length;if(previewBytes>limits.previewBytes)fail('preview_limit','预演预览总量超限');const texture_id='sheet-'+binding.sheet_id,texture={texture_id,sheet_node_ref:binding.node_ref,image_url:preview.preview.data_uri,cells:previsCells()};response.textures.push(texture);const sheet=response.sheets.find(s=>s.sheet_id===binding.sheet_id);sheet.texture_id=texture_id;sheet.cells=previsCells();for(const shot of sheet.shots)shot.image={kind:'cell',texture_id,sheet_node_ref:binding.node_ref,cell:shot.cell};}
  check();const prepared={...clone(args),data:response};preparations.set(prepared,{projectId,sources:bindings,responseFingerprint:previsCanonical(response)});return prepared;
 }
 function bindPreparedResult(result,args){if(args.resource_uri!==previsUri)return result;const binding=preparations.get(args);if(!binding||binding.projectId!==getProjectId()||previsCanonical(result.response)!==binding.responseFingerprint)fail('invalid_source','预演缺少原始来源绑定');for(const b of binding.sources)assertResultSnapshot(b.snapshot,graph().nodes,graph().edges);return {...result,previsSourceContext:clone(binding)};}
 function capture(data,{trace,chat,isCurrent}={}){
  const binding=trace?.result?.previsSourceContext;if(typeof isCurrent!=='function'||!trace?.id||!chat?.id||!binding||binding.projectId!==getProjectId()||previsCanonical(data)!==binding.responseFingerprint)fail('invalid_source','预演缺少真实会话来源绑定');const scope={projectId:getProjectId(),chatId:chat.id,traceId:trace.id},lifetime=new AbortController();
  const guard=(signal,{detached=false}={})=>{abort(signal);if(!detached)abort(lifetime.signal);if(!isCurrent()||getProjectId()!==scope.projectId||trace.result.response!==data||previsCanonical(data)!==binding.responseFingerprint)fail('stale_previs','预演卡片已切换或被替换');for(const b of binding.sources)assertResultSnapshot(b.snapshot,graph().nodes,graph().edges);return true;};
  async function validateSourcesCurrent({signal,detached=false}={}){if(!detached)signal=signal?AbortSignal.any([signal,lifetime.signal]):lifetime.signal;const sourceGuard=()=>guard(signal,{detached});sourceGuard();let total=0;for(const b of binding.sources){const actual=await read(source(b.node_ref).fullImage||source(b.node_ref).image,{signal,check:sourceGuard});total+=actual.bytes;if(total>limits.totalBytes||actual.sha256!==b.source_sha256)fail('source_changed','图板真实像素或总预算已变化');}if(trace.appState)await validateSelections(trace.appState,{signal,detached});sourceGuard();return true;}
  async function validateSelections(state,{signal,detached=false}={}){for(const [code,e]of Object.entries(state.edits)){if(!e.image)continue;const original=data.sheets.flatMap(s=>s.shots).find(s=>s.shot_code===code)?.image;if(previsCanonical(e.image)===previsCanonical(original))continue;const ledger=(trace.previsJobs||[]).filter(r=>r.kind==='variants'&&r.shot_code===code&&r.target_ref===e.image.sheet_node_ref&&r.plan_id===state.variants[code]?.plan_id).at(-1);if(!ledger||e.image.kind!=='cell')fail('invalid_selection','预演选图必须来自该镜头实际生成图板');const status=await inspect(ledger,{recover:!!ledger.receipt,signal,detached});if(status.status!=='completed'||!ledger.receipt)fail('invalid_selection','变体图板尚未真实保存或原任务未核实');}}
  async function validateReply(details,savedState=trace.appState){guard();const state=savedState,stateKey=previsCanonical(state);if(savedState!==trace.appState)fail('state_changed','预演必须使用实际已保存状态');const payload=validatePrevisReply(details,data,state);await validateSourcesCurrent();await validateSelections(state);guard();if(trace.appState!==state||previsCanonical(state)!==stateKey)fail('state_changed','确认核验期间预演编辑变化');const manifest_revision=await previsHash({manifest:data,sources:binding.sources,payload});guard();if(details.expected_manifest_revision!==undefined&&details.expected_manifest_revision!==manifest_revision)fail('manifest_conflict','预演确认针对旧镜头版本');return {manifest_revision};}
  async function preflightReply(details){const state=previsStateFromPayload(data,details?.payload),payload=validatePrevisReply(details,data,state);await validateSourcesCurrent();await validateSelections(state);guard();const manifest_revision=await previsHash({manifest:data,sources:binding.sources,payload});if(details.expected_manifest_revision!==undefined&&details.expected_manifest_revision!==manifest_revision)fail('manifest_conflict','预演确认针对旧镜头版本');return {manifest_revision};}
  async function hydrateSelectedVariants(manifest,{signal}={}){const refs=new Set(manifest.sheets.flatMap(s=>s.shots.map(s=>s.image?.sheet_node_ref)).filter(Boolean));manifest.textures=manifest.textures||[];for(const record of new Map((trace.previsJobs||[]).filter(r=>r.kind==='variants'&&refs.has(r.target_ref)).map(r=>[r.target_ref,r])).values()){const status=await inspect(record,{recover:false,signal});if(status.status!=='completed')fail('invalid_selection','已选图板缺少实际保存结果');const texture_id='variant-'+record.target_ref;manifest.textures=manifest.textures.filter(t=>t.texture_id!==texture_id);manifest.textures.push({texture_id,sheet_node_ref:record.target_ref,image_url:status.image_url,cells:previsCells()});for(const sheet of manifest.sheets)for(const shot of sheet.shots)if(shot.image?.sheet_node_ref===record.target_ref)shot.image.texture_id=texture_id;}return manifest;}
  async function resolveReply(details,savedState=trace.appState){const stateKey=previsCanonical(savedState);const {manifest_revision}=await validateReply(details,savedState),payload=validatePrevisReply(details,data,savedState),result={manifest_revision,reply_id:details.reply_id,manifest:applyPrevisPayload(data,payload),sources:binding.sources.map(({node_ref,source_sha256})=>({node_ref,source_sha256}))};await hydrateSelectedVariants(result.manifest);await validateSourcesCurrent();await validateSelections(savedState);guard();if(trace.appState!==savedState||previsCanonical(savedState)!==stateKey)fail('state_changed','预演确认图板核验期间编辑变化');const modelResult={...result,manifest:{...result.manifest,textures:(result.manifest.textures||[]).map(({image_url,...texture})=>texture),sheets:result.manifest.sheets.map(({image_url,...sheet})=>sheet)}};return {kind:'confirmed',text:'已确认并保存镜头预演编辑。请依据真实顺序、时长、运镜及已选变体继续制作；缺图板只可用正常确认后的 previs_generate_sheet 工具，不得声称已经生成。\n'+JSON.stringify(modelResult),metadata:{handoffId:'previs_'+details.reply_id,contextNodeIds:binding.sources.map(b=>previsNodeId(b.node_ref))},result};}
  async function persistChange(key,next,check=guard){const old=trace[key];trace[key]=next;let committed=false;try{if(await persistConversation()===false)fail('conversation_save_failed','预演会话保存失败');committed=true;check();return next;}catch(error){if(trace[key]===next){if(old===undefined)delete trace[key];else trace[key]=old;}if(committed)try{if(await persistConversation()===false)throw Error('补偿未保存');}catch{fail('conversation_rollback_failed','预演会话及补偿保存失败');}throw error;}}
  async function applyReply(details,savedState=trace.appState){const stateKey=previsCanonical(savedState);const resolved=await resolveReply(details,savedState),existing=trace.previsReplies?.find(r=>r.reply_id===details.reply_id);if(existing){if(existing.manifest_revision!==resolved.result.manifest_revision||previsCanonical(existing.payload)!==previsCanonical(details.payload))fail('reply_conflict','同一回复身份不能改变镜头计划');return clone(existing);}const entry={...resolved.result,payload:clone(details.payload),status:'prepared'},oldReplies=trace.previsReplies,oldManifest=trace.previsManifest,nextReplies=[...(oldReplies||[]),entry],nextManifest=clone(entry.manifest);trace.previsReplies=nextReplies;trace.previsManifest=nextManifest;let committed=false;try{if(await persistConversation()===false)fail('conversation_save_failed','预演确认保存失败');committed=true;await validateSourcesCurrent();await validateSelections(savedState);guard();if(trace.appState!==savedState||previsCanonical(savedState)!==stateKey||trace.previsReplies!==nextReplies||trace.previsManifest!==nextManifest)fail('state_changed','预演提交期间确认记录被替换');return clone(entry);}catch(error){if(trace.previsReplies===nextReplies){if(oldReplies===undefined)delete trace.previsReplies;else trace.previsReplies=oldReplies;}if(trace.previsManifest===nextManifest){if(oldManifest===undefined)delete trace.previsManifest;else trace.previsManifest=oldManifest;}if(committed)try{if(await persistConversation()===false)throw Error('补偿未保存');}catch{fail('conversation_rollback_failed','预演确认和补偿保存失败');}throw error;}}
  function requireLedgerNode(record){const node=graph().nodes.find(n=>n.id===previsNodeId(record.target_ref));if(node?.type!=='image'||node.previsTask?.plan_id!==record.plan_id||node.previsTask?.trace_id!==trace.id||node.previsTask?.request_hash!==record.request_hash)fail('output_changed','原预演目标节点已撤销或修改；不能自动重建');return node;}
  async function inspect(record,{recover=true,signal,detached=false}={}){const recordGuard=()=>guard(signal,{detached});recordGuard();if(!(trace.previsJobs||[]).includes(record))fail('task_changed','预演真实任务记录已被替换');requireLedgerNode(record);let job=generationAPI?.getJobs?.().find(j=>j.id===record.job_id);if(recover&&(!job||job.status==='unknown')){if(typeof generationAPI?.recover!=='function')fail('recovery_unavailable','生成任务恢复接口未配置');await generationAPI.recover(record.job_id,{signal});recordGuard();requireLedgerNode(record);job=generationAPI.getJobs().find(j=>j.id===record.job_id);}if(!job)return {status:'unknown'};
   if(job.request?.nodeId!==previsNodeId(record.target_ref)||job.request?.kind!=='image.generate'||job.request?.parameters?.previsPlanId!==record.plan_id)fail('task_changed','原预演生成任务身份不符');if(['failed','cancelled','configuration_required'].includes(job.status))return {status:'failed',code:job.code||job.status};const savedApplication=job.recovered===true&&record.receipt?.job_id===record.job_id&&record.receipt?.node_ref===record.target_ref&&/^[a-f0-9]{64}$/.test(record.receipt?.output_sha256||'');if(job.status!=='succeeded'||job.applying||job.applicationError||!savedApplication&&(!job.applied||!job.resultIds?.includes(previsNodeId(record.target_ref))))return {status:'pending'};
   const node=requireLedgerNode(record),media=node.fullImage||node.image,output=job.outputs?.find(o=>o.type==='image'&&(o.fullImage||o.image||o.url)===media);if(!output||!local(media))fail('output_changed','预演任务结果尚未真实落盘或与节点不符');const receiptKey=record.receipt?previsCanonical(record.receipt):null,jobKey=previsCanonical({request:job.request,outputs:job.outputs,resultIds:job.resultIds,status:job.status,applied:job.applied,recovered:job.recovered}),checkOutput=()=>{recordGuard();const currentJob=generationAPI.getJobs().find(j=>j.id===record.job_id);if(receiptKey&&previsCanonical(record.receipt)!==receiptKey||!(trace.previsJobs||[]).includes(record)||requireLedgerNode(record)!==node||(node.fullImage||node.image)!==media||currentJob?.applying||currentJob?.applicationError||previsCanonical({request:currentJob?.request,outputs:currentJob?.outputs,resultIds:currentJob?.resultIds,status:currentJob?.status,applied:currentJob?.applied,recovered:currentJob?.recovered})!==jobKey)fail('output_changed','预演结果节点、媒体或实际任务读取期间改变');};checkOutput();const actual=await read(media,{signal,check:checkOutput});if(record.receipt&&record.receipt.output_sha256!==actual.sha256)fail('output_changed','预演已保存结果像素改变');const preview=await wait(renderPreview(actual.blob,{signal}),signal);checkOutput();const verifyOutput=async()=>{const checked=await read(media,{signal,check:checkOutput});if(checked.sha256!==actual.sha256)fail('output_changed','预演结果真实字节在核验期间改变');checkOutput();};await verifyOutput();if(record.receipt&&(record.receipt.width!==preview.width||record.receipt.height!==preview.height))fail('output_changed','已保存变体真实尺寸改变');const receipt={node_ref:record.target_ref,job_id:record.job_id,output_sha256:actual.sha256,width:preview.width,height:preview.height};if(!record.receipt){record.receipt=receipt;try{if(await persistConversation()===false)fail('conversation_save_failed','预演生成结果回执保存失败');await verifyOutput();checkOutput();}catch(error){if(record.receipt===receipt)delete record.receipt;try{await persistConversation();}catch{}throw error;}}
   checkOutput();return {status:'completed',image_url:preview.preview.data_uri,cells:previsCells(),receipt:clone(receipt)};
  }
  async function lookupVariants(args,{signal}={}){fields(args,['source_refs']);if(!Array.isArray(args.source_refs)||args.source_refs.length>96||new Set(args.source_refs).size!==args.source_refs.length)fail('invalid_previs','变体查询来源无效');for(const ref of args.source_refs)if(!binding.sources.some(b=>b.node_ref===ref)&&!(trace.previsJobs||[]).some(r=>r.target_ref===ref))fail('invalid_source','变体查询不得读取其他来源');await validateSourcesCurrent({signal});const records=(trace.previsJobs||[]).filter(r=>r.kind==='variants'&&args.source_refs.includes(r.source_ref)),latest=new Map(records.map(r=>[r.shot_code,r])),items=[];for(const record of latest.values()){const value=await inspect(record,{signal});items.push({shot_code:record.shot_code,plan_id:record.plan_id,node_id:record.target_ref,submitted_at:record.submitted_at,...value});}return {content:[],structuredContent:{items}};}
  async function submitTask({kind,plan_id,shot_code,sheet_id,source_ref,source_cell,prompt,reply_id},{callId,signal}={}){
   guard(signal);if(typeof callId!=='string'||!/^[A-Za-z0-9_-]{8,180}$/.test(callId)||typeof plan_id!=='string'||!/^[A-Za-z0-9_-]{1,180}$/.test(plan_id))fail('invalid_previs','预演任务身份无效');const identity={kind,plan_id,shot_code,sheet_id,source_ref,source_cell,prompt,reply_id},request_hash=await previsHash(identity);const planRecords=(trace.previsJobs||[]).filter(r=>r.plan_id===plan_id),historic=planRecords.find(r=>r.call_ids.includes(callId))||planRecords.at(-1);let retryTarget;if(historic){if(historic.request_hash!==request_hash)fail('operation_conflict','同一图板计划不能更改生成参数');if(!historic.job_id)fail('unknown_dispatch','原预演任务尚无已保存身份；请保留目标节点核对，不能重复派发');const node=requireLedgerNode(historic),status=await inspect(historic,{signal}),job=generationAPI?.getJobs?.().find(j=>j.id===historic.job_id);if(!historic.call_ids.includes(callId)&&['failed','cancelled','configuration_required'].includes(job?.status))retryTarget=node;else return {content:[],structuredContent:{node_id:historic.target_ref,plan_id,task_id:historic.job_id,status:status.status}};}
   const key=previsCanonical([scope,plan_id]),prior=operations.get(key);if(prior){if(prior.request_hash!==request_hash)fail('operation_conflict','进行中的图板计划参数不一致');return prior.pending;}const pending=perform();operations.set(key,{request_hash,pending});try{return await pending;}finally{operations.delete(key);}
   async function perform(){await validateSourcesCurrent({signal});guard(signal);const spec=data.generation_spec||{},request={kind:'image.generate',label:kind==='variants'?'预演九格景别变体':'预演镜头图板',prompt,inputs:[],parameters:{count:1,ratio:spec.aspect_ratio||'16:9',...(spec.model?{model:spec.model}:{}),...(spec.resolution?{resolution:spec.resolution,imageSize:spec.resolution}:{}),previsPlanId:plan_id}};if(typeof generationAPI?.availability!=='function'||typeof generationAPI?.submit!=='function')fail('configuration_required','本地图片生成接口未配置');const availability=await generationAPI.availability({request,signal});guard(signal);if(availability?.configured!==true)fail('configuration_required','图片生成服务未配置：请在本地连接API并配置对应图片模型');if(source_ref){const src=source(source_ref),actual=await read(src.fullImage||src.image,{signal,check:()=>guard(signal)});identity.source_sha256=actual.sha256;identity.source_snapshot=captureResultSnapshot(graph().nodes,graph().edges,src.id);const crop=await wait(renderCell(actual.blob,source_cell,{signal}),signal);guard(signal);request.inputs=[{type:'image',url:crop}];}
    const patch={type:'image',title:request.label+' · '+(shot_code||sheet_id),image:'',fullImage:'',width:360,height:203,previsTask:{trace_id:trace.id,plan_id,request_hash}},node=retryTarget||(source_ref?app.createConnected(previsNodeId(source_ref),[patch])?.[0]:typeof app.addNode==='function'?app.addNode('image',undefined,null,patch.title,patch):null);if(!node?.id||!graph().nodes.includes(node))fail('apply_failed','真实预演待生成节点无法创建');request.nodeId=node.id;const target_ref='node/'+node.id,record={...identity,request_hash,target_ref,call_ids:[callId],submitted_at:Date.now(),status:'preparing'};
    const check=()=>{guard(signal,{detached:true});requireLedgerNode(record);if(record.source_snapshot)assertResultSnapshot(record.source_snapshot,graph().nodes,graph().edges);};check();if(await store.save(app.projectSnapshot?.()||graph(),scope.projectId)===false)fail('save_failed','预演目标节点保存失败，未发起生成');await store.flush?.();check();await persistChange('previsJobs',[...(trace.previsJobs||[]),record],check);
    const job=generationAPI.submit(request,{resultMode:'spread',beforeDispatch:check,beforeDispatchReady:async({jobId})=>{check();record.job_id=jobId;record.status='submitted';if(await persistConversation()===false)fail('conversation_save_failed','真实任务身份保存失败，已阻止派发');await validateSourcesCurrent({signal,detached:true});if(record.source_ref){const actual=await read(source(record.source_ref).fullImage||source(record.source_ref).image,{signal,check});if(actual.sha256!==record.source_sha256)fail('source_changed','变体来源真实字节改变');}check();}});if(!job?.id)fail('invalid_task','生成接口未返回真实任务身份');record.job_id=job.id;check();if(await persistConversation()===false)fail('conversation_save_failed','预演真实任务关联未保存；请查询原任务，不可重新发起');check();return {content:[],structuredContent:{node_id:target_ref,plan_id,task_id:job.id,status:'pending'}};
   }
  }
  async function submitVariants(args,{callId,signal,userAction=true}={}){if(userAction!==true)fail('user_action_required','变体生成须来自当前官方页面实际操作');fields(args,['plan_id','source','shot_code']);fields(args.source,['kind','sheet_node_ref','cell']);if(args.source.kind!=='cell'||!Number.isInteger(args.source.cell)||args.source.cell<0||args.source.cell>8)fail('invalid_previs','变体来源必须为真实图板cell');const shot=data.sheets.flatMap(s=>s.shots).find(s=>s.shot_code===args.shot_code),edited=trace.appState?.edits?.[args.shot_code]?.image??shot?.image;if(!shot||edited?.kind!=='cell'||edited.sheet_node_ref!==args.source.sheet_node_ref||edited.cell!==args.source.cell)fail('invalid_source','变体来源不匹配当前真实镜头');const prompt='Create one storyboard sheet with exactly nine equal cells in a 3 by 3 grid, no text, no borders. Use the supplied real frame as identity and scene reference. Show the same subject and scene in ELS, LS, MLS, MS, MCU, CU, ECU and low/high camera angles. Preserve character, props, lighting, and scene continuity. '+(shot.script_text||'');return submitTask({kind:'variants',plan_id:args.plan_id,shot_code:args.shot_code,source_ref:args.source.sheet_node_ref,source_cell:args.source.cell,prompt},{callId,signal});}

  async function querySelectedVariants({signal,recover=true}={}){const savedState=trace.appState,stateKey=previsCanonical(savedState);guard(signal);const response=clone(data),sources=clone(binding.sources),refs=new Map();for(const [code,e]of Object.entries(savedState?.edits||{})){const ref=e.image?.sheet_node_ref,plan=savedState.variants?.[code]?.plan_id;if(e.image?.kind==='cell'&&ref&&plan)refs.set(ref,{code,plan});}for(const sheet of response.sheets)for(const shot of sheet.shots)if(shot.variant?.node_ref)refs.set(shot.variant.node_ref,{code:shot.shot_code,plan:shot.variant.plan_id});response.textures=response.textures||[];for(const [ref,{code,plan}]of refs){const record=(trace.previsJobs||[]).filter(r=>r.kind==='variants'&&r.target_ref===ref&&r.shot_code===code&&r.plan_id===plan).at(-1);if(!record||!record.receipt)fail('invalid_selection','刷新恢复缺少实际已保存变体回执');const status=await inspect(record,{recover,signal});if(status.status!=='completed')return {changed:false,pending:true};guard(signal);const texture_id='variant-'+ref;response.textures=response.textures.filter(t=>t.texture_id!==texture_id);response.textures.push({texture_id,sheet_node_ref:ref,image_url:status.image_url,cells:previsCells()});if(!sources.some(b=>b.node_ref===ref)){const node=requireLedgerNode(record);sources.push({sheet_id:record.shot_code,node_ref:ref,media:node.fullImage||node.image,source_sha256:record.receipt.output_sha256,snapshot:captureResultSnapshot(graph().nodes,graph().edges,node.id)});}}await validateSourcesCurrent({signal});guard(signal);if(trace.appState!==savedState||previsCanonical(savedState)!==stateKey)fail('state_changed','已保存选图恢复期间编辑变化');if(response.textures.reduce((n,t)=>n+(t.image_url?.length||0),0)>limits.previewBytes)fail('preview_limit','已保存选图总预览超过有界预算');const context={projectId:scope.projectId,sources,responseFingerprint:previsCanonical(response)};return {changed:previsCanonical(response)!==previsCanonical(data)||previsCanonical(sources)!==previsCanonical(binding.sources),projection:{response,previsSourceContext:context}};}
  async function querySheets({signal}={}){await validateSourcesCurrent({signal});const manifest=await hydrateSelectedVariants(clone(trace.previsManifest||data),{signal});manifest.textures=manifest.textures||[];let changed=false;for(const record of (trace.previsJobs||[]).filter(r=>r.kind==='sheet')){const status=await inspect(record,{signal});if(status.status!=='completed')continue;const sheet=manifest.sheets.find(s=>s.sheet_id===record.sheet_id);if(!sheet)continue;const texture_id='sheet-'+sheet.sheet_id;sheet.sheet_node_ref=record.target_ref;sheet.texture_id=texture_id;sheet.cells=previsCells();for(const shot of sheet.shots)if(!shot.image)shot.image={kind:'cell',texture_id,sheet_node_ref:record.target_ref,cell:shot.cell};manifest.textures=manifest.textures.filter(t=>t.texture_id!==texture_id);manifest.textures.push({texture_id,sheet_node_ref:record.target_ref,image_url:status.image_url,cells:status.cells});changed=true;}guard(signal);changed=previsCanonical(trace.previsManifest||data)!==previsCanonical(manifest);if(changed)await persistChange('previsManifest',manifest,()=>guard(signal));const sources=clone(binding.sources);for(const record of (trace.previsJobs||[]).filter(r=>r.receipt)){if(!manifest.textures.some(t=>t.sheet_node_ref===record.target_ref))continue;if(!sources.some(b=>b.node_ref===record.target_ref)){const node=requireLedgerNode(record);sources.push({sheet_id:record.sheet_id||record.shot_code,node_ref:record.target_ref,media:node.fullImage||node.image,source_sha256:record.receipt.output_sha256,snapshot:captureResultSnapshot(graph().nodes,graph().edges,node.id)});}}guard(signal);return {manifest,changed,manifest_revision:await previsHash({manifest,sources}),projection:{response:manifest,previsSourceContext:{projectId:scope.projectId,sources,responseFingerprint:previsCanonical(manifest)}}};}
  guard();return {scope,binding:clone(binding),guard,validateSourcesCurrent,validateState:value=>{guard();return validatePrevisState(value,data);},validateReply,preflightReply,resolveReply,applyReply,submitVariants,lookupVariants,querySelectedVariants,querySheets,inspect,submitTask,isCurrent:()=>{try{return guard();}catch{return false;}},dispose:()=>lifetime.abort(failure('cancelled','预演页面已关闭'))};
 }
 async function generateSheets(args,trace,chat,{userAction,isCurrent,sourceContext,signal}={}){
  if(userAction!==true||typeof isCurrent!=='function'||!isCurrent()||!sourceContext||sourceContext.scope.traceId!==trace?.id||sourceContext.scope.chatId!==chat?.id)fail('user_action_required','预演图板生成须经正常工具确认');fields(args,['reply_id','shot_codes']);const reply=trace.previsReplies?.find(r=>r.reply_id===args.reply_id);if(!reply||reply.status!=='accepted'||!reply.run_id||!trace.appReplyReceipts?.some(r=>r.reply_id===reply.reply_id&&r.run_id===reply.run_id))fail('missing_reply','图板生成需要实际接受并持久保存的预演确认');if(!Array.isArray(args.shot_codes)||!args.shot_codes.length||new Set(args.shot_codes).size!==args.shot_codes.length)fail('invalid_previs','镜头生成范围无效');sourceContext.guard(signal);const manifest=trace.previsManifest||reply.manifest,shots=manifest.sheets.flatMap(s=>s.shots);if(args.shot_codes.some(c=>!shots.some(s=>s.shot_code===c)))fail('invalid_previs','图板生成仅可处理已确认镜头');const results=[];
  for(const sheet of manifest.sheets.filter(s=>s.shots.some(s=>args.shot_codes.includes(s.shot_code)))){if(sheet.sheet_node_ref)continue;if(sheet.shots.some(s=>!args.shot_codes.includes(s.shot_code)))fail('invalid_previs','同一图板需要明确确认其全部镜头');const prompt='Create one storyboard sheet, exactly nine equally sized cells in a 3 by 3 grid. Fill the requested cells in row-major order; no captions, text, borders or logos. '+sheet.shots.map(s=>`Cell ${s.cell+1}: ${s.size||'MS'}, camera ${s.camera_height||'eye'}; ${s.script_text||''}`).join('\n');const plan_id='sheet_'+await previsHash({reply_id:args.reply_id,sheet_id:sheet.sheet_id});results.push(await sourceContext.submitTask({kind:'sheet',plan_id,sheet_id:sheet.sheet_id,prompt,reply_id:args.reply_id},{callId:'generate_'+plan_id,signal}));if(!isCurrent())fail('stale_previs','图板生成所属会话已切换');}
  return {submitted:results.map(r=>r.structuredContent),reply_id:args.reply_id};
 }
 return {prepareAppArgs,bindPreparedResult,capture,generateSheets};
}
