// Contracts extracted from the unmodified previs@v3.584fd5b2.html.
export const previsUri='ui://tapnow/previs@v3';
export const previsPolicy=Object.freeze({allowExpanded:true,autoExpandOnReady:true});
export const previsLimits=Object.freeze({shots:96,stateBytes:16384,textBytes:8192,sourceBytes:16*1024*1024,totalBytes:64*1024*1024,timeoutMs:30000,previewBytes:900000});
export const previsMoves=Object.freeze(['static','push_in','pull_out','pan_left','pan_right','tilt_up','tilt_down']);
const sizes=['ELS','LS','MLS','MS','MCU','CU','ECU'],heights=['low','eye','high','overhead'],curves=['smooth','linear','punch'],transitions=['cut','dissolve'];
const object=v=>!!v&&typeof v==='object'&&!Array.isArray(v),clone=v=>structuredClone(v);
const fail=message=>{throw Object.assign(Error(message||'预演数据与实际镜头或已保存状态不一致'),{code:'invalid_previs'});};
const text=(v,max,required=false)=>{if(typeof v!=='string'||v.length>max||required&&!v.trim())fail();return v;};
const fields=(v,keys)=>{if(!object(v)||Object.keys(v).some(k=>!keys.includes(k)))fail();};
const id=v=>{if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,180}$/.test(v))fail();return v;};
export const previsNodeId=v=>{if(typeof v!=='string'||!/^node\/[A-Za-z0-9_-]{1,180}$/.test(v))fail('预演来源必须为实际node引用');return v.slice(5);};
const number=(v,min,max)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)fail();return v;};
const choice=(v,values)=>{if(!values.includes(v))fail();return v;};
const cell=v=>{if(!Number.isInteger(v)||v<0||v>8)fail();return v;};
export const previsCells=()=>Array.from({length:9},(_,i)=>({x:(i%3)/3,y:Math.floor(i/3)/3,w:1/3,h:1/3}));
export function preparePrevis(data,title='镜头预演'){
 fields(data,['version','locale','title','sheets','order','generation_spec','textures']);if(data.version!==undefined&&data.version!==3)fail();
 if(!Array.isArray(data.sheets)||!data.sheets.length||data.sheets.length>96)fail();const ids=new Set(),codes=new Set();
 const sheets=data.sheets.map(sheet=>{fields(sheet,['sheet_id','sheet_node_ref','shots','texture_id','image_url','cells']);id(sheet.sheet_id);if(ids.has(sheet.sheet_id)||!Array.isArray(sheet.shots)||!sheet.shots.length||sheet.shots.length>9)fail();ids.add(sheet.sheet_id);if(sheet.sheet_node_ref!==undefined)previsNodeId(sheet.sheet_node_ref);
 const used=new Set(),shots=sheet.shots.map(shot=>{fields(shot,['shot_code','cell','duration','move','size','camera_height','speed_curve','transition','script_text','dialogue','lens','image','variant']);id(shot.shot_code);if(codes.has(shot.shot_code)||used.has(cell(shot.cell)))fail();codes.add(shot.shot_code);used.add(shot.cell);number(shot.duration,.4,15);choice(shot.move,previsMoves);for(const [k,values]of Object.entries({size:sizes,camera_height:heights,speed_curve:curves,transition:transitions}))if(shot[k]!==undefined)choice(shot[k],values);if(shot.script_text!==undefined)text(shot.script_text,600);if(shot.lens!==undefined)text(shot.lens,120);if(shot.dialogue!==undefined){fields(shot.dialogue,['text','est_duration']);text(shot.dialogue.text,200);number(shot.dialogue.est_duration,0,120);}return clone(shot);});return {...clone(sheet),shots};});
 if(codes.size>96)fail();const order=data.order??sheets.flatMap(s=>[...s.shots].sort((a,b)=>a.cell-b.cell).map(s=>s.shot_code));if(!Array.isArray(order)||order.length!==codes.size||new Set(order).size!==codes.size||order.some(c=>!codes.has(c)))fail();
 let generation_spec;if(data.generation_spec!==undefined){fields(data.generation_spec,['model','aspect_ratio','resolution']);generation_spec=clone(data.generation_spec);for(const key of ['model','resolution'])if(generation_spec[key]!==undefined)text(generation_spec[key],120,true);if(generation_spec.aspect_ratio!==undefined&&!/^(?:16:9|9:16|1:1|4:3|3:4|21:9|3:2|2:3)$/.test(generation_spec.aspect_ratio))fail();}
 return {version:3,title:text(data.title??title,200,true),locale:text(data.locale??'zh-CN',16,true),sheets,order:clone(order),...(generation_spec?{generation_spec}:{}),...(data.textures?{textures:clone(data.textures)}:{})};
}
export function initialPrevisState(data){return {v:3,selected_shot:data.order[0],edits:{},order:[...data.order],deleted:[],variants:{}};}
export function validatePrevisState(value,data){
 fields(value,['v','selected_shot','edits','order','deleted','variants','submission']);if(![2,3].includes(value.v))fail();const codes=data.sheets.flatMap(s=>s.shots.map(s=>s.shot_code));if(!codes.includes(value.selected_shot)||!Array.isArray(value.order)||value.order.length!==codes.length||new Set(value.order).size!==codes.length||value.order.some(c=>!codes.includes(c))||!Array.isArray(value.deleted)||new Set(value.deleted).size!==value.deleted.length||value.deleted.some(c=>!codes.includes(c)))fail();fields(value.edits,codes);fields(value.variants,codes);let bytes=0;
 for(const edit of Object.values(value.edits)){fields(edit,['dur','move','curve','trans','size','camera_height','image','stale','script_text','dialogue_text']);number(edit.dur,.4,15);choice(edit.move,previsMoves);choice(edit.curve,curves);choice(edit.trans,transitions);if(edit.size!==undefined)choice(edit.size,sizes);if(edit.camera_height!==undefined)choice(edit.camera_height,heights);if(edit.stale!==undefined&&typeof edit.stale!=='boolean')fail();for(const [key,max]of [['script_text',600],['dialogue_text',200]])if(edit[key]!==undefined)bytes+=new TextEncoder().encode(text(edit[key],max,true)).length;if(edit.image!==undefined){fields(edit.image,['kind','texture_id','sheet_node_ref','cell']);choice(edit.image.kind,['cell','asset']);text(edit.image.texture_id,220,true);previsNodeId(edit.image.sheet_node_ref);if(edit.image.kind==='cell')cell(edit.image.cell);}}
 if(bytes>previsLimits.textBytes)fail('预演文本超过官方8KiB预算');
 for(const variant of Object.values(value.variants)){fields(variant,['plan_id','call_id','status','node_id','texture_id','source_key','submitted_at','original_image','original_size','original_camera_height','error','error_code','error_reason','error_request_id']);id(variant.plan_id);id(variant.call_id);choice(variant.status,['submitting','pending','ready','blocked','failed']);if(variant.node_id!==undefined)previsNodeId(variant.node_id);if(variant.submitted_at!==undefined)number(variant.submitted_at,0,Number.MAX_SAFE_INTEGER);}
 if(value.submission!==undefined){fields(value.submission,['reply_id','run_id','payload_hash','status','submitted_at','accepted_by_host','projection_received','edited_after_submit']);id(value.submission.reply_id);text(value.submission.payload_hash,80,true);choice(value.submission.status,['submitted','accepted','running','completed','failed','waiting','unknown','inactive']);if(value.submission.run_id!==undefined)text(value.submission.run_id,200,true);for(const k of ['accepted_by_host','projection_received','edited_after_submit'])if(value.submission[k]!==undefined&&typeof value.submission[k]!=='boolean')fail();if(value.submission.submitted_at!==undefined)number(value.submission.submitted_at,0,Number.MAX_SAFE_INTEGER);}
 if(new TextEncoder().encode(JSON.stringify(value)).length>previsLimits.stateBytes)fail('预演状态超过官方16KiB预算');return clone(value);
}
export function previsReplyPayload(data,value){
 const s=validatePrevisState(value,data),variant_selections=[];const edits=Object.entries(s.edits).filter(([code])=>!s.deleted.includes(code)).map(([shot_code,e])=>{const result={shot_code,duration:e.dur,move:e.move,speed_curve:e.curve,transition:e.trans};for(const k of ['size','camera_height','script_text','dialogue_text'])if(e[k]!==undefined)result[k]=e[k];const image=e.image,v=s.variants[shot_code];if(image?.kind==='cell'&&v?.node_id===image.sheet_node_ref&&v.plan_id)variant_selections.push({shot_code,plan_id:v.plan_id,node_ref:v.node_id,cell:image.cell});else if(image)result.image=image.kind==='cell'?{kind:'cell',sheet_ref:image.sheet_node_ref,cell:image.cell}:{kind:'asset',node_ref:image.sheet_node_ref};return result;});
 return {schema_version:'previs_reply.v1',decision:'confirm',edits,deleted_shot_codes:s.deleted,order:s.order.filter(c=>!s.deleted.includes(c)),variant_selections};
}
export const previsCanonical=value=>JSON.stringify(value,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
export async function previsHash(value){const bytes=value instanceof Uint8Array?value:new TextEncoder().encode(previsCanonical(value));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export function validatePrevisReply(details,data,savedState){fields(details,['type','reply_id','action','payload','expected_manifest_revision']);if(details.type!=='app_reply'||details.action!=='previs_reply'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(details.reply_id)||previsCanonical(details.payload)!==previsCanonical(previsReplyPayload(data,savedState)))fail('预演确认必须精确匹配已保存编辑');if(!details.payload.order.length)fail('预演至少保留一个镜头');for(const sheet of data.sheets){const duration=sheet.shots.filter(s=>!details.payload.deleted_shot_codes.includes(s.shot_code)).reduce((n,s)=>n+(details.payload.edits.find(e=>e.shot_code===s.shot_code)?.duration??s.duration),0);if(duration>30+Number.EPSILON)fail('每张图板镜头总时长不能超过30秒');}return clone(details.payload);}
export function applyPrevisPayload(data,payload){const next=clone(data),deleted=new Set(payload.deleted_shot_codes);next.order=[...payload.order];next.sheets=next.sheets.map(sheet=>({...sheet,shots:sheet.shots.filter(s=>!deleted.has(s.shot_code)).map(shot=>{const edit=payload.edits.find(e=>e.shot_code===shot.shot_code),selection=payload.variant_selections.find(v=>v.shot_code===shot.shot_code),result={...shot};if(edit){for(const k of ['duration','move','speed_curve','transition','size','camera_height','script_text'])if(edit[k]!==undefined)result[k]=edit[k];if(edit.dialogue_text!==undefined&&result.dialogue)result.dialogue={...result.dialogue,text:edit.dialogue_text};if(edit.image)result.image=edit.image.kind==='cell'?{kind:'cell',sheet_node_ref:edit.image.sheet_ref,cell:edit.image.cell}:{kind:'asset',sheet_node_ref:edit.image.node_ref};}if(selection){result.image={kind:'cell',texture_id:'variant-'+selection.node_ref,sheet_node_ref:selection.node_ref,cell:selection.cell};result.variant={plan_id:selection.plan_id,node_ref:selection.node_ref,cell:selection.cell};}return result;})})).filter(s=>s.shots.length);return next;}
// The official UI validates before its debounced state commit. This transient
// reconstruction validates the payload without pretending it has been saved.
export function previsStateFromPayload(data,payload){
 fields(payload,['schema_version','decision','edits','deleted_shot_codes','order','variant_selections']);if(payload.schema_version!=='previs_reply.v1'||payload.decision!=='confirm'||!Array.isArray(payload.edits)||!Array.isArray(payload.deleted_shot_codes)||!Array.isArray(payload.order)||!Array.isArray(payload.variant_selections))fail();const state=initialPrevisState(data),seen=new Set();state.deleted=clone(payload.deleted_shot_codes);state.order=[...payload.order,...state.deleted];state.edits={};
 for(const edit of payload.edits){fields(edit,['shot_code','duration','move','speed_curve','transition','size','camera_height','script_text','dialogue_text','image']);if(seen.has(edit.shot_code))fail();seen.add(edit.shot_code);const shot=data.sheets.flatMap(s=>s.shots).find(s=>s.shot_code===edit.shot_code);if(!shot)fail();const e={dur:edit.duration,move:edit.move,curve:edit.speed_curve,trans:edit.transition};for(const k of ['size','camera_height','script_text','dialogue_text'])if(edit[k]!==undefined)e[k]=edit[k];if(edit.image){fields(edit.image,edit.image.kind==='cell'?['kind','sheet_ref','cell']:['kind','node_ref']);const ref=edit.image.sheet_ref??edit.image.node_ref,texture=data.textures?.find(t=>t.sheet_node_ref===ref);if(!texture)fail();e.image={kind:edit.image.kind,texture_id:texture.texture_id,sheet_node_ref:ref,...edit.image.kind==='cell'?{cell:edit.image.cell}:{}};}state.edits[edit.shot_code]=e;}
 const selections=new Set();for(const selection of payload.variant_selections){fields(selection,['shot_code','plan_id','node_ref','cell']);if(selections.has(selection.shot_code)||!state.edits[selection.shot_code]||state.edits[selection.shot_code].image)fail();selections.add(selection.shot_code);previsNodeId(selection.node_ref);cell(selection.cell);state.edits[selection.shot_code].image={kind:'cell',texture_id:'variant-'+selection.node_ref,sheet_node_ref:selection.node_ref,cell:selection.cell};state.variants[selection.shot_code]={plan_id:selection.plan_id,call_id:'preflight-'+selection.plan_id,status:'ready',node_id:selection.node_ref};}
 validatePrevisState(state,data);if(previsCanonical(previsReplyPayload(data,state))!==previsCanonical(payload))fail();return state;
}
