import {createAppController,prepareApp} from '../integration.mjs';
import {adReviewUri} from '../ad-review.mjs';
import {createAdReviewRuntime} from '../ad-review-runtime.mjs';
const status=document.getElementById('status'),cards=document.getElementById('cards'),reply=document.getElementById('reply'),busy=document.getElementById('busy');
let database,chat={id:'qa-ad-review-chat',messages:[],replies:[]},graph={nodes:[],edges:[]},saving=false,queueSaving=false,pageLeaving=false;const urls=new Map();
async function openDatabase(){database=await new Promise((resolve,reject)=>{const request=indexedDB.open('tapnow-qa-ad-review-v1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('sessions');request.result.createObjectStore('assets');};request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('验收存储被旧页阻塞'));});}
function read(store,key){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),request=tx.objectStore(store).get(key);tx.oncomplete=()=>resolve(request.result);tx.onerror=tx.onabort=()=>reject(tx.error||request.error);});}
function write(store,key,value){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error);});}
const save=()=>write('sessions','current',structuredClone({chat,graph}));
const localAssets={async put(blob){const id='asset:'+crypto.randomUUID();await write('assets',id,blob);return id;},async url(id){if(urls.has(id))return urls.get(id);const blob=await read('assets',id);if(!(blob instanceof Blob))throw Error('本地验收源媒体不存在');const url=URL.createObjectURL(blob);urls.set(id,url);return url;}};
const runtime=createAdReviewRuntime({app:{getState:()=>graph},localAssets,getProjectId:()=> 'qa-ad-review-project'});
function showReplies(){reply.value=chat.replies.map(item=>item.text).join('\n\n');status.textContent=`已保存 ${chat.messages.length} 个官方审核页；实际交接 ${chat.replies.length} 次；未调用模型。`;}
const current=(trace,currentChat)=>()=>!pageLeaving&&chat===currentChat&&chat.messages.includes(trace);
const controller=createAppController({getContext:()=>({chat,panelActive:true,pageLeaving,streaming:busy.checked}),getAdReviewSourceContext:(response,trace,currentChat)=>runtime.capture(response,{trace,chat:currentChat,isCurrent:current(trace,currentChat)}),
 onSaveState:async(currentChat,trace,state)=>{if(saving||queueSaving)throw Error('验收正在保存，请稍后');const previous=trace.appState;trace.appState=state;saving=true;try{await save();}catch(error){trace.appState=previous;throw error;}finally{saving=false;}},
 onQueuePrompt:async(text,trace,currentChat,metadata,isSourceCurrent=()=>true)=>{if(busy.checked||saving||queueSaving||!isSourceCurrent())return false;if(metadata?.handoffId&&chat.replies.some(item=>item.traceId===trace.id&&item.handoffId===metadata.handoffId))return true;const previous=chat.replies,entry={traceId:trace.id,...metadata,text},next=[...previous,entry];chat.replies=next;queueSaving=true;let committed=false;try{await save();committed=true;if(!isSourceCurrent()||busy.checked)throw Error('保存交接期间审核来源已切换');}catch(error){chat.replies=chat.replies===next?previous:chat.replies.filter(item=>item!==entry);if(committed)await save();throw error;}finally{queueSaving=false;}showReplies();return true;},onError:message=>{status.textContent=message;}});
function render(){controller.prune(chat.messages);for(const trace of chat.messages){const element=controller.render(trace);if(element&&element.parentElement!==cards)cards.append(element);}showReplies();}
async function sourcePreview(){const section=document.getElementById('sources');section.replaceChildren();for(const node of graph.nodes){const media=document.createElement(node.type==='image'?'img':'video');media.src=await localAssets.url(node.image||node.video);if(node.type==='video'){media.controls=true;media.preload='metadata';}else media.alt='Canvas实际绘制的保温杯验收图片';section.append(media);}}
async function imageBlob(changed=false){const canvas=document.createElement('canvas');canvas.width=480;canvas.height=320;const ctx=canvas.getContext('2d');ctx.fillStyle=changed?'#7d2d2d':'#a7bfaf';ctx.fillRect(0,0,480,320);ctx.fillStyle='#f2eee2';ctx.fillRect(170,70,120,190);ctx.fillStyle='#252d2a';ctx.fillRect(164,58,132,25);ctx.font='bold 24px system-ui';ctx.fillText(changed?'替换来源':'本地验收素材',34,300);return new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}
function input(){const stage=document.getElementById('stage').value,items=graph.nodes.filter(node=>stage==='frame_cull'?node.type==='image':node.type==='video').map((node,index)=>({combo:'C'+(index+1),node_ref:'node/'+node.id,media:node.type,node_title:node.title,hook:index?'对照方向':'随身携带',angle:'通勤',persona:'日常使用者',meta:'真实本地素材，创意判断'}));document.getElementById('input').value=JSON.stringify({locale:document.getElementById('locale').value,stage,batch:{label:'local-batch-'+stage,product:'保温杯',note:'验收素材；不代表广告表现或模型审查。'},items},null,2);}
document.getElementById('fixture').onclick=async()=>{const button=document.getElementById('fixture');button.disabled=true;try{if(graph.nodes.length)throw Error('素材已存在，可以直接打开审核');const response=await fetch('/qa/trim-scenes.mp4');if(!response.ok)throw Error('本机QA MP4不存在');const video=await localAssets.put(await response.blob()),image=await localAssets.put(await imageBlob());graph.nodes=[{id:'qa-ad-image-a',type:'image',image,title:'本地杯子首帧A'},{id:'qa-ad-image-b',type:'image',image,title:'本地杯子首帧B'},{id:'qa-ad-video-a',type:'video',video,title:'本地真实视频A'},{id:'qa-ad-video-b',type:'video',video,title:'本地真实视频B'}];await save();input();await sourcePreview();showReplies();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
document.getElementById('open').onclick=async()=>{const button=document.getElementById('open');button.disabled=true;try{const args={resource_uri:adReviewUri,title:'真实本地广告创意审核',data:JSON.parse(document.getElementById('input').value)},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>!pageLeaving&&!busy.checked}),trace={id:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)},previous=chat.messages;chat.messages=[...previous,trace];try{await save();}catch(error){chat.messages=previous;throw error;}render();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
document.getElementById('stage').onchange=input;document.getElementById('locale').onchange=input;document.getElementById('rerender').onclick=render;busy.onchange=render;
document.getElementById('replace').onclick=async()=>{try{const node=graph.nodes.find(node=>node.id==='qa-ad-image-a');if(!node)throw Error('请先保存验收素材');node.image=await localAssets.put(await imageBlob(true));await save();await sourcePreview();status.textContent='源图已真实替换；旧首帧审核页再次保存/确认应拒绝。';}catch(error){status.textContent=error.message;}};
window.addEventListener('pagehide',()=>{pageLeaving=true;controller.reset();for(const url of urls.values())URL.revokeObjectURL(url);database?.close();});
try{await openDatabase();const stored=await read('sessions','current');if(stored){if(!stored.chat?.id||!Array.isArray(stored.chat.messages)||!Array.isArray(stored.chat.replies)||!Array.isArray(stored.graph?.nodes))throw Error('验收存储无效');chat=stored.chat;graph=stored.graph;}input();render();await sourcePreview();for(const id of ['fixture','open','rerender','busy','replace'])document.getElementById(id).disabled=false;}catch(error){status.textContent='验收页未就绪：'+error.message;}
