import {createAppController,prepareApp} from '../integration.mjs';
import {animaticUri,animaticTools} from '../animatic.mjs';
import {createAnimaticRuntime} from '../animatic-runtime.mjs';
import {providerConfigured} from '../../node-composer/provider-configuration.mjs';
import {prepareGenerationRequestReady} from '../../node-composer/generation-request.mjs';
import {resultProvenance} from '../../media-preview/provenance.mjs';
const status=document.getElementById('status'),cards=document.getElementById('cards'),reply=document.getElementById('reply'),nodes=document.getElementById('nodes'),busy=document.getElementById('busy'),fail=document.getElementById('fail');
function fixture(){const c=document.createElement('canvas');c.width=c.height=900;const x=c.getContext('2d'),colors=['#bd9c67','#658f82','#d8856c','#9f7b98','#7296ac','#c7b877','#678581','#a68370','#94a87c'];for(let i=0;i<9;i++){const left=i%3*300,top=Math.floor(i/3)*300;x.fillStyle=colors[i];x.fillRect(left,top,300,300);x.fillStyle='#242420';x.fillRect(left+85,top+125,130,100);x.beginPath();x.arc(left+150,top+90,35,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='16px system-ui';x.fillText('NON AI QA CELL '+i,left+32,top+270);}return c.toDataURL('image/png');}
const input=fixture();let database,session={chat:{id:'qa-animatic-chat',messages:[],replies:[]},graph:{nodes:[{id:'qa-source',type:'image',title:'非 AI QA九格源图',image:input,fullImage:input,x:0,y:0,width:375,height:375,pixelWidth:900,pixelHeight:900}],edges:[]},undo:[]};
async function openDatabase(){database=await new Promise((resolve,reject)=>{const r=indexedDB.open('freenow-qa-animatic-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('sessions');r.result.createObjectStore('assets');};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('独立验收库被旧页阻塞'));});}
function read(store,key){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),r=tx.objectStore(store).get(key);tx.oncomplete=()=>resolve(r.result);tx.onerror=tx.onabort=()=>reject(tx.error||Error('事务读取失败'));});}
function write(store,key,value){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error||Error('事务提交失败'));});}
const save=()=>write('sessions','current',structuredClone(session)),assetUrls=new Map(),localAssets={async put(blob){const id='asset:'+crypto.randomUUID();await write('assets',id,blob);return id;},async url(id){if(!id.startsWith('asset:'))return id;if(assetUrls.has(id))return assetUrls.get(id);const blob=await read('assets',id);if(!(blob instanceof Blob))throw Error('实际镜头素材不存在');const url=URL.createObjectURL(blob);assetUrls.set(id,url);return url;}};
const app={getState:()=>session.graph,createConnected:(sourceId,patches)=>{session.undo.push(structuredClone(session.graph));return patches.map(p=>{const source=session.graph.nodes.find(n=>n.id===sourceId);if(!source)throw Error('源图已失效');const node={...p,id:crypto.randomUUID(),x:source.x+430,y:source.y};session.graph.nodes.push(node);session.graph.edges.push({id:crypto.randomUUID(),source:sourceId,target:node.id});return node;});},updateNode:(id,patch)=>{const n=session.graph.nodes.find(n=>n.id===id);if(!n)throw Error('结果节点失效');session.undo.push(structuredClone(session.graph));Object.assign(n,patch);return n;}};
async function metadata(){const response=await fetch('/api/generation/config',{signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('本机生成配置读取失败');return response.json();}
const provider=GenerationCore.httpProvider({baseUrl:new URL('/api/generation',location.href).href,recoverable:true});provider.isConfigured=async({request}={})=>providerConfigured(await metadata(),request);
const service=new GenerationCore.TaskService({prepareRequest:prepareGenerationRequestReady,prepareInputs:async request=>{const inputs=[];for(const item of request.inputs??[]){if(!item.url?.startsWith('asset:')){inputs.push(item);continue;}const blob=await read('assets',item.url);if(!(blob instanceof Blob))throw Error('实际景别输入不存在');const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});inputs.push({...item,url});}return {...request,inputs};}});service.setProvider(provider);
const generation={submit:(request,options)=>service.submit(request,options),getJobs:()=>[...service.jobs.values()].map(({controller,...job})=>job),recover:(id,options)=>service.recover(id,options),availability:async({kind}={})=>({configured:providerConfigured(await metadata(),{kind})}),async applyRecovered(id){return apply(id);},async retryApplication(id){return apply(id);}};
async function apply(id){const job=service.jobs.get(id);if(job?.status!=='succeeded'||job.outputs?.length!==1||job.outputs[0].type!=='image')throw Error('任务尚未生成真实单图');const o=job.outputs[0],url=o.fullImage||o.image||o.url;if(!GenerationCore.isGenerationMediaRef(url))throw Error('结果必须已经在本机gateway保存');const image=new Image();image.src=url;await image.decode();app.updateNode(job.request.nodeId,{image:url,fullImage:url,pixelWidth:image.naturalWidth,pixelHeight:image.naturalHeight,...resultProvenance(job,o)});if(fail.checked)throw Error('QA画布保存失败');await save();job.applied=true;job.resultIds=[job.request.nodeId];show();return job;}
service.subscribe(job=>{if(job.status==='succeeded'&&!job.recovered)apply(job.id).catch(error=>{service.jobs.get(job.id).applicationError=error.message;status.textContent=error.message;});show().catch(()=>{});});
const runtime=createAnimaticRuntime({app,localAssets,store:{save:async()=>{if(fail.checked)return false;await save();return true;},flush:async()=>{}},getProjectId:()=> 'qa-animatic-project',persistConversation:save,generation});
async function show(){nodes.replaceChildren();for(const node of session.graph.nodes){const fig=document.createElement('figure'),cap=document.createElement('figcaption');if(node.fullImage||node.image){const img=document.createElement('img');img.src=await localAssets.url(node.fullImage||node.image);img.width=220;img.alt=node.title;fig.append(img);}cap.textContent='node/'+node.id+'\n'+node.title;fig.append(cap);nodes.append(fig);}reply.value=JSON.stringify({states:session.chat.messages.map(t=>({trace:t.id,state:t.appState,jobs:t.animaticJobs,context:t.animaticContext})),queue:session.chat.replies},null,2);status.textContent=`${session.chat.messages.length} 个官方编辑器；${session.chat.replies.length} 条普通交接；${service.jobs.size} 个真实本机任务。源图为非 AI fixture；未把fixture当作生成结果。`;}
const controller=createAppController({getContext:()=>({chat:session.chat,panelActive:true,pageLeaving:false,streaming:busy.checked}),getGenerationAppSourceContext:(data,trace,chat)=>runtime.capture(data,{trace,chat,isCurrent:()=>chat===session.chat&&chat.messages.includes(trace)&&!busy.checked}),onGenerationAppTool:async(name,args,trace,chat,options)=>{const result=await runtime[name===animaticTools.submit?'submit':'lookup'](args,trace,chat,options);await show();return result;},onGenerationAppContext:async(value,trace,chat,options)=>{const result=await runtime.setModelContext(value,trace,chat,options);await show();return result;},onSaveState:async(chat,trace,state)=>{const old=trace.appState;trace.appState=state;try{await save();}catch(error){trace.appState=old;throw error;}await show();},onQueuePrompt:async(text,trace,chat,metadata,isCurrent=()=>true,validate)=>{if(busy.checked||!isCurrent())return false;const old=chat.replies;if(chat.replies.some(r=>r.handoffId===metadata.handoffId))return true;chat.replies=[...old,{text,trace_id:trace.id,...metadata}];try{await save();await validate?.();if(!isCurrent())throw Error('保存期间来源切换');}catch(e){chat.replies=old;await save();throw e;}await show();return true;},onError:message=>status.textContent=message});
function render(){controller.prune(session.chat.messages);for(const trace of session.chat.messages){const el=controller.render(trace);if(el&&el.parentElement!==cards)cards.append(el);}show().catch(e=>status.textContent=e.message);}
async function open(textOnly=false){try{const shots=Array.from({length:4},(_,i)=>({shot_code:'SH'+(i+1),cell:i,duration:2+i/2,move:['static','push_in','pan_left','tilt_down'][i],size:['MS','CU','LS','MCU'][i],camera_height:'eye',script_text:['人物发现信封','手部打开信封','人物在桌前阅读','人物望向窗外'][i],...(i===1?{dialogue:{text:'这封信是给我的？',est_duration:3.1}}:{})})),args={resource_uri:animaticUri,title:textOnly?'QA 待生成镜头设计':'QA 真实九格分镜',data:{version:3,locale:'zh-CN',beats:[{beat_id:'beat-1',text:'非 AI QA：发现与阅读',shot_codes:['SH1','SH2','SH3']},{beat_id:'beat-2',text:'反应',shot_codes:['SH4']}],sheets:[{sheet_id:'board-1',label:'非 AI fixture 镜头设计',...textOnly?{}:{node_ref:'node/qa-source'},shots}]}},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>!busy.checked}),trace={id:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)};session.chat.messages.push(trace);await save();render();}catch(e){status.textContent=e.message;}}
document.getElementById('open').onclick=()=>open();document.getElementById('text').onclick=()=>open(true);document.getElementById('rerender').onclick=render;busy.onchange=render;
document.getElementById('verify').onclick=async()=>{try{const saved=await read('sessions','current');reply.value=JSON.stringify({saved,live_graph_matches_commit:JSON.stringify(saved.graph)===JSON.stringify(session.graph)},null,2);status.textContent='实际 IndexedDB 会话、编辑、输入与任务回执已事务回读。非 AI fixture 未作为成功生成证据。';}catch(e){status.textContent=e.message;}};
document.getElementById('undo').onclick=async()=>{const g=session.undo.pop();if(!g){status.textContent='没有本地操作可撤销';return;}session.graph=g;await save();await show();status.textContent='已撤销并保存真实图操作；景别回执不会重建已撤销结果。';};
window.addEventListener('pagehide',()=>{controller.reset();for(const url of assetUrls.values())URL.revokeObjectURL(url);database?.close();});
try{await openDatabase();const saved=await read('sessions','current');if(saved)session=saved;render();for(const id of ['open','text','rerender','verify','undo','busy','fail'])document.getElementById(id).disabled=false;}catch(e){status.textContent='验收未就绪：'+e.message;}
