import {createAppController,prepareApp} from '../integration.mjs';
import {animaticV1Uri} from '../animatic-v1.mjs';
import {createAnimaticV1Runtime} from '../animatic-v1-runtime.mjs';
import {createTemplateQaChatStore} from './template-source-chat-store.mjs';
import {animaticV1QaRawArgs,animaticV1QaSavedSummary} from './animatic-v1-input.mjs';
const $=id=>document.getElementById(id),store=createTemplateQaChatStore({name:'tapnow-animatic-v1-history-qa-v1',label:'历史动态分镜验收'});
let chat,trace,streaming=false,failSave=false,pageLeaving=false;
function fixture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=900;const x=canvas.getContext('2d'),colors=['#b89b65','#678e80','#d1886b','#9e7a94','#7395a6','#c0b370','#64877e','#a68272','#90a576'];for(let i=0;i<9;i++){const left=i%3*300,top=Math.floor(i/3)*300;x.fillStyle=colors[i];x.fillRect(left,top,300,300);x.fillStyle='#222';x.fillRect(left+85,top+130,130,100);x.beginPath();x.arc(left+150,top+85,35,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='18px system-ui';x.fillText('NON AI QA CELL '+i,left+32,top+270);}return canvas.toDataURL('image/png');}
const runtime=createAnimaticV1Runtime({app:{getState:()=>chat.qaGraph},localAssets:{url:async()=>{throw Error('此验收页未使用asset引用');}},getProjectId:()=> 'qa-animatic-v1-history-project'}),persist=()=>store.save(chat);
function report(error){$('receipt').textContent=JSON.stringify({error,source_uri:trace?.result.resource_uri,saved_state:trace?.appState,confirmed_handoffs:trace?.appHandoffs||[],saved_queue:chat?.queuedMessages||[]},null,2);}
const current=(response,record,owner)=>()=>!pageLeaving&&owner===chat&&chat.messages.includes(record)&&record.status==='done'&&record.result.response===response;
const controller=createAppController({getContext:()=>({chat,panelActive:!pageLeaving,pageLeaving,streaming}),getAnimaticV1SourceContext:(response,record,owner)=>runtime.capture(response,{trace:record,chat:owner,isCurrent:current(response,record,owner)}),onSaveState:async(owner,record,state)=>{
 if(failSave)throw Error('模拟：历史动态分镜状态事务保存失败');if(owner!==chat||pageLeaving)throw Error('会话已切换');const previous=record.appState;record.appState=state;try{await persist();report();return true;}catch(error){if(record.appState===state){if(previous===undefined)delete record.appState;else record.appState=previous;}throw error;}
},onQueuePrompt:async(text,record,owner,metadata,isCurrent,validate)=>{
 if(owner!==chat||!isCurrent()||streaming||failSave)return false;if(metadata.handoffId&&record.appHandoffs?.includes(metadata.handoffId))return true;
 const previousQueue=chat.queuedMessages,previousHandoffs=record.appHandoffs,queue=[...(previousQueue||[]),{id:crypto.randomUUID(),text,widgetOrigin:{traceId:record.id,callId:record.callId,resourceUri:record.result.resource_uri,...metadata}}],handoffs=metadata.handoffId?[...(previousHandoffs||[]),metadata.handoffId]:previousHandoffs;chat.queuedMessages=queue;if(metadata.handoffId)record.appHandoffs=handoffs;
 try{await persist();await validate?.();if(!isCurrent()||streaming||pageLeaving)throw Error('交接保存期间来源已变化');report();return true;}catch(error){if(chat.queuedMessages===queue)chat.queuedMessages=previousQueue;if(record.appHandoffs===handoffs){if(previousHandoffs===undefined)delete record.appHandoffs;else record.appHandoffs=previousHandoffs;}await persist();report(error.message);return false;}
},onError:report});
function render(){if(trace)$('card').replaceChildren(controller.render(trace));}
try{
 chat=await store.load()||{id:'qa-animatic-v1-history-chat',messages:[],queuedMessages:[]};if(!chat.qaGraph){const input=fixture();chat.qaGraph={nodes:[{id:'qa-source',type:'image',title:'非 AI QA 九格源图',image:input,fullImage:input,x:0,y:0,width:375,height:375}],edges:[]};await persist();}
 $('source').src=chat.qaGraph.nodes[0].fullImage;trace=chat.messages.filter(item=>item.name==='show_app').at(-1);
 $('input').value=JSON.stringify(trace?animaticV1QaRawArgs(trace).data:{version:1,locale:'zh-CN',sheets:[{sheet_id:'board-1',label:'明确非 AI 的 QA 故事板',node_ref:'node/qa-source',shots:[{shot_code:'SH1',cell:0,duration:2,move:'static',size:'MS',script_text:'发现信封'},{shot_code:'SH2',cell:1,duration:3,move:'push_in',size:'CU',transition:'dissolve',script_text:'打开信封'},{shot_code:'SH3',cell:2,duration:2,move:'pan_left',size:'LS',script_text:'转向窗外'}]}]},null,2);
 $('open').onclick=async()=>{if(streaming||pageLeaving)return;const button=$('open');button.disabled=true;try{const qaRawArgs={resource_uri:animaticV1Uri,title:'历史动态分镜 v1 验收',data:JSON.parse($('input').value)},args=await runtime.prepareAppArgs(qaRawArgs,{isCurrent:()=>!pageLeaving&&!streaming}),result=runtime.bindPreparedResult(prepareApp(args),args),id=crypto.randomUUID(),next={id,callId:'animatic_v1_qa_'+id,role:'tool',name:'show_app',status:'done',args:structuredClone(qaRawArgs),qaRawArgs:structuredClone(qaRawArgs),result},previous=trace;chat.messages.push(next);try{if(failSave)throw Error('模拟：打开历史动态分镜保存失败');await persist();if(pageLeaving)throw Error('验收页已关闭');}catch(error){chat.messages=chat.messages.filter(item=>item!==next);trace=previous;await persist();throw error;}trace=next;render();report();}catch(error){report(error.message);}finally{button.disabled=false;}};
 $('busy').onclick=()=>{streaming=!streaming;$('busy').textContent='运行状态：'+(streaming?'运行中':'空闲');render();report();};$('fail').onclick=()=>{failSave=!failSave;$('fail').textContent='保存状态：'+(failSave?'失败':'正常');report();};$('verify').onclick=async()=>{const saved=await store.load();$('receipt').textContent=JSON.stringify({transaction_readback:animaticV1QaSavedSummary(saved),saved_matches_live:JSON.stringify(saved)===JSON.stringify(chat)},null,2);};for(const id of ['open','busy','fail','verify'])$(id).disabled=false;render();report();
}catch(error){report(error.message);}
window.addEventListener('pagehide',()=>{pageLeaving=true;controller.reset();store.close();});
