import {createAppController,prepareApp} from '../integration.mjs';
import {colorAdjustUri} from '../color-adjust.mjs';
import {createColorAdjustRuntime} from '../color-adjust-runtime.mjs';
const $=id=>document.getElementById(id),requestedSession=new URL(location.href).searchParams.get('session');
if(requestedSession!==null&&!/^[A-Za-z0-9_-]{1,64}$/.test(requestedSession))throw Error('验收session须为1–64位字母、数字、下划线或连字符');
const databaseName='tapnow-qa-color-adjust-v2'+(requestedSession?'-'+requestedSession:'');
const status=document.getElementById('status'),cards=document.getElementById('cards'),reply=document.getElementById('reply'),nodes=document.getElementById('nodes'),busy=document.getElementById('busy'),fail=document.getElementById('fail');
function fixture(){const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const ctx=canvas.getContext('2d');ctx.fillStyle='#d5cbb4';ctx.fillRect(0,0,960,540);ctx.fillStyle='#41584b';ctx.fillRect(96,144,330,312);ctx.fillStyle='#ab573b';ctx.beginPath();ctx.arc(705,282,144,0,2*Math.PI);ctx.fill();ctx.fillStyle='#222';ctx.font='30px sans-serif';ctx.fillText('QA COLOR INPUT — 960 × 540',48,72);return canvas.toDataURL('image/png');}
let database,panelClosed=false,stateSaves=0,pendingStateSaves=0,session={chat:{id:'qa-color-adjust-chat',messages:[],replies:[]},graph:{nodes:[{id:'qa-source',type:'image',title:'QA 调色真实输入',image:fixture(),fullImage:fixture(),x:0,y:0,width:320,height:180,pixelWidth:960,pixelHeight:540}],edges:[]}};
async function openDatabase(){database=await new Promise((resolve,reject)=>{const r=indexedDB.open(databaseName,1);r.onupgradeneeded=()=>{r.result.createObjectStore('sessions');r.result.createObjectStore('assets');};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('验收存储被旧页阻塞'));});}
function read(store,key){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),r=tx.objectStore(store).get(key);tx.oncomplete=()=>resolve(r.result);tx.onerror=tx.onabort=()=>reject(tx.error||r.error||Error('事务回读失败'));});}
function write(store,key,value){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error||Error('事务提交失败'));});}
const save=()=>write('sessions','current',structuredClone(session));
const assetUrls=new Map(),localAssets={async put(blob){const id='asset:'+crypto.randomUUID();await write('assets',id,blob);return id;},async url(id){if(id.startsWith('data:image/'))return id;if(assetUrls.has(id))return assetUrls.get(id);const blob=await read('assets',id);if(!(blob instanceof Blob))throw Error('真实调色PNG未保存');const url=URL.createObjectURL(blob);assetUrls.set(id,url);return url;}};
const runtime=createColorAdjustRuntime({app:{getState:()=>session.graph,createConnected:(sourceId,patches)=>patches.map(p=>{const source=session.graph.nodes.find(n=>n.id===sourceId);if(!source)throw Error('源图已失效');const node={...p,id:crypto.randomUUID(),x:source.x+400,y:source.y};session.graph.nodes.push(node);session.graph.edges.push({id:crypto.randomUUID(),source:sourceId,target:node.id});return node;})},localAssets,store:{save:async()=>{if(fail.checked)return false;await save();return true;},flush:async()=>{}},getProjectId:()=> 'qa-color-adjust-project',persistConversation:save});
async function show(){nodes.replaceChildren();for(const node of session.graph.nodes){const fig=document.createElement('figure'),img=document.createElement('img'),cap=document.createElement('figcaption');img.src=await localAssets.url(node.fullImage||node.image);img.width=300;img.alt=node.title;cap.textContent='node/'+node.id+'\n'+(node.provenance?.receipt?JSON.stringify(node.provenance.receipt):'960×540 真实 QA 源图');fig.append(img,cap);nodes.append(fig);}reply.value=JSON.stringify({receipts:session.chat.messages.map(t=>t.colorAdjustReceipt).filter(Boolean),contexts:session.chat.messages.map(t=>t.colorAdjustContext).filter(Boolean),replies:session.chat.replies},null,2);status.textContent=`官方页 ${session.chat.messages.length}；已保存调色回执 ${session.chat.messages.filter(t=>t.colorAdjustReceipt).length}；当前真实图节点 ${session.graph.nodes.length}；实际跳过队列 ${session.chat.replies.length}。未调用模型。`;}
const controller=createAppController({getContext:()=>({chat:session.chat,panelActive:!panelClosed,pageLeaving:false,streaming:busy.checked}),getColorAdjustSourceContext:(data,trace,chat)=>runtime.capture(data,{trace,chat,isCurrent:()=>chat===session.chat&&chat.messages.includes(trace)&&!busy.checked}),onApplyColorAdjust:async(args,trace,chat,options)=>{const receipt=await runtime.apply(args,trace,chat,options);await show();return receipt;},onColorAdjustContext:async(value,trace,chat,options)=>{if($('fail-context-once').checked){$('fail-context-once').checked=false;throw Error('模拟：调色上下文单次保存失败');}const result=await runtime.setModelContext(value,trace,chat,options);await show();return result;},onSaveState:async(chat,trace,state)=>{pendingStateSaves++;$('saving').textContent=`等待状态保存回执 ${pendingStateSaves}；实际成功事务 ${stateSaves}`;try{const delay=Math.min(10000,Math.max(0,Number($('save-delay').value)||0));if(delay)await new Promise(resolve=>setTimeout(resolve,delay));if($('fail-save-once').checked){$('fail-save-once').checked=false;throw Error('模拟：调色参数单次保存失败');}const old=trace.appState;trace.appState=state;try{await save();stateSaves++;$('state').value=JSON.stringify(session.chat.messages.map(t=>({trace_id:t.id,state:t.appState})),null,2);}catch(error){trace.appState=old;throw error;}}finally{pendingStateSaves--;$('saving').textContent=`等待状态保存回执 ${pendingStateSaves}；实际成功事务 ${stateSaves}`;}},onQueuePrompt:async(text,trace,chat,metadata,isCurrent=()=>true)=>{if(busy.checked||!isCurrent())return false;if(chat.replies.some(r=>r.traceId===trace.id&&r.handoffId===metadata?.handoffId))return true;const old=chat.replies,entry={traceId:trace.id,...metadata,text};chat.replies=[...old,entry];let committed=false;try{await save();committed=true;if(busy.checked||!isCurrent())throw Error('保存期间调色跳过来源变化');}catch(error){chat.replies=old;if(committed)await save();throw error;}await show();return true;},onError:message=>status.textContent=message});
function render(){controller.prune(session.chat.messages);if(!panelClosed)for(const trace of session.chat.messages){const el=controller.render(trace);if(el&&el.parentElement!==cards)cards.append(el);}show().catch(e=>status.textContent=e.message);}
document.getElementById('open').onclick=async()=>{const button=document.getElementById('open');button.disabled=true;try{const args={resource_uri:colorAdjustUri,title:'QA 官方调色',data:{node_ref:'node/qa-source',locale:'zh-CN',suggested:{temperature:12,tint:-4,exposure:8}}},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>!busy.checked}),trace={id:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)},old=session.chat.messages;session.chat.messages=[...old,trace];try{await save();}catch(e){session.chat.messages=old;throw e;}panelClosed=false;render();}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
document.getElementById('verify').onclick=async()=>{try{const saved=await read('sessions','current');if(!saved)throw Error('验收库尚无提交');$('state').value=JSON.stringify(saved.chat.messages.map(t=>({trace_id:t.id,state:t.appState})),null,2);const receipts=saved.chat.messages.flatMap(t=>t.colorAdjustReceipt?[t.colorAdjustReceipt]:[]),evidence=[];for(const receipt of receipts){const node=saved.graph.nodes.find(n=>n.id===receipt.node_id);if(!node||node.fullImage!==node.provenance?.outputMedia||JSON.stringify(node.provenance.receipt)!==JSON.stringify(receipt))throw Error('持久节点与实际回执不符');const blob=await read('assets',node.fullImage);if(!(blob instanceof Blob))throw Error('实际PNG不存在');const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join('');if(sha256!==receipt.output_sha256)throw Error('已保存图片字节哈希不一致');const image=new Image();image.src=await localAssets.url(node.fullImage);await image.decode();if(image.naturalWidth!==receipt.width||image.naturalHeight!==receipt.height)throw Error('真实PNG解码尺寸不一致');evidence.push({node_id:node.id,png_bytes:blob.size,width:image.naturalWidth,height:image.naturalHeight,output_sha256:sha256,params:receipt.params});}reply.value=JSON.stringify({persisted_outputs:evidence,persisted_contexts:saved.chat.messages.map(t=>t.colorAdjustContext).filter(Boolean),skip_queue:saved.chat.replies,live_graph_matches_commit:JSON.stringify(saved.graph)===JSON.stringify(session.graph)},null,2);status.textContent='实际 PNG 字节、原图尺寸、节点和会话回执已完成事务回读核验。';}catch(e){status.textContent=e.message;}};
document.getElementById('rerender').onclick=render;busy.onchange=render;
$('close').onclick=async()=>{const button=$('close');button.disabled=true;try{await controller.prepareToClose();controller.reset();panelClosed=true;cards.replaceChildren();await show();status.textContent='最后参数已收到真实状态事务回执，页面已关闭；重新打开可继续编辑。';}catch(error){status.textContent='关闭保留在当前页：'+error.message;}finally{button.disabled=false;}};
$('reopen').onclick=()=>{panelClosed=false;render();};
$('upload').onchange=async()=>{const file=$('upload').files?.[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>16*1024*1024)throw Error('真实图片须为16MiB以内 PNG/JPEG/WebP');await controller.prepareToClose();const asset=await localAssets.put(file),image=new Image();image.src=await localAssets.url(asset);await image.decode();const old=session;session={chat:{id:'qa-color-adjust-chat-'+crypto.randomUUID(),messages:[],replies:[]},graph:{nodes:[{id:'qa-source',type:'image',title:file.name,image:asset,fullImage:asset,x:0,y:0,width:320,height:180,pixelWidth:image.naturalWidth,pixelHeight:image.naturalHeight}],edges:[]}};try{await save();}catch(error){session=old;throw error;}controller.reset();cards.replaceChildren();panelClosed=false;await show();status.textContent='真实本地图片已保存；打开官方调色页开始新来源验收。';}catch(error){controller.cancelClose();status.textContent=error.message;}finally{$('upload').value='';}};
window.colorAdjustQA={databaseName,snapshot:()=>structuredClone(session)};

window.addEventListener('pagehide',()=>{controller.reset();for(const url of assetUrls.values())URL.revokeObjectURL(url);database?.close();});
try{await openDatabase();const saved=await read('sessions','current');if(saved){if(!Array.isArray(saved.chat?.messages)||!Array.isArray(saved.chat?.replies)||!Array.isArray(saved.graph?.nodes)||!Array.isArray(saved.graph?.edges))throw Error('验收库数据无效');session=saved;}render();for(const id of ['open','rerender','verify','busy','fail','close','reopen','upload','save-delay','fail-save-once','fail-context-once'])document.getElementById(id).disabled=false;}catch(e){status.textContent='验收未就绪：'+e.message;}
