import {createAppController, prepareApp} from '../integration.mjs';
import {cutlistReviewUri, initialCutlistReviewState} from '../cutlist-review.mjs';
import {createCutlistReviewRuntime, createCutlistReviewExecutor} from '../cutlist-review-runtime.mjs';
import {openVideoFrames} from '../../video-media/frames.mjs';
const status=document.getElementById('status'),cards=document.getElementById('cards'),reply=document.getElementById('reply'),busy=document.getElementById('busy'),outputs=document.getElementById('outputs'),failSave=document.getElementById('fail-save');
let database,chat={id:'qa-cutlist-review-chat',messages:[],replies:[]},graph={nodes:[],edges:[]},saving=false,queueSaving=false,executing=false,pageLeaving=false,lastOperation=null,panelOpen=true,closing=false,savePending=0,saveCount=0;
function databaseName(){const session=new URLSearchParams(location.search).get('session');if(session===null)return 'tapnow-qa-cutlist-review-v1';if(!/^[A-Za-z0-9-]{1,48}$/.test(session))throw Error('验收session须为1–48个字母、数字或连字符');return 'tapnow-qa-cutlist-review-v1-'+session;}
async function openDatabase(){database=await new Promise((resolve,reject)=>{const request=indexedDB.open(databaseName(),1);request.onupgradeneeded=()=>{request.result.createObjectStore('sessions');request.result.createObjectStore('assets');};request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('专用验收存储被旧页面阻塞'));});}
function read(store,key){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),request=tx.objectStore(store).get(key);tx.oncomplete=()=>resolve(request.result);tx.onerror=tx.onabort=()=>reject(tx.error||request.error||Error('验收读取失败'));});}
function write(store,key,value){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error||Error('验收事务保存失败'));});}
const save=()=>write('sessions','current',structuredClone({chat,graph})),assetUrls=new Map();
const localAssets={async put(blob){const id='asset:'+crypto.randomUUID();await write('assets',id,blob);return id;},async url(id){if(assetUrls.has(id))return assetUrls.get(id);const blob=await read('assets',id);if(!(blob instanceof Blob))throw Error('真实验收素材不存在');const url=URL.createObjectURL(blob);assetUrls.set(id,url);return url;}};
const app={getState:()=>graph,createConnected:(sourceId,patches)=>{if(!graph.nodes.some(node=>node.id===sourceId))throw Error('验收来源已变化');const added=patches.map(patch=>({...patch,id:crypto.randomUUID()}));graph.nodes.push(...added);graph.edges.push(...added.map(node=>({id:crypto.randomUUID(),source:sourceId,target:node.id})));return added;}};
const runtime=createCutlistReviewRuntime({app,localAssets,getProjectId:()=> 'qa-cutlist-review-project'}),executor=createCutlistReviewExecutor({app,localAssets,store:{save,flush:async()=>{}}});
function showReplies(){document.getElementById('state').value=chat.messages.map(trace=>JSON.stringify({traceId:trace.id,state:trace.appState},null,2)).join('\n');reply.value=chat.replies.map(item=>item.text).join('\n\n');status.textContent=`已保存${chat.messages.length}个审阅页；状态待完成${savePending}，本页状态提交${saveCount}；普通队列${chat.replies.length}次；拼装产物${graph.nodes.filter(node=>node.provenance?.kind==='cutlist-local-assembly').length}份。未调用模型。`;document.getElementById('assemble').disabled=!chat.replies.some(item=>item.handoffId?.startsWith('cutlist_'))||busy.checked||executing;}
const current=(trace,currentChat)=>()=>!pageLeaving&&chat===currentChat&&chat.messages.includes(trace);
const controller=createAppController({getContext:()=>({chat,panelActive:panelOpen,pageLeaving,streaming:busy.checked}),getCutlistSourceContext:(response,trace,currentChat)=>runtime.capture(response,{trace,chat:currentChat,isCurrent:current(trace,currentChat)}),
 onSaveState:async(currentChat,trace,state)=>{if(saving||queueSaving||executing)throw Error('验收正在保存或本地执行，请稍后');saving=true;savePending++;showReplies();let previous,assigned=false;try{const delay=Math.max(0,Math.min(7000,Number(document.getElementById('save-delay').value)||0));if(delay)await new Promise(resolve=>setTimeout(resolve,delay));if(failSave.checked)throw Error('模拟：拼装计划状态事务保存失败');previous=trace.appState;trace.appState=state;assigned=true;await save();saveCount++;}catch(error){if(assigned)trace.appState=previous;throw error;}finally{saving=false;savePending--;showReplies();}},
 onQueuePrompt:async(text,trace,currentChat,metadata,isSourceCurrent=()=>true)=>{if(busy.checked||saving||queueSaving||executing||!isSourceCurrent())return false;if(metadata?.handoffId&&chat.replies.some(item=>item.traceId===trace.id&&item.handoffId===metadata.handoffId))return true;
  const previous=chat.replies,entry={traceId:trace.id,...metadata,text,state:structuredClone(trace.appState)},next=[...previous,entry];chat.replies=next;queueSaving=true;let committed=false;
  try{await save();committed=true;if(!isSourceCurrent()||busy.checked)throw Error('保存交接期间审阅来源已切换');}catch(error){chat.replies=chat.replies===next?previous:chat.replies.filter(item=>item!==entry);if(committed)await save();throw error;}finally{queueSaving=false;}showReplies();return true;},onError:message=>{status.textContent=message;}});
function render(){controller.prune(chat.messages);if(!panelOpen){cards.replaceChildren();showReplies();return;}for(const trace of chat.messages){const element=controller.render(trace);if(element&&element.parentElement!==cards)cards.append(element);}showReplies();}
async function showOutputs(){outputs.replaceChildren();const receipts=[];for(const node of graph.nodes.filter(node=>node.provenance?.kind==='cutlist-local-assembly')){const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src=await localAssets.url(node.video);outputs.append(video);receipts.push({nodeId:node.id,operationId:node.provenance.operationId,duration:node.duration,mediaSha256:node.provenance.mediaSha256,width:node.videoMetadata.width,height:node.videoMetadata.height});}document.getElementById('receipts').textContent=JSON.stringify(receipts,null,2);}
document.getElementById('fixture').onclick=async()=>{const button=document.getElementById('fixture');button.disabled=true;try{if(busy.checked||executing)throw Error('验收正在运行');const res=await fetch('/qa/trim-scenes.mp4');if(!res.ok)throw Error('真实本地QA视频读取失败');const blob=await res.blob(),url=URL.createObjectURL(blob);let actual;try{const frames=await openVideoFrames(url);try{await frames.at(0,320);actual={duration:frames.duration,width:frames.width,height:frames.height};}finally{frames.dispose();}}finally{URL.revokeObjectURL(url);}const asset=await localAssets.put(blob),duration=Math.round(actual.duration*1000),ids=['qa-cutlist-a-'+crypto.randomUUID(),'qa-cutlist-b-'+crypto.randomUUID()];for(const id of ids)graph.nodes.push({id,type:'video',video:asset,title:'QA真实视频来源',videoMetadata:actual,width:320,height:180});await save();document.getElementById('input').value=JSON.stringify({locale:'zh-CN',ratio:'16:9',target_duration_s:6,notes:'QA实际8秒视频的前后区间；审核没有生成授权。',shots:ids.map((id,index)=>({id,label:index?'后段来源':'前段来源',media_duration_ms:duration,in_ms:index?4000:0,out_ms:index?7000:3000,default_keep:true,trim_reason:'本地确定性验收建议'}))},null,2);status.textContent=`真实MP4已保存到隔离素材库：${actual.width}×${actual.height} / ${actual.duration}s。可以打开官方审阅。`;}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
document.getElementById('open').onclick=async()=>{const button=document.getElementById('open');button.disabled=true;try{if(executing)throw Error('正在本地拼装');const args={resource_uri:cutlistReviewUri,title:'真实来源拼装审阅',data:JSON.parse(document.getElementById('input').value)},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>!pageLeaving&&!busy.checked}),trace={id:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)},previous=chat.messages;chat.messages=[...previous,trace];try{await save();}catch(error){chat.messages=previous;throw error;}panelOpen=true;render();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
document.getElementById('assemble').onclick=async()=>{const entry=chat.replies.filter(item=>item.handoffId?.startsWith('cutlist_')).at(-1),trace=chat.messages.find(trace=>trace.id===entry?.traceId);if(!trace)return;executing=true;showReplies();let context;try{if(busy.checked||saving||queueSaving)throw Error('验收正在运行或保存');context=runtime.capture(trace.result.response,{trace,chat,isCurrent:current(trace,chat)});lastOperation='qa-assembly-'+entry.handoffId.slice(8);const original=entry.text.split('\n\n')[0],receipt=await executor.execute({operationId:lastOperation,message:original,response:trace.result.response,state:entry.state,authorization:{kind:'local_cutlist_assembly',handoffId:entry.handoffId}},{sourceContext:context});await showOutputs();status.textContent=JSON.stringify(receipt);document.getElementById('retry').disabled=true;}catch(error){status.textContent=error.message;document.getElementById('retry').disabled=error.applied!==true;}finally{context?.dispose();executing=false;document.getElementById('assemble').disabled=false;}};
document.getElementById('retry').onclick=async()=>{try{const receipt=await executor.retrySave(lastOperation);await showOutputs();status.textContent=JSON.stringify(receipt);document.getElementById('retry').disabled=true;}catch(error){status.textContent=error.message;}};
document.getElementById('rerender').onclick=render;busy.onchange=render;
document.getElementById('close').onclick=async()=>{if(closing||executing)return;closing=true;for(const id of ['close','reopen','open','fixture'])document.getElementById(id).disabled=true;try{await controller.prepareToClose();panelOpen=false;render();}catch(error){status.textContent=error.message+'；审阅页已保留，可再次关闭重试';}finally{controller.cancelClose();closing=false;for(const id of ['close','reopen','open','fixture'])document.getElementById(id).disabled=false;}};
document.getElementById('reopen').onclick=()=>{if(closing)return;panelOpen=true;render();};
window.cutlistReviewQA={snapshot:()=>structuredClone({chat,graph,panelOpen,savePending,saveCount})};
window.addEventListener('pagehide',()=>{pageLeaving=true;controller.reset();for(const url of assetUrls.values())URL.revokeObjectURL(url);database?.close();});
try{await openDatabase();const stored=await read('sessions','current');if(stored){if(!stored.chat?.id||!Array.isArray(stored.chat.messages)||!Array.isArray(stored.chat.replies)||!Array.isArray(stored.graph?.nodes)||!Array.isArray(stored.graph.edges))throw Error('验收存储无效');chat=stored.chat;graph=stored.graph;}render();await showOutputs();for(const id of ['fixture','open','rerender','busy','fail-save','save-delay','close','reopen'])document.getElementById(id).disabled=false;}catch(error){status.textContent='验收页未就绪：'+error.message;}
