import {createAppController, prepareApp} from '../integration.mjs';
import {libraryPickerUri, initialLibraryPickerState} from '../library-picker.mjs';
import {createLibraryPickerRuntime} from '../library-picker-runtime.mjs';
const status=document.getElementById('status'),cards=document.getElementById('cards'),reply=document.getElementById('reply'),nodes=document.getElementById('nodes'),busy=document.getElementById('busy'),fail=document.getElementById('fail');
function fixtureImage() {const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const ctx=canvas.getContext('2d');ctx.fillStyle='#d5cbb4';ctx.fillRect(0,0,320,180);ctx.fillStyle='#41584b';ctx.fillRect(32,48,110,104);ctx.fillStyle='#ab573b';ctx.beginPath();ctx.arc(235,94,48,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';ctx.font='14px sans-serif';ctx.fillText('QA LIBRARY INPUT FIXTURE',16,24);return canvas.toDataURL('image/png');}
let database,session={chat:{id:'qa-library-chat',messages:[],replies:[]},graph:{nodes:[],edges:[]},library:{items:[{id:'qa-library-image',type:'image',name:'QA 构图参考',folder:'QA 测试文件夹',image:fixtureImage()}],folders:['QA 测试文件夹']}};
async function openDatabase(){database=await new Promise((resolve,reject)=>{const request=indexedDB.open('tapnow-qa-library-picker-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('sessions');request.onsuccess=()=>{request.result.onversionchange=()=>request.result.close();resolve(request.result);};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(Error('验收存储被旧页面阻塞'));});}
function read(){return new Promise((resolve,reject)=>{const tx=database.transaction('sessions','readonly'),request=tx.objectStore('sessions').get('current');tx.oncomplete=()=>resolve(request.result);tx.onerror=tx.onabort=()=>reject(tx.error||request.error||Error('验收事务回读失败'));});}
function save(){const snapshot=structuredClone(session);return new Promise((resolve,reject)=>{const tx=database.transaction('sessions','readwrite');tx.objectStore('sessions').put(snapshot,'current');tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(tx.error||Error('验收事务保存失败'));});}
const library={get items(){return session.library.items;},get folders(){return session.library.folders;}};
const runtime=createLibraryPickerRuntime({library,app:{getState:()=>session.graph,insertAsset:asset=>{const node={...structuredClone(asset),id:crypto.randomUUID(),title:asset.name,x:session.graph.nodes.length*360,y:0,width:320,height:180};session.graph.nodes.push(node);return node;}},store:{save:async()=>{if(fail.checked)return false;await save();return true;},flush:async()=>{}},getProjectId:()=> 'qa-library-project',persistConversation:save});
function show(){reply.value=session.chat.replies.map(item=>item.text).join('\n\n');nodes.replaceChildren();for(const node of session.graph.nodes){const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption');image.src=node.fullImage||node.image;image.width=240;image.alt='实际保存的 QA 库图片';caption.textContent='node/'+node.id+'\n'+JSON.stringify(node.provenance);figure.append(image,caption);nodes.append(figure);}status.textContent=`官方页 ${session.chat.messages.length}；实际引用队列 ${session.chat.replies.length}；当前图节点 ${session.graph.nodes.length}。未调用模型。`;}
const controller=createAppController({getContext:()=>({chat:session.chat,panelActive:true,pageLeaving:false,streaming:busy.checked}),getLibrarySourceContext:(response,trace,chat)=>runtime.capture(response,{trace,chat,isCurrent:()=>chat===session.chat&&chat.messages.includes(trace)&&!busy.checked}),onSaveState:async(chat,trace,state)=>{const previous=trace.appState;trace.appState=state;try{await save();}catch(error){trace.appState=previous;throw error;}},onLibraryAddToCanvas:async(args,trace,chat,options)=>{const receipt=await options.sourceContext.addToCanvas(args,options);show();return receipt;},onQueuePrompt:async(text,trace,chat,metadata,isCurrent=()=>true)=>{
 if(busy.checked||!isCurrent())return false;if(metadata.handoffId&&chat.replies.some(item=>item.traceId===trace.id&&item.handoffId===metadata.handoffId))return true;
 const previous=chat.replies,entry={traceId:trace.id,...metadata,text};chat.replies=[...previous,entry];let committed=false;
 try{await save();committed=true;if(busy.checked||!isCurrent())throw Error('保存期间素材引用来源已变化');}catch(error){chat.replies=previous;if(committed)await save();throw error;}show();return true;
},onError:message=>{status.textContent=message;}});
function render(){controller.prune(session.chat.messages);for(const trace of session.chat.messages){const element=controller.render(trace);if(element&&element.parentElement!==cards)cards.append(element);}show();}
document.getElementById('open').onclick=async()=>{const button=document.getElementById('open');button.disabled=true;try{const args={resource_uri:libraryPickerUri,title:'QA 个人素材库',data:{}},prepared=await runtime.prepareAppArgs(args,{isCurrent:()=>!busy.checked}),trace={id:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)};trace.appState=initialLibraryPickerState(trace.result.response);const previous=session.chat.messages;session.chat.messages=[...previous,trace];try{await save();}catch(error){session.chat.messages=previous;throw error;}render();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
document.getElementById('rerender').onclick=render;busy.onchange=render;
document.getElementById('verify').onclick=async()=>{try{const stored=await read();if(!stored)throw Error('验收库尚无提交');const identities=stored.graph.nodes.map(node=>({node_ref:'node/'+node.id,asset_id:node.provenance?.asset_id,actual_media_equals_fixture:node.fullImage===stored.library.items[0].image})),receipts=stored.chat.messages.flatMap(trace=>trace.libraryPickerPlacements||[]);if(identities.some(item=>!item.actual_media_equals_fixture)||receipts.some(receipt=>!identities.some(node=>node.node_ref===receipt.node_ref)))throw Error('回读节点来源与已保存回执不一致');const evidence={persisted_nodes:identities,persisted_receipts:receipts,persisted_replies:stored.chat.replies.length,live_graph_matches_commit:JSON.stringify(stored.graph)===JSON.stringify(session.graph)};reply.value=JSON.stringify(evidence,null,2)+'\n\n'+stored.chat.replies.map(item=>item.text).join('\n\n');status.textContent='专用 IndexedDB 已完成真实事务回读；结果见证据。';}catch(error){status.textContent=error.message;}};
window.addEventListener('pagehide',()=>{controller.reset();database?.close();});
try{await openDatabase();const stored=await read();if(stored){if(!Array.isArray(stored.chat?.messages)||!Array.isArray(stored.chat.replies)||!Array.isArray(stored.graph?.nodes)||!Array.isArray(stored.library?.items)||!Array.isArray(stored.library.folders))throw Error('专用验收数据无效');session=stored;}render();for(const id of ['open','rerender','verify','busy','fail'])document.getElementById(id).disabled=false;}catch(error){status.textContent='验收页未就绪：'+error.message;}
