import {createAppController,prepareApp} from '../integration.mjs';
import {previsUri,previsHash} from '../previs.mjs';
import {createPrevisRuntime} from '../previs-runtime.mjs';
import {providerConfigured} from '../../node-composer/provider-configuration.mjs';
import {configurationBoundProvider} from '../../generation-config/client.mjs';
import {isGenerationMediaRef} from '../../generation-results/media-ref.mjs';
const $=id=>document.getElementById(id),urls=new Map();let database,session={chat:{id:'qa-previs-chat',messages:[]},graph:{nodes:[],edges:[]},queue:[],undo:[],requests:[]};
function read(store,key){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readonly'),request=tx.objectStore(store).get(key);tx.oncomplete=()=>resolve(request.result);tx.onerror=tx.onabort=()=>reject(tx.error||request.error);});}
function write(store,key,value){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.objectStore(store).put(value,key);tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error);});}
async function save(){if($('fail').checked)throw Error('模拟真实事务保存失败');await write('session','current',structuredClone(session));}
const localAssets={async put(blob){const ref='asset:'+crypto.randomUUID();await write('assets',ref,blob);return ref;},async url(ref){if(ref.startsWith('data:')||isGenerationMediaRef(ref))return ref;if(urls.has(ref))return urls.get(ref);const blob=await read('assets',ref);if(!(blob instanceof Blob))throw Error('实际素材不存在');const url=URL.createObjectURL(blob);urls.set(ref,url);return url;}};
function inputImage(){const canvas=document.createElement('canvas');canvas.width=960;canvas.height=540;const ctx=canvas.getContext('2d');for(let i=0;i<9;i++){const x=i%3*320,y=Math.floor(i/3)*180;ctx.fillStyle=['#c4b99d','#acbdb4','#b7aaa1'][i%3];ctx.fillRect(x,y,320,180);ctx.fillStyle='#29392f';ctx.fillRect(x+30,y+110,260,50);ctx.fillStyle='#9c5938';ctx.beginPath();ctx.arc(x+100+i*10,y+75,24+i*2,0,2*Math.PI);ctx.fill();ctx.fillStyle='#222';ctx.font='16px sans-serif';ctx.fillText('QA INPUT · '+(i+1)+' · NOT GENERATED',x+12,y+25);}return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('QA源图编码失败')),'image/png'));}
const app={getState:()=>session.graph,createConnected(sourceId,patches){session.undo.push(structuredClone(session.graph));const source=session.graph.nodes.find(n=>n.id===sourceId);if(!source)throw Error('源图已失效');return patches.map(p=>{const node={...structuredClone(p),id:crypto.randomUUID(),x:source.x+400,y:source.y};session.graph.nodes.push(node);session.graph.edges.push({id:crypto.randomUUID(),source:sourceId,target:node.id});return node;});},addNode(type,_point,_image,title,patch){session.undo.push(structuredClone(session.graph));const node={...patch,type,title,id:crypto.randomUUID(),x:0,y:240};session.graph.nodes.push(node);return node;}};
const fetchTracked=async(url,options={})=>{if(typeof url==='string'&&url.includes('/api/generation/tasks')){session.requests.push({url:new URL(url,location.href).pathname,method:options.method||'GET',at:Date.now()});await save();}return fetch(url,options);},configIds=new WeakMap(),service=new GenerationCore.TaskService(),provider=configurationBoundProvider(GenerationCore.httpProvider,{baseUrl:new URL('/api/generation',location.href).href,getConfigurationId:signal=>configIds.get(signal),fetchImpl:fetchTracked});
provider.isConfigured=async({request,signal}={})=>{const response=await fetch('/api/generation/config',{signal,redirect:'error'});if(!response.ok)return false;const config=await response.json();if(signal&&config.configurationId)configIds.set(signal,config.configurationId);return providerConfigured(config,request);};service.setProvider(provider);
async function applyJob(job,{explicit=false}={}){if(job.recovered&&!explicit)return;if(job.applied||job.applying||job.status!=='succeeded')return;const target=session.graph.nodes.find(n=>n.id===job.request.nodeId),record=session.chat.messages.flatMap(t=>t.previsJobs||[]).find(r=>r.job_id===job.id);if(!record||target?.previsTask?.plan_id!==record.plan_id||target.previsTask.request_hash!==record.request_hash)throw Error('实际目标已撤销或修改，不能重建');if(job.outputs?.length!==1||job.outputs[0].type!=='image')throw Error('图板须为一个真实图片结果');job.applying=true;try{const media=job.outputs[0].fullImage||job.outputs[0].image||job.outputs[0].url;if(!isGenerationMediaRef(media))throw Error('本机生成结果尚未落盘');const response=await fetch(media,{redirect:'error',mode:'same-origin'}),blob=await response.blob();if(!response.ok||!blob.size)throw Error('真实生成媒体读取失败');const url=URL.createObjectURL(blob),image=new Image();try{image.src=url;await image.decode();if(!image.naturalWidth||!image.naturalHeight)throw Error('真实生成图板解码失败');if(!session.graph.nodes.includes(target))throw Error('原目标已撤销');session.undo.push(structuredClone(session.graph));target.image=target.fullImage=media;target.pixelWidth=image.naturalWidth;target.pixelHeight=image.naturalHeight;target.generation={jobId:job.id};await save();if(!session.graph.nodes.includes(target)||target.fullImage!==media)throw Error('保存期间结果已改变');job.resultIds=[target.id];job.applied=true;}finally{URL.revokeObjectURL(url);}}finally{job.applying=false;}await show();}
service.subscribe(job=>{if(job.status==='succeeded')applyJob(service.jobs.get(job.id)).catch(error=>$('status').textContent=error.message);show().catch(()=>{});});
const generationAPI={availability:async({request,signal})=>({configured:await provider.isConfigured({request,signal})}),submit:(request,options)=>service.submit(request,options),getJobs:()=>[...service.jobs.values()],recover:(id,options)=>service.recover(id,options)};
const runtime=createPrevisRuntime({app,localAssets,store:{save:async()=>{await save();return true;}},generationAPI,getProjectId:()=> 'qa-previs-project',persistConversation:save});
const getSource=(data,trace,chat)=>runtime.capture(data,{trace,chat,isCurrent:()=>chat===session.chat&&chat.messages.includes(trace)&&trace.result.response===data});
const controller=createAppController({getContext:()=>({chat:session.chat,panelActive:true,pageLeaving:false,streaming:$('busy').checked}),getGenerationAppSourceContext:getSource,onGenerationAppTool:async(name,args,trace,chat,opts)=>{const value=await(name==='previs_variants_submit'?opts.sourceContext.submitVariants(args,opts):opts.sourceContext.lookupVariants(args,opts));await show();return value.structuredContent??value;},onValidateAppReply:(details,_trace,_chat,opts)=>opts.sourceContext.preflightReply(details),onAppReply:async(details,trace,_chat,opts)=>{const prior=trace.appReplyReceipts?.find(r=>r.reply_id===details.reply_id);const resolved=await opts.sourceContext.resolveReply(details),fingerprint=await previsHash(details.payload);if(prior){if(prior.fingerprint!==fingerprint)throw Error('回复身份冲突');return {reply_id:details.reply_id,run_id:prior.run_id,deduped:true};}await opts.sourceContext.applyReply(details);const queued={id:crypto.randomUUID(),text:resolved.text,trace_id:trace.id,reply_id:details.reply_id,status:'waiting'},receipt={reply_id:details.reply_id,run_id:queued.id,fingerprint,status:'waiting'};session.queue.push(queued);trace.appReplyReceipts=[...(trace.appReplyReceipts||[]),receipt];const entry=trace.previsReplies.find(r=>r.reply_id===details.reply_id);entry.status='accepted';entry.run_id=queued.id;try{await save();await opts.sourceContext.validateSourcesCurrent();}catch(error){session.queue=session.queue.filter(q=>q!==queued);trace.appReplyReceipts=trace.appReplyReceipts.filter(r=>r!==receipt);entry.status='prepared';delete entry.run_id;await save();throw error;}await show();return {reply_id:details.reply_id,run_id:queued.id,deduped:false};},onAppReplyRunStatus:params=>({status:session.queue.some(q=>q.id===params.run_id)?'waiting':'unknown'}),onSaveState:async(_chat,trace,state)=>{const old=trace.appState;trace.appState=state;try{await save();}catch(error){trace.appState=old;throw error;}},onError:message=>$('status').textContent=message});
async function show(){const nodes=$('nodes');nodes.replaceChildren();for(const node of session.graph.nodes){const fig=document.createElement('figure'),cap=document.createElement('figcaption');if(node.fullImage||node.image){const image=document.createElement('img');image.src=await localAssets.url(node.fullImage||node.image);image.width=280;image.alt=node.title;fig.append(image);}cap.textContent=node.title+'\nnode/'+node.id+'\n'+(node.previsTask?'真实任务占位/结果：'+node.previsTask.plan_id:'本地QA真实输入');fig.append(cap);nodes.append(fig);}const jobs=generationAPI.getJobs().map(({controller,...job})=>({id:job.id,status:job.status,applied:job.applied,request:job.request,resultIds:job.resultIds,error:job.error}));$('evidence').value=JSON.stringify({saved_states:session.chat.messages.map(t=>({trace_id:t.id,state:t.appState,previsReplies:t.previsReplies,jobs:t.previsJobs})),real_waiting_queue:session.queue,actual_generation_jobs:jobs,requests:session.requests},null,2);$('status').textContent=`官方预演 ${session.chat.messages.length}；已保存待续消息 ${session.queue.length}（未执行Agent）；本次真实任务 ${jobs.length}；本机请求记录 POST ${session.requests.filter(r=>r.method==='POST').length} / GET ${session.requests.filter(r=>r.method==='GET').length}。`;}
async function restoreSelectedVariants(trace){const oldResult=trace.result,oldState=trace.appState,source=getSource(oldResult.response,trace,session.chat);try{const restored=await source.querySelectedVariants({recover:true});if(!restored.changed)return restored;source.guard();if(trace.result!==oldResult||trace.appState!==oldState)throw Error('选图恢复期间实际状态改变');const next={...oldResult,...restored.projection};trace.result=next;let committed=false;try{await save();committed=true;if(trace.result!==next||trace.appState!==oldState)throw Error('选图恢复保存期间实际状态改变');const verified=getSource(next.response,trace,session.chat);try{await verified.validateSourcesCurrent();}finally{verified.dispose();}return restored;}catch(error){if(trace.result===next)trace.result=oldResult;if(committed)await save();throw error;}}finally{source.dispose();}}
async function restoreAllSelectedVariants(){for(const trace of session.chat.messages)if(trace.previsJobs?.some(job=>job.kind==='variants'))await restoreSelectedVariants(trace);}
function render(){controller.prune(session.chat.messages);for(const trace of session.chat.messages){const element=controller.render(trace);if(element&&element.parentElement!==$('cards'))$('cards').append(element);}show().catch(error=>$('status').textContent=error.message);}
async function open(missing=false){const spec={aspect_ratio:'16:9',...$('model').value.trim()?{model:$('model').value.trim()}:{}},args={resource_uri:previsUri,title:missing?'QA 缺图板镜头计划':'QA 真实图板预演',data:{version:3,locale:'zh-CN',generation_spec:spec,sheets:[{sheet_id:'qa-board',...missing?{}:{sheet_node_ref:'node/qa-source'},shots:[{shot_code:'S1',cell:0,duration:3,move:'push_in',size:'MS',script_text:'人物观察前方，保持真实参考主体'},{shot_code:'S2',cell:1,duration:4,move:'pan_right',size:'CU',script_text:'近景转向物件',dialogue:{text:'看这里',est_duration:1.2}},{shot_code:'S3',cell:2,duration:3,move:'static',size:'LS',script_text:'人物完整站位'}]}]}};const prepared=await runtime.prepareAppArgs(args),trace={id:crypto.randomUUID(),callId:crypto.randomUUID(),name:'show_app',args,status:'done',result:runtime.bindPreparedResult(prepareApp(prepared),prepared)};session.chat.messages.push(trace);try{await save();}catch(error){session.chat.messages=session.chat.messages.filter(t=>t!==trace);throw error;}render();}
for(const [button,action]of Object.entries({open:()=>open(),missing:()=>open(true),refresh:async()=>{await restoreAllSelectedVariants();for(const trace of session.chat.messages){const source=getSource(trace.result.response,trace,session.chat),projection=await source.querySheets();if(projection.changed){const old=trace.result,next={...old,...projection.projection};trace.result=next;try{await save();}catch(error){trace.result=old;throw error;}}}render();},apply:async()=>{for(const job of service.jobs.values())if(job.recovered&&job.status==='succeeded'&&!job.applied)await applyJob(job,{explicit:true});await show();},generate:async()=>{const trace=[...session.chat.messages].reverse().find(t=>t.previsReplies?.some(r=>r.status==='accepted'));if(!trace)throw Error('请先在官方页确认镜头计划，等待真实消息保存');const entry=trace.previsReplies.at(-1),source=getSource(trace.result.response,trace,session.chat);await runtime.generateSheets({reply_id:entry.reply_id,shot_codes:entry.manifest.order},trace,session.chat,{userAction:true,isCurrent:()=>!$('busy').checked,sourceContext:source});await show();},undo:async()=>{const prior=session.undo.pop();if(!prior)throw Error('没有可撤销的结果');session.graph=prior;await save();render();},verify:async()=>{const saved=await read('session','current');$('evidence').value=JSON.stringify(saved,null,2);$('status').textContent='已真实回读独立IndexedDB；未清理已有记录。';}}))$(button).onclick=async()=>{try{await action();}catch(error){$('status').textContent=error.message;}};
$('busy').onchange=render;
window.addEventListener('pagehide',()=>{controller.reset();for(const url of urls.values())URL.revokeObjectURL(url);database?.close();});
try{database=await new Promise((resolve,reject)=>{const request=indexedDB.open('tapnow-qa-previs-v1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('session');request.result.createObjectStore('assets');};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});const saved=await read('session','current');if(saved)session=saved;else{const ref=await localAssets.put(await inputImage());session.graph.nodes.push({id:'qa-source',type:'image',title:'九格真实QA输入（非模型生成）',image:ref,fullImage:ref,x:0,y:0,width:360,height:203,pixelWidth:960,pixelHeight:540});await save();}await restoreAllSelectedVariants();render();for(const button of ['open','missing','refresh','apply','generate','undo','verify'])$(button).disabled=false;}catch(error){$('status').textContent='验收未就绪：'+error.message;}
