import {createAppController, prepareApp} from '../integration.mjs';
import {productKitUri} from '../product-kit.mjs';
import {createProductKitRuntime} from '../product-kit-runtime.mjs';
const $ = id => document.getElementById(id), status = $('status'), cards = $('cards'), busy = $('busy'), failSave = $('fail-save');
let database, session = {chat: {id: 'qa-product-kit-chat', messages: [], replies: []}, graph: {nodes: [], edges: []}};
const sample = {node_ref: 'node/qa-product', version: 1, locale: 'zh-CN', variant: 'full', product: {name: '', category: 'functional', price_band: 'mid'}, kit_version: 1, updated_at: new Date().toISOString().slice(0, 10), palette: [{role: 'scene', name: '暖灰', hex: '#D8D1C7', locked: false, alternatives: [{name: '砂岩', hex: '#C9B8A3'}]}, {role: 'product', name: '深灰', hex: '#242424', locked: false, alternatives: [{name: '铅灰', hex: '#414141'}]}, {role: 'information', name: '亚麻白', hex: '#EEE9DF', locked: false, alternatives: [{name: '纸白', hex: '#F5F2EA'}]}, {role: 'accent', name: '陶土橙', hex: '#B96F4A', locked: false, alternatives: [{name: '赭石', hex: '#9B5D3D'}]}], tones: {selected: [{word: '克制', physical: '大留白 · 文案极少'}], options: [{word: '克制', physical: '大留白 · 文案极少'}, {word: '精密', physical: '正视角 · 结构特写'}], max: 2}, look: {state: 'unlocked', sentence: 'Neutral lighting and measured negative space.'}, bans: {product: []}, copy: {language: {value: '中文', locked: true, source: '验收页本次创作设置'}, voice: {value: '克制直给', options: ['克制直给', '自然描述']}}, hypotheses: [], plan_attached: false, summary: '本地产品素材创作设置'};
$('input').value = JSON.stringify(sample, null, 2);
async function openDatabase() {database = await new Promise((resolve, reject) => {const r = indexedDB.open('tapnow-qa-product-kit-v1', 1);r.onupgradeneeded = () => {r.result.createObjectStore('sessions');r.result.createObjectStore('assets');};r.onsuccess = () => {r.result.onversionchange = () => r.result.close();resolve(r.result);};r.onerror = () => reject(r.error);r.onblocked = () => reject(Error('验收存储被旧页面阻塞'));});}
function read(store, key) {return new Promise((resolve, reject) => {const tx = database.transaction(store, 'readonly'), r = tx.objectStore(store).get(key);tx.oncomplete = () => resolve(r.result);tx.onerror = tx.onabort = () => reject(tx.error || r.error || Error('验收读取失败'));});}
function write(store, key, value) {return new Promise((resolve, reject) => {const tx = database.transaction(store, 'readwrite');tx.objectStore(store).put(value, key);tx.oncomplete = () => resolve();tx.onerror = tx.onabort = () => reject(tx.error || Error('验收事务提交失败'));});}
const save = () => write('sessions', 'current', structuredClone({...session, input: $('input').value})), urls = new Map();
const localAssets = {put: async blob => {const id = 'asset:' + crypto.randomUUID();await write('assets', id, blob);return id;}, url: async id => {if (!/^asset:/.test(id)) throw Error('验收只允许实际本地素材');if (urls.has(id)) return urls.get(id);const blob = await read('assets', id);if (!(blob instanceof Blob)) throw Error('产品图片未实际保存');const url = URL.createObjectURL(blob);urls.set(id, url);return url;}};
const runtime = createProductKitRuntime({app: {getState: () => session.graph}, localAssets, getProjectId: () => 'qa-product-kit-project'});
function show() {$('state').value = JSON.stringify(session.chat.messages.map(trace => ({trace_id: trace.id, state: trace.appState, source_sha256: trace.result.productKitSourceContext?.source_sha256})), null, 2);$('reply').value = JSON.stringify(session.chat.replies, null, 2);status.textContent = `真实图片${session.graph.nodes.length}张；官方素材板${session.chat.messages.length}个；持久队列${session.chat.replies.length}次。未调用模型或生成接口。`;}
async function showSource() {const node = session.graph.nodes[0];if (!node) {$('source').textContent = '尚未导入产品图片；本页不创建假产品来源。';return;}const image = document.createElement('img');image.src = await localAssets.url(node.fullImage);image.alt = node.title;const caption = document.createElement('p');caption.textContent = `${node.title} · node/${node.id}`;$('source').replaceChildren(image, caption);}
const controller = createAppController({getContext: () => ({chat: session.chat, panelActive: true, pageLeaving: false, streaming: busy.checked}), getProductKitSourceContext: (data, trace, chat) => runtime.capture(data, {trace, chat, isCurrent: () => chat === session.chat && chat.messages.includes(trace)}),
  onSaveState: async (chat, trace, state) => {if (failSave.checked) throw Error('模拟：Product Kit 状态事务保存失败');const previous = trace.appState;trace.appState = state;try {await save();show();} catch (error) {trace.appState = previous;throw error;}},
  onQueuePrompt: async (text, trace, chat, metadata, isCurrent = () => true, validateSource) => {if (busy.checked || failSave.checked || !isCurrent()) return false;await validateSource?.();if (chat.replies.some(item => item.traceId === trace.id && item.handoffId === metadata?.handoffId)) return true;const previous = chat.replies, entry = {traceId: trace.id, ...metadata, text}, next = [...previous, entry];chat.replies = next;let committed = false;try {await save();committed = true;await validateSource?.();if (busy.checked || failSave.checked || !isCurrent()) throw Error('保存期间 Product Kit 来源已变化');} catch (error) {chat.replies = chat.replies === next ? previous : chat.replies.filter(item => item !== entry);if (committed) await save();throw error;}show();return true;}, onError: message => {status.textContent = message;},
});
function render() {controller.prune(session.chat.messages);for (const trace of session.chat.messages) {const element = controller.render(trace);if (element && element.parentElement !== cards) cards.append(element);}show();}
$('upload').onchange = async () => {const file = $('upload').files?.[0];if (!file) return;try {if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 8 * 1024 * 1024) throw Error('导入真实图片须为8MiB以内 PNG/JPEG/WebP');const asset = await localAssets.put(file), previous = session.graph.nodes;session.graph.nodes = [{id: 'qa-product', type: 'image', title: file.name, image: asset, fullImage: asset, x: 0, y: 0, width: 320, height: 320}];const data = JSON.parse($('input').value);data.product.name = file.name.replace(/\.[^.]+$/, '').replace(/\s+/g, ' ').trim().slice(0, 20).trim() || '本地导入素材';$('input').value = JSON.stringify(data, null, 2);try {await save();} catch (error) {session.graph.nodes = previous;throw error;}await showSource();status.textContent = '真实产品图片已导入并保存；旧卡片来源失效。核对类别、价格带与创作设置后打开新素材板。';} catch (error) {status.textContent = error.message;}finally {$('upload').value = '';}};
$('open').onclick = async () => {const button = $('open');button.disabled = true;try {if (failSave.checked) throw Error('模拟：Product Kit 卡片保存失败');const args = {resource_uri: productKitUri, title: 'Product Kit · 真实本地素材', data: JSON.parse($('input').value)}, prepared = await runtime.prepareAppArgs(args, {isCurrent: () => !busy.checked}), trace = {id: crypto.randomUUID(), name: 'show_app', args, status: 'done', result: runtime.bindPreparedResult(prepareApp(prepared), prepared)}, previous = session.chat.messages;session.chat.messages = [...previous, trace];try {await save();} catch (error) {session.chat.messages = previous;throw error;}render();} catch (error) {status.textContent = error.message;}finally {button.disabled = false;}};
$('verify').onclick = async () => {try {const persisted = await read('sessions', 'current');if (!persisted) throw Error('尚无持久事务');$('state').value = JSON.stringify(persisted.chat.messages.map(trace => ({trace_id: trace.id, state: trace.appState, source: {node_ref: trace.result.productKitSourceContext?.node_ref, source_sha256: trace.result.productKitSourceContext?.source_sha256}})), null, 2);$('reply').value = JSON.stringify(persisted.chat.replies, null, 2);status.textContent = `事务回读成功：${persisted.chat.messages.length}个素材板，${persisted.chat.replies.length}次实际交接。`; } catch (error) {status.textContent = error.message;}};
$('rerender').onclick = render;busy.onchange = render;
window.productKitQA = {snapshot: () => structuredClone(session), runtime};
window.addEventListener('pagehide', () => {controller.reset();for (const url of urls.values()) URL.revokeObjectURL(url);database?.close();});
try {await openDatabase();const saved = await read('sessions', 'current');if (saved) {if (!Array.isArray(saved.chat?.messages) || !Array.isArray(saved.chat?.replies) || !Array.isArray(saved.graph?.nodes) || !Array.isArray(saved.graph?.edges)) throw Error('验收存储无效');session = saved;if (typeof saved.input === 'string') $('input').value = saved.input;}await showSource();render();for (const id of ['upload', 'open', 'rerender', 'verify', 'busy', 'fail-save']) $(id).disabled = false;} catch (error) {status.textContent = '验收未就绪：' + error.message;}
