import {normalizeForm,FORM_LABELS,formLanguage,compactOptions,ratingMax,validateForm,formSubmission,formDraft,formAccent} from './model.mjs';
import icons from './icons.mjs';
import {bindRadioGroup} from './radio-group.mjs';
const el=(tag,cls='',text)=>{const element=document.createElement(tag);element.className=cls;if(text!==undefined)element.textContent=text;return element;};
const icon=name=>{const span=el('span','agent-form-icon');span.innerHTML=icons[name];span.ariaHidden='true';return span;};
const button=(label,cls,click,iconName)=>{const node=el('button',cls);node.type='button';if(iconName)node.append(icon(iconName));if(label)node.append(document.createTextNode(label));node.onclick=click;return node;};
export function loadFormStyles(){if(document.querySelector('link[data-agent-forms]'))return;const link=el('link');link.rel='stylesheet';link.href=new URL('./styles.css',import.meta.url).href;link.dataset.agentForms='';document.head.append(link);}
function thumbnail(fileId,label,resolveImage){const wrap=el('span','agent-form-thumbnail');wrap.append(icon('photo'));if(fileId&&resolveImage)Promise.resolve().then(()=>resolveImage(fileId)).then(url=>{if(!url||typeof url!=='string'||! /^(?:https?:|blob:|data:image\/|\/|\.\/|assets\/)/i.test(url))return;const image=el('img');image.alt=label;image.loading='lazy';image.referrerPolicy='no-referrer';image.onload=()=>wrap.querySelector('.agent-form-icon')?.remove();image.onerror=()=>image.remove();image.src=url;wrap.append(image);}).catch(()=>{});return wrap;}
function rows(result,form,labels,resolveImage){const root=el('div','agent-form-summary-rows');for(const value of result.values || []){const row=el('div','agent-form-summary-row');row.append(el('span','agent-form-summary-label',value.field_label));const field=form?.fields.find(field=>field.id===value.field_id);if(field?.type==='image_select'&&Array.isArray(value.value)){const images=el('span','agent-form-summary-images');for(const selected of value.value){const option=field.options.find(option=>option.value===selected);images.append(thumbnail(option?.file_id,option?.label || selected,resolveImage));}row.append(images);}else{const answer=el('span','agent-form-summary-answer',value.display ?? labels.unanswered);answer.dataset.empty=String(!value.display);row.append(answer);}root.append(row);}return root;}
function accentStyle(element,form){const color=formAccent(form.accent);if(!color)return;const bubble=form.display_type==='bubble',mix=(amount,base)=>`color-mix(in srgb, ${color} ${amount}%, ${base})`;const properties={'card-bg':[12,'#1f1f1f'],'card-ring':[30,'transparent'],'section-bg':[bubble?20:8,'transparent'],'option-bg':[22,'transparent'],'option-bg-hover':[30,'transparent'],'option-ring':[28,'transparent'],'selected-bg':[38,'transparent'],'selected-ring':[62,'transparent'],'btn-bg':[bubble?60:56,'transparent'],'btn-bg-hover':[bubble?72:68,'transparent'],'btn-ring':[72,'transparent'],'btn-fg':[20,'#ffffff'],star:[65,'#ffffff'],title:[42,'#ffffff'],desc:[20,'#bcbcbc']};for(const [key,[amount,base]]of Object.entries(properties))element.style.setProperty('--form-'+key,mix(amount,base));}
let sequence=0;
export function createFormCard({trace,onSubmit,onDraftChange=()=>{},onEdit,resolveImage,isBusy=()=>false}){
 loadFormStyles();let current=trace,form=normalizeForm(trace),values=form&&formDraft(form,trace.formDraft),errors={},busy=false,disposed=false,editing=false,localResult=null,popover=null,renderedState='',submissionId=null,submissionPayload=null;const prefix='agent-form-'+(++sequence),element=el('section','agent-form-card'),fieldErrors=new Map(),syncers=new Map();let globalError;
 if(!form){element.textContent='表单内容无效';return {element,destroy(){element.remove();},getDraft(){return {};},submit:async()=>false,skip:async()=>false};}
 const labels=FORM_LABELS[formLanguage(form)];element.lang=formLanguage(form);element.dataset.traceId=trace.id || trace.callId;accentStyle(element,form);
 const result=()=>localResult || current.formLatestSubmission || (current.status==='done'&&Array.isArray(current.result?.values)?current.result:null),inactive=()=>busy||isBusy()||!onSubmit||(!editing&&!['pending','running','waiting'].includes(current.status)&&!(current.status==='done'&&current.result?.awaiting_submission===true));
 const draft=()=>structuredClone(values);
 const terminal=()=>['interrupted','cancelled','error','denied'].includes(current.status);
 function terminalMessage(){if(!terminal())return '';const error=current.result?.error||current.error;return typeof error==='string'?error:typeof error?.message==='string'?error.message:({interrupted:'页面已刷新，此表单未提交。请重新发送需求以继续。',cancelled:'本次操作已停止，表单未提交。',denied:'此表单已取消，尚未提交。',error:'表单处理失败，尚未提交。'}[current.status]);}
 function paintTerminal(){if(!globalError)return;if(terminal()){globalError.textContent=terminalMessage();globalError.dataset.terminal=current.status;}else if(globalError.dataset.terminal){globalError.textContent='';delete globalError.dataset.terminal;}}

 function persist(){try{onDraftChange(current,draft());return true;}catch(reason){globalError.textContent=reason.message||'保存失败';return false;}}
 function change(field,value){if(inactive())return;values[field.id]=value;submissionId=null;delete errors[field.id];paintError(field.id);syncers.get(field.id)?.();persist();}
 function paintError(id){const node=fieldErrors.get(id);if(node)node.textContent=errors[id] || '';const block=element.querySelector(`[data-field-id="${CSS.escape(id)}"]`);block?.setAttribute('aria-invalid',String(!!errors[id]));}
 function closePopover(focus=false){if(!popover)return;const old=popover;popover=null;old.trigger.ariaExpanded='false';old.panel.remove();document.removeEventListener('pointerdown',old.outside,true);window.removeEventListener('resize',old.position);window.removeEventListener('scroll',old.position,true);if(focus)old.trigger.focus({preventScroll:true});}
 function showPopover(trigger,panel){closePopover();trigger.ariaExpanded='true';panel.id=prefix+'-popover';trigger.setAttribute('aria-controls',panel.id);panel.classList.add('agent-form-popover');panel.lang=element.lang;document.body.append(panel);const position=()=>{if(!trigger.isConnected){closePopover();return;}const rect=trigger.getBoundingClientRect();panel.style.minWidth=panel.classList.contains('agent-form-select-menu')?rect.width+'px':'';const width=panel.offsetWidth,height=panel.offsetHeight;panel.style.left=Math.max(8,Math.min(innerWidth-width-8,rect.left))+'px';panel.style.top=Math.max(8,rect.bottom+6+height<=innerHeight-8?rect.bottom+6:rect.top-height-6)+'px';};const outside=event=>{if(!panel.contains(event.target)&&!trigger.contains(event.target))closePopover();};popover={trigger,panel,position,outside};panel.onfocusout=()=>queueMicrotask(()=>{if(popover?.panel===panel&&!panel.contains(document.activeElement)&&document.activeElement!==trigger)closePopover();});panel.onkeydown=event=>{event.stopPropagation();if(event.key==='Escape'){event.preventDefault();closePopover(true);}};document.addEventListener('pointerdown',outside,true);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);position();return panel;}
 function multi(field,selected){const previous=Array.isArray(values[field.id])?values[field.id]:[];if(previous.includes(selected)){const next=previous.filter(value=>value!==selected);change(field,next.length?next:null);}else if(field.max_select===undefined||previous.length<field.max_select)change(field,[...previous,selected]);}
 function control(field){const wrap=el('div','agent-form-control');const type=field.type;const updates=[];syncers.set(field.id,()=>updates.forEach(update=>update()));
  if(['radio','checkbox','image_select'].includes(type)){
   const compact=compactOptions(field),image=type==='image_select',radio=type==='radio'&&!compact,radioItems=[];wrap.classList.add(image?'agent-form-images':compact?'agent-form-chips':'agent-form-options');
   for(const option of field.options){const choose=()=>type==='radio'?change(field,values[field.id]===option.value&&compact?null:option.value):multi(field,option.value);const item=button('',image?'agent-form-image-choice':compact?'agent-form-chip':'agent-form-option',choose);item.ariaLabel=option.label;
    if(image){item.append(thumbnail(option.file_id,option.label,resolveImage));const mark=el('span','agent-form-image-check');mark.append(icon('check'));item.append(mark);if(option.label!==option.value)item.append(el('span','agent-form-image-caption',option.label));}
    else if(compact)item.textContent=option.label;
    else{const mark=el('span','agent-form-choice-mark');mark.dataset.type=type;if(type==='checkbox')mark.append(icon('check'));const text=el('span','agent-form-choice-copy');text.append(el('span','agent-form-option-label',option.label));if(option.description)text.append(el('span','agent-form-option-description',option.description));item.append(mark,text);}
    if(radio){item.value=option.value;radioItems.push(item);}else updates.push(()=>{const picked=type==='radio'?values[field.id]===option.value:values[field.id]?.includes(option.value);item.ariaPressed=String(!!picked);});wrap.append(item);
   }
   if(radio)updates.push(bindRadioGroup(wrap,radioItems,{label:field.label,value:()=>values[field.id],inactive}));
  }else if(type==='rating'){
   wrap.classList.add('agent-form-rating');const max=ratingMax(field),counter=el('span','agent-form-rating-value');for(let i=1;i<=max;i++){const star=button('','agent-form-star',()=>change(field,values[field.id]===i?null:i));star.ariaLabel=`${i}/${max}`;updates.push(()=>{const picked=(values[field.id]||0)>=i;star.replaceChildren(icon(picked?'starFilled':'star'));star.ariaPressed=String(picked);});wrap.append(star);}updates.push(()=>{counter.textContent=values[field.id]>0?`${values[field.id]}/${max}`:'';});wrap.append(counter);
  }else if(type==='slider'){
   wrap.classList.add('agent-form-slider');const input=el('input');input.type='range';input.min=field.min??0;input.max=field.max??100;input.step=field.step>0?field.step:1;input.ariaLabel=field.label;const value=el('span');updates.push(()=>{input.value=values[field.id]??input.min;value.textContent=input.value+(field.unit||'');const percent=(Number(input.value)-Number(input.min))/(Number(input.max)-Number(input.min)||1)*100;input.style.setProperty('--range-progress',percent+'%');});input.oninput=()=>change(field,Number(input.value));wrap.append(input,value);
  }else if(type==='number'){
   wrap.classList.add('agent-form-number');const group=el('div','agent-form-number-input'),input=el('input');input.type='number';input.ariaLabel=field.label;input.placeholder=field.placeholder||'';if(field.min!==undefined)input.min=field.min;if(field.max!==undefined)input.max=field.max;input.step='any';const clamp=value=>Math.min(field.max??Infinity,Math.max(field.min??-Infinity,value)),step=field.step>0?field.step:1;const minus=button('','',()=>change(field,clamp((values[field.id]??field.min??0)-step)),'minus'),plus=button('','',()=>change(field,clamp((values[field.id]??field.min??0)+step)),'plus');minus.ariaLabel='minus';plus.ariaLabel='plus';input.oninput=()=>change(field,input.value===''||!Number.isFinite(input.valueAsNumber)?null:input.valueAsNumber);input.onblur=()=>{if(typeof values[field.id]==='number')change(field,clamp(values[field.id]));};updates.push(()=>{if(document.activeElement!==input)input.value=values[field.id]??'';minus.disabled=values[field.id]!=null&&field.min!==undefined&&values[field.id]<=field.min;plus.disabled=values[field.id]!=null&&field.max!==undefined&&values[field.id]>=field.max;});group.append(minus,input,plus);wrap.append(group);if(field.unit)wrap.append(el('span','agent-form-unit',field.unit));
  }else if(type==='select'){
   const trigger=button('','agent-form-input agent-form-select',()=>{const menu=el('div','agent-form-select-menu');menu.role='listbox';menu.ariaLabel=field.label;const buttons=field.options.map(option=>{const item=button(option.label,'agent-form-select-option',()=>{change(field,option.value);closePopover(true);});item.role='option';item.ariaSelected=String(values[field.id]===option.value);if(values[field.id]===option.value)item.prepend(icon('check'));item.onkeydown=event=>{if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const index=buttons.indexOf(item),next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();}};menu.append(item);return item;});showPopover(trigger,menu);buttons[Math.max(0,field.options.findIndex(option=>option.value===values[field.id]))]?.focus({preventScroll:true});});trigger.ariaLabel=field.label;trigger.ariaHasPopup='listbox';trigger.ariaExpanded='false';updates.push(()=>{const option=field.options.find(option=>option.value===values[field.id]);trigger.replaceChildren(el('span','',option?.label||field.placeholder||labels.selectPlaceholder),icon('chevronDown'));trigger.dataset.placeholder=String(!option);});wrap.append(trigger);
  }else if(type==='date'){
   const trigger=button('','agent-form-input agent-form-date',()=>calendar(field,trigger));trigger.ariaLabel=field.label;trigger.ariaHasPopup='dialog';trigger.ariaExpanded='false';updates.push(()=>{trigger.replaceChildren(el('span','',values[field.id]||field.placeholder||labels.datePlaceholder),icon('calendar'));trigger.dataset.placeholder=String(!values[field.id]);});wrap.append(trigger);
  }else{
   const input=el(field.multiline||type!=='text'?'textarea':'input','agent-form-input');if(input.tagName==='TEXTAREA')input.rows=3;else input.type='text';input.ariaLabel=field.label;input.placeholder=field.placeholder||'';if(field.max_length>=0)input.maxLength=field.max_length;input.value=values[field.id]||'';input.oninput=()=>change(field,input.value||null);wrap.append(input);
  }
  updates.forEach(update=>update());return wrap;
 }
 function calendar(field,trigger){let date=typeof values[field.id]==='string'?new Date(values[field.id]+'T00:00:00'):new Date();if(Number.isNaN(date.getTime()))date=new Date();let month=new Date(date.getFullYear(),date.getMonth(),1);const panel=el('div','agent-form-calendar');panel.role='dialog';panel.ariaLabel=field.label;
  const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const draw=()=>{panel.replaceChildren();const header=el('div','agent-form-calendar-heading'),title=el('span','',new Intl.DateTimeFormat(element.lang,{month:'long',year:'numeric'}).format(month));const previous=button('','',()=>{month.setMonth(month.getMonth()-1);draw();panel.querySelector('[data-calendar-nav=previous]')?.focus();},'chevronLeft'),next=button('','',()=>{month.setMonth(month.getMonth()+1);draw();panel.querySelector('[data-calendar-nav=next]')?.focus();},'chevronRight');previous.ariaLabel='Previous month';next.ariaLabel='Next month';previous.dataset.calendarNav='previous';next.dataset.calendarNav='next';header.append(previous,title,next);const grid=el('div','agent-form-calendar-grid');grid.role='grid';for(let i=0;i<7;i++)grid.append(el('span','agent-form-weekday',new Intl.DateTimeFormat(element.lang,{weekday:'short'}).format(new Date(2026,0,4+i))));const first=new Date(month.getFullYear(),month.getMonth(),1-month.getDay()),today=iso(new Date());for(let i=0;i<42;i++){const current=new Date(first.getFullYear(),first.getMonth(),first.getDate()+i),value=iso(current),day=button(String(current.getDate()),'agent-form-day',()=>{change(field,values[field.id]===value?null:value);closePopover(true);});day.ariaLabel=value;day.ariaSelected=String(values[field.id]===value);day.dataset.outside=String(current.getMonth()!==month.getMonth());day.dataset.today=String(value===today);day.dataset.date=value;day.onkeydown=event=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7,Home:-current.getDay(),End:6-current.getDay()}[event.key];if(delta!==undefined||['PageUp','PageDown'].includes(event.key)){event.preventDefault();let target;if(delta!==undefined)target=new Date(current.getFullYear(),current.getMonth(),current.getDate()+delta);else{const move=(event.key==='PageDown'?1:-1)*(event.shiftKey?12:1),targetMonth=new Date(current.getFullYear(),current.getMonth()+move,1),last=new Date(targetMonth.getFullYear(),targetMonth.getMonth()+1,0).getDate();target=new Date(targetMonth.getFullYear(),targetMonth.getMonth(),Math.min(last,current.getDate()));}if(target.getMonth()!==month.getMonth()||target.getFullYear()!==month.getFullYear()){month=new Date(target.getFullYear(),target.getMonth(),1);draw();}panel.querySelector(`[data-date="${iso(target)}"]`)?.focus();}};grid.append(day);}panel.append(header,grid);};draw();showPopover(trigger,panel);(panel.querySelector('[aria-selected=true]')||panel.querySelector('[data-today=true]')||panel.querySelector('[data-outside=false]'))?.focus({preventScroll:true});
 }
 function render(){renderedState=JSON.stringify([current.status,current.formLatestSubmission,current.result,current.error]);closePopover();element.replaceChildren();fieldErrors.clear();syncers.clear();element.dataset.bubble=String(form.display_type==='bubble');const submitted=result(),summary=!!submitted&&!editing,heading=el('div','agent-form-heading'),title=el('div','agent-form-title');if(form.form_icon!=='none')title.append(icon('forms'));title.append(el('span','',form.title));if(summary){const status=el('span','agent-form-status');status.append(icon('check'),document.createTextNode(submitted.skipped?labels.skipped:labels.submitted));title.append(status);}heading.append(title);if(form.description&&!summary)heading.append(el('div','agent-form-description',form.description));element.append(heading);
  if(summary){const content=el('div','agent-form-submitted');if(!submitted.skipped)content.append(rows(submitted,form,labels,resolveImage));const edit=button(labels.edit,'agent-form-edit',async()=>{try{if(onEdit&&await onEdit(current)===false)return;if(disposed)return;editing=true;submissionId=null;if(!submitted.skipped)values=Object.fromEntries(submitted.values.map(value=>[value.field_id,value.value]));errors={};render();}catch(reason){globalError.textContent=reason.message||'无法修改';}},'pencil');edit.disabled=!onSubmit||busy||isBusy();content.append(edit);element.append(content);
  }else{const fields=el('fieldset','agent-form-fields');fields.disabled=inactive();for(const field of form.fields){const block=el('div','agent-form-field');block.dataset.fieldId=field.id;const label=el('div','agent-form-field-label',field.label);if(field.required)label.append(el('span','agent-form-required','*'));block.append(label);if(field.description)block.append(el('div','agent-form-description',field.description));block.append(control(field));const error=el('div','agent-form-field-error');error.role='alert';error.id=prefix+'-'+field.id+'-error';block.setAttribute('aria-describedby',error.id);fieldErrors.set(field.id,error);block.append(error);fields.append(block);paintError(field.id);}element.append(fields);const actions=el('div','agent-form-actions'),submit=button(form.submit_label||labels.submit,'agent-form-submit',()=>send(false)),skip=button(labels.skip,'agent-form-skip',()=>send(true));submit.disabled=skip.disabled=inactive();actions.append(submit,skip);element.append(actions);}
  globalError=el('div','agent-form-error');globalError.role='alert';element.append(globalError);paintTerminal();element.ariaBusy=String(busy);
 }
 async function send(skipped=false){if(disposed||inactive())return false;errors=skipped?{}:validateForm(form,values);for(const field of form.fields)paintError(field.id);if(Object.keys(errors).length){element.querySelector(`[data-field-id="${CSS.escape(Object.keys(errors)[0])}"]`)?.scrollIntoView({block:'nearest'});return false;}if(!persist())return false;const submission=formSubmission(form,values,current.callId,skipped);const payload=JSON.stringify(submission);if(!submissionId||submissionPayload!==payload)submissionId=crypto.randomUUID();submissionPayload=payload;busy=true;render();try{const accepted=await onSubmit(current,submission,{submissionId});if(accepted===false)throw Error('表单未能提交，请重试');if(!disposed){localResult=submission;editing=false;busy=false;render();}return true;}catch(reason){if(!disposed){busy=false;render();globalError.textContent=reason.message||'提交失败，请重试';}return false;}}
 element.onkeydown=event=>{event.stopPropagation();if(event.key==='Enter'&&!event.isComposing&&(event.ctrlKey||event.metaKey)){event.preventDefault();send(false);}};render();
 return {element,getDraft:draft,submit:()=>send(false),skip:()=>send(true),update(next){current=next;if(terminal())editing=false;if(!editing&&JSON.stringify([next.status,next.formLatestSubmission,next.result,next.error])!==renderedState){localResult=null;render();return;}paintTerminal();if(inactive())closePopover();const fields=element.querySelector('.agent-form-fields');if(fields)fields.disabled=inactive();for(const action of element.querySelectorAll('.agent-form-submit,.agent-form-skip'))action.disabled=inactive();const edit=element.querySelector('.agent-form-edit');if(edit)edit.disabled=!onSubmit||busy||isBusy();},suspend(){closePopover();},destroy(){disposed=true;closePopover();element.remove();}};
}
export function renderFormSummary(trace,{resolveImage}={}){if(trace.status!=='done'||!trace.result)return null;loadFormStyles();const form=normalizeForm(trace),result=trace.result,labels=FORM_LABELS[form?formLanguage(form):'zh'];const root=el('div','agent-form-submission-summary'),heading=el('div','agent-form-title');heading.append(icon('forms'),el('span','',result.form_title),el('span','agent-form-status',result.skipped?labels.skipped:labels.submitted));root.append(heading);if(!result.skipped)root.append(rows(result,form,labels,resolveImage));return root;}
