import { models } from './model-catalog.mjs';
import { icons } from './confirmation-icons.mjs';
import { chevron, lock } from './model-icons.mjs';
import { createHoverIntent } from './hover-intent.mjs';
import { createThinkingControl } from './thinking-control.mjs';
import { readThinking, saveThinking, thinkingSummary, thinkingStorageKey, getThinkingSpec } from './thinking-settings.mjs';
import { hasStartedSession, sessionModelId, captureSessionModel } from './model-session.mjs';
import { bindTooltip } from './tooltip.mjs';
export { createPanelResize } from "./panel-resize.mjs";
export { observeFooter } from './footer-layout.mjs';
const lockedDescription='会话开始后无法更改模型，请开启新对话以使用不同模型';
const storageKey = 'tapnow-agent-model';
for (const file of ['./models.css','./thinking.css','./footer.css']) { const style=document.createElement('link');style.rel='stylesheet';style.href=new URL(file,import.meta.url).href;document.head.append(style); }
const make=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
function selectedId(){try{const value=JSON.parse(localStorage.getItem(storageKey)||'null');if(models.some(m=>m.id===value?.id))return value.id;}catch{}return 'auto';}
export function getSelection(session){const id=sessionModelId(session,selectedId()),thinking=readThinking(id,localStorage);return {id,...(thinking?{thinking}:{})};}
export function prepareSessionSelection(session){const selection=getSelection(session);if(!models.some(model=>model.id===selection.id)&&selection.id)throw Error('此会话使用的模型暂不可用，请保留历史并新建对话。');captureSessionModel(session,selectedId());return getSelection(session);}
export function getLabel(session){const id=getSelection(session).id;return models.find(m=>m.id===id)?.label||id||'模型';}
export function createControl({disabled=false,onError,beforeOpen,session=null}){
 const locked=hasStartedSession(session),lockedModel=models.find(m=>m.id===getSelection(session).id),canAdjust=locked&&!!getThinkingSpec(lockedModel?.id);
 const trigger=make('button','agent-model-trigger agent-mode');trigger.type='button';trigger.disabled=disabled;trigger.setAttribute('aria-label','AI 模型');trigger.setAttribute('aria-haspopup','menu');trigger.setAttribute('aria-expanded','false');
 let menu=null,info=null,scroll=null,more=null,expanded=false,hoverTimer=0,resizeObserver=null,exitTimer=0,leaving=null,scrollFrame=0,thinkingControl=null,hoverIntent=null,suppressInfoFocus=false;
 const tooltip=bindTooltip(trigger,{text:()=>locked&&!canAdjust?lockedDescription:'',enabled:()=>!menu&&!disabled});
 const update=()=>{
   const selection=getSelection(session),model=models.find(m=>m.id===selection.id);trigger.replaceChildren();
   if(model?.icon){const icon=make('img','agent-model-trigger-icon');icon.src=model.icon;icon.alt='';trigger.append(icon);}
   const label=make('span','agent-model-trigger-label',getLabel(session));trigger.append(label);
   trigger.dataset.locked=String(locked);trigger.setAttribute('aria-disabled',String(disabled||(locked&&!canAdjust)));trigger.setAttribute('aria-label',[getLabel(session),thinkingSummary(selection.id,selection.thinking),locked?'模型已锁定':null].filter(Boolean).join(', '));
   const summary=thinkingSummary(selection.id,selection.thinking);
   if(summary)trigger.append(make('span','agent-model-trigger-effort',summary));
   if(!locked||canAdjust)trigger.insertAdjacentHTML('beforeend',chevron);
   if(menu)for(const row of menu.querySelectorAll('[data-model]')){
     const chosen=row.dataset.model===selection.id;row.classList.toggle('selected',chosen);
     row.querySelector('.agent-model-check').innerHTML=chosen?icons.check:'';
     const effort=row.querySelector('.agent-model-effort');effort.textContent=thinkingSummary(row.dataset.model,readThinking(row.dataset.model,localStorage));effort.hidden=!effort.textContent;
   }
 };

 function dismissInfo(){thinkingControl?.destroy();thinkingControl=null;clearTimeout(hoverTimer);info?.remove();info=null;}
 function deferInfo(){clearTimeout(hoverTimer);hoverTimer=setTimeout(dismissInfo,400);}
 function position(){if(!menu)return;const r=trigger.getBoundingClientRect(),above=r.top>=menu.offsetHeight+16;menu.dataset.side=above?'top':'bottom';menu.style.left=Math.max(8,Math.min(innerWidth-menu.offsetWidth-8,r.right-menu.offsetWidth+(locked&&canAdjust?40:0)))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-menu.offsetHeight-8,above?r.top-menu.offsetHeight-8:r.bottom+8))+'px';if(info)positionInfo();}
 function positionInfo(){if(!menu||!info)return;const m=menu.getBoundingClientRect(),row=menu.querySelector(`[data-model="${info.dataset.model}"]`).getBoundingClientRect();let top=row.top+row.height/2-info.offsetHeight/2;if(info.offsetHeight<=m.height)top=Math.max(m.top,Math.min(m.bottom-info.offsetHeight,top));info.style.top=Math.max(8,Math.min(innerHeight-info.offsetHeight-8,top))+'px';info.style.left=Math.max(8,m.left-info.offsetWidth-6)+'px';}
 function showInfo(model){clearTimeout(hoverTimer);if(model.id==='auto')return dismissInfo();if(info?.dataset.model===model.id)return;dismissInfo();info=make('section','agent-model-info');info.dataset.model=model.id;info.setAttribute('aria-label',model.label+' 模型说明');const header=make('header');if(model.icon){const img=make('img');img.src=model.icon;img.alt='';header.append(img);}header.append(make('h4','',model.label));const body=make('div','agent-model-info-body');body.append(header,make('p','',model.description));info.append(body);const metrics=make('dl','agent-model-metrics');for(const [key,label]of [['speed','速度'],['intelligence','智能'],['cost','成本']]){const row=make('div'),dt=make('dt','',label),dd=make('dd'),meter=make('meter','visually-hidden');meter.min=1;meter.max=5;meter.value=model.capabilities[key];meter.setAttribute('aria-label',label);dd.append(meter);for(let i=0;i<5;i++){const tick=make('span',i<model.capabilities[key]?'filled':'');tick.setAttribute('aria-hidden','true');dd.append(tick);}row.append(dt,dd);metrics.append(row);}body.append(metrics);thinkingControl=createThinkingControl({id:model.id,settings:readThinking(model.id,localStorage),onChange:value=>{saveThinking(model.id,value,localStorage);window.dispatchEvent(new Event('agent:thinking-selection'));},onError});if(thinkingControl)info.append(thinkingControl.element);info.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();hoverIntent?.cancel?.();const row=menu?.querySelector(`[data-model="${info.dataset.model}"]`);dismissInfo();suppressInfoFocus=true;row?.focus({preventScroll:true});suppressInfoFocus=false;}else if(e.key==='Tab')close(true);};info.onpointerenter=()=>clearTimeout(hoverTimer);info.onpointerleave=deferInfo;document.body.append(info);positionInfo();}
 function fade(){if(!scroll||!menu)return;menu.classList.toggle('scroll-top',scroll.scrollTop>1);menu.classList.toggle('scroll-bottom',scroll.scrollTop+scroll.clientHeight<scroll.scrollHeight-1);positionInfo();}
 function choose(model){if(locked)return;try{localStorage.setItem(storageKey,JSON.stringify({id:model.id}));window.dispatchEvent(new Event('agent:model-selection'));close(true);}catch(error){onError?.(error.message);}}
 function row(model){const b=make('button','agent-model-row'+(model.id==='auto'?' agent-model-auto':''));b.type='button';b.dataset.model=model.id;const content=make('span','agent-model-row-content');if(model.icon){const img=make('img');img.src=model.icon;img.alt='';content.append(img);}const labels=make('span','agent-model-labels');labels.append(make('span','agent-model-name',model.label));if(model.id==='auto')labels.append(make('span','agent-model-description',model.description));content.append(labels);b.append(content,make('span','agent-model-effort'),make('span','agent-model-check'));b.onclick=()=>choose(model);b.onpointerenter=event=>hoverIntent?.request(event,()=>showInfo(model));b.onfocus=()=>{if(!suppressInfoFocus)showInfo(model);};return b;}
 function expand(value,focusFirst=false){expanded=value;more.setAttribute('aria-expanded',String(value));const area=menu.querySelector('.agent-model-other');area.classList.toggle('expanded',value);area.firstElementChild.inert=!value;area.firstElementChild.setAttribute('aria-hidden',String(!value));dismissInfo();if(value){cancelAnimationFrame(scrollFrame);const initial=scroll.scrollTop,target=Math.max(0,initial+more.getBoundingClientRect().top-scroll.getBoundingClientRect().top),started=performance.now();const frame=now=>{if(!menu)return;const t=Math.min(1,(now-started)/220);scroll.scrollTop=initial+(target-initial)*(1-(1-t)**4);if(t<1)scrollFrame=requestAnimationFrame(frame);else if(focusFirst)area.querySelector('button')?.focus({preventScroll:true});};scrollFrame=requestAnimationFrame(frame);}position();}
 function keydown(event){if(event.key==='Escape'){event.preventDefault();event.stopPropagation();if(expanded&&event.target.closest('.agent-model-other')){expand(false);more.focus();}else close(true);return;}if(event.key==='ArrowLeft'&&event.target.closest('.agent-model-other')){event.preventDefault();expand(false);more.focus();return;}if(event.target===more&&['ArrowDown','ArrowRight'].includes(event.key)){event.preventDefault();expand(true,true);return;}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();event.stopPropagation();const area=event.target.closest('.agent-model-other');const buttons=[...(area||menu).querySelectorAll('button')].filter(b=>!b.closest('[inert]'));const current=buttons.indexOf(document.activeElement);let index=event.key==='Home'?0:event.key==='End'?buttons.length-1:current+(event.key==='ArrowDown'?1:-1);index=area?(index+buttons.length)%buttons.length:Math.max(0,Math.min(buttons.length-1,index));buttons[index]?.focus();}if(event.key==='Tab')close(true);}
 function outside(event){if(!menu?.contains(event.target)&&!info?.contains(event.target)&&!trigger.contains(event.target))close();}
 function close(focus=false){tooltip.hide();hoverIntent?.destroy();hoverIntent=null;dismissInfo();cancelAnimationFrame(scrollFrame);resizeObserver?.disconnect();resizeObserver=null;if(!menu)return;const old=menu;menu=null;scroll=null;trigger.setAttribute('aria-expanded','false');document.removeEventListener('pointerdown',outside,true);window.removeEventListener('resize',position);document.removeEventListener('scroll',position,true);clearTimeout(exitTimer);leaving?.remove();leaving=old;old.dataset.state='closed';old.inert=true;old.setAttribute('aria-hidden','true');old.style.pointerEvents='none';exitTimer=setTimeout(()=>{old.remove();if(leaving===old)leaving=null;},150);if(focus)trigger.focus({preventScroll:true});}
 function open(){if(disabled||(locked&&!canAdjust))return;beforeOpen?.();tooltip.hide();clearTimeout(exitTimer);leaving?.remove();leaving=null;menu=make('div','agent-model-menu');if(locked&&canAdjust){openLocked();return;}hoverIntent=createHoverIntent({getCard:()=>info,getActiveRow:()=>info?menu?.querySelector(`[data-model="${info.dataset.model}"]`):null});menu.role='menu';menu.setAttribute('aria-label','AI 模型');menu.dataset.state='open';const wrap=make('div','agent-model-scroll-wrap');scroll=make('div','agent-model-scroll');scroll.append(row(models[0]));const recommended=make('div','agent-model-group');recommended.append(make('div','agent-model-section','精选推荐'));models.filter(m=>m.group==='recommended').forEach(m=>recommended.append(row(m)));scroll.append(recommended);const otherGroup=make('div','agent-model-group');more=make('button','agent-model-more','更多模型');more.insertAdjacentHTML('beforeend',chevron);more.type='button';more.setAttribute('aria-expanded','false');more.onclick=()=>expand(!expanded);const area=make('div','agent-model-other'),inner=make('div');inner.inert=true;inner.setAttribute('aria-hidden','true');models.filter(m=>m.group==='other').forEach(m=>inner.append(row(m)));area.append(inner);otherGroup.append(more,area);scroll.append(otherGroup);wrap.append(scroll);menu.append(wrap);menu.onkeydown=keydown;menu.onpointerenter=()=>clearTimeout(hoverTimer);menu.onpointerleave=deferInfo;document.body.append(menu);trigger.setAttribute('aria-expanded','true');scroll.onscroll=fade;resizeObserver=new ResizeObserver(()=>{position();fade();});resizeObserver.observe(scroll);resizeObserver.observe(scroll.firstElementChild);update();position();fade();if(models.find(m=>m.id===getSelection(session).id)?.group==='other')expand(true);else expanded=false;document.addEventListener('pointerdown',outside,true);window.addEventListener('resize',position);document.addEventListener('scroll',position,true);menu.tabIndex=-1;menu.focus({preventScroll:true});}
 function openLocked(){
   menu.classList.add('agent-model-locked-menu');menu.role='dialog';menu.setAttribute('aria-label','模型思考设置');menu.dataset.state='open';
   const body=make('div','agent-model-locked-body'),header=make('div','agent-model-locked-header');
   if(lockedModel.icon){const icon=make('img');icon.src=lockedModel.icon;icon.alt='';header.append(icon);}
   const badge=make('span','agent-model-locked-badge');badge.innerHTML=lock;badge.append(document.createTextNode('模型已锁定'));
   header.append(make('h4','',lockedModel.label),badge);body.append(header,make('p','',lockedDescription));menu.append(body);
   thinkingControl=createThinkingControl({id:lockedModel.id,settings:readThinking(lockedModel.id,localStorage),onChange:value=>{saveThinking(lockedModel.id,value,localStorage);window.dispatchEvent(new Event('agent:thinking-selection'));},onError});
   if(thinkingControl)menu.append(thinkingControl.element);
   menu.addEventListener('keydown',event=>{if(event.key==='Escape'||event.key==='Tab'){if(event.key==='Escape')event.preventDefault();event.stopPropagation();close(true);}},true);
   document.body.append(menu);trigger.setAttribute('aria-expanded','true');position();
   resizeObserver=new ResizeObserver(position);resizeObserver.observe(menu);
   document.addEventListener('pointerdown',outside,true);window.addEventListener('resize',position);document.addEventListener('scroll',position,true);
   menu.querySelector('[role=slider],[role=switch]')?.focus({preventScroll:true});
 }
 trigger.onclick=()=>menu?close():open();trigger.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();if(!menu)open();menu?.querySelector('button,[role=slider]')?.focus();}};window.addEventListener('agent:model-selection',update);window.addEventListener('agent:thinking-selection',update);const onStorage=e=>{if(e.key===storageKey)update();if(e.key===thinkingStorageKey){update();if(info)thinkingControl?.update(readThinking(info.dataset.model,localStorage));else if(locked&&canAdjust)thinkingControl?.update(readThinking(lockedModel.id,localStorage));}};window.addEventListener('storage',onStorage);update();
 return {element:trigger,close,destroy(){close();tooltip.destroy();clearTimeout(exitTimer);leaving?.remove();window.removeEventListener('agent:model-selection',update);window.removeEventListener('agent:thinking-selection',update);window.removeEventListener('storage',onStorage);}};
}
