import * as core from './core.mjs';
import * as segmentation from './segmentation.mjs';
import {mediaSource} from '../video-creation/core.mjs';
import {openVideoFrames} from '../video-media/frames.mjs';
import icons from './icons.mjs';
const app=window.CanvasApp,el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const button=(label,icon,fn,showText=false)=>{const b=el('button');b.type='button';b.setAttribute('aria-label',label);b.dataset.tooltip=label;b.innerHTML=icons[icon]||'';if(showText)b.append(el('span','',label));b.onclick=fn;return b;};
const clock=time=>`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;
async function transport(source,signal){const raw=await window.LocalAssets.url(source);if(raw.startsWith('data:'))return raw;const url=new URL(raw,document.baseURI);if(url.origin!==location.origin&&url.protocol!=='blob:')return url.href;const r=await fetch(url,{signal});if(!r.ok)throw Error('本地素材读取失败');return window.LocalMedia.asDataUrl(await r.blob());}
let current;
class MaskEditor {
  constructor(node,mode){
    this.id=node.id;this.mode=mode;this.source=mediaSource(node);this.clip=JSON.stringify(node.clip||null);this.alive=true;this.listeners=new AbortController();this.rect=null;this.mask=null;this.reference=null;this.ready=false;
    this.root=el('section','video-mask-editor');this.root.setAttribute('aria-label',mode==='replace'?'物体替换':'物体移除');this.root.tabIndex=-1;this.root.onpointerdown=e=>e.stopPropagation();
    this.surface=el('div','video-mask-surface');this.video=el('video');this.video.muted=true;this.video.playsInline=true;this.video.preload='auto';this.video.crossOrigin='anonymous';this.video.setAttribute('aria-label','编辑源视频');this.overlay=el('canvas','video-temporal-mask');this.overlay.setAttribute('aria-label','逐帧视频蒙层');this.selection=el('div','video-mask-selection');this.selection.tabIndex=0;this.selection.setAttribute('aria-label','视频区域选择');this.selection.setAttribute('role','application');this.box=el('div','video-mask-box');
    const move=el('div','video-mask-move');move.dataset.handle='move';this.box.append(move);for(const h of ['tl','tr','bl','br']){const handle=button('调整'+h+'角','corner',()=>{});handle.className='video-mask-handle '+h;handle.dataset.handle=h;this.box.append(handle);}this.confirmBar=el('div','video-mask-confirm');this.cancel=button('取消选区','cancel',()=>this.cancelSelection());this.confirm=button('识别选中目标','confirm',()=>this.recognize());this.confirmBar.append(this.cancel,this.confirm);this.confirmBar.onpointerdown=e=>e.stopPropagation();this.box.append(this.confirmBar);this.selection.append(this.box);
    this.controls=el('div','video-mask-player');this.play=button('播放','play',()=>this.togglePlay());this.seek=el('input');this.seek.type='range';this.seek.min=0;this.seek.step=.001;this.seek.setAttribute('aria-label','编辑视频播放进度');this.time=el('span');this.seek.oninput=()=>{this.video.currentTime=Number(this.seek.value);this.renderMask();};this.controls.append(this.play,this.seek,this.time);this.surface.append(this.video,this.overlay,this.controls,this.selection);
    this.panel=el('section','video-mask-panel');this.panel.setAttribute('aria-label','视频编辑参数');const header=el('header');header.append(el('strong','',mode==='replace'?'物体替换':'物体移除'));this.actions=el('div','video-mask-actions');this.add=button('添加蒙层','add',()=>this.startDrawing(),true);this.pick=button('从画布中选择','canvas',()=>this.pickImage(),true);this.upload=button('从本地上传','upload',()=>this.file.click(),true);this.actions.append(this.add,this.pick,this.upload);header.append(this.actions);
    const cards=el('div','video-mask-cards');this.targetCard=this.card(mode==='replace'?'被替换物':'目标','target',()=>this.clearMask());cards.append(this.targetCard.root);if(mode==='replace'){const arrow=el('span','video-mask-arrow');arrow.innerHTML=icons.arrow;this.refCard=this.card('替换物','reference',()=>{this.reference=null;this.paint();});cards.append(arrow,this.refCard.root);}else cards.classList.add('remove');
    const footer=el('footer'),submit=el('div','creation-submit-group'),cost=el('span','creation-cost');cost.innerHTML=icons.cost;cost.append(el('span','','—'));cost.title='由接入的生成服务返回用量';this.generate=button('生成','generate',()=>this.submit());this.generate.className='creation-generate';submit.append(cost,this.generate);footer.append(submit);this.status=el('p','video-mask-status','正在读取视频…');this.status.setAttribute('role','status');this.connect=button('连接视频分割 API','',()=>segmentation.configure({returnFocus:this.connect}),true);this.connect.hidden=true;this.stop=button('取消识别','cancel',()=>this.recognizing?.abort(),true);this.stop.hidden=true;this.file=el('input');this.file.type='file';this.file.accept='image/jpeg,image/png,image/webp';this.file.hidden=true;this.file.onchange=()=>{const file=this.file.files[0];this.file.value='';if(file)this.uploadImage(file);};this.panel.append(header,cards,footer,this.status,this.connect,this.stop,this.file);this.root.append(this.surface,this.panel);document.body.append(this.root);document.body.classList.add('video-masking');
    document.querySelector(`.node[data-id="${this.id}"] video`)?.pause();this.bindSelection();const opts={signal:this.listeners.signal};document.addEventListener('canvas:render',()=>{const n=this.node();if(!n||mediaSource(n)!==this.source||JSON.stringify(n.clip||null)!==this.clip||!app.getState().selected.includes(this.id)){this.close();return;}this.syncStoredMask(n.videoMask);this.place();},opts);document.addEventListener('pointerdown',e=>{if(!this.root.contains(e.target)&&!e.target.closest('dialog,.task-tray'))this.close();},opts);document.addEventListener('keydown',e=>{if(e.target.closest('dialog'))return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(this.recognizing)this.recognizing.abort();else if(this.rect||this.drawing)this.cancelSelection();else this.close();}else if(e.code==='Space'&&this.root.contains(e.target)&&!e.target.matches('input,button')){e.preventDefault();this.togglePlay();}}, {...opts,capture:true});window.addEventListener('resize',()=>this.fit(false),opts);
    this.video.onloadedmetadata=()=>{this.duration=this.video.duration;this.offset=node.clip?.start||0;this.end=Math.min(node.clip?.end??this.duration,this.duration);this.ready=this.video.videoWidth>0&&Number.isFinite(this.duration)&&this.end>this.offset;this.seek.min=this.offset;this.seek.max=this.end;this.video.currentTime=this.offset;this.overlay.width=this.video.videoWidth;this.overlay.height=this.video.videoHeight;if(this.ready)this.status.hidden=true;else this.error('视频信息无效');this.paint();this.loadMask(node.videoMask);};this.video.onerror=()=>this.error('视频加载失败，请检查来源');this.video.ontimeupdate=()=>{if(!this.video.paused&&this.video.currentTime>=this.end){this.video.pause();this.video.currentTime=this.offset;}this.syncPlayer();this.renderMask();};this.video.onseeked=()=>{this.syncPlayer();this.renderMask();};this.video.onplay=this.video.onpause=()=>this.syncPlayer();window.LocalAssets.url(this.source||'').then(src=>{if(this.alive)this.video.src=src;}).catch(e=>this.error(e.message));this.fit(true);this.paint();this.root.focus({preventScroll:true});this.tick();
  }
  node(){return app.getState().nodes.find(n=>n.id===this.id);}
  guard(){const n=this.node();if(!n||mediaSource(n)!==this.source||JSON.stringify(n.clip||null)!==this.clip)throw Error('来源视频已变化，请重新打开');}
  card(label,icon,clear){const root=el('div','video-mask-card'),body=el('div','video-mask-card-content');body.innerHTML=icons[icon];const remove=button('清除'+label,'cancel',clear);remove.className='video-mask-card-clear';const caption=el('span','video-mask-caption',label);root.append(body,remove,caption);return {root,body,remove,icon};}
  paintCard(card,source,highlight,loading=false){card.root.classList.toggle('highlight',highlight);card.remove.hidden=!source;card.remove.disabled=!!this.busy||!!this.recognizing;card.body.replaceChildren();if(loading)card.body.append(el('span','video-mask-spinner'));else if(source){const img=el('img');img.src=source;img.alt=card===this.targetCard?'Selected region':'Reference';card.body.append(img);}else card.body.innerHTML=icons[card.icon];}
  paint(){if(!this.alive)return;this.add.hidden=!!this.mask;this.pick.hidden=this.upload.hidden=this.mode!=='replace'||!this.mask;this.add.disabled=!this.ready||!!this.recognizing||!!this.busy;this.pick.disabled=this.upload.disabled=!!this.busy||!!this.uploading;this.generate.disabled=!this.ready||!this.mask||this.mode==='replace'&&!this.reference||!!this.busy||!!this.recognizing||!!this.uploading;this.play.disabled=!this.ready||!!this.recognizing;this.seek.disabled=!this.ready||!!this.recognizing;this.stop.hidden=!this.recognizing;this.confirm.disabled=!!this.recognizing;this.cancel.disabled=!!this.recognizing;this.selection.classList.toggle('drawing',!!this.drawing&&!this.rect);this.selection.classList.toggle('processing',!!this.recognizing);this.selection.style.pointerEvents=this.ready&&!this.busy?'auto':'none';this.controls.classList.toggle('selection-active',!!this.rect);this.box.hidden=!this.rect;this.confirmBar.hidden=!this.rect||!!this.recognizing;
    if(this.rect){const r=this.rect;Object.assign(this.box.style,{left:r.x*100+'%',top:r.y*100+'%',width:r.width*100+'%',height:r.height*100+'%'});this.confirmBar.dataset.placement=1-r.y-r.height>=.12?'bottom':r.y>=.12?'top':'inside';}this.paintCard(this.targetCard,this.thumbnail,!this.mask,!!this.recognizing);if(this.refCard)this.paintCard(this.refCard,this.reference?.preview,!!this.mask,!!this.uploading);this.syncPlayer();}
  fit(animated){cancelAnimationFrame(this.fitFrame);const n=this.node();if(!n)return;const c=document.querySelector('#canvas').getBoundingClientRect(),to=core.fitMask(n,c.width,c.height),from={...app.getState().view};if(!animated||matchMedia('(prefers-reduced-motion:reduce)').matches){app.setView(to);this.place();return;}const duration=Math.min(1500,Math.max(200,200+Math.hypot(to.x-from.x,to.y-from.y)*.5+Math.abs(to.scale-from.scale)*600+200/Math.max(.2,from.scale))),start=performance.now();const frame=now=>{if(!this.alive)return;const t=Math.min(1,(now-start)/duration),p=1-(1-t)**3;app.setView({x:from.x+(to.x-from.x)*p,y:from.y+(to.y-from.y)*p,scale:from.scale+(to.scale-from.scale)*p});this.panel.classList.toggle('entering',t<1);if(t<1)this.fitFrame=requestAnimationFrame(frame);};this.fitFrame=requestAnimationFrame(frame);}
  place(){if(!this.alive)return;const n=this.node();if(!n)return;const {view}=app.getState(),c=document.querySelector('#canvas').getBoundingClientRect();Object.assign(this.root.style,{left:c.left+n.x*view.scale+view.x+'px',top:c.top+n.y*view.scale+view.y+'px',width:n.width*view.scale+'px',height:n.height*view.scale+'px'});this.panel.style.width=Math.min(500,innerWidth-32)+'px';}
  bindSelection(){let drag;const point=e=>{const r=this.surface.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};};this.selection.onpointerdown=e=>{if(e.button!==0||!this.ready||this.recognizing||this.busy||e.target.closest('.video-mask-confirm'))return;e.preventDefault();e.stopPropagation();this.video.pause();this.selection.setPointerCapture(e.pointerId);const p=point(e),handle=e.target.closest('[data-handle]')?.dataset.handle;drag={point:p,initial:this.rect?{...this.rect}:null,handle};if(!handle){this.drawing=true;this.rect=core.drawRect(p,p);}this.paint();};this.selection.onpointermove=e=>{if(!drag)return;const p=point(e);if(drag.handle){const bounds=this.surface.getBoundingClientRect();this.rect=core.transformRect(drag.initial,p.x-drag.point.x,p.y-drag.point.y,drag.handle==='move'?null:drag.handle,Math.min(1,20/bounds.width),Math.min(1,20/bounds.height));}else this.rect=core.drawRect(drag.point,p);this.paint();};this.selection.onpointerup=this.selection.onpointercancel=()=>{if(!drag)return;drag=null;if(!core.validRect(this.rect))this.rect=null;this.drawing=false;this.paint();};this.selection.onkeydown=e=>{if(!this.rect||this.recognizing||this.busy)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?.01:.001;this.rect=core.transformRect(this.rect,e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0,null);this.paint();}if(e.key==='Enter'){e.preventDefault();this.recognize();}};}
  startDrawing(){this.video.pause();this.rect=null;this.drawing=true;this.status.hidden=true;this.connect.hidden=true;this.paint();this.selection.focus({preventScroll:true});}
  cancelSelection(){this.rect=null;this.drawing=false;this.paint();this.add.focus({preventScroll:true});}
  syncPlayer(){if(!this.video)return;const playing=!this.video.paused;this.play.innerHTML=icons[playing?'pause':'play'];this.play.setAttribute('aria-label',playing?'暂停':'播放');this.seek.value=this.video.currentTime;this.seek.style.setProperty('--progress',Math.max(0,Math.min(100,(this.video.currentTime-(this.offset||0))/((this.end||0)-(this.offset||0)||1)*100))+'%');this.time.textContent=clock(Math.max(0,this.video.currentTime-(this.offset||0)))+' / '+clock(Math.max(0,(this.end||0)-(this.offset||0)));}
  togglePlay(){if(!this.ready||this.recognizing)return;if(this.video.paused){if(this.video.currentTime>=this.end-.01)this.video.currentTime=this.offset;this.video.play().catch(e=>this.error(e.message));}else this.video.pause();}
  async recognize(){if(!core.validRect(this.rect)||this.recognizing||this.busy)return;this.video.pause();const rect={...this.rect},time=this.video.currentTime,controller=new AbortController();this.recognizing=controller;const timer=setTimeout(()=>controller.abort(),300000);this.status.hidden=true;this.connect.hidden=true;this.paint();let reader;
    try{this.guard();await segmentation.availability({signal:controller.signal});this.guard();const req=core.segmentationRequest({nodeId:this.id,source:await transport(this.source,controller.signal),rect,time,width:this.video.videoWidth,height:this.video.videoHeight,duration:this.duration});const result=await segmentation.segment(req,{signal:controller.signal,onProgress:value=>{if(this.alive&&this.recognizing===controller){this.status.hidden=false;this.status.textContent='正在识别目标… '+Math.round(Math.max(0,Math.min(100,value)))+'%';}}});if(!this.alive||controller.signal.aborted)return;this.guard();const mask=core.validateMask(result,{width:this.video.videoWidth,height:this.video.videoHeight,duration:this.duration});reader=await openVideoFrames(await window.LocalAssets.url(this.source),controller.signal);const frame=await reader.at(time,mask.width);const preview=this.makeThumbnail(frame,mask,time);const asset=await window.LocalAssets.put(new Blob([JSON.stringify(mask)],{type:'application/json'}));if(!this.alive||controller.signal.aborted)return;this.guard();this.mask=mask;this.maskAsset=asset;this.thumbnail=preview;this.maskTime=time;this.rect=null;this.drawing=false;this.lastFrame=-1;this.status.hidden=true;app.updateNode(this.id,{videoMask:{source:this.source,clip:this.clip,asset,time,width:mask.width,height:mask.height,duration:this.duration}});this.renderMask();
    }catch(e){if(this.alive){this.error(e.name==='AbortError'?'识别已取消；外部识别是否停止尚未确认':e.message);this.connect.hidden=e.code!=='configuration_required';}}finally{clearTimeout(timer);reader?.dispose();if(this.recognizing===controller)this.recognizing=null;if(this.alive)this.paint();}}
  makeThumbnail(frame,mask,time){const rgba=core.decodeMask(mask.frames[core.frameAt(mask,time)],mask.width,mask.height,[255,255,255,255]),bounds=core.maskBounds(rgba,mask.width,mask.height);if(!bounds)return null;const alpha=el('canvas');alpha.width=mask.width;alpha.height=mask.height;alpha.getContext('2d').putImageData(new ImageData(rgba,mask.width,mask.height),0,0);const c=frame.getContext('2d');c.globalCompositeOperation='destination-in';c.drawImage(alpha,0,0);const thumb=el('canvas');thumb.width=bounds.width;thumb.height=bounds.height;thumb.getContext('2d').drawImage(frame,bounds.x,bounds.y,bounds.width,bounds.height,0,0,bounds.width,bounds.height);return thumb.toDataURL('image/png');}
  syncStoredMask(saved){if(!this.ready)return;const asset=saved?.source===this.source&&saved.clip===this.clip?saved.asset:null;if((this.maskAsset||null)===(asset||null))return;this.mask=null;this.maskAsset=null;this.thumbnail=null;this.lastFrame=-1;this.overlay.getContext('2d').clearRect(0,0,this.overlay.width,this.overlay.height);if(asset)this.loadMask(saved);this.paint();}
  async loadMask(saved){if(!saved||saved.source!==this.source||saved.clip!==this.clip||this.loadingMask===saved.asset)return;this.loadingMask=saved.asset;let reader;try{const response=await fetch(await window.LocalAssets.url(saved.asset),{signal:this.listeners.signal}),value=await response.json();const mask=core.validateMask(value,{width:this.video.videoWidth,height:this.video.videoHeight,duration:this.duration});reader=await openVideoFrames(await window.LocalAssets.url(this.source),this.listeners.signal);const frame=await reader.at(saved.time,mask.width);if(!this.alive||this.mask||this.recognizing||this.node()?.videoMask?.asset!==saved.asset)return;this.mask=mask;this.maskAsset=saved.asset;this.maskTime=saved.time;this.thumbnail=this.makeThumbnail(frame,mask,saved.time);this.lastFrame=-1;this.renderMask();this.paint();}catch(e){if(this.alive)this.error('蒙层恢复失败：'+e.message);}finally{reader?.dispose();if(this.loadingMask===saved.asset)this.loadingMask=null;}}
  clearMask(){if(this.busy||this.recognizing)return;this.mask=null;this.maskAsset=null;this.thumbnail=null;this.lastFrame=-1;this.overlay.getContext('2d').clearRect(0,0,this.overlay.width,this.overlay.height);app.updateNode(this.id,{videoMask:null});this.paint();}
  renderMask(){if(!this.mask)return;const frame=core.frameAt(this.mask,this.video.currentTime);if(frame===this.lastFrame)return;this.lastFrame=frame;const rgba=core.decodeMask(this.mask.frames[frame],this.mask.width,this.mask.height);this.overlay.getContext('2d').putImageData(new ImageData(rgba,this.mask.width,this.mask.height),0,0);this.overlay.dataset.frame=frame;}
  tick(){if(!this.alive)return;if(!this.video.paused){this.renderMask();this.syncPlayer();}this.raf=requestAnimationFrame(()=>this.tick());}
  async uploadImage(file){if(this.uploading||this.busy)return;this.uploading=true;this.paint();try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('仅支持 JPEG、PNG、WebP 图片');if(file.size>10*1024*1024)throw Error('图片不能超过 10MB');const bitmap=await createImageBitmap(file);bitmap.close();const asset=await window.LocalAssets.put(file),preview=await window.LocalAssets.url(asset);if(this.alive)this.reference={url:asset,preview};}catch(e){if(this.alive)this.error(e.message);}finally{this.uploading=false;if(this.alive)this.paint();}}
  pickImage(){const d=el('dialog','video-mask-picker'),header=el('header');header.append(el('h2','','从画布选择主体'),button('关闭素材选择','cancel',()=>d.close()));const grid=el('div','video-mask-image-grid');for(const n of app.getState().nodes.filter(n=>n.type==='image'&&(n.fullImage||n.image))){const b=button(n.title||'image','',async()=>{try{const url=n.fullImage||n.image,preview=await window.LocalAssets.url(url);if(this.alive){this.reference={url,preview,nodeId:n.id};this.paint();}d.close();}catch(e){this.error(e.message);}}),img=el('img');window.LocalAssets.url(n.fullImage||n.image).then(url=>img.src=url).catch(()=>{});img.alt=n.title||'image';b.append(img,el('span','','选择'));grid.append(b);}if(!grid.childElementCount)grid.append(el('p','','画布暂无图片'));d.append(header,grid);document.body.append(d);d.onclose=()=>{d.remove();if(this.alive)this.pick.focus({preventScroll:true});};d.showModal();this.picker=d;}
  error(message){this.status.hidden=false;this.status.textContent=message;}
  async submit(){if(this.generate.disabled)return;this.busy=true;this.paint();this.video.pause();const id=this.id,source=this.source,clip=this.clip,mask=structuredClone(this.mask),maskAsset=this.maskAsset,ref=this.reference?{...this.reference}:null;try{const req=core.editRequest(this.node(),this.mode,await window.LocalAssets.url(source),mask,ref);if(window.GenerationAPI.isConfigured())for(const input of req.inputs)input.url=await transport(input.url);else for(const input of req.inputs)input.url=await window.LocalAssets.url(input.url);const guard=()=>{const n=app.getState().nodes.find(n=>n.id===id);if(!n||mediaSource(n)!==source||JSON.stringify(n.clip||null)!==clip||n.videoMask?.asset!==maskAsset)throw Error('来源视频或蒙层已变化，请重新生成');if(ref?.nodeId){const r=app.getState().nodes.find(n=>n.id===ref.nodeId);if(!r||(r.fullImage||r.image)!==ref.url)throw Error('替换素材已变化，请重新选择');}};await window.GenerationAPI.runInPlace(req,{guard,type:'video',apply:async output=>{guard();return app.createConnected(id,[{...output,video:output.video||output.url,image:output.poster,title:output.title||req.label}]);}});this.close();}catch(e){if(this.alive)this.error(e.message);else app.notify(e.message);}finally{this.busy=false;if(this.alive)this.paint();}}
  close(){if(!this.alive)return;this.alive=false;this.recognizing?.abort();this.listeners.abort();cancelAnimationFrame(this.fitFrame);cancelAnimationFrame(this.raf);this.video.pause();this.video.removeAttribute('src');this.video.load();this.picker?.close();this.root.remove();document.body.classList.remove('video-masking');if(current===this)current=null;app.render();}
}
export function open(node,mode='replace'){current?.close();window.NodeActions.close();window.NodeActions.closePop();app.select(node.id);current=new MaskEditor(node,mode==='erase'?'remove':mode);return current;}
