import {directions,modes,clampDuration,fitCreation,extendRequest,mediaSource,extensionSettings} from './core.mjs';
import {extensionRequestState} from './native-profile.mjs';
import {openSubjects} from '../../../subject-library.mjs';
const app=window.CanvasApp,icons=window.CANVAS_MENU_ICONS;
const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const button=(label,icon,fn,cls='')=>{const b=el('button',cls);b.type='button';b.setAttribute('aria-label',label);b.dataset.tooltip=label;b.innerHTML=icons[icon]||'';b.onclick=fn;return b;};
let current;
class Creation {
  constructor(node){
    this.sourceNode=node;this.projectId=app.projectIdentity().id;this.referenceNodes=new Map();this.id=node.id;this.source=mediaSource(node);this.sourceClip=JSON.stringify(node.clip||null);this.settings=extensionSettings(node);this.references=[];this.subjects=[];this.alive=true;this.listeners=new AbortController();
    this.root=el('section','video-creation');this.root.setAttribute('aria-label','视频创作 Beta');this.root.tabIndex=-1;
    const top=el('header','video-creation-top');this.subjectButton=button('添加主体','creationSubject',()=>this.pickSubjects(),'creation-subject');this.subjectButton.setAttribute('aria-haspopup','dialog');this.refs=el('div','creation-references');this.add=button('从画布选择参考','creationAdd',()=>this.selectReference(),'creation-add');const close=button('关闭视频创作','creationClose',()=>this.close(),'creation-close');top.append(this.subjectButton,el('i','creation-divider'),this.refs,this.add,close);
    this.promptWrap=el('div','creation-prompt-wrap');this.placeholder=el('div','creation-placeholder');this.promptMount=el('div');this.promptWrap.append(this.placeholder,this.promptMount);
    this.footer=el('footer','creation-footer');this.trigger=button('延长镜头','videoExtend',()=>this.toggleSettings(),'creation-settings-trigger');this.triggerText=el('span');this.trigger.append(this.triggerText);this.trigger.setAttribute('aria-haspopup','dialog');this.trigger.setAttribute('aria-expanded','false');const submitGroup=el('div','creation-submit-group'),cost=el('span','creation-cost');cost.innerHTML=icons.creationCost;cost.append(el('span','','—'));cost.title='由接入的生成服务返回用量';this.generate=button('确认并生成','creationGenerate',()=>this.submit(),'creation-generate');submitGroup.append(cost,this.generate);this.footer.append(this.trigger,submitGroup);
    this.status=el('p','creation-status');this.status.setAttribute('role','status');this.status.hidden=true;this.root.append(top,this.promptWrap,this.footer,this.status);document.body.append(this.root);document.body.classList.add('video-creation-active');
    this.editor=window.TextEditor.createPrompt({element:this.promptMount,onUpdate:(text,editor)=>{this.prompt=text;this.paintPlaceholder();this.suggest(editor);},onCursor:editor=>this.suggest(editor)});
    this.root.onpointerdown=e=>e.stopPropagation();this.root.onclick=e=>e.stopPropagation();this.root.onkeydown=e=>{if(e.key!=='Escape')e.stopPropagation();};
    const opts={signal:this.listeners.signal};document.addEventListener('keydown',e=>this.key(e),{...opts,capture:true});document.addEventListener('pointerdown',e=>{if(this.pop&&!this.pop.contains(e.target)&&!this.trigger.contains(e.target))this.closeSettings(false);if(this.mentions&&!this.mentions.contains(e.target)&&!this.promptWrap.contains(e.target))this.closeMentions();},opts);
    document.addEventListener('canvas:render',()=>{const n=this.node();if(!n||mediaSource(n)!==this.source||JSON.stringify(n.clip||null)!==this.sourceClip){this.close();return;}if(!this.selecting&&!app.getState().selected.includes(this.id)){this.close();return;}this.place();},opts);window.addEventListener('resize',()=>{this.fit(false);this.place();},opts);
    this.paint();this.fit(true);this.place();this.root.focus({preventScroll:true});if(!this.source)this.error('来源视频尚不可用，请先上传或生成视频');
  }
  node(){return app.projectIdentity().id===this.projectId&&app.getState().nodes.includes(this.sourceNode)?this.sourceNode:null;}
  async readiness(request){
    const hint='参考生成 · '+request.parameters.modelId+' · '+request.parameters.resolution+' · '+(request.parameters.generateAudio?'有声':'无声')+'；原片保留。';
    const available=await window.GenerationAPI.availability({request});
    if(available.configured!==true)return {ready:false,reason:available.reason||'延长镜头服务尚未配置',hint};
    const metadata=await window.GenerationAPI.configuration();
    return metadata?extensionRequestState(metadata,request):{ready:true,reason:'',hint};
  }
  async refreshReadiness(){
    const ticket=this.readinessTicket=(this.readinessTicket||0)+1;this.generate.disabled=true;
    try{const node=this.node();if(!node||!this.source)throw Error('来源视频尚不可用，请先上传或生成视频');const request=extendRequest(node,this.settings,this.references,this.subjects,this.editor?.getText()||'',this.source),state=await this.readiness(request);if(!this.alive||ticket!==this.readinessTicket)return;this.ready=state.ready;this.status.hidden=false;this.status.textContent=[this.operationError,state.reason,state.hint].filter(Boolean).join(' ');this.generate.disabled=!this.ready||this.busy;}catch(error){if(this.alive&&ticket===this.readinessTicket){this.ready=false;this.status.hidden=false;this.status.textContent=error.message;}}
  }
  fit(animated){
    cancelAnimationFrame(this.animation);const box=document.querySelector('#canvas').getBoundingClientRect(),n=this.node();if(!n)return;const to=fitCreation(n,box.width,box.height),from={...app.getState().view};
    if(!animated||matchMedia('(prefers-reduced-motion:reduce)').matches){app.setView(to);return;}
    const distance=Math.hypot(to.x-from.x,to.y-from.y),duration=Math.min(1500,Math.max(200,200+distance*.5+Math.abs(to.scale-from.scale)*600+200/Math.max(from.scale,.2))),start=performance.now();
    const frame=now=>{if(!this.alive)return;const t=Math.min(1,(now-start)/duration),p=1-(1-t)**3;app.setView({x:from.x+(to.x-from.x)*p,y:from.y+(to.y-from.y)*p,scale:from.scale+(to.scale-from.scale)*p});if(t<1)this.animation=requestAnimationFrame(frame);};this.animation=requestAnimationFrame(frame);
  }
  place(){if(!this.alive)return;const n=this.node();if(!n)return;const canvas=document.querySelector('#canvas').getBoundingClientRect(),{view}=app.getState(),w=Math.min(680,innerWidth-40);this.root.style.width=w+'px';this.root.style.left=canvas.left+(n.x+n.width/2)*view.scale+view.x-w/2+'px';this.root.style.top=canvas.top+(n.y+n.height)*view.scale+view.y+8+'px';if(this.pop)this.placeSettings();}
  paintPlaceholder(){this.placeholder.hidden=!!this.editor?.getText().trim();this.placeholder.replaceChildren(document.createTextNode(this.settings.direction==='片尾延长'?'接下来发生什么？输入 ':'此前发生了什么？输入 '),el('kbd','','@'),document.createTextNode(' 引用画布或主体素材'));}
  paint(){this.triggerText.replaceChildren(...[this.settings.direction,'·','自适应','·',this.settings.duration+'s','·',this.settings.mode].map((text,i)=>el('span',i===4?'creation-duration-summary':i%2?'creation-separator':'',text)));this.paintPlaceholder();this.generate.disabled=!this.source||this.busy||!this.ready;if(!this.busy)void this.refreshReadiness();this.subjectButton.disabled=this.add.disabled=this.references.length+this.subjects.length>=4||this.busy;this.refs.replaceChildren();for(const r of [...this.references,...this.subjects.map(s=>({id:s.id,title:s.name,type:'subject',image:s.assets.find(a=>a.image||a.type==='image')?.image||s.assets.find(a=>a.type==='image')?.url}))]){const chip=el('div','creation-reference');chip.dataset.referenceId=r.id;const use=button('引用 '+r.title,'',()=>this.insertReference(r));if(r.image){const img=el('img');img.alt=r.title;window.LocalAssets.url(r.image).then(url=>img.src=url).catch(()=>{});use.append(img);}else use.innerHTML=icons.creationSubject;const remove=button('移除 '+r.title,'creationClose',()=>{this.references=this.references.filter(x=>x.id!==r.id);this.subjects=this.subjects.filter(x=>x.id!==r.id);const positions=[];this.editor.state.doc.descendants((n,pos)=>{if(n.type.name==='promptReference'&&n.attrs.id===r.id)positions.push({from:pos,to:pos+n.nodeSize});});const chain=this.editor.chain();positions.reverse().forEach(p=>chain.deleteRange(p));chain.run();this.paint();},'creation-reference-remove');chip.append(use,remove);this.refs.append(chip);}}
  pickSubjects(){this.closeSettings(false);const d=openSubjects({selected:this.subjects.map(s=>s.id),limit:4-this.references.length,anchor:this.subjectButton,onChoose:items=>{const removed=this.subjects.filter(s=>!items.some(x=>x.id===s.id)).map(s=>s.id);this.subjects=items;const positions=[];this.editor.state.doc.descendants((n,pos)=>{if(n.type.name==='promptReference'&&removed.includes(n.attrs.id))positions.push({from:pos,to:pos+n.nodeSize});});const chain=this.editor.chain();positions.reverse().forEach(p=>chain.deleteRange(p));chain.run();this.paint();}});this.subjectButton.setAttribute('aria-expanded','true');d.addEventListener('close',()=>this.subjectButton.setAttribute('aria-expanded','false'),{once:true});}
  async addReference(n){if(!n||n.id===this.id||this.references.some(r=>r.id===n.id)||this.references.length+this.subjects.length>=4)return;const url=n.type==='video'?mediaSource(n):n.fullImage||n.image;if(!url)return;this.referenceNodes.set(n.id,n);this.references.push({id:n.id,title:n.title,type:n.type,url,image:n.image,...(n.clip?{clip:structuredClone(n.clip)}:{})});this.paint();}
  selectReference(){
    if(this.selecting){this.exitSelection();return;}this.closeSettings(false);this.closeMentions();cancelAnimationFrame(this.animation);this.selecting=true;document.body.classList.add('video-reference-selecting');this.selectionBar=el('aside','creation-selection-bar');this.selectionBar.append(el('span','','从画布选择参考'),button('退出','creationClose',()=>this.exitSelection()));document.body.append(this.selectionBar);
    for(const n of app.getState().nodes){if(n.id!==this.id&&['image','video'].includes(n.type)&&(n.type==='video'?mediaSource(n):n.fullImage||n.image))document.querySelector(`.node[data-id="${n.id}"]`)?.classList.add('creation-reference-target');}
    this.selectionController=new AbortController();const select=e=>{const target=e.target.closest('.creation-reference-target');if(!target)return;e.preventDefault();e.stopImmediatePropagation();if(e.type==='click'){const n=app.getState().nodes.find(n=>n.id===target.dataset.id);this.addReference(n);this.exitSelection();}};
    for(const type of ['pointerdown','pointerup','click','dblclick'])document.addEventListener(type,select,{capture:true,signal:this.selectionController.signal});
  }
  exitSelection(){this.selecting=false;this.selectionController?.abort();this.selectionBar?.remove();document.body.classList.remove('video-reference-selecting');document.querySelectorAll('.creation-reference-target').forEach(e=>e.classList.remove('creation-reference-target'));}
  closeSettings(focus=true){this.pop?.remove();this.pop=null;this.trigger.setAttribute('aria-expanded','false');if(focus&&this.alive)this.trigger.focus({preventScroll:true});}
  toggleSettings(){if(this.pop){this.closeSettings();return;}this.closeMentions();this.pop=el('section','creation-settings');this.pop.setAttribute('role','dialog');this.pop.setAttribute('aria-label','延长参数');this.pop.onpointerdown=e=>e.stopPropagation();this.pop.onclick=e=>e.stopPropagation();
    const group=(label,key,values)=>{const section=el('div','creation-setting-section');section.append(el('span','creation-setting-label',label));const row=el('div','creation-segments');row.setAttribute('role','group');row.setAttribute('aria-label',label);const selected=el('i','creation-segment-selection');row.append(selected);for(const value of values){const b=el('button','',value);b.type='button';b.dataset.value=value;b.setAttribute('aria-pressed',String(this.settings[key]===value));b.onclick=()=>{this.settings[key]=value;update();this.paint();};row.append(b);}const update=()=>{for(const b of row.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.value===this.settings[key]));const chosen=row.querySelector('[aria-pressed=true]');selected.style.left=chosen.offsetLeft+'px';selected.style.width=chosen.offsetWidth+'px';};section.append(row);this.pop.append(section);return update;};
    const updateDirection=group('延长镜头','direction',directions);
    const section=el('div','creation-setting-section');section.append(el('span','creation-setting-label','新增时长'));const line=el('div','creation-duration-line'),ruler=el('div','creation-duration-ruler'),mark=el('i','creation-segment-selection'),field=el('label','creation-duration-field'),input=el('input');input.type='text';input.inputMode='numeric';input.pattern='[0-9]*';input.setAttribute('aria-label','新增时长');input.value=this.settings.duration;field.append(input,el('span','','s'));ruler.append(mark);for(let v=4;v<=30;v++){const b=el('button','',v+'s');b.type='button';b.dataset.duration=v;b.setAttribute('aria-pressed',String(v===this.settings.duration));b.onclick=()=>set(v);ruler.append(b);}const set=value=>{this.settings.duration=clampDuration(value);input.value=this.settings.duration;for(const b of ruler.querySelectorAll('button'))b.setAttribute('aria-pressed',String(+b.dataset.duration===this.settings.duration));const chosen=ruler.querySelector('[aria-pressed=true]');mark.style.left=chosen.offsetLeft+'px';mark.style.width=chosen.offsetWidth+'px';ruler.scrollTo({left:chosen.offsetLeft-ruler.clientWidth/2+chosen.offsetWidth/2,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});this.paint();};input.onchange=input.onblur=()=>set(input.value);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();set(input.value);}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();set(clampDuration(input.value)+(e.key==='ArrowUp'?1:-1));}};ruler.onwheel=e=>{e.preventDefault();e.stopPropagation();ruler.scrollLeft+=e.deltaX||e.deltaY;};line.append(ruler,field);section.append(line);this.pop.append(section);const updateMode=group('延长方式','mode',modes);
    document.body.append(this.pop);this.trigger.setAttribute('aria-expanded','true');this.placeSettings();updateDirection();updateMode();set(this.settings.duration);this.pop.querySelector('button').focus({preventScroll:true});
    this.pop.onkeydown=e=>{if(e.key==='Escape')return;e.stopPropagation();if(!e.target.matches('button')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const buttons=[...e.target.parentElement.querySelectorAll('button')],i=buttons.indexOf(e.target);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length]?.focus({preventScroll:true});};
  }
  placeSettings(){const r=this.trigger.getBoundingClientRect(),w=this.pop.offsetWidth,h=this.pop.offsetHeight;this.pop.style.left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2))+'px';this.pop.style.top=(r.top-h-8>=8?r.top-h-8:Math.min(innerHeight-h-8,r.bottom+8))+'px';}
  async insertReference(r,range){let image=r.image;try{if(image?.startsWith('asset:'))image=await window.LocalAssets.url(image);}catch(e){this.error(e.message);return;}if(!this.alive)return;let chain=this.editor.chain().focus();if(range)chain=chain.deleteRange(range);chain.insertContent([{type:'promptReference',attrs:{id:r.id,label:r.title||r.name,kind:r.type||'subject',image:image||''}},{type:'text',text:' '}]).run();this.closeMentions();}
  suggest(editor){
    if(!this.alive||editor.view.composing||!editor.state.selection.empty)return this.closeMentions();const {from}=editor.state.selection,before=editor.state.doc.textBetween(Math.max(0,from-100),from,'\n','\uFFFC'),match=before.match(/@([^@\s]*)$/);if(!match)return this.closeMentions();
    const query=match[1].toLowerCase(),range={from:from-query.length-1,to:from};this.closeMentions();const items=[...this.references,...this.subjects.map(s=>({...s,title:s.name,type:'subject'})),...app.getState().nodes.filter(n=>n.id!==this.id&&['image','video'].includes(n.type)&&!this.references.some(r=>r.id===n.id)&&(n.type==='video'?mediaSource(n):n.fullImage||n.image))].filter(r=>(r.title||'').toLowerCase().includes(query)).slice(0,12);if(!items.length)return;
    this.mentions=el('div','creation-mentions');this.mentions.setAttribute('role','listbox');this.mentions.setAttribute('aria-label','引用素材');for(const r of items){const b=el('button','',r.title);b.type='button';b.setAttribute('role','option');b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{if(r.type!=='subject'&&!this.references.some(x=>x.id===r.id)){if(this.references.length+this.subjects.length>=4){this.error('最多添加 4 个参考素材或主体');return;}this.addReference(r);}this.insertReference(r,range);};this.mentions.append(b);}this.promptWrap.append(this.mentions);this.mentionIndex=0;this.markMention();
  }
  markMention(){[...this.mentions.children].forEach((b,i)=>b.setAttribute('aria-selected',String(i===this.mentionIndex)));}
  closeMentions(){this.mentions?.remove();this.mentions=null;}
  key(e){if(document.querySelector('.subject-library[open],.subject-editor[open],.subject-canvas-picker[open]'))return;if(this.mentions&&['ArrowUp','ArrowDown','Enter'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(e.key==='Enter')this.mentions.children[this.mentionIndex].click();else{this.mentionIndex=(this.mentionIndex+(e.key==='ArrowDown'?1:-1)+this.mentions.children.length)%this.mentions.children.length;this.markMention();}return;}if(e.key!=='Escape')return;e.preventDefault();e.stopImmediatePropagation();if(this.mentions)this.closeMentions();else if(this.pop)this.closeSettings();else if(this.selecting)this.exitSelection();else this.close();}
  error(message){this.operationError=message;this.status.hidden=false;this.status.textContent=message;}
  async submit(){if(this.busy||!this.source)return;this.closeSettings(false);this.closeMentions();this.busy=true;this.paint();const source=this.source,clip=this.sourceClip,id=this.id,settings={...this.settings},refs=structuredClone(this.references),refNodes=new Map(this.referenceNodes),subjects=structuredClone(this.subjects),node=this.node();
    try{this.operationError='';const request=extendRequest(node,settings,refs,subjects,this.editor.getText({blockSeparator:'\n'}),source);
      const guard=()=>{const n=app.getState().nodes.find(n=>n.id===id);if(app.projectIdentity().id!==this.projectId||n!==this.sourceNode||mediaSource(n)!==source||JSON.stringify(n.clip||null)!==clip)throw Error('来源视频已变化，请重新生成');for(const r of refs){const n=app.getState().nodes.find(n=>n.id===r.id),url=n?.type==='video'?mediaSource(n):n?.fullImage||n?.image;if(n!==refNodes.get(r.id)||url!==r.url||JSON.stringify(n.clip||null)!==JSON.stringify(r.clip||null))throw Error('参考素材已变化，请重新生成');}};
      guard();const state=await this.readiness(request);guard();if(!state.ready)throw Error(state.reason);
      await window.GenerationAPI.runInPlace(request,{type:'video',guard,apply:async output=>{guard();const prepend=settings.direction==='片头延长';return app.createConnected(id,[{...output,video:output.video||output.url,image:output.poster,title:output.title||settings.direction}],{side:prepend?'left':'right',reverse:prepend});}});this.close();
    }catch(e){if(this.alive)this.error(e.message);else app.notify(e.message);}finally{this.busy=false;if(this.alive)this.paint();}
  }
  close(){if(!this.alive)return;this.alive=false;cancelAnimationFrame(this.animation);this.listeners.abort();this.exitSelection();this.closeSettings(false);this.closeMentions();this.editor.destroy();this.root.remove();document.body.classList.remove('video-creation-active');if(current===this)current=null;app.render();}
}
export function openExtend(node){if(current?.id===node.id){current.close();return;}current?.close();window.NodeActions.close();window.NodeActions.closePop();app.select(node.id);current=new Creation(node);return current;}
