import {renderAppDetail} from './app-detail.mjs';
import {renderAppMarkdown} from './app-detail-content.mjs';
import {readBuiltinSkillDetail} from '../agent-skills/detail.mjs';
import {resolveSkillFile,skillFrontmatter} from './skill-package.mjs';
import {managerIcons} from './icons.mjs';
import {appCatalog} from './catalog.mjs';
import {validateSkill} from './model.mjs';
import {getSkillIcon} from '../agent-attachments/skill-icons.mjs';
import {icons} from '../agent-attachments/icons.mjs';
import {referenceIcons} from '../agent-composer/reference-icons.mjs';
import {bindTooltip} from '../agent-composer/tooltip.mjs';
const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./styles.css',import.meta.url);document.head.append(css);
const el=(tag,cls='',text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
import {appRegistry} from './registry.mjs';
export {configureAppAdapter,availableApps} from './registry.mjs';
export async function openManager({tab='skills',initialCreate=false,getSkills,getCustom,saveCustom,getDisabled,setDisabled,onSkill,onApp,onImport,sanitize}){
 document.querySelector('#skill-manager')?.close();const dialog=el('dialog','agent-manager');dialog.id='skill-manager';let query='',list=[],view=0,menus=[],tips=[],guard=null,navigationPending=false;
 const returnFocus=document.activeElement;document.body.append(dialog);dialog.showModal();
 function closeDialog(){if(dialog.dataset.closing)return;dialog.dataset.closing='true';dialog.inert=true;const anim=dialog.animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.98)'}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:200,fill:'forwards'});anim.finished.finally(()=>dialog.close());}
 async function requestNavigation(action){if(navigationPending||dialog.dataset.closing||!dialog.isConnected)return;navigationPending=true;try{if(!guard||!guard()||await confirmAction('放弃更改？','未保存的更改将会丢失。','放弃'))action();}finally{navigationPending=false;}}
 function confirmAction(title,description,label){return new Promise(resolve=>{const modal=el('dialog','manager-confirm');modal.role='alertdialog';modal.ariaLabel=title;modal.append(el('h2','',title),el('p','',description));const footer=el('footer');footer.append(textButton('取消',()=>{modal.close();},'manager-secondary'),textButton(label,()=>{resolve(true);modal.close();},'manager-danger'));modal.append(footer);document.body.append(modal);modal.onclose=()=>{modal.remove();resolve(false);};modal.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();modal.close();}};modal.showModal();});}
 function dispose(){menus.forEach(m=>{m.trigger?.setAttribute('aria-expanded','false');m.remove();});menus=[];tips.forEach(t=>t.destroy());tips=[];}
 const changed=()=>{if(dialog.isConnected)renderList();},importError=e=>notice(e.detail),importNotice=e=>notice(e.detail);window.addEventListener('agent-skill-import-error',importError);window.addEventListener('agent-skill-import-notice',importNotice);window.addEventListener('agent-skills-changed',changed);
 dialog.oncancel=e=>{e.preventDefault();requestNavigation(()=>closeDialog());};
 dialog.onclose=()=>{window.removeEventListener('agent-skill-import-error',importError);window.removeEventListener('agent-skill-import-notice',importNotice);window.removeEventListener('agent-skills-changed',changed);view++;dispose();dialog.remove();if(returnFocus?.isConnected)returnFocus.focus();};
 dialog.onkeydown=e=>{e.stopPropagation();};dialog.onpointerdown=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)requestNavigation(()=>closeDialog());}};
 function button(label,action,cls='',icon){const b=el('button',cls);b.type='button';b.ariaLabel=label;if(icon)b.innerHTML=icon;b.onclick=()=>{try{Promise.resolve(action()).catch(error=>notice(error.message));}catch(error){notice(error.message);}};return b;}
 function textButton(label,action,cls=''){const b=button(label,action,cls);b.textContent=label;return b;}
 function notice(message){dialog.querySelector('.manager-notice')?.remove();const p=el('p','manager-notice',message);p.role='alert';dialog.append(p);}
 function reset(title,back=false){guard=null;view++;dispose();dialog.replaceChildren();dialog.ariaLabel=title;const header=el('header','manager-header');if(back){const b=button('返回',()=>requestNavigation(renderList),'manager-back',referenceIcons.back);b.append(el('span','','返回'));header.append(b);}else{const tabs=el('div','manager-tabs');tabs.role='tablist';tabs.ariaLabel='技能';for(const [key,label]of [['apps','应用'],['skills','技能']]){const b=textButton(label,()=>{tab=key;query='';renderList();},'');b.role='tab';b.setAttribute('aria-selected',String(tab===key));b.tabIndex=tab===key?0:-1;b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();tab=key==='apps'?'skills':'apps';query='';renderList();dialog.querySelector('[aria-selected=true]').focus();}};tabs.append(b);}header.append(tabs);}header.append(button('关闭',()=>requestNavigation(()=>closeDialog()),'manager-close',managerIcons.close));dialog.append(header);const heading=el('h2','manager-sr-only',title);dialog.append(heading);}
 function artwork(item,skill=false){const a=el('span','manager-artwork');if(skill)a.innerHTML=getSkillIcon(item.name,item.custom);else{const img=el('img');img.src=item.icon;img.alt=item.name;a.append(img);}return a;}
 function card(item,skill=false){const body=button(item.name,()=>skill?skillDetail(item):appDetail(item),'manager-card-main'),top=el('div','manager-card-top'),labels=el('div','manager-card-labels');labels.append(el('p','manager-name',item.name),el('p','manager-author',skill?(item.custom?'个人':'TapNow'):item.author));top.append(artwork(item,skill),labels);body.append(top,el('p','manager-description',item.description||''));if(skill){body.classList.add('manager-card');if(getDisabled().includes(item.name))body.dataset.disabled='true';else{const check=el('span','manager-skill-enabled');check.innerHTML=managerIcons.check;top.append(check);}return body;}const card=el('article','manager-card');card.append(body);const state=appRegistry.state(item.id);if(!state.installed){card.append(button('安装应用',async()=>{await appRegistry.install(item.id);renderRows();},'manager-install',managerIcons.plus));}else{const check=el('span','manager-installed');check.innerHTML=managerIcons.check;card.append(check);}return card;}
 let grid;
 function renderRows(){grid.replaceChildren();const items=tab==='apps'?appCatalog:[...list,...getCustom()];for(const item of items.filter(i=>(i.name+' '+(i.description||'')).toLowerCase().includes(query.toLowerCase())))grid.append(card(item,tab==='skills'));if(!grid.children.length)grid.append(el('p','manager-empty','暂无结果'));}
 function renderList(){reset(tab==='apps'?'管理应用':'管理技能');const controls=el('div','manager-controls'),search=el('label','manager-search');search.innerHTML=icons.search;const input=el('input');input.placeholder=input.ariaLabel='搜索';input.autocomplete='off';input.spellcheck=false;input.value=query;input.oninput=()=>{query=input.value;renderRows();};search.append(input);controls.append(search);if(tab==='skills'){const add=button('添加',()=>addMenu(add),'manager-add',managerIcons.plus);add.append(el('span','','添加'));add.setAttribute('aria-haspopup','menu');controls.append(add);}dialog.append(controls);grid=el('div','manager-grid');dialog.append(grid);renderRows();}
 function addMenu(trigger){const existing=menus.find(menu=>menu.isConnected&&menu.trigger===trigger);dispose();if(existing)return;const menu=el('div','manager-add-menu');menu.role='menu';menu.ariaLabel='添加';menu.trigger=trigger;trigger.setAttribute('aria-expanded','true');const actions=[['创建技能',()=>editSkill(),icons['创建技能']],['上传技能文件',()=>importSkills('skill-file'),icons['上传技能文件']],['上传技能文件夹',()=>importSkills('skill-folder'),icons['上传技能文件夹']]];for(const [label,action,icon]of actions){const b=el('div');b.role='menuitem';b.tabIndex=-1;if(icon)b.innerHTML=icon;b.append(el('span','',label));const invoke=()=>{menu.remove();trigger.setAttribute('aria-expanded','false');try{Promise.resolve(action()).catch(error=>notice(error.message));}catch(error){notice(error.message);}};b.onclick=invoke;b.onkeydown=e=>{if(e.target===b&&['Enter',' '].includes(e.key)){e.preventDefault();invoke();}};b.onpointerenter=()=>b.focus({preventScroll:true});const hint=label==='上传技能文件'?'上传 Markdown 技能文件（.md 或 .markdown），例如 SKILL.md。':label==='上传技能文件夹'?'上传包含 Markdown 文件的技能文件夹，例如 SKILL.md 和相关参考文件。':null;if(hint){const help=button(hint,()=>{},'manager-help',icons.info);help.onclick=e=>e.stopPropagation();tips.push(bindTooltip(help,{text:()=>hint}));b.append(help);}menu.append(b);}dialog.append(menu);menus.push(menu);const r=trigger.getBoundingClientRect(),d=dialog.getBoundingClientRect();menu.style.top=(r.bottom-d.top+4)+'px';menu.style.right='24px';menu.querySelector('[role=menuitem]').focus();menu.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();menu.remove();trigger.focus();trigger.setAttribute('aria-expanded','false');}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const buttons=[...menu.querySelectorAll('[role=menuitem]')],i=buttons.indexOf(document.activeElement);buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus();}};menu.addEventListener('focusout',()=>queueMicrotask(()=>{if(!menu.contains(document.activeElement)&&document.activeElement!==trigger){menu.remove();trigger.setAttribute('aria-expanded','false');}}));}
 async function importSkills(action){await onImport(action);}
 function toggle(checked,label,onChange){const b=button(label,()=>{onChange(!checked);checked=!checked;b.setAttribute('aria-checked',String(checked));},'manager-switch');b.role='switch';b.setAttribute('aria-checked',String(checked));b.append(el('span'));return b;}
 async function skillDetail(skill){reset(skill.name,true);const token=view,body=el('div','manager-detail'),intro=el('div','manager-intro'),line=el('div','manager-detail-title');line.append(el('p','',skill.name),el('small','',skill.custom?'个人':'TapNow'),toggle(!getDisabled().includes(skill.name),'启用 '+skill.name,checked=>{const values=getDisabled().filter(n=>n!==skill.name);if(!checked)values.push(skill.name);setDisabled(values);}));intro.append(line,el('p','manager-detail-description',skill.description));body.append(intro);const article=el('article','manager-article');body.append(article);dialog.append(body);if(skill.custom){const {renderSkillMarkdown}=await import('/assets/agent-editor.js');if(view!==token)return;let filePath=skill.entryPath||'SKILL.md';const show=text=>{article.innerHTML=renderSkillMarkdown(text);};show(skill.text);article.onclick=event=>{const link=event.target.closest('[data-skill-link]');if(!link)return;event.preventDefault();try{const file=resolveSkillFile(skill,filePath,link.dataset.skillLink);filePath=file.path;show(skillFrontmatter(file.content).body);const back=textButton('返回技能正文',()=>{filePath=skill.entryPath||'SKILL.md';show(skill.text);},'manager-reference-back');article.prepend(back,el('p','manager-reference-path',file.path));}catch(error){notice(error.message);}};}else{article.textContent='加载中…';try{const data=await readBuiltinSkillDetail(skill.name);if(!dialog.isConnected||view!==token)return;if(data.sourceFormat==='captured-article-html')article.replaceChildren(sanitize(data.content));else{article.style.whiteSpace='pre-wrap';article.style.overflowWrap='anywhere';article.textContent=data.content;}}catch(e){if(view===token)article.textContent=e.message;}}
 if(view!==token)return;const footer=el('footer','manager-footer');if(skill.custom){footer.append(textButton('卸载',async()=>{if(await confirmAction('卸载技能？','该技能将从你的个人技能中移除，此操作无法撤销。','卸载')){await saveCustom(getCustom().filter(s=>s.name!==skill.name),{oldName:skill.name,newName:null,previous:skill});renderList();}},'manager-uninstall'),textButton('编辑技能',()=>editSkill(skill),'manager-secondary'));}footer.append(textButton('在对话中使用',async()=>{await onSkill(skill.name);dialog.close();},'manager-primary'));dialog.append(footer);}
 function editSkill(existing){reset(existing?'编辑技能':'创建技能',true);if(initialCreate){dialog.classList.add('manager-standalone');dialog.querySelector('.manager-back')?.remove();}const form=el('form','manager-form'),title=el('div','manager-form-title');title.append(el('p','',existing?'编辑技能':'创建技能'),el('span','','个人'));form.append(title);const fields={};for(const [key,label,placeholder,hint]of [['name','技能名称','输入名称','只允许小写字母、数字和连字符'],['description','描述','输入描述','Agent 会根据这些描述决定在对话中使用哪些技能。'],['text','指令','输入指令']]){const group=el('label','manager-field'),caption=el('span','manager-field-label',label);if(hint){const help=button(hint,()=>{},'manager-help',icons.info);tips.push(bindTooltip(help,{text:()=>hint}));caption.append(help);}const input=el(key==='name'?'input':'textarea');input.ariaLabel=label;input.placeholder=placeholder;input.value=existing?.[key]||'';input.dataset.field=key;fields[key]=input;group.append(caption,input);form.append(group);}const footer=el('footer','manager-footer'),cancel=textButton('取消',()=>requestNavigation(initialCreate?closeDialog:renderList),'manager-secondary'),save=textButton(existing?'保存':'创建',async()=>{const skill=validateSkill(Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])),[...list,...getCustom()],existing?.name);const updated={...existing,...skill};if(existing?.files)updated.files=existing.files.map(file=>file.path===existing.entryPath?{...file,content:'---\nname: '+skill.name+'\ndescription: '+JSON.stringify(skill.description)+'\n---\n'+skill.text}:file);await saveCustom([...getCustom().filter(s=>s.name!==existing?.name),updated],existing?{oldName:existing.name,newName:skill.name,previous:existing}:null);guard=null;if(initialCreate)closeDialog();else renderList();},'manager-primary');footer.append(cancel,save);form.append(footer);const isDirty=()=>Object.entries(fields).some(([k,v])=>v.value!==(existing?.[k]||''));guard=isDirty;const validate=()=>{const dirty=isDirty();cancel.disabled=!dirty;save.disabled=existing?!dirty:!Object.values(fields).some(f=>f.value.trim());};Object.values(fields).forEach(f=>f.oninput=validate);form.onsubmit=e=>{e.preventDefault();save.click();};dialog.append(form);validate();fields.name.focus();}
 function appDetail(app){
  reset(app.name,true);const token=view,current=()=>dialog.isConnected&&view===token;
  const {body,footer,description}=renderAppDetail({app,state:appRegistry.state(app.id),artwork,
   toggle:(enabled,label)=>toggle(enabled,label,value=>appRegistry.enable(app.id,value)),
   onUse:async text=>{if(!app.external&&appRegistry.state(app.id).enabled===false)appRegistry.enable(app.id,true);await onApp(app,text??app.examples?.[0]??'');if(current())dialog.close();},
   onInstall:async()=>{await appRegistry.install(app.id);if(current())appDetail(app);},
   onUninstall:async()=>{if(!await confirmAction('卸载应用？','该应用将从你的工作区移除，之后可以重新安装。','卸载')||!current())return;await appRegistry.uninstall(app.id);if(current())appDetail(app);},
   onError:message=>{if(current())notice(message);}
  });dialog.append(body,footer);
  if(app.publicContent??app.description)import('/assets/agent-editor.js').then(({renderSkillMarkdown})=>{
   if(current())renderAppMarkdown(description,app.publicContent??app.description,renderSkillMarkdown);
  }).catch(()=>{if(current())notice('应用介绍格式加载失败，已保留文字内容。');});
 }

 reset('加载中');try{list=await getSkills();if(dialog.isConnected){if(initialCreate)editSkill();else renderList();}}catch(error){notice(error.message);}
 return {close:()=>requestNavigation(closeDialog)};
}
