import {createGenerationCard} from '../../agent-generation/card.mjs';
const localFixture=new URL(location.href).searchParams.get('fixture')==='local-contract';document.querySelector('#fixture-note').hidden=!localFixture;
document.querySelector('#catalog-note').textContent=localFixture?'当前端口是本地合同fixture：目录来自隔离服务的受控记录，试听为真实WAV字节；并非ElevenLabs或其他供应商成功。前端没有额外注入Key，不改主画布/会话存储。':'目录与试听使用本机真实供应商路由；无配置必须显示未配置。此QA不注入供应商样例或浏览器Key，节点和卡片在内存中。';
const audit=[],log=(event,data={})=>{audit.push({at:new Date().toISOString(),event,...data});document.querySelector('#audit').textContent=JSON.stringify(audit,null,2);};
const NativeAudio=window.Audio;let audioSequence=0;
window.Audio=class QAVisibleNativeAudio extends NativeAudio{
 constructor(...args){super(...args);const audioId='native-audio-'+(++audioSequence),figure=document.createElement('figure'),caption=document.createElement('figcaption');caption.textContent='原生音频 '+audioSequence;this.controls=true;this.dataset.qaAudioId=audioId;figure.append(caption,this);document.querySelector('#native-audio').append(figure);
  for(const event of ['loadedmetadata','playing','timeupdate','ended','pause','error'])this.addEventListener(event,()=>log('native-audio-'+event,{audioId,duration:Number.isFinite(this.duration)?this.duration:null,currentTime:this.currentTime,paused:this.paused,ended:this.ended,readyState:this.readyState,errorCode:this.error?.code}));
 }
 removeAttribute(name){super.removeAttribute(name);if(String(name).toLowerCase()==='src'){const figure=this.closest('figure');if(figure)figure.hidden=true;log('native-audio-released',{audioId:this.dataset.qaAudioId,currentTime:this.currentTime});}}
};
const nativeFetch=window.fetch.bind(window);window.fetch=async(input,options={})=>{const url=String(input);if(!url.startsWith('/api/generation/voices'))return nativeFetch(input,options);log('voice-request',{url});try{const response=await nativeFetch(input,options);log('voice-response',{url,status:response.status,type:response.headers.get('content-type')});return response;}catch(error){log('voice-request-ended',{url,name:error.name});throw error;}};
const nodes=['voice-qa-a','voice-qa-b'].map((id,index)=>({id,type:'audio',title:'音色QA '+(index+1),x:0,y:0,width:300,height:180,audioConfig:window.AudioCore.transition({prompt:'请核对所选真实音色。'},'elevenlabs-v3','Text-to-Speech')})),state={nodes,selected:[nodes[0].id],edges:[],view:{x:0,y:0,scale:1}};
Object.assign(window,{CanvasApp:{getState:()=>state,getNodeElement:()=>null,updateNode(id,patch){Object.assign(nodes.find(node=>node.id===id),patch);log('node-config',{nodeId:id,voiceId:patch.audioConfig?.params?.voice_id});document.dispatchEvent(new Event('canvas:render'));},disconnect(){},saveSelection(){}},NodeActions:{notify:message=>log('notice',{message}),colors(){}},GenerationAPI:{getJobs:()=>[],subscribe(){},submit(){throw Error('此QA仅核对请求，不派发生成');}},VoiceInput:{bind(){}},LocalAssets:{url:async value=>value}});
const script=document.createElement('script');script.src='/audio-ui.js';document.body.append(script);await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=reject;});document.querySelector('#canvas').append(document.querySelector('.audio-editor'));
const trace={id:'voice-qa-trace',callId:'voice-qa-call',status:'pending',args:{kind:'audio.generate',model:'elevenlabs',audioScene:'Text-to-Speech',nodeId:nodes[0].id,prompt:'请核对所选真实音色。'}},mount=()=>createGenerationCard(trace,{getNodes:()=>nodes,getConfig:id=>nodes.find(n=>n.id===id)?.audioConfig||{},onConfirm:(trace,allowed,args)=>log('card-confirm',{allowed,voiceId:args?.voice}),onChange:trace=>log('card-draft',{voiceId:trace.confirmationDraft?.voice})});let card=mount();document.querySelector('#card').append(card.element);
document.querySelector('#request').onclick=async()=>{try{const node=await window.AudioAPI.buildRequest(state.selected[0]),agent=await window.AudioAPI.buildRequest(nodes[0].id,trace.confirmationDraft||trace.args);log('real-request-parameters',{nodeVoiceId:node.parameters.voice_id,agentVoiceId:agent.parameters.voice_id,nodeModel:node.parameters.model,agentModel:agent.parameters.model});}catch(error){log('request-error',{message:error.message});}};
document.querySelector('#switch').onclick=()=>{state.selected=[state.selected[0]===nodes[0].id?nodes[1].id:nodes[0].id];document.dispatchEvent(new Event('canvas:render'));log('selected-node',{nodeId:state.selected[0]});};
document.querySelector('#card-toggle').onclick=()=>{if(card){card.destroy();card=null;log('card-destroy');}else{card=mount();document.querySelector('#card').append(card.element);log('card-recreate');}};
window.voiceCatalogQA={audit,state,trace};log('ready',{catalog:'/api/generation/voices?model=eleven_v3',supplierFixtures:localFixture});
